**!!! WAJIB PAKAI GPU !!!**

# **IMPORT LIBRARY**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

In [ ]:
import pickle, tqdm, time,json
import pandas as pd
import numpy as np
import cupy as cp
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.model_selection import StratifiedKFold, GridSearchCV, KFold
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
# from sklearn.neighbors import BallTree, KDTree
import matplotlib.pyplot as plt

# **LOADING DATASET**

### DATA data_with_lk

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk/train_dataset_balanced.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk/test_dataset_balanced.csv', index_col=False)

### DATA data_with_lk @500

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/train_dataset.csv', index_col=False)

### DATA data_no_lk

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk/test_dataset.csv', index_col=False)

### DATA data_no_lk @500

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@500/test_dataset.csv', index_col=False)

### DATA data_no_lk @1000

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@1000/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@1000/test_dataset.csv', index_col=False)

### DATA PMR unbalanced 360 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### DATA positive unbalanced 344 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### DATA @500 110 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_test.csv', index_col=False)

### DATA @1000 55 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_test.csv', index_col=False)

### DATA Top 10 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_test.csv', index_col=False)

# PREPROCESSING

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/feature_dictionary.json', 'r') as json_file:
    feature_dictionary = json.load(json_file)

## ALL FEATURES

In [ ]:
train_data353 = train_df[feature_dictionary['all'] + ['tp_ICD_cl0']]
test_data353 = test_df[feature_dictionary['all'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_all.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data353.columns if x.startswith('n_')]

train_data353[num_cols] = scaler.transform(train_data353[num_cols])
test_data353[num_cols] = scaler.transform(test_data353[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_all.pkl', 'rb') as file:
    le = pickle.load(file)

train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])
test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

## 150 FEATURES

In [ ]:
train_data150 = train_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]
test_data150 = test_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_150.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data150.columns if x.startswith('n_')]

train_data150[num_cols] = scaler.transform(train_data150[num_cols])
test_data150[num_cols] = scaler.transform(test_data150[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_150.pkl', 'rb') as file:
    le = pickle.load(file)

train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])
test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

## 140 FEATURES

In [ ]:
train_data140 = train_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]
test_data140 = test_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_140.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data140.columns if x.startswith('n_')]

train_data140[num_cols] = scaler.transform(train_data140[num_cols])
test_data140[num_cols] = scaler.transform(test_data140[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_140.pkl', 'rb') as file:
    le = pickle.load(file)

train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])
test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

## 130 FEATURES

In [ ]:
train_data130 = train_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]
test_data130 = test_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_130.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data130.columns if x.startswith('n_')]

train_data130[num_cols] = scaler.transform(train_data130[num_cols])
test_data130[num_cols] = scaler.transform(test_data130[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_130.pkl', 'rb') as file:
    le = pickle.load(file)

train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])
test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

## 120 FEATURES

In [ ]:
train_data120 = train_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]
test_data120 = test_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_120.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data120.columns if x.startswith('n_')]

train_data120[num_cols] = scaler.transform(train_data120[num_cols])
test_data120[num_cols] = scaler.transform(test_data120[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_120.pkl', 'rb') as file:
    le = pickle.load(file)

train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])
test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

## 110 FEATURES

In [ ]:
train_data110 = train_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]
test_data110 = test_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_110.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data110.columns if x.startswith('n_')]

train_data110[num_cols] = scaler.transform(train_data110[num_cols])
test_data110[num_cols] = scaler.transform(test_data110[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_110.pkl', 'rb') as file:
    le = pickle.load(file)

train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])
test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

## 100 FEATURES

In [ ]:
train_data100 = train_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]
test_data100 = test_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_100.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data100.columns if x.startswith('n_')]

train_data100[num_cols] = scaler.transform(train_data100[num_cols])
test_data100[num_cols] = scaler.transform(test_data100[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_100.pkl', 'rb') as file:
    le = pickle.load(file)

train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])
test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

## 90 FEATURES

In [ ]:
train_data90 = train_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]
test_data90 = test_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_90.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data90.columns if x.startswith('n_')]

train_data90[num_cols] = scaler.transform(train_data90[num_cols])
test_data90[num_cols] = scaler.transform(test_data90[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_90.pkl', 'rb') as file:
    le = pickle.load(file)

train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])
test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

## 80 FEATURES

In [ ]:
train_data80 = train_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]
test_data80 = test_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_80.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data80.columns if x.startswith('n_')]

train_data80[num_cols] = scaler.transform(train_data80[num_cols])
test_data80[num_cols] = scaler.transform(test_data80[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_80.pkl', 'rb') as file:
    le = pickle.load(file)

train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])
test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

## 70 FEATURES

In [ ]:
train_data70 = train_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]
test_data70 = test_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_70.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data70.columns if x.startswith('n_')]

train_data70[num_cols] = scaler.transform(train_data70[num_cols])
test_data70[num_cols] = scaler.transform(test_data70[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_70.pkl', 'rb') as file:
    le = pickle.load(file)

train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])
test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

## 60 FEATURES

In [ ]:
train_data60 = train_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]
test_data60 = test_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_60.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data60.columns if x.startswith('n_')]

train_data60[num_cols] = scaler.transform(train_data60[num_cols])
test_data60[num_cols] = scaler.transform(test_data60[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_60.pkl', 'rb') as file:
    le = pickle.load(file)

train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])
test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

## 50 FEATURES

In [ ]:
train_data50 = train_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]
test_data50 = test_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_50.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data50.columns if x.startswith('n_')]

train_data50[num_cols] = scaler.transform(train_data50[num_cols])
test_data50[num_cols] = scaler.transform(test_data50[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_50.pkl', 'rb') as file:
    le = pickle.load(file)

train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])
test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

## 40 FEATURES

In [ ]:
train_data40 = train_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]
test_data40 = test_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_40.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data40.columns if x.startswith('n_')]

train_data40[num_cols] = scaler.transform(train_data40[num_cols])
test_data40[num_cols] = scaler.transform(test_data40[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_40.pkl', 'rb') as file:
    le = pickle.load(file)

train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])
test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

## 30 FEATURES

In [ ]:
train_data30 = train_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]
test_data30 = test_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_30.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data30.columns if x.startswith('n_')]

train_data30[num_cols] = scaler.transform(train_data30[num_cols])
test_data30[num_cols] = scaler.transform(test_data30[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_30.pkl', 'rb') as file:
    le = pickle.load(file)

train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])
test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

## 20 FEATURES

In [ ]:
train_data20 = train_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]
test_data20 = test_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_20.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data20.columns if x.startswith('n_')]

train_data20[num_cols] = scaler.transform(train_data20[num_cols])
test_data20[num_cols] = scaler.transform(test_data20[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_20.pkl', 'rb') as file:
    le = pickle.load(file)

train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])
test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

## 10 FEATURES

In [ ]:
train_data10 = train_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]
test_data10 = test_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_10.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data10.columns if x.startswith('n_')]

train_data10[num_cols] = scaler.transform(train_data10[num_cols])
test_data10[num_cols] = scaler.transform(test_data10[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_10.pkl', 'rb') as file:
    le = pickle.load(file)

train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])
test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

## 5 FEATURES

In [ ]:
train_data5 = train_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]
test_data5 = test_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_5.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data5.columns if x.startswith('n_')]

train_data5[num_cols] = scaler.transform(train_data5[num_cols])
test_data5[num_cols] = scaler.transform(test_data5[num_cols])

In [ ]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_5.pkl', 'rb') as file:
    le = pickle.load(file)

train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])
test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

# SPLIT DISTANCE

In [ ]:
def find_range_for_prefix(lst, prefix):
    first_index = None
    last_index = None

    # Find first index
    for i, item in enumerate(lst):
        if item.startswith(prefix):
            first_index = i
            break

    # Find last index
    for i in range(len(lst) - 1, -1, -1):
        if lst[i].startswith(prefix):
            last_index = i
            break

    return first_index, last_index

In [ ]:
column5 = sorted(train_data5.columns)
train_data5 = train_data5[column5]
test_data5 = test_data5[column5]

first_c5, last_c5 = find_range_for_prefix(column5, prefix='c')
first_n5, last_n5 = find_range_for_prefix(column5, prefix='n')
first_o5, last_o5 = find_range_for_prefix(column5, prefix='o')

In [ ]:
column10 = sorted(train_data10.columns)
train_data10 = train_data10[column10]
test_data10 = test_data10[column10]

first_c10, last_c10 = find_range_for_prefix(column10, prefix='c')
first_n10, last_n10 = find_range_for_prefix(column10, prefix='n')
first_o10, last_o10 = find_range_for_prefix(column10, prefix='o')

In [ ]:
column20 = sorted(train_data20.columns)
train_data20 = train_data20[column20]
test_data20 = test_data20[column20]

first_c20, last_c20 = find_range_for_prefix(column20, prefix='c')
first_n20, last_n20 = find_range_for_prefix(column20, prefix='n')
first_o20, last_o20 = find_range_for_prefix(column20, prefix='o')

In [ ]:
column30 = sorted(train_data30.columns)
train_data30 = train_data30[column30]
test_data30 = test_data30[column30]

first_c30, last_c30 = find_range_for_prefix(column30, prefix='c')
first_n30, last_n30 = find_range_for_prefix(column30, prefix='n')
first_o30, last_o30 = find_range_for_prefix(column30, prefix='o')

In [ ]:
column40 = sorted(train_data40.columns)
train_data40 = train_data40[column40]
test_data40 = test_data40[column40]

first_c40, last_c40 = find_range_for_prefix(column40, prefix='c')
first_n40, last_n40 = find_range_for_prefix(column40, prefix='n')
first_o40, last_o40 = find_range_for_prefix(column40, prefix='o')

In [ ]:
column50 = sorted(train_data50.columns)
train_data50 = train_data50[column50]
test_data50 = test_data50[column50]

first_c50, last_c50 = find_range_for_prefix(column50, prefix='c')
first_n50, last_n50 = find_range_for_prefix(column50, prefix='n')
first_o50, last_o50 = find_range_for_prefix(column50, prefix='o')

In [ ]:
column60 = sorted(train_data60.columns)
train_data60 = train_data60[column60]
test_data60 = test_data60[column60]

first_c60, last_c60 = find_range_for_prefix(column60, prefix='c')
first_n60, last_n60 = find_range_for_prefix(column60, prefix='n')
first_o60, last_o60 = find_range_for_prefix(column60, prefix='o')

In [ ]:
column70 = sorted(train_data70.columns)
train_data70 = train_data70[column70]
test_data70 = test_data70[column70]

first_c70, last_c70 = find_range_for_prefix(column70, prefix='c')
first_n70, last_n70 = find_range_for_prefix(column70, prefix='n')
first_o70, last_o70 = find_range_for_prefix(column70, prefix='o')

In [ ]:
column80 = sorted(train_data80.columns)
train_data80 = train_data80[column80]
test_data80 = test_data80[column80]

first_c80, last_c80 = find_range_for_prefix(column80, prefix='c')
first_n80, last_n80 = find_range_for_prefix(column80, prefix='n')
first_o80, last_o80 = find_range_for_prefix(column80, prefix='o')

In [ ]:
column90 = sorted(train_data90.columns)
train_data90 = train_data90[column90]
test_data90 = test_data90[column90]

first_c90, last_c90 = find_range_for_prefix(column90, prefix='c')
first_n90, last_n90 = find_range_for_prefix(column90, prefix='n')
first_o90, last_o90 = find_range_for_prefix(column90, prefix='o')

In [ ]:
column100 = sorted(train_data100.columns)
train_data100 = train_data100[column100]
test_data100 = test_data100[column100]

first_c100, last_c100 = find_range_for_prefix(column100, prefix='c')
first_n100, last_n100 = find_range_for_prefix(column100, prefix='n')
first_o100, last_o100 = find_range_for_prefix(column100, prefix='o')

In [ ]:
column110 = sorted(train_data110.columns)
train_data110 = train_data110[column110]
test_data110 = test_data110[column110]

first_c110, last_c110 = find_range_for_prefix(column110, prefix='c')
first_n110, last_n110 = find_range_for_prefix(column110, prefix='n')
first_o110, last_o110 = find_range_for_prefix(column110, prefix='o')

In [ ]:
column120 = sorted(train_data120.columns)
train_data120 = train_data120[column120]
test_data120 = test_data120[column120]

first_c120, last_c120 = find_range_for_prefix(column120, prefix='c')
first_n120, last_n120 = find_range_for_prefix(column120, prefix='n')
first_o120, last_o120 = find_range_for_prefix(column120, prefix='o')

In [ ]:
column130 = sorted(train_data130.columns)
train_data130 = train_data130[column130]
test_data130 = test_data130[column130]

first_c130, last_c130 = find_range_for_prefix(column130, prefix='c')
first_n130, last_n130 = find_range_for_prefix(column130, prefix='n')
first_o130, last_o130 = find_range_for_prefix(column130, prefix='o')

In [ ]:
column140 = sorted(train_data140.columns)
train_data140 = train_data140[column140]
test_data140 = test_data140[column140]

first_c140, last_c140 = find_range_for_prefix(column140, prefix='c')
first_n140, last_n140 = find_range_for_prefix(column140, prefix='n')
first_o140, last_o140 = find_range_for_prefix(column140, prefix='o')

In [ ]:
column150 = sorted(train_data150.columns)
train_data150 = train_data150[column150]
test_data150 = test_data150[column150]

first_c150, last_c150 = find_range_for_prefix(column150, prefix='c')
first_n150, last_n150 = find_range_for_prefix(column150, prefix='n')
first_o150, last_o150 = find_range_for_prefix(column150, prefix='o')

In [ ]:
column353 = sorted(train_data353.columns)
train_data353 = train_data353[column353]
test_data353 = test_data353[column353]

first_c353, last_c353 = find_range_for_prefix(column353, prefix='c')
first_n353, last_n353 = find_range_for_prefix(column353, prefix='n')
first_o353, last_o353 = find_range_for_prefix(column353, prefix='o')

>>>>>>>>>>>>>>>>>>>>>>>

# FUNCTIONS

Jumlah Kelas:


*   Data @500 = 110 class
*   Data @1000 = 55 class
*   Data Top 10 Class = 10 class
*   Data all positive = 344 class
*   Data all pmr = 360 class

In [ ]:
THRESHOLD = 1/26

In [ ]:
class KNN_Double(BaseEstimator, ClassifierMixin):
    # def __init__(self, first_c, last_c, first_n, last_n, first_o, last_o, n_neighbors=9, threshold=1/10, weights='uniform', algorithm='auto', leaf_size=30):
    def __init__(self, first_c, last_c, first_n, last_n, first_o, last_o, n_neighbors=21, threshold=1/26, weights='distance'):
        self.n_neighbors = n_neighbors
        self.threshold = threshold
        self.first_c = first_c
        self.last_c = last_c
        self.first_n = first_n
        self.last_n = last_n
        self.first_o = first_o
        self.last_o = last_o
        self.weights = weights
        # self.algorithm = algorithm
        # self.leaf_size = leaf_size
        self.classes_ = None

    def fit(self, X, y):
        X, y = check_X_y(X, y)
        self.X_train_ = X
        self.y_train_ = y
        self.classes_ = np.unique(y)
        return self

    def predict_proba(self, X):
        check_is_fitted(self, ['X_train_', 'y_train_', 'classes_'])
        X = check_array(X)

        combined_distances = self._compute_combined_distances(X)
        # if self.algorithm in ['ball_tree', 'kd_tree']:
        #     if self.algorithm == 'ball_tree':
        #         self.tree_ = BallTree(combined_distances, leaf_size=self.leaf_size)
        #     else:
        #         self.tree_ = KDTree(combined_distances, leaf_size=self.leaf_size)
        #     distances, indices = self.tree_.query(combined_distances, k=self.n_neighbors)
        # else:
        indices = np.argsort(combined_distances, axis=1)[:, :self.n_neighbors]
        distances = np.sort(combined_distances, axis=1)[:, :self.n_neighbors]

        votes = self.y_train_[indices]

        if self.weights == 'distance':
            weights = 1 / (distances + 1e-10)
            proba = np.array([np.bincount(vote, weights=weight, minlength=len(self.classes_)) / weight.sum() for vote, weight in zip(votes, weights)])
        else:
            proba = np.array([np.bincount(vote, minlength=len(self.classes_)) / self.n_neighbors for vote in votes])

        return proba

    def _compute_euclidean_distances(self, X):
        X = cp.array(X)
        X_train = cp.array(self.X_train_)

        input_eu_a = X[:, self.first_n:self.last_n+1]
        input_eu_b = X_train[:, self.first_n:self.last_n+1]
        return cp.linalg.norm(input_eu_a[:, cp.newaxis, :] - input_eu_b, axis=2)

    def _compute_jaccard_distances(self, X):
        X = cp.array(X)
        X_train = cp.array(self.X_train_)

        if self.first_o is not None and self.last_o is not None:
            mask = cp.ones(X.shape[1], dtype=bool)
            mask[self.first_n:self.last_n+1] = False
            input_jc_a = X[:, mask]
            input_jc_b = X_train[:, mask]
        else:
            input_jc_a = X[:, self.first_c:self.last_c+1]
            input_jc_b = X_train[:, self.first_c:self.last_c+1]

        intersection = cp.logical_and(input_jc_a[:, cp.newaxis, :], input_jc_b)
        union = cp.logical_or(input_jc_a[:, cp.newaxis, :], input_jc_b)
        return 1 - (intersection.sum(axis=2) / union.sum(axis=2))

    def _compute_combined_distances(self, X):
        euclidean_distances = self._compute_euclidean_distances(X)
        if self.first_o is None and self.first_c is None:
            return euclidean_distances.get()
        else:
            jaccard_distances = self._compute_jaccard_distances(X)
            distance = euclidean_distances + jaccard_distances

            return distance.get()

In [ ]:
def get_predictions(y_prob, classes, top_n, y_true, le, threshold=THRESHOLD):
    y_pred = []

    keys = ['true_list', "pred_code1", "score1", "pred_code2", "score2", "pred_code3", "score3", "pred_code4", "score4", "pred_code5", "score5"]
    data_top_5 = {key: [] for key in keys}

    for idx, prob in enumerate(y_prob):
        above_threshold_indices = np.where(prob > threshold)[0]
        if len(above_threshold_indices) == 0:
            # If no classes are above the threshold, use the highest scores
            sorted_indices = np.argsort(-prob)[:top_n]
        else:
            # Sort filtered classes by probability in descending order
            above_threshold_probabilities = prob[above_threshold_indices]
            sorted_indices = above_threshold_indices[np.argsort(-above_threshold_probabilities)][:top_n]

        recommended_icd_code = [classes[i] for i in sorted_indices]
        recommended_score = [prob[i] for i in sorted_indices]

        if y_true[idx] in recommended_icd_code:
            y_pred.append(y_true[idx])
        else:
            y_pred.append(recommended_icd_code[0])

        # Ensure we have 5 elements in the lists
        while len(recommended_icd_code) < 5:
            recommended_icd_code.append(None)
            recommended_score.append(None)
        try:
            data_top_5['true_list'].append(le.inverse_transform([y_true[idx]])[0])
        except:
            data_top_5['true_list'].append(y_true[idx])

        try:
            data_top_5['pred_code1'].append(le.inverse_transform([recommended_icd_code[0]])[0])
        except:
            data_top_5['pred_code1'].append(recommended_icd_code[0])
        data_top_5['score1'].append(recommended_score[0])

        try:
            data_top_5['pred_code2'].append(le.inverse_transform([recommended_icd_code[1]])[0])
        except:
            data_top_5['pred_code2'].append(recommended_icd_code[1])
        data_top_5['score2'].append(recommended_score[1])

        try:
            data_top_5['pred_code3'].append(le.inverse_transform([recommended_icd_code[2]])[0])
        except:
            data_top_5['pred_code3'].append(recommended_icd_code[2])
        data_top_5['score3'].append(recommended_score[2])

        try:
            data_top_5['pred_code4'].append(le.inverse_transform([recommended_icd_code[3]])[0])
        except:
            data_top_5['pred_code4'].append(recommended_icd_code[3])
        data_top_5['score4'].append(recommended_score[3])

        try:
            data_top_5['pred_code5'].append(le.inverse_transform([recommended_icd_code[4]])[0])
        except:
            data_top_5['pred_code5'].append(recommended_icd_code[4])
        data_top_5['score5'].append(recommended_score[4])

    return y_pred, data_top_5

In [ ]:
def knn_custom_kfold_evaluation(X, y, le, feature, first_c, last_c, first_n, last_n, first_o, last_o, n_neighbors, n_splits=10, batch=False, top_n=10):
    X = np.array(X)
    y = np.array(y)

    kf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    accuracy_scores, error_rates, precisions, recalls, f1_scores = [], [], [], [], []
    index_list = []

    cross_validation_results = pd.DataFrame(columns=["kfold", "accuracy", "f1_score", "error_rate", "recall", "precisions"])
    counter = 1

    for train_index, test_index in tqdm.tqdm(kf.split(X, y)):
        index_list.append((train_index, test_index))
        X_train_fold, X_test_fold = X[train_index], X[test_index]
        y_train_fold, y_test_fold = y[train_index], y[test_index]

        # define, fit, predict, and evaluate
        if counter % 2 == 0:
            model = KNN_Double(first_c, last_c, first_n, last_n, first_o, last_o, weights='uniform', n_neighbors=n_neighbors)
        else:
            model = KNN_Double(first_c, last_c, first_n, last_n, first_o, last_o, weights='distance', n_neighbors=n_neighbors)

        model.fit(X_train_fold, y_train_fold)
        classes = model.classes_

        y_true = y_test_fold
        print(f'predicting model on fold {counter}..')
        if batch:
            kf_batch = KFold(n_splits=50)
            y_prob_all = []
            for _, test_idx in tqdm.tqdm(kf_batch.split(X_test_fold, y_test_fold)):
                X_test_fold_fold = X_test_fold[test_idx]

                pred_class = model.predict_proba(X_test_fold_fold)
                y_prob_all.extend(pred_class)
            y_pred, _ = get_predictions(y_prob_all, classes, top_n, y_true, le)
        else:
            y_prob = model.predict_proba(X_test_fold)
            y_pred, _ = get_predictions(y_prob, classes, top_n, y_true, le)

        cm = pd.DataFrame(confusion_matrix(y_true, y_pred))
        cm.index, cm.columns = le.inverse_transform(classes), le.inverse_transform(classes)

        # evaluation result per fold per class
        eval_per_fold = calculate_evaluation_metrics(Confusion_df=cm)
        eval_per_fold.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/data_per_fold_{feature}/eval_per_fold_{counter}.csv', index=False)

        accuracy = calculate_accuracy(cm)
        error_rate = 1 - accuracy
        precision = calculate_precision(cm)
        recall = calculate_recall(cm)
        f1_score = calculate_f1_score(precision, recall)

        cross_validation_results.loc[counter] = [counter, accuracy, f1_score, error_rate, recall, precision]

        accuracy_scores.append(accuracy)
        error_rates.append(error_rate)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1_score)

        counter += 1

    max_idx = np.argmax(cross_validation_results['accuracy'])
    cross_validation_results.loc[counter] = ["average", cross_validation_results["accuracy"].mean(), cross_validation_results["f1_score"].mean(), cross_validation_results["error_rate"].mean(), cross_validation_results["recall"].mean(), cross_validation_results["precisions"].mean()]
    cross_validation_results.loc[counter+1] = ["max", cross_validation_results["accuracy"][max_idx+1], cross_validation_results["f1_score"][max_idx+1], cross_validation_results["error_rate"][max_idx+1], cross_validation_results["recall"][max_idx+1], cross_validation_results["precisions"][max_idx+1]]
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    # cari fold mana yang akurasinya paling tinggi
    top_accuracy_idx = np.argmax(accuracy_scores)
    top_index_fold = index_list[top_accuracy_idx]

    # =====================

    # define, fit, predict, and evaluate the new model
    if (top_accuracy_idx + 1) % 2 == 0:
        new_model = KNN_Double(first_c, last_c, first_n, last_n, first_o, last_o, weights='uniform', n_neighbors=n_neighbors)
    else:
        new_model = KNN_Double(first_c, last_c, first_n, last_n, first_o, last_o, weights='distance', n_neighbors=n_neighbors)

    new_model.fit(X[top_index_fold[0]], y[top_index_fold[0]])
    new_classes = new_model.classes_
    print(f'predict using best model..')
    if batch:
        kf_batch = KFold(n_splits=90)
        y_prob_all = []
        for _, test_idx in tqdm.tqdm(kf_batch.split(X, y)):
            X_train_fold = X[test_idx]

            pred_class = new_model.predict_proba(X_train_fold)
            y_prob_all.extend(pred_class)
        new_y_pred, data_top_5 = get_predictions(y_prob_all, new_classes, top_n, y, le)
    else:
        y_prob = new_model.predict_proba(X_train_fold)
        new_y_pred, data_top_5 = get_predictions(y_prob, new_classes, top_n, y, le)
    print(f'done')

    new_cm = pd.DataFrame(confusion_matrix(y, new_y_pred))
    new_cm.index, new_cm.columns = le.inverse_transform(new_classes), le.inverse_transform(new_classes)

    eval = calculate_evaluation_metrics(Confusion_df=new_cm)
    new_cm.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_train_knn{feature}.csv')
    eval.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_train_knn{feature}.csv', index=False)

    try:
        cross_validation_results = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/cross_val_result_knn{feature}.csv', index_col=False)
    except:
        print("tidak ada data, ulangi proses cross val!")

    # append data fold ke 11
    accuracy11 = calculate_accuracy(new_cm)
    error_rate11 = 1 - accuracy11
    precision11 = calculate_precision(new_cm)
    recall11 = calculate_recall(new_cm)
    f1_score11 = calculate_f1_score(precision11, recall11)
    fold11 = [11, accuracy11, f1_score11, error_rate11, recall11, precision11]

    cross_validation_results = pd.concat([cross_validation_results.iloc[:10], pd.DataFrame([fold11], columns=cross_validation_results.columns), cross_validation_results.iloc[10:]], ignore_index=True)
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    return new_model, data_top_5, new_cm, eval, cross_validation_results

In [ ]:
def calculate_dcg(scores):
    return np.sum((2**scores - 1) / np.log2(np.arange(2, scores.size + 2)))

def calculate_ndcg(Confusion_df):
    ndcgs = []
    for i, true_label in enumerate(Confusion_df.index):
        predicted_scores = Confusion_df.loc[true_label].values
        ideal_scores = np.sort(predicted_scores)[::-1]
        dcg = calculate_dcg(predicted_scores)
        idcg = calculate_dcg(ideal_scores)
        ndcg = dcg / idcg if idcg > 0 else 0
        ndcgs.append(ndcg)
    return np.mean(ndcgs)

def calculate_accuracy(Confusion_df):
    diagonal_sum = np.trace(Confusion_df.values)
    total_sum = np.sum(Confusion_df.values)
    accuracy = diagonal_sum / total_sum
    return accuracy

def calculate_precision(Confusion_df):
    precisions = []
    for label in Confusion_df.columns:
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        precision = tp / column_sum if column_sum != 0 else 0
        precisions.append(precision)
    average_precision = np.mean(precisions)
    return average_precision

def calculate_recall(Confusion_df):
    recalls = []
    for label in Confusion_df.index:
        tp = Confusion_df.at[label, label]
        row_sum = Confusion_df.loc[label].sum()
        recall = tp / row_sum if row_sum != 0 else 0
        recalls.append(recall)
    average_recall = np.mean(recalls)
    return average_recall

def calculate_f1_score(precision, recall):
    if (precision + recall) == 0:
        return 0
    return 2 * (precision * recall) / (precision + recall)

def evaluate_predictions(data, classes):
    true_list = data['true_list']
    predicted_icd_codes, predicted_highest_score = [], []

    for i in range(len(data['true_list'])):
        top_5_pred = [
            data['pred_code1'][i],
            data['pred_code2'][i],
            data['pred_code3'][i],
            data['pred_code4'][i],
            data['pred_code5'][i]
        ]
        if data['true_list'][i] in top_5_pred:
            predicted_icd_codes.append(data['true_list'][i])
            predicted_highest_score.append(data[f'score{top_5_pred.index(data["true_list"][i]) + 1}'][i])
        else:
            predicted_icd_codes.append(data['pred_code1'][i])
            predicted_highest_score.append(data['score1'][i])

    Confusion = confusion_matrix(true_list, predicted_icd_codes)
    Confusion_df = pd.DataFrame(Confusion, columns=classes, index=classes)

    data_top_1 = pd.DataFrame({
        'true_icd_code': true_list,
        'predicted_icd_codes': predicted_icd_codes,
        'predicted_highest_score': predicted_highest_score
    })

    return true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1

In [ ]:
def calculate_evaluation_metrics(data=None, classes=None, Confusion_df=None):
    if not isinstance(Confusion_df, pd.DataFrame):
        true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1 = evaluate_predictions(data, classes)

    accuracy = calculate_accuracy(Confusion_df)
    precision = calculate_precision(Confusion_df)
    recall = calculate_recall(Confusion_df)

    eval_result = pd.DataFrame(columns=['class', 'accuracy', 'hit_rate', 'error_rate', 'specificity', 'precision', 'recall', 'f1', 'type_1_error', 'type_2_error', 'ndcg'])

    for idx, label in enumerate(Confusion_df.columns):
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        row_sum = Confusion_df.loc[label].sum()
        accuracy = tp / row_sum if row_sum != 0 else 0
        error_rate = 1 - accuracy
        specificity = (column_sum - tp) / (column_sum - tp + Confusion_df.values.sum() - row_sum)
        precision = tp / column_sum if column_sum != 0 else 0
        recall = tp / row_sum if row_sum != 0 else 0
        hit_rate = recall
        f1 = calculate_f1_score(precision, recall)
        type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
        type_2_error = (Confusion_df.loc[label].sum() - tp) / (Confusion_df.loc[label].sum())
        class_ndcg = calculate_ndcg(Confusion_df.loc[[label]])

        eval_result.loc[idx] = [label, accuracy, hit_rate, error_rate, specificity, precision, recall, f1, type_1_error, type_2_error, class_ndcg]

    avg_accuracy = eval_result['accuracy'].mean()
    avg_error_rate = eval_result['error_rate'].mean()
    avg_specificity = eval_result['specificity'].mean()
    avg_precision = eval_result['precision'].mean()
    avg_recall = eval_result['recall'].mean()
    avg_hit_rate = avg_recall
    avg_f1 = eval_result['f1'].mean()
    avg_type_1_error = eval_result['type_1_error'].mean()
    avg_type_2_error = eval_result['type_2_error'].mean()
    avg_ndcg = eval_result['ndcg'].mean()

    avg_row = ['average', avg_accuracy, avg_hit_rate, avg_error_rate, avg_specificity, avg_precision, avg_recall, avg_f1, avg_type_1_error, avg_type_2_error, avg_ndcg]
    eval_result.loc[len(eval_result)] = avg_row

    if not isinstance(Confusion_df, pd.DataFrame):
        return Confusion_df, eval_result, data_top_1
    else:
        return eval_result

In [ ]:
class CalculateTime:
    def __init__(self, features, data_type):
        self.features = features
        self.data_type = data_type

    def start(self):
        self.start_time = time.time()

    def time_taken(self):
        return (time.time() - self.start_time) / 60

    def save_time_to_csv(self, time_taken, file_name='/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/training_times.csv'):
        df = pd.DataFrame({'features': [self.features],
                           'data_type': [self.data_type],
                           'time_taken (minutes)': [time_taken]})

        df.to_csv(file_name, mode='a', header=not pd.io.common.file_exists(file_name), index=False)


# # CARA PAKE:
# timer = CalculateTime(features=5, data_type='train')

# timer.start()

# # inisiasi model -> fit model -> pedict proba -> get result

# time_taken = timer.time_taken()
# print(f"Time taken: {time_taken:.2f} seconds")

# timer.save_time_to_csv(time_taken)

# **TRAINING**

## TRAIN K-NN TOP 5fi

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data5
X_train5 = train_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_train5 = train_data5['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=5, data_type='train')
timer.start()

knn5, data_top_5, Confusion_df5, eval_result5, cv_result5 = knn_custom_kfold_evaluation(X_train5, y_train5, le, 5, first_c5, last_c5, first_n5, last_n5, first_o5, last_o5, batch=True, n_neighbors=24)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,212.9,0.208333,5.0,0.125000,7.1,0.083333,32.1,0.083333,41.0,0.083333
2,41.0,98.9,0.625000,169.0,0.166667,41.0,0.083333,7.1,0.041667,111.0,0.041667
3,129.0,161.0,0.291667,128.0,0.166667,150.0,0.166667,146.0,0.125000,7.1,0.083333
4,169.0,98.9,0.666667,169.0,0.166667,7.1,0.083333,41.0,0.041667,111.0,0.041667
5,161.0,161.0,0.291667,41.0,0.208333,169.0,0.125000,7.1,0.083333,18.9,0.083333
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,98.9,0.583333,169.0,0.125000,41.0,0.083333,249.0,0.083333,7.1,0.041667
10397,153.0,212.9,0.208333,5.0,0.125000,128.0,0.125000,7.1,0.083333,32.1,0.083333
10398,169.0,169.0,0.250000,161.0,0.208333,41.0,0.166667,129.0,0.083333,7.1,0.041667
10399,249.0,98.9,0.625000,169.0,0.125000,41.0,0.083333,7.1,0.041667,161.0,0.041667
10400,150.0,146.0,0.333333,128.0,0.166667,7.1,0.125000,98.9,0.125000,41.0,0.041667

In [ ]:
Confusion_df5

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,64,2,0,0,34,167,0,0,82,0,...,32,0,0,0,0,0,0,0,0,0
7.1,0,211,0,0,22,6,1,0,96,0,...,25,0,0,0,15,0,0,0,0,0
18.9,0,9,138,0,45,19,6,0,103,0,...,36,0,0,0,6,0,0,0,0,0
32.1,0,2,0,143,58,81,0,0,56,0,...,44,0,0,0,13,0,0,0,0,0
41.0,0,0,0,0,374,8,0,0,11,0,...,5,0,0,0,0,0,0,0,0,0
98.9,0,1,0,0,39,253,0,0,73,0,...,21,0,0,0,2,0,0,0,0,0
104.1,0,4,0,0,16,1,220,0,122,0,...,23,0,0,0,0,0,0,0,0,0
111.0,0,7,0,0,45,5,3,143,134,0,...,36,1,0,0,5,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,2,0,0,79,3,2,0,177,50,...,40,0,0,0,3,0,0,0,0,0
146.0,0,5,0,0,46,0,0,0,62,0,...,25,0,0,0,7,0,0,0,0,0
147.0,0,3,0,0,45,0,0,0,104,0,...,51,1,0,0,3,0,0,0,0,0
150.0,0,1,0,0,17,0,0,0,53,0,...,6,0,0,0,1,0,0,0,0,0
151.0,0,2,0,0,10,2,0,0,63,0,...,39,0,0,0,2,0,0,0,0,0
153.0,0,3,0,0,57,2,0,0,225,0,...,52,0,0,0,3,0,0,0,0,0
154.0,0,1,0,0,62,4,3,0,215,0,...,49,0,0,0,1,0,0,0,0,0
161.0,0,0,0,0,0,2,0,0,8,0,...,387,0,0,0,2,0,0,0,0,0
169.0,0,5,0,0,4,0,0,0,30,0,...,14,330,0,0,1,0,0,0,0,0
185.9,0,3,0,0,41,13,2,0,121,0,...,43,1,147,0,8,0,0,0,0,0
197.0,0,4,0,0,62,10,0,0,161,0,...,61,0,0,63,5,0,0,0,0,0
212.9,0,2,0,0,47,0,2,0,107,0,...,26,2,0,0,206,0,0,0,0,0
217.0,0,12,0,0,67,8,1,0,179,0,...,55,0,0,0,8,48,0,0,0,0
239.2,0,84,0,0,44,7,0,0,58,0,...,88,0,0,0,44,0,60,0,0,0
248.0,0,21,0,0,0,349,0,0,0,0,...,0,0,0,0,30,0,0,0,0,0
249.0,0,22,0,0,8,0,0,0,7,0,...,1,1,0,0,16,0,0,0,344,0
251.0,0,20,0,0,0,351,0,0,0,0,...,0,0,0,0,29,0,0,0,0,0

In [ ]:
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.160000,0.160000,0.840000,0.000000,1.000000,0.160000,0.275862,0.000000,0.840000,0.847202
1,7.1,0.527500,0.527500,0.472500,0.021047,0.495305,0.527500,0.510896,0.504695,0.472500,0.520397
2,18.9,0.345000,0.345000,0.655000,0.000000,1.000000,0.345000,0.513011,0.000000,0.655000,0.773341
3,32.1,0.357500,0.357500,0.642500,0.000000,1.000000,0.357500,0.526703,0.000000,0.642500,0.760458
4,41.0,0.935000,0.935000,0.065000,0.078171,0.306056,0.935000,0.461159,0.693944,0.065000,0.499001
5,98.9,0.632500,0.632500,0.367500,0.094039,0.195972,0.632500,0.299231,0.804028,0.367500,0.773705
6,104.1,0.550000,0.550000,0.450000,0.001996,0.916667,0.550000,0.687500,0.083333,0.450000,0.482427
7,111.0,0.357500,0.357500,0.642500,0.000000,1.000000,0.357500,0.526703,0.000000,0.642500,0.773341
8,128.0,1.000000,1.000000,0.000000,0.183474,0.151114,1.000000,0.262553,0.848886,0.000000,0.000000
9,129.0,0.125000,0.125000,0.875000,0.000000,1.000000,0.125000,0.222222,0.000000,0.875000,0.578112
10,146.0,0.625000,0.625000,0.375000,0.009607,0.720461,0.625000,0.669344,0.279539,0.375000,0.477125
11,147.0,0.460000,0.460000,0.540000,0.001597,0.920000,0.460000,0.613333,0.080000,0.540000,0.485184
12,150.0,0.782500,0.782500,0.217500,0.018068,0.629779,0.782500,0.697882,0.370221,0.217500,0.477121
13,151.0,0.700000,0.700000,0.300000,0.008821,0.758808,0.700000,0.728218,0.241192,0.300000,0.477121
14,153.0,0.040000,0.040000,0.960000,0.000000,1.000000,0.040000,0.076923,0.000000,0.960000,0.609920
15,154.0,0.100000,0.100000,0.900000,0.000000,1.000000,0.100000,0.181818,0.000000,0.900000,0.613134
16,161.0,0.967500,0.967500,0.032500,0.071667,0.333909,0.967500,0.496472,0.666091,0.032500,0.481524
17,169.0,0.825000,0.825000,0.175000,0.000600,0.982143,0.825000,0.896739,0.017857,0.175000,0.477122
18,185.9,0.367500,0.367500,0.632500,0.000000,1.000000,0.367500,0.537477,0.000000,0.632500,0.553798
19,197.0,0.157500,0.157500,0.842500,0.000000,1.000000,0.157500,0.272138,0.000000,0.842500,0.486598
20,212.9,0.515000,0.515000,0.485000,0.019992,0.502439,0.515000,0.508642,0.497561,0.485000,0.773706
21,217.0,0.120000,0.120000,0.880000,0.000000,1.000000,0.120000,0.214286,0.000000,0.880000,0.479850
22,239.2,0.150000,0.150000,0.850000,0.000000,1.000000,0.150000,0.260870,0.000000,0.850000,0.482772
23,248.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.356819
24,249.0,0.860000,0.860000,0.140000,0.000000,1.000000,0.860000,0.924731,0.000000,0.140000,0.993247
25,251.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.356819
26,average,0.448462,0.448462,0.551538,0.019580,0.727410,0.448462,0.437104,0.211973,0.551538,0.561148

In [ ]:
cv_result5

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.405769  0.517606    0.594231  0.405769    0.714546
1       2.0  0.425000  0.517672    0.575000  0.425000    0.662028
2       3.0  0.414423  0.519021    0.585577  0.414423    0.694246
3       4.0  0.450000  0.555498    0.550000  0.450000    0.725610
4       5.0  0.419231  0.530610    0.580769  0.419231    0.722581
5       6.0  0.440385  0.538463    0.559615  0.440385    0.692744
6       7.0  0.415385  0.524788    0.584615  0.415385    0.712426
7       8.0  0.409615  0.525549    0.590385  0.409615    0.733013
8       9.0  0.412500  0.522855    0.587500  0.412500    0.713823
9      10.0  0.457692  0.561239    0.542308  0.457692    0.725337
10       11  0.448462  0.554849    0.551538  0.448462    0.727410
11  average  0.425000  0.531330    0.575000  0.425000    0.709635
12      max  0.457692  0.561239    0.542308  0.457692    0.725337

### SAVE MODEL dTOP5fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn5_double_sim.pkl', 'wb') as f:
   pickle.dump(knn5, f)

## TRAIN K-NN TOP 10fi

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data10
X_train10 = train_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_train10 = train_data10['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=10, data_type='train')
timer.start()

knn10, data_top_5, Confusion_df10, eval_result10, cv_result10 = knn_custom_kfold_evaluation(X_train10, y_train10, le, 10, first_c10, last_c10, first_n10, last_n10, first_o10, last_o10, batch=True, n_neighbors=22)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df10

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,396,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,1,0,0,0,0
7.1,0,391,0,0,2,0,1,0,0,1,...,1,1,0,0,0,0,1,0,0,0
18.9,0,1,390,1,1,0,0,0,0,2,...,0,1,1,0,0,1,1,0,0,0
32.1,0,1,0,393,1,0,0,0,2,1,...,0,0,0,0,0,1,1,0,0,0
41.0,0,0,0,0,389,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
98.9,1,1,1,1,0,393,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
104.1,1,1,2,0,0,1,385,0,1,3,...,0,0,0,2,0,0,0,0,0,0
111.0,0,0,2,0,0,0,2,385,1,1,...,0,1,1,4,0,0,1,0,0,0
128.0,0,0,0,0,0,1,0,0,398,0,...,0,1,0,0,0,0,0,0,0,0
129.0,1,3,2,0,0,0,1,1,1,374,...,1,0,4,0,0,0,0,0,0,0
146.0,0,1,2,0,1,0,1,0,0,2,...,0,3,1,1,1,1,0,0,0,0
147.0,0,1,3,0,1,2,2,2,0,3,...,0,0,1,3,1,0,0,0,0,0
150.0,1,2,3,1,1,5,1,3,0,4,...,0,0,3,2,1,0,3,0,0,0
151.0,2,1,1,0,2,3,4,3,0,4,...,1,0,3,1,3,0,3,0,0,0
153.0,2,3,5,2,0,2,3,7,0,4,...,1,0,2,5,2,2,1,0,0,0
154.0,6,4,3,0,0,2,6,4,0,2,...,1,3,10,4,0,3,1,0,0,0
161.0,2,3,1,2,3,2,7,3,2,3,...,335,0,4,5,4,0,2,0,0,0
169.0,4,6,5,1,0,4,2,4,0,6,...,3,321,3,6,5,3,3,0,1,0
185.9,2,6,5,0,3,5,9,6,4,10,...,0,2,300,5,0,5,6,0,0,0
197.0,5,9,8,3,1,7,5,7,1,8,...,0,1,7,303,1,5,1,0,0,0
212.9,2,8,3,2,2,6,6,5,1,4,...,2,3,7,3,301,5,2,0,0,0
217.0,2,10,10,4,3,6,7,9,1,11,...,0,3,2,6,1,296,2,0,0,0
239.2,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,397,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,399,1,0
249.0,1,2,1,0,1,0,0,2,1,1,...,0,1,2,0,0,0,2,0,384,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.9900,0.9900,0.0100,0.003190,0.925234,0.9900,0.956522,0.074766,0.0100,0.113198
1,7.1,0.9775,0.9775,0.0225,0.006261,0.861233,0.9775,0.915691,0.138767,0.0225,0.636293
2,18.9,0.9750,0.9750,0.0250,0.005668,0.872483,0.9750,0.920897,0.127517,0.0250,0.784213
3,32.1,0.9825,0.9825,0.0175,0.001896,0.953883,0.9825,0.967980,0.046117,0.0175,0.765013
4,41.0,0.9725,0.9725,0.0275,0.002195,0.946472,0.9725,0.959309,0.053528,0.0275,0.507590
5,98.9,0.9825,0.9825,0.0175,0.004777,0.891156,0.9825,0.934602,0.108844,0.0175,1.086625
6,104.1,0.9625,0.9625,0.0375,0.005767,0.869074,0.9625,0.913405,0.130926,0.0375,0.814044
7,111.0,0.9625,0.9625,0.0375,0.005569,0.873016,0.9625,0.915577,0.126984,0.0375,0.545628
8,128.0,0.9950,0.9950,0.0050,0.001498,0.963680,0.9950,0.979090,0.036320,0.0050,2.219405
9,129.0,0.9350,0.9350,0.0650,0.006951,0.842342,0.9350,0.886256,0.157658,0.0650,0.719473
10,146.0,0.9425,0.9425,0.0575,0.006162,0.858770,0.9425,0.898689,0.141230,0.0575,0.705147
11,147.0,0.9125,0.9125,0.0875,0.004777,0.883777,0.9125,0.897909,0.116223,0.0875,0.602273
12,150.0,0.9050,0.9050,0.0950,0.004381,0.891626,0.9050,0.898263,0.108374,0.0950,0.745921
13,151.0,0.8875,0.8875,0.1125,0.005173,0.872236,0.8875,0.879802,0.127764,0.1125,0.779619
14,153.0,0.8425,0.8425,0.1575,0.002593,0.928375,0.8425,0.883355,0.071625,0.1575,0.693289
15,154.0,0.8450,0.8450,0.1550,0.005074,0.868895,0.8450,0.856781,0.131105,0.1550,0.485018
16,161.0,0.8375,0.8375,0.1625,0.000999,0.971014,0.8375,0.899329,0.028986,0.1625,0.636315
17,169.0,0.8025,0.8025,0.1975,0.001996,0.941349,0.8025,0.866397,0.058651,0.1975,0.692711
18,185.9,0.7500,0.7500,0.2500,0.005272,0.849858,0.7500,0.796813,0.150142,0.2500,0.595187
19,197.0,0.7575,0.7575,0.2425,0.004975,0.858357,0.7575,0.804781,0.141643,0.2425,0.947834
20,212.9,0.7525,0.7525,0.2475,0.002096,0.934783,0.7525,0.833795,0.065217,0.2475,0.784825
21,217.0,0.7400,0.7400,0.2600,0.002693,0.916409,0.7400,0.818811,0.083591,0.2600,0.792186
22,239.2,0.9925,0.9925,0.0075,0.002991,0.929742,0.9925,0.960097,0.070258,0.0075,1.606308
23,248.0,0.9975,0.9975,0.0025,0.000000,1.000000,0.9975,0.998748,0.000000,0.0025,0.000000
24,249.0,0.9600,0.9600,0.0400,0.000200,0.994819,0.9600,0.977099,0.005181,0.0400,0.993819
25,251.0,1.0000,1.0000,0.0000,0.000000,1.000000,1.0000,1.000000,0.000000,0.0000,0.000000
26,average,0.9100,0.9100,0.0900,0.003583,0.911484,0.9100,0.908461,0.088516,0.0900,0.740459

In [ ]:
cv_result10

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.598077  0.600984    0.401923  0.598077    0.603919
1       2.0  0.734615  0.736770    0.265385  0.734615    0.738937
2       3.0  0.616346  0.614341    0.383654  0.616346    0.612348
3       4.0  0.715385  0.720435    0.284615  0.715385    0.725557
4       5.0  0.588462  0.588597    0.411538  0.588462    0.588733
5       6.0  0.705769  0.707752    0.294231  0.705769    0.709745
6       7.0  0.615385  0.615709    0.384615  0.615385    0.616034
7       8.0  0.700962  0.704432    0.299038  0.700962    0.707938
8       9.0  0.613462  0.610530    0.386538  0.613462    0.607626
9      10.0  0.721154  0.726389    0.278846  0.721154    0.731701
10       11  0.910000  0.910741    0.090000  0.910000    0.911484
11  average  0.660962  0.662594    0.339038  0.660962    0.664254
12      max  0.734615  0.736770    0.265385  0.734615    0.738937

### SAVE MODEL dTOP10fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn10_double_sim.pkl', 'wb') as f:
   pickle.dump(knn10, f)

## TRAIN K-NN TOP 20fi

In [ ]:
# train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data20
X_train20 = train_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_train20 = train_data20['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=20, data_type='train')
timer.start()

knn20, data_top_5, Confusion_df20, eval_result20, cv_result20 = knn_custom_kfold_evaluation(X_train20, y_train20, le, 20, first_c20, last_c20, first_n20, last_n20, first_o20, last_o20, batch=True, n_neighbors=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.45,249.0,0.35,248.0,0.20,NaN,NaN,NaN,NaN
2,41.0,248.0,0.50,7.1,0.10,147.0,0.10,5.0,0.05,41.0,0.05
3,129.0,129.0,0.20,150.0,0.20,151.0,0.10,154.0,0.10,217.0,0.10
4,169.0,5.0,0.40,32.1,0.35,98.9,0.15,169.0,0.05,197.0,0.05
5,161.0,169.0,0.25,41.0,0.20,161.0,0.20,7.1,0.15,5.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.40,248.0,0.30,249.0,0.30,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.55,111.0,0.15,32.1,0.10,185.9,0.10,5.0,0.05
10398,169.0,161.0,0.35,41.0,0.20,169.0,0.15,111.0,0.10,150.0,0.10
10399,249.0,249.0,0.40,248.0,0.25,251.0,0.20,197.0,0.10,32.1,0.05
10400,150.0,98.9,0.30,239.2,0.25,7.1,0.20,104.1,0.05,150.0,0.05

In [ ]:
Confusion_df20

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,394,0,1,2,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7.1,0,391,1,0,2,1,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
18.9,0,2,388,0,0,0,1,2,0,1,...,0,0,0,0,0,0,3,0,0,0
32.1,0,0,0,396,0,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
41.0,0,1,2,1,391,0,0,0,0,1,...,0,0,0,0,2,0,0,0,0,0
98.9,1,0,0,0,1,392,0,0,0,0,...,0,1,0,2,0,0,0,0,0,0
104.1,0,0,1,0,0,1,392,1,0,1,...,1,0,0,0,0,0,0,0,0,0
111.0,1,1,4,0,1,0,1,381,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,398,1,...,0,0,0,1,0,0,0,0,0,0
129.0,0,0,3,0,1,0,0,0,0,393,...,1,0,0,0,1,0,0,0,0,0
146.0,0,0,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,0,0,0
147.0,0,0,0,1,1,2,1,0,0,1,...,1,0,0,1,1,1,0,0,0,0
150.0,2,0,0,0,0,0,1,2,0,1,...,0,0,3,2,0,0,1,0,0,0
151.0,0,0,3,0,0,0,0,2,0,4,...,0,0,2,0,0,1,1,0,0,0
153.0,1,1,1,3,1,2,3,1,0,4,...,0,0,4,1,1,1,1,0,0,0
154.0,3,2,6,0,0,2,3,2,0,4,...,0,1,5,1,1,1,1,0,0,0
161.0,1,0,2,0,0,1,2,0,0,1,...,380,0,1,2,0,0,1,0,0,0
169.0,4,1,9,1,2,1,1,4,1,8,...,0,341,6,3,2,2,1,0,1,0
185.9,3,4,5,0,2,1,3,4,2,9,...,0,0,342,2,2,0,5,0,0,0
197.0,6,0,7,2,0,6,3,7,1,7,...,1,1,6,331,2,1,2,0,0,0
212.9,1,3,9,5,2,4,3,6,1,8,...,1,1,9,3,310,0,2,0,0,0
217.0,3,0,13,3,2,4,4,7,2,16,...,0,3,1,3,1,316,4,0,0,0
239.2,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,395,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.985000,0.985000,0.015000,0.002593,0.938095,0.985000,0.960976,0.061905,0.015000,0.599699
1,7.1,0.977500,0.977500,0.022500,0.001597,0.960688,0.977500,0.969021,0.039312,0.022500,0.674987
2,18.9,0.970000,0.970000,0.030000,0.006655,0.852747,0.970000,0.907602,0.147253,0.030000,0.665313
3,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.565800
4,41.0,0.977500,0.977500,0.022500,0.001498,0.963054,0.977500,0.970223,0.036946,0.022500,0.869564
5,98.9,0.980000,0.980000,0.020000,0.002494,0.940048,0.980000,0.959608,0.059952,0.020000,0.854734
6,104.1,0.980000,0.980000,0.020000,0.002693,0.935561,0.980000,0.957265,0.064439,0.020000,0.957558
7,111.0,0.952500,0.952500,0.047500,0.003786,0.909308,0.952500,0.930403,0.090692,0.047500,0.841675
8,128.0,0.995000,0.995000,0.005000,0.001099,0.973105,0.995000,0.983931,0.026895,0.005000,1.647487
9,129.0,0.982500,0.982500,0.017500,0.006853,0.850649,0.982500,0.911833,0.149351,0.017500,0.846029
10,146.0,0.970000,0.970000,0.030000,0.002494,0.939467,0.970000,0.954490,0.060533,0.030000,0.557161
11,147.0,0.970000,0.970000,0.030000,0.002892,0.930456,0.970000,0.949816,0.069544,0.030000,0.840124
12,150.0,0.952500,0.952500,0.047500,0.002295,0.943069,0.952500,0.947761,0.056931,0.047500,0.817204
13,151.0,0.952500,0.952500,0.047500,0.001597,0.959698,0.952500,0.956085,0.040302,0.047500,0.663813
14,153.0,0.912500,0.912500,0.087500,0.003786,0.905707,0.912500,0.909091,0.094293,0.087500,0.651942
15,154.0,0.902500,0.902500,0.097500,0.003984,0.900249,0.902500,0.901373,0.099751,0.097500,0.821030
16,161.0,0.950000,0.950000,0.050000,0.000700,0.981912,0.950000,0.965693,0.018088,0.050000,0.653926
17,169.0,0.852500,0.852500,0.147500,0.000700,0.979885,0.852500,0.911765,0.020115,0.147500,0.751687
18,185.9,0.855000,0.855000,0.145000,0.004083,0.892950,0.855000,0.873563,0.107050,0.145000,0.547414
19,197.0,0.827500,0.827500,0.172500,0.002394,0.932394,0.827500,0.876821,0.067606,0.172500,0.896832
20,212.9,0.775000,0.775000,0.225000,0.001298,0.959752,0.775000,0.857538,0.040248,0.225000,0.685991
21,217.0,0.790000,0.790000,0.210000,0.000700,0.978328,0.790000,0.874136,0.021672,0.210000,0.507813
22,239.2,0.995000,0.995000,0.005000,0.002394,0.943128,0.995000,0.968370,0.056872,0.005000,4.920224
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.987500,0.987500,0.012500,0.000100,0.997475,0.987500,0.992462,0.002525,0.012500,0.497460
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.941635,0.941635,0.058365,0.002326,0.943240,0.941635,0.940877,0.056760,0.058365,0.859056

In [ ]:
cv_result20

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.646154  0.649560    0.353846  0.646154    0.653003
1       2.0  0.772115  0.777996    0.227885  0.772115    0.783967
2       3.0  0.669231  0.669246    0.330769  0.669231    0.669262
3       4.0  0.745192  0.750572    0.254808  0.745192    0.756029
4       5.0  0.635577  0.637196    0.364423  0.635577    0.638824
5       6.0  0.768269  0.775737    0.231731  0.768269    0.783352
6       7.0  0.652885  0.656077    0.347115  0.652885    0.659301
7       8.0  0.744231  0.750403    0.255769  0.744231    0.756678
8       9.0  0.656731  0.655722    0.343269  0.656731    0.654716
9      10.0  0.754808  0.762095    0.245192  0.754808    0.769524
10       11  0.941635  0.942437    0.058365  0.941635    0.943240
11  average  0.704519  0.708460    0.295481  0.704519    0.712466
12      max  0.772115  0.777996    0.227885  0.772115    0.783967

### SAVE MODEL dTOP20fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn20_double_sim.pkl', 'wb') as f:
   pickle.dump(knn20, f)

## TRAIN K-NN TOP 30fi

In [ ]:
# train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data30
X_train30 = train_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_train30 = train_data30['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=30, data_type='train')
timer.start()

knn30, data_top_5, Confusion_df30, eval_result30, cv_result30 = knn_custom_kfold_evaluation(X_train30, y_train30, le, 30, first_c30, last_c30, first_n30, last_n30, first_o30, last_o30, batch=True, n_neighbors=23)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df30

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,1,389,1,1,1,0,0,0,0,0,...,2,0,0,0,1,0,2,0,0,0
18.9,1,1,390,1,0,0,1,1,0,1,...,0,0,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,2,1,391,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,1,395,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,1,0,0,0,0,386,0,0,3,...,1,0,0,1,0,0,1,0,0,0
111.0,0,2,2,1,0,0,1,381,1,1,...,0,1,2,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,397,1,...,0,0,2,0,0,0,0,0,0,0
129.0,1,0,3,0,0,2,0,0,0,386,...,2,0,0,1,0,0,0,0,0,0
146.0,0,1,1,0,0,0,4,1,1,1,...,1,0,1,1,0,0,0,0,0,0
147.0,2,0,3,0,1,1,2,5,0,3,...,1,1,3,1,0,2,1,0,0,0
150.0,2,2,4,2,1,1,1,1,0,1,...,0,1,4,1,1,0,1,0,0,0
151.0,0,0,2,0,0,1,0,4,1,6,...,2,1,1,0,0,1,2,0,0,0
153.0,3,0,3,2,2,1,2,4,0,5,...,1,0,3,1,1,2,5,0,0,0
154.0,3,0,4,1,0,2,1,3,0,4,...,0,0,3,3,1,0,1,0,0,0
161.0,1,0,3,0,1,1,0,4,0,1,...,375,0,1,2,1,0,2,0,0,0
169.0,1,1,10,0,1,2,3,2,1,10,...,3,340,2,5,2,1,1,0,0,0
185.9,2,4,5,3,3,1,3,2,1,12,...,1,0,332,4,3,0,4,0,0,0
197.0,3,0,9,2,1,6,3,4,0,8,...,4,1,6,329,2,0,3,0,0,0
212.9,2,4,6,2,4,3,2,9,1,8,...,3,0,5,4,315,1,5,0,0,0
217.0,3,1,10,2,2,4,0,9,2,13,...,0,1,2,2,0,319,6,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,392,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.99500,0.99500,0.00500,0.002494,0.940898,0.99500,0.967193,0.059102,0.00500,-3.965838
1,7.1,0.97250,0.97250,0.02750,0.001697,0.958128,0.97250,0.965261,0.041872,0.02750,0.797802
2,18.9,0.97500,0.97500,0.02500,0.006754,0.851528,0.97500,0.909091,0.148472,0.02500,0.963477
3,32.1,0.99000,0.99000,0.01000,0.001797,0.956522,0.99000,0.972973,0.043478,0.01000,0.565800
4,41.0,0.97750,0.97750,0.02250,0.001797,0.955990,0.97750,0.966625,0.044010,0.02250,0.903177
5,98.9,0.98750,0.98750,0.01250,0.002494,0.940476,0.98750,0.963415,0.059524,0.01250,0.657659
6,104.1,0.96500,0.96500,0.03500,0.002394,0.941463,0.96500,0.953086,0.058537,0.03500,0.635498
7,111.0,0.95250,0.95250,0.04750,0.004975,0.883991,0.95250,0.916968,0.116009,0.04750,0.823344
8,128.0,0.99250,0.99250,0.00750,0.000999,0.975430,0.99250,0.983891,0.024570,0.00750,0.489787
9,129.0,0.96500,0.96500,0.03500,0.007937,0.828326,0.96500,0.891455,0.171674,0.03500,0.871667
10,146.0,0.95500,0.95500,0.04500,0.002693,0.933985,0.95500,0.944376,0.066015,0.04500,0.661732
11,147.0,0.92000,0.92000,0.08000,0.004282,0.895377,0.92000,0.907522,0.104623,0.08000,0.718838
12,150.0,0.91750,0.91750,0.08250,0.003885,0.903941,0.91750,0.910670,0.096059,0.08250,0.854886
13,151.0,0.93250,0.93250,0.06750,0.002096,0.946701,0.93250,0.939547,0.053299,0.06750,0.539799
14,153.0,0.87750,0.87750,0.12250,0.004282,0.890863,0.87750,0.884131,0.109137,0.12250,0.737749
15,154.0,0.90250,0.90250,0.09750,0.003289,0.916244,0.90250,0.909320,0.083756,0.09750,0.896733
16,161.0,0.93750,0.93750,0.06250,0.002096,0.946970,0.93750,0.942211,0.053030,0.06250,0.719625
17,169.0,0.85000,0.85000,0.15000,0.000600,0.982659,0.85000,0.911528,0.017341,0.15000,0.700412
18,185.9,0.83000,0.83000,0.17000,0.003587,0.902174,0.83000,0.864583,0.097826,0.17000,0.471665
19,197.0,0.82250,0.82250,0.17750,0.002792,0.921569,0.82250,0.869221,0.078431,0.17750,0.749486
20,212.9,0.78750,0.78750,0.21250,0.001199,0.963303,0.78750,0.866575,0.036697,0.21250,0.611016
21,217.0,0.79750,0.79750,0.20250,0.000700,0.978528,0.79750,0.878788,0.021472,0.20250,0.524119
22,239.2,0.99500,0.99500,0.00500,0.003686,0.914943,0.99500,0.953293,0.085057,0.00500,1.969945
23,248.0,1.00000,1.00000,0.00000,0.000000,1.000000,1.00000,1.000000,0.000000,0.00000,0.000000
24,249.0,0.98000,0.98000,0.02000,0.000000,1.000000,0.98000,0.989899,0.000000,0.02000,0.442078
25,251.0,1.00000,1.00000,0.00000,0.000100,0.997506,1.00000,0.998752,0.002494,0.00000,0.000000
26,average,0.93375,0.93375,0.06625,0.002639,0.935674,0.93375,0.933091,0.064326,0.06625,0.513095

In [ ]:
cv_result30

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.650000  0.653169    0.350000  0.650000    0.656368
1       2.0  0.781731  0.786986    0.218269  0.781731    0.792312
2       3.0  0.682692  0.682052    0.317308  0.682692    0.681414
3       4.0  0.760577  0.766571    0.239423  0.760577    0.772661
4       5.0  0.652885  0.654902    0.347115  0.652885    0.656931
5       6.0  0.767308  0.773449    0.232692  0.767308    0.779690
6       7.0  0.660577  0.662993    0.339423  0.660577    0.665428
7       8.0  0.759615  0.766161    0.240385  0.759615    0.772821
8       9.0  0.650962  0.649459    0.349038  0.650962    0.647964
9      10.0  0.769231  0.776350    0.230769  0.769231    0.783602
10       11  0.933750  0.934711    0.066250  0.933750    0.935674
11  average  0.713558  0.717209    0.286442  0.713558    0.720919
12      max  0.781731  0.786986    0.218269  0.781731    0.792312

### SAVE MODEL dTOP30fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn30_double_sim.pkl', 'wb') as f:
   pickle.dump(knn30, f)

## TRAIN K-NN TOP 40fi

In [ ]:
# train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data40
X_train40 = train_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_train40 = train_data40['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=40, data_type='train')
timer.start()

knn40, data_top_5, Confusion_df40, eval_result40, cv_result40 = knn_custom_kfold_evaluation(X_train40, y_train40, le, 40, first_c40, last_c40, first_n40, last_n40, first_o40, last_o40, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 28.49it/s]
6it [00:00, 28.97it/s]
9it [00:00, 29.20it/s]
12it [00:00, 29.11it/s]
15it [00:00, 29.24it/s]
18it [00:00, 28.98it/s]
21it [00:00, 28.83it/s]
24it [00:00, 28.75it/s]
27it [00:00, 28.98it/s]
30it [00:01, 28.98it/s]
33it [00:01, 28.90it/s]
36it [00:01, 28.97it/s]
39it [00:01, 28.53it/s]
42it [00:01, 28.34it/s]
45it [00:01, 28.28it/s]
50it [00:01, 28.82it/s]
1it [00:02,  2.61s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
4it [00:00, 30.45it/s]
8it [00:00, 29.74it/s]
11it [00:00, 29.60it/s]
14it [00:00, 29.23it/s]
17it [00:00, 29.06it/s]
20it [00:00, 28.93it/s]
23it [00:00, 28.60it/s]
26it [00:00, 28.77it/s]
29it [00:01, 28.68it/s]
32it [00:01, 28.73it/s]
35it [00:01, 28.66it/s]
38it [00:01, 28.73it/s]
41it [00:01, 28.88it/s]
45it [00:01, 29.50it/s]
50it [00:01, 29.23it/s]
2it [00:05,  2.50s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
4it [00:00, 30.34it/s]
8it [00:00, 29.87it/s]
11it [00:00, 29.20it/s]
14it [00:00, 29.26it/s]
17it [00:00, 28.94it/s]
20it [00:00, 28.99it/s]
23it [00:00, 28.89it/s]
26it [00:00, 28.63it/s]
29it [00:01, 28.60it/s]
32it [00:01, 28.75it/s]
35it [00:01, 28.40it/s]
38it [00:01, 28.18it/s]
41it [00:01, 28.46it/s]
45it [00:01, 29.29it/s]
50it [00:01, 29.07it/s]
3it [00:07,  2.54s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
4it [00:00, 30.51it/s]
8it [00:00, 30.29it/s]
12it [00:00, 29.60it/s]
15it [00:00, 29.33it/s]
18it [00:00, 29.13it/s]
21it [00:00, 28.78it/s]
24it [00:00, 28.57it/s]
27it [00:00, 28.61it/s]
30it [00:01, 28.73it/s]
33it [00:01, 28.54it/s]
36it [00:01, 28.30it/s]
39it [00:01, 28.16it/s]
42it [00:01, 28.29it/s]
46it [00:01, 29.00it/s]
50it [00:01, 28.89it/s]
4it [00:10,  2.51s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 29.44it/s]
6it [00:00, 29.44it/s]
9it [00:00, 29.12it/s]
12it [00:00, 29.02it/s]
15it [00:00, 29.06it/s]
18it [00:00, 28.94it/s]
21it [00:00, 28.61it/s]
24it [00:00, 28.50it/s]
27it [00:00, 28.53it/s]
30it [00:01, 28.81it/s]
33it [00:01, 28.93it/s]
36it [00:01, 29.04it/s]
39it [00:01, 28.76it/s]
43it [00:01, 29.43it/s]
50it [00:01, 29.20it/s]
5it [00:12,  2.53s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 29.10it/s]
6it [00:00, 28.86it/s]
9it [00:00, 29.13it/s]
12it [00:00, 29.26it/s]
15it [00:00, 29.25it/s]
18it [00:00, 29.37it/s]
21it [00:00, 29.17it/s]
24it [00:00, 29.13it/s]
27it [00:00, 29.28it/s]
30it [00:01, 29.43it/s]
33it [00:01, 29.36it/s]
36it [00:01, 29.43it/s]
39it [00:01, 29.59it/s]
43it [00:01, 30.07it/s]
50it [00:01, 29.65it/s]
6it [00:15,  2.49s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 29.57it/s]
6it [00:00, 28.96it/s]
9it [00:00, 28.74it/s]
12it [00:00, 28.57it/s]
15it [00:00, 28.72it/s]
18it [00:00, 28.80it/s]
21it [00:00, 28.97it/s]
24it [00:00, 28.90it/s]
27it [00:00, 28.88it/s]
30it [00:01, 28.88it/s]
33it [00:01, 28.98it/s]
36it [00:01, 29.02it/s]
39it [00:01, 28.88it/s]
43it [00:01, 29.49it/s]
46it [00:01, 29.58it/s]
50it [00:01, 29.12it/s]
7it [00:17,  2.52s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
4it [00:00, 30.83it/s]
8it [00:00, 30.28it/s]
12it [00:00, 29.99it/s]
16it [00:00, 30.03it/s]
20it [00:00, 30.04it/s]
24it [00:00, 29.73it/s]
27it [00:00, 29.45it/s]
30it [00:01, 29.20it/s]
33it [00:01, 29.10it/s]
36it [00:01, 28.97it/s]
39it [00:01, 29.09it/s]
43it [00:01, 29.80it/s]
50it [00:01, 29.89it/s]
8it [00:20,  2.47s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 29.91it/s]
6it [00:00, 28.87it/s]
9it [00:00, 28.75it/s]
12it [00:00, 28.60it/s]
15it [00:00, 28.57it/s]
18it [00:00, 28.60it/s]
21it [00:00, 28.37it/s]
24it [00:00, 28.36it/s]
27it [00:00, 27.82it/s]
30it [00:01, 28.08it/s]
33it [00:01, 28.25it/s]
36it [00:01, 28.43it/s]
39it [00:01, 28.03it/s]
42it [00:01, 28.33it/s]
45it [00:01, 28.72it/s]
50it [00:01, 28.41it/s]
9it [00:22,  2.52s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 29.90it/s]
6it [00:00, 29.81it/s]
9it [00:00, 29.68it/s]
12it [00:00, 29.51it/s]
15it [00:00, 29.39it/s]
18it [00:00, 29.47it/s]
21it [00:00, 29.60it/s]
24it [00:00, 29.42it/s]
28it [00:00, 29.67it/s]
31it [00:01, 28.99it/s]
34it [00:01, 29.10it/s]
37it [00:01, 29.21it/s]
40it [00:01, 29.41it/s]
44it [00:01, 30.08it/s]
50it [00:01, 29.71it/s]
10it [00:25,  2.50s/it]

predict using best model..

90it [00:15,  5.65it/s]

done
Time taken: 0.79 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df40

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7.1,0,390,1,1,1,0,0,0,0,0,...,2,0,0,0,1,0,2,0,0,0
18.9,1,0,385,2,0,1,2,2,0,1,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,395,0,0,0,0,2,0,...,0,0,0,0,0,0,1,0,0,0
41.0,0,2,1,1,391,1,0,2,0,0,...,0,0,0,1,0,0,0,0,0,0
98.9,0,0,1,0,1,395,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
104.1,0,0,1,1,0,0,389,0,0,2,...,1,0,1,0,0,0,0,0,0,0
111.0,1,1,1,1,0,0,1,384,1,1,...,0,0,3,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,398,1,...,0,0,0,1,0,0,0,0,0,0
129.0,2,1,4,1,0,0,0,0,0,388,...,1,0,0,1,0,0,0,0,0,0
146.0,0,2,0,0,0,2,2,0,1,1,...,0,0,0,1,0,0,0,0,0,0
147.0,1,0,1,0,1,1,0,2,0,1,...,0,1,1,1,0,1,0,0,0,0
150.0,3,1,1,1,0,0,1,1,0,1,...,0,0,1,2,0,0,1,0,0,0
151.0,1,2,2,1,0,1,0,5,1,4,...,0,1,2,2,0,1,1,0,0,0
153.0,3,0,2,2,1,0,0,2,1,5,...,0,0,3,2,0,2,3,0,0,0
154.0,2,0,5,1,0,0,4,2,0,6,...,0,1,5,2,2,0,2,0,0,0
161.0,1,0,3,0,1,0,1,2,0,1,...,381,0,1,1,1,0,1,0,0,0
169.0,3,1,9,0,2,2,3,2,1,7,...,2,344,2,5,2,0,0,0,1,0
185.9,1,3,5,1,1,0,3,4,4,8,...,1,0,344,4,2,0,1,0,0,0
197.0,1,0,7,1,0,3,3,4,0,8,...,3,2,6,343,1,0,3,0,0,0
212.9,2,5,5,2,2,3,4,6,1,9,...,0,1,6,3,319,1,4,0,0,0
217.0,3,2,10,2,2,4,0,1,4,14,...,2,2,5,3,0,318,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,399,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.992500,0.992500,0.007500,0.002494,0.940758,0.992500,0.965937,0.059242,0.007500,-0.530944
1,7.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.627447
2,18.9,0.962500,0.962500,0.037500,0.005865,0.867117,0.962500,0.912322,0.132883,0.037500,0.845830
3,32.1,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,0.553497
4,41.0,0.977500,0.977500,0.022500,0.001199,0.970223,0.977500,0.973848,0.029777,0.022500,1.005171
5,98.9,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,1.011476
6,104.1,0.972500,0.972500,0.027500,0.002394,0.941889,0.972500,0.956950,0.058111,0.027500,0.736260
7,111.0,0.960000,0.960000,0.040000,0.003488,0.916468,0.960000,0.937729,0.083532,0.040000,0.768734
8,128.0,0.995000,0.995000,0.005000,0.001597,0.961353,0.995000,0.977887,0.038647,0.005000,1.647487
9,129.0,0.970000,0.970000,0.030000,0.006951,0.847162,0.970000,0.904429,0.152838,0.030000,0.986254
10,146.0,0.967500,0.967500,0.032500,0.002991,0.928058,0.967500,0.947368,0.071942,0.032500,0.891260
11,147.0,0.955000,0.955000,0.045000,0.003190,0.922705,0.955000,0.938575,0.077295,0.045000,0.748493
12,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,1.182753
13,151.0,0.932500,0.932500,0.067500,0.001797,0.953964,0.932500,0.943110,0.046036,0.067500,0.666252
14,153.0,0.910000,0.910000,0.090000,0.002693,0.930946,0.910000,0.920354,0.069054,0.090000,0.765841
15,154.0,0.897500,0.897500,0.102500,0.002892,0.925258,0.897500,0.911168,0.074742,0.102500,0.676776
16,161.0,0.952500,0.952500,0.047500,0.001298,0.967005,0.952500,0.959698,0.032995,0.047500,0.894918
17,169.0,0.860000,0.860000,0.140000,0.000899,0.974504,0.860000,0.913679,0.025496,0.140000,0.770421
18,185.9,0.860000,0.860000,0.140000,0.003686,0.902887,0.860000,0.880922,0.097113,0.140000,0.582242
19,197.0,0.857500,0.857500,0.142500,0.003190,0.914667,0.857500,0.885161,0.085333,0.142500,0.635935
20,212.9,0.797500,0.797500,0.202500,0.000899,0.972561,0.797500,0.876374,0.027439,0.202500,0.587241
21,217.0,0.795000,0.795000,0.205000,0.000600,0.981481,0.795000,0.878453,0.018519,0.205000,0.487445
22,239.2,0.997500,0.997500,0.002500,0.002593,0.938824,0.997500,0.967273,0.061176,0.002500,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.942212,0.942212,0.057788,0.002304,0.943651,0.942212,0.941587,0.056349,0.057788,0.653701

In [ ]:
cv_result40

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.648077  0.652052    0.351923  0.648077    0.656077
1       2.0  0.782692  0.788165    0.217308  0.782692    0.793715
2       3.0  0.683654  0.683372    0.316346  0.683654    0.683090
3       4.0  0.756731  0.761347    0.243269  0.756731    0.766019
4       5.0  0.647115  0.648609    0.352885  0.647115    0.650109
5       6.0  0.780769  0.784948    0.219231  0.780769    0.789173
6       7.0  0.661538  0.662790    0.338462  0.661538    0.664047
7       8.0  0.766346  0.772603    0.233654  0.766346    0.778963
8       9.0  0.668269  0.667956    0.331731  0.668269    0.667643
9      10.0  0.776923  0.781947    0.223077  0.776923    0.787036
10       11  0.942212  0.942931    0.057788  0.942212    0.943651
11  average  0.717212  0.720379    0.282788  0.717212    0.723587
12      max  0.782692  0.788165    0.217308  0.782692    0.793715

### SAVE MODEL dTOP40fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn40_double_sim.pkl', 'wb') as f:
   pickle.dump(knn40, f)

## TRAIN K-NN TOP 50fi

In [ ]:
# train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data50
X_train50 = train_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_train50 = train_data50['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=50, data_type='train')
timer.start()

knn50, data_top_5, Confusion_df50, eval_result50, cv_result50 = knn_custom_kfold_evaluation(X_train50, y_train50, le, 50, first_c50, last_c50, first_n50, last_n50, first_o50, last_o50, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 29.63it/s]
6it [00:00, 29.25it/s]
9it [00:00, 29.12it/s]
12it [00:00, 28.90it/s]
15it [00:00, 28.90it/s]
18it [00:00, 29.04it/s]
21it [00:00, 29.09it/s]
24it [00:00, 29.11it/s]
27it [00:00, 29.00it/s]
30it [00:01, 27.99it/s]
33it [00:01, 27.94it/s]
36it [00:01, 28.11it/s]
39it [00:01, 28.32it/s]
42it [00:01, 28.76it/s]
46it [00:01, 29.52it/s]
50it [00:01, 29.00it/s]
1it [00:02,  2.56s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 29.97it/s]
6it [00:00, 29.70it/s]
9it [00:00, 29.63it/s]
12it [00:00, 29.67it/s]
15it [00:00, 29.67it/s]
18it [00:00, 29.56it/s]
21it [00:00, 29.64it/s]
24it [00:00, 28.87it/s]
27it [00:00, 28.35it/s]
30it [00:01, 28.02it/s]
33it [00:01, 28.29it/s]
36it [00:01, 28.51it/s]
39it [00:01, 28.25it/s]
42it [00:01, 28.45it/s]
46it [00:01, 29.22it/s]
50it [00:01, 29.05it/s]
2it [00:04,  2.48s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
4it [00:00, 30.23it/s]
8it [00:00, 29.54it/s]
11it [00:00, 29.38it/s]
14it [00:00, 29.31it/s]
17it [00:00, 29.45it/s]
20it [00:00, 29.56it/s]
23it [00:00, 29.61it/s]
26it [00:00, 29.66it/s]
29it [00:00, 29.72it/s]
32it [00:01, 29.64it/s]
35it [00:01, 29.38it/s]
38it [00:01, 29.21it/s]
41it [00:01, 29.24it/s]
45it [00:01, 29.96it/s]
50it [00:01, 29.65it/s]
3it [00:07,  2.52s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 28.80it/s]
6it [00:00, 27.52it/s]
9it [00:00, 28.31it/s]
12it [00:00, 28.75it/s]
15it [00:00, 28.87it/s]
18it [00:00, 28.91it/s]
21it [00:00, 29.08it/s]
24it [00:00, 29.28it/s]
27it [00:00, 29.30it/s]
30it [00:01, 29.40it/s]
33it [00:01, 29.48it/s]
36it [00:01, 29.45it/s]
39it [00:01, 29.57it/s]
43it [00:01, 30.08it/s]
50it [00:01, 29.41it/s]
4it [00:09,  2.48s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 28.77it/s]
6it [00:00, 28.21it/s]
9it [00:00, 28.33it/s]
12it [00:00, 28.66it/s]
15it [00:00, 28.42it/s]
18it [00:00, 28.57it/s]
21it [00:00, 28.19it/s]
24it [00:00, 28.31it/s]
27it [00:00, 28.54it/s]
30it [00:01, 28.59it/s]
33it [00:01, 28.68it/s]
36it [00:01, 28.27it/s]
39it [00:01, 27.66it/s]
42it [00:01, 28.18it/s]
46it [00:01, 29.20it/s]
50it [00:01, 28.62it/s]
5it [00:12,  2.52s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 29.31it/s]
6it [00:00, 28.93it/s]
9it [00:00, 29.33it/s]
12it [00:00, 29.49it/s]
15it [00:00, 29.39it/s]
18it [00:00, 29.48it/s]
21it [00:00, 29.44it/s]
24it [00:00, 29.01it/s]
27it [00:00, 29.15it/s]
30it [00:01, 29.04it/s]
33it [00:01, 29.07it/s]
37it [00:01, 29.48it/s]
40it [00:01, 29.32it/s]
43it [00:01, 29.35it/s]
50it [00:01, 29.52it/s]
6it [00:14,  2.47s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
4it [00:00, 29.99it/s]
7it [00:00, 29.78it/s]
11it [00:00, 29.97it/s]
14it [00:00, 29.84it/s]
17it [00:00, 29.71it/s]
20it [00:00, 28.97it/s]
23it [00:00, 28.91it/s]
26it [00:00, 28.26it/s]
29it [00:01, 28.35it/s]
32it [00:01, 28.54it/s]
35it [00:01, 28.47it/s]
38it [00:01, 28.75it/s]
41it [00:01, 29.01it/s]
45it [00:01, 29.66it/s]
50it [00:01, 29.22it/s]
7it [00:17,  2.51s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 29.99it/s]
6it [00:00, 29.78it/s]
9it [00:00, 29.54it/s]
12it [00:00, 29.57it/s]
15it [00:00, 29.47it/s]
18it [00:00, 29.10it/s]
21it [00:00, 29.24it/s]
24it [00:00, 29.22it/s]
27it [00:00, 29.32it/s]
30it [00:01, 29.29it/s]
33it [00:01, 29.31it/s]
36it [00:01, 28.61it/s]
39it [00:01, 28.80it/s]
42it [00:01, 29.06it/s]
46it [00:01, 29.73it/s]
50it [00:01, 29.32it/s]
8it [00:19,  2.47s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
4it [00:00, 30.02it/s]
8it [00:00, 30.01it/s]
12it [00:00, 29.99it/s]
15it [00:00, 29.70it/s]
18it [00:00, 29.71it/s]
21it [00:00, 29.67it/s]
24it [00:00, 29.46it/s]
27it [00:00, 29.49it/s]
30it [00:01, 29.37it/s]
33it [00:01, 29.11it/s]
36it [00:01, 29.23it/s]
39it [00:01, 29.17it/s]
42it [00:01, 29.10it/s]
45it [00:01, 29.12it/s]
50it [00:01, 29.35it/s]
9it [00:22,  2.50s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 29.31it/s]
6it [00:00, 28.61it/s]
9it [00:00, 28.32it/s]
12it [00:00, 27.72it/s]
15it [00:00, 28.05it/s]
18it [00:00, 27.77it/s]
21it [00:00, 27.51it/s]
24it [00:00, 27.65it/s]
27it [00:00, 27.67it/s]
30it [00:01, 27.37it/s]
33it [00:01, 27.53it/s]
36it [00:01, 27.79it/s]
39it [00:01, 27.90it/s]
42it [00:01, 28.22it/s]
45it [00:01, 28.69it/s]
50it [00:01, 28.25it/s]
10it [00:24,  2.49s/it]

predict using best model..

90it [00:16,  5.62it/s]

done
Time taken: 0.79 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,41.0,0.190476,7.1,0.142857,5.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.333333,111.0,0.285714,239.2,0.142857,5.0,0.047619,98.9,0.047619
10398,169.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,111.0,0.095238,150.0,0.095238
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.476190,154.0,0.095238,185.9,0.095238,18.9,0.047619,146.0,0.047619

In [ ]:
Confusion_df50

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7.1,0,390,1,1,1,0,0,0,0,0,...,2,0,0,0,1,0,1,0,0,0
18.9,1,0,384,2,0,1,3,2,0,0,...,0,1,0,1,0,0,2,0,0,0
32.1,0,0,0,395,0,0,0,0,2,0,...,0,0,0,0,0,0,1,0,0,0
41.0,0,2,0,1,392,1,0,2,0,0,...,0,0,0,1,0,0,0,0,0,0
98.9,1,0,1,0,0,395,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
104.1,1,0,1,1,0,0,387,1,0,2,...,1,0,1,0,0,0,0,0,0,0
111.0,0,1,1,1,0,0,1,386,1,2,...,0,0,2,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,1,395,1,...,0,0,1,0,0,0,0,0,0,0
129.0,2,1,6,1,0,0,0,0,0,386,...,0,0,0,1,0,1,1,0,0,0
146.0,0,2,1,0,0,1,2,0,1,0,...,0,0,0,1,0,0,0,0,0,0
147.0,0,0,1,0,1,0,0,4,0,1,...,0,0,0,2,0,1,1,0,0,0
150.0,1,1,0,3,0,0,2,0,0,2,...,0,0,1,1,0,0,1,0,0,0
151.0,1,2,3,1,0,1,0,3,1,3,...,0,0,1,2,0,1,1,0,0,0
153.0,3,0,2,1,1,0,0,3,1,5,...,0,0,2,3,0,3,3,0,0,0
154.0,0,0,4,1,0,0,5,1,0,6,...,0,1,5,2,2,0,0,0,0,0
161.0,1,0,2,0,0,0,1,1,0,1,...,382,0,2,1,1,0,1,0,0,0
169.0,2,1,9,2,2,2,3,2,1,8,...,1,344,2,4,3,0,0,0,1,0
185.9,1,1,7,1,1,0,3,3,3,7,...,1,0,348,4,2,0,1,0,0,0
197.0,3,0,7,1,0,2,4,3,0,9,...,3,2,6,340,1,1,1,0,0,0
212.9,2,5,5,3,2,3,3,4,1,9,...,0,0,5,4,322,1,4,0,0,0
217.0,3,2,9,1,2,4,0,1,3,14,...,2,1,4,3,0,328,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.992500,0.992500,0.007500,0.002195,0.947494,0.992500,0.969475,0.052506,0.007500,-0.530944
1,7.1,0.975000,0.975000,0.025000,0.001797,0.955882,0.975000,0.965347,0.044118,0.025000,0.695736
2,18.9,0.960000,0.960000,0.040000,0.005964,0.864865,0.960000,0.909953,0.135135,0.040000,0.759175
3,32.1,0.987500,0.987500,0.012500,0.002096,0.949519,0.987500,0.968137,0.050481,0.012500,0.553497
4,41.0,0.980000,0.980000,0.020000,0.000999,0.975124,0.980000,0.977556,0.024876,0.020000,0.958271
5,98.9,0.987500,0.987500,0.012500,0.001498,0.963415,0.987500,0.975309,0.036585,0.012500,1.481441
6,104.1,0.967500,0.967500,0.032500,0.002693,0.934783,0.967500,0.950860,0.065217,0.032500,0.906417
7,111.0,0.965000,0.965000,0.035000,0.003090,0.925659,0.965000,0.944920,0.074341,0.035000,0.795505
8,128.0,0.987500,0.987500,0.012500,0.001398,0.965770,0.987500,0.976514,0.034230,0.012500,0.811297
9,129.0,0.965000,0.965000,0.035000,0.007050,0.844639,0.965000,0.900817,0.155361,0.035000,0.853958
10,146.0,0.970000,0.970000,0.030000,0.002991,0.928230,0.970000,0.948655,0.071770,0.030000,0.924453
11,147.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.602597
12,150.0,0.950000,0.950000,0.050000,0.003289,0.920097,0.950000,0.934809,0.079903,0.050000,0.780970
13,151.0,0.942500,0.942500,0.057500,0.001398,0.964194,0.942500,0.953224,0.035806,0.057500,0.908734
14,153.0,0.912500,0.912500,0.087500,0.002593,0.933504,0.912500,0.922882,0.066496,0.087500,0.756572
15,154.0,0.912500,0.912500,0.087500,0.002991,0.924051,0.912500,0.918239,0.075949,0.087500,0.606533
16,161.0,0.955000,0.955000,0.045000,0.001099,0.972010,0.955000,0.963430,0.027990,0.045000,0.868032
17,169.0,0.860000,0.860000,0.140000,0.000500,0.985673,0.860000,0.918558,0.014327,0.140000,0.743641
18,185.9,0.870000,0.870000,0.130000,0.003289,0.913386,0.870000,0.891165,0.086614,0.130000,0.719614
19,197.0,0.850000,0.850000,0.150000,0.003190,0.913978,0.850000,0.880829,0.086022,0.150000,0.583342
20,212.9,0.805000,0.805000,0.195000,0.000999,0.969880,0.805000,0.879781,0.030120,0.195000,0.583171
21,217.0,0.820000,0.820000,0.180000,0.000899,0.973294,0.820000,0.890095,0.026706,0.180000,0.474145
22,239.2,0.995000,0.995000,0.005000,0.002195,0.947619,0.995000,0.970732,0.052381,0.005000,2.309168
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.944231,0.944231,0.055769,0.002223,0.945635,0.944231,0.943752,0.054365,0.055769,0.715414

In [ ]:
cv_result50

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.652885  0.656302    0.347115  0.652885    0.659755
1       2.0  0.788462  0.794449    0.211538  0.788462    0.800528
2       3.0  0.680769  0.681237    0.319231  0.680769    0.681705
3       4.0  0.750962  0.756681    0.249038  0.750962    0.762488
4       5.0  0.650962  0.652415    0.349038  0.650962    0.653875
5       6.0  0.781731  0.785806    0.218269  0.781731    0.789923
6       7.0  0.661538  0.663408    0.338462  0.661538    0.665288
7       8.0  0.773077  0.779993    0.226923  0.773077    0.787033
8       9.0  0.668269  0.667575    0.331731  0.668269    0.666882
9      10.0  0.775000  0.780379    0.225000  0.775000    0.785833
10       11  0.944231  0.944932    0.055769  0.944231    0.945635
11  average  0.718365  0.721824    0.281635  0.718365    0.725331
12      max  0.788462  0.794449    0.211538  0.788462    0.800528

### SAVE MODEL dTOP50fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn50_double_sim.pkl', 'wb') as f:
   pickle.dump(knn50, f)

## TRAIN K-NN TOP 60fi

In [ ]:
# train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data60
X_train60 = train_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_train60 = train_data60['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=60, data_type='train')
timer.start()

knn60, data_top_5, Confusion_df60, eval_result60, cv_result60 = knn_custom_kfold_evaluation(X_train60, y_train60, le, 60, first_c60, last_c60, first_n60, last_n60, first_o60, last_o60, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 26.96it/s]
6it [00:00, 26.74it/s]
9it [00:00, 27.51it/s]
12it [00:00, 28.31it/s]
15it [00:00, 28.65it/s]
18it [00:00, 28.53it/s]
21it [00:00, 28.58it/s]
24it [00:00, 28.76it/s]
27it [00:00, 28.71it/s]
30it [00:01, 28.74it/s]
33it [00:01, 28.36it/s]
36it [00:01, 28.43it/s]
39it [00:01, 28.61it/s]
43it [00:01, 29.38it/s]
46it [00:01, 29.52it/s]
50it [00:01, 28.69it/s]
1it [00:02,  2.58s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 29.81it/s]
6it [00:00, 29.08it/s]
9it [00:00, 29.10it/s]
12it [00:00, 29.11it/s]
15it [00:00, 29.11it/s]
18it [00:00, 29.16it/s]
21it [00:00, 28.93it/s]
24it [00:00, 28.74it/s]
27it [00:00, 28.60it/s]
30it [00:01, 28.53it/s]
33it [00:01, 28.26it/s]
36it [00:01, 28.49it/s]
39it [00:01, 28.65it/s]
42it [00:01, 28.82it/s]
45it [00:01, 28.89it/s]
50it [00:01, 28.76it/s]
2it [00:05,  2.50s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 29.79it/s]
6it [00:00, 29.41it/s]
9it [00:00, 29.31it/s]
12it [00:00, 29.34it/s]
15it [00:00, 29.29it/s]
18it [00:00, 29.10it/s]
21it [00:00, 28.90it/s]
24it [00:00, 28.94it/s]
27it [00:00, 29.08it/s]
30it [00:01, 29.10it/s]
33it [00:01, 29.09it/s]
36it [00:01, 28.93it/s]
39it [00:01, 28.71it/s]
42it [00:01, 29.04it/s]
46it [00:01, 29.66it/s]
50it [00:01, 29.26it/s]
3it [00:07,  2.52s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 29.61it/s]
6it [00:00, 29.09it/s]
9it [00:00, 29.11it/s]
12it [00:00, 29.28it/s]
15it [00:00, 29.29it/s]
18it [00:00, 29.29it/s]
21it [00:00, 29.16it/s]
24it [00:00, 29.27it/s]
27it [00:00, 29.20it/s]
30it [00:01, 29.10it/s]
33it [00:01, 28.94it/s]
36it [00:01, 28.93it/s]
39it [00:01, 28.58it/s]
42it [00:01, 28.95it/s]
46it [00:01, 29.51it/s]
50it [00:01, 29.26it/s]
4it [00:09,  2.48s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 29.84it/s]
6it [00:00, 29.28it/s]
9it [00:00, 28.54it/s]
12it [00:00, 28.58it/s]
15it [00:00, 28.55it/s]
18it [00:00, 28.53it/s]
21it [00:00, 28.51it/s]
24it [00:00, 28.20it/s]
27it [00:00, 28.21it/s]
30it [00:01, 28.43it/s]
33it [00:01, 28.46it/s]
36it [00:01, 28.35it/s]
39it [00:01, 28.41it/s]
43it [00:01, 29.07it/s]
46it [00:01, 29.02it/s]
50it [00:01, 28.64it/s]
5it [00:12,  2.54s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 29.74it/s]
6it [00:00, 29.36it/s]
9it [00:00, 29.29it/s]
12it [00:00, 29.25it/s]
15it [00:00, 29.18it/s]
18it [00:00, 29.10it/s]
21it [00:00, 29.01it/s]
24it [00:00, 28.98it/s]
27it [00:00, 28.70it/s]
30it [00:01, 28.83it/s]
33it [00:01, 28.78it/s]
36it [00:01, 28.83it/s]
39it [00:01, 29.00it/s]
43it [00:01, 29.51it/s]
46it [00:01, 29.61it/s]
50it [00:01, 29.18it/s]
6it [00:15,  2.49s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 29.37it/s]
6it [00:00, 28.60it/s]
9it [00:00, 28.61it/s]
12it [00:00, 28.80it/s]
15it [00:00, 28.94it/s]
18it [00:00, 28.70it/s]
21it [00:00, 27.88it/s]
24it [00:00, 27.18it/s]
27it [00:00, 26.91it/s]
30it [00:01, 27.39it/s]
33it [00:01, 27.68it/s]
36it [00:01, 27.92it/s]
39it [00:01, 28.25it/s]
42it [00:01, 28.65it/s]
46it [00:01, 29.33it/s]
50it [00:01, 28.44it/s]
7it [00:17,  2.53s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 29.96it/s]
6it [00:00, 29.25it/s]
9it [00:00, 28.81it/s]
12it [00:00, 28.96it/s]
15it [00:00, 29.03it/s]
18it [00:00, 28.53it/s]
21it [00:00, 28.58it/s]
24it [00:00, 28.84it/s]
27it [00:00, 29.00it/s]
30it [00:01, 29.09it/s]
33it [00:01, 28.95it/s]
36it [00:01, 29.11it/s]
39it [00:01, 28.95it/s]
42it [00:01, 29.21it/s]
46it [00:01, 29.68it/s]
50it [00:01, 29.20it/s]
8it [00:20,  2.50s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 29.31it/s]
6it [00:00, 28.65it/s]
9it [00:00, 28.78it/s]
12it [00:00, 28.22it/s]
15it [00:00, 27.98it/s]
18it [00:00, 28.11it/s]
21it [00:00, 28.14it/s]
24it [00:00, 28.09it/s]
27it [00:00, 28.10it/s]
30it [00:01, 28.10it/s]
33it [00:01, 28.16it/s]
36it [00:01, 28.35it/s]
39it [00:01, 28.66it/s]
42it [00:01, 28.82it/s]
45it [00:01, 29.13it/s]
50it [00:01, 28.62it/s]
9it [00:22,  2.53s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 29.05it/s]
6it [00:00, 28.75it/s]
9it [00:00, 28.48it/s]
12it [00:00, 28.60it/s]
15it [00:00, 28.72it/s]
18it [00:00, 28.62it/s]
21it [00:00, 28.67it/s]
24it [00:00, 28.72it/s]
27it [00:00, 28.68it/s]
30it [00:01, 28.80it/s]
33it [00:01, 28.66it/s]
36it [00:01, 28.56it/s]
39it [00:01, 28.49it/s]
42it [00:01, 28.66it/s]
45it [00:01, 28.32it/s]
50it [00:01, 28.64it/s]
10it [00:25,  2.51s/it]

predict using best model..

90it [00:15,  5.63it/s]

done
Time taken: 0.79 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df60

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7.1,0,390,1,1,1,0,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,384,2,0,1,2,2,0,0,...,0,1,0,1,0,0,2,0,0,0
32.1,0,0,0,395,0,0,0,0,2,0,...,0,0,0,0,0,0,1,0,0,0
41.0,0,3,0,1,392,0,0,2,0,0,...,0,0,0,1,0,0,0,0,0,0
98.9,1,0,0,0,0,394,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
104.1,1,0,1,0,0,0,387,2,0,3,...,0,0,1,1,0,0,0,0,0,0
111.0,0,1,1,1,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,397,1,...,0,0,0,0,0,1,0,0,0,0
129.0,1,1,6,1,0,0,0,0,0,386,...,2,0,0,1,0,0,1,0,0,0
146.0,0,1,1,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,1,0,1,0,0,5,0,1,...,0,0,0,1,0,1,1,0,0,0
150.0,1,0,0,1,0,0,2,1,0,2,...,0,0,2,1,1,0,1,0,0,0
151.0,1,1,2,1,0,1,0,3,1,3,...,1,0,1,0,0,2,1,0,0,0
153.0,1,1,3,1,1,1,0,3,1,5,...,0,0,2,3,1,3,3,0,0,0
154.0,0,0,5,0,1,1,3,3,0,5,...,0,2,5,1,2,0,0,0,0,0
161.0,0,0,1,0,2,0,0,2,0,1,...,381,1,2,1,1,0,2,0,0,0
169.0,3,2,8,2,1,1,3,2,2,11,...,0,343,2,4,3,0,0,0,1,0
185.9,3,3,7,0,2,0,2,3,3,8,...,0,0,345,3,2,0,1,0,0,0
197.0,3,1,6,1,0,4,4,1,0,7,...,3,2,6,346,1,0,1,0,0,0
212.9,2,4,6,3,2,4,3,4,0,8,...,2,2,7,3,315,0,7,0,0,0
217.0,1,2,11,1,2,6,0,0,3,14,...,1,1,5,3,0,324,6,0,0,0
239.2,0,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.992500,0.992500,0.007500,0.001896,0.954327,0.992500,0.973039,0.045673,0.007500,-0.530944
1,7.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.704070
2,18.9,0.960000,0.960000,0.040000,0.005964,0.864865,0.960000,0.909953,0.135135,0.040000,0.844398
3,32.1,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,0.553497
4,41.0,0.980000,0.980000,0.020000,0.001298,0.967901,0.980000,0.973913,0.032099,0.020000,0.969523
5,98.9,0.985000,0.985000,0.015000,0.001896,0.953995,0.985000,0.969250,0.046005,0.015000,0.871182
6,104.1,0.967500,0.967500,0.032500,0.002096,0.948529,0.967500,0.957921,0.051471,0.032500,0.743603
7,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.808743
8,128.0,0.992500,0.992500,0.007500,0.001398,0.965937,0.992500,0.979038,0.034063,0.007500,0.807951
9,129.0,0.965000,0.965000,0.035000,0.007050,0.844639,0.965000,0.900817,0.155361,0.035000,0.818519
10,146.0,0.980000,0.980000,0.020000,0.003090,0.926714,0.980000,0.952612,0.073286,0.020000,0.633219
11,147.0,0.962500,0.962500,0.037500,0.003190,0.923261,0.962500,0.942472,0.076739,0.037500,0.554034
12,150.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.732741
13,151.0,0.947500,0.947500,0.052500,0.001298,0.966837,0.947500,0.957071,0.033163,0.052500,0.824908
14,153.0,0.902500,0.902500,0.097500,0.002593,0.932817,0.902500,0.917408,0.067183,0.097500,0.673242
15,154.0,0.907500,0.907500,0.092500,0.002991,0.923664,0.907500,0.915511,0.076336,0.092500,0.705746
16,161.0,0.952500,0.952500,0.047500,0.001199,0.969466,0.952500,0.960908,0.030534,0.047500,0.754308
17,169.0,0.857500,0.857500,0.142500,0.000999,0.971671,0.857500,0.911023,0.028329,0.142500,0.516916
18,185.9,0.862500,0.862500,0.137500,0.003587,0.905512,0.862500,0.883483,0.094488,0.137500,0.667204
19,197.0,0.865000,0.865000,0.135000,0.002693,0.927614,0.865000,0.895213,0.072386,0.135000,0.684106
20,212.9,0.787500,0.787500,0.212500,0.001099,0.966258,0.787500,0.867769,0.033742,0.212500,0.634455
21,217.0,0.810000,0.810000,0.190000,0.000799,0.975904,0.810000,0.885246,0.024096,0.190000,0.509734
22,239.2,0.990000,0.990000,0.010000,0.002892,0.931765,0.990000,0.960000,0.068235,0.010000,1.030794
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.476642
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.943462,0.943462,0.056538,0.002254,0.944850,0.943462,0.942878,0.055150,0.056538,0.614946

In [ ]:
cv_result60

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.651923  0.654080    0.348077  0.651923    0.656252
1       2.0  0.785577  0.790990    0.214423  0.785577    0.796479
2       3.0  0.684615  0.684855    0.315385  0.684615    0.685095
3       4.0  0.750962  0.756850    0.249038  0.750962    0.762831
4       5.0  0.665385  0.668134    0.334615  0.665385    0.670907
5       6.0  0.784615  0.788136    0.215385  0.784615    0.791689
6       7.0  0.666346  0.668604    0.333654  0.666346    0.670877
7       8.0  0.770192  0.777550    0.229808  0.770192    0.785051
8       9.0  0.670192  0.670210    0.329808  0.670192    0.670228
9      10.0  0.775962  0.780611    0.224038  0.775962    0.785316
10       11  0.943462  0.944155    0.056538  0.943462    0.944850
11  average  0.720577  0.724002    0.279423  0.720577    0.727472
12      max  0.785577  0.790990    0.214423  0.785577    0.796479

In [ ]:
y_train60.value_counts()

tp_ICD_cl0
25    400
4     400
1     400
12    400
14    400
20    400
2     400
22    400
3     400
10    400
18    400
7     400
13    400
21    400
11    400
5     400
6     400
8     400
19    400
0     400
23    400
24    400
16    400
17    400
9     400
15    400
Name: count, dtype: int64

### SAVE MODEL dTOP60fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn60_double_sim.pkl', 'wb') as f:
   pickle.dump(knn60, f)

## TRAIN K-NN TOP 70fi

In [ ]:
# train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data70
X_train70 = train_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_train70 = train_data70['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=70, data_type='train')
timer.start()

knn70, data_top_5, Confusion_df70, eval_result70, cv_result70 = knn_custom_kfold_evaluation(X_train70, y_train70, le, 70, first_c70, last_c70, first_n70, last_n70, first_o70, last_o70, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 27.81it/s]
6it [00:00, 27.35it/s]
9it [00:00, 27.01it/s]
12it [00:00, 27.18it/s]
15it [00:00, 27.22it/s]
18it [00:00, 27.35it/s]
21it [00:00, 27.44it/s]
24it [00:00, 27.38it/s]
27it [00:00, 27.49it/s]
30it [00:01, 27.17it/s]
33it [00:01, 27.38it/s]
36it [00:01, 27.70it/s]
39it [00:01, 27.97it/s]
42it [00:01, 28.35it/s]
46it [00:01, 29.10it/s]
50it [00:01, 27.96it/s]
1it [00:02,  2.64s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 29.11it/s]
6it [00:00, 28.62it/s]
9it [00:00, 28.30it/s]
12it [00:00, 27.73it/s]
15it [00:00, 27.67it/s]
18it [00:00, 28.03it/s]
21it [00:00, 28.32it/s]
24it [00:00, 28.40it/s]
27it [00:00, 28.48it/s]
30it [00:01, 28.49it/s]
33it [00:01, 28.38it/s]
36it [00:01, 28.37it/s]
39it [00:01, 28.30it/s]
42it [00:01, 28.52it/s]
45it [00:01, 28.90it/s]
50it [00:01, 28.57it/s]
2it [00:05,  2.52s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 29.26it/s]
6it [00:00, 29.12it/s]
9it [00:00, 29.07it/s]
12it [00:00, 29.02it/s]
15it [00:00, 29.07it/s]
18it [00:00, 29.00it/s]
21it [00:00, 28.75it/s]
24it [00:00, 28.56it/s]
27it [00:00, 28.18it/s]
30it [00:01, 27.84it/s]
33it [00:01, 27.86it/s]
36it [00:01, 28.22it/s]
39it [00:01, 28.41it/s]
42it [00:01, 28.23it/s]
45it [00:01, 28.15it/s]
50it [00:01, 28.42it/s]
3it [00:07,  2.56s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 28.91it/s]
6it [00:00, 28.90it/s]
9it [00:00, 28.80it/s]
12it [00:00, 28.72it/s]
15it [00:00, 28.77it/s]
18it [00:00, 28.82it/s]
21it [00:00, 28.78it/s]
24it [00:00, 28.65it/s]
27it [00:00, 28.42it/s]
30it [00:01, 28.43it/s]
33it [00:01, 28.20it/s]
36it [00:01, 28.41it/s]
39it [00:01, 28.42it/s]
42it [00:01, 28.76it/s]
46it [00:01, 29.34it/s]
50it [00:01, 28.84it/s]
4it [00:10,  2.50s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 29.18it/s]
6it [00:00, 28.93it/s]
9it [00:00, 28.93it/s]
12it [00:00, 28.50it/s]
15it [00:00, 28.62it/s]
18it [00:00, 28.78it/s]
21it [00:00, 28.56it/s]
24it [00:00, 28.54it/s]
27it [00:00, 28.50it/s]
30it [00:01, 28.13it/s]
33it [00:01, 27.93it/s]
36it [00:01, 28.01it/s]
39it [00:01, 28.10it/s]
42it [00:01, 28.02it/s]
45it [00:01, 28.40it/s]
50it [00:01, 28.40it/s]
5it [00:12,  2.54s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 29.00it/s]
6it [00:00, 28.97it/s]
9it [00:00, 28.71it/s]
12it [00:00, 28.27it/s]
15it [00:00, 28.11it/s]
18it [00:00, 28.00it/s]
21it [00:00, 27.62it/s]
24it [00:00, 27.73it/s]
27it [00:00, 27.92it/s]
30it [00:01, 27.77it/s]
33it [00:01, 27.74it/s]
36it [00:01, 27.84it/s]
39it [00:01, 27.76it/s]
42it [00:01, 28.34it/s]
45it [00:01, 28.77it/s]
50it [00:01, 28.31it/s]
6it [00:15,  2.51s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 29.09it/s]
6it [00:00, 28.56it/s]
9it [00:00, 28.58it/s]
12it [00:00, 28.54it/s]
15it [00:00, 28.59it/s]
18it [00:00, 28.57it/s]
21it [00:00, 28.64it/s]
24it [00:00, 28.50it/s]
27it [00:00, 28.42it/s]
30it [00:01, 28.34it/s]
33it [00:01, 28.35it/s]
36it [00:01, 28.54it/s]
39it [00:01, 28.37it/s]
42it [00:01, 28.75it/s]
46it [00:01, 29.40it/s]
50it [00:01, 28.75it/s]
7it [00:17,  2.54s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 28.63it/s]
6it [00:00, 28.22it/s]
9it [00:00, 28.11it/s]
12it [00:00, 28.48it/s]
15it [00:00, 28.49it/s]
18it [00:00, 28.63it/s]
21it [00:00, 28.53it/s]
24it [00:00, 28.45it/s]
27it [00:00, 28.57it/s]
30it [00:01, 28.71it/s]
33it [00:01, 28.78it/s]
36it [00:01, 28.72it/s]
39it [00:01, 28.45it/s]
42it [00:01, 28.79it/s]
45it [00:01, 29.13it/s]
50it [00:01, 28.79it/s]
8it [00:20,  2.50s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 29.73it/s]
6it [00:00, 29.17it/s]
9it [00:00, 28.76it/s]
12it [00:00, 28.60it/s]
15it [00:00, 28.70it/s]
18it [00:00, 28.57it/s]
21it [00:00, 28.56it/s]
24it [00:00, 28.46it/s]
27it [00:00, 28.46it/s]
30it [00:01, 28.55it/s]
33it [00:01, 28.57it/s]
36it [00:01, 28.53it/s]
39it [00:01, 28.66it/s]
42it [00:01, 28.82it/s]
46it [00:01, 29.39it/s]
50it [00:01, 28.87it/s]
9it [00:22,  2.53s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 29.66it/s]
6it [00:00, 29.57it/s]
9it [00:00, 29.02it/s]
12it [00:00, 29.02it/s]
15it [00:00, 28.40it/s]
18it [00:00, 27.88it/s]
21it [00:00, 27.74it/s]
24it [00:00, 28.01it/s]
27it [00:00, 28.10it/s]
30it [00:01, 27.95it/s]
33it [00:01, 28.10it/s]
36it [00:01, 27.81it/s]
39it [00:01, 27.62it/s]
42it [00:01, 28.16it/s]
45it [00:01, 28.69it/s]
50it [00:01, 28.30it/s]
10it [00:25,  2.53s/it]

predict using best model..

90it [00:16,  5.59it/s]

done
Time taken: 0.80 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
2,41.0,248.0,0.523810,32.1,0.190476,5.0,0.142857,41.0,0.095238,18.9,0.047619
3,129.0,150.0,0.190476,129.0,0.142857,151.0,0.142857,217.0,0.142857,153.0,0.095238
4,169.0,5.0,0.428571,32.1,0.380952,98.9,0.142857,169.0,0.047619,NaN,NaN
5,161.0,161.0,0.285714,41.0,0.190476,169.0,0.190476,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.238095,239.2,0.190476,111.0,0.142857,5.0,0.095238,32.1,0.095238
10398,169.0,161.0,0.285714,41.0,0.238095,150.0,0.142857,169.0,0.142857,7.1,0.095238
10399,249.0,249.0,0.285714,251.0,0.285714,248.0,0.238095,18.9,0.095238,169.0,0.047619
10400,150.0,98.9,0.380952,239.2,0.142857,150.0,0.095238,154.0,0.095238,185.9,0.095238

In [ ]:
Confusion_df70

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,392,0,0,0,0,1,1,0,0,0,...,2,0,1,0,0,0,2,0,0,0
7.1,0,391,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,1
18.9,1,0,387,0,1,0,1,0,0,2,...,1,1,3,0,0,0,3,0,0,0
32.1,0,0,1,395,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
41.0,0,0,1,0,394,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,0
98.9,0,1,1,0,2,387,0,1,0,0,...,0,0,0,0,1,0,3,0,0,0
104.1,0,0,1,0,1,0,392,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,2,1,2,1,387,0,1,...,0,0,1,0,0,2,0,0,0,0
128.0,0,0,0,0,0,0,0,0,397,1,...,0,0,0,0,0,1,1,0,0,0
129.0,2,1,1,0,1,1,0,0,0,388,...,1,0,0,0,0,1,0,0,0,0
146.0,0,2,1,0,0,1,1,0,1,3,...,0,0,0,0,1,1,1,0,0,0
147.0,0,0,1,0,0,0,0,2,0,3,...,1,0,0,1,1,0,1,0,0,0
150.0,0,0,1,1,0,1,2,2,2,3,...,3,0,1,2,0,2,1,0,0,0
151.0,0,3,2,1,2,0,0,3,2,1,...,2,0,2,0,0,1,0,0,0,0
153.0,4,0,1,0,1,3,2,3,1,7,...,0,0,5,3,1,2,0,0,0,0
154.0,2,1,0,1,0,5,4,3,0,5,...,1,1,2,0,0,0,1,0,0,0
161.0,0,1,1,0,2,1,0,1,0,3,...,383,0,1,1,1,1,1,0,0,0
169.0,2,1,7,1,0,0,3,2,1,7,...,1,346,2,4,2,0,3,0,1,1
185.9,0,1,10,0,4,1,2,3,0,6,...,0,0,346,3,1,1,1,0,0,0
197.0,1,0,12,1,0,5,3,2,1,6,...,2,0,1,350,1,0,3,0,0,0
212.9,0,0,11,3,3,6,0,2,0,9,...,1,1,5,2,325,2,5,0,0,0
217.0,3,2,13,3,1,7,1,1,5,16,...,0,1,4,1,0,304,9,0,0,0
239.2,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.980000,0.980000,0.020000,0.001498,0.963145,0.980000,0.971499,0.036855,0.020000,0.399327
1,7.1,0.977500,0.977500,0.022500,0.001298,0.967822,0.977500,0.972637,0.032178,0.022500,0.731309
2,18.9,0.967500,0.967500,0.032500,0.006557,0.854305,0.967500,0.907386,0.145695,0.032500,0.576582
3,32.1,0.987500,0.987500,0.012500,0.001398,0.965770,0.987500,0.976514,0.034230,0.012500,0.941369
4,41.0,0.985000,0.985000,0.015000,0.001896,0.953995,0.985000,0.969250,0.046005,0.015000,0.459392
5,98.9,0.967500,0.967500,0.032500,0.003488,0.917062,0.967500,0.941606,0.082938,0.032500,0.605607
6,104.1,0.980000,0.980000,0.020000,0.002195,0.946860,0.980000,0.963145,0.053140,0.020000,0.670553
7,111.0,0.967500,0.967500,0.032500,0.002593,0.937046,0.967500,0.952030,0.062954,0.032500,0.799592
8,128.0,0.992500,0.992500,0.007500,0.001298,0.968293,0.992500,0.980247,0.031707,0.007500,0.760682
9,129.0,0.970000,0.970000,0.030000,0.007346,0.839827,0.970000,0.900232,0.160173,0.030000,1.251424
10,146.0,0.955000,0.955000,0.045000,0.002494,0.938575,0.955000,0.946716,0.061425,0.045000,0.800908
11,147.0,0.952500,0.952500,0.047500,0.003090,0.924757,0.952500,0.938424,0.075243,0.047500,0.634781
12,150.0,0.935000,0.935000,0.065000,0.003885,0.905569,0.935000,0.920049,0.094431,0.065000,0.709578
13,151.0,0.940000,0.940000,0.060000,0.001896,0.951899,0.940000,0.945912,0.048101,0.060000,0.931151
14,153.0,0.895000,0.895000,0.105000,0.002593,0.932292,0.895000,0.913265,0.067708,0.105000,0.620185
15,154.0,0.907500,0.907500,0.092500,0.004182,0.896296,0.907500,0.901863,0.103704,0.092500,0.714007
16,161.0,0.957500,0.957500,0.042500,0.001597,0.959900,0.957500,0.958698,0.040100,0.042500,0.740225
17,169.0,0.865000,0.865000,0.135000,0.000400,0.988571,0.865000,0.922667,0.011429,0.135000,0.713436
18,185.9,0.865000,0.865000,0.135000,0.002892,0.922667,0.865000,0.892903,0.077333,0.135000,0.764706
19,197.0,0.875000,0.875000,0.125000,0.001896,0.948509,0.875000,0.910273,0.051491,0.125000,0.789113
20,212.9,0.812500,0.812500,0.187500,0.000899,0.973054,0.812500,0.885559,0.026946,0.187500,0.758464
21,217.0,0.760000,0.760000,0.240000,0.001398,0.955975,0.760000,0.846797,0.044025,0.240000,0.508982
22,239.2,0.995000,0.995000,0.005000,0.003885,0.910755,0.995000,0.951016,0.089245,0.005000,4.344157
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000100,0.997455,0.980000,0.988651,0.002545,0.020000,0.434680
25,251.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
26,average,0.941154,0.941154,0.058846,0.002345,0.942901,0.941154,0.940571,0.057099,0.058846,0.794623

In [ ]:
cv_result70

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.660577  0.662937    0.339423  0.660577    0.665315
1       2.0  0.779808  0.785735    0.220192  0.779808    0.791753
2       3.0  0.690385  0.690263    0.309615  0.690385    0.690142
3       4.0  0.750962  0.758664    0.249038  0.750962    0.766527
4       5.0  0.666346  0.669124    0.333654  0.666346    0.671925
5       6.0  0.782692  0.787919    0.217308  0.782692    0.793215
6       7.0  0.660577  0.662920    0.339423  0.660577    0.665280
7       8.0  0.759615  0.767606    0.240385  0.759615    0.775767
8       9.0  0.675000  0.675017    0.325000  0.675000    0.675035
9      10.0  0.779808  0.784473    0.220192  0.779808    0.789195
10       11  0.941154  0.942027    0.058846  0.941154    0.942901
11  average  0.720577  0.724466    0.279423  0.720577    0.728415
12      max  0.782692  0.787919    0.217308  0.782692    0.793215

### SAVE MODEL dTOP70fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn70_double_sim.pkl', 'wb') as f:
   pickle.dump(knn70, f)

## TRAIN K-NN TOP 80fi

In [ ]:
# train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data80
X_train80 = train_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_train80 = train_data80['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=80, data_type='train')
timer.start()

knn80, data_top_5, Confusion_df80, eval_result80, cv_result80 = knn_custom_kfold_evaluation(X_train80, y_train80, le, 80, first_c80, last_c80, first_n80, last_n80, first_o80, last_o80, batch=True, n_neighbors=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 28.31it/s]
6it [00:00, 28.17it/s]
9it [00:00, 28.06it/s]
12it [00:00, 27.95it/s]
15it [00:00, 28.10it/s]
18it [00:00, 27.98it/s]
21it [00:00, 27.92it/s]
24it [00:00, 27.54it/s]
27it [00:00, 27.24it/s]
30it [00:01, 26.93it/s]
33it [00:01, 26.95it/s]
36it [00:01, 27.00it/s]
39it [00:01, 26.98it/s]
42it [00:01, 27.44it/s]
45it [00:01, 27.74it/s]
50it [00:01, 27.64it/s]
1it [00:02,  2.66s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 28.62it/s]
6it [00:00, 27.98it/s]
9it [00:00, 27.90it/s]
12it [00:00, 27.88it/s]
15it [00:00, 27.91it/s]
18it [00:00, 28.01it/s]
21it [00:00, 28.00it/s]
24it [00:00, 27.87it/s]
27it [00:00, 27.73it/s]
30it [00:01, 27.84it/s]
33it [00:01, 27.79it/s]
36it [00:01, 27.87it/s]
39it [00:01, 27.80it/s]
42it [00:01, 27.95it/s]
45it [00:01, 27.47it/s]
50it [00:01, 27.91it/s]
2it [00:05,  2.55s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 28.79it/s]
6it [00:00, 28.56it/s]
9it [00:00, 28.59it/s]
12it [00:00, 28.44it/s]
15it [00:00, 28.43it/s]
18it [00:00, 28.60it/s]
21it [00:00, 28.35it/s]
24it [00:00, 28.41it/s]
27it [00:00, 28.20it/s]
30it [00:01, 27.95it/s]
33it [00:01, 27.94it/s]
36it [00:01, 27.96it/s]
39it [00:01, 28.11it/s]
42it [00:01, 28.09it/s]
45it [00:01, 28.44it/s]
50it [00:01, 28.41it/s]
3it [00:07,  2.57s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 29.06it/s]
6it [00:00, 28.77it/s]
9it [00:00, 28.34it/s]
12it [00:00, 27.98it/s]
15it [00:00, 27.75it/s]
18it [00:00, 27.93it/s]
21it [00:00, 28.05it/s]
24it [00:00, 27.96it/s]
27it [00:00, 28.07it/s]
30it [00:01, 28.10it/s]
33it [00:01, 28.12it/s]
36it [00:01, 28.18it/s]
39it [00:01, 28.26it/s]
42it [00:01, 28.34it/s]
45it [00:01, 28.72it/s]
50it [00:01, 28.39it/s]
4it [00:10,  2.52s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 28.19it/s]
6it [00:00, 28.13it/s]
9it [00:00, 28.14it/s]
12it [00:00, 27.96it/s]
15it [00:00, 27.96it/s]
18it [00:00, 27.94it/s]
21it [00:00, 27.93it/s]
24it [00:00, 28.16it/s]
27it [00:00, 28.23it/s]
30it [00:01, 28.02it/s]
33it [00:01, 28.20it/s]
36it [00:01, 28.28it/s]
39it [00:01, 28.27it/s]
42it [00:01, 28.45it/s]
45it [00:01, 28.50it/s]
50it [00:01, 28.19it/s]
5it [00:12,  2.56s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 27.66it/s]
6it [00:00, 27.11it/s]
9it [00:00, 27.32it/s]
12it [00:00, 27.49it/s]
15it [00:00, 27.38it/s]
18it [00:00, 27.44it/s]
21it [00:00, 27.42it/s]
24it [00:00, 26.71it/s]
27it [00:00, 26.75it/s]
30it [00:01, 26.92it/s]
33it [00:01, 26.92it/s]
36it [00:01, 26.89it/s]
39it [00:01, 26.84it/s]
42it [00:01, 26.59it/s]
45it [00:01, 26.59it/s]
50it [00:01, 27.03it/s]
6it [00:15,  2.55s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 29.10it/s]
6it [00:00, 28.81it/s]
9it [00:00, 28.65it/s]
12it [00:00, 28.59it/s]
15it [00:00, 28.42it/s]
18it [00:00, 28.35it/s]
21it [00:00, 28.34it/s]
24it [00:00, 28.25it/s]
27it [00:00, 28.28it/s]
30it [00:01, 28.15it/s]
33it [00:01, 28.22it/s]
36it [00:01, 28.26it/s]
39it [00:01, 28.29it/s]
42it [00:01, 28.34it/s]
45it [00:01, 28.49it/s]
50it [00:01, 28.51it/s]
7it [00:17,  2.56s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 29.05it/s]
6it [00:00, 28.45it/s]
9it [00:00, 28.45it/s]
12it [00:00, 28.37it/s]
15it [00:00, 28.18it/s]
18it [00:00, 28.22it/s]
21it [00:00, 28.23it/s]
24it [00:00, 28.30it/s]
27it [00:00, 28.23it/s]
30it [00:01, 28.22it/s]
33it [00:01, 28.17it/s]
36it [00:01, 27.94it/s]
39it [00:01, 27.67it/s]
42it [00:01, 27.94it/s]
45it [00:01, 28.18it/s]
50it [00:01, 28.21it/s]
8it [00:20,  2.53s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 28.73it/s]
6it [00:00, 28.45it/s]
9it [00:00, 28.15it/s]
12it [00:00, 28.19it/s]
15it [00:00, 27.66it/s]
18it [00:00, 27.72it/s]
21it [00:00, 27.77it/s]
24it [00:00, 27.83it/s]
27it [00:00, 27.73it/s]
30it [00:01, 27.78it/s]
33it [00:01, 27.72it/s]
36it [00:01, 27.80it/s]
39it [00:01, 27.86it/s]
42it [00:01, 27.97it/s]
45it [00:01, 28.36it/s]
50it [00:01, 28.07it/s]
9it [00:22,  2.56s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 28.39it/s]
6it [00:00, 27.55it/s]
9it [00:00, 27.09it/s]
12it [00:00, 27.37it/s]
15it [00:00, 27.66it/s]
18it [00:00, 27.61it/s]
21it [00:00, 27.52it/s]
24it [00:00, 27.38it/s]
27it [00:00, 27.40it/s]
30it [00:01, 27.19it/s]
33it [00:01, 27.12it/s]
36it [00:01, 27.34it/s]
39it [00:01, 27.39it/s]
42it [00:01, 27.66it/s]
45it [00:01, 27.91it/s]
50it [00:01, 27.60it/s]
10it [00:25,  2.56s/it]

predict using best model..

90it [00:16,  5.56it/s]

done
Time taken: 0.80 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df80

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,2,0,385,0,0,1,2,1,0,2,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,0,392,0,1,0,1,...,1,0,0,1,0,0,0,0,0,0
104.1,1,0,0,0,0,0,389,2,0,4,...,0,0,0,0,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,384,1,1,...,0,0,2,2,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,1,398,0,...,0,0,1,0,0,0,0,0,0,0
129.0,0,1,5,1,2,0,0,0,0,388,...,0,1,0,0,0,0,1,0,0,0
146.0,0,2,0,0,0,0,1,0,1,0,...,0,1,1,1,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,2,0,2,...,1,1,0,0,0,1,0,0,0,0
150.0,1,0,0,1,1,1,2,0,0,1,...,0,0,1,1,0,0,1,0,0,0
151.0,2,2,3,1,0,1,0,2,0,2,...,1,0,4,0,1,1,1,0,0,0
153.0,3,0,2,1,0,0,2,2,2,3,...,0,0,2,3,1,2,4,0,0,0
154.0,1,0,6,2,0,2,2,3,0,5,...,0,1,4,1,2,0,0,0,0,0
161.0,1,0,2,1,0,0,0,2,0,2,...,379,1,3,1,1,2,1,0,0,0
169.0,2,1,9,1,0,1,4,0,1,7,...,1,349,2,4,3,1,0,0,1,0
185.9,2,3,6,2,1,1,5,2,3,9,...,2,0,341,2,3,0,1,0,0,0
197.0,2,2,8,1,4,4,3,3,0,9,...,0,2,5,338,1,0,2,0,0,0
212.9,1,5,7,4,2,3,2,5,0,8,...,0,1,8,2,318,0,6,0,0,0
217.0,2,2,10,2,2,5,0,1,3,11,...,1,2,6,4,0,324,6,0,0,0
239.2,0,0,0,1,0,0,0,0,1,1,...,0,0,1,0,0,0,395,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001996,0.952153,0.995000,0.973105,0.047847,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002096,0.949029,0.977500,0.963054,0.050971,0.022500,0.680443
2,18.9,0.962500,0.962500,0.037500,0.006261,0.859375,0.962500,0.908019,0.140625,0.037500,0.998066
3,32.1,0.990000,0.990000,0.010000,0.002195,0.947368,0.990000,0.968215,0.052632,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001199,0.970297,0.980000,0.975124,0.029703,0.020000,1.101860
5,98.9,0.980000,0.980000,0.020000,0.002096,0.949153,0.980000,0.964330,0.050847,0.020000,0.695463
6,104.1,0.972500,0.972500,0.027500,0.002394,0.941889,0.972500,0.956950,0.058111,0.027500,0.594823
7,111.0,0.960000,0.960000,0.040000,0.002792,0.932039,0.960000,0.945813,0.067961,0.040000,0.713443
8,128.0,0.995000,0.995000,0.005000,0.001199,0.970732,0.995000,0.982716,0.029268,0.005000,1.877443
9,129.0,0.970000,0.970000,0.030000,0.006853,0.849015,0.970000,0.905484,0.150985,0.030000,0.828617
10,146.0,0.972500,0.972500,0.027500,0.002693,0.935096,0.972500,0.953431,0.064904,0.027500,0.885249
11,147.0,0.967500,0.967500,0.032500,0.002892,0.930288,0.967500,0.948529,0.069712,0.032500,0.597626
12,150.0,0.965000,0.965000,0.035000,0.002892,0.930120,0.965000,0.947239,0.069880,0.035000,0.881925
13,151.0,0.942500,0.942500,0.057500,0.001896,0.952020,0.942500,0.947236,0.047980,0.057500,0.836667
14,153.0,0.910000,0.910000,0.090000,0.002494,0.935733,0.910000,0.922687,0.064267,0.090000,0.814605
15,154.0,0.910000,0.910000,0.090000,0.002892,0.926209,0.910000,0.918033,0.073791,0.090000,0.762807
16,161.0,0.947500,0.947500,0.052500,0.000899,0.976804,0.947500,0.961929,0.023196,0.052500,0.767246
17,169.0,0.872500,0.872500,0.127500,0.001099,0.969444,0.872500,0.918421,0.030556,0.127500,0.765681
18,185.9,0.852500,0.852500,0.147500,0.003984,0.895013,0.852500,0.873239,0.104987,0.147500,0.552535
19,197.0,0.845000,0.845000,0.155000,0.002295,0.936288,0.845000,0.888305,0.063712,0.155000,0.638644
20,212.9,0.795000,0.795000,0.205000,0.001199,0.963636,0.795000,0.871233,0.036364,0.205000,0.661025
21,217.0,0.810000,0.810000,0.190000,0.000700,0.978852,0.810000,0.886457,0.021148,0.190000,0.620128
22,239.2,0.987500,0.987500,0.012500,0.002892,0.931604,0.987500,0.958738,0.068396,0.012500,0.980094
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.547783
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.944038,0.944038,0.055962,0.002231,0.945370,0.944038,0.943442,0.054630,0.055962,0.548124

In [ ]:
cv_result80

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.663462  0.666790    0.336538  0.663462    0.670151
1       2.0  0.780769  0.786803    0.219231  0.780769    0.792931
2       3.0  0.688462  0.687689    0.311538  0.688462    0.686919
3       4.0  0.742308  0.748215    0.257692  0.742308    0.754217
4       5.0  0.663462  0.665626    0.336538  0.663462    0.667804
5       6.0  0.777885  0.784658    0.222115  0.777885    0.791551
6       7.0  0.664423  0.666270    0.335577  0.664423    0.668127
7       8.0  0.758654  0.765867    0.241346  0.758654    0.773219
8       9.0  0.673077  0.672638    0.326923  0.673077    0.672200
9      10.0  0.767308  0.773894    0.232692  0.767308    0.780595
10       11  0.944038  0.944704    0.055962  0.944038    0.945370
11  average  0.717981  0.721845    0.282019  0.717981    0.725771
12      max  0.780769  0.786803    0.219231  0.780769    0.792931

### SAVE MODEL dTOP80fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn80_double_sim.pkl', 'wb') as f:
   pickle.dump(knn80, f)

## TRAIN K-NN TOP 90fi

In [ ]:
# train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data90
X_train90 = train_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_train90 = train_data90['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=90, data_type='train')
timer.start()

knn90, data_top_5, Confusion_df90, eval_result90, cv_result90 = knn_custom_kfold_evaluation(X_train90, y_train90, le, 90, first_c90, last_c90, first_n90, last_n90, first_o90, last_o90, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
1it [00:01,  1.30s/it]
4it [00:01,  3.59it/s]
7it [00:01,  6.69it/s]
10it [00:01,  9.94it/s]
13it [00:01, 13.09it/s]
16it [00:01, 15.93it/s]
19it [00:01, 18.44it/s]
22it [00:02, 20.33it/s]
25it [00:02, 21.60it/s]
28it [00:02, 22.97it/s]
31it [00:02, 24.02it/s]
34it [00:02, 24.76it/s]
37it [00:02, 25.54it/s]
40it [00:02, 26.03it/s]
43it [00:02, 26.70it/s]
46it [00:02, 27.06it/s]
50it [00:03, 15.96it/s]
1it [00:03,  3.97s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 27.71it/s]
6it [00:00, 27.35it/s]
9it [00:00, 27.25it/s]
12it [00:00, 27.39it/s]
15it [00:00, 27.22it/s]
18it [00:00, 27.23it/s]
21it [00:00, 27.30it/s]
24it [00:00, 27.30it/s]
27it [00:00, 27.50it/s]
30it [00:01, 27.46it/s]
33it [00:01, 27.41it/s]
36it [00:01, 27.36it/s]
39it [00:01, 27.33it/s]
42it [00:01, 27.37it/s]
45it [00:01, 27.31it/s]
50it [00:01, 27.40it/s]
2it [00:06,  3.13s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 27.74it/s]
6it [00:00, 27.42it/s]
9it [00:00, 27.32it/s]
12it [00:00, 27.45it/s]
15it [00:00, 27.42it/s]
18it [00:00, 27.41it/s]
21it [00:00, 27.13it/s]
24it [00:00, 26.39it/s]
27it [00:01, 26.22it/s]
30it [00:01, 26.58it/s]
33it [00:01, 26.62it/s]
36it [00:01, 26.71it/s]
39it [00:01, 26.78it/s]
42it [00:01, 27.07it/s]
45it [00:01, 27.56it/s]
50it [00:01, 27.18it/s]
3it [00:09,  2.92s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 27.51it/s]
6it [00:00, 27.37it/s]
9it [00:00, 27.18it/s]
12it [00:00, 27.04it/s]
15it [00:00, 27.25it/s]
18it [00:00, 27.24it/s]
21it [00:00, 27.27it/s]
24it [00:00, 27.26it/s]
27it [00:00, 27.31it/s]
30it [00:01, 27.31it/s]
33it [00:01, 27.46it/s]
36it [00:01, 27.07it/s]
39it [00:01, 27.18it/s]
42it [00:01, 26.96it/s]
45it [00:01, 27.21it/s]
50it [00:01, 27.29it/s]
4it [00:11,  2.76s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 27.45it/s]
6it [00:00, 26.69it/s]
9it [00:00, 26.88it/s]
12it [00:00, 27.21it/s]
15it [00:00, 26.96it/s]
18it [00:00, 26.71it/s]
21it [00:00, 26.60it/s]
24it [00:00, 26.62it/s]
27it [00:01, 26.87it/s]
30it [00:01, 26.81it/s]
33it [00:01, 26.86it/s]
36it [00:01, 26.78it/s]
39it [00:01, 26.72it/s]
42it [00:01, 26.98it/s]
45it [00:01, 27.51it/s]
50it [00:01, 27.04it/s]
5it [00:14,  2.75s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 27.82it/s]
6it [00:00, 27.78it/s]
9it [00:00, 27.70it/s]
12it [00:00, 27.45it/s]
15it [00:00, 27.36it/s]
18it [00:00, 27.35it/s]
21it [00:00, 27.38it/s]
24it [00:00, 27.32it/s]
27it [00:00, 27.41it/s]
30it [00:01, 27.22it/s]
33it [00:01, 27.23it/s]
36it [00:01, 27.29it/s]
39it [00:01, 27.25it/s]
42it [00:01, 27.47it/s]
45it [00:01, 27.77it/s]
50it [00:01, 27.58it/s]
6it [00:16,  2.68s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 26.53it/s]
6it [00:00, 27.03it/s]
9it [00:00, 27.13it/s]
12it [00:00, 27.13it/s]
15it [00:00, 27.26it/s]
18it [00:00, 27.53it/s]
21it [00:00, 27.07it/s]
24it [00:00, 26.96it/s]
27it [00:01, 26.74it/s]
30it [00:01, 26.40it/s]
33it [00:01, 26.55it/s]
36it [00:01, 26.75it/s]
39it [00:01, 26.91it/s]
42it [00:01, 27.30it/s]
45it [00:01, 27.82it/s]
50it [00:01, 27.25it/s]
7it [00:19,  2.68s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 27.77it/s]
6it [00:00, 27.47it/s]
9it [00:00, 27.58it/s]
12it [00:00, 27.32it/s]
15it [00:00, 27.37it/s]
18it [00:00, 27.39it/s]
21it [00:00, 27.48it/s]
24it [00:00, 27.50it/s]
27it [00:00, 27.55it/s]
30it [00:01, 27.29it/s]
33it [00:01, 27.38it/s]
36it [00:01, 27.43it/s]
39it [00:01, 27.41it/s]
42it [00:01, 27.78it/s]
45it [00:01, 27.99it/s]
50it [00:01, 27.63it/s]
8it [00:22,  2.62s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 27.63it/s]
6it [00:00, 27.30it/s]
9it [00:00, 27.03it/s]
12it [00:00, 26.76it/s]
15it [00:00, 26.70it/s]
18it [00:00, 26.72it/s]
21it [00:00, 26.75it/s]
24it [00:00, 26.78it/s]
27it [00:01, 26.94it/s]
30it [00:01, 27.04it/s]
33it [00:01, 27.20it/s]
36it [00:01, 27.07it/s]
39it [00:01, 27.14it/s]
42it [00:01, 27.41it/s]
45it [00:01, 27.63it/s]
50it [00:01, 27.23it/s]
9it [00:24,  2.64s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 27.81it/s]
6it [00:00, 27.39it/s]
9it [00:00, 27.26it/s]
12it [00:00, 26.77it/s]
15it [00:00, 26.56it/s]
18it [00:00, 26.69it/s]
21it [00:00, 26.66it/s]
24it [00:00, 26.58it/s]
27it [00:01, 26.36it/s]
30it [00:01, 26.17it/s]
33it [00:01, 26.18it/s]
36it [00:01, 26.01it/s]
39it [00:01, 25.39it/s]
42it [00:01, 25.31it/s]
45it [00:01, 25.85it/s]
50it [00:01, 26.33it/s]
10it [00:27,  2.74s/it]

predict using best model..

90it [00:16,  5.52it/s]

done
Time taken: 0.83 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df90

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,0,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
129.0,1,1,6,1,1,0,0,0,0,388,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,0,1,0,0,0,0
150.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,2,0,0,0,4,0,4,...,1,1,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,1,3,1,6,...,0,0,1,4,1,3,3,0,0,0
154.0,1,1,5,2,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
161.0,0,2,1,0,2,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,10,...,1,343,2,4,3,0,1,0,1,0
185.9,1,3,8,0,1,2,2,6,5,12,...,1,0,335,2,3,0,2,0,0,0
197.0,2,3,10,2,1,3,6,4,0,8,...,1,1,5,332,1,2,2,0,0,0
212.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,317,0,5,0,0,0
217.0,2,4,11,3,1,6,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001498,0.963680,0.995000,0.979090,0.036320,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
2,18.9,0.965000,0.965000,0.035000,0.007247,0.840959,0.965000,0.898719,0.159041,0.035000,0.843988
3,32.1,0.990000,0.990000,0.010000,0.002096,0.949640,0.990000,0.969400,0.050360,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
5,98.9,0.982500,0.982500,0.017500,0.002295,0.944712,0.982500,0.963235,0.055288,0.017500,0.743315
6,104.1,0.975000,0.975000,0.025000,0.002195,0.946602,0.975000,0.960591,0.053398,0.025000,0.495457
7,111.0,0.962500,0.962500,0.037500,0.003388,0.918854,0.962500,0.940171,0.081146,0.037500,0.831063
8,128.0,0.995000,0.995000,0.005000,0.001398,0.966019,0.995000,0.980296,0.033981,0.005000,1.156444
9,129.0,0.970000,0.970000,0.030000,0.008920,0.811715,0.970000,0.883827,0.188285,0.030000,0.830807
10,146.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.754017
11,147.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.581016
12,150.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.908066
13,151.0,0.935000,0.935000,0.065000,0.001697,0.956522,0.935000,0.945638,0.043478,0.065000,0.743932
14,153.0,0.897500,0.897500,0.102500,0.002195,0.942257,0.897500,0.919334,0.057743,0.102500,0.622271
15,154.0,0.892500,0.892500,0.107500,0.003190,0.917738,0.892500,0.904943,0.082262,0.107500,0.597606
16,161.0,0.937500,0.937500,0.062500,0.000799,0.979112,0.937500,0.957854,0.020888,0.062500,0.747673
17,169.0,0.857500,0.857500,0.142500,0.001099,0.968927,0.857500,0.909814,0.031073,0.142500,0.618824
18,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.491757
19,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.764709
20,212.9,0.792500,0.792500,0.207500,0.001199,0.963526,0.792500,0.869684,0.036474,0.207500,0.751471
21,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472451
22,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.938942,0.938942,0.061058,0.002432,0.940993,0.938942,0.938308,0.059007,0.061058,0.482145

In [ ]:
cv_result90

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.660577  0.663653    0.339423  0.660577    0.666757
1       2.0  0.778846  0.788418    0.221154  0.778846    0.798228
2       3.0  0.689423  0.689491    0.310577  0.689423    0.689558
3       4.0  0.739423  0.745998    0.260577  0.739423    0.752691
4       5.0  0.662500  0.665176    0.337500  0.662500    0.667875
5       6.0  0.775000  0.782269    0.225000  0.775000    0.789676
6       7.0  0.664423  0.666303    0.335577  0.664423    0.668194
7       8.0  0.750962  0.759401    0.249038  0.750962    0.768033
8       9.0  0.666346  0.665668    0.333654  0.666346    0.664990
9      10.0  0.760577  0.767490    0.239423  0.760577    0.774529
10       11  0.938942  0.939967    0.061058  0.938942    0.940993
11  average  0.714808  0.719387    0.285192  0.714808    0.724053
12      max  0.778846  0.788418    0.221154  0.778846    0.798228

### SAVE MODEL dTOP90fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn90_double_sim.pkl', 'wb') as f:
   pickle.dump(knn90, f)

## TRAIN K-NN TOP 100fi

In [ ]:
# train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data100
X_train100 = train_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_train100 = train_data100['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=100, data_type='train')
timer.start()

knn100, data_top_5, Confusion_df100, eval_result100, cv_result100 = knn_custom_kfold_evaluation(X_train100, y_train100, le, 100, first_c100, last_c100, first_n100, last_n100, first_o100, last_o100, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 26.65it/s]
6it [00:00, 25.86it/s]
9it [00:00, 26.08it/s]
12it [00:00, 25.66it/s]
15it [00:00, 25.79it/s]
18it [00:00, 25.99it/s]
21it [00:00, 26.21it/s]
24it [00:00, 26.45it/s]
27it [00:01, 26.59it/s]
30it [00:01, 26.68it/s]
33it [00:01, 26.66it/s]
36it [00:01, 26.76it/s]
39it [00:01, 27.03it/s]
42it [00:01, 27.23it/s]
45it [00:01, 27.03it/s]
50it [00:01, 26.60it/s]
1it [00:02,  2.71s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 27.51it/s]
6it [00:00, 27.34it/s]
9it [00:00, 27.00it/s]
12it [00:00, 27.01it/s]
15it [00:00, 27.08it/s]
18it [00:00, 27.17it/s]
21it [00:00, 26.94it/s]
24it [00:00, 26.99it/s]
27it [00:01, 26.88it/s]
30it [00:01, 26.72it/s]
33it [00:01, 26.85it/s]
36it [00:01, 26.91it/s]
39it [00:01, 26.91it/s]
42it [00:01, 27.24it/s]
45it [00:01, 27.56it/s]
50it [00:01, 27.16it/s]
2it [00:05,  2.61s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 27.53it/s]
6it [00:00, 26.70it/s]
9it [00:00, 26.74it/s]
12it [00:00, 26.80it/s]
15it [00:00, 26.92it/s]
18it [00:00, 26.76it/s]
21it [00:00, 26.63it/s]
24it [00:00, 26.50it/s]
27it [00:01, 26.45it/s]
30it [00:01, 26.45it/s]
33it [00:01, 26.27it/s]
36it [00:01, 26.23it/s]
39it [00:01, 26.38it/s]
42it [00:01, 26.75it/s]
45it [00:01, 27.13it/s]
50it [00:01, 26.76it/s]
3it [00:07,  2.66s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 27.16it/s]
6it [00:00, 26.70it/s]
9it [00:00, 26.84it/s]
12it [00:00, 26.62it/s]
15it [00:00, 26.62it/s]
18it [00:00, 26.80it/s]
21it [00:00, 26.90it/s]
24it [00:00, 27.04it/s]
27it [00:01, 26.88it/s]
30it [00:01, 26.70it/s]
33it [00:01, 26.69it/s]
36it [00:01, 26.89it/s]
39it [00:01, 26.96it/s]
42it [00:01, 27.07it/s]
45it [00:01, 27.21it/s]
50it [00:01, 26.89it/s]
4it [00:10,  2.61s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 27.61it/s]
6it [00:00, 27.23it/s]
9it [00:00, 26.37it/s]
12it [00:00, 26.07it/s]
15it [00:00, 26.15it/s]
18it [00:00, 26.32it/s]
21it [00:00, 26.51it/s]
24it [00:00, 26.64it/s]
27it [00:01, 26.48it/s]
30it [00:01, 26.28it/s]
33it [00:01, 26.18it/s]
36it [00:01, 26.31it/s]
39it [00:01, 25.19it/s]
42it [00:01, 25.55it/s]
45it [00:01, 25.51it/s]
50it [00:01, 26.09it/s]
5it [00:13,  2.69s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 27.77it/s]
6it [00:00, 27.48it/s]
9it [00:00, 27.08it/s]
12it [00:00, 27.10it/s]
15it [00:00, 26.96it/s]
18it [00:00, 26.94it/s]
21it [00:00, 26.77it/s]
24it [00:00, 26.49it/s]
27it [00:01, 26.57it/s]
30it [00:01, 26.22it/s]
33it [00:01, 26.26it/s]
36it [00:01, 26.59it/s]
39it [00:01, 26.57it/s]
42it [00:01, 26.81it/s]
45it [00:01, 27.12it/s]
50it [00:01, 26.86it/s]
6it [00:15,  2.64s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 27.76it/s]
6it [00:00, 27.08it/s]
9it [00:00, 26.63it/s]
12it [00:00, 26.88it/s]
15it [00:00, 26.84it/s]
18it [00:00, 26.68it/s]
21it [00:00, 26.64it/s]
24it [00:00, 26.75it/s]
27it [00:01, 26.60it/s]
30it [00:01, 26.33it/s]
33it [00:01, 25.76it/s]
36it [00:01, 25.48it/s]
39it [00:01, 25.65it/s]
42it [00:01, 26.12it/s]
45it [00:01, 26.57it/s]
50it [00:01, 26.51it/s]
7it [00:18,  2.67s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 27.43it/s]
6it [00:00, 27.20it/s]
9it [00:00, 27.23it/s]
12it [00:00, 27.03it/s]
15it [00:00, 26.83it/s]
18it [00:00, 26.63it/s]
21it [00:00, 26.80it/s]
24it [00:00, 26.36it/s]
27it [00:01, 26.02it/s]
30it [00:01, 25.61it/s]
33it [00:01, 25.68it/s]
36it [00:01, 26.13it/s]
39it [00:01, 26.47it/s]
42it [00:01, 26.84it/s]
45it [00:01, 27.18it/s]
50it [00:01, 26.77it/s]
8it [00:21,  2.63s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 27.22it/s]
6it [00:00, 27.20it/s]
9it [00:00, 26.80it/s]
12it [00:00, 26.68it/s]
15it [00:00, 26.60it/s]
18it [00:00, 26.64it/s]
21it [00:00, 26.79it/s]
24it [00:00, 26.86it/s]
27it [00:01, 26.71it/s]
30it [00:01, 26.46it/s]
33it [00:01, 26.45it/s]
36it [00:01, 26.33it/s]
39it [00:01, 26.48it/s]
42it [00:01, 26.62it/s]
45it [00:01, 26.82it/s]
50it [00:01, 26.66it/s]
9it [00:23,  2.67s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 26.63it/s]
6it [00:00, 26.68it/s]
9it [00:00, 26.45it/s]
12it [00:00, 26.03it/s]
15it [00:00, 26.08it/s]
18it [00:00, 26.24it/s]
21it [00:00, 26.20it/s]
24it [00:00, 25.77it/s]
27it [00:01, 25.47it/s]
30it [00:01, 25.59it/s]
33it [00:01, 25.87it/s]
36it [00:01, 26.15it/s]
39it [00:01, 26.46it/s]
42it [00:01, 26.82it/s]
45it [00:01, 27.08it/s]
50it [00:01, 26.46it/s]
10it [00:26,  2.65s/it]

predict using best model..

90it [00:16,  5.43it/s]

done
Time taken: 0.82 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df100

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,0,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
129.0,1,1,6,1,1,0,0,0,0,388,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,0,1,0,0,0,0
150.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,2,0,0,0,4,0,4,...,1,1,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,1,3,1,6,...,0,0,1,4,1,3,3,0,0,0
154.0,1,1,5,2,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
161.0,0,2,1,0,2,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,10,...,1,343,2,4,3,0,1,0,1,0
185.9,1,3,8,0,1,2,2,6,5,12,...,1,0,335,2,3,0,2,0,0,0
197.0,2,3,10,2,1,3,6,4,0,8,...,1,1,5,332,1,2,2,0,0,0
212.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,317,0,5,0,0,0
217.0,2,4,11,3,1,6,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001498,0.963680,0.995000,0.979090,0.036320,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
2,18.9,0.965000,0.965000,0.035000,0.007247,0.840959,0.965000,0.898719,0.159041,0.035000,0.843988
3,32.1,0.990000,0.990000,0.010000,0.002096,0.949640,0.990000,0.969400,0.050360,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
5,98.9,0.982500,0.982500,0.017500,0.002295,0.944712,0.982500,0.963235,0.055288,0.017500,0.743315
6,104.1,0.975000,0.975000,0.025000,0.002195,0.946602,0.975000,0.960591,0.053398,0.025000,0.495457
7,111.0,0.962500,0.962500,0.037500,0.003388,0.918854,0.962500,0.940171,0.081146,0.037500,0.831063
8,128.0,0.995000,0.995000,0.005000,0.001398,0.966019,0.995000,0.980296,0.033981,0.005000,1.156444
9,129.0,0.970000,0.970000,0.030000,0.008920,0.811715,0.970000,0.883827,0.188285,0.030000,0.830807
10,146.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.754017
11,147.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.581016
12,150.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.908066
13,151.0,0.935000,0.935000,0.065000,0.001697,0.956522,0.935000,0.945638,0.043478,0.065000,0.743932
14,153.0,0.897500,0.897500,0.102500,0.002195,0.942257,0.897500,0.919334,0.057743,0.102500,0.622271
15,154.0,0.892500,0.892500,0.107500,0.003190,0.917738,0.892500,0.904943,0.082262,0.107500,0.597606
16,161.0,0.937500,0.937500,0.062500,0.000799,0.979112,0.937500,0.957854,0.020888,0.062500,0.747673
17,169.0,0.857500,0.857500,0.142500,0.001099,0.968927,0.857500,0.909814,0.031073,0.142500,0.618824
18,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.491757
19,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.764709
20,212.9,0.792500,0.792500,0.207500,0.001199,0.963526,0.792500,0.869684,0.036474,0.207500,0.751471
21,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472451
22,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.938942,0.938942,0.061058,0.002432,0.940993,0.938942,0.938308,0.059007,0.061058,0.482145

In [ ]:
cv_result100

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.660577  0.663653    0.339423  0.660577    0.666757
1       2.0  0.778846  0.788418    0.221154  0.778846    0.798228
2       3.0  0.689423  0.689491    0.310577  0.689423    0.689558
3       4.0  0.739423  0.745998    0.260577  0.739423    0.752691
4       5.0  0.662500  0.665176    0.337500  0.662500    0.667875
5       6.0  0.775000  0.782269    0.225000  0.775000    0.789676
6       7.0  0.664423  0.666303    0.335577  0.664423    0.668194
7       8.0  0.750962  0.759401    0.249038  0.750962    0.768033
8       9.0  0.666346  0.665668    0.333654  0.666346    0.664990
9      10.0  0.760577  0.767490    0.239423  0.760577    0.774529
10       11  0.938942  0.939967    0.061058  0.938942    0.940993
11  average  0.714808  0.719387    0.285192  0.714808    0.724053
12      max  0.778846  0.788418    0.221154  0.778846    0.798228

### SAVE MODEL dTOP100fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn100_double_sim.pkl', 'wb') as f:
   pickle.dump(knn100, f)

## TRAIN K-NN TOP 110fi

In [ ]:
# train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data110
X_train110 = train_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_train110 = train_data110['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=110, data_type='train')
timer.start()

knn110, data_top_5, Confusion_df110, eval_result110, cv_result110 = knn_custom_kfold_evaluation(X_train110, y_train110, le, 110, first_c110, last_c110, first_n110, last_n110, first_o110, last_o110, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 26.69it/s]
6it [00:00, 26.46it/s]
9it [00:00, 26.48it/s]
12it [00:00, 26.38it/s]
15it [00:00, 26.43it/s]
18it [00:00, 26.37it/s]
21it [00:00, 26.46it/s]
24it [00:00, 26.31it/s]
27it [00:01, 26.00it/s]
30it [00:01, 25.72it/s]
33it [00:01, 25.66it/s]
36it [00:01, 25.68it/s]
39it [00:01, 25.61it/s]
42it [00:01, 25.97it/s]
45it [00:01, 26.33it/s]
50it [00:01, 26.25it/s]
1it [00:02,  2.74s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 27.09it/s]
6it [00:00, 26.92it/s]
9it [00:00, 26.60it/s]
12it [00:00, 26.42it/s]
15it [00:00, 26.42it/s]
18it [00:00, 26.43it/s]
21it [00:00, 26.36it/s]
24it [00:00, 26.36it/s]
27it [00:01, 26.29it/s]
30it [00:01, 26.33it/s]
33it [00:01, 26.45it/s]
36it [00:01, 26.47it/s]
39it [00:01, 26.54it/s]
42it [00:01, 26.78it/s]
45it [00:01, 27.15it/s]
50it [00:01, 26.72it/s]
2it [00:05,  2.65s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 26.91it/s]
6it [00:00, 26.69it/s]
9it [00:00, 26.34it/s]
12it [00:00, 26.31it/s]
15it [00:00, 26.52it/s]
18it [00:00, 26.56it/s]
21it [00:00, 26.49it/s]
24it [00:00, 26.38it/s]
27it [00:01, 26.52it/s]
30it [00:01, 26.50it/s]
33it [00:01, 26.08it/s]
36it [00:01, 26.12it/s]
39it [00:01, 26.15it/s]
42it [00:01, 26.32it/s]
45it [00:01, 26.73it/s]
50it [00:01, 26.49it/s]
3it [00:08,  2.70s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 24.98it/s]
6it [00:00, 25.44it/s]
9it [00:00, 25.93it/s]
12it [00:00, 25.72it/s]
15it [00:00, 25.68it/s]
18it [00:00, 25.52it/s]
21it [00:00, 25.23it/s]
24it [00:00, 25.32it/s]
27it [00:01, 25.49it/s]
30it [00:01, 25.66it/s]
33it [00:01, 25.82it/s]
36it [00:01, 25.86it/s]
39it [00:01, 25.76it/s]
42it [00:01, 25.94it/s]
45it [00:01, 25.96it/s]
50it [00:01, 25.63it/s]
4it [00:10,  2.69s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 25.64it/s]
6it [00:00, 25.61it/s]
9it [00:00, 25.57it/s]
12it [00:00, 25.32it/s]
15it [00:00, 25.09it/s]
18it [00:00, 25.06it/s]
21it [00:00, 24.95it/s]
24it [00:00, 25.07it/s]
27it [00:01, 24.99it/s]
30it [00:01, 24.95it/s]
33it [00:01, 24.66it/s]
36it [00:01, 25.08it/s]
39it [00:01, 25.32it/s]
42it [00:01, 25.78it/s]
45it [00:01, 26.04it/s]
50it [00:01, 25.45it/s]
5it [00:13,  2.74s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 26.86it/s]
6it [00:00, 25.96it/s]
9it [00:00, 25.95it/s]
12it [00:00, 25.93it/s]
15it [00:00, 26.05it/s]
18it [00:00, 26.00it/s]
21it [00:00, 25.90it/s]
24it [00:00, 26.03it/s]
27it [00:01, 26.10it/s]
30it [00:01, 26.21it/s]
33it [00:01, 26.18it/s]
36it [00:01, 26.10it/s]
39it [00:01, 26.13it/s]
42it [00:01, 26.44it/s]
45it [00:01, 26.60it/s]
50it [00:01, 26.28it/s]
6it [00:16,  2.70s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 26.94it/s]
6it [00:00, 26.61it/s]
9it [00:00, 25.92it/s]
12it [00:00, 25.98it/s]
15it [00:00, 26.10it/s]
18it [00:00, 26.05it/s]
21it [00:00, 25.97it/s]
24it [00:00, 25.97it/s]
27it [00:01, 26.08it/s]
30it [00:01, 25.84it/s]
33it [00:01, 25.95it/s]
36it [00:01, 25.99it/s]
39it [00:01, 26.04it/s]
42it [00:01, 26.35it/s]
45it [00:01, 26.35it/s]
50it [00:01, 26.15it/s]
7it [00:18,  2.73s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 27.31it/s]
6it [00:00, 26.90it/s]
9it [00:00, 26.74it/s]
12it [00:00, 26.82it/s]
15it [00:00, 26.63it/s]
18it [00:00, 26.65it/s]
21it [00:00, 26.66it/s]
24it [00:00, 26.67it/s]
27it [00:01, 26.47it/s]
30it [00:01, 26.51it/s]
33it [00:01, 26.52it/s]
36it [00:01, 26.51it/s]
39it [00:01, 26.45it/s]
42it [00:01, 26.57it/s]
45it [00:01, 26.81it/s]
50it [00:01, 26.67it/s]
8it [00:21,  2.68s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 26.41it/s]
6it [00:00, 26.01it/s]
9it [00:00, 26.10it/s]
12it [00:00, 26.06it/s]
15it [00:00, 25.88it/s]
18it [00:00, 25.81it/s]
21it [00:00, 25.39it/s]
24it [00:00, 25.53it/s]
27it [00:01, 25.49it/s]
30it [00:01, 25.65it/s]
33it [00:01, 25.43it/s]
36it [00:01, 25.50it/s]
39it [00:01, 25.50it/s]
42it [00:01, 25.65it/s]
45it [00:01, 26.06it/s]
50it [00:01, 25.82it/s]
9it [00:24,  2.73s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 26.48it/s]
6it [00:00, 26.40it/s]
9it [00:00, 26.37it/s]
12it [00:00, 25.75it/s]
15it [00:00, 25.90it/s]
18it [00:00, 25.96it/s]
21it [00:00, 25.88it/s]
24it [00:00, 26.05it/s]
27it [00:01, 26.16it/s]
30it [00:01, 26.15it/s]
33it [00:01, 25.99it/s]
36it [00:01, 25.78it/s]
39it [00:01, 25.69it/s]
42it [00:01, 25.80it/s]
45it [00:01, 26.10it/s]
50it [00:01, 26.16it/s]
10it [00:27,  2.70s/it]

predict using best model..

90it [00:16,  5.31it/s]

done
Time taken: 0.84 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df110

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
129.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
150.0,2,0,1,1,1,1,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
154.0,1,0,5,1,0,0,2,3,0,6,...,0,2,5,1,2,0,1,0,0,0
161.0,0,2,1,0,1,0,0,3,0,3,...,376,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,10,...,1,342,2,4,3,0,1,0,1,0
185.9,1,3,10,0,1,2,2,5,5,10,...,0,0,335,2,3,0,2,0,0,0
197.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
212.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,315,0,5,0,0,0
217.0,3,4,11,3,1,6,0,1,3,15,...,1,2,7,3,0,314,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002593,0.937650,0.977500,0.957160,0.062350,0.022500,0.680443
2,18.9,0.965000,0.965000,0.035000,0.007346,0.839130,0.965000,0.897674,0.160870,0.035000,0.819078
3,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
5,98.9,0.982500,0.982500,0.017500,0.002394,0.942446,0.982500,0.962056,0.057554,0.017500,0.743315
6,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.493387
7,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.831063
8,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
9,129.0,0.972500,0.972500,0.027500,0.008625,0.817227,0.972500,0.888128,0.182773,0.027500,0.826670
10,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
11,147.0,0.955000,0.955000,0.045000,0.003190,0.922705,0.955000,0.938575,0.077295,0.045000,0.585773
12,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,0.922340
13,151.0,0.937500,0.937500,0.062500,0.001697,0.956633,0.937500,0.946970,0.043367,0.062500,0.735479
14,153.0,0.900000,0.900000,0.100000,0.002394,0.937500,0.900000,0.918367,0.062500,0.100000,0.555856
15,154.0,0.900000,0.900000,0.100000,0.003388,0.913706,0.900000,0.906801,0.086294,0.100000,0.653272
16,161.0,0.940000,0.940000,0.060000,0.000700,0.981723,0.940000,0.960409,0.018277,0.060000,0.727469
17,169.0,0.855000,0.855000,0.145000,0.000999,0.971591,0.855000,0.909574,0.028409,0.145000,0.619105
18,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.705604
19,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.747798
20,212.9,0.787500,0.787500,0.212500,0.001298,0.960366,0.787500,0.865385,0.039634,0.212500,0.752916
21,217.0,0.785000,0.785000,0.215000,0.000999,0.969136,0.785000,0.867403,0.030864,0.215000,0.486048
22,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.939327,0.939327,0.060673,0.002417,0.941307,0.939327,0.938675,0.058693,0.060673,0.443849

In [ ]:
cv_result110

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.662500  0.666377    0.337500  0.662500    0.670300
1       2.0  0.777885  0.787220    0.222115  0.777885    0.796781
2       3.0  0.692308  0.692452    0.307692  0.692308    0.692597
3       4.0  0.738462  0.745882    0.261538  0.738462    0.753454
4       5.0  0.663462  0.666214    0.336538  0.663462    0.668990
5       6.0  0.775000  0.782927    0.225000  0.775000    0.791018
6       7.0  0.664423  0.666303    0.335577  0.664423    0.668194
7       8.0  0.751923  0.759816    0.248077  0.751923    0.767877
8       9.0  0.668269  0.668245    0.331731  0.668269    0.668221
9      10.0  0.764423  0.771237    0.235577  0.764423    0.778174
10       11  0.939327  0.940316    0.060673  0.939327    0.941307
11  average  0.715865  0.720667    0.284135  0.715865    0.725561
12      max  0.777885  0.787220    0.222115  0.777885    0.796781

### SAVE MODEL dTOP110fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn110_double_sim.pkl', 'wb') as f:
   pickle.dump(knn110, f)

## TRAIN K-NN TOP 120fi

In [ ]:
# train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data120
X_train120 = train_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_train120 = train_data120['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=120, data_type='train')
timer.start()

knn120, data_top_5, Confusion_df120, eval_result120, cv_result120 = knn_custom_kfold_evaluation(X_train120, y_train120, le, 120, first_c120, last_c120, first_n120, last_n120, first_o120, last_o120, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 24.00it/s]
6it [00:00, 24.80it/s]
9it [00:00, 25.37it/s]
12it [00:00, 25.25it/s]
15it [00:00, 24.95it/s]
18it [00:00, 24.76it/s]
21it [00:00, 24.74it/s]
24it [00:00, 24.92it/s]
27it [00:01, 25.05it/s]
30it [00:01, 25.17it/s]
33it [00:01, 25.13it/s]
36it [00:01, 25.14it/s]
39it [00:01, 25.24it/s]
42it [00:01, 25.41it/s]
45it [00:01, 25.76it/s]
50it [00:01, 25.25it/s]
1it [00:02,  2.86s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 25.70it/s]
6it [00:00, 25.39it/s]
9it [00:00, 25.30it/s]
12it [00:00, 24.99it/s]
15it [00:00, 25.18it/s]
18it [00:00, 25.06it/s]
21it [00:00, 24.93it/s]
24it [00:00, 24.74it/s]
27it [00:01, 24.50it/s]
30it [00:01, 24.55it/s]
33it [00:01, 24.92it/s]
36it [00:01, 25.13it/s]
39it [00:01, 25.23it/s]
42it [00:01, 25.46it/s]
45it [00:01, 25.79it/s]
50it [00:01, 25.22it/s]
2it [00:05,  2.77s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 25.75it/s]
6it [00:00, 25.64it/s]
9it [00:00, 25.57it/s]
12it [00:00, 25.45it/s]
15it [00:00, 25.25it/s]
18it [00:00, 25.28it/s]
21it [00:00, 25.40it/s]
24it [00:00, 24.96it/s]
27it [00:01, 24.85it/s]
30it [00:01, 24.48it/s]
33it [00:01, 24.84it/s]
36it [00:01, 24.96it/s]
39it [00:01, 24.94it/s]
42it [00:01, 25.44it/s]
45it [00:01, 25.59it/s]
50it [00:01, 25.28it/s]
3it [00:08,  2.82s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 25.55it/s]
6it [00:00, 25.15it/s]
9it [00:00, 24.93it/s]
12it [00:00, 24.91it/s]
15it [00:00, 24.85it/s]
18it [00:00, 24.92it/s]
21it [00:00, 25.00it/s]
24it [00:00, 24.91it/s]
27it [00:01, 24.87it/s]
30it [00:01, 24.79it/s]
33it [00:01, 24.80it/s]
36it [00:01, 24.89it/s]
39it [00:01, 24.84it/s]
42it [00:01, 24.89it/s]
45it [00:01, 25.55it/s]
50it [00:01, 25.25it/s]
4it [00:11,  2.76s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 26.68it/s]
6it [00:00, 25.75it/s]
9it [00:00, 25.60it/s]
12it [00:00, 25.61it/s]
15it [00:00, 25.57it/s]
18it [00:00, 25.50it/s]
21it [00:00, 25.29it/s]
24it [00:00, 25.26it/s]
27it [00:01, 25.36it/s]
30it [00:01, 25.45it/s]
33it [00:01, 25.41it/s]
36it [00:01, 25.56it/s]
39it [00:01, 25.58it/s]
42it [00:01, 25.75it/s]
45it [00:01, 26.04it/s]
50it [00:01, 25.74it/s]
5it [00:13,  2.78s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 26.30it/s]
6it [00:00, 26.01it/s]
9it [00:00, 25.89it/s]
12it [00:00, 25.83it/s]
15it [00:00, 25.76it/s]
18it [00:00, 25.69it/s]
21it [00:00, 25.66it/s]
24it [00:00, 25.61it/s]
27it [00:01, 25.37it/s]
30it [00:01, 25.14it/s]
33it [00:01, 25.26it/s]
36it [00:01, 25.37it/s]
39it [00:01, 25.55it/s]
42it [00:01, 25.79it/s]
45it [00:01, 25.87it/s]
50it [00:01, 25.63it/s]
6it [00:16,  2.74s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 26.07it/s]
6it [00:00, 25.87it/s]
9it [00:00, 25.79it/s]
12it [00:00, 25.57it/s]
15it [00:00, 25.29it/s]
18it [00:00, 25.24it/s]
21it [00:00, 25.02it/s]
24it [00:00, 25.10it/s]
27it [00:01, 25.16it/s]
30it [00:01, 25.12it/s]
33it [00:01, 25.19it/s]
36it [00:01, 25.28it/s]
39it [00:01, 25.25it/s]
42it [00:01, 25.41it/s]
45it [00:01, 25.80it/s]
50it [00:01, 25.57it/s]
7it [00:19,  2.77s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 26.63it/s]
6it [00:00, 26.17it/s]
9it [00:00, 25.64it/s]
12it [00:00, 25.58it/s]
15it [00:00, 25.87it/s]
18it [00:00, 25.87it/s]
21it [00:00, 25.61it/s]
24it [00:00, 25.58it/s]
27it [00:01, 25.61it/s]
30it [00:01, 25.53it/s]
33it [00:01, 25.52it/s]
36it [00:01, 25.69it/s]
39it [00:01, 25.63it/s]
42it [00:01, 25.88it/s]
45it [00:01, 26.18it/s]
50it [00:01, 25.73it/s]
8it [00:22,  2.76s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 25.07it/s]
6it [00:00, 25.06it/s]
9it [00:00, 25.35it/s]
12it [00:00, 25.49it/s]
15it [00:00, 25.68it/s]
18it [00:00, 25.73it/s]
21it [00:00, 25.79it/s]
24it [00:00, 25.84it/s]
27it [00:01, 25.60it/s]
30it [00:01, 25.59it/s]
33it [00:01, 25.81it/s]
36it [00:01, 25.90it/s]
39it [00:01, 25.69it/s]
42it [00:01, 25.86it/s]
45it [00:01, 25.79it/s]
50it [00:01, 25.79it/s]
9it [00:24,  2.77s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 25.89it/s]
6it [00:00, 25.52it/s]
9it [00:00, 25.30it/s]
12it [00:00, 25.01it/s]
15it [00:00, 25.22it/s]
18it [00:00, 25.37it/s]
21it [00:00, 25.25it/s]
24it [00:00, 25.40it/s]
27it [00:01, 25.59it/s]
30it [00:01, 25.68it/s]
33it [00:01, 25.60it/s]
36it [00:01, 25.56it/s]
39it [00:01, 25.70it/s]
42it [00:01, 25.93it/s]
45it [00:01, 26.25it/s]
50it [00:01, 25.75it/s]
10it [00:27,  2.76s/it]

predict using best model..

90it [00:17,  5.29it/s]

done
Time taken: 0.85 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df120

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
129.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
150.0,2,0,1,1,1,1,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
154.0,1,0,5,1,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
161.0,0,2,2,0,1,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,10,...,1,342,2,4,3,0,1,0,1,0
185.9,1,3,10,0,1,2,2,5,5,11,...,0,0,335,2,3,0,2,0,0,0
197.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
212.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,315,0,5,0,0,0
217.0,3,4,11,3,1,7,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002593,0.937650,0.977500,0.957160,0.062350,0.022500,0.680443
2,18.9,0.965000,0.965000,0.035000,0.007444,0.837310,0.965000,0.896632,0.162690,0.035000,0.819078
3,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
5,98.9,0.982500,0.982500,0.017500,0.002494,0.940191,0.982500,0.960880,0.059809,0.017500,0.743315
6,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.493387
7,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.831063
8,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
9,129.0,0.972500,0.972500,0.027500,0.008920,0.812109,0.972500,0.885097,0.187891,0.027500,0.826670
10,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
11,147.0,0.955000,0.955000,0.045000,0.003090,0.924939,0.955000,0.939729,0.075061,0.045000,0.585773
12,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,0.922340
13,151.0,0.937500,0.937500,0.062500,0.001697,0.956633,0.937500,0.946970,0.043367,0.062500,0.735479
14,153.0,0.900000,0.900000,0.100000,0.002394,0.937500,0.900000,0.918367,0.062500,0.100000,0.555856
15,154.0,0.897500,0.897500,0.102500,0.003289,0.915816,0.897500,0.906566,0.084184,0.102500,0.589162
16,161.0,0.937500,0.937500,0.062500,0.000700,0.981675,0.937500,0.959079,0.018325,0.062500,0.761292
17,169.0,0.855000,0.855000,0.145000,0.000999,0.971591,0.855000,0.909574,0.028409,0.145000,0.619105
18,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.619384
19,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.747798
20,212.9,0.787500,0.787500,0.212500,0.001298,0.960366,0.787500,0.865385,0.039634,0.212500,0.752916
21,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472621
22,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.939038,0.939038,0.060962,0.002429,0.941115,0.939038,0.938397,0.058885,0.060962,0.438852

In [ ]:
cv_result120

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.662500  0.666377    0.337500  0.662500    0.670300
1       2.0  0.776923  0.786517    0.223077  0.776923    0.796351
2       3.0  0.692308  0.692452    0.307692  0.692308    0.692597
3       4.0  0.738462  0.745882    0.261538  0.738462    0.753454
4       5.0  0.663462  0.666214    0.336538  0.663462    0.668990
5       6.0  0.775000  0.782927    0.225000  0.775000    0.791018
6       7.0  0.664423  0.666303    0.335577  0.664423    0.668194
7       8.0  0.750000  0.757808    0.250000  0.750000    0.765780
8       9.0  0.667308  0.666836    0.332692  0.667308    0.666365
9      10.0  0.764423  0.771609    0.235577  0.764423    0.778932
10       11  0.939038  0.940076    0.060962  0.939038    0.941115
11  average  0.715481  0.720293    0.284519  0.715481    0.725198
12      max  0.776923  0.786517    0.223077  0.776923    0.796351

### SAVE MODEL dTOP120fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn120_double_sim.pkl', 'wb') as f:
   pickle.dump(knn120, f)

## TRAIN K-NN TOP 130fi

In [ ]:
# train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data130
X_train130 = train_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_train130 = train_data130['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=130, data_type='train')
timer.start()

knn130, data_top_5, Confusion_df130, eval_result130, cv_result130 = knn_custom_kfold_evaluation(X_train130, y_train130, le, 130, first_c130, last_c130, first_n130, last_n130, first_o130, last_o130, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 24.99it/s]
6it [00:00, 25.10it/s]
9it [00:00, 25.14it/s]
12it [00:00, 25.35it/s]
15it [00:00, 25.23it/s]
18it [00:00, 25.39it/s]
21it [00:00, 25.17it/s]
24it [00:00, 25.29it/s]
27it [00:01, 25.03it/s]
30it [00:01, 25.19it/s]
33it [00:01, 25.10it/s]
36it [00:01, 25.11it/s]
39it [00:01, 25.15it/s]
42it [00:01, 25.33it/s]
45it [00:01, 25.80it/s]
50it [00:01, 25.42it/s]
1it [00:02,  2.84s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 25.95it/s]
6it [00:00, 25.56it/s]
9it [00:00, 25.77it/s]
12it [00:00, 25.88it/s]
15it [00:00, 25.89it/s]
18it [00:00, 25.89it/s]
21it [00:00, 25.80it/s]
24it [00:00, 25.25it/s]
27it [00:01, 25.17it/s]
30it [00:01, 25.43it/s]
33it [00:01, 25.54it/s]
36it [00:01, 25.62it/s]
39it [00:01, 25.03it/s]
42it [00:01, 24.89it/s]
45it [00:01, 25.31it/s]
50it [00:01, 25.59it/s]
2it [00:05,  2.73s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 24.41it/s]
6it [00:00, 24.62it/s]
9it [00:00, 24.79it/s]
12it [00:00, 24.86it/s]
15it [00:00, 25.09it/s]
18it [00:00, 24.97it/s]
21it [00:00, 24.92it/s]
24it [00:00, 24.82it/s]
27it [00:01, 24.55it/s]
30it [00:01, 24.62it/s]
33it [00:01, 24.63it/s]
36it [00:01, 24.56it/s]
39it [00:01, 24.66it/s]
42it [00:01, 24.68it/s]
45it [00:01, 25.09it/s]
50it [00:02, 24.87it/s]
3it [00:08,  2.79s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 25.41it/s]
6it [00:00, 24.86it/s]
9it [00:00, 25.20it/s]
12it [00:00, 25.52it/s]
15it [00:00, 25.57it/s]
18it [00:00, 25.64it/s]
21it [00:00, 25.48it/s]
24it [00:00, 25.40it/s]
27it [00:01, 25.49it/s]
30it [00:01, 25.62it/s]
33it [00:01, 25.44it/s]
36it [00:01, 25.34it/s]
39it [00:01, 25.29it/s]
42it [00:01, 25.67it/s]
45it [00:01, 25.89it/s]
50it [00:01, 25.42it/s]
4it [00:11,  2.75s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 26.36it/s]
6it [00:00, 26.07it/s]
9it [00:00, 25.61it/s]
12it [00:00, 25.49it/s]
15it [00:00, 25.38it/s]
18it [00:00, 25.50it/s]
21it [00:00, 25.51it/s]
24it [00:00, 25.40it/s]
27it [00:01, 25.49it/s]
30it [00:01, 25.73it/s]
33it [00:01, 25.81it/s]
36it [00:01, 25.75it/s]
39it [00:01, 25.51it/s]
42it [00:01, 25.46it/s]
45it [00:01, 25.94it/s]
50it [00:01, 25.76it/s]
5it [00:13,  2.77s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 25.03it/s]
6it [00:00, 24.83it/s]
9it [00:00, 24.43it/s]
12it [00:00, 24.29it/s]
15it [00:00, 24.60it/s]
18it [00:00, 24.67it/s]
21it [00:00, 24.50it/s]
24it [00:00, 24.57it/s]
27it [00:01, 24.73it/s]
30it [00:01, 24.82it/s]
33it [00:01, 25.15it/s]
36it [00:01, 25.31it/s]
39it [00:01, 25.08it/s]
42it [00:01, 24.76it/s]
45it [00:01, 24.70it/s]
50it [00:02, 24.78it/s]
6it [00:16,  2.75s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 25.70it/s]
6it [00:00, 26.08it/s]
9it [00:00, 25.83it/s]
12it [00:00, 25.78it/s]
15it [00:00, 25.82it/s]
18it [00:00, 25.86it/s]
21it [00:00, 25.76it/s]
24it [00:00, 25.72it/s]
27it [00:01, 25.64it/s]
30it [00:01, 24.95it/s]
33it [00:01, 25.09it/s]
36it [00:01, 25.19it/s]
39it [00:01, 25.24it/s]
42it [00:01, 25.54it/s]
45it [00:01, 25.92it/s]
50it [00:01, 25.70it/s]
7it [00:19,  2.79s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 25.55it/s]
6it [00:00, 25.20it/s]
9it [00:00, 25.08it/s]
12it [00:00, 25.43it/s]
15it [00:00, 25.41it/s]
18it [00:00, 25.51it/s]
21it [00:00, 25.59it/s]
24it [00:00, 25.77it/s]
27it [00:01, 25.89it/s]
30it [00:01, 25.74it/s]
33it [00:01, 25.72it/s]
36it [00:01, 25.68it/s]
39it [00:01, 25.73it/s]
42it [00:01, 25.96it/s]
45it [00:01, 26.30it/s]
50it [00:01, 25.84it/s]
8it [00:22,  2.74s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 25.95it/s]
6it [00:00, 25.31it/s]
9it [00:00, 25.41it/s]
12it [00:00, 25.36it/s]
15it [00:00, 25.17it/s]
18it [00:00, 25.23it/s]
21it [00:00, 25.19it/s]
24it [00:00, 25.21it/s]
27it [00:01, 25.29it/s]
30it [00:01, 25.36it/s]
33it [00:01, 25.46it/s]
36it [00:01, 25.39it/s]
39it [00:01, 25.47it/s]
42it [00:01, 25.77it/s]
45it [00:01, 26.11it/s]
50it [00:01, 25.59it/s]
9it [00:24,  2.76s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 25.41it/s]
6it [00:00, 25.23it/s]
9it [00:00, 25.28it/s]
12it [00:00, 25.31it/s]
15it [00:00, 25.42it/s]
18it [00:00, 25.24it/s]
21it [00:00, 25.22it/s]
24it [00:00, 25.09it/s]
27it [00:01, 25.03it/s]
30it [00:01, 24.92it/s]
33it [00:01, 24.86it/s]
36it [00:01, 25.05it/s]
39it [00:01, 25.17it/s]
42it [00:01, 25.55it/s]
45it [00:01, 25.71it/s]
50it [00:01, 25.37it/s]
10it [00:27,  2.76s/it]

predict using best model..

90it [00:17,  5.22it/s]

done
Time taken: 0.85 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df130

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
129.0,1,1,6,0,1,0,0,0,0,388,...,0,0,0,1,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
150.0,2,0,1,2,1,1,1,0,0,1,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,0,3,1,6,...,0,0,1,4,1,3,3,0,0,0
154.0,1,0,5,1,0,0,2,3,0,7,...,0,2,5,1,1,0,1,0,0,0
161.0,0,2,2,0,2,0,0,3,0,3,...,374,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,11,...,1,341,2,4,3,0,1,0,1,0
185.9,1,3,10,0,1,2,2,5,5,12,...,0,0,335,2,3,0,2,0,0,0
197.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
212.9,1,6,9,4,2,3,2,4,1,8,...,0,2,8,2,316,0,5,0,0,0
217.0,3,4,11,3,1,7,0,1,3,16,...,1,2,8,3,0,312,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.99500,0.99500,0.00500,0.001697,0.959036,0.99500,0.976687,0.040964,0.00500,-3.965838
1,7.1,0.97750,0.97750,0.02250,0.002593,0.937650,0.97750,0.957160,0.062350,0.02250,0.680443
2,18.9,0.96500,0.96500,0.03500,0.007444,0.837310,0.96500,0.896632,0.162690,0.03500,0.819078
3,32.1,0.99000,0.99000,0.01000,0.001896,0.954217,0.99000,0.971779,0.045783,0.01000,0.414882
4,41.0,0.98000,0.98000,0.02000,0.001199,0.970297,0.98000,0.975124,0.029703,0.02000,1.101860
5,98.9,0.98250,0.98250,0.01750,0.002394,0.942446,0.98250,0.962056,0.057554,0.01750,0.743315
6,104.1,0.97500,0.97500,0.02500,0.001996,0.951220,0.97500,0.962963,0.048780,0.02500,0.493387
7,111.0,0.96250,0.96250,0.03750,0.003289,0.921053,0.96250,0.941320,0.078947,0.03750,0.831063
8,128.0,0.99500,0.99500,0.00500,0.001398,0.966019,0.99500,0.980296,0.033981,0.00500,1.156444
9,129.0,0.97000,0.97000,0.03000,0.008920,0.811715,0.97000,0.883827,0.188285,0.03000,0.825864
10,146.0,0.97250,0.97250,0.02750,0.003090,0.926190,0.97250,0.948780,0.073810,0.02750,0.754017
11,147.0,0.95500,0.95500,0.04500,0.002991,0.927184,0.95500,0.940887,0.072816,0.04500,0.585773
12,150.0,0.95250,0.95250,0.04750,0.003488,0.915865,0.95250,0.933824,0.084135,0.04750,0.949886
13,151.0,0.93750,0.93750,0.06250,0.001697,0.956633,0.93750,0.946970,0.043367,0.06250,0.735479
14,153.0,0.90000,0.90000,0.10000,0.002394,0.937500,0.90000,0.918367,0.062500,0.10000,0.619412
15,154.0,0.90000,0.90000,0.10000,0.003388,0.913706,0.90000,0.906801,0.086294,0.10000,0.588538
16,161.0,0.93500,0.93500,0.06500,0.000700,0.981627,0.93500,0.957746,0.018373,0.06500,0.780692
17,169.0,0.85250,0.85250,0.14750,0.000999,0.971510,0.85250,0.908123,0.028490,0.14750,0.553439
18,185.9,0.83750,0.83750,0.16250,0.004083,0.890957,0.83750,0.863402,0.109043,0.16250,0.552974
19,197.0,0.83000,0.83000,0.17000,0.002394,0.932584,0.83000,0.878307,0.067416,0.17000,0.747798
20,212.9,0.79000,0.79000,0.21000,0.001199,0.963415,0.79000,0.868132,0.036585,0.21000,0.745340
21,217.0,0.78000,0.78000,0.22000,0.000999,0.968944,0.78000,0.864266,0.031056,0.22000,0.472704
22,239.2,0.99000,0.99000,0.01000,0.002991,0.929577,0.99000,0.958838,0.070423,0.01000,0.894102
23,248.0,1.00000,1.00000,0.00000,0.000000,1.000000,1.00000,1.000000,0.000000,0.00000,0.000000
24,249.0,0.98250,0.98250,0.01750,0.000100,0.997462,0.98250,0.989924,0.002538,0.01750,0.455442
25,251.0,1.00000,1.00000,0.00000,0.000100,0.997506,1.00000,0.998752,0.002494,0.00000,0.000000
26,average,0.93875,0.93875,0.06125,0.002440,0.940832,0.93875,0.938114,0.059168,0.06125,0.482158

In [ ]:
cv_result130

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.663462  0.667209    0.336538  0.663462    0.670998
1       2.0  0.776923  0.786486    0.223077  0.776923    0.796287
2       3.0  0.691346  0.691335    0.308654  0.691346    0.691324
3       4.0  0.739423  0.746597    0.260577  0.739423    0.753911
4       5.0  0.664423  0.667252    0.335577  0.664423    0.670106
5       6.0  0.775000  0.782542    0.225000  0.775000    0.790233
6       7.0  0.664423  0.666303    0.335577  0.664423    0.668194
7       8.0  0.750962  0.759149    0.249038  0.750962    0.767518
8       9.0  0.666346  0.665823    0.333654  0.666346    0.665300
9      10.0  0.762500  0.769931    0.237500  0.762500    0.777509
10       11  0.938750  0.939790    0.061250  0.938750    0.940832
11  average  0.715481  0.720263    0.284519  0.715481    0.725138
12      max  0.776923  0.786486    0.223077  0.776923    0.796287

### SAVE MODEL dTOP130fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn130_double_sim.pkl', 'wb') as f:
   pickle.dump(knn130, f)

## TRAIN K-NN TOP 140fi

In [ ]:
# train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data140
X_train140 = train_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_train140 = train_data140['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=140, data_type='train')
timer.start()

knn140, data_top_5, Confusion_df140, eval_result140, cv_result140 = knn_custom_kfold_evaluation(X_train140, y_train140, le, 140, first_c140, last_c140, first_n140, last_n140, first_o140, last_o140, batch=True, n_neighbors=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 24.74it/s]
6it [00:00, 24.70it/s]
9it [00:00, 24.65it/s]
12it [00:00, 24.44it/s]
15it [00:00, 24.48it/s]
18it [00:00, 24.62it/s]
21it [00:00, 24.67it/s]
24it [00:00, 24.78it/s]
27it [00:01, 24.82it/s]
30it [00:01, 24.68it/s]
33it [00:01, 24.75it/s]
36it [00:01, 24.80it/s]
39it [00:01, 24.82it/s]
42it [00:01, 25.20it/s]
45it [00:01, 25.62it/s]
50it [00:01, 25.03it/s]
1it [00:02,  2.85s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 25.13it/s]
6it [00:00, 25.03it/s]
9it [00:00, 24.62it/s]
12it [00:00, 24.63it/s]
15it [00:00, 24.74it/s]
18it [00:00, 24.65it/s]
21it [00:00, 24.68it/s]
24it [00:00, 24.57it/s]
27it [00:01, 24.72it/s]
30it [00:01, 24.60it/s]
33it [00:01, 24.56it/s]
36it [00:01, 24.43it/s]
39it [00:01, 24.30it/s]
42it [00:01, 24.59it/s]
45it [00:01, 24.70it/s]
50it [00:02, 24.62it/s]
2it [00:05,  2.78s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 26.19it/s]
6it [00:00, 25.73it/s]
9it [00:00, 25.62it/s]
12it [00:00, 25.26it/s]
15it [00:00, 25.18it/s]
18it [00:00, 25.18it/s]
21it [00:00, 25.03it/s]
24it [00:00, 24.36it/s]
27it [00:01, 24.41it/s]
30it [00:01, 24.63it/s]
33it [00:01, 24.74it/s]
36it [00:01, 24.97it/s]
39it [00:01, 25.20it/s]
42it [00:01, 25.36it/s]
45it [00:01, 25.47it/s]
50it [00:01, 25.19it/s]
3it [00:08,  2.80s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 25.78it/s]
6it [00:00, 24.40it/s]
9it [00:00, 23.42it/s]
12it [00:00, 23.08it/s]
15it [00:00, 23.63it/s]
18it [00:00, 23.72it/s]
21it [00:00, 23.73it/s]
24it [00:01, 23.76it/s]
27it [00:01, 24.14it/s]
30it [00:01, 24.22it/s]
33it [00:01, 24.31it/s]
36it [00:01, 24.37it/s]
39it [00:01, 24.54it/s]
42it [00:01, 24.69it/s]
45it [00:01, 24.90it/s]
50it [00:02, 24.34it/s]
4it [00:11,  2.78s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 26.12it/s]
6it [00:00, 25.38it/s]
9it [00:00, 25.46it/s]
12it [00:00, 25.32it/s]
15it [00:00, 25.31it/s]
18it [00:00, 25.31it/s]
21it [00:00, 25.07it/s]
24it [00:00, 25.14it/s]
27it [00:01, 25.13it/s]
30it [00:01, 25.01it/s]
33it [00:01, 24.91it/s]
36it [00:01, 24.95it/s]
39it [00:01, 25.05it/s]
42it [00:01, 25.41it/s]
45it [00:01, 25.76it/s]
50it [00:01, 25.41it/s]
5it [00:13,  2.79s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 26.38it/s]
6it [00:00, 25.98it/s]
9it [00:00, 25.89it/s]
12it [00:00, 25.41it/s]
15it [00:00, 25.60it/s]
18it [00:00, 25.62it/s]
21it [00:00, 25.47it/s]
24it [00:00, 25.34it/s]
27it [00:01, 25.16it/s]
30it [00:01, 25.05it/s]
33it [00:01, 25.10it/s]
36it [00:01, 24.84it/s]
39it [00:01, 24.97it/s]
42it [00:01, 25.31it/s]
45it [00:01, 25.53it/s]
50it [00:01, 25.47it/s]
6it [00:16,  2.76s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 26.24it/s]
6it [00:00, 25.25it/s]
9it [00:00, 24.51it/s]
12it [00:00, 24.94it/s]
15it [00:00, 25.25it/s]
18it [00:00, 25.47it/s]
21it [00:00, 25.49it/s]
24it [00:00, 25.57it/s]
27it [00:01, 25.59it/s]
30it [00:01, 25.24it/s]
33it [00:01, 25.11it/s]
36it [00:01, 25.20it/s]
39it [00:01, 24.97it/s]
42it [00:01, 25.30it/s]
45it [00:01, 25.66it/s]
50it [00:01, 25.46it/s]
7it [00:19,  2.77s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 26.49it/s]
6it [00:00, 26.16it/s]
9it [00:00, 25.86it/s]
12it [00:00, 25.82it/s]
15it [00:00, 25.59it/s]
18it [00:00, 25.46it/s]
21it [00:00, 25.60it/s]
24it [00:00, 25.59it/s]
27it [00:01, 25.39it/s]
30it [00:01, 25.25it/s]
33it [00:01, 25.36it/s]
36it [00:01, 25.29it/s]
39it [00:01, 25.22it/s]
42it [00:01, 25.46it/s]
45it [00:01, 25.53it/s]
50it [00:01, 25.52it/s]
8it [00:22,  2.73s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 25.56it/s]
6it [00:00, 25.22it/s]
9it [00:00, 25.01it/s]
12it [00:00, 25.03it/s]
15it [00:00, 25.04it/s]
18it [00:00, 25.04it/s]
21it [00:00, 25.14it/s]
24it [00:00, 25.17it/s]
27it [00:01, 25.00it/s]
30it [00:01, 24.90it/s]
33it [00:01, 24.97it/s]
36it [00:01, 24.95it/s]
39it [00:01, 25.08it/s]
42it [00:01, 25.39it/s]
45it [00:01, 25.63it/s]
50it [00:01, 25.10it/s]
9it [00:24,  2.78s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 25.72it/s]
6it [00:00, 25.62it/s]
9it [00:00, 25.55it/s]
12it [00:00, 25.24it/s]
15it [00:00, 25.37it/s]
18it [00:00, 25.40it/s]
21it [00:00, 25.42it/s]
24it [00:00, 25.34it/s]
27it [00:01, 25.04it/s]
30it [00:01, 25.21it/s]
33it [00:01, 25.45it/s]
36it [00:01, 25.50it/s]
39it [00:01, 25.50it/s]
42it [00:01, 25.75it/s]
45it [00:01, 25.89it/s]
50it [00:01, 25.59it/s]
10it [00:27,  2.77s/it]

predict using best model..

90it [00:17,  5.25it/s]

done
Time taken: 0.85 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df140

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,390,1,0,5,...,0,0,0,0,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
129.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,1,1,0,0,0,0
150.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
151.0,1,1,3,1,1,0,0,3,0,4,...,1,0,1,0,0,1,1,0,0,0
153.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
154.0,1,1,5,1,0,1,2,2,0,7,...,0,2,5,1,2,0,1,0,0,0
161.0,0,2,2,0,2,0,0,3,0,3,...,374,1,3,1,1,2,2,0,0,0
169.0,1,1,9,1,0,2,4,0,1,11,...,1,342,2,4,3,0,1,0,1,0
185.9,1,3,10,0,1,2,2,5,5,11,...,0,0,334,2,3,0,2,0,0,0
197.0,3,3,11,2,1,3,5,3,0,7,...,1,1,6,332,1,2,2,0,0,0
212.9,1,6,9,4,2,3,2,4,1,8,...,0,2,8,2,314,1,5,0,0,0
217.0,3,4,11,3,1,7,0,1,3,16,...,1,1,8,3,0,313,5,0,0,0
239.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
2,18.9,0.965000,0.965000,0.035000,0.007543,0.835498,0.965000,0.895592,0.164502,0.035000,0.843988
3,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.001199,0.970297,0.980000,0.975124,0.029703,0.020000,1.101860
5,98.9,0.982500,0.982500,0.017500,0.002394,0.942446,0.982500,0.962056,0.057554,0.017500,0.743315
6,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.486484
7,111.0,0.962500,0.962500,0.037500,0.003090,0.925481,0.962500,0.943627,0.074519,0.037500,0.831063
8,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
9,129.0,0.972500,0.972500,0.027500,0.008920,0.812109,0.972500,0.885097,0.187891,0.027500,0.826670
10,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
11,147.0,0.952500,0.952500,0.047500,0.003190,0.922518,0.952500,0.937269,0.077482,0.047500,0.584286
12,150.0,0.955000,0.955000,0.045000,0.003488,0.916067,0.955000,0.935129,0.083933,0.045000,0.909818
13,151.0,0.940000,0.940000,0.060000,0.001697,0.956743,0.940000,0.948298,0.043257,0.060000,0.755102
14,153.0,0.897500,0.897500,0.102500,0.002394,0.937337,0.897500,0.916986,0.062663,0.102500,0.558801
15,154.0,0.895000,0.895000,0.105000,0.003388,0.913265,0.895000,0.904040,0.086735,0.105000,0.591432
16,161.0,0.935000,0.935000,0.065000,0.000700,0.981627,0.935000,0.957746,0.018373,0.065000,0.780692
17,169.0,0.855000,0.855000,0.145000,0.000899,0.974359,0.855000,0.910786,0.025641,0.145000,0.553225
18,185.9,0.835000,0.835000,0.165000,0.003984,0.893048,0.835000,0.863049,0.106952,0.165000,0.619458
19,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.784948
20,212.9,0.785000,0.785000,0.215000,0.001298,0.960245,0.785000,0.863824,0.039755,0.215000,0.746882
21,217.0,0.782500,0.782500,0.217500,0.001099,0.966049,0.782500,0.864641,0.033951,0.217500,0.472699
22,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.938654,0.938654,0.061346,0.002444,0.940735,0.938654,0.938001,0.059265,0.061346,0.439376

In [ ]:
cv_result140

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.663462  0.667292    0.336538  0.663462    0.671167
1       2.0  0.775962  0.785851    0.224038  0.775962    0.795996
2       3.0  0.690385  0.690336    0.309615  0.690385    0.690288
3       4.0  0.739423  0.746557    0.260577  0.739423    0.753829
4       5.0  0.662500  0.665383    0.337500  0.662500    0.668292
5       6.0  0.774038  0.781138    0.225962  0.774038    0.788369
6       7.0  0.664423  0.665838    0.335577  0.664423    0.667258
7       8.0  0.750000  0.757611    0.250000  0.750000    0.765378
8       9.0  0.666346  0.665836    0.333654  0.666346    0.665327
9      10.0  0.762500  0.769952    0.237500  0.762500    0.777552
10       11  0.938654  0.939694    0.061346  0.938654    0.940735
11  average  0.714904  0.719580    0.285096  0.714904    0.724346
12      max  0.775962  0.785851    0.224038  0.775962    0.795996

### SAVE MODEL dTOP140fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn140_double_sim.pkl', 'wb') as f:
   pickle.dump(knn140, f)

## TRAIN K-NN TOP 150fi

In [ ]:
# train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data150
X_train150 = train_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_train150 = train_data150['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features=150, data_type='train')
timer.start()

knn150, data_top_5, Confusion_df150, eval_result150, cv_result150 = knn_custom_kfold_evaluation(X_train150, y_train150, le, 150, first_c150, last_c150, first_n150, last_n150, first_o150, last_o150, batch=True, n_neighbors=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
3it [00:00, 24.90it/s]
6it [00:00, 24.70it/s]
9it [00:00, 24.68it/s]
12it [00:00, 24.75it/s]
15it [00:00, 24.19it/s]
18it [00:00, 24.26it/s]
21it [00:00, 24.42it/s]
24it [00:00, 24.60it/s]
27it [00:01, 24.46it/s]
30it [00:01, 24.55it/s]
33it [00:01, 24.67it/s]
36it [00:01, 24.56it/s]
39it [00:01, 24.62it/s]
42it [00:01, 24.62it/s]
45it [00:01, 25.03it/s]
50it [00:02, 24.74it/s]
1it [00:02,  2.87s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
3it [00:00, 25.48it/s]
6it [00:00, 25.50it/s]
9it [00:00, 25.36it/s]
12it [00:00, 25.13it/s]
15it [00:00, 24.91it/s]
18it [00:00, 25.07it/s]
21it [00:00, 24.97it/s]
24it [00:00, 24.79it/s]
27it [00:01, 24.74it/s]
30it [00:01, 24.79it/s]
33it [00:01, 24.59it/s]
36it [00:01, 24.70it/s]
39it [00:01, 24.74it/s]
42it [00:01, 25.07it/s]
45it [00:01, 25.37it/s]
50it [00:01, 25.08it/s]
2it [00:05,  2.76s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
3it [00:00, 25.48it/s]
6it [00:00, 25.38it/s]
9it [00:00, 25.37it/s]
12it [00:00, 24.86it/s]
15it [00:00, 24.29it/s]
18it [00:00, 24.53it/s]
21it [00:00, 24.13it/s]
24it [00:00, 24.46it/s]
27it [00:01, 24.61it/s]
30it [00:01, 24.79it/s]
33it [00:01, 24.79it/s]
36it [00:01, 24.94it/s]
39it [00:01, 25.06it/s]
42it [00:01, 25.14it/s]
45it [00:01, 25.48it/s]
50it [00:01, 25.06it/s]
3it [00:08,  2.80s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
3it [00:00, 25.62it/s]
6it [00:00, 24.97it/s]
9it [00:00, 24.54it/s]
12it [00:00, 24.58it/s]
15it [00:00, 24.70it/s]
18it [00:00, 24.77it/s]
21it [00:00, 24.69it/s]
24it [00:00, 24.68it/s]
27it [00:01, 24.87it/s]
30it [00:01, 25.06it/s]
33it [00:01, 25.16it/s]
36it [00:01, 25.09it/s]
39it [00:01, 24.97it/s]
42it [00:01, 25.36it/s]
45it [00:01, 25.54it/s]
50it [00:01, 25.18it/s]
4it [00:11,  2.75s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
3it [00:00, 25.45it/s]
6it [00:00, 25.18it/s]
9it [00:00, 25.30it/s]
12it [00:00, 25.38it/s]
15it [00:00, 25.32it/s]
18it [00:00, 25.15it/s]
21it [00:00, 25.20it/s]
24it [00:00, 25.28it/s]
27it [00:01, 25.37it/s]
30it [00:01, 24.96it/s]
33it [00:01, 24.99it/s]
36it [00:01, 24.97it/s]
39it [00:01, 24.73it/s]
42it [00:01, 24.75it/s]
45it [00:01, 24.69it/s]
50it [00:01, 25.09it/s]
5it [00:13,  2.80s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
3it [00:00, 25.11it/s]
6it [00:00, 24.91it/s]
9it [00:00, 24.84it/s]
12it [00:00, 25.05it/s]
15it [00:00, 25.23it/s]
18it [00:00, 25.40it/s]
21it [00:00, 25.23it/s]
24it [00:00, 25.28it/s]
27it [00:01, 25.22it/s]
30it [00:01, 25.25it/s]
33it [00:01, 25.28it/s]
36it [00:01, 25.18it/s]
39it [00:01, 25.18it/s]
42it [00:01, 25.30it/s]
45it [00:01, 25.36it/s]
50it [00:01, 25.28it/s]
6it [00:16,  2.76s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
3it [00:00, 25.34it/s]
6it [00:00, 25.22it/s]
9it [00:00, 24.89it/s]
12it [00:00, 24.87it/s]
15it [00:00, 24.88it/s]
18it [00:00, 24.85it/s]
21it [00:00, 24.28it/s]
24it [00:00, 24.05it/s]
27it [00:01, 24.46it/s]
30it [00:01, 24.76it/s]
33it [00:01, 24.82it/s]
36it [00:01, 24.81it/s]
39it [00:01, 24.92it/s]
42it [00:01, 25.16it/s]
45it [00:01, 25.57it/s]
50it [00:01, 25.07it/s]
7it [00:19,  2.79s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
3it [00:00, 25.62it/s]
6it [00:00, 25.34it/s]
9it [00:00, 25.39it/s]
12it [00:00, 25.24it/s]
15it [00:00, 25.23it/s]
18it [00:00, 25.15it/s]
21it [00:00, 25.19it/s]
24it [00:00, 25.25it/s]
27it [00:01, 25.27it/s]
30it [00:01, 25.34it/s]
33it [00:01, 25.34it/s]
36it [00:01, 25.19it/s]
39it [00:01, 25.33it/s]
42it [00:01, 25.50it/s]
45it [00:01, 25.63it/s]
50it [00:01, 25.43it/s]
8it [00:22,  2.76s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
3it [00:00, 26.08it/s]
6it [00:00, 25.56it/s]
9it [00:00, 25.01it/s]
12it [00:00, 25.04it/s]
15it [00:00, 25.01it/s]
18it [00:00, 24.99it/s]
21it [00:00, 25.07it/s]
24it [00:00, 25.12it/s]
27it [00:01, 25.10it/s]
30it [00:01, 25.08it/s]
33it [00:01, 25.14it/s]
36it [00:01, 25.05it/s]
39it [00:01, 25.09it/s]
42it [00:01, 25.36it/s]
45it [00:01, 25.51it/s]
50it [00:01, 25.30it/s]
9it [00:25,  2.79s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
3it [00:00, 24.85it/s]
6it [00:00, 24.85it/s]
9it [00:00, 24.34it/s]
12it [00:00, 24.45it/s]
15it [00:00, 24.62it/s]
18it [00:00, 24.62it/s]
21it [00:00, 24.51it/s]
24it [00:00, 24.43it/s]
27it [00:01, 24.54it/s]
30it [00:01, 24.67it/s]
33it [00:01, 24.74it/s]
36it [00:01, 24.78it/s]
39it [00:01, 24.95it/s]
42it [00:01, 25.20it/s]
45it [00:01, 25.40it/s]
50it [00:02, 24.96it/s]
10it [00:27,  2.77s/it]

predict using best model..

90it [00:17,  5.23it/s]

done
Time taken: 0.86 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df150

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
18.9,2,0,387,0,0,1,1,0,0,2,...,0,1,0,0,0,0,2,0,0,0
32.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
41.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,1,1,1,392,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0
104.1,0,0,0,0,0,0,390,2,0,4,...,0,0,0,0,0,0,0,0,0,0
111.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,1,397,1,...,0,0,1,0,0,0,0,0,0,0
129.0,0,1,5,1,1,0,0,0,0,390,...,0,0,0,0,0,0,1,0,0,0
146.0,0,2,0,0,0,0,1,0,1,0,...,0,1,0,1,0,0,0,0,0,0
147.0,0,1,0,0,0,2,1,2,0,1,...,1,0,0,0,0,1,0,0,0,0
150.0,0,0,0,1,1,0,2,0,0,1,...,0,0,1,1,0,0,1,0,0,0
151.0,1,2,2,1,0,0,0,2,0,3,...,1,0,2,0,0,1,1,0,0,0
153.0,3,0,1,1,0,0,1,3,1,3,...,0,0,2,2,0,2,5,0,0,0
154.0,1,0,3,2,0,2,1,3,0,5,...,0,1,4,2,2,0,1,0,0,0
161.0,0,2,1,0,1,0,0,1,0,2,...,379,1,3,2,1,2,1,0,0,0
169.0,2,1,9,1,0,2,4,1,1,7,...,1,347,2,4,3,0,0,0,1,0
185.9,2,3,8,1,1,2,2,3,4,11,...,2,0,338,2,3,0,1,0,0,0
197.0,2,2,9,2,0,2,5,3,0,11,...,0,2,5,335,1,1,2,0,0,0
212.9,1,5,7,3,2,2,1,5,1,9,...,0,1,8,2,319,0,6,0,0,0
217.0,3,3,10,3,1,5,0,2,3,10,...,2,2,7,3,0,323,5,0,0,0
239.2,0,0,0,1,0,0,0,0,1,1,...,0,0,2,0,0,0,394,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
1,7.1,0.977500,0.977500,0.022500,0.002494,0.939904,0.977500,0.958333,0.060096,0.022500,0.680443
2,18.9,0.967500,0.967500,0.032500,0.006063,0.863839,0.967500,0.912736,0.136161,0.032500,1.008122
3,32.1,0.990000,0.990000,0.010000,0.001996,0.951923,0.990000,0.970588,0.048077,0.010000,0.414882
4,41.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,1.101860
5,98.9,0.980000,0.980000,0.020000,0.001896,0.953771,0.980000,0.966708,0.046229,0.020000,1.039126
6,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.524005
7,111.0,0.962500,0.962500,0.037500,0.002991,0.927711,0.962500,0.944785,0.072289,0.037500,0.724503
8,128.0,0.992500,0.992500,0.007500,0.001298,0.968293,0.992500,0.980247,0.031707,0.007500,0.952407
9,129.0,0.975000,0.975000,0.025000,0.007346,0.840517,0.975000,0.902778,0.159483,0.025000,0.832551
10,146.0,0.975000,0.975000,0.025000,0.002693,0.935252,0.975000,0.954712,0.064748,0.025000,0.890677
11,147.0,0.962500,0.962500,0.037500,0.003090,0.925481,0.962500,0.943627,0.074519,0.037500,0.690750
12,150.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.752044
13,151.0,0.947500,0.947500,0.052500,0.001697,0.957071,0.947500,0.952261,0.042929,0.052500,0.903021
14,153.0,0.917500,0.917500,0.082500,0.002494,0.936224,0.917500,0.926768,0.063776,0.082500,0.679885
15,154.0,0.912500,0.912500,0.087500,0.003190,0.919395,0.912500,0.915935,0.080605,0.087500,0.662708
16,161.0,0.947500,0.947500,0.052500,0.000899,0.976804,0.947500,0.961929,0.023196,0.052500,0.739237
17,169.0,0.867500,0.867500,0.132500,0.000899,0.974719,0.867500,0.917989,0.025281,0.132500,0.764063
18,185.9,0.845000,0.845000,0.155000,0.003885,0.896552,0.845000,0.870013,0.103448,0.155000,0.517739
19,197.0,0.837500,0.837500,0.162500,0.002195,0.938375,0.837500,0.885073,0.061625,0.162500,0.558233
20,212.9,0.797500,0.797500,0.202500,0.000999,0.969605,0.797500,0.875171,0.030395,0.202500,0.604325
21,217.0,0.807500,0.807500,0.192500,0.000700,0.978788,0.807500,0.884932,0.021212,0.192500,0.704864
22,239.2,0.985000,0.985000,0.015000,0.002991,0.929245,0.985000,0.956311,0.070755,0.015000,0.678525
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.501234
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.944423,0.944423,0.055577,0.002215,0.945957,0.944423,0.943818,0.054043,0.055577,0.498437

In [ ]:
cv_result150

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.661538  0.665610    0.338462  0.661538    0.669732
1       2.0  0.786538  0.792558    0.213462  0.786538    0.798670
2       3.0  0.686538  0.686187    0.313462  0.686538    0.685835
3       4.0  0.739423  0.745594    0.260577  0.739423    0.751870
4       5.0  0.665385  0.668003    0.334615  0.665385    0.670642
5       6.0  0.771154  0.778406    0.228846  0.771154    0.785795
6       7.0  0.666346  0.668824    0.333654  0.666346    0.671320
7       8.0  0.750000  0.757324    0.250000  0.750000    0.764793
8       9.0  0.673077  0.672171    0.326923  0.673077    0.671268
9      10.0  0.766346  0.773695    0.233654  0.766346    0.781187
10       11  0.944423  0.945190    0.055577  0.944423    0.945957
11  average  0.716635  0.720837    0.283365  0.716635    0.725111
12      max  0.786538  0.792558    0.213462  0.786538    0.798670

### SAVE MODEL dTOP150fi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn150_double_sim.pkl', 'wb') as f:
   pickle.dump(knn150, f)

## TRAIN K-NN ALLfi

In [ ]:
# train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for train_data353
X_train353 = train_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_train353 = train_data353['tp_ICD_cl0']

In [ ]:
timer = CalculateTime(features='all', data_type='train')
timer.start()

knn353, data_top_5, Confusion_df353, eval_result353, cv_result353 = knn_custom_kfold_evaluation(X_train353, y_train353, le, 353, first_c353, last_c353, first_n353, last_n353, first_o353, last_o353, batch=True, n_neighbors=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

0it [00:00, ?it/s]

predicting model on fold 1..

0it [00:00, ?it/s]
1it [00:00,  1.88it/s]
3it [00:00,  5.40it/s]
5it [00:00,  8.55it/s]
7it [00:00, 11.16it/s]
9it [00:00, 13.26it/s]
11it [00:01, 14.87it/s]
13it [00:01, 16.06it/s]
15it [00:01, 16.87it/s]
17it [00:01, 17.52it/s]
19it [00:01, 18.06it/s]
21it [00:01, 18.43it/s]
23it [00:01, 18.62it/s]
25it [00:01, 18.81it/s]
27it [00:01, 18.86it/s]
29it [00:02, 18.97it/s]
31it [00:02, 19.05it/s]
33it [00:02, 19.10it/s]
35it [00:02, 19.08it/s]
37it [00:02, 19.14it/s]
39it [00:02, 19.24it/s]
41it [00:02, 19.34it/s]
43it [00:02, 19.52it/s]
46it [00:02, 19.84it/s]
50it [00:03, 16.20it/s]
1it [00:03,  3.93s/it]

predicting model on fold 2..

0it [00:00, ?it/s]
2it [00:00, 19.55it/s]
4it [00:00, 19.32it/s]
6it [00:00, 19.28it/s]
8it [00:00, 19.02it/s]
10it [00:00, 19.02it/s]
12it [00:00, 19.15it/s]
14it [00:00, 18.98it/s]
16it [00:00, 19.08it/s]
18it [00:00, 19.08it/s]
20it [00:01, 19.04it/s]
22it [00:01, 19.03it/s]
24it [00:01, 19.09it/s]
26it [00:01, 18.97it/s]
28it [00:01, 19.04it/s]
30it [00:01, 19.15it/s]
32it [00:01, 19.06it/s]
34it [00:01, 18.94it/s]
36it [00:01, 19.05it/s]
38it [00:01, 19.12it/s]
40it [00:02, 19.10it/s]
42it [00:02, 19.33it/s]
44it [00:02, 19.52it/s]
46it [00:02, 19.60it/s]
50it [00:02, 19.23it/s]
2it [00:07,  3.57s/it]

predicting model on fold 3..

0it [00:00, ?it/s]
2it [00:00, 19.48it/s]
4it [00:00, 19.36it/s]
6it [00:00, 19.25it/s]
8it [00:00, 19.26it/s]
10it [00:00, 19.25it/s]
12it [00:00, 18.96it/s]
14it [00:00, 19.06it/s]
16it [00:00, 19.06it/s]
18it [00:00, 19.13it/s]
20it [00:01, 19.08it/s]
22it [00:01, 19.02it/s]
24it [00:01, 19.11it/s]
26it [00:01, 19.20it/s]
28it [00:01, 19.15it/s]
30it [00:01, 19.20it/s]
32it [00:01, 19.15it/s]
34it [00:01, 19.09it/s]
36it [00:01, 19.07it/s]
38it [00:01, 18.96it/s]
40it [00:02, 18.96it/s]
42it [00:02, 19.18it/s]
44it [00:02, 19.28it/s]
46it [00:02, 19.39it/s]
50it [00:02, 19.13it/s]
3it [00:10,  3.54s/it]

predicting model on fold 4..

0it [00:00, ?it/s]
2it [00:00, 19.40it/s]
4it [00:00, 18.97it/s]
6it [00:00, 18.89it/s]
8it [00:00, 18.67it/s]
10it [00:00, 18.36it/s]
12it [00:00, 18.27it/s]
14it [00:00, 18.51it/s]
16it [00:00, 18.42it/s]
18it [00:00, 18.59it/s]
20it [00:01, 18.77it/s]
22it [00:01, 18.83it/s]
24it [00:01, 18.85it/s]
26it [00:01, 18.93it/s]
28it [00:01, 19.03it/s]
30it [00:01, 19.02it/s]
32it [00:01, 19.07it/s]
34it [00:01, 19.14it/s]
36it [00:01, 19.12it/s]
38it [00:02, 19.21it/s]
40it [00:02, 19.23it/s]
43it [00:02, 19.65it/s]
46it [00:02, 19.88it/s]
48it [00:02, 19.87it/s]
50it [00:02, 19.10it/s]
4it [00:14,  3.45s/it]

predicting model on fold 5..

0it [00:00, ?it/s]
2it [00:00, 19.43it/s]
4it [00:00, 19.29it/s]
6it [00:00, 19.26it/s]
8it [00:00, 19.23it/s]
10it [00:00, 19.26it/s]
12it [00:00, 19.18it/s]
14it [00:00, 19.03it/s]
16it [00:00, 19.04it/s]
18it [00:00, 19.03it/s]
20it [00:01, 19.03it/s]
22it [00:01, 19.01it/s]
24it [00:01, 18.98it/s]
26it [00:01, 19.03it/s]
28it [00:01, 19.10it/s]
30it [00:01, 19.15it/s]
32it [00:01, 19.11it/s]
34it [00:01, 19.07it/s]
36it [00:01, 19.02it/s]
38it [00:01, 19.05it/s]
40it [00:02, 19.06it/s]
42it [00:02, 19.26it/s]
44it [00:02, 19.39it/s]
46it [00:02, 19.40it/s]
48it [00:02, 19.37it/s]
50it [00:02, 19.17it/s]
5it [00:17,  3.45s/it]

predicting model on fold 6..

0it [00:00, ?it/s]
2it [00:00, 19.33it/s]
4it [00:00, 19.28it/s]
6it [00:00, 19.19it/s]
8it [00:00, 19.24it/s]
10it [00:00, 19.19it/s]
12it [00:00, 19.12it/s]
14it [00:00, 18.81it/s]
16it [00:00, 18.61it/s]
18it [00:00, 18.79it/s]
20it [00:01, 18.91it/s]
22it [00:01, 18.98it/s]
24it [00:01, 19.08it/s]
26it [00:01, 19.18it/s]
28it [00:01, 19.17it/s]
30it [00:01, 19.23it/s]
32it [00:01, 19.29it/s]
34it [00:01, 19.29it/s]
36it [00:01, 19.21it/s]
38it [00:01, 19.12it/s]
40it [00:02, 18.91it/s]
42it [00:02, 19.13it/s]
44it [00:02, 19.25it/s]
46it [00:02, 19.45it/s]
50it [00:02, 19.20it/s]
6it [00:20,  3.40s/it]

predicting model on fold 7..

0it [00:00, ?it/s]
2it [00:00, 19.51it/s]
4it [00:00, 19.27it/s]
6it [00:00, 19.24it/s]
8it [00:00, 19.27it/s]
10it [00:00, 19.01it/s]
12it [00:00, 18.96it/s]
14it [00:00, 19.01it/s]
16it [00:00, 18.79it/s]
18it [00:00, 18.83it/s]
20it [00:01, 18.82it/s]
22it [00:01, 18.65it/s]
24it [00:01, 18.54it/s]
26it [00:01, 18.54it/s]
28it [00:01, 18.60it/s]
30it [00:01, 18.54it/s]
32it [00:01, 18.60it/s]
34it [00:01, 18.49it/s]
36it [00:01, 18.51it/s]
38it [00:02, 18.59it/s]
40it [00:02, 18.50it/s]
42it [00:02, 18.70it/s]
44it [00:02, 18.66it/s]
46it [00:02, 18.74it/s]
48it [00:02, 18.85it/s]
50it [00:02, 18.77it/s]
7it [00:24,  3.43s/it]

predicting model on fold 8..

0it [00:00, ?it/s]
2it [00:00, 19.38it/s]
4it [00:00, 19.40it/s]
6it [00:00, 19.32it/s]
8it [00:00, 19.30it/s]
10it [00:00, 19.23it/s]
12it [00:00, 19.24it/s]
14it [00:00, 19.25it/s]
16it [00:00, 19.23it/s]
18it [00:00, 19.24it/s]
20it [00:01, 19.15it/s]
22it [00:01, 19.15it/s]
24it [00:01, 19.18it/s]
26it [00:01, 19.15it/s]
28it [00:01, 19.19it/s]
30it [00:01, 18.80it/s]
32it [00:01, 18.57it/s]
34it [00:01, 18.67it/s]
36it [00:01, 18.85it/s]
38it [00:01, 18.93it/s]
40it [00:02, 18.67it/s]
42it [00:02, 18.88it/s]
44it [00:02, 19.05it/s]
46it [00:02, 19.06it/s]
48it [00:02, 19.32it/s]
50it [00:02, 19.10it/s]
8it [00:27,  3.40s/it]

predicting model on fold 9..

0it [00:00, ?it/s]
2it [00:00, 18.82it/s]
4it [00:00, 18.44it/s]
6it [00:00, 18.67it/s]
8it [00:00, 18.95it/s]
10it [00:00, 18.97it/s]
12it [00:00, 18.88it/s]
14it [00:00, 18.76it/s]
16it [00:00, 18.88it/s]
18it [00:00, 18.88it/s]
20it [00:01, 18.59it/s]
22it [00:01, 18.78it/s]
24it [00:01, 18.87it/s]
26it [00:01, 18.90it/s]
28it [00:01, 18.96it/s]
30it [00:01, 18.87it/s]
32it [00:01, 18.82it/s]
34it [00:01, 18.94it/s]
36it [00:01, 19.07it/s]
38it [00:02, 18.73it/s]
40it [00:02, 18.76it/s]
42it [00:02, 19.00it/s]
44it [00:02, 19.23it/s]
46it [00:02, 19.37it/s]
48it [00:02, 19.52it/s]
50it [00:02, 18.97it/s]
9it [00:31,  3.43s/it]

predicting model on fold 10..

0it [00:00, ?it/s]
2it [00:00, 19.56it/s]
4it [00:00, 19.29it/s]
6it [00:00, 19.09it/s]
8it [00:00, 19.06it/s]
10it [00:00, 19.03it/s]
12it [00:00, 18.97it/s]
14it [00:00, 18.94it/s]
16it [00:00, 18.85it/s]
18it [00:00, 18.96it/s]
20it [00:01, 18.95it/s]
22it [00:01, 18.91it/s]
24it [00:01, 18.82it/s]
26it [00:01, 18.89it/s]
28it [00:01, 18.99it/s]
30it [00:01, 19.04it/s]
32it [00:01, 19.12it/s]
34it [00:01, 19.04it/s]
36it [00:01, 19.02it/s]
38it [00:02, 18.93it/s]
40it [00:02, 19.00it/s]
42it [00:02, 19.17it/s]
44it [00:02, 19.29it/s]
46it [00:02, 19.37it/s]
48it [00:02, 19.34it/s]
50it [00:02, 19.07it/s]
10it [00:34,  3.45s/it]

predict using best model..

90it [00:20,  4.32it/s]

done
Time taken: 1.03 minutes

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1

In [ ]:
Confusion_df353

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,397,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7.1,0,395,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18.9,2,1,385,1,0,0,0,0,2,2,...,0,1,0,0,0,0,3,0,0,0
32.1,0,0,0,396,0,0,0,0,0,1,...,0,0,0,0,0,0,2,0,0,0
41.0,0,0,0,0,390,0,1,0,2,1,...,1,0,0,0,0,0,0,0,0,0
98.9,0,0,2,1,0,391,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
104.1,0,0,0,0,0,0,389,0,2,3,...,0,1,0,0,0,1,0,0,0,0
111.0,0,0,2,0,0,1,2,383,1,1,...,1,0,1,1,0,0,1,0,0,0
128.0,0,1,0,0,0,0,0,1,390,0,...,0,0,2,1,0,0,1,0,0,0
129.0,2,1,2,0,2,1,1,0,3,385,...,0,0,0,0,1,1,0,0,0,0
146.0,1,2,0,0,0,0,3,0,4,1,...,0,0,1,0,0,0,1,0,0,0
147.0,4,2,0,0,1,2,1,1,1,4,...,1,0,0,1,1,1,0,0,0,0
150.0,2,2,1,0,1,1,1,1,2,1,...,0,2,2,1,1,0,2,0,0,0
151.0,2,2,0,0,0,0,1,1,4,1,...,2,2,3,2,0,1,1,0,0,0
153.0,4,3,2,2,1,3,0,3,2,5,...,1,1,2,1,1,2,2,0,0,0
154.0,3,1,5,0,1,1,1,2,2,6,...,0,0,5,2,1,0,0,0,0,0
161.0,5,6,5,2,6,1,3,2,8,9,...,328,2,4,3,1,1,1,0,0,0
169.0,2,5,10,3,6,3,2,1,4,8,...,3,323,2,2,3,2,1,0,1,0
185.9,6,6,6,1,5,5,4,4,5,12,...,0,0,313,4,3,1,3,0,0,0
197.0,6,2,11,1,4,7,5,4,7,11,...,2,1,5,309,2,2,4,0,0,0
212.9,3,10,4,3,2,8,3,2,8,11,...,0,2,6,3,297,0,5,0,0,0
217.0,4,1,11,4,2,3,1,4,9,15,...,2,2,7,4,0,307,3,0,0,0
239.2,0,2,0,1,0,0,0,0,1,0,...,0,0,3,0,0,0,392,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.992500,0.992500,0.007500,0.004579,0.896163,0.992500,0.941874,0.103837,0.007500,0.055294
1,7.1,0.987500,0.987500,0.012500,0.004678,0.893665,0.987500,0.938242,0.106335,0.012500,0.774043
2,18.9,0.962500,0.962500,0.037500,0.006162,0.861298,0.962500,0.909091,0.138702,0.037500,0.853777
3,32.1,0.990000,0.990000,0.010000,0.001896,0.954217,0.990000,0.971779,0.045783,0.010000,0.429369
4,41.0,0.975000,0.975000,0.025000,0.003090,0.926366,0.975000,0.950061,0.073634,0.025000,0.703796
5,98.9,0.977500,0.977500,0.022500,0.003686,0.913551,0.977500,0.944444,0.086449,0.022500,0.882488
6,104.1,0.972500,0.972500,0.027500,0.002892,0.930622,0.972500,0.951100,0.069378,0.027500,0.579591
7,111.0,0.957500,0.957500,0.042500,0.002593,0.936430,0.957500,0.946848,0.063570,0.042500,0.727675
8,128.0,0.975000,0.975000,0.025000,0.006655,0.853392,0.975000,0.910152,0.146608,0.025000,0.680600
9,129.0,0.962500,0.962500,0.037500,0.009312,0.803758,0.962500,0.875995,0.196242,0.037500,1.028561
10,146.0,0.960000,0.960000,0.040000,0.003984,0.905660,0.960000,0.932039,0.094340,0.040000,0.705799
11,147.0,0.932500,0.932500,0.067500,0.002593,0.934837,0.932500,0.933667,0.065163,0.067500,1.095783
12,150.0,0.935000,0.935000,0.065000,0.004182,0.899038,0.935000,0.916667,0.100962,0.065000,0.956766
13,151.0,0.935000,0.935000,0.065000,0.002593,0.935000,0.935000,0.935000,0.065000,0.065000,0.773271
14,153.0,0.872500,0.872500,0.127500,0.003289,0.913613,0.872500,0.892583,0.086387,0.127500,0.666019
15,154.0,0.905000,0.905000,0.095000,0.003885,0.902743,0.905000,0.903870,0.097257,0.095000,0.707206
16,161.0,0.820000,0.820000,0.180000,0.001298,0.961877,0.820000,0.885290,0.038123,0.180000,0.653380
17,169.0,0.807500,0.807500,0.192500,0.001498,0.955621,0.807500,0.875339,0.044379,0.192500,0.784168
18,185.9,0.782500,0.782500,0.217500,0.004282,0.879213,0.782500,0.828042,0.120787,0.217500,0.509310
19,197.0,0.772500,0.772500,0.227500,0.002693,0.919643,0.772500,0.839674,0.080357,0.227500,0.727116
20,212.9,0.742500,0.742500,0.257500,0.001398,0.954984,0.742500,0.835443,0.045016,0.257500,0.705379
21,217.0,0.767500,0.767500,0.232500,0.001199,0.962382,0.767500,0.853964,0.037618,0.232500,0.487805
22,239.2,0.980000,0.980000,0.020000,0.003090,0.926714,0.980000,0.952612,0.073286,0.020000,0.706865
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.515731
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.921154,0.921154,0.078846,0.003140,0.923779,0.921154,0.919807,0.076221,0.078846,0.642684

In [ ]:
cv_result353

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.628846  0.631709    0.371154  0.628846    0.634598
1       2.0  0.725962  0.735149    0.274038  0.725962    0.744572
2       3.0  0.651923  0.654129    0.348077  0.651923    0.656350
3       4.0  0.710577  0.719500    0.289423  0.710577    0.728650
4       5.0  0.624038  0.627892    0.375962  0.624038    0.631793
5       6.0  0.724038  0.731684    0.275962  0.724038    0.739493
6       7.0  0.633654  0.637298    0.366346  0.633654    0.640985
7       8.0  0.714423  0.724047    0.285577  0.714423    0.733933
8       9.0  0.641346  0.640501    0.358654  0.641346    0.639657
9      10.0  0.704808  0.715495    0.295192  0.704808    0.726511
10       11  0.921154  0.922465    0.078846  0.921154    0.923779
11  average  0.675962  0.681740    0.324038  0.675962    0.687654
12      max  0.725962  0.735149    0.274038  0.725962    0.744572

### SAVE MODEL dAllfi

In [ ]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn353_double_sim.pkl', 'wb') as f:
   pickle.dump(knn353, f)

# **TESTING**

## LOADING TEST_DATASET

In [ ]:
# sudah load dataset testing dari awal

## LOAD & APPLY MODEL_SHAP

In [ ]:
# sudah apply shap ke data testing dari awal

## LOAD & APPLY MODEL dTOP5fi

In [ ]:
# le = LabelEncoder()
# le.fit(test_data5['tp_ICD_cl0'])

In [ ]:
# test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data5
X_test5 = test_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_test5 = test_data5['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn5_double_sim.pkl', 'rb') as f:
  knn5 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=50)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test5, y_test5)):
    X_test_fold = X_test5.values[test_index]

    probability = knn5.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

50it [00:08,  6.17it/s]

In [ ]:
classes5 = knn5.classes_

y_pred5, data_top_5 = get_predictions(y_prob_all, classes5, 10, np.array(y_test5), le)

Confusion_df5 = pd.DataFrame(confusion_matrix(np.array(y_test5), y_pred5))
Confusion_df5.index, Confusion_df5.columns = le.inverse_transform(classes5), le.inverse_transform(classes5)

eval_result5 = calculate_evaluation_metrics(Confusion_df=Confusion_df5)

<ipython-input-81-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-81-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,212.9,0.208333,5.0,0.125000,7.1,0.083333,32.1,0.083333,41.0,0.083333
2,41.0,98.9,0.625000,169.0,0.166667,41.0,0.083333,7.1,0.041667,111.0,0.041667
3,129.0,161.0,0.291667,128.0,0.166667,150.0,0.166667,146.0,0.125000,7.1,0.083333
4,169.0,98.9,0.666667,169.0,0.166667,7.1,0.083333,41.0,0.041667,111.0,0.041667
5,161.0,161.0,0.291667,41.0,0.208333,169.0,0.125000,7.1,0.083333,18.9,0.083333
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,98.9,0.583333,169.0,0.125000,41.0,0.083333,249.0,0.083333,7.1,0.041667
10397,153.0,212.9,0.208333,5.0,0.125000,128.0,0.125000,7.1,0.083333,32.1,0.083333
10398,169.0,169.0,0.250000,161.0,0.208333,41.0,0.166667,129.0,0.083333,7.1,0.041667
10399,249.0,98.9,0.625000,169.0,0.125000,41.0,0.083333,7.1,0.041667,161.0,0.041667
10400,150.0,146.0,0.333333,128.0,0.166667,7.1,0.125000,98.9,0.125000,41.0,0.041667

In [ ]:
Confusion_df5.index = Confusion_df5.index + 1
Confusion_df5
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,64,2,0,0,34,167,0,0,82,0,...,32,0,0,0,0,0,0,0,0,0
8.1,0,211,0,0,22,6,1,0,96,0,...,25,0,0,0,15,0,0,0,0,0
19.9,0,9,138,0,45,19,6,0,103,0,...,36,0,0,0,6,0,0,0,0,0
33.1,0,2,0,143,58,81,0,0,56,0,...,44,0,0,0,13,0,0,0,0,0
42.0,0,0,0,0,374,8,0,0,11,0,...,5,0,0,0,0,0,0,0,0,0
99.9,0,1,0,0,39,253,0,0,73,0,...,21,0,0,0,2,0,0,0,0,0
105.1,0,4,0,0,16,1,220,0,122,0,...,23,0,0,0,0,0,0,0,0,0
112.0,0,7,0,0,45,5,3,143,134,0,...,36,1,0,0,5,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,2,0,0,79,3,2,0,177,50,...,40,0,0,0,3,0,0,0,0,0
147.0,0,5,0,0,46,0,0,0,62,0,...,25,0,0,0,7,0,0,0,0,0
148.0,0,3,0,0,45,0,0,0,104,0,...,51,1,0,0,3,0,0,0,0,0
151.0,0,1,0,0,17,0,0,0,53,0,...,6,0,0,0,1,0,0,0,0,0
152.0,0,2,0,0,10,2,0,0,63,0,...,39,0,0,0,2,0,0,0,0,0
154.0,0,3,0,0,57,2,0,0,225,0,...,52,0,0,0,3,0,0,0,0,0
155.0,0,1,0,0,62,4,3,0,215,0,...,49,0,0,0,1,0,0,0,0,0
162.0,0,0,0,0,0,2,0,0,8,0,...,387,0,0,0,2,0,0,0,0,0
170.0,0,5,0,0,4,0,0,0,30,0,...,14,330,0,0,1,0,0,0,0,0
186.9,0,3,0,0,41,13,2,0,121,0,...,43,1,147,0,8,0,0,0,0,0
198.0,0,4,0,0,62,10,0,0,161,0,...,61,0,0,63,5,0,0,0,0,0
213.9,0,2,0,0,47,0,2,0,107,0,...,26,2,0,0,206,0,0,0,0,0
218.0,0,12,0,0,67,8,1,0,179,0,...,55,0,0,0,8,48,0,0,0,0
240.2,0,84,0,0,44,7,0,0,58,0,...,88,0,0,0,44,0,60,0,0,0
249.0,0,21,0,0,0,349,0,0,0,0,...,0,0,0,0,30,0,0,0,0,0
250.0,0,22,0,0,8,0,0,0,7,0,...,1,1,0,0,16,0,0,0,344,0
252.0,0,20,0,0,0,351,0,0,0,0,...,0,0,0,0,29,0,0,0,0,0

In [ ]:
eval_result5.index = eval_result5.index + 1
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.160000,0.160000,0.840000,0.000000,1.000000,0.160000,0.275862,0.000000,0.840000,0.847202
2,7.1,0.527500,0.527500,0.472500,0.021047,0.495305,0.527500,0.510896,0.504695,0.472500,0.520397
3,18.9,0.345000,0.345000,0.655000,0.000000,1.000000,0.345000,0.513011,0.000000,0.655000,0.773341
4,32.1,0.357500,0.357500,0.642500,0.000000,1.000000,0.357500,0.526703,0.000000,0.642500,0.760458
5,41.0,0.935000,0.935000,0.065000,0.078171,0.306056,0.935000,0.461159,0.693944,0.065000,0.499001
6,98.9,0.632500,0.632500,0.367500,0.094039,0.195972,0.632500,0.299231,0.804028,0.367500,0.773705
7,104.1,0.550000,0.550000,0.450000,0.001996,0.916667,0.550000,0.687500,0.083333,0.450000,0.482427
8,111.0,0.357500,0.357500,0.642500,0.000000,1.000000,0.357500,0.526703,0.000000,0.642500,0.773341
9,128.0,1.000000,1.000000,0.000000,0.183474,0.151114,1.000000,0.262553,0.848886,0.000000,0.000000
10,129.0,0.125000,0.125000,0.875000,0.000000,1.000000,0.125000,0.222222,0.000000,0.875000,0.578112
11,146.0,0.625000,0.625000,0.375000,0.009607,0.720461,0.625000,0.669344,0.279539,0.375000,0.477125
12,147.0,0.460000,0.460000,0.540000,0.001597,0.920000,0.460000,0.613333,0.080000,0.540000,0.485184
13,150.0,0.782500,0.782500,0.217500,0.018068,0.629779,0.782500,0.697882,0.370221,0.217500,0.477121
14,151.0,0.700000,0.700000,0.300000,0.008821,0.758808,0.700000,0.728218,0.241192,0.300000,0.477121
15,153.0,0.040000,0.040000,0.960000,0.000000,1.000000,0.040000,0.076923,0.000000,0.960000,0.609920
16,154.0,0.100000,0.100000,0.900000,0.000000,1.000000,0.100000,0.181818,0.000000,0.900000,0.613134
17,161.0,0.967500,0.967500,0.032500,0.071667,0.333909,0.967500,0.496472,0.666091,0.032500,0.481524
18,169.0,0.825000,0.825000,0.175000,0.000600,0.982143,0.825000,0.896739,0.017857,0.175000,0.477122
19,185.9,0.367500,0.367500,0.632500,0.000000,1.000000,0.367500,0.537477,0.000000,0.632500,0.553798
20,197.0,0.157500,0.157500,0.842500,0.000000,1.000000,0.157500,0.272138,0.000000,0.842500,0.486598
21,212.9,0.515000,0.515000,0.485000,0.019992,0.502439,0.515000,0.508642,0.497561,0.485000,0.773706
22,217.0,0.120000,0.120000,0.880000,0.000000,1.000000,0.120000,0.214286,0.000000,0.880000,0.479850
23,239.2,0.150000,0.150000,0.850000,0.000000,1.000000,0.150000,0.260870,0.000000,0.850000,0.482772
24,248.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.356819
25,249.0,0.860000,0.860000,0.140000,0.000000,1.000000,0.860000,0.924731,0.000000,0.140000,0.993247
26,251.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.356819
27,average,0.448462,0.448462,0.551538,0.019580,0.727410,0.448462,0.437104,0.211973,0.551538,0.561148

In [ ]:
Confusion_df5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn5.csv')
eval_result5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn5.csv', index=False)

## LOAD & APPLY MODEL dTOP10fi

In [ ]:
# test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data10
X_test10 = test_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_test10 = test_data10['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn10_double_sim.pkl', 'rb') as f:
    knn10 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=30)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test10, y_test10)):
    X_test_fold = X_test10.values[test_index]

    probability = knn10.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

30it [00:15,  1.90it/s]

In [ ]:
classes10 = knn10.classes_

y_pred10, data_top_5 = get_predictions(y_prob_all, classes10, 10, np.array(y_test10), le)

Confusion_df10 = pd.DataFrame(confusion_matrix(np.array(y_test10), y_pred10))
Confusion_df10.index, Confusion_df10.columns = le.inverse_transform(classes10), le.inverse_transform(classes10)

eval_result10 = calculate_evaluation_metrics(Confusion_df=Confusion_df10)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.454545,248.0,0.272727,249.0,0.272727,NaN,NaN,NaN,NaN
2,41.0,5.0,0.318182,32.1,0.318182,249.0,0.181818,41.0,0.090909,104.1,0.045455
3,129.0,129.0,0.272727,150.0,0.227273,151.0,0.136364,41.0,0.090909,154.0,0.090909
4,169.0,5.0,0.409091,32.1,0.363636,98.9,0.136364,169.0,0.045455,197.0,0.045455
5,161.0,161.0,0.454545,41.0,0.136364,5.0,0.090909,18.9,0.090909,7.1,0.045455
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.409091,251.0,0.409091,248.0,0.181818,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.500000,32.1,0.136364,111.0,0.136364,5.0,0.045455,41.0,0.045455
10398,169.0,41.0,0.318182,161.0,0.227273,150.0,0.136364,169.0,0.136364,18.9,0.045455
10399,249.0,249.0,0.363636,248.0,0.272727,251.0,0.181818,197.0,0.090909,5.0,0.045455
10400,150.0,239.2,0.227273,98.9,0.181818,197.0,0.090909,212.9,0.090909,7.1,0.045455

In [ ]:
Confusion_df10.index = Confusion_df10.index + 1
Confusion_df10
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,396,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,1,0,0,0,0
8.1,0,391,0,0,2,0,1,0,0,1,...,1,1,0,0,0,0,1,0,0,0
19.9,0,1,390,1,1,0,0,0,0,2,...,0,1,1,0,0,1,1,0,0,0
33.1,0,1,0,393,1,0,0,0,2,1,...,0,0,0,0,0,1,1,0,0,0
42.0,0,0,0,0,389,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
99.9,1,1,1,1,0,393,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
105.1,1,1,2,0,0,1,385,0,1,3,...,0,0,0,2,0,0,0,0,0,0
112.0,0,0,2,0,0,0,2,385,1,1,...,0,1,1,4,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,398,0,...,0,1,0,0,0,0,0,0,0,0
130.0,1,3,2,0,0,0,1,1,1,374,...,1,0,4,0,0,0,0,0,0,0
147.0,0,1,2,0,1,0,1,0,0,2,...,0,3,1,1,1,1,0,0,0,0
148.0,0,1,3,0,1,2,2,2,0,3,...,0,0,1,3,1,0,0,0,0,0
151.0,1,2,3,1,1,5,1,3,0,4,...,0,0,3,2,1,0,3,0,0,0
152.0,2,1,1,0,2,3,4,3,0,4,...,1,0,3,1,3,0,3,0,0,0
154.0,2,3,5,2,0,2,3,7,0,4,...,1,0,2,5,2,2,1,0,0,0
155.0,6,4,3,0,0,2,6,4,0,2,...,1,3,10,4,0,3,1,0,0,0
162.0,2,3,1,2,3,2,7,3,2,3,...,335,0,4,5,4,0,2,0,0,0
170.0,4,6,5,1,0,4,2,4,0,6,...,3,321,3,6,5,3,3,0,1,0
186.9,2,6,5,0,3,5,9,6,4,10,...,0,2,300,5,0,5,6,0,0,0
198.0,5,9,8,3,1,7,5,7,1,8,...,0,1,7,303,1,5,1,0,0,0
213.9,2,8,3,2,2,6,6,5,1,4,...,2,3,7,3,301,5,2,0,0,0
218.0,2,10,10,4,3,6,7,9,1,11,...,0,3,2,6,1,296,2,0,0,0
240.2,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,397,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,399,1,0
250.0,1,2,1,0,1,0,0,2,1,1,...,0,1,2,0,0,0,2,0,384,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result10.index = eval_result10.index + 1
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.9900,0.9900,0.0100,0.003190,0.925234,0.9900,0.956522,0.074766,0.0100,0.113198
2,7.1,0.9775,0.9775,0.0225,0.006261,0.861233,0.9775,0.915691,0.138767,0.0225,0.636293
3,18.9,0.9750,0.9750,0.0250,0.005668,0.872483,0.9750,0.920897,0.127517,0.0250,0.784213
4,32.1,0.9825,0.9825,0.0175,0.001896,0.953883,0.9825,0.967980,0.046117,0.0175,0.765013
5,41.0,0.9725,0.9725,0.0275,0.002195,0.946472,0.9725,0.959309,0.053528,0.0275,0.507590
6,98.9,0.9825,0.9825,0.0175,0.004777,0.891156,0.9825,0.934602,0.108844,0.0175,1.086625
7,104.1,0.9625,0.9625,0.0375,0.005767,0.869074,0.9625,0.913405,0.130926,0.0375,0.814044
8,111.0,0.9625,0.9625,0.0375,0.005569,0.873016,0.9625,0.915577,0.126984,0.0375,0.545628
9,128.0,0.9950,0.9950,0.0050,0.001498,0.963680,0.9950,0.979090,0.036320,0.0050,2.219405
10,129.0,0.9350,0.9350,0.0650,0.006951,0.842342,0.9350,0.886256,0.157658,0.0650,0.719473
11,146.0,0.9425,0.9425,0.0575,0.006162,0.858770,0.9425,0.898689,0.141230,0.0575,0.705147
12,147.0,0.9125,0.9125,0.0875,0.004777,0.883777,0.9125,0.897909,0.116223,0.0875,0.602273
13,150.0,0.9050,0.9050,0.0950,0.004381,0.891626,0.9050,0.898263,0.108374,0.0950,0.745921
14,151.0,0.8875,0.8875,0.1125,0.005173,0.872236,0.8875,0.879802,0.127764,0.1125,0.779619
15,153.0,0.8425,0.8425,0.1575,0.002593,0.928375,0.8425,0.883355,0.071625,0.1575,0.693289
16,154.0,0.8450,0.8450,0.1550,0.005074,0.868895,0.8450,0.856781,0.131105,0.1550,0.485018
17,161.0,0.8375,0.8375,0.1625,0.000999,0.971014,0.8375,0.899329,0.028986,0.1625,0.636315
18,169.0,0.8025,0.8025,0.1975,0.001996,0.941349,0.8025,0.866397,0.058651,0.1975,0.692711
19,185.9,0.7500,0.7500,0.2500,0.005272,0.849858,0.7500,0.796813,0.150142,0.2500,0.595187
20,197.0,0.7575,0.7575,0.2425,0.004975,0.858357,0.7575,0.804781,0.141643,0.2425,0.947834
21,212.9,0.7525,0.7525,0.2475,0.002096,0.934783,0.7525,0.833795,0.065217,0.2475,0.784825
22,217.0,0.7400,0.7400,0.2600,0.002693,0.916409,0.7400,0.818811,0.083591,0.2600,0.792186
23,239.2,0.9925,0.9925,0.0075,0.002991,0.929742,0.9925,0.960097,0.070258,0.0075,1.606308
24,248.0,0.9975,0.9975,0.0025,0.000000,1.000000,0.9975,0.998748,0.000000,0.0025,0.000000
25,249.0,0.9600,0.9600,0.0400,0.000200,0.994819,0.9600,0.977099,0.005181,0.0400,0.993819
26,251.0,1.0000,1.0000,0.0000,0.000000,1.000000,1.0000,1.000000,0.000000,0.0000,0.000000
27,average,0.9100,0.9100,0.0900,0.003583,0.911484,0.9100,0.908461,0.088516,0.0900,0.740459

In [ ]:
Confusion_df10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn10.csv')
eval_result10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn10.csv', index=False)

## LOAD & APPLY MODEL dTOP20fi

In [ ]:
# test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data20
X_test20 = test_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_test20 = test_data20['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn20_double_sim.pkl', 'rb') as f:
    knn20 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=30)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test20, y_test20)):
    X_test_fold = X_test20.values[test_index]

    probability = knn20.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

30it [00:15,  1.88it/s]

In [ ]:
classes20 = knn20.classes_

y_pred20, data_top_5 = get_predictions(y_prob_all, classes20, 10, np.array(y_test20), le)

Confusion_df20 = pd.DataFrame(confusion_matrix(np.array(y_test20), y_pred20))
Confusion_df20.index, Confusion_df20.columns = le.inverse_transform(classes20), le.inverse_transform(classes20)

eval_result20 = calculate_evaluation_metrics(Confusion_df=Confusion_df20)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.45,249.0,0.35,248.0,0.20,NaN,NaN,NaN,NaN
2,41.0,248.0,0.50,7.1,0.10,147.0,0.10,5.0,0.05,41.0,0.05
3,129.0,129.0,0.20,150.0,0.20,151.0,0.10,154.0,0.10,217.0,0.10
4,169.0,5.0,0.40,32.1,0.35,98.9,0.15,169.0,0.05,197.0,0.05
5,161.0,169.0,0.25,41.0,0.20,161.0,0.20,7.1,0.15,5.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.40,248.0,0.30,249.0,0.30,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.55,111.0,0.15,32.1,0.10,185.9,0.10,5.0,0.05
10398,169.0,161.0,0.35,41.0,0.20,169.0,0.15,111.0,0.10,150.0,0.10
10399,249.0,249.0,0.40,248.0,0.25,251.0,0.20,197.0,0.10,32.1,0.05
10400,150.0,98.9,0.30,239.2,0.25,7.1,0.20,104.1,0.05,150.0,0.05

In [ ]:
Confusion_df20.index = Confusion_df20.index + 1
Confusion_df20
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,394,0,1,2,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
8.1,0,391,1,0,2,1,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
19.9,0,2,388,0,0,0,1,2,0,1,...,0,0,0,0,0,0,3,0,0,0
33.1,0,0,0,396,0,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
42.0,0,1,2,1,391,0,0,0,0,1,...,0,0,0,0,2,0,0,0,0,0
99.9,1,0,0,0,1,392,0,0,0,0,...,0,1,0,2,0,0,0,0,0,0
105.1,0,0,1,0,0,1,392,1,0,1,...,1,0,0,0,0,0,0,0,0,0
112.0,1,1,4,0,1,0,1,381,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,398,1,...,0,0,0,1,0,0,0,0,0,0
130.0,0,0,3,0,1,0,0,0,0,393,...,1,0,0,0,1,0,0,0,0,0
147.0,0,0,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,0,0,0
148.0,0,0,0,1,1,2,1,0,0,1,...,1,0,0,1,1,1,0,0,0,0
151.0,2,0,0,0,0,0,1,2,0,1,...,0,0,3,2,0,0,1,0,0,0
152.0,0,0,3,0,0,0,0,2,0,4,...,0,0,2,0,0,1,1,0,0,0
154.0,1,1,1,3,1,2,3,1,0,4,...,0,0,4,1,1,1,1,0,0,0
155.0,3,2,6,0,0,2,3,2,0,4,...,0,1,5,1,1,1,1,0,0,0
162.0,1,0,2,0,0,1,2,0,0,1,...,380,0,1,2,0,0,1,0,0,0
170.0,4,1,9,1,2,1,1,4,1,8,...,0,341,6,3,2,2,1,0,1,0
186.9,3,4,5,0,2,1,3,4,2,9,...,0,0,342,2,2,0,5,0,0,0
198.0,6,0,7,2,0,6,3,7,1,7,...,1,1,6,331,2,1,2,0,0,0
213.9,1,3,9,5,2,4,3,6,1,8,...,1,1,9,3,310,0,2,0,0,0
218.0,3,0,13,3,2,4,4,7,2,16,...,0,3,1,3,1,316,4,0,0,0
240.2,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,398,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,395,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result20.index = eval_result20.index + 1
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.985000,0.985000,0.015000,0.002593,0.938095,0.985000,0.960976,0.061905,0.015000,0.599699
2,7.1,0.977500,0.977500,0.022500,0.001597,0.960688,0.977500,0.969021,0.039312,0.022500,0.674987
3,18.9,0.970000,0.970000,0.030000,0.006655,0.852747,0.970000,0.907602,0.147253,0.030000,0.665313
4,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.565800
5,41.0,0.977500,0.977500,0.022500,0.001498,0.963054,0.977500,0.970223,0.036946,0.022500,0.869564
6,98.9,0.980000,0.980000,0.020000,0.002494,0.940048,0.980000,0.959608,0.059952,0.020000,0.854734
7,104.1,0.980000,0.980000,0.020000,0.002693,0.935561,0.980000,0.957265,0.064439,0.020000,0.957558
8,111.0,0.952500,0.952500,0.047500,0.003786,0.909308,0.952500,0.930403,0.090692,0.047500,0.841675
9,128.0,0.995000,0.995000,0.005000,0.001099,0.973105,0.995000,0.983931,0.026895,0.005000,1.647487
10,129.0,0.982500,0.982500,0.017500,0.006853,0.850649,0.982500,0.911833,0.149351,0.017500,0.846029
11,146.0,0.970000,0.970000,0.030000,0.002494,0.939467,0.970000,0.954490,0.060533,0.030000,0.557161
12,147.0,0.970000,0.970000,0.030000,0.002892,0.930456,0.970000,0.949816,0.069544,0.030000,0.840124
13,150.0,0.952500,0.952500,0.047500,0.002295,0.943069,0.952500,0.947761,0.056931,0.047500,0.817204
14,151.0,0.952500,0.952500,0.047500,0.001597,0.959698,0.952500,0.956085,0.040302,0.047500,0.663813
15,153.0,0.912500,0.912500,0.087500,0.003786,0.905707,0.912500,0.909091,0.094293,0.087500,0.651942
16,154.0,0.902500,0.902500,0.097500,0.003984,0.900249,0.902500,0.901373,0.099751,0.097500,0.821030
17,161.0,0.950000,0.950000,0.050000,0.000700,0.981912,0.950000,0.965693,0.018088,0.050000,0.653926
18,169.0,0.852500,0.852500,0.147500,0.000700,0.979885,0.852500,0.911765,0.020115,0.147500,0.751687
19,185.9,0.855000,0.855000,0.145000,0.004083,0.892950,0.855000,0.873563,0.107050,0.145000,0.547414
20,197.0,0.827500,0.827500,0.172500,0.002394,0.932394,0.827500,0.876821,0.067606,0.172500,0.896832
21,212.9,0.775000,0.775000,0.225000,0.001298,0.959752,0.775000,0.857538,0.040248,0.225000,0.685991
22,217.0,0.790000,0.790000,0.210000,0.000700,0.978328,0.790000,0.874136,0.021672,0.210000,0.507813
23,239.2,0.995000,0.995000,0.005000,0.002394,0.943128,0.995000,0.968370,0.056872,0.005000,4.920224
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.987500,0.987500,0.012500,0.000100,0.997475,0.987500,0.992462,0.002525,0.012500,0.497460
26,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
27,average,0.941635,0.941635,0.058365,0.002326,0.943240,0.941635,0.940877,0.056760,0.058365,0.859056

In [ ]:
Confusion_df20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn20.csv')
eval_result20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn20.csv', index=False)

## LOAD & APPLY MODEL dTOP30fi

In [ ]:
# test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data30
X_test30 = test_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_test30 = test_data30['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn30_double_sim.pkl', 'rb') as f:
    knn30 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=42)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test30, y_test30)):
    X_test_fold = X_test30.values[test_index]

    probability = knn30.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

42it [00:15,  2.67it/s]

In [ ]:
classes30 = knn30.classes_

y_pred30, data_top_5 = get_predictions(y_prob_all, classes30, 10, np.array(y_test30), le)

Confusion_df30 = pd.DataFrame(confusion_matrix(np.array(y_test30), y_pred30))
Confusion_df30.index, Confusion_df30.columns = le.inverse_transform(classes30), le.inverse_transform(classes30)

eval_result30 = calculate_evaluation_metrics(Confusion_df=Confusion_df30)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.478261,248.0,0.347826,249.0,0.173913,NaN,NaN,NaN,NaN
2,41.0,248.0,0.434783,32.1,0.260870,5.0,0.173913,41.0,0.086957,185.9,0.043478
3,129.0,129.0,0.217391,150.0,0.173913,154.0,0.130435,217.0,0.130435,151.0,0.086957
4,169.0,32.1,0.478261,5.0,0.347826,98.9,0.086957,169.0,0.086957,NaN,NaN
5,161.0,161.0,0.260870,169.0,0.217391,41.0,0.173913,7.1,0.130435,5.0,0.086957
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.434783,248.0,0.304348,249.0,0.260870,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.521739,111.0,0.130435,154.0,0.086957,5.0,0.043478,32.1,0.043478
10398,169.0,161.0,0.304348,41.0,0.173913,169.0,0.130435,111.0,0.086957,146.0,0.086957
10399,249.0,249.0,0.347826,248.0,0.304348,251.0,0.173913,197.0,0.086957,18.9,0.043478
10400,150.0,98.9,0.347826,239.2,0.130435,153.0,0.086957,185.9,0.086957,104.1,0.043478

In [ ]:
Confusion_df30.index = Confusion_df30.index + 1
Confusion_df30
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,1,389,1,1,1,0,0,0,0,0,...,2,0,0,0,1,0,2,0,0,0
19.9,1,1,390,1,0,0,1,1,0,1,...,0,0,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,2,1,391,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,0,1,395,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105.1,0,1,0,0,0,0,386,0,0,3,...,1,0,0,1,0,0,1,0,0,0
112.0,0,2,2,1,0,0,1,381,1,1,...,0,1,2,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,397,1,...,0,0,2,0,0,0,0,0,0,0
130.0,1,0,3,0,0,2,0,0,0,386,...,2,0,0,1,0,0,0,0,0,0
147.0,0,1,1,0,0,0,4,1,1,1,...,1,0,1,1,0,0,0,0,0,0
148.0,2,0,3,0,1,1,2,5,0,3,...,1,1,3,1,0,2,1,0,0,0
151.0,2,2,4,2,1,1,1,1,0,1,...,0,1,4,1,1,0,1,0,0,0
152.0,0,0,2,0,0,1,0,4,1,6,...,2,1,1,0,0,1,2,0,0,0
154.0,3,0,3,2,2,1,2,4,0,5,...,1,0,3,1,1,2,5,0,0,0
155.0,3,0,4,1,0,2,1,3,0,4,...,0,0,3,3,1,0,1,0,0,0
162.0,1,0,3,0,1,1,0,4,0,1,...,375,0,1,2,1,0,2,0,0,0
170.0,1,1,10,0,1,2,3,2,1,10,...,3,340,2,5,2,1,1,0,0,0
186.9,2,4,5,3,3,1,3,2,1,12,...,1,0,332,4,3,0,4,0,0,0
198.0,3,0,9,2,1,6,3,4,0,8,...,4,1,6,329,2,0,3,0,0,0
213.9,2,4,6,2,4,3,2,9,1,8,...,3,0,5,4,315,1,5,0,0,0
218.0,3,1,10,2,2,4,0,9,2,13,...,0,1,2,2,0,319,6,0,0,0
240.2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,398,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,392,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result30.index = eval_result30.index + 1
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.99500,0.99500,0.00500,0.002494,0.940898,0.99500,0.967193,0.059102,0.00500,-3.965838
2,7.1,0.97250,0.97250,0.02750,0.001697,0.958128,0.97250,0.965261,0.041872,0.02750,0.797802
3,18.9,0.97500,0.97500,0.02500,0.006754,0.851528,0.97500,0.909091,0.148472,0.02500,0.963477
4,32.1,0.99000,0.99000,0.01000,0.001797,0.956522,0.99000,0.972973,0.043478,0.01000,0.565800
5,41.0,0.97750,0.97750,0.02250,0.001797,0.955990,0.97750,0.966625,0.044010,0.02250,0.903177
6,98.9,0.98750,0.98750,0.01250,0.002494,0.940476,0.98750,0.963415,0.059524,0.01250,0.657659
7,104.1,0.96500,0.96500,0.03500,0.002394,0.941463,0.96500,0.953086,0.058537,0.03500,0.635498
8,111.0,0.95250,0.95250,0.04750,0.004975,0.883991,0.95250,0.916968,0.116009,0.04750,0.823344
9,128.0,0.99250,0.99250,0.00750,0.000999,0.975430,0.99250,0.983891,0.024570,0.00750,0.489787
10,129.0,0.96500,0.96500,0.03500,0.007937,0.828326,0.96500,0.891455,0.171674,0.03500,0.871667
11,146.0,0.95500,0.95500,0.04500,0.002693,0.933985,0.95500,0.944376,0.066015,0.04500,0.661732
12,147.0,0.92000,0.92000,0.08000,0.004282,0.895377,0.92000,0.907522,0.104623,0.08000,0.718838
13,150.0,0.91750,0.91750,0.08250,0.003885,0.903941,0.91750,0.910670,0.096059,0.08250,0.854886
14,151.0,0.93250,0.93250,0.06750,0.002096,0.946701,0.93250,0.939547,0.053299,0.06750,0.539799
15,153.0,0.87750,0.87750,0.12250,0.004282,0.890863,0.87750,0.884131,0.109137,0.12250,0.737749
16,154.0,0.90250,0.90250,0.09750,0.003289,0.916244,0.90250,0.909320,0.083756,0.09750,0.896733
17,161.0,0.93750,0.93750,0.06250,0.002096,0.946970,0.93750,0.942211,0.053030,0.06250,0.719625
18,169.0,0.85000,0.85000,0.15000,0.000600,0.982659,0.85000,0.911528,0.017341,0.15000,0.700412
19,185.9,0.83000,0.83000,0.17000,0.003587,0.902174,0.83000,0.864583,0.097826,0.17000,0.471665
20,197.0,0.82250,0.82250,0.17750,0.002792,0.921569,0.82250,0.869221,0.078431,0.17750,0.749486
21,212.9,0.78750,0.78750,0.21250,0.001199,0.963303,0.78750,0.866575,0.036697,0.21250,0.611016
22,217.0,0.79750,0.79750,0.20250,0.000700,0.978528,0.79750,0.878788,0.021472,0.20250,0.524119
23,239.2,0.99500,0.99500,0.00500,0.003686,0.914943,0.99500,0.953293,0.085057,0.00500,1.969945
24,248.0,1.00000,1.00000,0.00000,0.000000,1.000000,1.00000,1.000000,0.000000,0.00000,0.000000
25,249.0,0.98000,0.98000,0.02000,0.000000,1.000000,0.98000,0.989899,0.000000,0.02000,0.442078
26,251.0,1.00000,1.00000,0.00000,0.000100,0.997506,1.00000,0.998752,0.002494,0.00000,0.000000
27,average,0.93375,0.93375,0.06625,0.002639,0.935674,0.93375,0.933091,0.064326,0.06625,0.513095

In [ ]:
Confusion_df30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn30.csv')
eval_result30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn30.csv', index=False)

## LOAD & APPLY MODEL dTOP40fi

In [ ]:
# test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data40
X_test40 = test_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_test40 = test_data40['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn40_double_sim.pkl', 'rb') as f:
    knn40 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=42)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test40, y_test40)):
    X_test_fold = X_test40.values[test_index]

    probability = knn40.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

42it [00:15,  2.65it/s]

In [ ]:
classes40 = knn40.classes_

y_pred40, data_top_5 = get_predictions(y_prob_all, classes40, 10, np.array(y_test40), le)

Confusion_df40 = pd.DataFrame(confusion_matrix(np.array(y_test40), y_pred40))
Confusion_df40.index, Confusion_df40.columns = le.inverse_transform(classes40), le.inverse_transform(classes40)

eval_result40 = calculate_evaluation_metrics(Confusion_df=Confusion_df40)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.333333,249.0,0.190476,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,41.0,0.190476,7.1,0.142857,5.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.476190,111.0,0.285714,239.2,0.095238,98.9,0.047619,150.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,111.0,0.095238,150.0,0.095238
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.476190,154.0,0.095238,185.9,0.095238,104.1,0.047619,146.0,0.047619

In [ ]:
Confusion_df40.index = Confusion_df40.index + 1
Confusion_df40
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
8.1,0,390,1,1,1,0,0,0,0,0,...,2,0,0,0,1,0,2,0,0,0
19.9,1,0,385,2,0,1,2,2,0,1,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,395,0,0,0,0,2,0,...,0,0,0,0,0,0,1,0,0,0
42.0,0,2,1,1,391,1,0,2,0,0,...,0,0,0,1,0,0,0,0,0,0
99.9,0,0,1,0,1,395,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
105.1,0,0,1,1,0,0,389,0,0,2,...,1,0,1,0,0,0,0,0,0,0
112.0,1,1,1,1,0,0,1,384,1,1,...,0,0,3,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,398,1,...,0,0,0,1,0,0,0,0,0,0
130.0,2,1,4,1,0,0,0,0,0,388,...,1,0,0,1,0,0,0,0,0,0
147.0,0,2,0,0,0,2,2,0,1,1,...,0,0,0,1,0,0,0,0,0,0
148.0,1,0,1,0,1,1,0,2,0,1,...,0,1,1,1,0,1,0,0,0,0
151.0,3,1,1,1,0,0,1,1,0,1,...,0,0,1,2,0,0,1,0,0,0
152.0,1,2,2,1,0,1,0,5,1,4,...,0,1,2,2,0,1,1,0,0,0
154.0,3,0,2,2,1,0,0,2,1,5,...,0,0,3,2,0,2,3,0,0,0
155.0,2,0,5,1,0,0,4,2,0,6,...,0,1,5,2,2,0,2,0,0,0
162.0,1,0,3,0,1,0,1,2,0,1,...,381,0,1,1,1,0,1,0,0,0
170.0,3,1,9,0,2,2,3,2,1,7,...,2,344,2,5,2,0,0,0,1,0
186.9,1,3,5,1,1,0,3,4,4,8,...,1,0,344,4,2,0,1,0,0,0
198.0,1,0,7,1,0,3,3,4,0,8,...,3,2,6,343,1,0,3,0,0,0
213.9,2,5,5,2,2,3,4,6,1,9,...,0,1,6,3,319,1,4,0,0,0
218.0,3,2,10,2,2,4,0,1,4,14,...,2,2,5,3,0,318,4,0,0,0
240.2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,399,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result40.index = eval_result40.index + 1
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.992500,0.992500,0.007500,0.002494,0.940758,0.992500,0.965937,0.059242,0.007500,-0.530944
2,7.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.627447
3,18.9,0.962500,0.962500,0.037500,0.005865,0.867117,0.962500,0.912322,0.132883,0.037500,0.845830
4,32.1,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,0.553497
5,41.0,0.977500,0.977500,0.022500,0.001199,0.970223,0.977500,0.973848,0.029777,0.022500,1.005171
6,98.9,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,1.011476
7,104.1,0.972500,0.972500,0.027500,0.002394,0.941889,0.972500,0.956950,0.058111,0.027500,0.736260
8,111.0,0.960000,0.960000,0.040000,0.003488,0.916468,0.960000,0.937729,0.083532,0.040000,0.768734
9,128.0,0.995000,0.995000,0.005000,0.001597,0.961353,0.995000,0.977887,0.038647,0.005000,1.647487
10,129.0,0.970000,0.970000,0.030000,0.006951,0.847162,0.970000,0.904429,0.152838,0.030000,0.986254
11,146.0,0.967500,0.967500,0.032500,0.002991,0.928058,0.967500,0.947368,0.071942,0.032500,0.891260
12,147.0,0.955000,0.955000,0.045000,0.003190,0.922705,0.955000,0.938575,0.077295,0.045000,0.748493
13,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,1.182753
14,151.0,0.932500,0.932500,0.067500,0.001797,0.953964,0.932500,0.943110,0.046036,0.067500,0.666252
15,153.0,0.910000,0.910000,0.090000,0.002693,0.930946,0.910000,0.920354,0.069054,0.090000,0.765841
16,154.0,0.897500,0.897500,0.102500,0.002892,0.925258,0.897500,0.911168,0.074742,0.102500,0.676776
17,161.0,0.952500,0.952500,0.047500,0.001298,0.967005,0.952500,0.959698,0.032995,0.047500,0.894918
18,169.0,0.860000,0.860000,0.140000,0.000899,0.974504,0.860000,0.913679,0.025496,0.140000,0.770421
19,185.9,0.860000,0.860000,0.140000,0.003686,0.902887,0.860000,0.880922,0.097113,0.140000,0.582242
20,197.0,0.857500,0.857500,0.142500,0.003190,0.914667,0.857500,0.885161,0.085333,0.142500,0.635935
21,212.9,0.797500,0.797500,0.202500,0.000899,0.972561,0.797500,0.876374,0.027439,0.202500,0.587241
22,217.0,0.795000,0.795000,0.205000,0.000600,0.981481,0.795000,0.878453,0.018519,0.205000,0.487445
23,239.2,0.997500,0.997500,0.002500,0.002593,0.938824,0.997500,0.967273,0.061176,0.002500,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.942212,0.942212,0.057788,0.002304,0.943651,0.942212,0.941587,0.056349,0.057788,0.653701

In [ ]:
Confusion_df40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn40.csv')
eval_result40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn40.csv', index=False)

## LOAD & APPLY MODEL dTOP50fi

In [ ]:
# test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data50
X_test50 = test_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_test50 = test_data50['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn50_double_sim.pkl', 'rb') as f:
    knn50 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=70)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test50, y_test50)):
    X_test_fold = X_test50.values[test_index]

    probability = knn50.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

70it [00:16,  4.35it/s]

In [ ]:
classes50 = knn50.classes_

y_pred50, data_top_5 = get_predictions(y_prob_all, classes50, 10, np.array(y_test50), le)

Confusion_df50 = pd.DataFrame(confusion_matrix(np.array(y_test50), y_pred50))
Confusion_df50.index, Confusion_df50.columns = le.inverse_transform(classes50), le.inverse_transform(classes50)

eval_result50 = calculate_evaluation_metrics(Confusion_df=Confusion_df50)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,41.0,0.190476,7.1,0.142857,5.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.333333,111.0,0.285714,239.2,0.142857,5.0,0.047619,98.9,0.047619
10398,169.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,111.0,0.095238,150.0,0.095238
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.476190,154.0,0.095238,185.9,0.095238,18.9,0.047619,146.0,0.047619

In [ ]:
eval_result50.index = eval_result50.index + 1
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.992500,0.992500,0.007500,0.002195,0.947494,0.992500,0.969475,0.052506,0.007500,-0.530944
2,7.1,0.975000,0.975000,0.025000,0.001797,0.955882,0.975000,0.965347,0.044118,0.025000,0.695736
3,18.9,0.960000,0.960000,0.040000,0.005964,0.864865,0.960000,0.909953,0.135135,0.040000,0.759175
4,32.1,0.987500,0.987500,0.012500,0.002096,0.949519,0.987500,0.968137,0.050481,0.012500,0.553497
5,41.0,0.980000,0.980000,0.020000,0.000999,0.975124,0.980000,0.977556,0.024876,0.020000,0.958271
6,98.9,0.987500,0.987500,0.012500,0.001498,0.963415,0.987500,0.975309,0.036585,0.012500,1.481441
7,104.1,0.967500,0.967500,0.032500,0.002693,0.934783,0.967500,0.950860,0.065217,0.032500,0.906417
8,111.0,0.965000,0.965000,0.035000,0.003090,0.925659,0.965000,0.944920,0.074341,0.035000,0.795505
9,128.0,0.987500,0.987500,0.012500,0.001398,0.965770,0.987500,0.976514,0.034230,0.012500,0.811297
10,129.0,0.965000,0.965000,0.035000,0.007050,0.844639,0.965000,0.900817,0.155361,0.035000,0.853958
11,146.0,0.970000,0.970000,0.030000,0.002991,0.928230,0.970000,0.948655,0.071770,0.030000,0.924453
12,147.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.602597
13,150.0,0.950000,0.950000,0.050000,0.003289,0.920097,0.950000,0.934809,0.079903,0.050000,0.780970
14,151.0,0.942500,0.942500,0.057500,0.001398,0.964194,0.942500,0.953224,0.035806,0.057500,0.908734
15,153.0,0.912500,0.912500,0.087500,0.002593,0.933504,0.912500,0.922882,0.066496,0.087500,0.756572
16,154.0,0.912500,0.912500,0.087500,0.002991,0.924051,0.912500,0.918239,0.075949,0.087500,0.606533
17,161.0,0.955000,0.955000,0.045000,0.001099,0.972010,0.955000,0.963430,0.027990,0.045000,0.868032
18,169.0,0.860000,0.860000,0.140000,0.000500,0.985673,0.860000,0.918558,0.014327,0.140000,0.743641
19,185.9,0.870000,0.870000,0.130000,0.003289,0.913386,0.870000,0.891165,0.086614,0.130000,0.719614
20,197.0,0.850000,0.850000,0.150000,0.003190,0.913978,0.850000,0.880829,0.086022,0.150000,0.583342
21,212.9,0.805000,0.805000,0.195000,0.000999,0.969880,0.805000,0.879781,0.030120,0.195000,0.583171
22,217.0,0.820000,0.820000,0.180000,0.000899,0.973294,0.820000,0.890095,0.026706,0.180000,0.474145
23,239.2,0.995000,0.995000,0.005000,0.002195,0.947619,0.995000,0.970732,0.052381,0.005000,2.309168
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.944231,0.944231,0.055769,0.002223,0.945635,0.944231,0.943752,0.054365,0.055769,0.715414

In [ ]:
Confusion_df50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn50.csv')
eval_result50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn50.csv', index=False)

## LOAD & APPLY MODEL dTOP60fi

In [ ]:
# test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data60
X_test60 = test_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_test60 = test_data60['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn60_double_sim.pkl', 'rb') as f:
    knn60 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=100)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test60, y_test60)):
    X_test_fold = X_test60.values[test_index]

    probability = knn60.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

100it [00:16,  6.13it/s]

In [ ]:
classes60 = knn60.classes_

y_pred60, data_top_5 = get_predictions(y_prob_all, classes60, 10, np.array(y_test60), le)

Confusion_df60 = pd.DataFrame(confusion_matrix(np.array(y_test60), y_pred60))
Confusion_df60.index, Confusion_df60.columns = le.inverse_transform(classes60), le.inverse_transform(classes60)

eval_result60 = calculate_evaluation_metrics(Confusion_df=Confusion_df60)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,41.0,0.238095,169.0,0.238095,161.0,0.190476,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.333333,111.0,0.285714,239.2,0.142857,5.0,0.047619,129.0,0.047619
10398,169.0,161.0,0.285714,41.0,0.190476,111.0,0.095238,146.0,0.095238,150.0,0.095238
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.428571,150.0,0.095238,151.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df60.index = Confusion_df60.index + 1
Confusion_df60
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
8.1,0,390,1,1,1,0,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,384,2,0,1,2,2,0,0,...,0,1,0,1,0,0,2,0,0,0
33.1,0,0,0,395,0,0,0,0,2,0,...,0,0,0,0,0,0,1,0,0,0
42.0,0,3,0,1,392,0,0,2,0,0,...,0,0,0,1,0,0,0,0,0,0
99.9,1,0,0,0,0,394,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
105.1,1,0,1,0,0,0,387,2,0,3,...,0,0,1,1,0,0,0,0,0,0
112.0,0,1,1,1,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,397,1,...,0,0,0,0,0,1,0,0,0,0
130.0,1,1,6,1,0,0,0,0,0,386,...,2,0,0,1,0,0,1,0,0,0
147.0,0,1,1,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,1,0,1,0,0,5,0,1,...,0,0,0,1,0,1,1,0,0,0
151.0,1,0,0,1,0,0,2,1,0,2,...,0,0,2,1,1,0,1,0,0,0
152.0,1,1,2,1,0,1,0,3,1,3,...,1,0,1,0,0,2,1,0,0,0
154.0,1,1,3,1,1,1,0,3,1,5,...,0,0,2,3,1,3,3,0,0,0
155.0,0,0,5,0,1,1,3,3,0,5,...,0,2,5,1,2,0,0,0,0,0
162.0,0,0,1,0,2,0,0,2,0,1,...,381,1,2,1,1,0,2,0,0,0
170.0,3,2,8,2,1,1,3,2,2,11,...,0,343,2,4,3,0,0,0,1,0
186.9,3,3,7,0,2,0,2,3,3,8,...,0,0,345,3,2,0,1,0,0,0
198.0,3,1,6,1,0,4,4,1,0,7,...,3,2,6,346,1,0,1,0,0,0
213.9,2,4,6,3,2,4,3,4,0,8,...,2,2,7,3,315,0,7,0,0,0
218.0,1,2,11,1,2,6,0,0,3,14,...,1,1,5,3,0,324,6,0,0,0
240.2,0,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result60.index = eval_result60.index + 1
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.992500,0.992500,0.007500,0.001896,0.954327,0.992500,0.973039,0.045673,0.007500,-0.530944
2,7.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.704070
3,18.9,0.960000,0.960000,0.040000,0.005964,0.864865,0.960000,0.909953,0.135135,0.040000,0.844398
4,32.1,0.987500,0.987500,0.012500,0.001797,0.956416,0.987500,0.971710,0.043584,0.012500,0.553497
5,41.0,0.980000,0.980000,0.020000,0.001298,0.967901,0.980000,0.973913,0.032099,0.020000,0.969523
6,98.9,0.985000,0.985000,0.015000,0.001896,0.953995,0.985000,0.969250,0.046005,0.015000,0.871182
7,104.1,0.967500,0.967500,0.032500,0.002096,0.948529,0.967500,0.957921,0.051471,0.032500,0.743603
8,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.808743
9,128.0,0.992500,0.992500,0.007500,0.001398,0.965937,0.992500,0.979038,0.034063,0.007500,0.807951
10,129.0,0.965000,0.965000,0.035000,0.007050,0.844639,0.965000,0.900817,0.155361,0.035000,0.818519
11,146.0,0.980000,0.980000,0.020000,0.003090,0.926714,0.980000,0.952612,0.073286,0.020000,0.633219
12,147.0,0.962500,0.962500,0.037500,0.003190,0.923261,0.962500,0.942472,0.076739,0.037500,0.554034
13,150.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.732741
14,151.0,0.947500,0.947500,0.052500,0.001298,0.966837,0.947500,0.957071,0.033163,0.052500,0.824908
15,153.0,0.902500,0.902500,0.097500,0.002593,0.932817,0.902500,0.917408,0.067183,0.097500,0.673242
16,154.0,0.907500,0.907500,0.092500,0.002991,0.923664,0.907500,0.915511,0.076336,0.092500,0.705746
17,161.0,0.952500,0.952500,0.047500,0.001199,0.969466,0.952500,0.960908,0.030534,0.047500,0.754308
18,169.0,0.857500,0.857500,0.142500,0.000999,0.971671,0.857500,0.911023,0.028329,0.142500,0.516916
19,185.9,0.862500,0.862500,0.137500,0.003587,0.905512,0.862500,0.883483,0.094488,0.137500,0.667204
20,197.0,0.865000,0.865000,0.135000,0.002693,0.927614,0.865000,0.895213,0.072386,0.135000,0.684106
21,212.9,0.787500,0.787500,0.212500,0.001099,0.966258,0.787500,0.867769,0.033742,0.212500,0.634455
22,217.0,0.810000,0.810000,0.190000,0.000799,0.975904,0.810000,0.885246,0.024096,0.190000,0.509734
23,239.2,0.990000,0.990000,0.010000,0.002892,0.931765,0.990000,0.960000,0.068235,0.010000,1.030794
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.476642
26,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
27,average,0.943462,0.943462,0.056538,0.002254,0.944850,0.943462,0.942878,0.055150,0.056538,0.614946

In [ ]:
Confusion_df60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn60.csv')
eval_result60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn60.csv', index=False)

## LOAD & APPLY MODEL dTOP70fi

In [ ]:
# test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data70
X_test70 = test_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_test70 = test_data70['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn70_double_sim.pkl', 'rb') as f:
    knn70 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=250)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test70, y_test70)):
    X_test_fold = X_test70.values[test_index]

    probability = knn70.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

250it [00:16, 14.71it/s]

In [ ]:
classes70 = knn70.classes_

y_pred70, data_top_5 = get_predictions(y_prob_all, classes70, 10, np.array(y_test70), le)

Confusion_df70 = pd.DataFrame(confusion_matrix(np.array(y_test70), y_pred70))
Confusion_df70.index, Confusion_df70.columns = le.inverse_transform(classes70), le.inverse_transform(classes70)

eval_result70 = calculate_evaluation_metrics(Confusion_df=Confusion_df70)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
2,41.0,248.0,0.523810,32.1,0.190476,5.0,0.142857,41.0,0.095238,18.9,0.047619
3,129.0,150.0,0.190476,129.0,0.142857,151.0,0.142857,217.0,0.142857,153.0,0.095238
4,169.0,5.0,0.428571,32.1,0.380952,98.9,0.142857,169.0,0.047619,NaN,NaN
5,161.0,161.0,0.285714,41.0,0.190476,169.0,0.190476,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.238095,239.2,0.190476,111.0,0.142857,5.0,0.095238,32.1,0.095238
10398,169.0,161.0,0.285714,41.0,0.238095,150.0,0.142857,169.0,0.142857,7.1,0.095238
10399,249.0,249.0,0.285714,251.0,0.285714,248.0,0.238095,18.9,0.095238,169.0,0.047619
10400,150.0,98.9,0.380952,239.2,0.142857,150.0,0.095238,154.0,0.095238,185.9,0.095238

In [ ]:
Confusion_df70.index = Confusion_df70.index + 1
Confusion_df70
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,392,0,0,0,0,1,1,0,0,0,...,2,0,1,0,0,0,2,0,0,0
8.1,0,391,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,1
19.9,1,0,387,0,1,0,1,0,0,2,...,1,1,3,0,0,0,3,0,0,0
33.1,0,0,1,395,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
42.0,0,0,1,0,394,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,0
99.9,0,1,1,0,2,387,0,1,0,0,...,0,0,0,0,1,0,3,0,0,0
105.1,0,0,1,0,1,0,392,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112.0,0,0,0,2,1,2,1,387,0,1,...,0,0,1,0,0,2,0,0,0,0
129.0,0,0,0,0,0,0,0,0,397,1,...,0,0,0,0,0,1,1,0,0,0
130.0,2,1,1,0,1,1,0,0,0,388,...,1,0,0,0,0,1,0,0,0,0
147.0,0,2,1,0,0,1,1,0,1,3,...,0,0,0,0,1,1,1,0,0,0
148.0,0,0,1,0,0,0,0,2,0,3,...,1,0,0,1,1,0,1,0,0,0
151.0,0,0,1,1,0,1,2,2,2,3,...,3,0,1,2,0,2,1,0,0,0
152.0,0,3,2,1,2,0,0,3,2,1,...,2,0,2,0,0,1,0,0,0,0
154.0,4,0,1,0,1,3,2,3,1,7,...,0,0,5,3,1,2,0,0,0,0
155.0,2,1,0,1,0,5,4,3,0,5,...,1,1,2,0,0,0,1,0,0,0
162.0,0,1,1,0,2,1,0,1,0,3,...,383,0,1,1,1,1,1,0,0,0
170.0,2,1,7,1,0,0,3,2,1,7,...,1,346,2,4,2,0,3,0,1,1
186.9,0,1,10,0,4,1,2,3,0,6,...,0,0,346,3,1,1,1,0,0,0
198.0,1,0,12,1,0,5,3,2,1,6,...,2,0,1,350,1,0,3,0,0,0
213.9,0,0,11,3,3,6,0,2,0,9,...,1,1,5,2,325,2,5,0,0,0
218.0,3,2,13,3,1,7,1,1,5,16,...,0,1,4,1,0,304,9,0,0,0
240.2,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,398,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,392,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result70.index = eval_result70.index + 1
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.980000,0.980000,0.020000,0.001498,0.963145,0.980000,0.971499,0.036855,0.020000,0.399327
2,7.1,0.977500,0.977500,0.022500,0.001298,0.967822,0.977500,0.972637,0.032178,0.022500,0.731309
3,18.9,0.967500,0.967500,0.032500,0.006557,0.854305,0.967500,0.907386,0.145695,0.032500,0.576582
4,32.1,0.987500,0.987500,0.012500,0.001398,0.965770,0.987500,0.976514,0.034230,0.012500,0.941369
5,41.0,0.985000,0.985000,0.015000,0.001896,0.953995,0.985000,0.969250,0.046005,0.015000,0.459392
6,98.9,0.967500,0.967500,0.032500,0.003488,0.917062,0.967500,0.941606,0.082938,0.032500,0.605607
7,104.1,0.980000,0.980000,0.020000,0.002195,0.946860,0.980000,0.963145,0.053140,0.020000,0.670553
8,111.0,0.967500,0.967500,0.032500,0.002593,0.937046,0.967500,0.952030,0.062954,0.032500,0.799592
9,128.0,0.992500,0.992500,0.007500,0.001298,0.968293,0.992500,0.980247,0.031707,0.007500,0.760682
10,129.0,0.970000,0.970000,0.030000,0.007346,0.839827,0.970000,0.900232,0.160173,0.030000,1.251424
11,146.0,0.955000,0.955000,0.045000,0.002494,0.938575,0.955000,0.946716,0.061425,0.045000,0.800908
12,147.0,0.952500,0.952500,0.047500,0.003090,0.924757,0.952500,0.938424,0.075243,0.047500,0.634781
13,150.0,0.935000,0.935000,0.065000,0.003885,0.905569,0.935000,0.920049,0.094431,0.065000,0.709578
14,151.0,0.940000,0.940000,0.060000,0.001896,0.951899,0.940000,0.945912,0.048101,0.060000,0.931151
15,153.0,0.895000,0.895000,0.105000,0.002593,0.932292,0.895000,0.913265,0.067708,0.105000,0.620185
16,154.0,0.907500,0.907500,0.092500,0.004182,0.896296,0.907500,0.901863,0.103704,0.092500,0.714007
17,161.0,0.957500,0.957500,0.042500,0.001597,0.959900,0.957500,0.958698,0.040100,0.042500,0.740225
18,169.0,0.865000,0.865000,0.135000,0.000400,0.988571,0.865000,0.922667,0.011429,0.135000,0.713436
19,185.9,0.865000,0.865000,0.135000,0.002892,0.922667,0.865000,0.892903,0.077333,0.135000,0.764706
20,197.0,0.875000,0.875000,0.125000,0.001896,0.948509,0.875000,0.910273,0.051491,0.125000,0.789113
21,212.9,0.812500,0.812500,0.187500,0.000899,0.973054,0.812500,0.885559,0.026946,0.187500,0.758464
22,217.0,0.760000,0.760000,0.240000,0.001398,0.955975,0.760000,0.846797,0.044025,0.240000,0.508982
23,239.2,0.995000,0.995000,0.005000,0.003885,0.910755,0.995000,0.951016,0.089245,0.005000,4.344157
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.980000,0.980000,0.020000,0.000100,0.997455,0.980000,0.988651,0.002545,0.020000,0.434680
26,251.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
27,average,0.941154,0.941154,0.058846,0.002345,0.942901,0.941154,0.940571,0.057099,0.058846,0.794623

In [ ]:
Confusion_df70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn70.csv')
eval_result70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn70.csv', index=False)

## LOAD & APPLY MODEL dTOP80fi

In [ ]:
# test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data80
X_test80 = test_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_test80 = test_data80['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn80_double_sim.pkl', 'rb') as f:
    knn80 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=300)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test80, y_test80)):
    X_test_fold = X_test80.values[test_index]

    probability = knn80.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

300it [00:17, 17.32it/s]

In [ ]:
classes80 = knn80.classes_

y_pred80, data_top_5 = get_predictions(y_prob_all, classes80, 10, np.array(y_test80), le)

Confusion_df80 = pd.DataFrame(confusion_matrix(np.array(y_test80), y_pred80))
Confusion_df80.index, Confusion_df80.columns = le.inverse_transform(classes80), le.inverse_transform(classes80)

eval_result80 = calculate_evaluation_metrics(Confusion_df=Confusion_df80)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.50,248.0,0.25,249.0,0.25,NaN,NaN,NaN,NaN
2,41.0,248.0,0.50,5.0,0.20,32.1,0.20,41.0,0.1,NaN,NaN
3,129.0,129.0,0.25,150.0,0.20,151.0,0.10,154.0,0.1,217.0,0.10
4,169.0,5.0,0.40,32.1,0.40,98.9,0.10,169.0,0.1,NaN,NaN
5,161.0,161.0,0.30,41.0,0.20,169.0,0.15,5.0,0.1,7.1,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.40,248.0,0.30,249.0,0.30,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.30,153.0,0.20,111.0,0.15,154.0,0.1,5.0,0.05
10398,169.0,161.0,0.35,41.0,0.25,169.0,0.15,150.0,0.1,7.1,0.05
10399,249.0,249.0,0.35,248.0,0.25,251.0,0.20,197.0,0.1,18.9,0.05
10400,150.0,98.9,0.30,146.0,0.15,185.9,0.10,217.0,0.1,18.9,0.05

In [ ]:
Confusion_df80.index = Confusion_df80.index + 1
Confusion_df80
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,2,0,385,0,0,1,2,1,0,2,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,0,392,0,1,0,1,...,1,0,0,1,0,0,0,0,0,0
105.1,1,0,0,0,0,0,389,2,0,4,...,0,0,0,0,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,384,1,1,...,0,0,2,2,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,1,398,0,...,0,0,1,0,0,0,0,0,0,0
130.0,0,1,5,1,2,0,0,0,0,388,...,0,1,0,0,0,0,1,0,0,0
147.0,0,2,0,0,0,0,1,0,1,0,...,0,1,1,1,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,2,0,2,...,1,1,0,0,0,1,0,0,0,0
151.0,1,0,0,1,1,1,2,0,0,1,...,0,0,1,1,0,0,1,0,0,0
152.0,2,2,3,1,0,1,0,2,0,2,...,1,0,4,0,1,1,1,0,0,0
154.0,3,0,2,1,0,0,2,2,2,3,...,0,0,2,3,1,2,4,0,0,0
155.0,1,0,6,2,0,2,2,3,0,5,...,0,1,4,1,2,0,0,0,0,0
162.0,1,0,2,1,0,0,0,2,0,2,...,379,1,3,1,1,2,1,0,0,0
170.0,2,1,9,1,0,1,4,0,1,7,...,1,349,2,4,3,1,0,0,1,0
186.9,2,3,6,2,1,1,5,2,3,9,...,2,0,341,2,3,0,1,0,0,0
198.0,2,2,8,1,4,4,3,3,0,9,...,0,2,5,338,1,0,2,0,0,0
213.9,1,5,7,4,2,3,2,5,0,8,...,0,1,8,2,318,0,6,0,0,0
218.0,2,2,10,2,2,5,0,1,3,11,...,1,2,6,4,0,324,6,0,0,0
240.2,0,0,0,1,0,0,0,0,1,1,...,0,0,1,0,0,0,395,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result80.index = eval_result80.index + 1
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001996,0.952153,0.995000,0.973105,0.047847,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002096,0.949029,0.977500,0.963054,0.050971,0.022500,0.680443
3,18.9,0.962500,0.962500,0.037500,0.006261,0.859375,0.962500,0.908019,0.140625,0.037500,0.998066
4,32.1,0.990000,0.990000,0.010000,0.002195,0.947368,0.990000,0.968215,0.052632,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001199,0.970297,0.980000,0.975124,0.029703,0.020000,1.101860
6,98.9,0.980000,0.980000,0.020000,0.002096,0.949153,0.980000,0.964330,0.050847,0.020000,0.695463
7,104.1,0.972500,0.972500,0.027500,0.002394,0.941889,0.972500,0.956950,0.058111,0.027500,0.594823
8,111.0,0.960000,0.960000,0.040000,0.002792,0.932039,0.960000,0.945813,0.067961,0.040000,0.713443
9,128.0,0.995000,0.995000,0.005000,0.001199,0.970732,0.995000,0.982716,0.029268,0.005000,1.877443
10,129.0,0.970000,0.970000,0.030000,0.006853,0.849015,0.970000,0.905484,0.150985,0.030000,0.828617
11,146.0,0.972500,0.972500,0.027500,0.002693,0.935096,0.972500,0.953431,0.064904,0.027500,0.885249
12,147.0,0.967500,0.967500,0.032500,0.002892,0.930288,0.967500,0.948529,0.069712,0.032500,0.597626
13,150.0,0.965000,0.965000,0.035000,0.002892,0.930120,0.965000,0.947239,0.069880,0.035000,0.881925
14,151.0,0.942500,0.942500,0.057500,0.001896,0.952020,0.942500,0.947236,0.047980,0.057500,0.836667
15,153.0,0.910000,0.910000,0.090000,0.002494,0.935733,0.910000,0.922687,0.064267,0.090000,0.814605
16,154.0,0.910000,0.910000,0.090000,0.002892,0.926209,0.910000,0.918033,0.073791,0.090000,0.762807
17,161.0,0.947500,0.947500,0.052500,0.000899,0.976804,0.947500,0.961929,0.023196,0.052500,0.767246
18,169.0,0.872500,0.872500,0.127500,0.001099,0.969444,0.872500,0.918421,0.030556,0.127500,0.765681
19,185.9,0.852500,0.852500,0.147500,0.003984,0.895013,0.852500,0.873239,0.104987,0.147500,0.552535
20,197.0,0.845000,0.845000,0.155000,0.002295,0.936288,0.845000,0.888305,0.063712,0.155000,0.638644
21,212.9,0.795000,0.795000,0.205000,0.001199,0.963636,0.795000,0.871233,0.036364,0.205000,0.661025
22,217.0,0.810000,0.810000,0.190000,0.000700,0.978852,0.810000,0.886457,0.021148,0.190000,0.620128
23,239.2,0.987500,0.987500,0.012500,0.002892,0.931604,0.987500,0.958738,0.068396,0.012500,0.980094
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.547783
26,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
27,average,0.944038,0.944038,0.055962,0.002231,0.945370,0.944038,0.943442,0.054630,0.055962,0.548124

In [ ]:
Confusion_df80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn80.csv')
eval_result80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn80.csv', index=False)

## LOAD & APPLY MODEL dTOP90fi

In [ ]:
# test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data90
X_test90 = test_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_test90 = test_data90['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn90_double_sim.pkl', 'rb') as f:
    knn90 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=500)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test90, y_test90)):
    X_test_fold = X_test90.values[test_index]

    probability = knn90.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

500it [00:18, 26.70it/s]

In [ ]:
classes90 = knn90.classes_

y_pred90, data_top_5 = get_predictions(y_prob_all, classes90, 10, np.array(y_test90), le)

Confusion_df90 = pd.DataFrame(confusion_matrix(np.array(y_test90), y_pred90))
Confusion_df90.index, Confusion_df90.columns = le.inverse_transform(classes90), le.inverse_transform(classes90)

eval_result90 = calculate_evaluation_metrics(Confusion_df=Confusion_df90)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.333333,248.0,0.238095,251.0,0.238095,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df90.index = Confusion_df90.index + 1
Confusion_df90
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,0,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
130.0,1,1,6,1,1,0,0,0,0,388,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,0,1,0,0,0,0
151.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,2,0,0,0,4,0,4,...,1,1,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,1,3,1,6,...,0,0,1,4,1,3,3,0,0,0
155.0,1,1,5,2,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
162.0,0,2,1,0,2,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,10,...,1,343,2,4,3,0,1,0,1,0
186.9,1,3,8,0,1,2,2,6,5,12,...,1,0,335,2,3,0,2,0,0,0
198.0,2,3,10,2,1,3,6,4,0,8,...,1,1,5,332,1,2,2,0,0,0
213.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,317,0,5,0,0,0
218.0,2,4,11,3,1,6,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result90.index = eval_result90.index + 1
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001498,0.963680,0.995000,0.979090,0.036320,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
3,18.9,0.965000,0.965000,0.035000,0.007247,0.840959,0.965000,0.898719,0.159041,0.035000,0.843988
4,32.1,0.990000,0.990000,0.010000,0.002096,0.949640,0.990000,0.969400,0.050360,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
6,98.9,0.982500,0.982500,0.017500,0.002295,0.944712,0.982500,0.963235,0.055288,0.017500,0.743315
7,104.1,0.975000,0.975000,0.025000,0.002195,0.946602,0.975000,0.960591,0.053398,0.025000,0.495457
8,111.0,0.962500,0.962500,0.037500,0.003388,0.918854,0.962500,0.940171,0.081146,0.037500,0.831063
9,128.0,0.995000,0.995000,0.005000,0.001398,0.966019,0.995000,0.980296,0.033981,0.005000,1.156444
10,129.0,0.970000,0.970000,0.030000,0.008920,0.811715,0.970000,0.883827,0.188285,0.030000,0.830807
11,146.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.754017
12,147.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.581016
13,150.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.908066
14,151.0,0.935000,0.935000,0.065000,0.001697,0.956522,0.935000,0.945638,0.043478,0.065000,0.743932
15,153.0,0.897500,0.897500,0.102500,0.002195,0.942257,0.897500,0.919334,0.057743,0.102500,0.622271
16,154.0,0.892500,0.892500,0.107500,0.003190,0.917738,0.892500,0.904943,0.082262,0.107500,0.597606
17,161.0,0.937500,0.937500,0.062500,0.000799,0.979112,0.937500,0.957854,0.020888,0.062500,0.747673
18,169.0,0.857500,0.857500,0.142500,0.001099,0.968927,0.857500,0.909814,0.031073,0.142500,0.618824
19,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.491757
20,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.764709
21,212.9,0.792500,0.792500,0.207500,0.001199,0.963526,0.792500,0.869684,0.036474,0.207500,0.751471
22,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472451
23,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.938942,0.938942,0.061058,0.002432,0.940993,0.938942,0.938308,0.059007,0.061058,0.482145

In [ ]:
Confusion_df90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn90.csv')
eval_result90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn90.csv', index=False)

## LOAD & APPLY MODEL dTOP100fi

In [ ]:
# test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data100
X_test100 = test_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_test100 = test_data100['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn100_double_sim.pkl', 'rb') as f:
    knn100 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=350)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test100, y_test100)):
    X_test_fold = X_test100.values[test_index]

    probability = knn100.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

350it [00:18, 19.19it/s]

In [ ]:
classes100 = knn100.classes_

y_pred100, data_top_5 = get_predictions(y_prob_all, classes100, 10, np.array(y_test100), le)

Confusion_df100 = pd.DataFrame(confusion_matrix(np.array(y_test100), y_pred100))
Confusion_df100.index, Confusion_df100.columns = le.inverse_transform(classes100), le.inverse_transform(classes100)

eval_result100 = calculate_evaluation_metrics(Confusion_df=Confusion_df100)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.333333,248.0,0.238095,251.0,0.238095,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df100.index = Confusion_df100.index + 1
Confusion_df100
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,0,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
130.0,1,1,6,1,1,0,0,0,0,388,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,0,1,0,0,0,0
151.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,2,0,0,0,4,0,4,...,1,1,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,1,3,1,6,...,0,0,1,4,1,3,3,0,0,0
155.0,1,1,5,2,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
162.0,0,2,1,0,2,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,10,...,1,343,2,4,3,0,1,0,1,0
186.9,1,3,8,0,1,2,2,6,5,12,...,1,0,335,2,3,0,2,0,0,0
198.0,2,3,10,2,1,3,6,4,0,8,...,1,1,5,332,1,2,2,0,0,0
213.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,317,0,5,0,0,0
218.0,2,4,11,3,1,6,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result100.index = eval_result100.index + 1
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001498,0.963680,0.995000,0.979090,0.036320,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
3,18.9,0.965000,0.965000,0.035000,0.007247,0.840959,0.965000,0.898719,0.159041,0.035000,0.843988
4,32.1,0.990000,0.990000,0.010000,0.002096,0.949640,0.990000,0.969400,0.050360,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
6,98.9,0.982500,0.982500,0.017500,0.002295,0.944712,0.982500,0.963235,0.055288,0.017500,0.743315
7,104.1,0.975000,0.975000,0.025000,0.002195,0.946602,0.975000,0.960591,0.053398,0.025000,0.495457
8,111.0,0.962500,0.962500,0.037500,0.003388,0.918854,0.962500,0.940171,0.081146,0.037500,0.831063
9,128.0,0.995000,0.995000,0.005000,0.001398,0.966019,0.995000,0.980296,0.033981,0.005000,1.156444
10,129.0,0.970000,0.970000,0.030000,0.008920,0.811715,0.970000,0.883827,0.188285,0.030000,0.830807
11,146.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.754017
12,147.0,0.955000,0.955000,0.045000,0.003388,0.918269,0.955000,0.936275,0.081731,0.045000,0.581016
13,150.0,0.957500,0.957500,0.042500,0.003388,0.918465,0.957500,0.937576,0.081535,0.042500,0.908066
14,151.0,0.935000,0.935000,0.065000,0.001697,0.956522,0.935000,0.945638,0.043478,0.065000,0.743932
15,153.0,0.897500,0.897500,0.102500,0.002195,0.942257,0.897500,0.919334,0.057743,0.102500,0.622271
16,154.0,0.892500,0.892500,0.107500,0.003190,0.917738,0.892500,0.904943,0.082262,0.107500,0.597606
17,161.0,0.937500,0.937500,0.062500,0.000799,0.979112,0.937500,0.957854,0.020888,0.062500,0.747673
18,169.0,0.857500,0.857500,0.142500,0.001099,0.968927,0.857500,0.909814,0.031073,0.142500,0.618824
19,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.491757
20,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.764709
21,212.9,0.792500,0.792500,0.207500,0.001199,0.963526,0.792500,0.869684,0.036474,0.207500,0.751471
22,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472451
23,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.938942,0.938942,0.061058,0.002432,0.940993,0.938942,0.938308,0.059007,0.061058,0.482145

In [ ]:
Confusion_df100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn100.csv')
eval_result100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn100.csv', index=False)

## LOAD & APPLY MODEL dTOP110fi

In [ ]:
# test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data110
X_test110 = test_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_test110 = test_data110['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn110_double_sim.pkl', 'rb') as f:
    knn110 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=400)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test110, y_test110)):
    X_test_fold = X_test110.values[test_index]

    probability = knn110.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

400it [00:18, 21.14it/s]

In [ ]:
classes110 = knn110.classes_

y_pred110, data_top_5 = get_predictions(y_prob_all, classes110, 10, np.array(y_test110), le)

Confusion_df110 = pd.DataFrame(confusion_matrix(np.array(y_test110), y_pred110))
Confusion_df110.index, Confusion_df110.columns = le.inverse_transform(classes110), le.inverse_transform(classes110)

eval_result110 = calculate_evaluation_metrics(Confusion_df=Confusion_df110)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df110.index = Confusion_df110.index + 1
Confusion_df110
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
130.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
151.0,2,0,1,1,1,1,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
155.0,1,0,5,1,0,0,2,3,0,6,...,0,2,5,1,2,0,1,0,0,0
162.0,0,2,1,0,1,0,0,3,0,3,...,376,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,10,...,1,342,2,4,3,0,1,0,1,0
186.9,1,3,10,0,1,2,2,5,5,10,...,0,0,335,2,3,0,2,0,0,0
198.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
213.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,315,0,5,0,0,0
218.0,3,4,11,3,1,6,0,1,3,15,...,1,2,7,3,0,314,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result110.index = eval_result110.index + 1
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002593,0.937650,0.977500,0.957160,0.062350,0.022500,0.680443
3,18.9,0.965000,0.965000,0.035000,0.007346,0.839130,0.965000,0.897674,0.160870,0.035000,0.819078
4,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
6,98.9,0.982500,0.982500,0.017500,0.002394,0.942446,0.982500,0.962056,0.057554,0.017500,0.743315
7,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.493387
8,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.831063
9,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
10,129.0,0.972500,0.972500,0.027500,0.008625,0.817227,0.972500,0.888128,0.182773,0.027500,0.826670
11,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
12,147.0,0.955000,0.955000,0.045000,0.003190,0.922705,0.955000,0.938575,0.077295,0.045000,0.585773
13,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,0.922340
14,151.0,0.937500,0.937500,0.062500,0.001697,0.956633,0.937500,0.946970,0.043367,0.062500,0.735479
15,153.0,0.900000,0.900000,0.100000,0.002394,0.937500,0.900000,0.918367,0.062500,0.100000,0.555856
16,154.0,0.900000,0.900000,0.100000,0.003388,0.913706,0.900000,0.906801,0.086294,0.100000,0.653272
17,161.0,0.940000,0.940000,0.060000,0.000700,0.981723,0.940000,0.960409,0.018277,0.060000,0.727469
18,169.0,0.855000,0.855000,0.145000,0.000999,0.971591,0.855000,0.909574,0.028409,0.145000,0.619105
19,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.705604
20,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.747798
21,212.9,0.787500,0.787500,0.212500,0.001298,0.960366,0.787500,0.865385,0.039634,0.212500,0.752916
22,217.0,0.785000,0.785000,0.215000,0.000999,0.969136,0.785000,0.867403,0.030864,0.215000,0.486048
23,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.939327,0.939327,0.060673,0.002417,0.941307,0.939327,0.938675,0.058693,0.060673,0.443849

In [ ]:
Confusion_df110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn110.csv')
eval_result110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn110.csv', index=False)

## LOAD & APPLY MODEL dTOP120fi

In [ ]:
# test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data120
X_test120 = test_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_test120 = test_data120['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn120_double_sim.pkl', 'rb') as f:
    knn120 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=400)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test120, y_test120)):
    X_test_fold = X_test120.values[test_index]

    probability = knn120.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

400it [00:19, 20.97it/s]

In [ ]:
classes120 = knn120.classes_

y_pred120, data_top_5 = get_predictions(y_prob_all, classes120, 10, np.array(y_test120), le)

Confusion_df120 = pd.DataFrame(confusion_matrix(np.array(y_test120), y_pred120))
Confusion_df120.index, Confusion_df120.columns = le.inverse_transform(classes120), le.inverse_transform(classes120)

eval_result120 = calculate_evaluation_metrics(Confusion_df=Confusion_df120)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.380952,248.0,0.238095,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df120.index = Confusion_df120.index + 1
Confusion_df120
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
130.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
151.0,2,0,1,1,1,1,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
155.0,1,0,5,1,0,0,2,3,0,7,...,0,2,5,1,2,0,1,0,0,0
162.0,0,2,2,0,1,0,0,3,0,3,...,375,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,10,...,1,342,2,4,3,0,1,0,1,0
186.9,1,3,10,0,1,2,2,5,5,11,...,0,0,335,2,3,0,2,0,0,0
198.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
213.9,1,6,9,4,2,4,2,4,1,8,...,0,2,8,2,315,0,5,0,0,0
218.0,3,4,11,3,1,7,0,1,3,16,...,1,2,7,3,0,313,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result120.index = eval_result120.index + 1
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002593,0.937650,0.977500,0.957160,0.062350,0.022500,0.680443
3,18.9,0.965000,0.965000,0.035000,0.007444,0.837310,0.965000,0.896632,0.162690,0.035000,0.819078
4,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001099,0.972705,0.980000,0.976339,0.027295,0.020000,1.101860
6,98.9,0.982500,0.982500,0.017500,0.002494,0.940191,0.982500,0.960880,0.059809,0.017500,0.743315
7,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.493387
8,111.0,0.962500,0.962500,0.037500,0.003289,0.921053,0.962500,0.941320,0.078947,0.037500,0.831063
9,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
10,129.0,0.972500,0.972500,0.027500,0.008920,0.812109,0.972500,0.885097,0.187891,0.027500,0.826670
11,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
12,147.0,0.955000,0.955000,0.045000,0.003090,0.924939,0.955000,0.939729,0.075061,0.045000,0.585773
13,150.0,0.952500,0.952500,0.047500,0.003388,0.918072,0.952500,0.934969,0.081928,0.047500,0.922340
14,151.0,0.937500,0.937500,0.062500,0.001697,0.956633,0.937500,0.946970,0.043367,0.062500,0.735479
15,153.0,0.900000,0.900000,0.100000,0.002394,0.937500,0.900000,0.918367,0.062500,0.100000,0.555856
16,154.0,0.897500,0.897500,0.102500,0.003289,0.915816,0.897500,0.906566,0.084184,0.102500,0.589162
17,161.0,0.937500,0.937500,0.062500,0.000700,0.981675,0.937500,0.959079,0.018325,0.062500,0.761292
18,169.0,0.855000,0.855000,0.145000,0.000999,0.971591,0.855000,0.909574,0.028409,0.145000,0.619105
19,185.9,0.837500,0.837500,0.162500,0.003885,0.895722,0.837500,0.865633,0.104278,0.162500,0.619384
20,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.747798
21,212.9,0.787500,0.787500,0.212500,0.001298,0.960366,0.787500,0.865385,0.039634,0.212500,0.752916
22,217.0,0.782500,0.782500,0.217500,0.000999,0.969040,0.782500,0.865837,0.030960,0.217500,0.472621
23,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.939038,0.939038,0.060962,0.002429,0.941115,0.939038,0.938397,0.058885,0.060962,0.438852

In [ ]:
Confusion_df120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn120.csv')
eval_result120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn120.csv', index=False)

## LOAD & APPLY MODEL dTOP130fi

In [ ]:
# test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data130
X_test130 = test_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_test130 = test_data130['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn130_double_sim.pkl', 'rb') as f:
    knn130 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=400)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test130, y_test130)):
    X_test_fold = X_test130.values[test_index]

    probability = knn130.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

400it [00:19, 20.69it/s]

In [ ]:
classes130 = knn130.classes_

y_pred130, data_top_5 = get_predictions(y_prob_all, classes130, 10, np.array(y_test130), le)

Confusion_df130 = pd.DataFrame(confusion_matrix(np.array(y_test130), y_pred130))
Confusion_df130.index, Confusion_df130.columns = le.inverse_transform(classes130), le.inverse_transform(classes130)

eval_result130 = calculate_evaluation_metrics(Confusion_df=Confusion_df130)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.333333,248.0,0.238095,251.0,0.238095,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df130.index = Confusion_df130.index + 1
Confusion_df130
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,2,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,1,0,0,0,390,0,0,5,...,0,0,0,1,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,398,0,...,0,0,1,0,0,1,0,0,0,0
130.0,1,1,6,0,1,0,0,0,0,388,...,0,0,0,1,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,3,...,1,0,2,1,1,1,0,0,0,0
151.0,2,0,1,2,1,1,1,0,0,1,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,1,1,0,0,4,0,4,...,1,0,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,0,3,1,6,...,0,0,1,4,1,3,3,0,0,0
155.0,1,0,5,1,0,0,2,3,0,7,...,0,2,5,1,1,0,1,0,0,0
162.0,0,2,2,0,2,0,0,3,0,3,...,374,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,11,...,1,341,2,4,3,0,1,0,1,0
186.9,1,3,10,0,1,2,2,5,5,12,...,0,0,335,2,3,0,2,0,0,0
198.0,3,3,9,2,1,3,5,4,0,8,...,1,1,6,332,1,2,2,0,0,0
213.9,1,6,9,4,2,3,2,4,1,8,...,0,2,8,2,316,0,5,0,0,0
218.0,3,4,11,3,1,7,0,1,3,16,...,1,2,8,3,0,312,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result130.index = eval_result130.index + 1
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.99500,0.99500,0.00500,0.001697,0.959036,0.99500,0.976687,0.040964,0.00500,-3.965838
2,7.1,0.97750,0.97750,0.02250,0.002593,0.937650,0.97750,0.957160,0.062350,0.02250,0.680443
3,18.9,0.96500,0.96500,0.03500,0.007444,0.837310,0.96500,0.896632,0.162690,0.03500,0.819078
4,32.1,0.99000,0.99000,0.01000,0.001896,0.954217,0.99000,0.971779,0.045783,0.01000,0.414882
5,41.0,0.98000,0.98000,0.02000,0.001199,0.970297,0.98000,0.975124,0.029703,0.02000,1.101860
6,98.9,0.98250,0.98250,0.01750,0.002394,0.942446,0.98250,0.962056,0.057554,0.01750,0.743315
7,104.1,0.97500,0.97500,0.02500,0.001996,0.951220,0.97500,0.962963,0.048780,0.02500,0.493387
8,111.0,0.96250,0.96250,0.03750,0.003289,0.921053,0.96250,0.941320,0.078947,0.03750,0.831063
9,128.0,0.99500,0.99500,0.00500,0.001398,0.966019,0.99500,0.980296,0.033981,0.00500,1.156444
10,129.0,0.97000,0.97000,0.03000,0.008920,0.811715,0.97000,0.883827,0.188285,0.03000,0.825864
11,146.0,0.97250,0.97250,0.02750,0.003090,0.926190,0.97250,0.948780,0.073810,0.02750,0.754017
12,147.0,0.95500,0.95500,0.04500,0.002991,0.927184,0.95500,0.940887,0.072816,0.04500,0.585773
13,150.0,0.95250,0.95250,0.04750,0.003488,0.915865,0.95250,0.933824,0.084135,0.04750,0.949886
14,151.0,0.93750,0.93750,0.06250,0.001697,0.956633,0.93750,0.946970,0.043367,0.06250,0.735479
15,153.0,0.90000,0.90000,0.10000,0.002394,0.937500,0.90000,0.918367,0.062500,0.10000,0.619412
16,154.0,0.90000,0.90000,0.10000,0.003388,0.913706,0.90000,0.906801,0.086294,0.10000,0.588538
17,161.0,0.93500,0.93500,0.06500,0.000700,0.981627,0.93500,0.957746,0.018373,0.06500,0.780692
18,169.0,0.85250,0.85250,0.14750,0.000999,0.971510,0.85250,0.908123,0.028490,0.14750,0.553439
19,185.9,0.83750,0.83750,0.16250,0.004083,0.890957,0.83750,0.863402,0.109043,0.16250,0.552974
20,197.0,0.83000,0.83000,0.17000,0.002394,0.932584,0.83000,0.878307,0.067416,0.17000,0.747798
21,212.9,0.79000,0.79000,0.21000,0.001199,0.963415,0.79000,0.868132,0.036585,0.21000,0.745340
22,217.0,0.78000,0.78000,0.22000,0.000999,0.968944,0.78000,0.864266,0.031056,0.22000,0.472704
23,239.2,0.99000,0.99000,0.01000,0.002991,0.929577,0.99000,0.958838,0.070423,0.01000,0.894102
24,248.0,1.00000,1.00000,0.00000,0.000000,1.000000,1.00000,1.000000,0.000000,0.00000,0.000000
25,249.0,0.98250,0.98250,0.01750,0.000100,0.997462,0.98250,0.989924,0.002538,0.01750,0.455442
26,251.0,1.00000,1.00000,0.00000,0.000100,0.997506,1.00000,0.998752,0.002494,0.00000,0.000000
27,average,0.93875,0.93875,0.06125,0.002440,0.940832,0.93875,0.938114,0.059168,0.06125,0.482158

In [ ]:
Confusion_df130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn130.csv')
eval_result130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn130.csv', index=False)

## LOAD & APPLY MODEL dTOP140fi

In [ ]:
# test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data140
X_test140 = test_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_test140 = test_data140['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn140_double_sim.pkl', 'rb') as f:
    knn140 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=300)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test140, y_test140)):
    X_test_fold = X_test140.values[test_index]

    probability = knn140.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

300it [00:18, 15.83it/s]

In [ ]:
classes140 = knn140.classes_

y_pred140, data_top_5 = get_predictions(y_prob_all, classes140, 10, np.array(y_test140), le)

Confusion_df140 = pd.DataFrame(confusion_matrix(np.array(y_test140), y_pred140))
Confusion_df140.index, Confusion_df140.columns = le.inverse_transform(classes140), le.inverse_transform(classes140)

eval_result140 = calculate_evaluation_metrics(Confusion_df=Confusion_df140)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.476190,248.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,248.0,0.476190,32.1,0.238095,5.0,0.190476,41.0,0.095238,NaN,NaN
3,129.0,129.0,0.238095,150.0,0.190476,217.0,0.142857,151.0,0.095238,154.0,0.095238
4,169.0,32.1,0.428571,5.0,0.380952,98.9,0.095238,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.333333,41.0,0.190476,169.0,0.142857,5.0,0.095238,7.1,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.285714,249.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.285714,153.0,0.190476,111.0,0.142857,154.0,0.095238,5.0,0.047619
10398,169.0,161.0,0.333333,41.0,0.285714,169.0,0.142857,150.0,0.095238,7.1,0.047619
10399,249.0,249.0,0.333333,248.0,0.285714,251.0,0.190476,197.0,0.095238,18.9,0.047619
10400,150.0,98.9,0.285714,146.0,0.142857,150.0,0.095238,185.9,0.095238,217.0,0.095238

In [ ]:
Confusion_df140.index = Confusion_df140.index + 1
Confusion_df140
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,1,0,386,1,0,1,2,0,0,1,...,0,1,0,1,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,1,1,393,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,0,0,0,0,390,1,0,5,...,0,0,0,0,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,1,0,0,0,0
130.0,1,1,6,0,1,0,0,0,0,389,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,1,0,0,1,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,1,0,4,0,4,...,1,0,2,1,1,1,0,0,0,0
151.0,2,0,1,1,1,0,1,0,0,2,...,0,0,1,1,1,0,1,0,0,0
152.0,1,1,3,1,1,0,0,3,0,4,...,1,0,1,0,0,1,1,0,0,0
154.0,2,0,3,1,1,2,0,3,1,7,...,0,0,1,4,1,3,3,0,0,0
155.0,1,1,5,1,0,1,2,2,0,7,...,0,2,5,1,2,0,1,0,0,0
162.0,0,2,2,0,2,0,0,3,0,3,...,374,1,3,1,1,2,2,0,0,0
170.0,1,1,9,1,0,2,4,0,1,11,...,1,342,2,4,3,0,1,0,1,0
186.9,1,3,10,0,1,2,2,5,5,11,...,0,0,334,2,3,0,2,0,0,0
198.0,3,3,11,2,1,3,5,3,0,7,...,1,1,6,332,1,2,2,0,0,0
213.9,1,6,9,4,2,3,2,4,1,8,...,0,2,8,2,314,1,5,0,0,0
218.0,3,4,11,3,1,7,0,1,3,16,...,1,1,8,3,0,313,5,0,0,0
240.2,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,396,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,393,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result140.index = eval_result140.index + 1
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002693,0.935407,0.977500,0.955990,0.064593,0.022500,0.680443
3,18.9,0.965000,0.965000,0.035000,0.007543,0.835498,0.965000,0.895592,0.164502,0.035000,0.843988
4,32.1,0.990000,0.990000,0.010000,0.001797,0.956522,0.990000,0.972973,0.043478,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.001199,0.970297,0.980000,0.975124,0.029703,0.020000,1.101860
6,98.9,0.982500,0.982500,0.017500,0.002394,0.942446,0.982500,0.962056,0.057554,0.017500,0.743315
7,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.486484
8,111.0,0.962500,0.962500,0.037500,0.003090,0.925481,0.962500,0.943627,0.074519,0.037500,0.831063
9,128.0,0.997500,0.997500,0.002500,0.001398,0.966102,0.997500,0.981550,0.033898,0.002500,0.000000
10,129.0,0.972500,0.972500,0.027500,0.008920,0.812109,0.972500,0.885097,0.187891,0.027500,0.826670
11,146.0,0.972500,0.972500,0.027500,0.003190,0.923990,0.972500,0.947625,0.076010,0.027500,0.754017
12,147.0,0.952500,0.952500,0.047500,0.003190,0.922518,0.952500,0.937269,0.077482,0.047500,0.584286
13,150.0,0.955000,0.955000,0.045000,0.003488,0.916067,0.955000,0.935129,0.083933,0.045000,0.909818
14,151.0,0.940000,0.940000,0.060000,0.001697,0.956743,0.940000,0.948298,0.043257,0.060000,0.755102
15,153.0,0.897500,0.897500,0.102500,0.002394,0.937337,0.897500,0.916986,0.062663,0.102500,0.558801
16,154.0,0.895000,0.895000,0.105000,0.003388,0.913265,0.895000,0.904040,0.086735,0.105000,0.591432
17,161.0,0.935000,0.935000,0.065000,0.000700,0.981627,0.935000,0.957746,0.018373,0.065000,0.780692
18,169.0,0.855000,0.855000,0.145000,0.000899,0.974359,0.855000,0.910786,0.025641,0.145000,0.553225
19,185.9,0.835000,0.835000,0.165000,0.003984,0.893048,0.835000,0.863049,0.106952,0.165000,0.619458
20,197.0,0.830000,0.830000,0.170000,0.002295,0.935211,0.830000,0.879470,0.064789,0.170000,0.784948
21,212.9,0.785000,0.785000,0.215000,0.001298,0.960245,0.785000,0.863824,0.039755,0.215000,0.746882
22,217.0,0.782500,0.782500,0.217500,0.001099,0.966049,0.782500,0.864641,0.033951,0.217500,0.472699
23,239.2,0.990000,0.990000,0.010000,0.002991,0.929577,0.990000,0.958838,0.070423,0.010000,0.894102
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.982500,0.982500,0.017500,0.000100,0.997462,0.982500,0.989924,0.002538,0.017500,0.455442
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.938654,0.938654,0.061346,0.002444,0.940735,0.938654,0.938001,0.059265,0.061346,0.439376

In [ ]:
Confusion_df140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn140.csv')
eval_result140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn140.csv', index=False)

## LOAD & APPLY MODEL dTOP150fi

In [ ]:
# test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data150
X_test150 = test_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_test150 = test_data150['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn150_double_sim.pkl', 'rb') as f:
    knn150 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=500)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test150, y_test150)):
    X_test_fold = X_test150.values[test_index]

    probability = knn150.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

500it [00:20, 24.17it/s]

In [ ]:
classes150 = knn150.classes_

y_pred150, data_top_5 = get_predictions(y_prob_all, classes150, 10, np.array(y_test150), le)

Confusion_df150 = pd.DataFrame(confusion_matrix(np.array(y_test150), y_pred150))
Confusion_df150.index, Confusion_df150.columns = le.inverse_transform(classes150), le.inverse_transform(classes150)

eval_result150 = calculate_evaluation_metrics(Confusion_df=Confusion_df150)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.50,248.0,0.25,249.0,0.25,NaN,NaN,NaN,NaN
2,41.0,248.0,0.50,5.0,0.20,32.1,0.20,41.0,0.1,NaN,NaN
3,129.0,129.0,0.25,150.0,0.20,151.0,0.10,154.0,0.1,217.0,0.10
4,169.0,5.0,0.40,32.1,0.40,98.9,0.10,169.0,0.1,NaN,NaN
5,161.0,161.0,0.35,41.0,0.20,169.0,0.15,5.0,0.1,239.2,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.40,248.0,0.30,249.0,0.30,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.30,153.0,0.20,111.0,0.15,154.0,0.1,5.0,0.05
10398,169.0,161.0,0.35,41.0,0.25,169.0,0.15,150.0,0.1,7.1,0.05
10399,249.0,249.0,0.35,248.0,0.25,251.0,0.20,197.0,0.1,18.9,0.05
10400,150.0,98.9,0.30,146.0,0.15,185.9,0.10,217.0,0.1,18.9,0.05

In [ ]:
Confusion_df150.index = Confusion_df150.index + 1
Confusion_df150
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8.1,0,391,1,1,0,1,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
19.9,2,0,387,0,0,1,1,0,0,2,...,0,1,0,0,0,0,2,0,0,0
33.1,0,0,0,396,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
42.0,0,2,2,1,392,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,1,1,1,392,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0
105.1,0,0,0,0,0,0,390,2,0,4,...,0,0,0,0,0,0,0,0,0,0
112.0,0,1,2,0,0,0,1,385,1,1,...,0,0,2,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,1,397,1,...,0,0,1,0,0,0,0,0,0,0
130.0,0,1,5,1,1,0,0,0,0,390,...,0,0,0,0,0,0,1,0,0,0
147.0,0,2,0,0,0,0,1,0,1,0,...,0,1,0,1,0,0,0,0,0,0
148.0,0,1,0,0,0,2,1,2,0,1,...,1,0,0,0,0,1,0,0,0,0
151.0,0,0,0,1,1,0,2,0,0,1,...,0,0,1,1,0,0,1,0,0,0
152.0,1,2,2,1,0,0,0,2,0,3,...,1,0,2,0,0,1,1,0,0,0
154.0,3,0,1,1,0,0,1,3,1,3,...,0,0,2,2,0,2,5,0,0,0
155.0,1,0,3,2,0,2,1,3,0,5,...,0,1,4,2,2,0,1,0,0,0
162.0,0,2,1,0,1,0,0,1,0,2,...,379,1,3,2,1,2,1,0,0,0
170.0,2,1,9,1,0,2,4,1,1,7,...,1,347,2,4,3,0,0,0,1,0
186.9,2,3,8,1,1,2,2,3,4,11,...,2,0,338,2,3,0,1,0,0,0
198.0,2,2,9,2,0,2,5,3,0,11,...,0,2,5,335,1,1,2,0,0,0
213.9,1,5,7,3,2,2,1,5,1,9,...,0,1,8,2,319,0,6,0,0,0
218.0,3,3,10,3,1,5,0,2,3,10,...,2,2,7,3,0,323,5,0,0,0
240.2,0,0,0,1,0,0,0,0,1,1,...,0,0,2,0,0,0,394,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,1
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result150.index = eval_result150.index + 1
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.995000,0.995000,0.005000,0.001697,0.959036,0.995000,0.976687,0.040964,0.005000,-3.965838
2,7.1,0.977500,0.977500,0.022500,0.002494,0.939904,0.977500,0.958333,0.060096,0.022500,0.680443
3,18.9,0.967500,0.967500,0.032500,0.006063,0.863839,0.967500,0.912736,0.136161,0.032500,1.008122
4,32.1,0.990000,0.990000,0.010000,0.001996,0.951923,0.990000,0.970588,0.048077,0.010000,0.414882
5,41.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,1.101860
6,98.9,0.980000,0.980000,0.020000,0.001896,0.953771,0.980000,0.966708,0.046229,0.020000,1.039126
7,104.1,0.975000,0.975000,0.025000,0.001996,0.951220,0.975000,0.962963,0.048780,0.025000,0.524005
8,111.0,0.962500,0.962500,0.037500,0.002991,0.927711,0.962500,0.944785,0.072289,0.037500,0.724503
9,128.0,0.992500,0.992500,0.007500,0.001298,0.968293,0.992500,0.980247,0.031707,0.007500,0.952407
10,129.0,0.975000,0.975000,0.025000,0.007346,0.840517,0.975000,0.902778,0.159483,0.025000,0.832551
11,146.0,0.975000,0.975000,0.025000,0.002693,0.935252,0.975000,0.954712,0.064748,0.025000,0.890677
12,147.0,0.962500,0.962500,0.037500,0.003090,0.925481,0.962500,0.943627,0.074519,0.037500,0.690750
13,150.0,0.972500,0.972500,0.027500,0.003090,0.926190,0.972500,0.948780,0.073810,0.027500,0.752044
14,151.0,0.947500,0.947500,0.052500,0.001697,0.957071,0.947500,0.952261,0.042929,0.052500,0.903021
15,153.0,0.917500,0.917500,0.082500,0.002494,0.936224,0.917500,0.926768,0.063776,0.082500,0.679885
16,154.0,0.912500,0.912500,0.087500,0.003190,0.919395,0.912500,0.915935,0.080605,0.087500,0.662708
17,161.0,0.947500,0.947500,0.052500,0.000899,0.976804,0.947500,0.961929,0.023196,0.052500,0.739237
18,169.0,0.867500,0.867500,0.132500,0.000899,0.974719,0.867500,0.917989,0.025281,0.132500,0.764063
19,185.9,0.845000,0.845000,0.155000,0.003885,0.896552,0.845000,0.870013,0.103448,0.155000,0.517739
20,197.0,0.837500,0.837500,0.162500,0.002195,0.938375,0.837500,0.885073,0.061625,0.162500,0.558233
21,212.9,0.797500,0.797500,0.202500,0.000999,0.969605,0.797500,0.875171,0.030395,0.202500,0.604325
22,217.0,0.807500,0.807500,0.192500,0.000700,0.978788,0.807500,0.884932,0.021212,0.192500,0.704864
23,239.2,0.985000,0.985000,0.015000,0.002991,0.929245,0.985000,0.956311,0.070755,0.015000,0.678525
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.501234
26,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
27,average,0.944423,0.944423,0.055577,0.002215,0.945957,0.944423,0.943818,0.054043,0.055577,0.498437

In [ ]:
Confusion_df150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn150.csv')
eval_result150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn150.csv', index=False)

## LOAD & APPLY MODEL dALLfi

In [ ]:
# test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

In [ ]:
# Separate features and tp_ICD_cl0 variable for test_data353
X_test353 = test_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_test353 = test_data353['tp_ICD_cl0']

In [ ]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/knn353_double_sim.pkl', 'rb') as f:
    knn353 = pickle.load(f)

### EVALUATION & SAVE

In [ ]:
# run evaluation in batches
kf = KFold(n_splits=800)

y_prob_all = []
for _, test_index in tqdm.tqdm(kf.split(X_test353, y_test353)):
    X_test_fold = X_test353.values[test_index]

    probability = knn353.predict_proba(X_test_fold)
    y_prob_all.extend(probability)

800it [00:34, 23.17it/s]

In [ ]:
classes353 = knn353.classes_

y_pred353, data_top_5 = get_predictions(y_prob_all, classes353, 10, np.array(y_test353), le)

Confusion_df353 = pd.DataFrame(confusion_matrix(np.array(y_test353), y_pred353))
Confusion_df353.index, Confusion_df353.columns = le.inverse_transform(classes353), le.inverse_transform(classes353)

eval_result353 = calculate_evaluation_metrics(Confusion_df=Confusion_df353)

In [ ]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.50,248.0,0.25,249.0,0.25,NaN,NaN,NaN,NaN
2,41.0,248.0,0.50,5.0,0.10,7.1,0.10,41.0,0.10,147.0,0.10
3,129.0,129.0,0.20,150.0,0.20,41.0,0.15,151.0,0.10,153.0,0.05
4,169.0,5.0,0.40,32.1,0.40,98.9,0.15,169.0,0.05,NaN,NaN
5,161.0,239.2,0.25,32.1,0.15,41.0,0.10,129.0,0.10,161.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.40,248.0,0.30,249.0,0.30,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.30,111.0,0.15,154.0,0.10,5.0,0.05,32.1,0.05
10398,169.0,150.0,0.10,161.0,0.10,169.0,0.10,185.9,0.10,5.0,0.05
10399,249.0,249.0,0.35,248.0,0.25,251.0,0.20,197.0,0.10,5.0,0.05
10400,150.0,98.9,0.20,146.0,0.20,7.1,0.15,150.0,0.15,185.9,0.10

In [ ]:
Confusion_df353.index = Confusion_df353.index + 1
Confusion_df353
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,397,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8.1,0,395,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19.9,2,1,385,1,0,0,0,0,2,2,...,0,1,0,0,0,0,3,0,0,0
33.1,0,0,0,396,0,0,0,0,0,1,...,0,0,0,0,0,0,2,0,0,0
42.0,0,0,0,0,390,0,1,0,2,1,...,1,0,0,0,0,0,0,0,0,0
99.9,0,0,2,1,0,391,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
105.1,0,0,0,0,0,0,389,0,2,3,...,0,1,0,0,0,1,0,0,0,0
112.0,0,0,2,0,0,1,2,383,1,1,...,1,0,1,1,0,0,1,0,0,0
129.0,0,1,0,0,0,0,0,1,390,0,...,0,0,2,1,0,0,1,0,0,0
130.0,2,1,2,0,2,1,1,0,3,385,...,0,0,0,0,1,1,0,0,0,0
147.0,1,2,0,0,0,0,3,0,4,1,...,0,0,1,0,0,0,1,0,0,0
148.0,4,2,0,0,1,2,1,1,1,4,...,1,0,0,1,1,1,0,0,0,0
151.0,2,2,1,0,1,1,1,1,2,1,...,0,2,2,1,1,0,2,0,0,0
152.0,2,2,0,0,0,0,1,1,4,1,...,2,2,3,2,0,1,1,0,0,0
154.0,4,3,2,2,1,3,0,3,2,5,...,1,1,2,1,1,2,2,0,0,0
155.0,3,1,5,0,1,1,1,2,2,6,...,0,0,5,2,1,0,0,0,0,0
162.0,5,6,5,2,6,1,3,2,8,9,...,328,2,4,3,1,1,1,0,0,0
170.0,2,5,10,3,6,3,2,1,4,8,...,3,323,2,2,3,2,1,0,1,0
186.9,6,6,6,1,5,5,4,4,5,12,...,0,0,313,4,3,1,3,0,0,0
198.0,6,2,11,1,4,7,5,4,7,11,...,2,1,5,309,2,2,4,0,0,0
213.9,3,10,4,3,2,8,3,2,8,11,...,0,2,6,3,297,0,5,0,0,0
218.0,4,1,11,4,2,3,1,4,9,15,...,2,2,7,4,0,307,3,0,0,0
240.2,0,2,0,1,0,0,0,0,1,0,...,0,0,3,0,0,0,392,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,394,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [ ]:
eval_result353.index = eval_result353.index + 1
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.992500,0.992500,0.007500,0.004579,0.896163,0.992500,0.941874,0.103837,0.007500,0.055294
2,7.1,0.987500,0.987500,0.012500,0.004678,0.893665,0.987500,0.938242,0.106335,0.012500,0.774043
3,18.9,0.962500,0.962500,0.037500,0.006162,0.861298,0.962500,0.909091,0.138702,0.037500,0.853777
4,32.1,0.990000,0.990000,0.010000,0.001896,0.954217,0.990000,0.971779,0.045783,0.010000,0.429369
5,41.0,0.975000,0.975000,0.025000,0.003090,0.926366,0.975000,0.950061,0.073634,0.025000,0.703796
6,98.9,0.977500,0.977500,0.022500,0.003686,0.913551,0.977500,0.944444,0.086449,0.022500,0.882488
7,104.1,0.972500,0.972500,0.027500,0.002892,0.930622,0.972500,0.951100,0.069378,0.027500,0.579591
8,111.0,0.957500,0.957500,0.042500,0.002593,0.936430,0.957500,0.946848,0.063570,0.042500,0.727675
9,128.0,0.975000,0.975000,0.025000,0.006655,0.853392,0.975000,0.910152,0.146608,0.025000,0.680600
10,129.0,0.962500,0.962500,0.037500,0.009312,0.803758,0.962500,0.875995,0.196242,0.037500,1.028561
11,146.0,0.960000,0.960000,0.040000,0.003984,0.905660,0.960000,0.932039,0.094340,0.040000,0.705799
12,147.0,0.932500,0.932500,0.067500,0.002593,0.934837,0.932500,0.933667,0.065163,0.067500,1.095783
13,150.0,0.935000,0.935000,0.065000,0.004182,0.899038,0.935000,0.916667,0.100962,0.065000,0.956766
14,151.0,0.935000,0.935000,0.065000,0.002593,0.935000,0.935000,0.935000,0.065000,0.065000,0.773271
15,153.0,0.872500,0.872500,0.127500,0.003289,0.913613,0.872500,0.892583,0.086387,0.127500,0.666019
16,154.0,0.905000,0.905000,0.095000,0.003885,0.902743,0.905000,0.903870,0.097257,0.095000,0.707206
17,161.0,0.820000,0.820000,0.180000,0.001298,0.961877,0.820000,0.885290,0.038123,0.180000,0.653380
18,169.0,0.807500,0.807500,0.192500,0.001498,0.955621,0.807500,0.875339,0.044379,0.192500,0.784168
19,185.9,0.782500,0.782500,0.217500,0.004282,0.879213,0.782500,0.828042,0.120787,0.217500,0.509310
20,197.0,0.772500,0.772500,0.227500,0.002693,0.919643,0.772500,0.839674,0.080357,0.227500,0.727116
21,212.9,0.742500,0.742500,0.257500,0.001398,0.954984,0.742500,0.835443,0.045016,0.257500,0.705379
22,217.0,0.767500,0.767500,0.232500,0.001199,0.962382,0.767500,0.853964,0.037618,0.232500,0.487805
23,239.2,0.980000,0.980000,0.020000,0.003090,0.926714,0.980000,0.952612,0.073286,0.020000,0.706865
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.985000,0.985000,0.015000,0.000100,0.997468,0.985000,0.991195,0.002532,0.015000,0.515731
26,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
27,average,0.921154,0.921154,0.078846,0.003140,0.923779,0.921154,0.919807,0.076221,0.078846,0.642684

In [ ]:
Confusion_df353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/confusion_test_double_knn353.csv')
eval_result353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_double/fv_6 (with or without lk)/data_with_lk@500/result_test_double_knn353.csv', index=False)