# **IMPORT LIBRARY**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pickle, time, json
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [11]:
train_data = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/train_dataset.csv', index_col=False)
test_data = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/test_dataset.csv', index_col=False)

In [12]:
train_data

,n_de_01,n_de_02,n_de_03,c_de_04,n_vs_01,n_vs_02,n_vs_03,n_vs_04,n_vs_05,n_vs_06,...,c_lk_111,c_lk_112,c_lk_113,c_lk_114,c_lk_115,c_lk_116,c_lk_121,c_lk_127,c_lk_128,tp_ICD_cl0
0,0.0,0.0,1.0,1,3.0,176.0,70.0,105.0,36.0,251.0,...,1,1,1,1,1,1,1,1,1,251.0
1,6.0,0.0,11.0,1,21.0,106.0,70.0,105.0,37.0,20.0,...,1,1,1,1,1,1,1,1,1,41.0
2,69.0,3.0,9.0,2,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,129.0
3,9.0,6.0,17.0,1,31.0,121.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,169.0
4,28.0,1.0,25.0,2,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10395,0.0,0.0,1.0,2,9.0,176.0,70.0,105.0,36.1,295.0,...,1,1,1,1,1,1,1,1,1,248.0
10396,20.0,3.0,14.0,1,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,153.0
10397,64.0,1.0,26.0,2,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,169.0
10398,0.0,0.0,4.0,1,9.0,75.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,249.0
10399,43.0,8.0,8.0,1,70.0,163.0,70.0,110.0,37.0,24.0,...,1,1,1,1,1,1,1,1,1,150.0

In [13]:
test_data

,n_de_01,n_de_02,n_de_03,c_de_04,n_vs_01,n_vs_02,n_vs_03,n_vs_04,n_vs_05,n_vs_06,...,c_lk_111,c_lk_112,c_lk_113,c_lk_114,c_lk_115,c_lk_116,c_lk_121,c_lk_127,c_lk_128,tp_ICD_cl0
0,62.0,2.0,20.0,2,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,151.0
1,54.0,5.0,1.0,2,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,185.9
2,0.0,0.0,1.0,2,9.0,74.0,70.0,105.0,37.0,20.0,...,1,1,1,1,1,1,1,1,1,248.0
3,57.0,5.0,20.0,1,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,146.0
4,0.0,0.0,1.0,1,9.0,176.0,70.0,105.0,36.4,251.0,...,1,1,1,1,1,1,1,1,1,251.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595,58.0,11.0,28.0,1,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,150.0
2596,71.0,2.0,9.0,1,56.0,176.0,70.0,105.0,36.5,20.0,...,1,1,1,1,1,1,1,1,1,18.9
2597,38.0,1.0,12.0,2,60.0,154.0,786.0,137.0,36.4,22.0,...,1,1,1,1,1,1,1,1,1,217.0
2598,65.0,9.0,24.0,2,42.0,150.0,977.0,139.0,36.0,20.0,...,1,1,1,1,1,1,1,1,1,104.1
2599,0.0,0.0,1.0,2,9.0,176.0,70.0,105.0,36.7,251.0,...,1,1,1,1,1,1,1,1,1,251.0

In [14]:
data = pd.concat([train_data, test_data], axis=0)

In [15]:
data['tp_ICD_cl0'].value_counts()

tp_ICD_cl0
251.0    500
41.0     500
7.1      500
150.0    500
153.0    500
212.9    500
18.9     500
239.2    500
32.1     500
146.0    500
185.9    500
111.0    500
151.0    500
217.0    500
147.0    500
98.9     500
104.1    500
128.0    500
197.0    500
5.0      500
248.0    500
249.0    500
161.0    500
169.0    500
129.0    500
154.0    500
Name: count, dtype: int64

In [9]:
data['tp_ICD_cl1'].value_counts()

tp_ICD_cl1
1875    500
880     496
2608    486
1942    485
1847    475
       ...
4511      1
5291      1
4779      1
4807      1
3833      1
Name: count, Length: 313, dtype: int64

In [ ]:
data['tp_IdPasien'].value_counts()

# **LOADING DATASET**

### LOAD DATA PMR unbalanced 360 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA positive unbalanced 344 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA @500 110 class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA @1000 55 class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA TOP 10 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA WITH LK

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/test_dataset.csv', index_col=False)

with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/feature_dictionary.json', 'rb') as file:
    features = json.load(file)

### LOAD DATA NO LK @1000

In [4]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/test_dataset.csv', index_col=False)

# PREPROCESSING

In [6]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/feature_dictionary.json', 'r') as json_file:
    feature_dictionary = json.load(json_file)

## ALL FEATURES

In [7]:
train_data353 = train_df[feature_dictionary['all'] + ['tp_ICD_cl0']]
test_data353 = test_df[feature_dictionary['all'] + ['tp_ICD_cl0']]

In [8]:
train_data353.head()

,n_de_01,c_an_071,c_an_169,n_vs_06,n_lk_012,n_de_02,n_vs_05,n_vs_01,c_de_04,n_de_03,...,c_lk_111,c_lk_112,c_lk_113,c_lk_114,c_lk_115,c_lk_116,c_lk_121,c_lk_127,c_lk_128,tp_ICD_cl0
0,0.0,0,0,251.0,39.0,0.0,36.0,3.0,1,1.0,...,1,1,1,1,1,1,1,1,1,251.0
1,6.0,0,0,20.0,66.0,0.0,37.0,21.0,1,11.0,...,1,1,1,1,1,1,1,1,1,41.0
2,69.0,0,0,20.0,66.0,3.0,36.5,56.0,2,9.0,...,1,1,1,1,1,1,1,1,1,129.0
3,9.0,0,0,20.0,66.0,6.0,36.5,31.0,1,17.0,...,1,1,1,1,1,1,1,1,1,169.0
4,28.0,0,1,20.0,66.0,1.0,36.5,56.0,2,25.0,...,1,1,1,1,1,1,1,1,1,161.0

In [9]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_all.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data353.columns if x.startswith('n_')]

train_data353[num_cols] = scaler.transform(train_data353[num_cols])
test_data353[num_cols] = scaler.transform(test_data353[num_cols])

In [10]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_all.pkl', 'rb') as file:
    le = pickle.load(file)

train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])
test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

## 150 FEATURES

In [11]:
train_data150 = train_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]
test_data150 = test_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]

In [12]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_150.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data150.columns if x.startswith('n_')]

train_data150[num_cols] = scaler.transform(train_data150[num_cols])
test_data150[num_cols] = scaler.transform(test_data150[num_cols])

<ipython-input-12-d7780d979e14>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data150[num_cols] = scaler.transform(train_data150[num_cols])
<ipython-input-12-d7780d979e14>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data150[num_cols] = scaler.transform(test_data150[num_cols])

In [13]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_150.pkl', 'rb') as file:
    le = pickle.load(file)

train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])
test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

<ipython-input-13-eb221fc66b4d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])
<ipython-input-13-eb221fc66b4d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

## 140 FEATURES

In [14]:
train_data140 = train_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]
test_data140 = test_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]

In [15]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_140.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data140.columns if x.startswith('n_')]

train_data140[num_cols] = scaler.transform(train_data140[num_cols])
test_data140[num_cols] = scaler.transform(test_data140[num_cols])

<ipython-input-15-ab269fcf6307>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data140[num_cols] = scaler.transform(train_data140[num_cols])
<ipython-input-15-ab269fcf6307>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data140[num_cols] = scaler.transform(test_data140[num_cols])

In [16]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_140.pkl', 'rb') as file:
    le = pickle.load(file)

train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])
test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

<ipython-input-16-b6dd57056cfb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])
<ipython-input-16-b6dd57056cfb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

## 130 FEATURES

In [17]:
train_data130 = train_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]
test_data130 = test_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]

In [18]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_130.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data130.columns if x.startswith('n_')]

train_data130[num_cols] = scaler.transform(train_data130[num_cols])
test_data130[num_cols] = scaler.transform(test_data130[num_cols])

<ipython-input-18-d396a671a766>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data130[num_cols] = scaler.transform(train_data130[num_cols])
<ipython-input-18-d396a671a766>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data130[num_cols] = scaler.transform(test_data130[num_cols])

In [19]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_130.pkl', 'rb') as file:
    le = pickle.load(file)

train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])
test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

<ipython-input-19-fe925daf011a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])
<ipython-input-19-fe925daf011a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

## 120 FEATURES

In [20]:
train_data120 = train_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]
test_data120 = test_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]

In [21]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_120.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data120.columns if x.startswith('n_')]

train_data120[num_cols] = scaler.transform(train_data120[num_cols])
test_data120[num_cols] = scaler.transform(test_data120[num_cols])

<ipython-input-21-5b8ca95de23e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data120[num_cols] = scaler.transform(train_data120[num_cols])
<ipython-input-21-5b8ca95de23e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data120[num_cols] = scaler.transform(test_data120[num_cols])

In [22]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_120.pkl', 'rb') as file:
    le = pickle.load(file)

train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])
test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

<ipython-input-22-a89b9322186f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])
<ipython-input-22-a89b9322186f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

## 110 FEATURES

In [23]:
train_data110 = train_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]
test_data110 = test_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]

In [24]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_110.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data110.columns if x.startswith('n_')]

train_data110[num_cols] = scaler.transform(train_data110[num_cols])
test_data110[num_cols] = scaler.transform(test_data110[num_cols])

<ipython-input-24-b6a0c56ccce1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data110[num_cols] = scaler.transform(train_data110[num_cols])
<ipython-input-24-b6a0c56ccce1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data110[num_cols] = scaler.transform(test_data110[num_cols])

In [25]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_110.pkl', 'rb') as file:
    le = pickle.load(file)

train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])
test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

<ipython-input-25-42a46f7ddb06>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])
<ipython-input-25-42a46f7ddb06>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

## 100 FEATURES

In [26]:
train_data100 = train_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]
test_data100 = test_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]

In [27]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_100.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data100.columns if x.startswith('n_')]

train_data100[num_cols] = scaler.transform(train_data100[num_cols])
test_data100[num_cols] = scaler.transform(test_data100[num_cols])

<ipython-input-27-41d179283bda>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data100[num_cols] = scaler.transform(train_data100[num_cols])
<ipython-input-27-41d179283bda>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data100[num_cols] = scaler.transform(test_data100[num_cols])

In [28]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_100.pkl', 'rb') as file:
    le = pickle.load(file)

train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])
test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

<ipython-input-28-8e132ae2ecda>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])
<ipython-input-28-8e132ae2ecda>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

## 90 FEATURES

In [29]:
train_data90 = train_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]
test_data90 = test_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]

In [30]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_90.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data90.columns if x.startswith('n_')]

train_data90[num_cols] = scaler.transform(train_data90[num_cols])
test_data90[num_cols] = scaler.transform(test_data90[num_cols])

<ipython-input-30-0e136ed5ebff>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data90[num_cols] = scaler.transform(train_data90[num_cols])
<ipython-input-30-0e136ed5ebff>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data90[num_cols] = scaler.transform(test_data90[num_cols])

In [31]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_90.pkl', 'rb') as file:
    le = pickle.load(file)

train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])
test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

<ipython-input-31-ebaecd4de649>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])
<ipython-input-31-ebaecd4de649>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

## 80 FEATURES

In [32]:
train_data80 = train_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]
test_data80 = test_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]

In [33]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_80.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data80.columns if x.startswith('n_')]

train_data80[num_cols] = scaler.transform(train_data80[num_cols])
test_data80[num_cols] = scaler.transform(test_data80[num_cols])

<ipython-input-33-7cb41b057e56>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data80[num_cols] = scaler.transform(train_data80[num_cols])
<ipython-input-33-7cb41b057e56>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data80[num_cols] = scaler.transform(test_data80[num_cols])

In [34]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_80.pkl', 'rb') as file:
    le = pickle.load(file)

train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])
test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

<ipython-input-34-dad9543c0862>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])
<ipython-input-34-dad9543c0862>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

## 70 FEATURES

In [35]:
train_data70 = train_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]
test_data70 = test_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]

In [36]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_70.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data70.columns if x.startswith('n_')]

train_data70[num_cols] = scaler.transform(train_data70[num_cols])
test_data70[num_cols] = scaler.transform(test_data70[num_cols])

<ipython-input-36-3bee303adb9f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data70[num_cols] = scaler.transform(train_data70[num_cols])
<ipython-input-36-3bee303adb9f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data70[num_cols] = scaler.transform(test_data70[num_cols])

In [37]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_70.pkl', 'rb') as file:
    le = pickle.load(file)

train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])
test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

<ipython-input-37-6ab11f4b1e9c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])
<ipython-input-37-6ab11f4b1e9c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

## 60 FEATURES

In [38]:
train_data60 = train_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]
test_data60 = test_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]

In [39]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_60.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data60.columns if x.startswith('n_')]

train_data60[num_cols] = scaler.transform(train_data60[num_cols])
test_data60[num_cols] = scaler.transform(test_data60[num_cols])

<ipython-input-39-80b488acb113>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data60[num_cols] = scaler.transform(train_data60[num_cols])
<ipython-input-39-80b488acb113>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data60[num_cols] = scaler.transform(test_data60[num_cols])

In [40]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_60.pkl', 'rb') as file:
    le = pickle.load(file)

train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])
test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

<ipython-input-40-e4d5e8685e83>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])
<ipython-input-40-e4d5e8685e83>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

## 50 FEATURES

In [41]:
train_data50 = train_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]
test_data50 = test_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]

In [42]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_50.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data50.columns if x.startswith('n_')]

train_data50[num_cols] = scaler.transform(train_data50[num_cols])
test_data50[num_cols] = scaler.transform(test_data50[num_cols])

<ipython-input-42-637e289183fc>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data50[num_cols] = scaler.transform(train_data50[num_cols])
<ipython-input-42-637e289183fc>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data50[num_cols] = scaler.transform(test_data50[num_cols])

In [43]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_50.pkl', 'rb') as file:
    le = pickle.load(file)

train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])
test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

<ipython-input-43-c06db5ef2e7d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])
<ipython-input-43-c06db5ef2e7d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

## 40 FEATURES

In [44]:
train_data40 = train_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]
test_data40 = test_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]

In [45]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_40.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data40.columns if x.startswith('n_')]

train_data40[num_cols] = scaler.transform(train_data40[num_cols])
test_data40[num_cols] = scaler.transform(test_data40[num_cols])

<ipython-input-45-e05a374fe52c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data40[num_cols] = scaler.transform(train_data40[num_cols])
<ipython-input-45-e05a374fe52c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data40[num_cols] = scaler.transform(test_data40[num_cols])

In [46]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_40.pkl', 'rb') as file:
    le = pickle.load(file)

train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])
test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

<ipython-input-46-7f88282e3a39>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])
<ipython-input-46-7f88282e3a39>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

## 30 FEATURES

In [47]:
train_data30 = train_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]
test_data30 = test_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]

In [48]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_30.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data30.columns if x.startswith('n_')]

train_data30[num_cols] = scaler.transform(train_data30[num_cols])
test_data30[num_cols] = scaler.transform(test_data30[num_cols])

<ipython-input-48-7b796c1929ff>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data30[num_cols] = scaler.transform(train_data30[num_cols])
<ipython-input-48-7b796c1929ff>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data30[num_cols] = scaler.transform(test_data30[num_cols])

In [49]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_30.pkl', 'rb') as file:
    le = pickle.load(file)

train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])
test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

<ipython-input-49-2b3f8ac79a19>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])
<ipython-input-49-2b3f8ac79a19>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

## 20 FEATURES

In [50]:
train_data20 = train_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]
test_data20 = test_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]

In [51]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_20.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data20.columns if x.startswith('n_')]

train_data20[num_cols] = scaler.transform(train_data20[num_cols])
test_data20[num_cols] = scaler.transform(test_data20[num_cols])

<ipython-input-51-55a266707538>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data20[num_cols] = scaler.transform(train_data20[num_cols])
<ipython-input-51-55a266707538>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data20[num_cols] = scaler.transform(test_data20[num_cols])

In [52]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_20.pkl', 'rb') as file:
    le = pickle.load(file)

train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])
test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

<ipython-input-52-7c0038e6c95b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])
<ipython-input-52-7c0038e6c95b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

## 10 FEATURES

In [53]:
train_data10 = train_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]
test_data10 = test_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]

In [54]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_10.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data10.columns if x.startswith('n_')]

train_data10[num_cols] = scaler.transform(train_data10[num_cols])
test_data10[num_cols] = scaler.transform(test_data10[num_cols])

<ipython-input-54-506e0a1cd87d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data10[num_cols] = scaler.transform(train_data10[num_cols])
<ipython-input-54-506e0a1cd87d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data10[num_cols] = scaler.transform(test_data10[num_cols])

In [55]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_10.pkl', 'rb') as file:
    le = pickle.load(file)

train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])
test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

<ipython-input-55-154e8dc9241a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])
<ipython-input-55-154e8dc9241a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

## 5 FEATURES

In [56]:
train_data5 = train_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]
test_data5 = test_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]

In [57]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_5.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data5.columns if x.startswith('n_')]

train_data5[num_cols] = scaler.transform(train_data5[num_cols])
test_data5[num_cols] = scaler.transform(test_data5[num_cols])

<ipython-input-57-38b2eab33523>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data5[num_cols] = scaler.transform(train_data5[num_cols])
<ipython-input-57-38b2eab33523>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data5[num_cols] = scaler.transform(test_data5[num_cols])

In [58]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_5.pkl', 'rb') as file:
    le = pickle.load(file)

train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])
test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

<ipython-input-58-9ed65b4e62d0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])
<ipython-input-58-9ed65b4e62d0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

# FUNCTIONS

Jumlah Kelas:


*   Data @500 = 110 class
*   Data @1000 = 55 class
*   Data Top 10 Class = 10 class
*   Data all positive = 344 class
*   Data all pmr = 360 class

In [59]:
# ubah threshold disini
threshold = [True, 1/26]

In [60]:
def get_predictions(y_prob, classes, threshold, top_n, y_true, le):
    y_pred = []

    keys = ['true_list', "pred_code1", "score1", "pred_code2", "score2", "pred_code3", "score3", "pred_code4", "score4", "pred_code5", "score5"]
    data_top_5 = {key: [] for key in keys}

    for idx, prob in enumerate(y_prob):
        above_threshold_indices = np.where(prob > threshold[1])[0]
        if len(above_threshold_indices) == 0:
            # If no classes are above the threshold, use the highest scores
            sorted_indices = np.argsort(-prob)[:top_n]
        else:
            # Sort filtered classes by probability in descending order
            above_threshold_probabilities = prob[above_threshold_indices]
            sorted_indices = above_threshold_indices[np.argsort(-above_threshold_probabilities)][:top_n]

        recommended_icd_code = [classes[i] for i in sorted_indices]
        recommended_score = [prob[i] for i in sorted_indices]
        if y_true[idx] in recommended_icd_code:
            y_pred.append(y_true[idx])
        else:
            y_pred.append(recommended_icd_code[0])

        # Ensure we have 5 elements in the lists
        while len(recommended_icd_code) < 5:
            recommended_icd_code.append(None)
            recommended_score.append(None)
        try:
            data_top_5['true_list'].append(le.inverse_transform([y_true[idx]])[0])
        except:
            data_top_5['true_list'].append(y_true[idx])

        try:
            data_top_5['pred_code1'].append(le.inverse_transform([recommended_icd_code[0]])[0])
        except:
            data_top_5['pred_code1'].append(recommended_icd_code[0])
        data_top_5['score1'].append(recommended_score[0])

        try:
            data_top_5['pred_code2'].append(le.inverse_transform([recommended_icd_code[1]])[0])
        except:
            data_top_5['pred_code2'].append(recommended_icd_code[1])
        data_top_5['score2'].append(recommended_score[1])

        try:
            data_top_5['pred_code3'].append(le.inverse_transform([recommended_icd_code[2]])[0])
        except:
            data_top_5['pred_code3'].append(recommended_icd_code[2])
        data_top_5['score3'].append(recommended_score[2])

        try:
            data_top_5['pred_code4'].append(le.inverse_transform([recommended_icd_code[3]])[0])
        except:
            data_top_5['pred_code4'].append(recommended_icd_code[3])
        data_top_5['score4'].append(recommended_score[3])

        try:
            data_top_5['pred_code5'].append(le.inverse_transform([recommended_icd_code[4]])[0])
        except:
            data_top_5['pred_code5'].append(recommended_icd_code[4])
        data_top_5['score5'].append(recommended_score[4])

    return y_pred, data_top_5

In [61]:
def knn_custom_kfold_evaluation(X, y, le, feature, n_splits=10, top_n=10, best_k=16026):
    X = np.array(X)
    y = np.array(y)

    kf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    # kf = KFold(n_splits=n_splits)
    accuracy_scores, error_rates, precisions, recalls, f1_scores, index_list = [],[],[],[],[],[]

    cross_validation_results = pd.DataFrame(columns=["kfold", "accuracy", "f1_score", "error_rate", "recall", "precisions"])
    counter = 1

    for train_index, test_index in kf.split(X, y):
        index_list.append((train_index, test_index))
        X_train_fold, X_test_fold = X[train_index], X[test_index]
        y_train_fold, y_test_fold = y[train_index], y[test_index]
        y_le = list(set(y))

        if counter % 2 == 0:
            model = KNeighborsClassifier(n_neighbors=best_k,
                                     metric='euclidean', weights='distance')
        else:
            model = KNeighborsClassifier(n_neighbors=best_k,
                                     metric='euclidean')

        model.fit(X_train_fold, y_train_fold)

        classes = model.classes_
        y_prob = model.predict_proba(X_test_fold)

        y_true = y_test_fold
        y_pred, _ = get_predictions(y_prob, classes, threshold, top_n, y_test_fold, le)

        cm = pd.DataFrame(confusion_matrix(y_test_fold, y_pred, labels=y_le))
        cm.index, cm.columns = le.inverse_transform(y_le), le.inverse_transform(y_le)


        # evaluation result per fold per class
        eval_per_fold = calculate_evaluation_metrics(Confusion_df=cm)
        eval_per_fold.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/data_per_fold_{feature}/eval_per_fold_{counter}.csv', index=False)

        accuracy = calculate_accuracy(cm)
        error_rate = 1 - accuracy
        precision = calculate_precision(cm)
        recall = calculate_recall(cm)
        f1_score = calculate_f1_score(precision, recall)

        cross_validation_results.loc[counter] = [int(counter), accuracy, f1_score, error_rate, recall, precision]

        accuracy_scores.append(accuracy)
        error_rates.append(error_rate)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1_score)

        counter += 1

    max_idx = np.argmax(cross_validation_results['accuracy'])
    cross_validation_results.loc[counter] = ["average", cross_validation_results["accuracy"].mean(), cross_validation_results["f1_score"].mean(), cross_validation_results["error_rate"].mean(), cross_validation_results["recall"].mean(), cross_validation_results["precisions"].mean()]
    cross_validation_results.loc[counter+1] = ["max", cross_validation_results["accuracy"][max_idx+1], cross_validation_results["f1_score"][max_idx+1], cross_validation_results["error_rate"][max_idx+1], cross_validation_results["recall"][max_idx+1], cross_validation_results["precisions"][max_idx+1]]
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    # cari fold mana yang akurasinya paling tinggi
    top_accuracy_idx = np.argmax(accuracy_scores)
    top_index_fold = index_list[top_accuracy_idx]

    # define, fit, predict, and evaluate the new model
    if (top_accuracy_idx + 1) % 2 == 0:
        new_model = KNeighborsClassifier(n_neighbors=best_k,
                                     metric='euclidean', weights='distance')
    else:
        new_model = KNeighborsClassifier(n_neighbors=best_k,
                                     metric='euclidean')
    # new_model.fit(X[top_index_fold[0]], y[top_index_fold[0]])
    new_model.fit(X, y)
    new_y_prob = new_model.predict_proba(X)
    new_classes = new_model.classes_
    print(len(new_classes))
    new_y_pred, data_top_5 = get_predictions(new_y_prob, new_classes, threshold, top_n, y, le)

    new_cm = pd.DataFrame(confusion_matrix(y, new_y_pred))
    new_cm.index, new_cm.columns = le.inverse_transform(new_classes), le.inverse_transform(new_classes)

    eval = calculate_evaluation_metrics(Confusion_df=new_cm)
    new_cm.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_train_knn{feature}.csv')
    eval.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_train_knn{feature}.csv', index=False)

    try:
        cross_validation_results = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index_col=False)
    except:
        print("tidak ada data, ulangi proses cross val!")

    # append data fold ke 11
    accuracy11 = calculate_accuracy(new_cm)
    error_rate11 = 1 - accuracy11
    precision11 = calculate_precision(new_cm)
    recall11 = calculate_recall(new_cm)
    f1_score11 = calculate_f1_score(precision11, recall11)
    fold11 = [11, accuracy11, f1_score11, error_rate11, recall11, precision11]

    cross_validation_results = pd.concat([cross_validation_results.iloc[:10], pd.DataFrame([fold11], columns=cross_validation_results.columns), cross_validation_results.iloc[10:]], ignore_index=True)
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    return new_model, data_top_5, new_cm, eval, cross_validation_results

In [62]:
def calculate_dcg(scores):
    return np.sum((2**scores - 1) / np.log2(np.arange(2, scores.size + 2)))

def calculate_ndcg(Confusion_df):
    ndcgs = []
    for i, true_label in enumerate(Confusion_df.index):
        predicted_scores = Confusion_df.loc[true_label].values
        ideal_scores = np.sort(predicted_scores)[::-1]
        dcg = calculate_dcg(predicted_scores)
        idcg = calculate_dcg(ideal_scores)
        ndcg = dcg / idcg if idcg > 0 else 0
        ndcgs.append(ndcg)
    return np.mean(ndcgs)

def calculate_accuracy(Confusion_df):
    diagonal_sum = np.trace(Confusion_df.values)
    total_sum = np.sum(Confusion_df.values)
    accuracy = diagonal_sum / total_sum
    return accuracy

def calculate_precision(Confusion_df):
    precisions = []
    for label in Confusion_df.columns:
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        precision = tp / column_sum if column_sum != 0 else 0
        precisions.append(precision)
    average_precision = np.mean(precisions)
    return average_precision

def calculate_recall(Confusion_df):
    recalls = []
    for label in Confusion_df.index:
        tp = Confusion_df.at[label, label]
        row_sum = Confusion_df.loc[label].sum()
        recall = tp / row_sum if row_sum != 0 else 0
        recalls.append(recall)
    average_recall = np.mean(recalls)
    return average_recall

def calculate_f1_score(precision, recall):
    if (precision + recall) == 0:
        return 0
    return 2 * (precision * recall) / (precision + recall)

def evaluate_predictions(data, classes):
    true_list = data['true_list']
    predicted_icd_codes, predicted_highest_score = [], []

    for i in range(len(data['true_list'])):
        top_5_pred = [
            data['pred_code1'][i],
            data['pred_code2'][i],
            data['pred_code3'][i],
            data['pred_code4'][i],
            data['pred_code5'][i]
        ]
        if data['true_list'][i] in top_5_pred:
            predicted_icd_codes.append(data['true_list'][i])
            predicted_highest_score.append(data[f'score{top_5_pred.index(data["true_list"][i]) + 1}'][i])
        else:
            predicted_icd_codes.append(data['pred_code1'][i])
            predicted_highest_score.append(data['score1'][i])

    Confusion = confusion_matrix(true_list, predicted_icd_codes)
    Confusion_df = pd.DataFrame(Confusion, columns=classes, index=classes)

    data_top_1 = pd.DataFrame({
        'true_icd_code': true_list,
        'predicted_icd_codes': predicted_icd_codes,
        'predicted_highest_score': predicted_highest_score
    })

    return true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1

In [63]:
def calculate_evaluation_metrics(data=None, classes=None, Confusion_df=None):
    if not isinstance(Confusion_df, pd.DataFrame):
        true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1 = evaluate_predictions(data, classes)

    accuracy = calculate_accuracy(Confusion_df)
    precision = calculate_precision(Confusion_df)
    recall = calculate_recall(Confusion_df)

    eval_result = pd.DataFrame(columns=['class', 'accuracy', 'hit_rate', 'error_rate', 'specificity', 'precision', 'recall', 'f1', 'type_1_error', 'type_2_error', 'ndcg'])

    for idx, label in enumerate(Confusion_df.columns):
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        row_sum = Confusion_df.loc[label].sum()
        accuracy = tp / row_sum if row_sum != 0 else 0
        error_rate = 1 - accuracy
        specificity = (column_sum - tp) / (column_sum - tp + Confusion_df.values.sum() - row_sum)
        precision = tp / column_sum if column_sum != 0 else 0
        recall = tp / row_sum if row_sum != 0 else 0
        hit_rate = recall
        f1 = calculate_f1_score(precision, recall)
        type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
        type_2_error = (Confusion_df.loc[label].sum() - tp) / (Confusion_df.loc[label].sum())
        class_ndcg = calculate_ndcg(Confusion_df.loc[[label]])

        eval_result.loc[idx] = [label, accuracy, hit_rate, error_rate, specificity, precision, recall, f1, type_1_error, type_2_error, class_ndcg]

    avg_accuracy = eval_result['accuracy'].mean()
    avg_error_rate = eval_result['error_rate'].mean()
    avg_specificity = eval_result['specificity'].mean()
    avg_precision = eval_result['precision'].mean()
    avg_recall = eval_result['recall'].mean()
    avg_hit_rate = avg_recall
    avg_f1 = eval_result['f1'].mean()
    avg_type_1_error = eval_result['type_1_error'].mean()
    avg_type_2_error = eval_result['type_2_error'].mean()
    avg_ndcg = eval_result['ndcg'].mean()

    avg_row = ['average', avg_accuracy, avg_hit_rate, avg_error_rate, avg_specificity, avg_precision, avg_recall, avg_f1, avg_type_1_error, avg_type_2_error, avg_ndcg]
    eval_result.loc[len(eval_result)] = avg_row

    if not isinstance(Confusion_df, pd.DataFrame):
        return Confusion_df, eval_result, data_top_1
    else:
        return eval_result

In [64]:
class CalculateTime:
    def __init__(self, features, data_type):
        self.features = features
        self.data_type = data_type

    def start(self):
        self.start_time = time.time()

    def time_taken(self):
        return (time.time() - self.start_time) / 60

    def save_time_to_csv(self, time_taken, file_name='/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/training_times.csv'):
        df = pd.DataFrame({'features': [self.features],
                           'data_type': [self.data_type],
                           'time_taken (minutes)': [time_taken]})

        df.to_csv(file_name, mode='a', header=not pd.io.common.file_exists(file_name), index=False)

# **TRAINING**

## TRAIN knn TOP 5fi

In [65]:
# Separate features and tp_ICD_cl0 variable for train_data5
X_train5 = train_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_train5 = train_data5['tp_ICD_cl0']

In [66]:
y_train5.value_counts()

tp_ICD_cl0
25    400
4     400
1     400
12    400
14    400
20    400
2     400
22    400
3     400
10    400
18    400
7     400
13    400
21    400
11    400
5     400
6     400
8     400
19    400
0     400
23    400
24    400
16    400
17    400
9     400
15    400
Name: count, dtype: int64

In [67]:
timer = CalculateTime(features=5, data_type='train')
timer.start()

knn5, data_top_5, Confusion_df5, eval_result5, cv_result5 = knn_custom_kfold_evaluation(X_train5, y_train5, le, feature=5, best_k=24)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.52 minutes

In [68]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.416667,248.0,0.333333,249.0,0.250000,NaN,NaN,NaN,NaN
2,41.0,32.1,0.416667,5.0,0.375000,217.0,0.083333,7.1,0.041667,41.0,0.041667
3,129.0,150.0,0.125000,154.0,0.125000,212.9,0.125000,98.9,0.083333,111.0,0.083333
4,169.0,32.1,0.541667,5.0,0.291667,169.0,0.083333,18.9,0.041667,98.9,0.041667
5,161.0,161.0,0.250000,41.0,0.208333,169.0,0.166667,7.1,0.083333,18.9,0.083333
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.666667,251.0,0.208333,249.0,0.125000,NaN,NaN,NaN,NaN
10397,153.0,239.2,0.375000,32.1,0.125000,111.0,0.125000,18.9,0.083333,129.0,0.083333
10398,169.0,41.0,0.250000,161.0,0.250000,169.0,0.125000,129.0,0.083333,7.1,0.041667
10399,249.0,249.0,0.416667,248.0,0.208333,251.0,0.208333,5.0,0.083333,98.9,0.041667
10400,150.0,146.0,0.333333,98.9,0.125000,239.2,0.125000,18.9,0.083333,32.1,0.083333

In [69]:
Confusion_df5

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,341,2,0,0,0,0,9,0,0,4,...,0,0,0,4,7,2,1,0,0,0
7.1,8,307,4,0,6,0,4,0,0,2,...,1,1,0,14,15,0,5,0,0,1
18.9,0,0,324,1,2,0,5,1,0,0,...,0,0,0,4,3,0,2,0,8,0
32.1,1,6,3,340,3,0,4,3,1,1,...,0,0,0,3,8,4,0,0,3,0
41.0,4,3,0,1,350,2,7,1,5,1,...,0,0,0,0,2,0,4,0,0,0
98.9,3,0,6,1,4,325,11,0,3,6,...,2,0,0,14,3,0,4,0,0,0
104.1,3,0,2,0,1,3,325,0,0,9,...,0,2,0,14,0,4,1,0,1,0
111.0,11,0,0,1,5,5,19,298,10,3,...,0,1,0,11,0,2,4,0,0,0
128.0,3,1,0,0,0,0,1,0,379,2,...,0,0,1,2,2,0,0,0,0,0
129.0,12,4,3,0,0,1,7,0,6,304,...,0,0,0,6,0,4,2,0,0,0
146.0,0,0,1,1,3,1,8,4,0,2,...,2,4,0,0,9,5,2,0,0,0
147.0,7,4,2,0,0,4,0,6,0,0,...,0,4,0,10,20,3,0,0,0,0
150.0,10,3,6,0,0,1,5,0,5,15,...,0,1,0,15,27,1,2,0,0,0
151.0,6,4,2,0,0,2,1,6,8,10,...,0,0,0,7,32,3,2,0,0,0
153.0,19,7,6,0,1,1,1,2,0,6,...,0,1,0,4,17,0,4,0,0,0
154.0,3,2,6,0,0,3,0,5,0,0,...,0,2,0,17,0,0,1,0,0,0
161.0,5,5,5,1,0,3,10,3,2,3,...,294,0,1,13,13,1,5,0,2,0
169.0,3,8,5,0,1,0,7,5,1,7,...,0,276,0,9,20,2,3,0,0,0
185.9,11,1,7,1,0,2,19,6,11,11,...,0,2,237,16,8,3,14,0,0,0
197.0,17,3,0,0,1,2,10,3,13,5,...,0,1,0,248,13,2,9,0,2,0
212.9,5,3,2,1,2,3,29,1,0,0,...,2,1,1,20,266,2,7,0,0,0
217.0,10,4,5,1,1,11,14,4,1,12,...,0,2,0,0,16,253,8,0,0,0
239.2,0,0,0,0,3,2,0,0,0,0,...,0,0,0,0,0,0,395,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,1,0,0,0,0,2,0,0,0,0,...,0,0,0,1,1,3,1,0,383,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,399

In [70]:
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.852500,0.852500,0.147500,0.014001,0.706004,0.852500,0.772367,0.293996,0.147500,0.558837
1,7.1,0.767500,0.767500,0.232500,0.005964,0.836512,0.767500,0.800522,0.163488,0.232500,0.457411
2,18.9,0.810000,0.810000,0.190000,0.006458,0.832905,0.810000,0.821293,0.167095,0.190000,0.446862
3,32.1,0.850000,0.850000,0.150000,0.000899,0.974212,0.850000,0.907877,0.025788,0.150000,0.430675
4,41.0,0.875000,0.875000,0.125000,0.003289,0.913838,0.875000,0.893997,0.086162,0.125000,0.457950
5,98.9,0.812500,0.812500,0.187500,0.004777,0.871314,0.812500,0.840880,0.128686,0.187500,0.406547
6,104.1,0.812500,0.812500,0.187500,0.016813,0.655242,0.812500,0.725446,0.344758,0.187500,0.381297
7,111.0,0.745000,0.745000,0.255000,0.004975,0.856322,0.745000,0.796791,0.143678,0.255000,0.533315
8,128.0,0.947500,0.947500,0.052500,0.006557,0.851685,0.947500,0.897041,0.148315,0.052500,0.841120
9,129.0,0.760000,0.760000,0.240000,0.009803,0.754342,0.760000,0.757161,0.245658,0.240000,0.396241
10,146.0,0.785000,0.785000,0.215000,0.007838,0.798982,0.785000,0.791929,0.201018,0.215000,0.428374
11,147.0,0.770000,0.770000,0.230000,0.020760,0.592308,0.770000,0.669565,0.407692,0.230000,0.356164
12,150.0,0.682500,0.682500,0.317500,0.012151,0.689394,0.682500,0.685930,0.310606,0.317500,0.355510
13,151.0,0.602500,0.602500,0.397500,0.009509,0.715134,0.602500,0.654003,0.284866,0.397500,0.356331
14,153.0,0.755000,0.755000,0.245000,0.028843,0.504174,0.755000,0.604605,0.495826,0.245000,1.396011
15,154.0,0.765000,0.765000,0.235000,0.008920,0.772727,0.765000,0.768844,0.227273,0.235000,0.459355
16,161.0,0.735000,0.735000,0.265000,0.000700,0.976744,0.735000,0.838802,0.023256,0.265000,0.469379
17,169.0,0.690000,0.690000,0.310000,0.002195,0.926174,0.690000,0.790831,0.073826,0.310000,0.411236
18,185.9,0.592500,0.592500,0.407500,0.000300,0.987500,0.592500,0.740625,0.012500,0.407500,0.531660
19,197.0,0.620000,0.620000,0.380000,0.018068,0.574074,0.620000,0.596154,0.425926,0.380000,0.396248
20,212.9,0.665000,0.665000,0.335000,0.021143,0.551867,0.665000,0.603175,0.448133,0.335000,0.527639
21,217.0,0.632500,0.632500,0.367500,0.004083,0.860544,0.632500,0.729107,0.139456,0.367500,0.397774
22,239.2,0.987500,0.987500,0.012500,0.008035,0.829832,0.987500,0.901826,0.170168,0.012500,0.723783
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.957500,0.957500,0.042500,0.001697,0.957500,0.957500,0.957500,0.042500,0.042500,0.636463
25,251.0,0.997500,0.997500,0.002500,0.000100,0.997500,0.997500,0.997500,0.002500,0.002500,0.000000
26,average,0.787308,0.787308,0.212692,0.008380,0.807186,0.787308,0.790145,0.192814,0.212692,0.475238

In [71]:
cv_result5

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.697115  0.703898    0.302885  0.697115    0.710814
1       2.0  0.674038  0.686935    0.325962  0.674038    0.700334
2       3.0  0.689423  0.700639    0.310577  0.689423    0.712225
3       4.0  0.658654  0.665572    0.341346  0.658654    0.672636
4       5.0  0.669231  0.679866    0.330769  0.669231    0.690845
5       6.0  0.662500  0.674430    0.337500  0.662500    0.686798
6       7.0  0.679808  0.687575    0.320192  0.679808    0.695522
7       8.0  0.649038  0.664499    0.350962  0.649038    0.680714
8       9.0  0.707692  0.714535    0.292308  0.707692    0.721512
9      10.0  0.645192  0.650606    0.354808  0.645192    0.656110
10       11  0.787308  0.797123    0.212692  0.787308    0.807186
11  average  0.673269  0.682855    0.326731  0.673269    0.692751
12      max  0.707692  0.714535    0.292308  0.707692    0.721512

### SAVE MODEL dTOP5fi

In [72]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier5.pkl', 'wb') as f:
    pickle.dump(knn5, f)

## TRAIN knn TOP 10fi

In [73]:
# train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])

In [74]:
# Separate features and tp_ICD_cl0 variable for train_data10
X_train10 = train_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_train10 = train_data10['tp_ICD_cl0']

In [75]:
timer = CalculateTime(features=10, data_type='train')
timer.start()

knn10, data_top_5, Confusion_df10, eval_result10, cv_result10 = knn_custom_kfold_evaluation(X_train10, y_train10, le, feature=10, best_k=22)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.37 minutes

In [76]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.545455,251.0,0.318182,249.0,0.136364,NaN,NaN,NaN,NaN
2,41.0,32.1,0.272727,5.0,0.136364,197.0,0.136364,41.0,0.090909,248.0,0.090909
3,129.0,150.0,0.272727,41.0,0.090909,129.0,0.090909,151.0,0.090909,154.0,0.090909
4,169.0,5.0,0.454545,32.1,0.227273,98.9,0.181818,18.9,0.045455,169.0,0.045455
5,161.0,161.0,0.363636,41.0,0.272727,185.9,0.181818,169.0,0.090909,111.0,0.045455
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.409091,251.0,0.318182,249.0,0.272727,NaN,NaN,NaN,NaN
10397,153.0,5.0,0.181818,32.1,0.136364,111.0,0.136364,7.1,0.090909,146.0,0.090909
10398,169.0,161.0,0.227273,169.0,0.181818,41.0,0.136364,185.9,0.136364,147.0,0.090909
10399,249.0,248.0,0.363636,249.0,0.227273,251.0,0.227273,18.9,0.045455,41.0,0.045455
10400,150.0,197.0,0.227273,98.9,0.136364,153.0,0.136364,7.1,0.090909,146.0,0.090909

In [77]:
Confusion_df10

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,399,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,399,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,1,2,392,0,0,...,0,0,0,0,0,1,0,0,0,0
128.0,0,0,0,0,0,0,0,0,399,0,...,0,0,0,0,0,0,0,0,0,0
129.0,1,2,1,0,0,0,1,0,1,385,...,1,0,0,0,1,1,0,0,0,0
146.0,0,3,0,0,0,0,2,1,0,2,...,0,0,0,2,0,2,0,0,0,0
147.0,0,2,2,0,1,0,1,2,0,2,...,0,0,0,1,0,0,0,0,0,0
150.0,0,2,3,0,0,1,3,2,0,2,...,1,1,1,3,1,1,1,0,0,0
151.0,0,0,1,1,0,1,1,0,0,1,...,0,0,1,0,2,1,0,0,0,0
153.0,1,5,3,0,0,4,4,2,1,6,...,0,0,0,3,1,4,1,0,0,0
154.0,2,2,7,2,3,2,3,2,0,5,...,1,1,1,3,3,2,1,0,0,0
161.0,1,5,3,2,0,0,6,8,2,4,...,343,2,1,1,2,1,0,0,0,0
169.0,3,6,6,0,1,1,7,2,0,7,...,0,336,2,5,0,3,2,0,0,0
185.9,3,5,5,2,1,3,3,2,3,10,...,0,3,328,4,1,0,1,0,0,0
197.0,0,10,4,2,2,3,8,7,1,9,...,3,2,3,324,1,1,0,0,0,0
212.9,3,3,6,1,2,3,5,4,0,7,...,0,1,4,4,326,7,3,0,0,0
217.0,2,4,2,2,2,8,8,3,0,6,...,1,3,6,6,1,316,5,0,0,0
239.2,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,397,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,1,3,1,0,1,0,1,0,1,3,...,0,0,1,0,1,0,1,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [78]:
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001697,0.959233,1.000000,0.979192,0.040767,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.005173,0.884956,1.000000,0.938967,0.115044,0.000000,0.000000
2,18.9,0.997500,0.997500,0.002500,0.004381,0.900677,0.997500,0.946619,0.099323,0.002500,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.001298,0.968523,1.000000,0.984010,0.031477,0.000000,0.000000
5,98.9,0.997500,0.997500,0.002500,0.002693,0.936620,0.997500,0.966102,0.063380,0.002500,0.000000
6,104.1,0.997500,0.997500,0.002500,0.005569,0.876923,0.997500,0.933333,0.123077,0.002500,0.000000
7,111.0,0.980000,0.980000,0.020000,0.003488,0.918033,0.980000,0.948005,0.081967,0.020000,0.721012
8,128.0,0.997500,0.997500,0.002500,0.000899,0.977941,0.997500,0.987624,0.022059,0.002500,0.000000
9,129.0,0.962500,0.962500,0.037500,0.006458,0.855556,0.962500,0.905882,0.144444,0.037500,1.008738
10,146.0,0.947500,0.947500,0.052500,0.003587,0.913253,0.947500,0.930061,0.086747,0.052500,0.715269
11,147.0,0.957500,0.957500,0.042500,0.002991,0.927361,0.957500,0.942189,0.072639,0.042500,0.943807
12,150.0,0.930000,0.930000,0.070000,0.002892,0.927681,0.930000,0.928839,0.072319,0.070000,0.844806
13,151.0,0.965000,0.965000,0.035000,0.003587,0.914692,0.965000,0.939173,0.085308,0.035000,0.782031
14,153.0,0.872500,0.872500,0.127500,0.002593,0.930667,0.872500,0.900645,0.069333,0.127500,0.735483
15,154.0,0.862500,0.862500,0.137500,0.004480,0.884615,0.862500,0.873418,0.115385,0.137500,0.817022
16,161.0,0.857500,0.857500,0.142500,0.000700,0.980000,0.857500,0.914667,0.020000,0.142500,0.628950
17,169.0,0.840000,0.840000,0.160000,0.001298,0.962751,0.840000,0.897196,0.037249,0.160000,0.800817
18,185.9,0.820000,0.820000,0.180000,0.002096,0.939828,0.820000,0.875834,0.060172,0.180000,0.521961
19,197.0,0.810000,0.810000,0.190000,0.003190,0.910112,0.810000,0.857143,0.089888,0.190000,0.871427
20,212.9,0.815000,0.815000,0.185000,0.001398,0.958824,0.815000,0.881081,0.041176,0.185000,0.600423
21,217.0,0.790000,0.790000,0.210000,0.002394,0.929412,0.790000,0.854054,0.070588,0.210000,0.667792
22,239.2,0.992500,0.992500,0.007500,0.001498,0.963592,0.992500,0.977833,0.036408,0.007500,1.113859
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000000,1.000000,0.962500,0.980892,0.000000,0.037500,0.979130
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.936731,0.936731,0.063269,0.002521,0.938159,0.936731,0.935692,0.061841,0.063269,0.490482

In [79]:
cv_result10

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.709615  0.715793    0.290385  0.709615    0.722080
1       2.0  0.628846  0.627620    0.371154  0.628846    0.626399
2       3.0  0.706731  0.706455    0.293269  0.706731    0.706179
3       4.0  0.620192  0.620754    0.379808  0.620192    0.621317
4       5.0  0.707692  0.711253    0.292308  0.707692    0.714849
5       6.0  0.626923  0.626217    0.373077  0.626923    0.625512
6       7.0  0.718269  0.723760    0.281731  0.718269    0.729336
7       8.0  0.631731  0.631106    0.368269  0.631731    0.630483
8       9.0  0.716346  0.719583    0.283654  0.716346    0.722849
9      10.0  0.629808  0.627045    0.370192  0.629808    0.624306
10       11  0.936731  0.937444    0.063269  0.936731    0.938159
11  average  0.669615  0.670959    0.330385  0.669615    0.672331
12      max  0.718269  0.723760    0.281731  0.718269    0.729336

### SAVE MODEL dTOP10fi

In [80]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier10.pkl', 'wb') as f:
    pickle.dump(knn10, f)

## TRAIN knn TOP 20fi

In [81]:
# train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])

In [82]:
# Separate features and tp_ICD_cl0 variable for train_data20
X_train20 = train_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_train20 = train_data20['tp_ICD_cl0']

In [83]:
timer = CalculateTime(features=20, data_type='train')
timer.start()

knn20, data_top_5, Confusion_df20, eval_result20, cv_result20 = knn_custom_kfold_evaluation(X_train20, y_train20, le, feature=20, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.33 minutes

In [84]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.55,251.0,0.30,249.0,0.15,NaN,NaN,NaN,NaN
2,41.0,147.0,0.25,7.1,0.15,104.1,0.10,151.0,0.10,248.0,0.10
3,129.0,150.0,0.20,129.0,0.15,217.0,0.15,154.0,0.10,185.9,0.10
4,169.0,5.0,0.45,32.1,0.20,98.9,0.20,41.0,0.05,169.0,0.05
5,161.0,169.0,0.30,161.0,0.20,7.1,0.15,41.0,0.15,146.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.15,150.0,0.15,153.0,0.15,5.0,0.10,32.1,0.10
10398,169.0,169.0,0.25,161.0,0.20,7.1,0.15,41.0,0.15,146.0,0.10
10399,249.0,249.0,0.30,251.0,0.30,248.0,0.25,18.9,0.05,169.0,0.05
10400,150.0,98.9,0.30,197.0,0.25,153.0,0.15,7.1,0.10,32.1,0.05

In [85]:
Confusion_df20

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,399,0,1,...,0,0,0,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,1,0,0,0,397,...,0,1,0,0,0,0,0,0,0,0
146.0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
147.0,0,0,1,0,0,0,0,1,0,0,...,0,1,1,0,0,1,0,0,0,0
150.0,0,0,2,0,0,0,1,2,0,1,...,0,0,2,0,0,0,0,0,0,0
151.0,1,0,0,0,0,0,2,3,0,1,...,0,0,0,0,2,2,1,0,0,0
153.0,2,1,1,0,0,0,1,2,1,1,...,2,0,0,1,1,3,2,0,0,0
154.0,2,0,4,0,0,1,2,3,0,5,...,0,1,3,0,0,0,0,0,0,0
161.0,1,0,1,0,1,0,0,3,0,2,...,389,0,0,1,0,0,0,0,0,0
169.0,2,0,3,0,0,1,2,3,1,9,...,1,363,2,1,1,1,0,0,0,0
185.9,0,1,2,3,1,1,4,2,0,3,...,0,1,356,4,2,1,1,0,0,0
197.0,0,2,7,0,0,3,7,6,2,6,...,1,2,2,348,1,2,0,0,0,0
212.9,1,4,5,1,0,2,6,4,0,6,...,2,1,6,3,338,1,2,0,0,0
217.0,4,1,5,0,0,3,6,8,0,6,...,0,2,2,0,3,328,6,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,2,1,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [86]:
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001298,0.968523,1.000000,0.984010,0.031477,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003090,0.928074,1.000000,0.962696,0.071926,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.003289,0.923611,0.997500,0.959135,0.076389,0.002500,0.000000
7,111.0,0.997500,0.997500,0.002500,0.003786,0.913043,0.997500,0.953405,0.086957,0.002500,0.000000
8,128.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
9,129.0,0.992500,0.992500,0.007500,0.004083,0.906393,0.992500,0.947494,0.093607,0.007500,1.019913
10,146.0,0.995000,0.995000,0.005000,0.001199,0.970732,0.995000,0.982716,0.029268,0.005000,1.434694
11,147.0,0.985000,0.985000,0.015000,0.001099,0.972840,0.985000,0.978882,0.027160,0.015000,0.913143
12,150.0,0.972500,0.972500,0.027500,0.001996,0.951100,0.972500,0.961681,0.048900,0.027500,0.770246
13,151.0,0.962500,0.962500,0.037500,0.001398,0.964912,0.962500,0.963705,0.035088,0.037500,0.708925
14,153.0,0.937500,0.937500,0.062500,0.002096,0.946970,0.937500,0.942211,0.053030,0.062500,0.706719
15,154.0,0.930000,0.930000,0.070000,0.003190,0.920792,0.930000,0.925373,0.079208,0.070000,0.724650
16,161.0,0.972500,0.972500,0.027500,0.000600,0.984810,0.972500,0.978616,0.015190,0.027500,0.776805
17,169.0,0.907500,0.907500,0.092500,0.000999,0.973190,0.907500,0.939198,0.026810,0.092500,0.484197
18,185.9,0.890000,0.890000,0.110000,0.001896,0.949333,0.890000,0.918710,0.050667,0.110000,0.639864
19,197.0,0.870000,0.870000,0.130000,0.001199,0.966667,0.870000,0.915789,0.033333,0.130000,0.755677
20,212.9,0.845000,0.845000,0.155000,0.001099,0.968481,0.845000,0.902537,0.031519,0.155000,0.648263
21,217.0,0.820000,0.820000,0.180000,0.001099,0.967552,0.820000,0.887686,0.032448,0.180000,0.623581
22,239.2,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.654271
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963654,0.963654,0.036346,0.001450,0.964307,0.963654,0.963101,0.035693,0.036346,0.417729

In [87]:
cv_result20

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.734615  0.741084    0.265385  0.734615    0.747667
1       2.0  0.675962  0.675606    0.324038  0.675962    0.675251
2       3.0  0.756731  0.761911    0.243269  0.756731    0.767163
3       4.0  0.652885  0.655564    0.347115  0.652885    0.658265
4       5.0  0.743269  0.748749    0.256731  0.743269    0.754309
5       6.0  0.666346  0.664877    0.333654  0.666346    0.663414
6       7.0  0.764423  0.767099    0.235577  0.764423    0.769794
7       8.0  0.673077  0.673662    0.326923  0.673077    0.674248
8       9.0  0.767308  0.770461    0.232692  0.767308    0.773641
9      10.0  0.669231  0.670167    0.330769  0.669231    0.671106
10       11  0.963654  0.963980    0.036346  0.963654    0.964307
11  average  0.710385  0.712918    0.289615  0.710385    0.715486
12      max  0.767308  0.770461    0.232692  0.767308    0.773641

### SAVE MODEL dTOP20fi

In [88]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier20.pkl', 'wb') as f:
    pickle.dump(knn20, f)

## TRAIN knn TOP 30fi

In [89]:
# train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])

In [90]:
# Separate features and tp_ICD_cl0 variable for train_data30
X_train30 = train_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_train30 = train_data30['tp_ICD_cl0']

In [91]:
timer = CalculateTime(features=30, data_type='train')
timer.start()

knn30, data_top_5, Confusion_df30, eval_result30, cv_result30 = knn_custom_kfold_evaluation(X_train30, y_train30, le, feature=30, best_k=23)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.39 minutes

In [92]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.695652,251.0,0.304348,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.391304,248.0,0.173913,197.0,0.086957,7.1,0.043478,18.9,0.043478
3,129.0,129.0,0.173913,150.0,0.173913,217.0,0.130435,154.0,0.086957,185.9,0.086957
4,169.0,5.0,0.434783,32.1,0.260870,98.9,0.217391,169.0,0.086957,NaN,NaN
5,161.0,161.0,0.260870,169.0,0.217391,7.1,0.130435,41.0,0.130435,146.0,0.086957
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.478261,248.0,0.347826,249.0,0.173913,NaN,NaN,NaN,NaN
10397,153.0,32.1,0.173913,111.0,0.130435,153.0,0.130435,5.0,0.086957,41.0,0.086957
10398,169.0,161.0,0.260870,169.0,0.217391,7.1,0.130435,41.0,0.130435,146.0,0.086957
10399,249.0,248.0,0.304348,251.0,0.304348,249.0,0.260870,18.9,0.043478,169.0,0.043478
10400,150.0,98.9,0.304348,146.0,0.217391,151.0,0.130435,147.0,0.086957,185.9,0.086957

In [93]:
Confusion_df30

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,398,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
98.9,1,0,0,1,0,395,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
104.1,0,0,0,0,0,0,398,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,1,1,390,0,1,...,0,1,0,0,1,0,1,0,0,0
128.0,0,0,0,0,0,0,0,1,399,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,1,0,0,2,0,1,0,391,...,0,1,0,1,1,0,0,0,0,0
146.0,0,0,0,1,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
147.0,0,0,1,0,0,1,1,1,0,3,...,1,0,1,1,0,1,1,0,0,0
150.0,2,0,0,1,0,1,1,3,1,0,...,1,1,1,0,1,1,1,0,0,0
151.0,1,1,3,0,1,1,1,4,1,2,...,0,1,0,2,2,1,1,0,0,0
153.0,3,1,1,2,0,0,2,4,0,3,...,1,0,3,2,0,2,1,0,0,0
154.0,2,0,4,0,0,1,1,2,0,6,...,0,0,2,4,0,1,0,0,0,0
161.0,0,2,1,0,0,2,3,2,0,1,...,380,0,0,2,0,0,1,0,0,0
169.0,2,0,7,0,1,1,4,3,1,12,...,0,343,3,1,2,2,1,0,0,0
185.9,1,0,4,2,0,0,5,2,0,5,...,0,2,357,3,1,1,1,0,0,0
197.0,1,2,4,1,3,2,6,5,3,10,...,2,1,2,340,1,2,0,0,0,0
212.9,1,2,4,4,0,0,4,4,0,11,...,1,0,3,4,334,1,4,0,0,0
217.0,2,0,7,0,0,2,4,7,0,11,...,0,1,3,1,3,333,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,4,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [94]:
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001597,0.961538,1.000000,0.980392,0.038462,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003686,0.915332,1.000000,0.955795,0.084668,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
4,41.0,0.995000,0.995000,0.005000,0.000500,0.987593,0.995000,0.991283,0.012407,0.005000,1.252740
5,98.9,0.987500,0.987500,0.012500,0.001398,0.965770,0.987500,0.976514,0.034230,0.012500,1.433844
6,104.1,0.995000,0.995000,0.005000,0.003786,0.912844,0.995000,0.952153,0.087156,0.005000,1.386662
7,111.0,0.975000,0.975000,0.025000,0.004083,0.904872,0.975000,0.938628,0.095128,0.025000,0.637427
8,128.0,0.997500,0.997500,0.002500,0.000600,0.985185,0.997500,0.991304,0.014815,0.002500,0.000000
9,129.0,0.977500,0.977500,0.022500,0.006458,0.857456,0.977500,0.913551,0.142544,0.022500,0.791431
10,146.0,0.975000,0.975000,0.025000,0.001697,0.958231,0.975000,0.966543,0.041769,0.025000,0.667771
11,147.0,0.955000,0.955000,0.045000,0.001697,0.957393,0.955000,0.956195,0.042607,0.045000,0.635900
12,150.0,0.945000,0.945000,0.055000,0.003388,0.917476,0.945000,0.931034,0.082524,0.055000,0.913352
13,151.0,0.935000,0.935000,0.065000,0.001896,0.951654,0.935000,0.943253,0.048346,0.065000,0.779721
14,153.0,0.920000,0.920000,0.080000,0.002693,0.931646,0.920000,0.925786,0.068354,0.080000,0.904725
15,154.0,0.922500,0.922500,0.077500,0.003388,0.915633,0.922500,0.919054,0.084367,0.077500,0.622513
16,161.0,0.950000,0.950000,0.050000,0.000600,0.984456,0.950000,0.966921,0.015544,0.050000,0.559646
17,169.0,0.857500,0.857500,0.142500,0.000999,0.971671,0.857500,0.911023,0.028329,0.142500,0.475903
18,185.9,0.892500,0.892500,0.107500,0.001797,0.952000,0.892500,0.921290,0.048000,0.107500,0.718642
19,197.0,0.850000,0.850000,0.150000,0.002295,0.936639,0.850000,0.891219,0.063361,0.150000,0.497424
20,212.9,0.835000,0.835000,0.165000,0.001298,0.962536,0.835000,0.894244,0.037464,0.165000,0.478716
21,217.0,0.832500,0.832500,0.167500,0.001199,0.965217,0.832500,0.893960,0.034783,0.167500,0.508863
22,239.2,1.000000,1.000000,0.000000,0.001697,0.959233,1.000000,0.979192,0.040767,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.554048
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.952981,0.952981,0.047019,0.001875,0.954063,0.952981,0.952483,0.045937,0.047019,0.531513

In [95]:
cv_result30

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.740385  0.747563    0.259615  0.740385    0.754881
1       2.0  0.684615  0.685672    0.315385  0.684615    0.686731
2       3.0  0.764423  0.768258    0.235577  0.764423    0.772133
3       4.0  0.657692  0.659756    0.342308  0.657692    0.661832
4       5.0  0.750962  0.758923    0.249038  0.750962    0.767054
5       6.0  0.683654  0.682437    0.316346  0.683654    0.681224
6       7.0  0.771154  0.775946    0.228846  0.771154    0.780798
7       8.0  0.667308  0.668780    0.332692  0.667308    0.670260
8       9.0  0.771154  0.773421    0.228846  0.771154    0.775701
9      10.0  0.665385  0.666868    0.334615  0.665385    0.668359
10       11  0.952981  0.953522    0.047019  0.952981    0.954063
11  average  0.715673  0.718762    0.284327  0.715673    0.721897
12      max  0.771154  0.775946    0.228846  0.771154    0.780798

### SAVE MODEL dTOP30fi

In [96]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier30.pkl', 'wb') as f:
    pickle.dump(knn30, f)

## TRAIN knn TOP 40fi

In [97]:
# train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])

In [98]:
# Separate features and tp_ICD_cl0 variable for train_data40
X_train40 = train_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_train40 = train_data40['tp_ICD_cl0']

In [99]:
timer = CalculateTime(features=40, data_type='train')
timer.start()

knn40, data_top_5, Confusion_df40, eval_result40, cv_result40 = knn_custom_kfold_evaluation(X_train40, y_train40, le, feature=40, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.33 minutes

In [100]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.571429,251.0,0.428571,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.476190,111.0,0.142857,5.0,0.095238,32.1,0.095238,41.0,0.047619
10398,169.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.333333,248.0,0.285714,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.380952,146.0,0.142857,147.0,0.095238,151.0,0.095238,154.0,0.095238

In [101]:
Confusion_df40

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,399,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,1,0,0,0,0,0,396,0,0,0,...,0,0,1,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,395,0,1,...,0,0,0,0,1,0,1,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,1,1,0,0,395,...,0,0,0,0,0,0,1,0,0,0
146.0,1,0,0,0,0,0,1,3,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,0,0,2,...,0,0,2,0,0,1,1,0,0,0
150.0,1,0,1,0,1,0,1,1,1,0,...,1,1,1,0,0,0,0,0,0,0
151.0,1,0,2,0,1,1,1,3,1,1,...,0,0,0,2,2,2,0,0,0,0
153.0,4,0,2,0,0,1,1,2,0,3,...,0,1,0,2,0,3,1,0,0,0
154.0,1,0,1,0,2,1,1,2,1,4,...,0,0,2,1,0,1,0,0,0,0
161.0,0,1,0,0,1,1,1,2,0,2,...,388,0,0,1,0,0,2,0,0,0
169.0,1,0,8,1,3,2,2,1,0,10,...,1,352,3,3,0,3,1,0,0,0
185.9,0,0,3,2,0,2,3,1,0,2,...,0,2,365,3,0,0,0,0,0,0
197.0,2,2,5,1,1,3,5,3,1,5,...,2,2,3,345,0,2,0,0,0,0
212.9,1,1,3,4,2,3,5,5,0,8,...,0,0,2,3,335,1,5,0,0,0
217.0,2,0,10,1,0,4,1,4,2,10,...,1,2,3,0,2,329,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,1,0,2,0,0,0,...,0,0,0,2,1,0,0,0,391,1
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [102]:
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003488,0.919540,1.000000,0.958084,0.080460,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
5,98.9,0.997500,0.997500,0.002500,0.001896,0.954545,0.997500,0.975550,0.045455,0.002500,0.000000
6,104.1,0.990000,0.990000,0.010000,0.002494,0.940618,0.990000,0.964677,0.059382,0.010000,1.489715
7,111.0,0.987500,0.987500,0.012500,0.002792,0.933806,0.987500,0.959903,0.066194,0.012500,0.724240
8,128.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
9,129.0,0.987500,0.987500,0.012500,0.004876,0.889640,0.987500,0.936019,0.110360,0.012500,0.884120
10,146.0,0.982500,0.982500,0.017500,0.002096,0.949275,0.982500,0.965602,0.050725,0.017500,0.749347
11,147.0,0.980000,0.980000,0.020000,0.001597,0.960784,0.980000,0.970297,0.039216,0.020000,0.575126
12,150.0,0.965000,0.965000,0.035000,0.002494,0.939173,0.965000,0.951911,0.060827,0.035000,0.998945
13,151.0,0.950000,0.950000,0.050000,0.001498,0.962025,0.950000,0.955975,0.037975,0.050000,0.809050
14,153.0,0.940000,0.940000,0.060000,0.001996,0.949495,0.940000,0.944724,0.050505,0.060000,1.122379
15,154.0,0.942500,0.942500,0.057500,0.002394,0.940150,0.942500,0.941323,0.059850,0.057500,0.703046
16,161.0,0.970000,0.970000,0.030000,0.000500,0.987277,0.970000,0.978562,0.012723,0.030000,0.779816
17,169.0,0.880000,0.880000,0.120000,0.000799,0.977778,0.880000,0.926316,0.022222,0.120000,0.555215
18,185.9,0.912500,0.912500,0.087500,0.001697,0.955497,0.912500,0.933504,0.044503,0.087500,0.646425
19,197.0,0.862500,0.862500,0.137500,0.001697,0.953039,0.862500,0.905512,0.046961,0.137500,0.729927
20,212.9,0.837500,0.837500,0.162500,0.000600,0.982405,0.837500,0.904184,0.017595,0.162500,0.580159
21,217.0,0.822500,0.822500,0.177500,0.001298,0.961988,0.822500,0.886792,0.038012,0.177500,0.683956
22,239.2,1.000000,1.000000,0.000000,0.001597,0.961538,1.000000,0.980392,0.038462,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.977500,0.977500,0.022500,0.000000,1.000000,0.977500,0.988622,0.000000,0.022500,0.672134
25,251.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
26,average,0.960962,0.960962,0.039038,0.001558,0.961697,0.960962,0.960384,0.038303,0.039038,0.488600

In [103]:
cv_result40

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.748077  0.755154    0.251923  0.748077    0.762367
1       2.0  0.679808  0.680758    0.320192  0.679808    0.681712
2       3.0  0.760577  0.763256    0.239423  0.760577    0.765954
3       4.0  0.661538  0.664466    0.338462  0.661538    0.667419
4       5.0  0.762500  0.768040    0.237500  0.762500    0.773661
5       6.0  0.682692  0.681699    0.317308  0.682692    0.680709
6       7.0  0.782692  0.783690    0.217308  0.782692    0.784690
7       8.0  0.685577  0.687445    0.314423  0.685577    0.689322
8       9.0  0.782692  0.785910    0.217308  0.782692    0.789154
9      10.0  0.670192  0.671533    0.329808  0.670192    0.672880
10       11  0.960962  0.961329    0.039038  0.960962    0.961697
11  average  0.721635  0.724195    0.278365  0.721635    0.726787
12      max  0.782692  0.783690    0.217308  0.782692    0.784690

### SAVE MODEL dTOP40fi

In [104]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier40.pkl', 'wb') as f:
    pickle.dump(knn40, f)

## TRAIN knn TOP 50fi

In [105]:
# train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])

In [106]:
# Separate features and tp_ICD_cl0 variable for train_data50
X_train50 = train_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_train50 = train_data50['tp_ICD_cl0']

In [107]:
timer = CalculateTime(features=50, data_type='train')
timer.start()

knn50, data_top_5, Confusion_df50, eval_result50, cv_result50 = knn_custom_kfold_evaluation(X_train50, y_train50, le, feature=50, best_k=160)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.38 minutes

In [108]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.27500,251.0,0.23750,249.0,0.12500,NaN,NaN,NaN,NaN
2,41.0,251.0,0.18750,249.0,0.16875,248.0,0.16250,5.0,0.15000,32.1,0.10625
3,129.0,129.0,0.11250,111.0,0.10000,104.1,0.08750,154.0,0.08750,150.0,0.07500
4,169.0,5.0,0.36875,32.1,0.27500,7.1,0.05625,98.9,0.05000,169.0,0.05000
5,161.0,161.0,0.29375,41.0,0.21250,7.1,0.13125,169.0,0.13125,151.0,0.04375
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.36875,251.0,0.36250,249.0,0.26875,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.15000,111.0,0.09375,197.0,0.07500,154.0,0.06250,18.9,0.05625
10398,169.0,161.0,0.30625,41.0,0.21250,7.1,0.12500,169.0,0.11250,151.0,0.05625
10399,249.0,5.0,0.22500,251.0,0.19375,249.0,0.18125,248.0,0.16875,32.1,0.09375
10400,150.0,98.9,0.12500,146.0,0.09375,5.0,0.08750,18.9,0.07500,151.0,0.06875

In [109]:
Confusion_df50

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,274,0,7,5,5,0,2,0,0,26,...,11,0,1,5,0,0,26,0,0,0
7.1,1,254,7,5,7,5,1,6,2,19,...,9,0,0,7,0,0,28,1,3,3
18.9,2,0,337,2,8,2,1,5,0,5,...,10,0,2,2,0,1,10,0,1,2
32.1,0,0,8,331,0,0,1,3,3,15,...,4,0,3,1,0,0,10,0,0,0
41.0,3,2,4,8,327,1,0,3,0,10,...,0,0,0,1,0,0,24,0,0,2
98.9,2,2,6,3,4,261,1,12,2,26,...,9,0,4,4,0,2,9,0,0,1
104.1,1,3,4,1,5,0,278,4,14,22,...,23,0,0,1,0,2,11,0,0,0
111.0,2,3,2,1,0,0,2,320,3,6,...,10,0,1,6,0,2,13,0,0,0
128.0,0,1,1,0,0,0,5,5,350,7,...,0,0,5,0,0,0,8,0,0,0
129.0,2,0,0,0,2,0,1,0,0,382,...,7,0,0,0,0,0,4,0,0,0
146.0,0,4,5,4,3,2,3,11,13,28,...,6,0,8,2,0,1,13,0,0,0
147.0,0,2,11,1,5,3,0,12,1,25,...,19,0,2,1,0,0,8,0,0,0
150.0,0,0,6,0,3,4,6,3,2,7,...,8,0,2,10,0,0,9,0,0,0
151.0,2,4,5,0,2,0,0,4,2,13,...,4,0,6,3,0,0,13,0,0,0
153.0,0,0,3,1,0,1,1,3,1,15,...,7,0,2,0,0,0,15,0,0,0
154.0,0,0,3,2,1,1,2,5,0,6,...,2,1,2,3,0,1,4,0,0,0
161.0,0,5,3,4,0,0,0,1,0,9,...,339,0,4,0,0,0,23,0,0,1
169.0,2,5,7,4,1,0,1,10,0,32,...,8,245,5,7,0,2,20,0,0,0
185.9,1,2,5,10,2,1,1,7,11,19,...,13,0,262,4,0,0,9,0,1,0
197.0,1,0,9,4,4,1,0,0,2,16,...,7,0,2,314,1,2,16,0,1,1
212.9,0,1,4,0,3,3,0,11,3,15,...,12,0,4,1,297,0,17,0,0,0
217.0,1,2,0,8,0,3,0,2,4,10,...,11,0,1,8,0,300,15,1,0,1
239.2,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,3,0,0,0,...,0,0,0,3,0,1,1,0,382,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,399

In [110]:
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.685000,0.685000,0.315000,0.001996,0.931973,0.685000,0.789625,0.068027,0.315000,0.448634
1,7.1,0.635000,0.635000,0.365000,0.003587,0.875862,0.635000,0.736232,0.124138,0.365000,0.346098
2,18.9,0.842500,0.842500,0.157500,0.009901,0.771167,0.842500,0.805257,0.228833,0.157500,0.460614
3,32.1,0.827500,0.827500,0.172500,0.006261,0.840102,0.827500,0.833753,0.159898,0.172500,0.464070
4,41.0,0.817500,0.817500,0.182500,0.005668,0.851562,0.817500,0.834184,0.148438,0.182500,0.345707
5,98.9,0.652500,0.652500,0.347500,0.002693,0.906250,0.652500,0.758721,0.093750,0.347500,0.458208
6,104.1,0.695000,0.695000,0.305000,0.003090,0.899676,0.695000,0.784203,0.100324,0.305000,0.437109
7,111.0,0.800000,0.800000,0.200000,0.010587,0.749415,0.800000,0.773881,0.250585,0.200000,0.372864
8,128.0,0.875000,0.875000,0.125000,0.006261,0.847458,0.875000,0.861009,0.152542,0.125000,0.464719
9,129.0,0.955000,0.955000,0.045000,0.032039,0.535764,0.955000,0.686433,0.464236,0.045000,0.428185
10,146.0,0.685000,0.685000,0.315000,0.002494,0.916388,0.685000,0.783977,0.083612,0.315000,0.458164
11,147.0,0.742500,0.742500,0.257500,0.015069,0.660000,0.742500,0.698824,0.340000,0.257500,0.458478
12,150.0,0.767500,0.767500,0.232500,0.006359,0.827493,0.767500,0.796368,0.172507,0.232500,0.422932
13,151.0,0.782500,0.782500,0.217500,0.004480,0.874302,0.782500,0.825858,0.125698,0.217500,0.391422
14,153.0,0.857500,0.857500,0.142500,0.009116,0.788506,0.857500,0.821557,0.211494,0.142500,0.448992
15,154.0,0.857500,0.857500,0.142500,0.020952,0.615799,0.857500,0.716823,0.384201,0.142500,0.429235
16,161.0,0.847500,0.847500,0.152500,0.017682,0.653179,0.847500,0.737758,0.346821,0.152500,0.345704
17,169.0,0.612500,0.612500,0.387500,0.000100,0.995935,0.612500,0.758514,0.004065,0.387500,0.458153
18,185.9,0.655000,0.655000,0.345000,0.005371,0.829114,0.655000,0.731844,0.170886,0.345000,0.405673
19,197.0,0.785000,0.785000,0.215000,0.006853,0.819843,0.785000,0.802043,0.180157,0.215000,0.451250
20,212.9,0.742500,0.742500,0.257500,0.000100,0.996644,0.742500,0.851003,0.003356,0.257500,0.392932
21,217.0,0.750000,0.750000,0.250000,0.001398,0.955414,0.750000,0.840336,0.044586,0.250000,0.423869
22,239.2,0.995000,0.995000,0.005000,0.029786,0.564539,0.995000,0.720362,0.435461,0.005000,1.055629
23,248.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
24,249.0,0.955000,0.955000,0.045000,0.000600,0.984536,0.955000,0.969543,0.015464,0.045000,0.454022
25,251.0,0.997500,0.997500,0.002500,0.001099,0.973171,0.997500,0.985185,0.026829,0.002500,0.000000
26,average,0.800673,0.800673,0.199327,0.007836,0.833043,0.800673,0.803877,0.166957,0.199327,0.416256

In [111]:
cv_result50

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.749038  0.775990    0.250962  0.749038    0.804953
1       2.0  0.728846  0.734800    0.271154  0.728846    0.740851
2       3.0  0.741346  0.772853    0.258654  0.741346    0.807157
3       4.0  0.708654  0.718016    0.291346  0.708654    0.727628
4       5.0  0.733654  0.754638    0.266346  0.733654    0.776857
5       6.0  0.734615  0.737955    0.265385  0.734615    0.741325
6       7.0  0.767308  0.785987    0.232692  0.767308    0.805597
7       8.0  0.717308  0.724555    0.282692  0.717308    0.731950
8       9.0  0.765385  0.789623    0.234615  0.765385    0.815447
9      10.0  0.704808  0.712919    0.295192  0.704808    0.721218
10       11  0.800673  0.816537    0.199327  0.800673    0.833043
11  average  0.735096  0.750733    0.264904  0.735096    0.767298
12      max  0.767308  0.785987    0.232692  0.767308    0.805597

### SAVE MODEL dTOP50fi

In [112]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier50.pkl', 'wb') as f:
    pickle.dump(knn50, f)

## TRAIN knn TOP 60fi

In [113]:
# train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])

In [114]:
# Separate features and tp_ICD_cl0 variable for train_data50
X_train60 = train_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_train60 = train_data60['tp_ICD_cl0']

In [115]:
timer = CalculateTime(features=60, data_type='train')
timer.start()

knn60, data_top_5, Confusion_df60, eval_result60, cv_result60 = knn_custom_kfold_evaluation(X_train60, y_train60, le, feature=60, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.34 minutes

In [116]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.285714,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.523810,248.0,0.333333,249.0,0.142857,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.428571,32.1,0.142857,111.0,0.142857,5.0,0.095238,41.0,0.047619
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,249.0,0.285714,248.0,0.190476,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.333333,151.0,0.142857,146.0,0.095238,147.0,0.095238,185.9,0.095238

In [117]:
Confusion_df60

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,397,0,0,0,...,0,0,1,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,394,0,1,...,2,0,0,0,1,0,1,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,1,0,0,0,397,...,0,0,1,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,1,0,0,0,1,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,1,1,1,1,1,1,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,2,1,0,0,2,4,1,1,...,1,0,0,1,2,1,1,0,0,0
153.0,3,1,1,0,0,2,1,3,0,3,...,0,1,0,2,0,2,0,0,0,0
154.0,0,0,0,0,0,2,0,5,0,2,...,0,0,2,4,0,1,0,0,0,0
161.0,0,1,0,1,0,1,1,2,0,2,...,389,0,0,1,0,0,1,0,0,0
169.0,2,0,5,1,2,1,3,1,0,8,...,0,356,3,3,1,3,1,0,0,0
185.9,0,0,3,2,1,2,1,2,0,4,...,0,2,362,3,0,0,0,0,0,0
197.0,1,2,5,2,1,2,5,1,1,5,...,1,2,2,348,0,3,1,0,0,0
212.9,0,1,5,5,1,4,5,2,0,7,...,1,0,4,2,341,1,2,0,0,0
217.0,1,1,10,0,0,4,2,4,1,12,...,0,1,3,0,2,333,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [118]:
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003289,0.923788,1.000000,0.960384,0.076212,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001398,0.966184,1.000000,0.982801,0.033816,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
6,104.1,0.992500,0.992500,0.007500,0.002394,0.942993,0.992500,0.967113,0.057007,0.007500,0.735272
7,111.0,0.985000,0.985000,0.015000,0.002693,0.935867,0.985000,0.959805,0.064133,0.015000,0.539790
8,128.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
9,129.0,0.992500,0.992500,0.007500,0.004678,0.894144,0.992500,0.940758,0.105856,0.007500,1.028235
10,146.0,0.985000,0.985000,0.015000,0.001797,0.956311,0.985000,0.970443,0.043689,0.015000,0.797112
11,147.0,0.975000,0.975000,0.025000,0.001398,0.965347,0.975000,0.970149,0.034653,0.025000,0.801606
12,150.0,0.967500,0.967500,0.032500,0.002295,0.943902,0.967500,0.955556,0.056098,0.032500,0.903009
13,151.0,0.947500,0.947500,0.052500,0.001697,0.957071,0.947500,0.952261,0.042929,0.052500,0.727714
14,153.0,0.937500,0.937500,0.062500,0.002096,0.946970,0.937500,0.942211,0.053030,0.062500,1.007326
15,154.0,0.945000,0.945000,0.055000,0.002593,0.935644,0.945000,0.940299,0.064356,0.055000,0.551465
16,161.0,0.972500,0.972500,0.027500,0.000500,0.987310,0.972500,0.979849,0.012690,0.027500,0.837941
17,169.0,0.890000,0.890000,0.110000,0.000700,0.980716,0.890000,0.933159,0.019284,0.110000,0.547332
18,185.9,0.905000,0.905000,0.095000,0.001697,0.955145,0.905000,0.929397,0.044855,0.095000,0.646134
19,197.0,0.870000,0.870000,0.130000,0.001797,0.950820,0.870000,0.908616,0.049180,0.130000,0.701466
20,212.9,0.852500,0.852500,0.147500,0.000799,0.977077,0.852500,0.910547,0.022923,0.147500,0.663760
21,217.0,0.832500,0.832500,0.167500,0.001298,0.962428,0.832500,0.892761,0.037572,0.167500,0.551960
22,239.2,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.962692,0.962692,0.037308,0.001489,0.963308,0.962692,0.962196,0.036692,0.037308,0.450921

In [119]:
cv_result60

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.750000  0.755040    0.250000  0.750000    0.760149
1       2.0  0.683654  0.684802    0.316346  0.683654    0.685954
2       3.0  0.764423  0.767788    0.235577  0.764423    0.771182
3       4.0  0.653846  0.656420    0.346154  0.653846    0.659015
4       5.0  0.770192  0.775709    0.229808  0.770192    0.781305
5       6.0  0.697115  0.695616    0.302885  0.697115    0.694123
6       7.0  0.788462  0.791148    0.211538  0.788462    0.793852
7       8.0  0.687500  0.688729    0.312500  0.687500    0.689962
8       9.0  0.778846  0.780608    0.221154  0.778846    0.782378
9      10.0  0.675000  0.675935    0.325000  0.675000    0.676872
10       11  0.962692  0.963000    0.037308  0.962692    0.963308
11  average  0.724904  0.727179    0.275096  0.724904    0.729479
12      max  0.788462  0.791148    0.211538  0.788462    0.793852

### SAVE MODEL dTOP60fi

In [120]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier60.pkl', 'wb') as f:
    pickle.dump(knn60, f)

## TRAIN knn TOP 70fi

In [121]:
# train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])

In [122]:
# Separate features and tp_ICD_cl0 variable for train_data70
X_train70 = train_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_train70 = train_data70['tp_ICD_cl0']

In [123]:
timer = CalculateTime(features=70, data_type='train')
timer.start()

knn70, data_top_5, Confusion_df70, eval_result70, cv_result70 = knn_custom_kfold_evaluation(X_train70, y_train70, le, feature=70, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.37 minutes

In [124]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.380952,32.1,0.142857,111.0,0.142857,5.0,0.095238,41.0,0.047619
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.428571,249.0,0.238095,248.0,0.190476,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,151.0,0.142857,104.1,0.095238,146.0,0.095238,147.0,0.095238

In [125]:
Confusion_df70

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,398,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,396,0,1,...,1,0,0,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,399,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,1,0,1,...,0,0,1,0,0,0,0,0,0,0
147.0,1,0,0,0,0,1,0,1,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,1,1,1,1,1,2,1,0,...,0,0,1,0,0,1,0,0,0,0
151.0,1,0,1,1,0,0,2,3,1,1,...,1,0,0,1,2,3,1,0,0,0
153.0,2,0,1,0,0,3,1,3,0,1,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,0,0,0,3,0,4,0,4,...,0,1,2,2,0,1,0,0,0,0
161.0,0,1,0,0,0,1,3,1,0,3,...,387,0,0,1,0,0,1,0,0,0
169.0,2,0,7,1,2,2,3,3,0,7,...,1,352,3,3,1,2,1,0,0,0
185.9,0,0,4,1,1,2,1,1,0,4,...,1,2,362,3,0,0,0,0,0,0
197.0,2,2,7,2,2,3,5,2,1,5,...,1,3,2,344,0,2,0,0,0,0
212.9,3,1,5,4,0,4,7,3,0,8,...,1,0,2,2,336,1,2,0,0,0
217.0,2,0,10,0,1,3,3,4,1,12,...,1,1,2,0,2,332,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [126]:
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001298,0.968523,1.000000,0.984010,0.031477,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003686,0.915332,1.000000,0.955795,0.084668,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000700,0.982801,1.000000,0.991326,0.017199,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002295,0.945626,1.000000,0.972053,0.054374,0.000000,0.000000
6,104.1,0.995000,0.995000,0.005000,0.002892,0.932084,0.995000,0.962515,0.067916,0.005000,1.386662
7,111.0,0.990000,0.990000,0.010000,0.002792,0.933962,0.990000,0.961165,0.066038,0.010000,0.725025
8,128.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
9,129.0,0.997500,0.997500,0.002500,0.004876,0.890625,0.997500,0.941038,0.109375,0.002500,0.000000
10,146.0,0.985000,0.985000,0.015000,0.002096,0.949398,0.985000,0.966871,0.050602,0.015000,1.005041
11,147.0,0.967500,0.967500,0.032500,0.001498,0.962687,0.967500,0.965087,0.037313,0.032500,0.901421
12,150.0,0.965000,0.965000,0.035000,0.001896,0.953086,0.965000,0.959006,0.046914,0.035000,0.852210
13,151.0,0.945000,0.945000,0.055000,0.001797,0.954545,0.945000,0.949749,0.045455,0.055000,0.737486
14,153.0,0.947500,0.947500,0.052500,0.001896,0.952261,0.947500,0.949875,0.047739,0.052500,0.730817
15,154.0,0.950000,0.950000,0.050000,0.002494,0.938272,0.950000,0.944099,0.061728,0.050000,0.613106
16,161.0,0.967500,0.967500,0.032500,0.000700,0.982234,0.967500,0.974811,0.017766,0.032500,0.682374
17,169.0,0.880000,0.880000,0.120000,0.000899,0.975069,0.880000,0.925099,0.024931,0.120000,0.733489
18,185.9,0.905000,0.905000,0.095000,0.001398,0.962766,0.905000,0.932990,0.037234,0.095000,0.672035
19,197.0,0.860000,0.860000,0.140000,0.001498,0.958217,0.860000,0.906456,0.041783,0.140000,0.774509
20,212.9,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.626100
21,217.0,0.830000,0.830000,0.170000,0.001398,0.959538,0.830000,0.890080,0.040462,0.170000,0.552158
22,239.2,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.961731,0.961731,0.038269,0.001527,0.962508,0.961731,0.961173,0.037492,0.038269,0.449086

In [127]:
cv_result70

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.748077  0.753359    0.251923  0.748077    0.758716
1       2.0  0.683654  0.684831    0.316346  0.683654    0.686012
2       3.0  0.767308  0.771043    0.232692  0.767308    0.774816
3       4.0  0.655769  0.657378    0.344231  0.655769    0.658994
4       5.0  0.764423  0.771272    0.235577  0.764423    0.778244
5       6.0  0.698077  0.696023    0.301923  0.698077    0.693981
6       7.0  0.791346  0.794141    0.208654  0.791346    0.796956
7       8.0  0.685577  0.686965    0.314423  0.685577    0.688359
8       9.0  0.780769  0.782870    0.219231  0.780769    0.784982
9      10.0  0.675000  0.675226    0.325000  0.675000    0.675453
10       11  0.961731  0.962119    0.038269  0.961731    0.962508
11  average  0.725000  0.727311    0.275000  0.725000    0.729651
12      max  0.791346  0.794141    0.208654  0.791346    0.796956

### SAVE MODEL dTOP70fi

In [128]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier70.pkl', 'wb') as f:
    pickle.dump(knn70, f)

## TRAIN knn TOP 80fi

In [129]:
# train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])

In [130]:
# Separate features and tp_ICD_cl0 variable for train_data80
X_train80 = train_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_train80 = train_data80['tp_ICD_cl0']

In [131]:
timer = CalculateTime(features=80, data_type='train')
timer.start()

knn80, data_top_5, Confusion_df80, eval_result80, cv_result80 = knn_custom_kfold_evaluation(X_train80, y_train80, le, feature=80, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.34 minutes

In [132]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.60,251.0,0.40,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.40,248.0,0.20,197.0,0.10,7.1,0.05,18.9,0.05
3,129.0,129.0,0.20,150.0,0.20,217.0,0.15,154.0,0.10,185.9,0.10
4,169.0,5.0,0.45,32.1,0.30,98.9,0.15,169.0,0.10,NaN,NaN
5,161.0,161.0,0.25,169.0,0.25,7.1,0.15,41.0,0.15,146.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.30,32.1,0.15,111.0,0.15,5.0,0.10,217.0,0.10
10398,169.0,161.0,0.25,169.0,0.20,7.1,0.15,41.0,0.15,146.0,0.10
10399,249.0,249.0,0.35,251.0,0.30,248.0,0.20,18.9,0.05,169.0,0.05
10400,150.0,98.9,0.25,146.0,0.15,151.0,0.15,147.0,0.10,185.9,0.10

In [133]:
Confusion_df80

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,400,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,1,0,0,397,0,1,...,0,0,0,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,399,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,0,0,0,1,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,1,0,2,...,0,0,0,0,0,0,1,0,0,0
150.0,0,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,2,0,0,0,0
151.0,1,0,1,1,1,0,0,2,0,0,...,0,0,0,0,1,1,0,0,0,0
153.0,2,0,0,0,0,1,2,3,0,1,...,0,0,0,1,0,3,0,0,0,0
154.0,0,0,1,0,0,2,0,2,0,3,...,0,0,5,1,0,1,0,0,0,0
161.0,0,0,1,0,0,1,1,1,0,1,...,391,0,1,0,0,0,1,0,0,0
169.0,1,0,5,1,1,1,3,2,0,7,...,0,365,2,2,0,1,1,0,0,0
185.9,1,0,3,1,0,2,1,1,0,3,...,1,2,367,3,0,1,0,0,0,0
197.0,1,1,5,3,0,3,3,2,1,4,...,1,3,2,355,0,2,0,0,0,0
212.9,3,1,5,2,0,4,2,6,0,10,...,0,0,1,2,344,1,1,0,0,0
217.0,3,0,10,0,1,3,3,3,1,9,...,1,1,1,1,2,335,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,393,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [134]:
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003190,0.925926,1.000000,0.961538,0.074074,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.001797,0.956938,1.000000,0.977995,0.043062,0.000000,0.000000
6,104.1,1.000000,1.000000,0.000000,0.001797,0.956938,1.000000,0.977995,0.043062,0.000000,0.000000
7,111.0,0.992500,0.992500,0.007500,0.002593,0.938534,0.992500,0.964763,0.061466,0.007500,1.086976
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.997500,0.997500,0.002500,0.004083,0.906818,0.997500,0.950000,0.093182,0.002500,0.000000
10,146.0,0.990000,0.990000,0.010000,0.001697,0.958838,0.990000,0.974170,0.041162,0.010000,0.744183
11,147.0,0.985000,0.985000,0.015000,0.000999,0.975248,0.985000,0.980100,0.024752,0.015000,0.635542
12,150.0,0.985000,0.985000,0.015000,0.001996,0.951691,0.985000,0.968059,0.048309,0.015000,0.663678
13,151.0,0.972500,0.972500,0.027500,0.001099,0.972500,0.972500,0.972500,0.027500,0.027500,1.034891
14,153.0,0.955000,0.955000,0.045000,0.001498,0.962217,0.955000,0.958595,0.037783,0.045000,0.786664
15,154.0,0.955000,0.955000,0.045000,0.002295,0.943210,0.955000,0.949068,0.056790,0.045000,0.481256
16,161.0,0.977500,0.977500,0.022500,0.000300,0.992386,0.977500,0.984887,0.007614,0.022500,0.993621
17,169.0,0.912500,0.912500,0.087500,0.000600,0.983827,0.912500,0.946822,0.016173,0.087500,0.586922
18,185.9,0.917500,0.917500,0.082500,0.001298,0.965789,0.917500,0.941026,0.034211,0.082500,0.643382
19,197.0,0.887500,0.887500,0.112500,0.001199,0.967302,0.887500,0.925684,0.032698,0.112500,0.782373
20,212.9,0.860000,0.860000,0.140000,0.000400,0.988506,0.860000,0.919786,0.011494,0.140000,0.504919
21,217.0,0.837500,0.837500,0.162500,0.001199,0.965418,0.837500,0.896921,0.034582,0.162500,0.732070
22,239.2,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000000,1.000000,0.982500,0.991173,0.000000,0.017500,0.626969
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.969519,0.969519,0.030481,0.001217,0.970150,0.969519,0.969098,0.029850,0.030481,0.396286

In [135]:
cv_result80

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.749038  0.754037    0.250962  0.749038    0.759102
1       2.0  0.687500  0.687269    0.312500  0.687500    0.687038
2       3.0  0.772115  0.774819    0.227885  0.772115    0.777541
3       4.0  0.656731  0.657978    0.343269  0.656731    0.659230
4       5.0  0.769231  0.774604    0.230769  0.769231    0.780052
5       6.0  0.700000  0.698236    0.300000  0.700000    0.696480
6       7.0  0.789423  0.791479    0.210577  0.789423    0.793546
7       8.0  0.691346  0.692896    0.308654  0.691346    0.694452
8       9.0  0.782692  0.783987    0.217308  0.782692    0.785286
9      10.0  0.675962  0.675974    0.324038  0.675962    0.675987
10       11  0.969519  0.969834    0.030481  0.969519    0.970150
11  average  0.727404  0.729128    0.272596  0.727404    0.730871
12      max  0.789423  0.791479    0.210577  0.789423    0.793546

### SAVE MODEL dTOP80fi

In [136]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier80.pkl', 'wb') as f:
    pickle.dump(knn80, f)

## TRAIN knn TOP 90fi

In [137]:
# train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])

In [138]:
# Separate features and tp_ICD_cl0 variable for train_data90
X_train90 = train_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_train90 = train_data90['tp_ICD_cl0']

In [139]:
timer = CalculateTime(features=90, data_type='train')
timer.start()

knn90, data_top_5, Confusion_df90, eval_result90, cv_result90 = knn_custom_kfold_evaluation(X_train90, y_train90, le, feature=90, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.37 minutes

In [140]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [141]:
Confusion_df90

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,396,0,1,...,0,0,1,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,398,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,1,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,4,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,0,0,0,3,1,4,0,3,...,0,1,2,1,0,1,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,2,0,4,1,2,2,4,4,0,6,...,1,353,4,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,1,1,0,4,...,1,2,364,4,0,0,0,0,0,0
197.0,2,1,5,3,2,5,4,1,1,4,...,1,3,2,349,0,2,0,0,0,0
212.9,4,1,8,3,0,3,3,4,0,9,...,0,1,1,3,335,1,1,1,0,0
217.0,4,0,11,0,1,3,2,5,0,11,...,1,1,2,0,2,332,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [142]:
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003587,0.917431,1.000000,0.956938,0.082569,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002195,0.947867,1.000000,0.973236,0.052133,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002096,0.950000,0.997500,0.973171,0.050000,0.002500,0.000000
7,111.0,0.990000,0.990000,0.010000,0.003289,0.923077,0.990000,0.955368,0.076923,0.010000,0.716132
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.995000,0.995000,0.005000,0.004480,0.898420,0.995000,0.944247,0.101580,0.005000,1.791256
10,146.0,0.985000,0.985000,0.015000,0.002096,0.949398,0.985000,0.966871,0.050602,0.015000,0.787535
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.957500,0.957500,0.042500,0.001597,0.959900,0.957500,0.958698,0.040100,0.042500,0.682775
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.955000,0.955000,0.045000,0.002494,0.938575,0.955000,0.946716,0.061425,0.045000,0.624468
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.882500,0.882500,0.117500,0.000999,0.972452,0.882500,0.925295,0.027548,0.117500,0.685245
18,185.9,0.910000,0.910000,0.090000,0.001398,0.962963,0.910000,0.935733,0.037037,0.090000,0.680800
19,197.0,0.872500,0.872500,0.127500,0.001498,0.958791,0.872500,0.913613,0.041209,0.127500,0.737474
20,212.9,0.837500,0.837500,0.162500,0.000799,0.976676,0.837500,0.901750,0.023324,0.162500,0.652119
21,217.0,0.830000,0.830000,0.170000,0.001199,0.965116,0.830000,0.892473,0.034884,0.170000,0.703678
22,239.2,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963654,0.963654,0.036346,0.001451,0.964384,0.963654,0.963118,0.035616,0.036346,0.449551

In [143]:
cv_result90

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.747115  0.753631    0.252885  0.747115    0.760262
1       2.0  0.682692  0.682370    0.317308  0.682692    0.682049
2       3.0  0.767308  0.771725    0.232692  0.767308    0.776194
3       4.0  0.656731  0.658133    0.343269  0.656731    0.659542
4       5.0  0.762500  0.769077    0.237500  0.762500    0.775769
5       6.0  0.700962  0.698829    0.299038  0.700962    0.696709
6       7.0  0.788462  0.789909    0.211538  0.788462    0.791361
7       8.0  0.684615  0.685537    0.315385  0.684615    0.686461
8       9.0  0.780769  0.782653    0.219231  0.780769    0.784547
9      10.0  0.678846  0.679152    0.321154  0.678846    0.679458
10       11  0.963654  0.964019    0.036346  0.963654    0.964384
11  average  0.725000  0.727102    0.275000  0.725000    0.729235
12      max  0.788462  0.789909    0.211538  0.788462    0.791361

### SAVE MODEL dTOP90fi

In [144]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier90.pkl', 'wb') as f:
    pickle.dump(knn90, f)

## TRAIN knn TOP 100fi

In [145]:
# train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])

In [146]:
# Separate features and tp_ICD_cl0 variable for train_data100
X_train100 = train_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_train100 = train_data100['tp_ICD_cl0']

In [147]:
timer = CalculateTime(features=100, data_type='train')
timer.start()

knn100, data_top_5, Confusion_df100, eval_result100, cv_result100 = knn_custom_kfold_evaluation(X_train100, y_train100, le, feature=100, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.35 minutes

In [148]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [149]:
Confusion_df100

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,396,0,1,...,0,0,1,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,398,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,1,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,4,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,0,0,0,3,1,4,0,3,...,0,1,2,1,0,1,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,2,0,4,1,2,2,4,4,0,6,...,1,353,4,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,1,1,0,4,...,1,2,364,4,0,0,0,0,0,0
197.0,2,1,5,3,2,5,4,1,1,5,...,1,3,2,348,0,2,0,0,0,0
212.9,4,1,8,3,0,3,4,4,0,8,...,0,1,1,2,335,1,1,1,0,0
217.0,4,0,10,0,1,3,2,5,0,11,...,1,1,2,0,2,332,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [150]:
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003488,0.919540,1.000000,0.958084,0.080460,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002195,0.947867,1.000000,0.973236,0.052133,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002195,0.947743,0.997500,0.971985,0.052257,0.002500,0.000000
7,111.0,0.990000,0.990000,0.010000,0.003289,0.923077,0.990000,0.955368,0.076923,0.010000,0.716132
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.995000,0.995000,0.005000,0.004480,0.898420,0.995000,0.944247,0.101580,0.005000,1.791256
10,146.0,0.985000,0.985000,0.015000,0.002195,0.947115,0.985000,0.965686,0.052885,0.015000,0.787535
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.957500,0.957500,0.042500,0.001697,0.957500,0.957500,0.957500,0.042500,0.042500,0.682775
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.955000,0.955000,0.045000,0.002494,0.938575,0.955000,0.946716,0.061425,0.045000,0.624468
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.882500,0.882500,0.117500,0.000999,0.972452,0.882500,0.925295,0.027548,0.117500,0.685245
18,185.9,0.910000,0.910000,0.090000,0.001398,0.962963,0.910000,0.935733,0.037037,0.090000,0.680800
19,197.0,0.870000,0.870000,0.130000,0.001398,0.961326,0.870000,0.913386,0.038674,0.130000,0.738072
20,212.9,0.837500,0.837500,0.162500,0.000799,0.976676,0.837500,0.901750,0.023324,0.162500,0.733571
21,217.0,0.830000,0.830000,0.170000,0.001199,0.965116,0.830000,0.892473,0.034884,0.170000,0.622844
22,239.2,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963558,0.963558,0.036442,0.001454,0.964296,0.963558,0.963016,0.035704,0.036442,0.449598

In [151]:
cv_result100

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.747115  0.753631    0.252885  0.747115    0.760262
1       2.0  0.682692  0.682401    0.317308  0.682692    0.682110
2       3.0  0.767308  0.771424    0.232692  0.767308    0.775585
3       4.0  0.656731  0.658032    0.343269  0.656731    0.659339
4       5.0  0.762500  0.769077    0.237500  0.762500    0.775769
5       6.0  0.700000  0.697940    0.300000  0.700000    0.695891
6       7.0  0.789423  0.790927    0.210577  0.789423    0.792437
7       8.0  0.684615  0.685452    0.315385  0.684615    0.686290
8       9.0  0.780769  0.782653    0.219231  0.780769    0.784547
9      10.0  0.678846  0.678983    0.321154  0.678846    0.679120
10       11  0.963558  0.963927    0.036442  0.963558    0.964296
11  average  0.725000  0.727052    0.275000  0.725000    0.729135
12      max  0.789423  0.790927    0.210577  0.789423    0.792437

### SAVE MODEL dTOP100fi

In [152]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier100.pkl', 'wb') as f:
    pickle.dump(knn100, f)

## TRAIN knn TOP 110fi

In [153]:
# train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])

In [154]:
# Separate features and tp_ICD_cl0 variable for train_data110
X_train110 = train_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_train110 = train_data110['tp_ICD_cl0']

In [155]:
timer = CalculateTime(features=110, data_type='train')
timer.start()

knn110, data_top_5, Confusion_df110, eval_result110, cv_result110 = knn_custom_kfold_evaluation(X_train110, y_train110, le, feature=110, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.41 minutes

In [156]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [157]:
Confusion_df110

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,397,0,1,...,0,0,0,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,398,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,4,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,0,0,0,3,0,5,0,3,...,0,1,2,1,0,0,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,3,0,4,1,1,2,4,4,0,6,...,1,354,3,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,1,1,0,4,...,1,2,364,4,0,0,0,0,0,0
197.0,1,1,5,3,3,4,4,1,1,5,...,1,3,2,349,0,2,0,0,0,0
212.9,4,1,8,3,0,3,4,4,0,8,...,0,1,1,2,335,1,1,1,0,0
217.0,4,0,10,0,1,3,2,5,0,10,...,1,1,2,0,2,331,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [158]:
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003488,0.919540,1.000000,0.958084,0.080460,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002096,0.950000,0.997500,0.973171,0.050000,0.002500,0.000000
7,111.0,0.992500,0.992500,0.007500,0.003388,0.921114,0.992500,0.955475,0.078886,0.007500,0.797434
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.995000,0.995000,0.005000,0.004381,0.900452,0.995000,0.945368,0.099548,0.005000,1.791256
10,146.0,0.987500,0.987500,0.012500,0.002295,0.944976,0.987500,0.965770,0.055024,0.012500,0.809770
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.957500,0.957500,0.042500,0.001697,0.957500,0.957500,0.957500,0.042500,0.042500,0.682775
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.957500,0.957500,0.042500,0.002494,0.938725,0.957500,0.948020,0.061275,0.042500,0.571593
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.885000,0.885000,0.115000,0.000999,0.972527,0.885000,0.926702,0.027473,0.115000,0.724643
18,185.9,0.910000,0.910000,0.090000,0.001099,0.970667,0.910000,0.939355,0.029333,0.090000,0.680800
19,197.0,0.872500,0.872500,0.127500,0.001398,0.961433,0.872500,0.914810,0.038567,0.127500,0.716784
20,212.9,0.837500,0.837500,0.162500,0.000799,0.976676,0.837500,0.901750,0.023324,0.162500,0.733571
21,217.0,0.827500,0.827500,0.172500,0.001099,0.967836,0.827500,0.892183,0.032164,0.172500,0.710099
22,239.2,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963942,0.963942,0.036058,0.001439,0.964711,0.963942,0.963397,0.035289,0.036058,0.455599

In [159]:
cv_result110

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.748077  0.754522    0.251923  0.748077    0.761080
1       2.0  0.682692  0.682401    0.317308  0.682692    0.682110
2       3.0  0.764423  0.768956    0.235577  0.764423    0.773542
3       4.0  0.657692  0.659114    0.342308  0.657692    0.660542
4       5.0  0.762500  0.768696    0.237500  0.762500    0.774993
5       6.0  0.700000  0.697940    0.300000  0.700000    0.695891
6       7.0  0.789423  0.790927    0.210577  0.789423    0.792437
7       8.0  0.684615  0.685544    0.315385  0.684615    0.686474
8       9.0  0.781731  0.783358    0.218269  0.781731    0.784993
9      10.0  0.678846  0.678955    0.321154  0.678846    0.679063
10       11  0.963942  0.964327    0.036058  0.963942    0.964711
11  average  0.725000  0.727041    0.275000  0.725000    0.729113
12      max  0.789423  0.790927    0.210577  0.789423    0.792437

### SAVE MODEL dTOP110fi

In [160]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier110.pkl', 'wb') as f:
    pickle.dump(knn110, f)

## TRAIN knn TOP 120fi

In [161]:
# train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])

In [162]:
# Separate features and tp_ICD_cl0 variable for train_data120
X_train120 = train_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_train120 = train_data120['tp_ICD_cl0']

In [163]:
timer = CalculateTime(features=120, data_type='train')
timer.start()

knn120, data_top_5, Confusion_df120, eval_result120, cv_result120 = knn_custom_kfold_evaluation(X_train120, y_train120, le, feature=120, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.39 minutes

In [164]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [165]:
Confusion_df120

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,397,0,1,...,0,0,0,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,398,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,4,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,1,0,0,3,0,5,0,3,...,0,1,2,1,0,0,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,3,0,4,1,1,2,4,4,0,6,...,1,354,3,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,1,1,0,4,...,1,2,364,4,0,0,0,0,0,0
197.0,1,1,5,3,3,4,4,1,1,5,...,1,3,2,349,0,2,0,0,0,0
212.9,4,1,8,3,0,3,4,4,0,8,...,0,1,1,2,335,1,1,1,0,0
217.0,4,0,10,0,1,3,2,5,0,10,...,1,1,2,0,2,331,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [166]:
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003587,0.917431,1.000000,0.956938,0.082569,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.001099,0.973236,1.000000,0.986436,0.026764,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002096,0.950000,0.997500,0.973171,0.050000,0.002500,0.000000
7,111.0,0.992500,0.992500,0.007500,0.003388,0.921114,0.992500,0.955475,0.078886,0.007500,0.797434
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.995000,0.995000,0.005000,0.004381,0.900452,0.995000,0.945368,0.099548,0.005000,1.791256
10,146.0,0.987500,0.987500,0.012500,0.002295,0.944976,0.987500,0.965770,0.055024,0.012500,0.809770
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.957500,0.957500,0.042500,0.001697,0.957500,0.957500,0.957500,0.042500,0.042500,0.682775
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.955000,0.955000,0.045000,0.002494,0.938575,0.955000,0.946716,0.061425,0.045000,0.583623
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.885000,0.885000,0.115000,0.000999,0.972527,0.885000,0.926702,0.027473,0.115000,0.724643
18,185.9,0.910000,0.910000,0.090000,0.001099,0.970667,0.910000,0.939355,0.029333,0.090000,0.680800
19,197.0,0.872500,0.872500,0.127500,0.001398,0.961433,0.872500,0.914810,0.038567,0.127500,0.716784
20,212.9,0.837500,0.837500,0.162500,0.000799,0.976676,0.837500,0.901750,0.023324,0.162500,0.733571
21,217.0,0.827500,0.827500,0.172500,0.001099,0.967836,0.827500,0.892183,0.032164,0.172500,0.710099
22,239.2,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963846,0.963846,0.036154,0.001443,0.964624,0.963846,0.963303,0.035376,0.036154,0.456062

In [167]:
cv_result120

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.748077  0.754522    0.251923  0.748077    0.761080
1       2.0  0.682692  0.682401    0.317308  0.682692    0.682110
2       3.0  0.764423  0.768956    0.235577  0.764423    0.773542
3       4.0  0.657692  0.659114    0.342308  0.657692    0.660542
4       5.0  0.762500  0.768696    0.237500  0.762500    0.774993
5       6.0  0.700000  0.697940    0.300000  0.700000    0.695891
6       7.0  0.789423  0.790927    0.210577  0.789423    0.792437
7       8.0  0.684615  0.685544    0.315385  0.684615    0.686474
8       9.0  0.781731  0.783358    0.218269  0.781731    0.784993
9      10.0  0.678846  0.678955    0.321154  0.678846    0.679063
10       11  0.963846  0.964235    0.036154  0.963846    0.964624
11  average  0.725000  0.727041    0.275000  0.725000    0.729113
12      max  0.789423  0.790927    0.210577  0.789423    0.792437

### SAVE MODEL dTOP120fi

In [168]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier120.pkl', 'wb') as f:
    pickle.dump(knn120, f)

## TRAIN knn TOP 130fi

In [169]:
# train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])

In [170]:
# Separate features and tp_ICD_cl0 variable for train_data130
X_train130 = train_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_train130 = train_data130['tp_ICD_cl0']

In [171]:
timer = CalculateTime(features=130, data_type='train')
timer.start()

knn130, data_top_5, Confusion_df130, eval_result130, cv_result130 = knn_custom_kfold_evaluation(X_train130, y_train130, le, feature=130, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.39 minutes

In [172]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [173]:
Confusion_df130

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,397,0,1,...,0,0,0,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,399,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,3,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,1,0,0,3,0,5,0,3,...,0,1,2,1,0,0,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,3,0,4,1,1,2,4,4,0,6,...,1,354,3,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,2,1,0,4,...,1,2,363,4,0,0,0,0,0,0
197.0,1,1,5,3,3,4,4,1,1,5,...,1,3,2,349,0,2,0,0,0,0
212.9,4,1,8,2,0,3,4,4,0,8,...,0,1,1,2,336,1,1,1,0,0
217.0,4,0,10,0,1,3,2,5,0,10,...,1,1,2,0,2,330,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [174]:
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003587,0.917431,1.000000,0.956938,0.082569,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000999,0.975610,1.000000,0.987654,0.024390,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002195,0.947743,0.997500,0.971985,0.052257,0.002500,0.000000
7,111.0,0.992500,0.992500,0.007500,0.003289,0.923256,0.992500,0.956627,0.076744,0.007500,0.797434
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.997500,0.997500,0.002500,0.004381,0.900677,0.997500,0.946619,0.099323,0.002500,0.000000
10,146.0,0.987500,0.987500,0.012500,0.002394,0.942721,0.987500,0.964591,0.057279,0.012500,0.809770
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.960000,0.960000,0.040000,0.001697,0.957606,0.960000,0.958801,0.042394,0.040000,0.792643
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.955000,0.955000,0.045000,0.002394,0.940887,0.955000,0.947891,0.059113,0.045000,0.583623
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.885000,0.885000,0.115000,0.000999,0.972527,0.885000,0.926702,0.027473,0.115000,0.724643
18,185.9,0.907500,0.907500,0.092500,0.001099,0.970588,0.907500,0.937984,0.029412,0.092500,0.688036
19,197.0,0.872500,0.872500,0.127500,0.001398,0.961433,0.872500,0.914810,0.038567,0.127500,0.716784
20,212.9,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.731244
21,217.0,0.825000,0.825000,0.175000,0.001099,0.967742,0.825000,0.890688,0.032258,0.175000,0.710208
22,239.2,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.963942,0.963942,0.036058,0.001439,0.964722,0.963942,0.963393,0.035278,0.036058,0.391586

In [175]:
cv_result130

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.749038  0.755608    0.250962  0.749038    0.762293
1       2.0  0.683654  0.683323    0.316346  0.683654    0.682992
2       3.0  0.765385  0.769683    0.234615  0.765385    0.774031
3       4.0  0.657692  0.659055    0.342308  0.657692    0.660424
4       5.0  0.762500  0.768696    0.237500  0.762500    0.774993
5       6.0  0.700000  0.697940    0.300000  0.700000    0.695891
6       7.0  0.788462  0.790024    0.211538  0.788462    0.791593
7       8.0  0.686538  0.687497    0.313462  0.686538    0.688459
8       9.0  0.781731  0.783358    0.218269  0.781731    0.784993
9      10.0  0.678846  0.678955    0.321154  0.678846    0.679063
10       11  0.963942  0.964332    0.036058  0.963942    0.964722
11  average  0.725385  0.727414    0.274615  0.725385    0.729473
12      max  0.788462  0.790024    0.211538  0.788462    0.791593

### SAVE MODEL dTOP130fi

In [176]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier130.pkl', 'wb') as f:
    pickle.dump(knn130, f)

## TRAIN knn TOP 140fi

In [177]:
# train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])

In [178]:
# Separate features and tp_ICD_cl0 variable for train_data140
X_train140 = train_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_train140 = train_data140['tp_ICD_cl0']

In [179]:
timer = CalculateTime(features=140, data_type='train')
timer.start()

knn140, data_top_5, Confusion_df140, eval_result140, cv_result140 = knn_custom_kfold_evaluation(X_train140, y_train140, le, feature=140, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.36 minutes

In [180]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.619048,251.0,0.380952,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.428571,248.0,0.190476,197.0,0.095238,7.1,0.047619,18.9,0.047619
3,129.0,129.0,0.190476,150.0,0.190476,217.0,0.142857,154.0,0.095238,185.9,0.095238
4,169.0,5.0,0.428571,32.1,0.285714,98.9,0.190476,169.0,0.095238,NaN,NaN
5,161.0,161.0,0.238095,169.0,0.238095,7.1,0.142857,41.0,0.142857,146.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.380952,249.0,0.190476,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.285714,32.1,0.142857,111.0,0.142857,5.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.285714,169.0,0.190476,7.1,0.142857,41.0,0.142857,146.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.238095,249.0,0.238095,18.9,0.047619,169.0,0.047619
10400,150.0,98.9,0.238095,146.0,0.142857,151.0,0.142857,147.0,0.095238,185.9,0.095238

In [181]:
Confusion_df140

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,399,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,397,0,1,...,0,0,0,0,1,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,399,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,2,0,2,...,0,1,1,0,1,1,1,0,0,0
150.0,0,0,2,1,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,3,0,1,...,0,0,0,1,2,1,1,0,0,0
153.0,2,0,0,0,0,2,1,3,0,0,...,0,1,0,1,0,3,0,0,0,0
154.0,0,0,1,0,0,3,0,5,0,3,...,0,1,2,1,0,0,0,0,0,0
161.0,0,1,1,0,0,2,1,1,0,3,...,388,0,0,0,0,0,1,0,0,0
169.0,3,0,4,1,1,2,4,4,0,6,...,1,354,3,3,1,2,1,0,0,0
185.9,0,0,3,1,0,2,2,1,0,4,...,1,2,363,4,0,0,0,0,0,0
197.0,1,1,5,3,3,4,4,1,1,5,...,1,3,2,349,0,2,0,0,0,0
212.9,4,1,8,2,0,3,4,4,0,8,...,0,1,1,2,336,1,1,1,0,0
217.0,4,0,10,0,1,3,2,5,0,10,...,1,1,2,0,2,330,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,1,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,392,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [182]:
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001498,0.963855,1.000000,0.981595,0.036145,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003587,0.917431,1.000000,0.956938,0.082569,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000999,0.975610,1.000000,0.987654,0.024390,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
6,104.1,0.997500,0.997500,0.002500,0.002195,0.947743,0.997500,0.971985,0.052257,0.002500,0.000000
7,111.0,0.992500,0.992500,0.007500,0.003190,0.925408,0.992500,0.957780,0.074592,0.007500,0.797434
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,0.997500,0.997500,0.002500,0.004381,0.900677,0.997500,0.946619,0.099323,0.002500,0.000000
10,146.0,0.987500,0.987500,0.012500,0.002394,0.942721,0.987500,0.964591,0.057279,0.012500,1.089604
11,147.0,0.970000,0.970000,0.030000,0.001498,0.962779,0.970000,0.966376,0.037221,0.030000,0.675957
12,150.0,0.970000,0.970000,0.030000,0.001797,0.955665,0.970000,0.962779,0.044335,0.030000,0.839058
13,151.0,0.962500,0.962500,0.037500,0.001697,0.957711,0.962500,0.960100,0.042289,0.037500,0.785301
14,153.0,0.952500,0.952500,0.047500,0.001697,0.957286,0.952500,0.954887,0.042714,0.047500,0.697959
15,154.0,0.955000,0.955000,0.045000,0.002394,0.940887,0.955000,0.947891,0.059113,0.045000,0.583623
16,161.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,0.730059
17,169.0,0.885000,0.885000,0.115000,0.000999,0.972527,0.885000,0.926702,0.027473,0.115000,0.724643
18,185.9,0.907500,0.907500,0.092500,0.001099,0.970588,0.907500,0.937984,0.029412,0.092500,0.688036
19,197.0,0.872500,0.872500,0.127500,0.001398,0.961433,0.872500,0.914810,0.038567,0.127500,0.716784
20,212.9,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.731244
21,217.0,0.825000,0.825000,0.175000,0.001099,0.967742,0.825000,0.890688,0.032258,0.175000,0.710208
22,239.2,1.000000,1.000000,0.000000,0.000899,0.977995,1.000000,0.988875,0.022005,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.683814
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.964038,0.964038,0.035962,0.001435,0.964809,0.964038,0.963488,0.035191,0.035962,0.402066

In [183]:
cv_result140

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.749038  0.755608    0.250962  0.749038    0.762293
1       2.0  0.683654  0.683203    0.316346  0.683654    0.682754
2       3.0  0.764423  0.768658    0.235577  0.764423    0.772940
3       4.0  0.657692  0.659094    0.342308  0.657692    0.660502
4       5.0  0.762500  0.768722    0.237500  0.762500    0.775046
5       6.0  0.700962  0.699060    0.299038  0.700962    0.697170
6       7.0  0.788462  0.790006    0.211538  0.788462    0.791557
7       8.0  0.687500  0.688569    0.312500  0.687500    0.689640
8       9.0  0.781731  0.783300    0.218269  0.781731    0.784876
9      10.0  0.678846  0.678827    0.321154  0.678846    0.678809
10       11  0.964038  0.964423    0.035962  0.964038    0.964809
11  average  0.725481  0.727505    0.274519  0.725481    0.729559
12      max  0.788462  0.790006    0.211538  0.788462    0.791557

### SAVE MODEL dTOP140fi

In [184]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier140.pkl', 'wb') as f:
    pickle.dump(knn140, f)

## TRAIN knn TOP 150fi

In [185]:
# train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])

In [186]:
# Separate features and tp_ICD_cl0 variable for train_data150
X_train150 = train_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_train150 = train_data150['tp_ICD_cl0']

In [187]:
timer = CalculateTime(features=150, data_type='train')
timer.start()

knn150, data_top_5, Confusion_df150, eval_result150, cv_result150 = knn_custom_kfold_evaluation(X_train150, y_train150, le, feature=150, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.38 minutes

In [188]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.60,251.0,0.40,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,5.0,0.40,248.0,0.20,197.0,0.10,7.1,0.05,18.9,0.05
3,129.0,129.0,0.20,150.0,0.20,217.0,0.15,154.0,0.10,185.9,0.10
4,169.0,5.0,0.45,32.1,0.30,98.9,0.15,169.0,0.10,NaN,NaN
5,161.0,161.0,0.25,169.0,0.25,7.1,0.15,41.0,0.15,146.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.30,32.1,0.15,111.0,0.15,5.0,0.10,217.0,0.10
10398,169.0,161.0,0.25,169.0,0.20,7.1,0.15,41.0,0.15,146.0,0.10
10399,249.0,249.0,0.35,251.0,0.30,248.0,0.20,18.9,0.05,169.0,0.05
10400,150.0,98.9,0.25,146.0,0.15,151.0,0.15,147.0,0.10,185.9,0.10

In [189]:
Confusion_df150

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,400,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,398,0,1,...,0,0,0,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,400,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,0,0,2,...,0,0,0,1,0,0,1,0,0,0
150.0,0,0,1,0,0,0,1,1,0,0,...,0,0,1,0,0,1,0,0,0,0
151.0,1,0,1,1,1,0,0,2,0,0,...,0,0,0,0,1,1,0,0,0,0
153.0,1,0,0,0,0,1,2,2,0,1,...,0,0,0,1,0,3,0,0,0,0
154.0,0,0,3,0,0,2,0,3,0,3,...,0,0,4,1,0,0,0,0,0,0
161.0,0,0,1,0,0,1,1,1,0,1,...,391,0,1,0,0,0,1,0,0,0
169.0,1,0,5,1,0,1,3,2,0,7,...,1,363,3,2,0,1,1,0,0,0
185.9,1,0,3,1,0,2,2,1,0,3,...,1,2,367,3,0,1,0,0,0,0
197.0,1,1,5,3,0,4,3,2,1,4,...,1,3,2,354,0,2,0,0,0,0
212.9,3,1,6,2,0,4,3,5,0,9,...,0,0,1,2,342,1,1,1,0,0
217.0,4,0,9,0,1,3,3,3,0,9,...,1,1,1,1,2,332,4,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,393,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [190]:
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.003388,0.921659,1.000000,0.959233,0.078341,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.001896,0.954654,1.000000,0.976801,0.045346,0.000000,0.000000
6,104.1,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
7,111.0,0.995000,0.995000,0.005000,0.002295,0.945368,0.995000,0.969549,0.054632,0.005000,1.707786
8,128.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
9,129.0,1.000000,1.000000,0.000000,0.003984,0.909091,1.000000,0.952381,0.090909,0.000000,0.000000
10,146.0,0.990000,0.990000,0.010000,0.002096,0.949640,0.990000,0.969400,0.050360,0.010000,1.042440
11,147.0,0.985000,0.985000,0.015000,0.000999,0.975248,0.985000,0.980100,0.024752,0.015000,0.601334
12,150.0,0.985000,0.985000,0.015000,0.002295,0.944844,0.985000,0.964504,0.055156,0.015000,0.973474
13,151.0,0.975000,0.975000,0.025000,0.001099,0.972569,0.975000,0.973783,0.027431,0.025000,1.037448
14,153.0,0.960000,0.960000,0.040000,0.001498,0.962406,0.960000,0.961202,0.037594,0.040000,0.596166
15,154.0,0.952500,0.952500,0.047500,0.001996,0.950125,0.952500,0.951311,0.049875,0.047500,0.652036
16,161.0,0.977500,0.977500,0.022500,0.000400,0.989873,0.977500,0.983648,0.010127,0.022500,0.993621
17,169.0,0.907500,0.907500,0.092500,0.000600,0.983740,0.907500,0.944083,0.016260,0.092500,0.579105
18,185.9,0.917500,0.917500,0.082500,0.001298,0.965789,0.917500,0.941026,0.034211,0.082500,0.650373
19,197.0,0.885000,0.885000,0.115000,0.001298,0.964578,0.885000,0.923077,0.035422,0.115000,0.792028
20,212.9,0.855000,0.855000,0.145000,0.000400,0.988439,0.855000,0.916890,0.011561,0.145000,0.554566
21,217.0,0.830000,0.830000,0.170000,0.000999,0.970760,0.830000,0.894879,0.029240,0.170000,0.713494
22,239.2,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000100,0.997506,1.000000,0.998752,0.002494,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000000,1.000000,0.982500,0.991173,0.000000,0.017500,0.626969
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.969135,0.969135,0.030865,0.001232,0.969832,0.969135,0.968669,0.030168,0.030865,0.443109

In [191]:
cv_result150

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.750000  0.754834    0.250000  0.750000    0.759731
1       2.0  0.687500  0.686915    0.312500  0.687500    0.686330
2       3.0  0.769231  0.771764    0.230769  0.769231    0.774313
3       4.0  0.655769  0.656912    0.344231  0.655769    0.658060
4       5.0  0.766346  0.771744    0.233654  0.766346    0.777218
5       6.0  0.699038  0.697580    0.300962  0.699038    0.696127
6       7.0  0.787500  0.789456    0.212500  0.787500    0.791422
7       8.0  0.693269  0.694702    0.306731  0.693269    0.696141
8       9.0  0.784615  0.786112    0.215385  0.784615    0.787614
9      10.0  0.677885  0.678060    0.322115  0.677885    0.678236
10       11  0.969135  0.969483    0.030865  0.969135    0.969832
11  average  0.727115  0.728808    0.272885  0.727115    0.730519
12      max  0.787500  0.789456    0.212500  0.787500    0.791422

### SAVE MODEL dTOP150fi

In [192]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier150.pkl', 'wb') as f:
    pickle.dump(knn150, f)

## TRAIN knn ALLfi

In [193]:
# train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])

In [194]:
# Separate features and tp_ICD_cl0 variable for train_data353
X_train353 = train_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_train353 = train_data353['tp_ICD_cl0']

In [195]:
timer = CalculateTime(features='all', data_type='train')
timer.start()

knn353, data_top_5, Confusion_df353, eval_result353, cv_result353 = knn_custom_kfold_evaluation(X_train353, y_train353, le, feature=353, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

26
Time taken: 0.44 minutes

In [196]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.60,251.0,0.40,NaN,NaN,NaN,NaN,NaN,NaN
2,41.0,147.0,0.20,7.1,0.15,104.1,0.10,151.0,0.10,248.0,0.10
3,129.0,129.0,0.20,150.0,0.20,217.0,0.15,154.0,0.10,185.9,0.10
4,169.0,5.0,0.45,32.1,0.30,98.9,0.15,169.0,0.10,NaN,NaN
5,161.0,161.0,0.25,169.0,0.25,7.1,0.15,41.0,0.15,146.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.50,248.0,0.30,249.0,0.20,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.30,32.1,0.15,111.0,0.15,5.0,0.10,217.0,0.10
10398,169.0,161.0,0.25,169.0,0.20,7.1,0.15,41.0,0.15,146.0,0.10
10399,249.0,251.0,0.35,248.0,0.25,249.0,0.25,18.9,0.05,169.0,0.05
10400,150.0,98.9,0.25,146.0,0.15,151.0,0.15,147.0,0.10,185.9,0.10

In [197]:
Confusion_df353

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7.1,0,400,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18.9,0,0,400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32.1,0,0,0,400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,400,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,0,0,0,0,0,400,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,400,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111.0,0,0,0,0,0,0,0,399,0,1,...,0,0,0,0,0,0,0,0,0,0
128.0,0,0,0,0,0,0,0,0,400,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,400,...,0,0,0,0,0,0,0,0,0,0
146.0,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,1,0,2,...,0,0,0,0,0,0,1,0,0,0
150.0,0,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,2,0,0,0,0
151.0,1,0,1,1,1,0,0,2,0,0,...,0,0,0,0,1,1,0,0,0,0
153.0,2,0,0,0,0,0,1,2,0,1,...,0,0,0,1,0,2,0,0,0,0
154.0,0,0,3,0,0,2,0,4,0,3,...,0,0,3,1,0,0,0,0,0,0
161.0,0,0,1,0,0,2,1,1,0,2,...,391,0,0,0,0,0,1,0,0,0
169.0,1,0,4,1,1,1,4,2,0,6,...,0,365,3,2,0,1,1,0,0,0
185.9,1,0,3,1,0,2,2,1,0,3,...,1,2,367,4,0,0,0,0,0,0
197.0,1,1,5,3,0,4,3,2,1,3,...,2,3,2,354,0,2,0,0,0,0
212.9,3,1,5,2,0,4,3,6,0,9,...,0,0,1,2,346,1,1,0,0,0
217.0,4,0,7,0,1,3,3,3,1,9,...,1,1,1,2,1,333,3,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,400,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,2,0,0,0,...,0,0,0,2,1,0,0,0,393,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,400

In [198]:
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,1.000000,1.000000,0.000000,0.001298,0.968523,1.000000,0.984010,0.031477,0.000000,0.000000
1,7.1,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
2,18.9,1.000000,1.000000,0.000000,0.002991,0.930233,1.000000,0.963855,0.069767,0.000000,0.000000
3,32.1,1.000000,1.000000,0.000000,0.000799,0.980392,1.000000,0.990099,0.019608,0.000000,0.000000
4,41.0,1.000000,1.000000,0.000000,0.000300,0.992556,1.000000,0.996264,0.007444,0.000000,0.000000
5,98.9,1.000000,1.000000,0.000000,0.001896,0.954654,1.000000,0.976801,0.045346,0.000000,0.000000
6,104.1,1.000000,1.000000,0.000000,0.002096,0.950119,1.000000,0.974421,0.049881,0.000000,0.000000
7,111.0,0.997500,0.997500,0.002500,0.002494,0.941038,0.997500,0.968447,0.058962,0.002500,0.000000
8,128.0,1.000000,1.000000,0.000000,0.000200,0.995025,1.000000,0.997506,0.004975,0.000000,0.000000
9,129.0,1.000000,1.000000,0.000000,0.003885,0.911162,1.000000,0.953516,0.088838,0.000000,0.000000
10,146.0,0.990000,0.990000,0.010000,0.001896,0.954217,0.990000,0.971779,0.045783,0.010000,1.042440
11,147.0,0.985000,0.985000,0.015000,0.000899,0.977667,0.985000,0.981320,0.022333,0.015000,0.635542
12,150.0,0.985000,0.985000,0.015000,0.002096,0.949398,0.985000,0.966871,0.050602,0.015000,0.670640
13,151.0,0.975000,0.975000,0.025000,0.001099,0.972569,0.975000,0.973783,0.027431,0.025000,1.037448
14,153.0,0.965000,0.965000,0.035000,0.001398,0.965000,0.965000,0.965000,0.035000,0.035000,0.702380
15,154.0,0.952500,0.952500,0.047500,0.002096,0.947761,0.952500,0.950125,0.052239,0.047500,0.685680
16,161.0,0.977500,0.977500,0.022500,0.000400,0.989873,0.977500,0.983648,0.010127,0.022500,0.784651
17,169.0,0.912500,0.912500,0.087500,0.000600,0.983827,0.912500,0.946822,0.016173,0.087500,0.616691
18,185.9,0.917500,0.917500,0.082500,0.001099,0.970899,0.917500,0.943445,0.029101,0.082500,0.702159
19,197.0,0.885000,0.885000,0.115000,0.001398,0.961957,0.885000,0.921875,0.038043,0.115000,0.792330
20,212.9,0.865000,0.865000,0.135000,0.000300,0.991404,0.865000,0.923899,0.008596,0.135000,0.541074
21,217.0,0.832500,0.832500,0.167500,0.000899,0.973684,0.832500,0.897574,0.026316,0.167500,0.609767
22,239.2,1.000000,1.000000,0.000000,0.000700,0.982801,1.000000,0.991326,0.017199,0.000000,0.000000
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.982500,0.982500,0.017500,0.000000,1.000000,0.982500,0.991173,0.000000,0.017500,0.626969
25,251.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
26,average,0.970096,0.970096,0.029904,0.001194,0.970761,0.970096,0.969656,0.029239,0.029904,0.363376

In [199]:
cv_result353

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.748077  0.753573    0.251923  0.748077    0.759150
1       2.0  0.688462  0.689180    0.311538  0.688462    0.689901
2       3.0  0.766346  0.769445    0.233654  0.766346    0.772569
3       4.0  0.655769  0.656568    0.344231  0.655769    0.657369
4       5.0  0.766346  0.771067    0.233654  0.766346    0.775846
5       6.0  0.701923  0.700286    0.298077  0.701923    0.698657
6       7.0  0.790385  0.792285    0.209615  0.790385    0.794195
7       8.0  0.691346  0.693037    0.308654  0.691346    0.694736
8       9.0  0.783654  0.785267    0.216346  0.783654    0.786887
9      10.0  0.677885  0.678133    0.322115  0.677885    0.678381
10       11  0.970096  0.970428    0.029904  0.970096    0.970761
11  average  0.727019  0.728884    0.272981  0.727019    0.730769
12      max  0.790385  0.792285    0.209615  0.790385    0.794195

### SAVE MODEL dAllfi

In [200]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier353.pkl', 'wb') as f:
    pickle.dump(knn353, f)

# **TESTING**

## LOADING TEST_DATASET

In [201]:
# sudah load dataset testing dari awal

## LOAD & APPLY MODEL_SHAP

In [202]:
# sudah apply shap ke data testing dari awal

## LOAD & APPLY MODEL dTOP5fi

In [203]:
# le = LabelEncoder()
# le.fit(test_data5['tp_ICD_cl0'])

In [204]:
# test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

In [205]:
# Separate features and tp_ICD_cl0 variable for test_data5
X_test5 = test_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_test5 = test_data5['tp_ICD_cl0']

In [206]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier5.pkl', 'rb') as f:
    knn_5 = pickle.load(f)

### EVALUATION & SAVE

In [207]:
prob5 = knn5.predict_proba(X_test5)
classes5 = knn5.classes_

y_pred5, data_top_5 = get_predictions(prob5, classes5, threshold, 10, np.array(y_test5), le)

Confusion_df5 = pd.DataFrame(confusion_matrix(np.array(y_test5), y_pred5))

Confusion_df5.index, Confusion_df5.columns = le.inverse_transform(classes5), le.inverse_transform(classes5)

eval_result5 = calculate_evaluation_metrics(Confusion_df=Confusion_df5)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [208]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,169.0,0.208333,151.0,0.166667,161.0,0.166667,104.1,0.083333,146.0,0.083333
2,185.9,104.1,0.166667,5.0,0.125000,18.9,0.125000,7.1,0.083333,151.0,0.083333
3,248.0,249.0,0.416667,248.0,0.208333,251.0,0.208333,5.0,0.083333,98.9,0.041667
4,146.0,153.0,0.166667,150.0,0.125000,41.0,0.083333,128.0,0.083333,146.0,0.083333
5,251.0,251.0,0.458333,248.0,0.291667,249.0,0.250000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,212.9,0.208333,129.0,0.125000,104.1,0.083333,153.0,0.083333,154.0,0.083333
2597,18.9,151.0,0.166667,197.0,0.166667,7.1,0.125000,98.9,0.083333,154.0,0.083333
2598,217.0,239.2,0.583333,98.9,0.125000,5.0,0.083333,104.1,0.083333,32.1,0.041667
2599,104.1,146.0,0.250000,111.0,0.125000,197.0,0.125000,129.0,0.083333,153.0,0.083333
2600,251.0,251.0,0.458333,248.0,0.291667,249.0,0.250000,NaN,NaN,NaN,NaN

In [209]:
Confusion_df5.index = Confusion_df5.index + 1
Confusion_df5
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,76,0,2,0,0,0,2,0,2,2,...,0,0,0,1,2,0,1,0,0,0
8.1,2,54,2,0,3,1,3,1,0,0,...,2,0,0,5,7,1,4,1,0,0
19.9,1,1,63,2,3,0,2,1,0,0,...,2,2,0,1,0,0,2,0,4,0
33.1,1,0,0,82,0,0,1,1,1,0,...,0,0,0,2,3,2,2,0,0,0
42.0,7,1,0,0,76,1,0,0,1,0,...,0,0,0,0,3,0,5,0,1,0
99.9,0,1,3,3,2,64,5,1,1,1,...,2,0,0,4,0,0,3,0,0,0
105.1,1,0,1,0,0,4,68,0,2,5,...,1,1,0,4,0,1,2,0,0,0
112.0,2,0,2,0,1,4,8,64,3,2,...,1,0,0,1,0,0,1,0,0,0
129.0,0,0,0,1,0,0,2,0,90,0,...,0,0,0,0,1,0,1,0,0,0
130.0,2,0,2,0,0,0,3,0,3,75,...,0,0,0,2,0,2,2,0,1,0
147.0,0,2,0,0,1,2,3,5,1,3,...,1,0,0,0,1,0,1,0,0,0
148.0,5,4,0,0,3,1,0,1,0,2,...,1,2,0,6,0,2,1,0,0,0
151.0,1,1,0,0,1,0,0,1,2,8,...,0,2,0,2,7,1,4,0,0,0
152.0,4,0,0,0,0,1,3,3,1,2,...,1,0,0,3,8,0,0,0,0,0
154.0,6,1,1,1,0,0,2,0,0,1,...,0,1,1,4,4,0,1,0,0,0
155.0,2,1,0,1,0,0,0,3,0,0,...,0,1,0,4,0,1,1,0,0,0
162.0,0,2,3,1,0,2,1,1,0,3,...,73,0,0,0,2,0,4,0,0,0
170.0,0,4,3,0,0,1,3,1,0,2,...,0,53,0,5,5,0,3,0,0,0
186.9,1,1,7,1,0,1,8,5,0,0,...,3,0,46,7,3,0,2,0,0,0
198.0,10,0,1,0,0,2,4,1,0,0,...,2,0,0,54,2,0,5,0,0,0
213.9,1,0,1,0,1,0,6,2,0,0,...,2,0,0,4,48,1,3,0,0,0
218.0,2,1,3,2,0,1,4,4,0,2,...,0,1,0,0,4,49,7,0,0,0
240.2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,2,0,0,94,0
252.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,96

In [210]:
eval_result5.index = eval_result5.index + 1
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.760000,0.760000,0.240000,0.019992,0.598425,0.760000,0.669604,0.401575,0.240000,0.656217
2,7.1,0.540000,0.540000,0.460000,0.007937,0.729730,0.540000,0.620690,0.270270,0.460000,0.630930
3,18.9,0.630000,0.630000,0.370000,0.012248,0.670213,0.630000,0.649485,0.329787,0.370000,0.500000
4,32.1,0.820000,0.820000,0.180000,0.004777,0.872340,0.820000,0.845361,0.127660,0.180000,0.637033
5,41.0,0.760000,0.760000,0.240000,0.005964,0.835165,0.760000,0.795812,0.164835,0.240000,1.367112
6,98.9,0.640000,0.640000,0.360000,0.008330,0.752941,0.640000,0.691892,0.247059,0.360000,0.579452
7,104.1,0.680000,0.680000,0.320000,0.023438,0.531250,0.680000,0.596491,0.468750,0.320000,0.612246
8,111.0,0.640000,0.640000,0.360000,0.012248,0.673684,0.640000,0.656410,0.326316,0.360000,0.568832
9,128.0,0.900000,0.900000,0.100000,0.007149,0.833333,0.900000,0.865385,0.166667,0.100000,0.706701
10,129.0,0.750000,0.750000,0.250000,0.013028,0.694444,0.750000,0.721154,0.305556,0.250000,0.621734
11,146.0,0.650000,0.650000,0.350000,0.014972,0.631068,0.650000,0.640394,0.368932,0.350000,0.519580
12,147.0,0.580000,0.580000,0.420000,0.027237,0.453125,0.580000,0.508772,0.546875,0.420000,0.270238
13,150.0,0.550000,0.550000,0.450000,0.015748,0.578947,0.550000,0.564103,0.421053,0.450000,0.262650
14,151.0,0.490000,0.490000,0.510000,0.016522,0.538462,0.490000,0.513089,0.461538,0.510000,0.255958
15,153.0,0.640000,0.640000,0.360000,0.035494,0.410256,0.640000,0.500000,0.589744,0.360000,1.238715
16,154.0,0.590000,0.590000,0.410000,0.014584,0.614583,0.590000,0.602041,0.385417,0.410000,0.244651
17,161.0,0.730000,0.730000,0.270000,0.007149,0.802198,0.730000,0.764398,0.197802,0.270000,0.601238
18,169.0,0.530000,0.530000,0.470000,0.003984,0.841270,0.530000,0.650307,0.158730,0.470000,0.235409
19,185.9,0.460000,0.460000,0.540000,0.000400,0.978723,0.460000,0.625850,0.021277,0.540000,0.231378
20,197.0,0.540000,0.540000,0.460000,0.021526,0.495413,0.540000,0.516746,0.504587,0.460000,0.227670
21,212.9,0.480000,0.480000,0.520000,0.020760,0.475248,0.480000,0.477612,0.524752,0.520000,0.224244
22,217.0,0.490000,0.490000,0.510000,0.005173,0.790323,0.490000,0.604938,0.209677,0.510000,0.221065
23,239.2,0.990000,0.990000,0.010000,0.021526,0.642857,0.990000,0.779528,0.357143,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.003587,0.912621,0.940000,0.926108,0.087379,0.060000,0.875097
26,251.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.581874
27,average,0.682308,0.682308,0.317692,0.012468,0.705643,0.682308,0.683107,0.294357,0.317692,0.495001

In [211]:
Confusion_df5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier5.csv')
eval_result5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier5.csv', index=False)

## LOAD & APPLY MODEL dTOP10fi

In [212]:
# test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

In [213]:
# Separate features and tp_ICD_cl0 variable for test_data10
X_test10 = test_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_test10 = test_data10['tp_ICD_cl0']

In [214]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier10.pkl', 'rb') as f:
    knn_10 = pickle.load(f)

### EVALUATION & SAVE

In [215]:
prob10 = knn_10.predict_proba(X_test10)
classes10 = knn_10.classes_

y_pred10, data_top_5 = get_predictions(prob10, classes10, threshold, 10, np.array(y_test10), le)

Confusion_df10 = pd.DataFrame(confusion_matrix(np.array(y_test10), y_pred10))
Confusion_df10.index, Confusion_df10.columns = le.inverse_transform(classes10), le.inverse_transform(classes10)

eval_result10 = calculate_evaluation_metrics(Confusion_df=Confusion_df10)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [216]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.363636,161.0,0.318182,169.0,0.136364,104.1,0.045455,146.0,0.045455
2,185.9,197.0,0.227273,5.0,0.090909,153.0,0.090909,154.0,0.090909,161.0,0.090909
3,248.0,248.0,0.500000,251.0,0.409091,249.0,0.090909,NaN,NaN,NaN,NaN
4,146.0,104.1,0.136364,111.0,0.136364,169.0,0.136364,197.0,0.136364,146.0,0.090909
5,251.0,251.0,0.500000,249.0,0.318182,248.0,0.181818,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.272727,150.0,0.181818,151.0,0.136364,147.0,0.090909,5.0,0.045455
2597,18.9,154.0,0.181818,18.9,0.136364,104.1,0.136364,111.0,0.090909,146.0,0.090909
2598,217.0,239.2,0.454545,41.0,0.090909,151.0,0.090909,154.0,0.090909,7.1,0.045455
2599,104.1,212.9,0.181818,104.1,0.136364,146.0,0.136364,197.0,0.136364,18.9,0.090909
2600,251.0,248.0,0.454545,251.0,0.454545,249.0,0.090909,NaN,NaN,NaN,NaN

In [217]:
Confusion_df10.index = Confusion_df5.index + 1
Confusion_df10
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
7.0,80,0,0,4,0,0,1,1,0,1,...,0,1,0,0,1,0,3,0,1,0
9.1,1,74,1,0,1,0,2,2,0,3,...,2,0,1,1,1,0,2,0,0,1
20.9,3,2,62,4,3,2,3,1,0,4,...,3,0,1,1,1,0,3,0,0,0
34.1,2,0,0,84,0,1,1,1,1,0,...,0,0,1,2,0,0,3,0,0,0
43.0,2,3,0,1,73,2,2,1,0,0,...,0,1,0,1,0,1,7,0,0,0
100.9,0,2,0,1,6,62,4,2,0,2,...,0,0,1,0,0,1,6,0,0,0
106.1,0,0,0,1,0,2,78,2,0,5,...,2,0,2,0,0,2,0,0,0,0
113.0,0,1,0,0,1,2,2,73,0,4,...,4,0,0,0,1,1,1,0,0,0
130.0,1,1,0,0,0,0,1,0,92,1,...,0,0,0,0,0,0,0,0,0,0
131.0,1,3,1,0,1,0,2,1,0,84,...,0,1,1,1,0,1,0,0,0,0
148.0,0,2,1,1,1,5,0,2,2,4,...,0,1,0,0,2,2,0,0,0,0
149.0,2,1,3,0,1,0,0,1,1,0,...,0,0,3,1,0,0,0,0,0,0
152.0,0,2,1,1,3,0,4,0,0,2,...,0,1,0,1,2,0,2,0,0,0
153.0,1,1,0,0,0,1,2,3,0,0,...,0,0,2,0,0,4,0,0,0,0
155.0,1,3,2,1,0,3,1,4,0,6,...,0,1,1,1,1,4,1,0,0,0
156.0,1,6,4,1,1,2,4,3,0,2,...,0,0,1,1,1,2,0,0,0,0
163.0,0,5,3,2,3,0,1,0,0,3,...,70,0,2,0,0,0,3,0,0,0
171.0,2,2,1,2,1,1,3,2,0,4,...,0,61,0,2,0,3,1,0,0,0
187.9,5,2,5,1,2,2,5,2,2,2,...,0,1,48,3,2,2,3,0,0,0
199.0,1,5,4,3,4,1,4,2,0,7,...,1,0,3,48,1,0,1,0,0,0
214.9,1,1,0,1,0,2,5,5,2,8,...,2,2,0,2,43,1,4,0,0,0
219.0,0,2,1,2,0,4,2,1,1,8,...,0,1,4,3,4,54,4,0,1,0
241.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,99,0,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
251.0,1,1,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,0,94,0
253.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [218]:
eval_result10.index = eval_result10.index + 1
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.800000,0.800000,0.200000,0.009901,0.761905,0.800000,0.780488,0.238095,0.200000,0.646306
2,7.1,0.740000,0.740000,0.260000,0.017682,0.621849,0.740000,0.675799,0.378151,0.260000,0.636002
3,18.9,0.620000,0.620000,0.380000,0.010685,0.696629,0.620000,0.656085,0.303371,0.380000,0.500000
4,32.1,0.840000,0.840000,0.160000,0.010293,0.763636,0.840000,0.800000,0.236364,0.160000,0.794994
5,41.0,0.730000,0.730000,0.270000,0.011076,0.722772,0.730000,0.726368,0.277228,0.270000,0.446783
6,98.9,0.620000,0.620000,0.380000,0.011858,0.673913,0.620000,0.645833,0.326087,0.380000,0.356207
7,104.1,0.780000,0.780000,0.220000,0.019223,0.614173,0.780000,0.687225,0.385827,0.220000,0.560652
8,111.0,0.730000,0.730000,0.270000,0.014196,0.669725,0.730000,0.698565,0.330275,0.270000,0.618626
9,128.0,0.920000,0.920000,0.080000,0.003984,0.901961,0.920000,0.910891,0.098039,0.080000,0.896690
10,129.0,0.840000,0.840000,0.160000,0.025721,0.560000,0.840000,0.672000,0.440000,0.160000,1.077116
11,146.0,0.700000,0.700000,0.300000,0.011858,0.700000,0.700000,0.700000,0.300000,0.300000,0.680131
12,147.0,0.780000,0.780000,0.220000,0.014972,0.672414,0.780000,0.722222,0.327586,0.220000,0.899733
13,150.0,0.760000,0.760000,0.240000,0.014584,0.672566,0.760000,0.713615,0.327434,0.240000,0.748209
14,151.0,0.810000,0.810000,0.190000,0.018453,0.632812,0.810000,0.710526,0.367188,0.190000,0.603893
15,153.0,0.600000,0.600000,0.400000,0.009116,0.722892,0.600000,0.655738,0.277108,0.400000,0.250000
16,154.0,0.570000,0.570000,0.430000,0.009509,0.703704,0.570000,0.629834,0.296296,0.430000,0.244651
17,161.0,0.700000,0.700000,0.300000,0.005569,0.833333,0.700000,0.760870,0.166667,0.300000,0.963620
18,169.0,0.610000,0.610000,0.390000,0.003984,0.859155,0.610000,0.713450,0.140845,0.390000,0.235409
19,185.9,0.480000,0.480000,0.520000,0.009116,0.676056,0.480000,0.561404,0.323944,0.520000,0.231378
20,197.0,0.480000,0.480000,0.520000,0.008330,0.695652,0.480000,0.568047,0.304348,0.520000,0.227670
21,212.9,0.430000,0.430000,0.570000,0.007149,0.704918,0.430000,0.534161,0.295082,0.570000,0.224244
22,217.0,0.540000,0.540000,0.460000,0.009901,0.683544,0.540000,0.603352,0.316456,0.460000,0.221065
23,239.2,0.990000,0.990000,0.010000,0.017296,0.692308,0.990000,0.814815,0.307692,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000799,0.979167,0.940000,0.959184,0.020833,0.060000,1.493829
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.731154,0.731154,0.268846,0.010602,0.738661,0.731154,0.726750,0.261339,0.268846,0.521431

In [219]:
Confusion_df10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier10.csv')
eval_result10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier10.csv', index=False)

## LOAD & APPLY MODEL dTOP20fi

In [220]:
# test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

In [221]:
# Separate features and tp_ICD_cl0 variable for test_data20
X_test20 = test_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_test20 = test_data20['tp_ICD_cl0']

In [222]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier20.pkl', 'rb') as f:
    knn_20 = pickle.load(f)

### EVALUATION & SAVE

In [223]:
prob20 = knn_20.predict_proba(X_test20)
classes20 = knn_20.classes_

y_pred20, data_top_5 = get_predictions(prob20, classes20, threshold, 10, np.array(y_test20), le)

Confusion_df20 = pd.DataFrame(confusion_matrix(np.array(y_test20), y_pred20))
Confusion_df20.index, Confusion_df20.columns = le.inverse_transform(classes20), le.inverse_transform(classes20)

eval_result20 = calculate_evaluation_metrics(Confusion_df=Confusion_df20)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [224]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.35,98.9,0.15,146.0,0.15,41.0,0.10,104.1,0.05
2,185.9,153.0,0.25,197.0,0.15,5.0,0.10,129.0,0.10,212.9,0.10
3,248.0,248.0,0.45,154.0,0.10,169.0,0.10,5.0,0.05,7.1,0.05
4,146.0,104.1,0.15,111.0,0.15,169.0,0.15,18.9,0.10,129.0,0.10
5,251.0,251.0,0.45,249.0,0.35,248.0,0.20,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.30,150.0,0.20,147.0,0.10,151.0,0.10,5.0,0.05
2597,18.9,154.0,0.20,18.9,0.15,129.0,0.15,151.0,0.15,153.0,0.10
2598,217.0,239.2,0.50,151.0,0.10,154.0,0.10,18.9,0.05,41.0,0.05
2599,104.1,212.9,0.20,5.0,0.15,104.1,0.10,146.0,0.10,197.0,0.10
2600,251.0,251.0,0.70,249.0,0.20,248.0,0.10,NaN,NaN,NaN,NaN

In [225]:
Confusion_df20.index = Confusion_df20.index + 1
Confusion_df20
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,81,0,0,1,0,1,1,0,1,1,...,0,1,1,1,0,0,3,0,1,0
8.1,0,81,0,0,0,0,0,0,0,4,...,0,4,0,1,0,1,1,0,0,1
19.9,3,0,70,4,4,1,0,1,0,7,...,1,2,0,0,0,0,3,0,0,0
33.1,1,0,1,85,1,0,1,1,2,0,...,0,0,1,0,0,0,2,0,0,0
42.0,0,1,0,3,81,2,1,1,1,1,...,0,0,0,1,0,2,4,0,0,0
99.9,0,2,1,2,3,66,2,0,0,4,...,0,0,0,1,2,1,6,0,0,0
105.1,2,1,3,2,1,1,71,2,2,5,...,1,0,3,1,0,0,0,0,0,0
112.0,2,2,1,1,2,0,0,72,1,5,...,1,0,0,1,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,1,91,0,...,0,0,0,1,0,2,0,0,0,0
130.0,1,2,0,1,0,1,0,3,0,86,...,0,0,1,0,0,0,0,0,0,0
147.0,0,1,1,0,0,3,1,1,2,3,...,0,0,0,0,0,1,0,0,0,0
148.0,1,1,1,0,1,1,2,3,0,2,...,0,0,1,0,0,0,0,0,0,0
151.0,1,0,0,1,3,0,2,4,0,3,...,0,0,0,1,0,0,2,0,0,0
152.0,1,0,0,0,3,0,3,3,0,1,...,1,1,1,0,1,0,1,0,0,0
154.0,4,0,4,2,1,1,1,4,0,2,...,0,2,2,1,0,2,0,0,0,0
155.0,0,0,5,3,1,4,1,2,0,3,...,1,0,2,3,0,0,0,0,0,0
162.0,0,1,4,0,0,0,0,0,1,2,...,86,0,2,0,0,0,2,0,0,0
170.0,1,2,2,1,2,1,1,3,2,2,...,3,65,0,2,0,3,1,0,0,0
186.9,3,0,2,0,0,1,0,6,5,5,...,2,1,53,2,2,1,3,0,0,0
198.0,2,2,5,2,1,1,3,2,1,5,...,2,0,2,53,0,1,0,0,0,0
213.9,1,1,0,1,0,0,2,7,2,9,...,2,0,3,1,61,0,3,0,0,0
218.0,3,1,0,1,0,0,3,2,2,6,...,0,2,4,0,1,57,5,0,1,0
240.2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,98,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [226]:
eval_result20.index = eval_result20.index + 1
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.810000,0.810000,0.190000,0.010293,0.757009,0.810000,0.782609,0.242991,0.190000,0.539472
2,7.1,0.810000,0.810000,0.190000,0.006754,0.826531,0.810000,0.818182,0.173469,0.190000,0.512251
3,18.9,0.700000,0.700000,0.300000,0.011858,0.700000,0.700000,0.700000,0.300000,0.300000,0.589242
4,32.1,0.850000,0.850000,0.150000,0.009901,0.772727,0.850000,0.809524,0.227273,0.150000,0.806957
5,41.0,0.810000,0.810000,0.190000,0.009116,0.778846,0.810000,0.794118,0.221154,0.190000,0.608359
6,98.9,0.660000,0.660000,0.340000,0.007149,0.785714,0.660000,0.717391,0.214286,0.340000,0.518524
7,104.1,0.710000,0.710000,0.290000,0.009509,0.747368,0.710000,0.728205,0.252632,0.290000,0.713801
8,111.0,0.720000,0.720000,0.280000,0.018453,0.605042,0.720000,0.657534,0.394958,0.280000,0.672334
9,128.0,0.910000,0.910000,0.090000,0.009116,0.798246,0.910000,0.850467,0.201754,0.090000,0.573103
10,129.0,0.860000,0.860000,0.140000,0.027237,0.551282,0.860000,0.671875,0.448718,0.140000,0.878997
11,146.0,0.800000,0.800000,0.200000,0.007543,0.808081,0.800000,0.804020,0.191919,0.200000,0.637986
12,147.0,0.830000,0.830000,0.170000,0.012638,0.721739,0.830000,0.772093,0.278261,0.170000,0.834406
13,150.0,0.800000,0.800000,0.200000,0.013418,0.701754,0.800000,0.747664,0.298246,0.200000,0.699007
14,151.0,0.800000,0.800000,0.200000,0.006754,0.824742,0.800000,0.812183,0.175258,0.200000,0.760611
15,153.0,0.650000,0.650000,0.350000,0.011858,0.684211,0.650000,0.666667,0.315789,0.350000,1.087742
16,154.0,0.640000,0.640000,0.360000,0.011858,0.680851,0.640000,0.659794,0.319149,0.360000,0.761861
17,161.0,0.860000,0.860000,0.140000,0.005569,0.860000,0.860000,0.860000,0.140000,0.140000,0.796599
18,169.0,0.650000,0.650000,0.350000,0.005173,0.833333,0.650000,0.730337,0.166667,0.350000,0.856870
19,185.9,0.530000,0.530000,0.470000,0.009116,0.697368,0.530000,0.602273,0.302632,0.470000,0.231378
20,197.0,0.530000,0.530000,0.470000,0.007149,0.746479,0.530000,0.619883,0.253521,0.470000,0.227670
21,212.9,0.610000,0.610000,0.390000,0.002394,0.910448,0.610000,0.730539,0.089552,0.390000,0.224244
22,217.0,0.570000,0.570000,0.430000,0.005569,0.802817,0.570000,0.666667,0.197183,0.430000,0.221065
23,239.2,0.990000,0.990000,0.010000,0.014196,0.733333,0.990000,0.842553,0.266667,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,2.413158
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.772308,0.772308,0.227692,0.008993,0.780693,0.772308,0.769985,0.219307,0.227692,0.621755

In [227]:
Confusion_df20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier20.csv')
eval_result20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier20.csv', index=False)

## LOAD & APPLY MODEL dTOP30fi

In [228]:
# test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

In [229]:
# Separate features and tp_ICD_cl0 variable for test_data30
X_test30 = test_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_test30 = test_data30['tp_ICD_cl0']

In [230]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier30.pkl', 'rb') as f:
    knn_30 = pickle.load(f)

### EVALUATION & SAVE

In [231]:
prob30 = knn_30.predict_proba(X_test30)
classes30 = knn_30.classes_

y_pred30, data_top_5 = get_predictions(prob30, classes30, threshold, 10, np.array(y_test30), le)

Confusion_df30 = pd.DataFrame(confusion_matrix(np.array(y_test30), y_pred30))
Confusion_df30.index, Confusion_df30.columns = le.inverse_transform(classes30), le.inverse_transform(classes30)

eval_result30 = calculate_evaluation_metrics(Confusion_df=Confusion_df30)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [232]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.304348,41.0,0.173913,98.9,0.130435,146.0,0.130435,185.9,0.130435
2,185.9,153.0,0.217391,147.0,0.130435,197.0,0.130435,5.0,0.086957,129.0,0.086957
3,248.0,248.0,0.478261,251.0,0.260870,249.0,0.217391,41.0,0.043478,NaN,NaN
4,146.0,104.1,0.130435,18.9,0.086957,111.0,0.086957,129.0,0.086957,146.0,0.086957
5,251.0,249.0,0.391304,251.0,0.391304,248.0,0.217391,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.260870,150.0,0.173913,151.0,0.173913,129.0,0.086957,147.0,0.086957
2597,18.9,18.9,0.173913,129.0,0.173913,154.0,0.173913,151.0,0.130435,150.0,0.086957
2598,217.0,98.9,0.217391,104.1,0.130435,147.0,0.130435,111.0,0.086957,129.0,0.086957
2599,104.1,104.1,0.304348,146.0,0.173913,5.0,0.130435,18.9,0.086957,111.0,0.086957
2600,251.0,251.0,0.652174,248.0,0.173913,249.0,0.173913,NaN,NaN,NaN,NaN

In [233]:
Confusion_df30.index = Confusion_df30.index + 1
Confusion_df30
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,1,0,0,1,1,0,1,...,0,1,1,0,1,0,2,0,0,0
8.1,0,80,0,2,0,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,2,0,77,2,3,0,0,1,1,5,...,2,0,1,0,0,0,2,0,0,0
33.1,1,0,0,86,0,0,2,1,1,0,...,0,0,1,1,0,0,1,0,0,0
42.0,0,0,0,3,83,1,0,1,0,3,...,0,0,0,0,0,2,6,0,0,0
99.9,0,1,3,1,1,66,2,1,0,5,...,1,0,0,0,1,0,3,0,1,0
105.1,1,1,4,1,2,1,78,1,2,2,...,1,0,2,0,0,0,0,0,0,0
112.0,2,2,1,0,0,1,1,75,0,4,...,2,2,0,1,0,0,1,0,0,0
129.0,0,0,0,1,0,0,0,1,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,2,0,0,0,0,0,2,0,88,...,0,0,2,1,0,0,0,0,0,0
147.0,1,0,1,1,0,1,2,0,2,3,...,2,1,2,0,0,1,0,0,0,0
148.0,1,1,2,0,1,0,1,2,0,2,...,0,0,2,0,1,1,0,0,0,0
151.0,0,0,1,1,1,0,1,5,0,2,...,0,0,0,3,2,0,3,0,0,0
152.0,0,0,0,0,3,2,1,2,0,1,...,1,1,2,0,1,0,0,0,0,0
154.0,4,0,7,1,1,0,1,6,0,4,...,0,0,1,0,0,1,0,0,0,0
155.0,2,0,1,1,0,0,1,1,0,6,...,2,0,0,4,1,1,1,0,0,0
162.0,2,0,0,1,1,0,1,0,0,2,...,89,1,1,0,0,0,2,0,0,0
170.0,1,2,5,3,3,0,2,2,0,3,...,2,59,2,2,0,2,1,0,0,0
186.9,0,0,1,1,0,1,0,7,5,4,...,2,2,57,1,2,1,3,0,0,0
198.0,2,2,0,0,1,2,2,2,2,7,...,4,1,3,51,0,1,0,0,0,0
213.9,1,0,0,3,0,0,5,5,2,6,...,1,0,2,1,60,0,4,0,0,0
218.0,1,0,4,2,0,1,4,3,2,4,...,0,0,3,0,1,63,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,97,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [234]:
eval_result30.index = eval_result30.index + 1
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.009116,0.787037,0.850000,0.817308,0.212963,0.150000,0.581222
2,7.1,0.800000,0.800000,0.200000,0.004381,0.879121,0.800000,0.837696,0.120879,0.200000,0.557659
3,18.9,0.770000,0.770000,0.230000,0.011858,0.719626,0.770000,0.743961,0.280374,0.230000,0.655118
4,32.1,0.860000,0.860000,0.140000,0.009901,0.774775,0.860000,0.815166,0.225225,0.140000,0.659805
5,41.0,0.830000,0.830000,0.170000,0.006754,0.830000,0.830000,0.830000,0.170000,0.170000,0.421461
6,98.9,0.660000,0.660000,0.340000,0.004381,0.857143,0.660000,0.745763,0.142857,0.340000,0.630606
7,104.1,0.780000,0.780000,0.220000,0.010685,0.742857,0.780000,0.760976,0.257143,0.220000,0.898879
8,111.0,0.750000,0.750000,0.250000,0.017296,0.630252,0.750000,0.684932,0.369748,0.250000,0.642943
9,128.0,0.910000,0.910000,0.090000,0.007149,0.834862,0.910000,0.870813,0.165138,0.090000,0.623177
10,129.0,0.880000,0.880000,0.120000,0.026101,0.567742,0.880000,0.690196,0.432258,0.120000,0.932918
11,146.0,0.760000,0.760000,0.240000,0.007543,0.800000,0.760000,0.779487,0.200000,0.240000,0.749395
12,147.0,0.800000,0.800000,0.200000,0.014584,0.683761,0.800000,0.737327,0.316239,0.200000,0.678388
13,150.0,0.770000,0.770000,0.230000,0.011858,0.719626,0.770000,0.743961,0.280374,0.230000,0.569024
14,151.0,0.780000,0.780000,0.220000,0.008330,0.787879,0.780000,0.783920,0.212121,0.220000,0.717160
15,153.0,0.640000,0.640000,0.360000,0.009509,0.727273,0.640000,0.680851,0.272727,0.360000,0.834802
16,154.0,0.670000,0.670000,0.330000,0.014196,0.650485,0.670000,0.660099,0.349515,0.330000,0.558664
17,161.0,0.890000,0.890000,0.110000,0.008723,0.801802,0.890000,0.843602,0.198198,0.110000,1.097000
18,169.0,0.590000,0.590000,0.410000,0.003984,0.855072,0.590000,0.698225,0.144928,0.410000,0.235409
19,185.9,0.570000,0.570000,0.430000,0.010293,0.686747,0.570000,0.622951,0.313253,0.430000,0.231378
20,197.0,0.510000,0.510000,0.490000,0.006359,0.761194,0.510000,0.610778,0.238806,0.490000,0.227670
21,212.9,0.600000,0.600000,0.400000,0.004381,0.845070,0.600000,0.701754,0.154930,0.400000,0.224244
22,217.0,0.630000,0.630000,0.370000,0.004777,0.840000,0.630000,0.720000,0.160000,0.370000,0.221065
23,239.2,0.990000,0.990000,0.010000,0.013418,0.744361,0.990000,0.849785,0.255639,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.970000,0.970000,0.030000,0.000799,0.979798,0.970000,0.974874,0.020202,0.030000,2.262941
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.779231,0.779231,0.220769,0.008722,0.788330,0.779231,0.776902,0.211670,0.220769,0.585036

In [235]:
Confusion_df30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier30.csv')
eval_result30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier30.csv', index=False)

## LOAD & APPLY MODEL dTOP40fi

In [236]:
# test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

In [237]:
# Separate features and tp_ICD_cl0 variable for test_data40
X_test40 = test_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_test40 = test_data40['tp_ICD_cl0']

In [238]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier40.pkl', 'rb') as f:
    knn_40 = pickle.load(f)

### EVALUATION & SAVE

In [239]:
prob40 = knn_40.predict_proba(X_test40)
classes40 = knn_40.classes_

y_pred40, data_top_5 = get_predictions(prob40, classes40, threshold, 10, np.array(y_test40), le)

Confusion_df40 = pd.DataFrame(confusion_matrix(np.array(y_test40), y_pred40))
Confusion_df40.index, Confusion_df40.columns = le.inverse_transform(classes40), le.inverse_transform(classes40)

eval_result40 = calculate_evaluation_metrics(Confusion_df=Confusion_df40)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [240]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,185.9,0.142857,98.9,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.476190,251.0,0.238095,249.0,0.190476,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,251.0,0.428571,249.0,0.333333,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.190476,151.0,0.190476,185.9,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,185.9,0.238095,98.9,0.190476,111.0,0.142857,104.1,0.095238,146.0,0.095238
2599,104.1,104.1,0.285714,146.0,0.190476,5.0,0.142857,18.9,0.095238,212.9,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [241]:
Confusion_df40.index = Confusion_df40.index + 1
Confusion_df40
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,82,0,0,2,1,0,2,1,0,1,...,0,1,1,0,1,0,3,0,0,0
8.1,0,79,0,1,1,1,0,0,0,4,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,77,2,1,0,0,1,1,6,...,2,0,2,0,0,0,2,0,0,0
33.1,1,0,0,85,1,0,1,0,2,1,...,0,1,1,1,0,0,1,0,0,0
42.0,1,0,0,2,82,1,0,3,0,3,...,0,0,0,0,0,1,6,0,0,0
99.9,2,2,2,1,2,64,2,2,1,3,...,1,0,0,1,1,0,4,0,1,0
105.1,0,1,2,4,1,1,75,1,2,3,...,1,0,3,1,0,1,0,0,0,0
112.0,2,0,1,0,0,1,1,75,1,5,...,2,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,1,0,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,0,1,0,90,...,0,0,1,1,0,0,0,0,0,0
147.0,0,1,1,0,1,1,2,1,2,3,...,1,0,2,0,0,2,2,0,0,0
148.0,0,1,2,0,1,0,1,1,0,3,...,1,0,1,1,1,1,0,0,0,0
151.0,1,0,2,0,1,0,1,3,1,3,...,0,0,1,3,1,0,2,0,0,0
152.0,0,0,0,0,3,1,0,1,0,1,...,2,0,2,0,1,1,0,0,0,0
154.0,4,0,5,1,0,0,2,3,0,3,...,0,0,5,2,0,1,2,0,0,0
155.0,1,0,3,1,0,2,0,1,0,3,...,0,0,1,3,1,1,2,0,0,0
162.0,1,0,0,1,0,0,0,0,0,1,...,95,0,0,0,0,0,2,0,0,0
170.0,1,1,5,2,1,0,0,2,3,1,...,1,66,1,2,0,4,1,0,0,0
186.9,1,0,3,2,0,1,1,5,5,4,...,2,1,60,2,0,1,2,0,0,0
198.0,3,3,3,1,2,1,2,1,2,5,...,3,0,2,52,0,2,0,0,0,0
213.9,3,0,0,1,0,0,3,4,2,8,...,3,0,1,4,61,0,3,0,0,0
218.0,3,0,5,2,0,0,2,1,2,2,...,0,0,3,1,0,67,2,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,98,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [242]:
eval_result40.index = eval_result40.index + 1
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.820000,0.820000,0.180000,0.010685,0.752294,0.820000,0.784689,0.247706,0.180000,0.601554
2,7.1,0.790000,0.790000,0.210000,0.003984,0.887640,0.790000,0.835979,0.112360,0.210000,0.564717
3,18.9,0.770000,0.770000,0.230000,0.013418,0.693694,0.770000,0.729858,0.306306,0.230000,0.526406
4,32.1,0.850000,0.850000,0.150000,0.009116,0.787037,0.850000,0.817308,0.212963,0.150000,0.670137
5,41.0,0.820000,0.820000,0.180000,0.006754,0.828283,0.820000,0.824121,0.171717,0.180000,0.433914
6,98.9,0.640000,0.640000,0.360000,0.003984,0.864865,0.640000,0.735632,0.135135,0.360000,0.807206
7,104.1,0.750000,0.750000,0.250000,0.007937,0.789474,0.750000,0.769231,0.210526,0.250000,0.769018
8,111.0,0.750000,0.750000,0.250000,0.012638,0.700935,0.750000,0.724638,0.299065,0.250000,0.602924
9,128.0,0.910000,0.910000,0.090000,0.009901,0.784483,0.910000,0.842593,0.215517,0.090000,0.580030
10,129.0,0.900000,0.900000,0.100000,0.024581,0.588235,0.900000,0.711462,0.411765,0.100000,0.723588
11,146.0,0.760000,0.760000,0.240000,0.006359,0.826087,0.760000,0.791667,0.173913,0.240000,0.718067
12,147.0,0.840000,0.840000,0.160000,0.013028,0.717949,0.840000,0.774194,0.282051,0.160000,0.781073
13,150.0,0.780000,0.780000,0.220000,0.008330,0.787879,0.780000,0.783920,0.212121,0.220000,0.744629
14,151.0,0.810000,0.810000,0.190000,0.007937,0.801980,0.810000,0.805970,0.198020,0.190000,0.582470
15,153.0,0.650000,0.650000,0.350000,0.010685,0.706522,0.650000,0.677083,0.293478,0.350000,0.909829
16,154.0,0.670000,0.670000,0.330000,0.012638,0.676768,0.670000,0.673367,0.323232,0.330000,0.647261
17,161.0,0.950000,0.950000,0.050000,0.008330,0.818966,0.950000,0.879630,0.181034,0.050000,0.965581
18,169.0,0.660000,0.660000,0.340000,0.001597,0.942857,0.660000,0.776471,0.057143,0.340000,0.771032
19,185.9,0.600000,0.600000,0.400000,0.011076,0.681818,0.600000,0.638298,0.318182,0.400000,0.231378
20,197.0,0.520000,0.520000,0.480000,0.009509,0.684211,0.520000,0.590909,0.315789,0.480000,0.227670
21,212.9,0.610000,0.610000,0.390000,0.002792,0.897059,0.610000,0.726190,0.102941,0.390000,0.224244
22,217.0,0.670000,0.670000,0.330000,0.006754,0.797619,0.670000,0.728261,0.202381,0.330000,0.827246
23,239.2,0.990000,0.990000,0.010000,0.014584,0.727941,0.990000,0.838983,0.272059,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,7.967723
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.788077,0.788077,0.211923,0.008378,0.796719,0.788077,0.785980,0.203281,0.211923,0.841450

In [243]:
Confusion_df40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier40.csv')
eval_result40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier40.csv', index=False)

## LOAD & APPLY MODEL dTOP50fi

In [244]:
# test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

In [245]:
# Separate features and tp_ICD_cl0 variable for test_data50
X_test50 = test_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_test50 = test_data50['tp_ICD_cl0']

In [246]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier50.pkl', 'rb') as f:
    knn_50 = pickle.load(f)

### EVALUATION & SAVE

In [247]:
prob50 = knn_50.predict_proba(X_test50)
classes50 = knn_50.classes_

y_pred50, data_top_5 = get_predictions(prob50, classes50, threshold, 10, np.array(y_test50), le)

Confusion_df50 = pd.DataFrame(confusion_matrix(np.array(y_test50), y_pred50))
Confusion_df50.index, Confusion_df50.columns = le.inverse_transform(classes50), le.inverse_transform(classes50)

eval_result50 = calculate_evaluation_metrics(Confusion_df=Confusion_df50)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [248]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.23750,41.0,0.18125,169.0,0.08125,150.0,0.06875,129.0,0.05625
2,185.9,239.2,0.11250,197.0,0.08750,111.0,0.08125,153.0,0.06875,98.9,0.06250
3,248.0,251.0,0.25000,248.0,0.19375,249.0,0.19375,5.0,0.13125,32.1,0.12500
4,146.0,154.0,0.09375,129.0,0.08125,217.0,0.07500,197.0,0.06875,5.0,0.06250
5,251.0,251.0,0.41250,249.0,0.36250,248.0,0.22500,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,129.0,0.10000,154.0,0.09375,18.9,0.08125,197.0,0.07500,217.0,0.06875
2597,18.9,153.0,0.10625,154.0,0.10625,151.0,0.08750,150.0,0.08125,129.0,0.07500
2598,217.0,98.9,0.15000,185.9,0.11250,104.1,0.09375,217.0,0.08750,111.0,0.08125
2599,104.1,104.1,0.13125,185.9,0.13125,129.0,0.08125,18.9,0.06250,197.0,0.06250
2600,251.0,248.0,0.35625,251.0,0.33125,249.0,0.30625,NaN,NaN,NaN,NaN

In [249]:
Confusion_df50.index = Confusion_df50.index + 1
Confusion_df50
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,61,0,1,3,0,0,2,0,0,9,...,0,0,1,2,0,0,11,0,0,0
8.1,0,65,2,0,0,1,2,1,1,5,...,3,0,1,1,1,1,6,0,0,0
19.9,4,0,72,3,3,1,0,1,0,1,...,4,0,0,0,0,0,5,0,0,2
33.1,0,0,1,77,0,0,1,1,1,1,...,2,0,2,1,0,0,7,0,0,0
42.0,0,0,0,4,76,0,0,1,0,3,...,0,0,0,0,0,0,11,0,0,0
99.9,0,0,1,2,2,51,2,3,0,9,...,4,0,2,0,0,0,4,0,0,1
105.1,0,1,5,1,0,0,58,1,6,3,...,3,0,0,2,0,1,7,0,0,0
112.0,0,0,2,1,1,0,0,66,0,3,...,2,0,0,3,0,0,4,0,0,0
129.0,0,1,2,1,0,0,0,0,86,1,...,1,0,1,0,0,1,1,0,0,0
130.0,1,0,0,0,0,0,1,0,0,96,...,0,0,0,0,0,0,1,0,0,0
147.0,0,1,1,0,1,1,1,5,3,11,...,0,1,1,1,1,0,7,0,0,0
148.0,0,0,4,0,2,0,0,4,0,9,...,4,1,1,0,0,0,3,0,0,0
151.0,0,0,2,0,4,0,0,1,1,4,...,3,0,0,1,0,0,6,0,0,0
152.0,1,0,3,0,0,0,0,3,1,7,...,4,0,2,2,0,0,2,0,0,0
154.0,0,0,6,1,0,1,0,1,1,5,...,0,0,1,0,0,0,4,0,0,0
155.0,0,0,0,0,1,1,0,2,0,3,...,0,0,2,1,0,0,2,0,0,0
162.0,0,1,0,4,1,0,0,0,0,3,...,82,0,1,0,0,0,5,0,0,0
170.0,0,2,6,4,1,0,0,3,0,7,...,0,53,2,1,0,0,4,0,0,0
186.9,0,0,2,2,0,0,1,2,5,4,...,7,0,56,1,0,0,3,0,0,0
198.0,0,0,4,1,4,2,0,1,0,5,...,2,0,1,70,0,0,6,0,0,0
213.9,0,0,1,1,0,1,0,1,1,5,...,5,1,0,0,73,0,2,0,0,0
218.0,0,0,1,2,0,1,0,1,1,6,...,1,0,1,0,0,74,3,0,0,2
240.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,100,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,96,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [250]:
eval_result50.index = eval_result50.index + 1
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.610000,0.610000,0.390000,0.002394,0.910448,0.610000,0.730539,0.089552,0.390000,1.000000
2,7.1,0.650000,0.650000,0.350000,0.002394,0.915493,0.650000,0.760234,0.084507,0.350000,0.486092
3,18.9,0.720000,0.720000,0.280000,0.017296,0.620690,0.720000,0.666667,0.379310,0.280000,0.816154
4,32.1,0.770000,0.770000,0.230000,0.011858,0.719626,0.770000,0.743961,0.280374,0.230000,0.378297
5,41.0,0.760000,0.760000,0.240000,0.007937,0.791667,0.760000,0.775510,0.208333,0.240000,0.350252
6,98.9,0.510000,0.510000,0.490000,0.003587,0.850000,0.510000,0.637500,0.150000,0.490000,0.356207
7,104.1,0.580000,0.580000,0.420000,0.004381,0.840580,0.580000,0.686391,0.159420,0.420000,0.333333
8,111.0,0.660000,0.660000,0.340000,0.012638,0.673469,0.660000,0.666667,0.326531,0.340000,0.528449
9,128.0,0.860000,0.860000,0.140000,0.008330,0.803738,0.860000,0.830918,0.196262,0.140000,0.699286
10,129.0,0.960000,0.960000,0.040000,0.039939,0.480000,0.960000,0.640000,0.520000,0.040000,1.607895
11,146.0,0.610000,0.610000,0.390000,0.002394,0.910448,0.610000,0.730539,0.089552,0.390000,0.278943
12,147.0,0.690000,0.690000,0.310000,0.020760,0.565574,0.690000,0.621622,0.434426,0.310000,0.483806
13,150.0,0.670000,0.670000,0.330000,0.007149,0.788235,0.670000,0.724324,0.211765,0.330000,0.516223
14,151.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.526088
15,153.0,0.770000,0.770000,0.230000,0.011858,0.719626,0.770000,0.743961,0.280374,0.230000,0.723084
16,154.0,0.820000,0.820000,0.180000,0.024961,0.561644,0.820000,0.666667,0.438356,0.180000,0.565580
17,161.0,0.820000,0.820000,0.180000,0.017682,0.645669,0.820000,0.722467,0.354331,0.180000,0.547696
18,169.0,0.530000,0.530000,0.470000,0.001199,0.946429,0.530000,0.679487,0.053571,0.470000,0.235409
19,185.9,0.560000,0.560000,0.440000,0.007543,0.746667,0.560000,0.640000,0.253333,0.440000,0.231378
20,197.0,0.700000,0.700000,0.300000,0.006754,0.804598,0.700000,0.748663,0.195402,0.300000,0.562035
21,212.9,0.730000,0.730000,0.270000,0.000799,0.973333,0.730000,0.834286,0.026667,0.270000,0.536816
22,217.0,0.740000,0.740000,0.260000,0.001597,0.948718,0.740000,0.831461,0.051282,0.260000,0.516178
23,239.2,1.000000,1.000000,0.000000,0.039939,0.490196,1.000000,0.657895,0.509804,0.000000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.885184
26,251.0,1.000000,1.000000,0.000000,0.001996,0.952381,1.000000,0.975610,0.047619,0.000000,0.000000
27,average,0.744615,0.744615,0.255385,0.009991,0.789230,0.744615,0.748259,0.210770,0.255385,0.506322

In [251]:
Confusion_df50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier50.csv')
eval_result50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier50.csv', index=False)

## LOAD & APPLY MODEL dTOP60fi

In [252]:
# test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

In [253]:
# Separate features and tp_ICD_cl0 variable for test_data60
X_test60 = test_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_test60 = test_data60['tp_ICD_cl0']

In [254]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier60.pkl', 'rb') as f:
    knn_60 = pickle.load(f)

### EVALUATION & SAVE

In [255]:
prob60 = knn_60.predict_proba(X_test60)
classes60 = knn_60.classes_

y_pred60, data_top_5 = get_predictions(prob60, classes60, threshold, 10, np.array(y_test60), le)

Confusion_df60 = pd.DataFrame(confusion_matrix(np.array(y_test60), y_pred60))
Confusion_df60.index, Confusion_df60.columns = le.inverse_transform(classes60), le.inverse_transform(classes60)

eval_result60 = calculate_evaluation_metrics(Confusion_df=Confusion_df60)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [256]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,185.9,0.142857,98.9,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.523810,251.0,0.238095,249.0,0.142857,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.190476,151.0,0.190476,185.9,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,7.1,0.285714,98.9,0.238095,111.0,0.095238,146.0,0.095238,147.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,212.9,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [257]:
Confusion_df60.index = Confusion_df60.index + 1
Confusion_df60
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,86,0,0,0,0,0,1,0,0,1,...,0,0,1,0,1,0,3,0,0,0
8.1,0,79,0,1,1,1,0,0,0,4,...,2,1,1,0,0,1,2,0,0,1
19.9,1,0,76,2,1,1,0,1,1,6,...,1,0,1,0,1,0,2,0,0,0
33.1,1,0,0,86,0,0,1,1,2,0,...,1,0,1,1,0,0,1,0,0,0
42.0,0,0,0,4,86,1,0,1,0,3,...,1,0,0,0,0,1,3,0,0,0
99.9,0,2,2,3,2,64,2,3,1,3,...,1,0,0,1,1,0,3,0,1,0
105.1,0,1,0,4,1,2,78,0,2,5,...,1,0,1,1,0,0,1,0,0,0
112.0,1,0,2,0,1,1,1,75,1,4,...,1,0,0,2,0,0,1,0,0,0
129.0,0,0,0,0,1,0,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,2,1,0,0,0,0,0,3,0,88,...,0,0,1,1,0,0,0,0,0,0
147.0,0,1,1,1,1,2,2,1,2,3,...,1,0,2,0,0,1,2,0,0,0
148.0,0,1,2,0,1,0,1,0,0,3,...,1,0,1,0,1,1,0,0,0,0
151.0,0,0,1,1,1,0,2,3,2,3,...,0,0,1,3,0,1,2,0,0,0
152.0,0,0,0,0,3,1,0,3,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,4,0,4,1,0,0,1,4,1,1,...,0,0,5,2,0,1,4,0,0,0
155.0,1,0,3,1,1,3,1,2,0,3,...,0,0,0,4,0,1,0,0,0,0
162.0,1,1,0,2,1,1,0,0,0,0,...,93,0,0,0,0,0,1,0,0,0
170.0,1,1,4,2,1,0,0,3,2,2,...,1,67,1,2,0,3,2,0,0,0
186.9,2,0,2,1,0,1,1,6,5,4,...,2,1,60,2,0,1,2,0,0,0
198.0,2,3,2,1,2,1,1,2,2,6,...,4,0,2,54,0,1,1,0,0,0
213.9,2,0,1,1,0,0,4,3,1,7,...,2,0,1,4,60,0,5,0,0,0
218.0,2,0,5,1,0,1,2,1,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,98,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [258]:
eval_result60.index = eval_result60.index + 1
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.860000,0.860000,0.140000,0.008330,0.803738,0.860000,0.830918,0.196262,0.140000,0.457828
2,7.1,0.790000,0.790000,0.210000,0.004381,0.877778,0.790000,0.831579,0.122222,0.210000,0.562941
3,18.9,0.760000,0.760000,0.240000,0.011467,0.723810,0.760000,0.741463,0.276190,0.240000,0.531005
4,32.1,0.860000,0.860000,0.140000,0.010293,0.767857,0.860000,0.811321,0.232143,0.140000,0.649480
5,41.0,0.860000,0.860000,0.140000,0.007149,0.826923,0.860000,0.843137,0.173077,0.140000,0.657036
6,98.9,0.640000,0.640000,0.360000,0.006359,0.800000,0.640000,0.711111,0.200000,0.360000,0.854258
7,104.1,0.780000,0.780000,0.220000,0.007937,0.795918,0.780000,0.787879,0.204082,0.220000,0.633829
8,111.0,0.750000,0.750000,0.250000,0.014584,0.669643,0.750000,0.707547,0.330357,0.250000,0.658746
9,128.0,0.910000,0.910000,0.090000,0.009901,0.784483,0.910000,0.842593,0.215517,0.090000,0.580030
10,129.0,0.880000,0.880000,0.120000,0.023438,0.594595,0.880000,0.709677,0.405405,0.120000,0.830353
11,146.0,0.740000,0.740000,0.260000,0.006359,0.822222,0.740000,0.778947,0.177778,0.260000,0.736577
12,147.0,0.850000,0.850000,0.150000,0.011858,0.739130,0.850000,0.790698,0.260870,0.150000,0.744282
13,150.0,0.770000,0.770000,0.230000,0.007937,0.793814,0.770000,0.781726,0.206186,0.230000,0.692614
14,151.0,0.840000,0.840000,0.160000,0.007937,0.807692,0.840000,0.823529,0.192308,0.160000,0.670519
15,153.0,0.630000,0.630000,0.370000,0.010685,0.700000,0.630000,0.663158,0.300000,0.370000,0.250000
16,154.0,0.670000,0.670000,0.330000,0.014196,0.650485,0.670000,0.660099,0.349515,0.330000,0.649395
17,161.0,0.930000,0.930000,0.070000,0.007543,0.830357,0.930000,0.877358,0.169643,0.070000,1.256720
18,169.0,0.670000,0.670000,0.330000,0.000799,0.971014,0.670000,0.792899,0.028986,0.330000,0.799015
19,185.9,0.600000,0.600000,0.400000,0.009509,0.714286,0.600000,0.652174,0.285714,0.400000,0.231378
20,197.0,0.540000,0.540000,0.460000,0.009509,0.692308,0.540000,0.606742,0.307692,0.460000,0.227670
21,212.9,0.600000,0.600000,0.400000,0.002394,0.909091,0.600000,0.722892,0.090909,0.400000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.005569,0.829268,0.680000,0.747253,0.170732,0.320000,0.830681
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,7.967723
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.791538,0.791538,0.208462,0.008242,0.799890,0.791538,0.789430,0.200110,0.208462,0.834474

In [259]:
Confusion_df60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier60.csv')
eval_result60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier60.csv', index=False)

## LOAD & APPLY MODEL dTOP70fi

In [260]:
# test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

In [261]:
# Separate features and tp_ICD_cl0 variable for test_data70
X_test70 = test_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_test70 = test_data70['tp_ICD_cl0']

In [262]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier70.pkl', 'rb') as f:
    knn_70 = pickle.load(f)

### EVALUATION & SAVE

In [263]:
prob70 = knn_70.predict_proba(X_test70)
classes70 = knn_70.classes_

y_pred70, data_top_5 = get_predictions(prob70, classes70, threshold, 10, np.array(y_test70), le)

Confusion_df70 = pd.DataFrame(confusion_matrix(np.array(y_test70), y_pred70))
Confusion_df70.index, Confusion_df70.columns = le.inverse_transform(classes70), le.inverse_transform(classes70)

eval_result70 = calculate_evaluation_metrics(Confusion_df=Confusion_df70)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [264]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,185.9,0.142857,98.9,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.523810,249.0,0.190476,251.0,0.190476,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.142857,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.428571,5.0,0.142857,185.9,0.142857,18.9,0.095238,111.0,0.047619
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [265]:
Confusion_df70.index = Confusion_df70.index + 1
Confusion_df70
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,1,1,1,0,0,0,4,...,2,1,1,0,0,1,2,0,0,1
19.9,1,0,75,2,1,0,0,2,1,5,...,1,1,1,0,1,0,2,0,0,0
33.1,1,0,0,86,0,0,1,0,2,0,...,1,1,1,1,0,0,1,0,0,0
42.0,0,1,0,5,86,1,0,1,0,3,...,0,0,0,1,0,0,2,0,0,0
99.9,0,2,2,4,4,63,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,2,2,1,79,2,2,4,...,0,0,0,1,0,0,1,0,0,0
112.0,1,0,3,0,0,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,0,0,1,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,89,...,0,0,2,1,0,0,0,0,0,0
147.0,0,1,1,1,0,3,2,0,2,3,...,2,1,3,0,0,1,1,0,0,0
148.0,0,1,2,0,1,0,1,1,0,2,...,1,0,0,1,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,2,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,0,0,0,3,1,0,2,0,1,...,0,0,2,0,1,1,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,1,0,3,1,1,4,1,2,0,3,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,1,0,2,0,0,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,2,0,1,2,2,3,...,1,66,1,2,0,2,2,0,0,0
186.9,2,0,2,1,0,1,1,5,5,4,...,2,1,60,2,0,1,3,0,0,0
198.0,3,3,1,1,1,1,2,2,2,6,...,4,1,2,51,0,1,1,0,0,0
213.9,2,0,2,1,0,0,5,3,1,6,...,2,0,2,3,59,1,5,0,0,0
218.0,2,0,5,2,0,2,2,1,2,1,...,0,0,2,0,0,67,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,97,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [266]:
eval_result70.index = eval_result70.index + 1
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.471112
2,7.1,0.790000,0.790000,0.210000,0.005173,0.858696,0.790000,0.822917,0.141304,0.210000,0.564409
3,18.9,0.750000,0.750000,0.250000,0.013028,0.694444,0.750000,0.721154,0.305556,0.250000,0.586393
4,32.1,0.860000,0.860000,0.140000,0.010685,0.761062,0.860000,0.807512,0.238938,0.140000,0.640028
5,41.0,0.860000,0.860000,0.140000,0.007149,0.826923,0.860000,0.843137,0.173077,0.140000,0.694029
6,98.9,0.630000,0.630000,0.370000,0.007149,0.777778,0.630000,0.696133,0.222222,0.370000,0.356207
7,104.1,0.790000,0.790000,0.210000,0.009509,0.766990,0.790000,0.778325,0.233010,0.210000,0.686511
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.614441
9,128.0,0.910000,0.910000,0.090000,0.009901,0.784483,0.910000,0.842593,0.215517,0.090000,0.565036
10,129.0,0.890000,0.890000,0.110000,0.021909,0.613793,0.890000,0.726531,0.386207,0.110000,0.692468
11,146.0,0.730000,0.730000,0.270000,0.007543,0.793478,0.730000,0.760417,0.206522,0.270000,0.732379
12,147.0,0.860000,0.860000,0.140000,0.011467,0.747826,0.860000,0.800000,0.252174,0.140000,0.920554
13,150.0,0.760000,0.760000,0.240000,0.007543,0.800000,0.760000,0.779487,0.200000,0.240000,0.659777
14,151.0,0.840000,0.840000,0.160000,0.009509,0.777778,0.840000,0.807692,0.222222,0.160000,0.664050
15,153.0,0.630000,0.630000,0.370000,0.011076,0.692308,0.630000,0.659686,0.307692,0.370000,0.250000
16,154.0,0.680000,0.680000,0.320000,0.014584,0.647619,0.680000,0.663415,0.352381,0.320000,0.672705
17,161.0,0.900000,0.900000,0.100000,0.008330,0.810811,0.900000,0.853081,0.189189,0.100000,1.096707
18,169.0,0.660000,0.660000,0.340000,0.002394,0.916667,0.660000,0.767442,0.083333,0.340000,0.785833
19,185.9,0.600000,0.600000,0.400000,0.009509,0.714286,0.600000,0.652174,0.285714,0.400000,0.231378
20,197.0,0.510000,0.510000,0.490000,0.007937,0.718310,0.510000,0.596491,0.281690,0.490000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002394,0.907692,0.590000,0.715152,0.092308,0.410000,0.224244
22,217.0,0.670000,0.670000,0.330000,0.004777,0.848101,0.670000,0.748603,0.151899,0.330000,0.857155
23,239.2,0.990000,0.990000,0.010000,0.014584,0.727941,0.990000,0.838983,0.272059,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.970000,0.970000,0.030000,0.001199,0.970000,0.970000,0.970000,0.030000,0.030000,2.240983
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008457,0.793121,0.786154,0.783331,0.206879,0.213846,0.593618

In [267]:
Confusion_df70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier70.csv')
eval_result70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier70.csv', index=False)

## LOAD & APPLY MODEL dTOP80fi

In [268]:
# test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

In [269]:
# Separate features and tp_ICD_cl0 variable for test_data80
X_test80 = test_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_test80 = test_data80['tp_ICD_cl0']

In [270]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier80.pkl', 'rb') as f:
    knn_80 = pickle.load(f)

### EVALUATION & SAVE

In [271]:
prob80 = knn_80.predict_proba(X_test80)
classes80 = knn_80.classes_

y_pred80, data_top_5 = get_predictions(prob80, classes80, threshold, 10, np.array(y_test80), le)

Confusion_df80 = pd.DataFrame(confusion_matrix(np.array(y_test80), y_pred80))
Confusion_df80.index, Confusion_df80.columns = le.inverse_transform(classes80), le.inverse_transform(classes80)

eval_result80 = calculate_evaluation_metrics(Confusion_df=Confusion_df80)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [272]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.30,41.0,0.20,146.0,0.15,150.0,0.10,151.0,0.10
2,185.9,153.0,0.25,147.0,0.15,197.0,0.15,5.0,0.10,129.0,0.10
3,248.0,248.0,0.55,249.0,0.25,251.0,0.10,5.0,0.05,41.0,0.05
4,146.0,104.1,0.15,111.0,0.10,129.0,0.10,146.0,0.10,147.0,0.10
5,251.0,251.0,0.40,249.0,0.35,248.0,0.25,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.20,151.0,0.20,185.9,0.20,129.0,0.10,147.0,0.10
2597,18.9,18.9,0.20,129.0,0.20,151.0,0.15,150.0,0.10,153.0,0.10
2598,217.0,98.9,0.25,7.1,0.15,104.1,0.10,111.0,0.10,146.0,0.10
2599,104.1,104.1,0.40,5.0,0.15,185.9,0.15,18.9,0.10,111.0,0.05
2600,251.0,251.0,0.70,249.0,0.20,248.0,0.10,NaN,NaN,NaN,NaN

In [273]:
Confusion_df80.index = Confusion_df80.index + 1
Confusion_df80
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,0,0,3,0,0,0
8.1,0,78,0,1,2,1,0,0,0,3,...,1,1,1,0,0,1,2,0,0,1
19.9,2,0,72,3,1,0,0,2,1,5,...,1,1,1,0,1,0,2,0,0,0
33.1,1,0,0,86,0,0,1,1,2,1,...,1,0,1,1,0,0,1,0,0,0
42.0,0,0,0,2,87,1,0,2,0,3,...,0,0,0,0,0,1,2,1,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,1,3,0,1,0
105.1,0,1,1,2,1,1,78,2,2,5,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,2,1,0,0,0,0,1,1,0,89,...,0,0,1,0,0,0,0,0,0,0
147.0,0,1,1,0,0,2,2,1,2,3,...,2,0,1,0,0,2,1,0,0,0
148.0,0,1,3,0,1,1,1,1,0,4,...,1,0,0,0,0,1,0,0,0,0
151.0,0,0,1,0,2,0,2,4,2,3,...,0,0,1,1,0,0,2,0,0,0
152.0,0,0,0,0,3,1,0,1,0,2,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,5,2,0,1,0,2,1,2,...,0,0,3,2,0,1,4,0,0,0
155.0,1,0,5,1,1,4,2,3,0,4,...,0,0,2,2,0,0,0,0,0,0
162.0,1,4,0,2,0,0,0,1,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,4,2,2,0,1,2,3,0,...,1,66,1,2,0,3,3,0,0,0
186.9,2,0,2,2,0,2,0,4,5,4,...,3,1,61,1,1,1,2,0,0,0
198.0,4,3,1,1,1,1,1,2,2,5,...,2,2,3,52,0,1,1,0,0,0
213.9,2,0,1,1,0,1,4,4,1,6,...,3,0,3,3,58,0,5,0,0,0
218.0,2,0,5,2,0,1,3,2,2,1,...,0,0,3,2,0,66,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,98,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [274]:
eval_result80.index = eval_result80.index + 1
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.008723,0.794393,0.850000,0.821256,0.205607,0.150000,0.470847
2,7.1,0.780000,0.780000,0.220000,0.005173,0.857143,0.780000,0.816754,0.142857,0.220000,0.678134
3,18.9,0.720000,0.720000,0.280000,0.013418,0.679245,0.720000,0.699029,0.320755,0.280000,0.664023
4,32.1,0.860000,0.860000,0.140000,0.009901,0.774775,0.860000,0.815166,0.225225,0.140000,0.774007
5,41.0,0.870000,0.870000,0.130000,0.006754,0.836538,0.870000,0.852941,0.163462,0.130000,0.642977
6,98.9,0.650000,0.650000,0.350000,0.007543,0.773810,0.650000,0.706522,0.226190,0.350000,0.818796
7,104.1,0.780000,0.780000,0.220000,0.008723,0.780000,0.780000,0.780000,0.220000,0.220000,0.597357
8,111.0,0.720000,0.720000,0.280000,0.014584,0.660550,0.720000,0.688995,0.339450,0.280000,0.547086
9,128.0,0.910000,0.910000,0.090000,0.010293,0.777778,0.910000,0.838710,0.222222,0.090000,0.573593
10,129.0,0.890000,0.890000,0.110000,0.023056,0.601351,0.890000,0.717742,0.398649,0.110000,0.918107
11,146.0,0.760000,0.760000,0.240000,0.008330,0.783505,0.760000,0.771574,0.216495,0.240000,0.710280
12,147.0,0.840000,0.840000,0.160000,0.011858,0.736842,0.840000,0.785047,0.263158,0.160000,0.706433
13,150.0,0.790000,0.790000,0.210000,0.009116,0.774510,0.790000,0.782178,0.225490,0.210000,0.655660
14,151.0,0.850000,0.850000,0.150000,0.007937,0.809524,0.850000,0.829268,0.190476,0.150000,0.653978
15,153.0,0.650000,0.650000,0.350000,0.009901,0.722222,0.650000,0.684211,0.277778,0.350000,0.871806
16,154.0,0.650000,0.650000,0.350000,0.012248,0.677083,0.650000,0.663265,0.322917,0.350000,0.808341
17,161.0,0.900000,0.900000,0.100000,0.007937,0.818182,0.900000,0.857143,0.181818,0.100000,1.075650
18,169.0,0.660000,0.660000,0.340000,0.002792,0.904110,0.660000,0.763006,0.095890,0.340000,0.759964
19,185.9,0.610000,0.610000,0.390000,0.009509,0.717647,0.610000,0.659459,0.282353,0.390000,0.231378
20,197.0,0.520000,0.520000,0.480000,0.007149,0.742857,0.520000,0.611765,0.257143,0.480000,0.227670
21,212.9,0.580000,0.580000,0.420000,0.001996,0.920635,0.580000,0.711656,0.079365,0.420000,0.224244
22,217.0,0.660000,0.660000,0.340000,0.005569,0.825000,0.660000,0.733333,0.175000,0.340000,0.856751
23,239.2,0.990000,0.990000,0.010000,0.014584,0.727941,0.990000,0.838983,0.272059,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.980000,0.980000,0.020000,0.000799,0.980000,0.980000,0.980000,0.020000,0.020000,7.751670
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.787308,0.787308,0.212692,0.008411,0.794455,0.787308,0.784540,0.205545,0.212692,0.854567

In [275]:
Confusion_df80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier80.csv')
eval_result80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier80.csv', index=False)

## LOAD & APPLY MODEL dTOP90fi

In [276]:
# test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

In [277]:
# Separate features and tp_ICD_cl0 variable for test_data90
X_test90 = test_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_test90 = test_data90['tp_ICD_cl0']

In [278]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier90.pkl', 'rb') as f:
    knn_90 = pickle.load(f)

### EVALUATION & SAVE

In [279]:
prob90 = knn_90.predict_proba(X_test90)
classes90 = knn_90.classes_

y_pred90, data_top_5 = get_predictions(prob90, classes90, threshold, 10, np.array(y_test90), le)

Confusion_df90 = pd.DataFrame(confusion_matrix(np.array(y_test90), y_pred90))
Confusion_df90.index, Confusion_df90.columns = le.inverse_transform(classes90), le.inverse_transform(classes90)

eval_result90 = calculate_evaluation_metrics(Confusion_df=Confusion_df90)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [280]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.142857,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,129.0,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [281]:
Confusion_df90.index = Confusion_df90.index + 1
Confusion_df90
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,1,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,92,...,0,0,2,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,3,...,2,1,3,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,59,1,1,1,3,0,0,0
198.0,3,3,1,1,2,1,1,2,2,5,...,3,1,3,51,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,0,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [282]:
eval_result90.index = eval_result90.index + 1
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.640569
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007149,0.828571,0.870000,0.848780,0.171429,0.130000,0.679601
6,98.9,0.650000,0.650000,0.350000,0.007149,0.783133,0.650000,0.710383,0.216867,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.008723,0.780000,0.780000,0.780000,0.220000,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022292,0.617450,0.920000,0.738956,0.382550,0.080000,0.983561
11,146.0,0.730000,0.730000,0.270000,0.008330,0.776596,0.730000,0.752577,0.223404,0.270000,0.740576
12,147.0,0.840000,0.840000,0.160000,0.010293,0.763636,0.840000,0.800000,0.236364,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008330,0.785714,0.770000,0.777778,0.214286,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008723,0.790476,0.830000,0.809756,0.209524,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.012638,0.683168,0.690000,0.686567,0.316832,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009116,0.796460,0.900000,0.845070,0.203540,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.590000,0.590000,0.410000,0.011076,0.678161,0.590000,0.631016,0.321839,0.410000,0.231378
20,197.0,0.510000,0.510000,0.490000,0.006754,0.750000,0.510000,0.607143,0.250000,0.490000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786538,0.786538,0.213462,0.008442,0.793340,0.786538,0.783644,0.206660,0.213462,0.586301

In [283]:
Confusion_df90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier90.csv')
eval_result90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier90.csv', index=False)

## LOAD & APPLY MODEL dTOP100fi

In [284]:
# test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

In [285]:
# Separate features and tp_ICD_cl0 variable for test_data100
X_test100 = test_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_test100 = test_data100['tp_ICD_cl0']

In [286]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier100.pkl', 'rb') as f:
    knn_100 = pickle.load(f)

### EVALUATION & SAVE

In [287]:
prob100 = knn_100.predict_proba(X_test100)
classes100 = knn_100.classes_

y_pred100, data_top_5 = get_predictions(prob100, classes100, threshold, 10, np.array(y_test100), le)

Confusion_df100 = pd.DataFrame(confusion_matrix(np.array(y_test100), y_pred100))
Confusion_df100.index, Confusion_df100.columns = le.inverse_transform(classes100), le.inverse_transform(classes100)

eval_result100 = calculate_evaluation_metrics(Confusion_df=Confusion_df100)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [288]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.142857,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,129.0,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [289]:
Confusion_df100.index = Confusion_df100.index + 1
Confusion_df100
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,92,...,0,0,2,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,3,...,2,1,3,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,58,1,1,1,3,0,0,0
198.0,3,3,1,1,2,1,1,2,2,6,...,3,1,3,50,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,1,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [290]:
eval_result100.index = eval_result100.index + 1
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.644235
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007149,0.828571,0.870000,0.848780,0.171429,0.130000,0.679601
6,98.9,0.650000,0.650000,0.350000,0.007149,0.783133,0.650000,0.710383,0.216867,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.008723,0.780000,0.780000,0.780000,0.220000,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022674,0.613333,0.920000,0.736000,0.386667,0.080000,0.983561
11,146.0,0.730000,0.730000,0.270000,0.008330,0.776596,0.730000,0.752577,0.223404,0.270000,0.740576
12,147.0,0.840000,0.840000,0.160000,0.010685,0.756757,0.840000,0.796209,0.243243,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008330,0.785714,0.770000,0.777778,0.214286,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008330,0.798077,0.830000,0.813725,0.201923,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.013028,0.676471,0.690000,0.683168,0.323529,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009116,0.796460,0.900000,0.845070,0.203540,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.580000,0.580000,0.420000,0.011076,0.674419,0.580000,0.623656,0.325581,0.420000,0.231378
20,197.0,0.500000,0.500000,0.500000,0.006754,0.746269,0.500000,0.598802,0.253731,0.500000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.785769,0.785769,0.214231,0.008472,0.792664,0.785769,0.782803,0.207336,0.214231,0.586442

In [291]:
Confusion_df100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier100.csv')
eval_result100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier100.csv', index=False)

## LOAD & APPLY MODEL dTOP110fi

In [292]:
# test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

In [293]:
# Separate features and tp_ICD_cl0 variable for test_data110
X_test110 = test_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_test110 = test_data110['tp_ICD_cl0']

In [294]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier110.pkl', 'rb') as f:
    knn_110 = pickle.load(f)

### EVALUATION & SAVE

In [295]:
prob110 = knn_110.predict_proba(X_test110)
classes110 = knn_110.classes_

y_pred110, data_top_5 = get_predictions(prob110, classes110, threshold, 10, np.array(y_test110), le)

Confusion_df110 = pd.DataFrame(confusion_matrix(np.array(y_test110), y_pred110))
Confusion_df110.index, Confusion_df110.columns = le.inverse_transform(classes110), le.inverse_transform(classes110)

eval_result110 = calculate_evaluation_metrics(Confusion_df=Confusion_df110)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [296]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.190476,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,129.0,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [297]:
Confusion_df110.index = Confusion_df110.index + 1
Confusion_df110
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,92,...,0,0,2,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,2,...,2,1,2,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,58,1,1,1,3,0,0,0
198.0,3,3,1,1,3,0,2,2,2,6,...,4,1,3,49,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,1,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [298]:
eval_result110.index = eval_result110.index + 1
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.644235
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007543,0.820755,0.870000,0.844660,0.179245,0.130000,0.679601
6,98.9,0.650000,0.650000,0.350000,0.006754,0.792683,0.650000,0.714286,0.207317,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.009116,0.772277,0.780000,0.776119,0.227723,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022292,0.617450,0.920000,0.738956,0.382550,0.080000,0.983561
11,146.0,0.750000,0.750000,0.250000,0.007937,0.789474,0.750000,0.769231,0.210526,0.250000,0.763586
12,147.0,0.840000,0.840000,0.160000,0.010685,0.756757,0.840000,0.796209,0.243243,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008330,0.785714,0.770000,0.777778,0.214286,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008330,0.798077,0.830000,0.813725,0.201923,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.013028,0.676471,0.690000,0.683168,0.323529,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009509,0.789474,0.900000,0.841121,0.210526,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.580000,0.580000,0.420000,0.010685,0.682353,0.580000,0.627027,0.317647,0.420000,0.231378
20,197.0,0.490000,0.490000,0.510000,0.006754,0.742424,0.490000,0.590361,0.257576,0.510000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008457,0.792976,0.786154,0.783052,0.207024,0.213846,0.587327

In [299]:
Confusion_df110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier110.csv')
eval_result110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier110.csv', index=False)

## LOAD & APPLY MODEL dTOP120fi

In [300]:
# test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

In [301]:
# Separate features and tp_ICD_cl0 variable for test_data120
X_test120 = test_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_test120 = test_data120['tp_ICD_cl0']

In [302]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier120.pkl', 'rb') as f:
    knn_120 = pickle.load(f)

### EVALUATION & SAVE

In [303]:
prob120 = knn_120.predict_proba(X_test120)
classes120 = knn_120.classes_

y_pred120, data_top_5 = get_predictions(prob120, classes120, threshold, 10, np.array(y_test120), le)

Confusion_df120 = pd.DataFrame(confusion_matrix(np.array(y_test120), y_pred120))
Confusion_df120.index, Confusion_df120.columns = le.inverse_transform(classes120), le.inverse_transform(classes120)

eval_result120 = calculate_evaluation_metrics(Confusion_df=Confusion_df120)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [304]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.190476,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,129.0,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [305]:
Confusion_df120.index = Confusion_df120.index + 1
Confusion_df120
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,92,...,0,0,2,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,2,...,2,1,2,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,58,1,1,1,3,0,0,0
198.0,3,3,1,1,3,0,2,2,2,6,...,4,1,3,49,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,1,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [306]:
eval_result120.index = eval_result120.index + 1
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.644235
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007543,0.820755,0.870000,0.844660,0.179245,0.130000,0.679601
6,98.9,0.650000,0.650000,0.350000,0.006754,0.792683,0.650000,0.714286,0.207317,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.009116,0.772277,0.780000,0.776119,0.227723,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022292,0.617450,0.920000,0.738956,0.382550,0.080000,0.983561
11,146.0,0.750000,0.750000,0.250000,0.007937,0.789474,0.750000,0.769231,0.210526,0.250000,0.763586
12,147.0,0.840000,0.840000,0.160000,0.010685,0.756757,0.840000,0.796209,0.243243,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008330,0.785714,0.770000,0.777778,0.214286,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008330,0.798077,0.830000,0.813725,0.201923,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.013028,0.676471,0.690000,0.683168,0.323529,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009509,0.789474,0.900000,0.841121,0.210526,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.580000,0.580000,0.420000,0.010685,0.682353,0.580000,0.627027,0.317647,0.420000,0.231378
20,197.0,0.490000,0.490000,0.510000,0.006754,0.742424,0.490000,0.590361,0.257576,0.510000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008457,0.792976,0.786154,0.783052,0.207024,0.213846,0.587327

In [307]:
Confusion_df120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier120.csv')
eval_result120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier120.csv', index=False)

## LOAD & APPLY MODEL dTOP130fi

In [308]:
# test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

In [309]:
# Separate features and tp_ICD_cl0 variable for test_data130
X_test130 = test_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_test130 = test_data130['tp_ICD_cl0']

In [310]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier130.pkl', 'rb') as f:
    knn_130 = pickle.load(f)

### EVALUATION & SAVE

In [311]:
prob130 = knn_130.predict_proba(X_test130)
classes130 = knn_130.classes_

y_pred130, data_top_5 = get_predictions(prob130, classes130, threshold, 10, np.array(y_test130), le)

Confusion_df130 = pd.DataFrame(confusion_matrix(np.array(y_test130), y_pred130))
Confusion_df130.index, Confusion_df130.columns = le.inverse_transform(classes130), le.inverse_transform(classes130)

eval_result130 = calculate_evaluation_metrics(Confusion_df=Confusion_df130)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [312]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.190476,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,129.0,0.095238
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [313]:
Confusion_df130.index = Confusion_df130.index + 1
Confusion_df130
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,2,1,0,92,...,0,0,1,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,2,...,2,1,2,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,58,1,1,1,3,0,0,0
198.0,3,3,1,1,3,0,2,2,2,6,...,4,1,3,49,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,1,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [314]:
eval_result130.index = eval_result130.index + 1
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.644235
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007543,0.820755,0.870000,0.844660,0.179245,0.130000,0.679601
6,98.9,0.650000,0.650000,0.350000,0.006754,0.792683,0.650000,0.714286,0.207317,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.009509,0.764706,0.780000,0.772277,0.235294,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.014196,0.666667,0.720000,0.692308,0.333333,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022292,0.617450,0.920000,0.738956,0.382550,0.080000,1.046979
11,146.0,0.750000,0.750000,0.250000,0.007937,0.789474,0.750000,0.769231,0.210526,0.250000,0.763586
12,147.0,0.840000,0.840000,0.160000,0.010685,0.756757,0.840000,0.796209,0.243243,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008330,0.785714,0.770000,0.777778,0.214286,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008330,0.798077,0.830000,0.813725,0.201923,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.013028,0.676471,0.690000,0.683168,0.323529,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009509,0.789474,0.900000,0.841121,0.210526,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.580000,0.580000,0.420000,0.010293,0.690476,0.580000,0.630435,0.309524,0.420000,0.231378
20,197.0,0.490000,0.490000,0.510000,0.006754,0.742424,0.490000,0.590361,0.257576,0.510000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008457,0.792998,0.786154,0.783036,0.207002,0.213846,0.589766

In [315]:
Confusion_df130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier130.csv')
eval_result130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier130.csv', index=False)

## LOAD & APPLY MODEL dTOP140fi

In [316]:
# test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

In [317]:
# Separate features and tp_ICD_cl0 variable for test_data140
X_test140 = test_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_test140 = test_data140['tp_ICD_cl0']

In [318]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier140.pkl', 'rb') as f:
    knn_140 = pickle.load(f)

### EVALUATION & SAVE

In [319]:
prob140 = knn_140.predict_proba(X_test140)
classes140 = knn_140.classes_

y_pred140, data_top_5 = get_predictions(prob140, classes140, threshold, 10, np.array(y_test140), le)

Confusion_df140 = pd.DataFrame(confusion_matrix(np.array(y_test140), y_pred140))
Confusion_df140.index, Confusion_df140.columns = le.inverse_transform(classes140), le.inverse_transform(classes140)

eval_result140 = calculate_evaluation_metrics(Confusion_df=Confusion_df140)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [320]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.285714,41.0,0.190476,146.0,0.142857,150.0,0.095238,151.0,0.095238
2,185.9,153.0,0.238095,147.0,0.142857,197.0,0.142857,5.0,0.095238,129.0,0.095238
3,248.0,248.0,0.428571,249.0,0.238095,251.0,0.238095,5.0,0.047619,41.0,0.047619
4,146.0,104.1,0.142857,111.0,0.095238,129.0,0.095238,146.0,0.095238,147.0,0.095238
5,251.0,249.0,0.380952,251.0,0.380952,248.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.238095,150.0,0.190476,151.0,0.190476,129.0,0.095238,147.0,0.095238
2597,18.9,18.9,0.190476,129.0,0.190476,151.0,0.142857,150.0,0.095238,153.0,0.095238
2598,217.0,98.9,0.285714,7.1,0.190476,104.1,0.095238,111.0,0.095238,146.0,0.095238
2599,104.1,104.1,0.380952,5.0,0.142857,185.9,0.142857,18.9,0.095238,111.0,0.047619
2600,251.0,251.0,0.714286,249.0,0.190476,248.0,0.095238,NaN,NaN,NaN,NaN

In [321]:
Confusion_df140.index = Confusion_df140.index + 1
Confusion_df140
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,79,0,2,1,1,0,0,0,3,...,2,1,1,0,0,0,2,0,0,1
19.9,1,0,73,3,1,0,0,1,2,4,...,2,1,1,0,1,0,2,0,0,0
33.1,1,0,0,87,0,0,1,0,1,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,0,0,6,87,1,0,0,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,0,3,1,1,78,2,2,4,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,3,0,1,1,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,2,1,0,92,...,0,0,1,1,0,0,0,0,0,0
147.0,1,1,1,1,0,1,2,1,1,2,...,2,1,2,0,0,2,1,0,0,0
148.0,0,1,2,0,1,1,1,1,0,4,...,1,0,0,0,1,1,0,0,0,0
151.0,0,0,1,1,2,0,2,4,1,3,...,0,0,1,3,0,0,2,0,0,0
152.0,0,1,1,0,3,1,0,2,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,6,1,0,1,1,3,1,1,...,0,0,4,1,0,1,4,0,1,0
155.0,0,0,3,2,1,5,1,2,0,5,...,0,0,1,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,2,0,1,...,90,0,0,0,0,0,1,0,0,0
170.0,0,0,5,2,3,0,1,2,1,2,...,1,66,2,2,0,2,3,0,0,0
186.9,2,0,2,1,0,2,1,5,5,4,...,3,1,58,1,1,1,3,0,0,0
198.0,3,3,1,1,3,0,3,1,2,6,...,4,1,3,49,0,1,1,0,0,0
213.9,2,0,1,2,0,0,4,3,1,5,...,3,0,3,3,59,1,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,68,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [322]:
eval_result140.index = eval_result140.index + 1
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.007543,0.817308,0.850000,0.833333,0.182692,0.150000,0.474590
2,7.1,0.790000,0.790000,0.210000,0.006359,0.831579,0.790000,0.810256,0.168421,0.210000,0.644235
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.687167
4,32.1,0.870000,0.870000,0.130000,0.012638,0.731092,0.870000,0.794521,0.268908,0.130000,0.771127
5,41.0,0.870000,0.870000,0.130000,0.007543,0.820755,0.870000,0.844660,0.179245,0.130000,0.678408
6,98.9,0.650000,0.650000,0.350000,0.006754,0.792683,0.650000,0.714286,0.207317,0.350000,0.774008
7,104.1,0.780000,0.780000,0.220000,0.009901,0.757282,0.780000,0.768473,0.242718,0.220000,0.688051
8,111.0,0.720000,0.720000,0.280000,0.013418,0.679245,0.720000,0.699029,0.320755,0.280000,0.617532
9,128.0,0.910000,0.910000,0.090000,0.008723,0.805310,0.910000,0.854460,0.194690,0.090000,0.573593
10,129.0,0.920000,0.920000,0.080000,0.022292,0.617450,0.920000,0.738956,0.382550,0.080000,1.046979
11,146.0,0.750000,0.750000,0.250000,0.007937,0.789474,0.750000,0.769231,0.210526,0.250000,0.763586
12,147.0,0.840000,0.840000,0.160000,0.010685,0.756757,0.840000,0.796209,0.243243,0.160000,0.664849
13,150.0,0.770000,0.770000,0.230000,0.008723,0.777778,0.770000,0.773869,0.222222,0.230000,0.650571
14,151.0,0.830000,0.830000,0.170000,0.008330,0.798077,0.830000,0.813725,0.201923,0.170000,0.727491
15,153.0,0.630000,0.630000,0.370000,0.009509,0.724138,0.630000,0.673797,0.275862,0.370000,0.250000
16,154.0,0.690000,0.690000,0.310000,0.013028,0.676471,0.690000,0.683168,0.323529,0.310000,0.678233
17,161.0,0.900000,0.900000,0.100000,0.009509,0.789474,0.900000,0.841121,0.210526,0.100000,1.087490
18,169.0,0.660000,0.660000,0.340000,0.003190,0.891892,0.660000,0.758621,0.108108,0.340000,0.781299
19,185.9,0.580000,0.580000,0.420000,0.010293,0.690476,0.580000,0.630435,0.309524,0.420000,0.231378
20,197.0,0.490000,0.490000,0.510000,0.006754,0.742424,0.490000,0.590361,0.257576,0.510000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002792,0.893939,0.590000,0.710843,0.106061,0.410000,0.224244
22,217.0,0.680000,0.680000,0.320000,0.004381,0.860759,0.680000,0.759777,0.139241,0.320000,0.834307
23,239.2,0.990000,0.990000,0.010000,0.014972,0.722628,0.990000,0.835443,0.277372,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.255921
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008458,0.792891,0.786154,0.782997,0.207109,0.213846,0.589720

In [323]:
Confusion_df140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier140.csv')
eval_result140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier140.csv', index=False)

## LOAD & APPLY MODEL dTOP150fi

In [324]:
# test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

In [325]:
# Separate features and tp_ICD_cl0 variable for test_data150
X_test150 = test_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_test150 = test_data150['tp_ICD_cl0']

In [326]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier150.pkl', 'rb') as f:
    knn_150 = pickle.load(f)

### EVALUATION & SAVE

In [327]:
prob150 = knn_150.predict_proba(X_test150)
classes150 = knn_150.classes_

y_pred150, data_top_5 = get_predictions(prob150, classes150, threshold, 10, np.array(y_test150), le)

Confusion_df150 = pd.DataFrame(confusion_matrix(np.array(y_test150), y_pred150))
Confusion_df150.index, Confusion_df150.columns = le.inverse_transform(classes150), le.inverse_transform(classes150)

eval_result150 = calculate_evaluation_metrics(Confusion_df=Confusion_df150)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [328]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.30,41.0,0.20,146.0,0.15,150.0,0.10,151.0,0.10
2,185.9,153.0,0.25,147.0,0.15,197.0,0.15,5.0,0.10,129.0,0.10
3,248.0,248.0,0.55,249.0,0.25,251.0,0.10,5.0,0.05,41.0,0.05
4,146.0,104.1,0.15,111.0,0.10,129.0,0.10,146.0,0.10,147.0,0.10
5,251.0,251.0,0.40,249.0,0.35,248.0,0.25,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.20,151.0,0.20,185.9,0.20,129.0,0.10,147.0,0.10
2597,18.9,18.9,0.20,129.0,0.20,151.0,0.15,150.0,0.10,153.0,0.10
2598,217.0,98.9,0.30,7.1,0.15,104.1,0.10,111.0,0.10,146.0,0.10
2599,104.1,104.1,0.40,5.0,0.15,18.9,0.10,129.0,0.10,111.0,0.05
2600,251.0,251.0,0.70,249.0,0.20,248.0,0.10,NaN,NaN,NaN,NaN

In [329]:
Confusion_df150.index = Confusion_df150.index + 1
Confusion_df150
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,0,0,1,0,0,1,...,1,0,1,0,1,0,3,0,0,0
8.1,0,78,0,1,2,1,0,0,0,3,...,1,1,1,0,0,1,2,0,0,1
19.9,1,0,73,3,1,0,0,2,1,4,...,1,1,1,0,1,0,2,0,0,0
33.1,1,0,0,86,0,0,1,1,2,1,...,1,0,1,1,0,0,1,0,0,0
42.0,0,0,0,4,87,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,2,1,2,...,1,0,0,0,1,1,3,0,1,0
105.1,0,1,1,2,1,1,78,2,2,5,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,2,0,1,2,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,88,...,0,0,2,0,0,0,0,0,0,0
147.0,1,1,1,0,0,1,2,1,1,4,...,2,0,2,0,0,1,1,0,0,0
148.0,0,1,3,0,1,1,1,1,0,4,...,1,0,0,0,0,1,0,0,0,0
151.0,0,0,1,0,2,0,2,3,2,3,...,0,0,1,2,0,0,2,0,0,0
152.0,0,1,0,0,3,1,0,1,0,1,...,0,0,2,0,1,0,0,0,0,0
154.0,3,0,5,2,0,1,0,2,1,2,...,0,0,3,2,0,1,4,0,0,0
155.0,1,0,5,1,1,5,2,3,0,4,...,0,0,2,2,0,0,0,0,0,0
162.0,1,3,0,2,0,0,0,1,0,1,...,91,0,0,0,0,0,1,0,0,0
170.0,0,0,4,3,2,0,1,3,3,0,...,1,66,0,2,0,3,3,0,0,0
186.9,2,0,2,2,0,2,0,4,5,4,...,3,1,60,1,1,1,2,0,0,0
198.0,4,3,1,1,1,1,1,1,2,5,...,3,2,3,50,0,1,1,0,0,0
213.9,2,0,1,1,0,2,3,4,1,6,...,3,0,3,2,59,0,5,0,0,0
218.0,2,0,5,2,0,1,2,2,2,1,...,0,0,3,2,0,67,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,1,3,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [330]:
eval_result150.index = eval_result150.index + 1
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.008330,0.801887,0.850000,0.825243,0.198113,0.150000,0.474590
2,7.1,0.780000,0.780000,0.220000,0.006359,0.829787,0.780000,0.804124,0.170213,0.220000,0.678134
3,18.9,0.730000,0.730000,0.270000,0.013028,0.688679,0.730000,0.708738,0.311321,0.270000,0.656330
4,32.1,0.860000,0.860000,0.140000,0.011076,0.754386,0.860000,0.803738,0.245614,0.140000,0.774007
5,41.0,0.870000,0.870000,0.130000,0.006754,0.836538,0.870000,0.852941,0.163462,0.130000,0.678690
6,98.9,0.650000,0.650000,0.350000,0.008330,0.755814,0.650000,0.698925,0.244186,0.350000,0.818796
7,104.1,0.780000,0.780000,0.220000,0.007937,0.795918,0.780000,0.787879,0.204082,0.220000,0.597357
8,111.0,0.720000,0.720000,0.280000,0.013807,0.672897,0.720000,0.695652,0.327103,0.280000,0.532426
9,128.0,0.910000,0.910000,0.090000,0.009901,0.784483,0.910000,0.842593,0.215517,0.090000,0.573593
10,129.0,0.880000,0.880000,0.120000,0.022674,0.602740,0.880000,0.715447,0.397260,0.120000,0.686749
11,146.0,0.760000,0.760000,0.240000,0.007937,0.791667,0.760000,0.775510,0.208333,0.240000,0.667785
12,147.0,0.840000,0.840000,0.160000,0.011858,0.736842,0.840000,0.785047,0.263158,0.160000,0.706433
13,150.0,0.790000,0.790000,0.210000,0.009509,0.766990,0.790000,0.778325,0.233010,0.210000,0.715673
14,151.0,0.850000,0.850000,0.150000,0.007937,0.809524,0.850000,0.829268,0.190476,0.150000,0.684045
15,153.0,0.650000,0.650000,0.350000,0.009509,0.730337,0.650000,0.687831,0.269663,0.350000,0.871806
16,154.0,0.650000,0.650000,0.350000,0.013807,0.650000,0.650000,0.650000,0.350000,0.350000,0.793692
17,161.0,0.910000,0.910000,0.090000,0.008330,0.812500,0.910000,0.858491,0.187500,0.090000,1.135093
18,169.0,0.660000,0.660000,0.340000,0.002792,0.904110,0.660000,0.763006,0.095890,0.340000,0.786762
19,185.9,0.600000,0.600000,0.400000,0.009901,0.705882,0.600000,0.648649,0.294118,0.400000,0.231378
20,197.0,0.500000,0.500000,0.500000,0.007149,0.735294,0.500000,0.595238,0.264706,0.500000,0.227670
21,212.9,0.590000,0.590000,0.410000,0.002394,0.907692,0.590000,0.715152,0.092308,0.410000,0.224244
22,217.0,0.670000,0.670000,0.330000,0.004777,0.848101,0.670000,0.748603,0.151899,0.330000,0.853235
23,239.2,0.990000,0.990000,0.010000,0.014584,0.727941,0.990000,0.838983,0.272059,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.000799,0.979381,0.950000,0.964467,0.020619,0.050000,1.249414
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.786154,0.786154,0.213846,0.008457,0.793057,0.786154,0.783418,0.206943,0.213846,0.600689

In [331]:
Confusion_df150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier150.csv')
eval_result150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier150.csv', index=False)

## LOAD & APPLY MODEL dALLfi

In [332]:
# test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

In [333]:
# Separate features and tp_ICD_cl0 variable for test_data353
X_test353 = test_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_test353 = test_data353['tp_ICD_cl0']

In [334]:
X_test353 = X_test353[X_train353.columns]

In [335]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/knnclassifier353.pkl', 'rb') as f:
    knn_353 = pickle.load(f)

### EVALUATION & SAVE

In [336]:
prob353 = knn_353.predict_proba(X_test353)
classes353 = knn_353.classes_

y_pred353, data_top_5 = get_predictions(prob353, classes353, threshold, 10, np.array(y_test353), le)

Confusion_df353 = pd.DataFrame(confusion_matrix(np.array(y_test353), y_pred353))
Confusion_df353.index, Confusion_df353.columns = le.inverse_transform(classes353), le.inverse_transform(classes353)

eval_result353 = calculate_evaluation_metrics(Confusion_df=Confusion_df353)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [337]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.30,41.0,0.20,146.0,0.15,150.0,0.1,151.0,0.10
2,185.9,153.0,0.25,147.0,0.15,197.0,0.15,5.0,0.1,129.0,0.10
3,248.0,248.0,0.55,5.0,0.10,154.0,0.10,169.0,0.1,18.9,0.05
4,146.0,104.1,0.15,111.0,0.10,129.0,0.10,146.0,0.1,147.0,0.10
5,251.0,251.0,0.40,249.0,0.35,248.0,0.25,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.20,151.0,0.20,185.9,0.20,129.0,0.1,147.0,0.10
2597,18.9,18.9,0.20,129.0,0.20,151.0,0.15,150.0,0.1,153.0,0.10
2598,217.0,98.9,0.30,7.1,0.15,104.1,0.10,111.0,0.1,146.0,0.10
2599,104.1,104.1,0.40,5.0,0.15,18.9,0.10,129.0,0.1,111.0,0.05
2600,251.0,251.0,0.70,249.0,0.20,248.0,0.10,NaN,NaN,NaN,NaN

In [338]:
Confusion_df353.index = Confusion_df353.index + 1
Confusion_df353
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,84,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,3,1,0,0
8.1,0,78,0,1,2,1,0,0,0,4,...,1,1,1,0,0,1,2,0,0,1
19.9,1,1,74,3,1,0,0,2,1,4,...,1,1,1,0,1,0,2,0,0,0
33.1,1,0,0,86,0,0,1,0,2,1,...,1,1,1,1,0,0,1,0,0,0
42.0,0,1,0,4,86,1,0,1,0,3,...,0,0,0,0,0,0,2,0,0,0
99.9,0,2,2,4,2,65,2,3,1,2,...,1,0,0,0,1,0,3,0,1,0
105.1,0,1,1,2,1,1,77,3,2,5,...,0,2,0,1,0,0,1,0,0,0
112.0,1,0,2,0,1,2,1,72,1,4,...,3,0,0,1,0,0,1,0,0,0
129.0,0,0,0,0,0,1,0,0,91,0,...,0,0,0,1,1,2,0,0,0,0
130.0,1,1,0,0,0,0,1,1,0,89,...,0,0,3,0,0,0,0,0,0,0
147.0,0,1,1,0,0,1,2,1,2,4,...,2,0,2,0,0,1,1,0,0,0
148.0,1,1,3,0,1,1,1,1,0,3,...,1,0,0,0,0,1,0,0,0,0
151.0,0,0,1,0,2,0,2,3,1,3,...,0,0,0,2,0,0,2,0,0,0
152.0,1,0,0,0,3,1,0,1,0,1,...,0,0,2,0,1,1,0,0,0,0
154.0,3,0,5,2,0,1,0,2,1,2,...,0,0,3,2,0,1,4,0,0,0
155.0,1,0,7,1,1,4,2,2,0,4,...,0,0,1,2,0,0,0,0,0,0
162.0,0,4,0,2,0,0,0,1,0,1,...,90,0,1,0,0,0,1,0,0,0
170.0,0,0,3,3,2,0,1,1,3,1,...,1,67,0,2,0,3,3,0,0,0
186.9,2,0,2,2,0,1,0,4,5,4,...,3,1,60,1,1,1,2,0,0,0
198.0,4,3,1,1,2,1,1,1,2,5,...,2,2,3,50,1,1,1,0,0,0
213.9,2,0,1,1,0,2,3,4,2,6,...,3,0,3,2,58,0,5,0,0,0
218.0,2,0,5,1,0,1,2,2,2,1,...,0,0,3,0,0,65,3,0,1,0
240.2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,4,95,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [339]:
eval_result353.index = eval_result353.index + 1
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.840000,0.840000,0.160000,0.007937,0.807692,0.840000,0.823529,0.192308,0.160000,0.446327
2,7.1,0.780000,0.780000,0.220000,0.005964,0.838710,0.780000,0.808290,0.161290,0.220000,0.605849
3,18.9,0.740000,0.740000,0.260000,0.013418,0.685185,0.740000,0.711538,0.314815,0.260000,0.706124
4,32.1,0.860000,0.860000,0.140000,0.010685,0.761062,0.860000,0.807512,0.238938,0.140000,0.761128
5,41.0,0.860000,0.860000,0.140000,0.007149,0.826923,0.860000,0.843137,0.173077,0.140000,0.707229
6,98.9,0.650000,0.650000,0.350000,0.007543,0.773810,0.650000,0.706522,0.226190,0.350000,0.821104
7,104.1,0.770000,0.770000,0.230000,0.007937,0.793814,0.770000,0.781726,0.206186,0.230000,0.599709
8,111.0,0.720000,0.720000,0.280000,0.013028,0.685714,0.720000,0.702439,0.314286,0.280000,0.532426
9,128.0,0.910000,0.910000,0.090000,0.010293,0.777778,0.910000,0.838710,0.222222,0.090000,0.573593
10,129.0,0.890000,0.890000,0.110000,0.023056,0.601351,0.890000,0.717742,0.398649,0.110000,0.645294
11,146.0,0.760000,0.760000,0.240000,0.008330,0.783505,0.760000,0.771574,0.216495,0.240000,0.636442
12,147.0,0.840000,0.840000,0.160000,0.011858,0.736842,0.840000,0.785047,0.263158,0.160000,0.910320
13,150.0,0.810000,0.810000,0.190000,0.009116,0.778846,0.810000,0.794118,0.221154,0.190000,0.700631
14,151.0,0.840000,0.840000,0.160000,0.008330,0.800000,0.840000,0.819512,0.200000,0.160000,0.729545
15,153.0,0.650000,0.650000,0.350000,0.011858,0.684211,0.650000,0.666667,0.315789,0.350000,0.871806
16,154.0,0.640000,0.640000,0.360000,0.013028,0.659794,0.640000,0.649746,0.340206,0.360000,0.797267
17,161.0,0.900000,0.900000,0.100000,0.007937,0.818182,0.900000,0.857143,0.181818,0.100000,1.008644
18,169.0,0.670000,0.670000,0.330000,0.003190,0.893333,0.670000,0.765714,0.106667,0.330000,0.744987
19,185.9,0.600000,0.600000,0.400000,0.009509,0.714286,0.600000,0.652174,0.285714,0.400000,0.231378
20,197.0,0.500000,0.500000,0.500000,0.006359,0.757576,0.500000,0.602410,0.242424,0.500000,0.227670
21,212.9,0.580000,0.580000,0.420000,0.002394,0.906250,0.580000,0.707317,0.093750,0.420000,0.224244
22,217.0,0.650000,0.650000,0.350000,0.004777,0.844156,0.650000,0.734463,0.155844,0.350000,0.842450
23,239.2,0.990000,0.990000,0.010000,0.014584,0.727941,0.990000,0.838983,0.272059,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.001996,0.952381,1.000000,0.975610,0.047619,0.000000,0.000000
25,249.0,0.950000,0.950000,0.050000,0.000799,0.979381,0.950000,0.964467,0.020619,0.050000,0.362006
26,251.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
27,average,0.784615,0.784615,0.215385,0.008518,0.791493,0.784615,0.781581,0.208507,0.215385,0.564853

In [340]:
Confusion_df353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/confusion_test_knnclassifier353.csv')
eval_result353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single/fv_3/data_with_lk@500/result_test_knnclassifier353.csv', index=False)