# **IMPORT LIBRARY**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pickle, time, json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# **LOADING DATASET**

### DATA PMR unbalanced 360 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_pmr_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### DATA positive unbalanced 344 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/all_positive_unbalanced/data_5_features_topn5_test.csv', index_col=False)

### DATA @500 110 class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@500/data_5_features_topn5_test.csv', index_col=False)

### DATA @1000 55 class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/@1000/data_5_features_topn5_test.csv', index_col=False)

### DATA TOP 10 Class

In [ ]:
train_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_train.csv', index_col=False)
test_data353 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_348_features_topn353_test.csv', index_col=False)

train_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_train.csv', index_col=False)
test_data150 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_150_features_topn150_test.csv', index_col=False)

train_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_train.csv', index_col=False)
test_data140 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_140_features_topn140_test.csv', index_col=False)

train_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_train.csv', index_col=False)
test_data130 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_130_features_topn130_test.csv', index_col=False)

train_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_train.csv', index_col=False)
test_data120 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_120_features_topn120_test.csv', index_col=False)

train_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_train.csv', index_col=False)
test_data110 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_110_features_topn110_test.csv', index_col=False)

train_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_train.csv', index_col=False)
test_data100 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_100_features_topn100_test.csv', index_col=False)

train_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_train.csv', index_col=False)
test_data90 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_90_features_topn90_test.csv', index_col=False)

train_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_train.csv', index_col=False)
test_data80 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_80_features_topn80_test.csv', index_col=False)

train_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_train.csv', index_col=False)
test_data70 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_70_features_topn70_test.csv', index_col=False)

train_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_train.csv', index_col=False)
test_data60 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_60_features_topn60_test.csv', index_col=False)

train_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_train.csv', index_col=False)
test_data50 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_50_features_topn50_test.csv', index_col=False)

train_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_train.csv', index_col=False)
test_data40 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_40_features_topn40_test.csv', index_col=False)

train_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_train.csv', index_col=False)
test_data30 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_30_features_topn30_test.csv', index_col=False)

train_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_train.csv', index_col=False)
test_data20 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_20_features_topn20_test.csv', index_col=False)

train_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_train.csv', index_col=False)
test_data10 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_10_features_topn10_test.csv', index_col=False)

train_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_train.csv', index_col=False)
test_data5 = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/fv_1/top_10_class/data_5_features_topn5_test.csv', index_col=False)

### LOAD DATA WITH LK

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk/test_dataset.csv', index_col=False)

with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk/feature_dictionary.json', 'rb') as file:
    features = json.load(file)

### LOAD DATA WITH LK @500

In [3]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/test_dataset.csv', index_col=False)

### LOAD DATA NO LK

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk/test_dataset.csv', index_col=False)

### DATA data_no_lk @500

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@500/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@500/test_dataset.csv', index_col=False)

### DATA data_no_lk @1000

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@1000/train_dataset.csv', index_col=False)
test_df = pd.read_csv('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_no_lk@1000/test_dataset.csv', index_col=False)

# PREPROCESSING

In [4]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/feature_dictionary.json', 'r') as json_file:
    feature_dictionary = json.load(json_file)

## ALL FEATURES

In [5]:
train_data353 = train_df[feature_dictionary['all'] + ['tp_ICD_cl0']]
test_data353 = test_df[feature_dictionary['all'] + ['tp_ICD_cl0']]

In [6]:
train_data353.head()

,n_de_01,c_an_071,c_an_169,n_vs_06,n_lk_012,n_de_02,n_vs_05,n_vs_01,c_de_04,n_de_03,...,c_lk_111,c_lk_112,c_lk_113,c_lk_114,c_lk_115,c_lk_116,c_lk_121,c_lk_127,c_lk_128,tp_ICD_cl0
0,0.0,0,0,251.0,39.0,0.0,36.0,3.0,1,1.0,...,1,1,1,1,1,1,1,1,1,251.0
1,6.0,0,0,20.0,66.0,0.0,37.0,21.0,1,11.0,...,1,1,1,1,1,1,1,1,1,41.0
2,69.0,0,0,20.0,66.0,3.0,36.5,56.0,2,9.0,...,1,1,1,1,1,1,1,1,1,129.0
3,9.0,0,0,20.0,66.0,6.0,36.5,31.0,1,17.0,...,1,1,1,1,1,1,1,1,1,169.0
4,28.0,0,1,20.0,66.0,1.0,36.5,56.0,2,25.0,...,1,1,1,1,1,1,1,1,1,161.0

In [7]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_all.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data353.columns if x.startswith('n_')]

train_data353[num_cols] = scaler.transform(train_data353[num_cols])
test_data353[num_cols] = scaler.transform(test_data353[num_cols])

In [8]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_all.pkl', 'rb') as file:
    le = pickle.load(file)

train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])
test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

## 150 FEATURES

In [9]:
train_data150 = train_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]
test_data150 = test_df[feature_dictionary['top 150'] + ['tp_ICD_cl0']]

In [10]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_150.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data150.columns if x.startswith('n_')]

train_data150[num_cols] = scaler.transform(train_data150[num_cols])
test_data150[num_cols] = scaler.transform(test_data150[num_cols])

<ipython-input-10-d7780d979e14>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data150[num_cols] = scaler.transform(train_data150[num_cols])
<ipython-input-10-d7780d979e14>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data150[num_cols] = scaler.transform(test_data150[num_cols])

In [11]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_150.pkl', 'rb') as file:
    le = pickle.load(file)

train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])
test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

<ipython-input-11-eb221fc66b4d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])
<ipython-input-11-eb221fc66b4d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

## 140 FEATURES

In [12]:
train_data140 = train_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]
test_data140 = test_df[feature_dictionary['top 140'] + ['tp_ICD_cl0']]

In [13]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_140.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data140.columns if x.startswith('n_')]

train_data140[num_cols] = scaler.transform(train_data140[num_cols])
test_data140[num_cols] = scaler.transform(test_data140[num_cols])

<ipython-input-13-ab269fcf6307>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data140[num_cols] = scaler.transform(train_data140[num_cols])
<ipython-input-13-ab269fcf6307>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data140[num_cols] = scaler.transform(test_data140[num_cols])

In [14]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_140.pkl', 'rb') as file:
    le = pickle.load(file)

train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])
test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

<ipython-input-14-b6dd57056cfb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])
<ipython-input-14-b6dd57056cfb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

## 130 FEATURES

In [15]:
train_data130 = train_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]
test_data130 = test_df[feature_dictionary['top 130'] + ['tp_ICD_cl0']]

In [16]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_130.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data130.columns if x.startswith('n_')]

train_data130[num_cols] = scaler.transform(train_data130[num_cols])
test_data130[num_cols] = scaler.transform(test_data130[num_cols])

<ipython-input-16-d396a671a766>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data130[num_cols] = scaler.transform(train_data130[num_cols])
<ipython-input-16-d396a671a766>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data130[num_cols] = scaler.transform(test_data130[num_cols])

In [17]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_130.pkl', 'rb') as file:
    le = pickle.load(file)

train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])
test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

<ipython-input-17-fe925daf011a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])
<ipython-input-17-fe925daf011a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

## 120 FEATURES

In [18]:
train_data120 = train_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]
test_data120 = test_df[feature_dictionary['top 120'] + ['tp_ICD_cl0']]

In [19]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_120.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data120.columns if x.startswith('n_')]

train_data120[num_cols] = scaler.transform(train_data120[num_cols])
test_data120[num_cols] = scaler.transform(test_data120[num_cols])

<ipython-input-19-5b8ca95de23e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data120[num_cols] = scaler.transform(train_data120[num_cols])
<ipython-input-19-5b8ca95de23e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data120[num_cols] = scaler.transform(test_data120[num_cols])

In [20]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_120.pkl', 'rb') as file:
    le = pickle.load(file)

train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])
test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

<ipython-input-20-a89b9322186f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])
<ipython-input-20-a89b9322186f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

## 110 FEATURES

In [21]:
train_data110 = train_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]
test_data110 = test_df[feature_dictionary['top 110'] + ['tp_ICD_cl0']]

In [22]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_110.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data110.columns if x.startswith('n_')]

train_data110[num_cols] = scaler.transform(train_data110[num_cols])
test_data110[num_cols] = scaler.transform(test_data110[num_cols])

<ipython-input-22-b6a0c56ccce1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data110[num_cols] = scaler.transform(train_data110[num_cols])
<ipython-input-22-b6a0c56ccce1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data110[num_cols] = scaler.transform(test_data110[num_cols])

In [23]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_110.pkl', 'rb') as file:
    le = pickle.load(file)

train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])
test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

<ipython-input-23-42a46f7ddb06>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])
<ipython-input-23-42a46f7ddb06>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

## 100 FEATURES

In [24]:
train_data100 = train_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]
test_data100 = test_df[feature_dictionary['top 100'] + ['tp_ICD_cl0']]

In [25]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_100.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data100.columns if x.startswith('n_')]

train_data100[num_cols] = scaler.transform(train_data100[num_cols])
test_data100[num_cols] = scaler.transform(test_data100[num_cols])

<ipython-input-25-41d179283bda>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data100[num_cols] = scaler.transform(train_data100[num_cols])
<ipython-input-25-41d179283bda>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data100[num_cols] = scaler.transform(test_data100[num_cols])

In [26]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_100.pkl', 'rb') as file:
    le = pickle.load(file)

train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])
test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

<ipython-input-26-8e132ae2ecda>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])
<ipython-input-26-8e132ae2ecda>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

## 90 FEATURES

In [27]:
train_data90 = train_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]
test_data90 = test_df[feature_dictionary['top 90'] + ['tp_ICD_cl0']]

In [28]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_90.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data90.columns if x.startswith('n_')]

train_data90[num_cols] = scaler.transform(train_data90[num_cols])
test_data90[num_cols] = scaler.transform(test_data90[num_cols])

<ipython-input-28-0e136ed5ebff>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data90[num_cols] = scaler.transform(train_data90[num_cols])
<ipython-input-28-0e136ed5ebff>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data90[num_cols] = scaler.transform(test_data90[num_cols])

In [29]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_90.pkl', 'rb') as file:
    le = pickle.load(file)

train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])
test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

<ipython-input-29-ebaecd4de649>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])
<ipython-input-29-ebaecd4de649>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

## 80 FEATURES

In [30]:
train_data80 = train_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]
test_data80 = test_df[feature_dictionary['top 80'] + ['tp_ICD_cl0']]

In [31]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_80.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data80.columns if x.startswith('n_')]

train_data80[num_cols] = scaler.transform(train_data80[num_cols])
test_data80[num_cols] = scaler.transform(test_data80[num_cols])

<ipython-input-31-7cb41b057e56>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data80[num_cols] = scaler.transform(train_data80[num_cols])
<ipython-input-31-7cb41b057e56>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data80[num_cols] = scaler.transform(test_data80[num_cols])

In [32]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_80.pkl', 'rb') as file:
    le = pickle.load(file)

train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])
test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

<ipython-input-32-dad9543c0862>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])
<ipython-input-32-dad9543c0862>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

## 70 FEATURES

In [33]:
train_data70 = train_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]
test_data70 = test_df[feature_dictionary['top 70'] + ['tp_ICD_cl0']]

In [34]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_70.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data70.columns if x.startswith('n_')]

train_data70[num_cols] = scaler.transform(train_data70[num_cols])
test_data70[num_cols] = scaler.transform(test_data70[num_cols])

<ipython-input-34-3bee303adb9f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data70[num_cols] = scaler.transform(train_data70[num_cols])
<ipython-input-34-3bee303adb9f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data70[num_cols] = scaler.transform(test_data70[num_cols])

In [35]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_70.pkl', 'rb') as file:
    le = pickle.load(file)

train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])
test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

<ipython-input-35-6ab11f4b1e9c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])
<ipython-input-35-6ab11f4b1e9c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

## 60 FEATURES

In [36]:
train_data60 = train_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]
test_data60 = test_df[feature_dictionary['top 60'] + ['tp_ICD_cl0']]

In [37]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_60.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data60.columns if x.startswith('n_')]

train_data60[num_cols] = scaler.transform(train_data60[num_cols])
test_data60[num_cols] = scaler.transform(test_data60[num_cols])

<ipython-input-37-80b488acb113>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data60[num_cols] = scaler.transform(train_data60[num_cols])
<ipython-input-37-80b488acb113>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data60[num_cols] = scaler.transform(test_data60[num_cols])

In [38]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_60.pkl', 'rb') as file:
    le = pickle.load(file)

train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])
test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

<ipython-input-38-e4d5e8685e83>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])
<ipython-input-38-e4d5e8685e83>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

## 50 FEATURES

In [39]:
train_data50 = train_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]
test_data50 = test_df[feature_dictionary['top 50'] + ['tp_ICD_cl0']]

In [40]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_50.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data50.columns if x.startswith('n_')]

train_data50[num_cols] = scaler.transform(train_data50[num_cols])
test_data50[num_cols] = scaler.transform(test_data50[num_cols])

<ipython-input-40-637e289183fc>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data50[num_cols] = scaler.transform(train_data50[num_cols])
<ipython-input-40-637e289183fc>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data50[num_cols] = scaler.transform(test_data50[num_cols])

In [41]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_50.pkl', 'rb') as file:
    le = pickle.load(file)

train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])
test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

<ipython-input-41-c06db5ef2e7d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])
<ipython-input-41-c06db5ef2e7d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

## 40 FEATURES

In [42]:
train_data40 = train_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]
test_data40 = test_df[feature_dictionary['top 40'] + ['tp_ICD_cl0']]

In [43]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_40.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data40.columns if x.startswith('n_')]

train_data40[num_cols] = scaler.transform(train_data40[num_cols])
test_data40[num_cols] = scaler.transform(test_data40[num_cols])

<ipython-input-43-e05a374fe52c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data40[num_cols] = scaler.transform(train_data40[num_cols])
<ipython-input-43-e05a374fe52c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data40[num_cols] = scaler.transform(test_data40[num_cols])

In [44]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_40.pkl', 'rb') as file:
    le = pickle.load(file)

train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])
test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

<ipython-input-44-7f88282e3a39>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])
<ipython-input-44-7f88282e3a39>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

## 30 FEATURES

In [45]:
train_data30 = train_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]
test_data30 = test_df[feature_dictionary['top 30'] + ['tp_ICD_cl0']]

In [46]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_30.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data30.columns if x.startswith('n_')]

train_data30[num_cols] = scaler.transform(train_data30[num_cols])
test_data30[num_cols] = scaler.transform(test_data30[num_cols])

<ipython-input-46-7b796c1929ff>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data30[num_cols] = scaler.transform(train_data30[num_cols])
<ipython-input-46-7b796c1929ff>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data30[num_cols] = scaler.transform(test_data30[num_cols])

In [47]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_30.pkl', 'rb') as file:
    le = pickle.load(file)

train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])
test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

<ipython-input-47-2b3f8ac79a19>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])
<ipython-input-47-2b3f8ac79a19>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

## 20 FEATURES

In [48]:
train_data20 = train_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]
test_data20 = test_df[feature_dictionary['top 20'] + ['tp_ICD_cl0']]

In [49]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_20.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data20.columns if x.startswith('n_')]

train_data20[num_cols] = scaler.transform(train_data20[num_cols])
test_data20[num_cols] = scaler.transform(test_data20[num_cols])

<ipython-input-49-55a266707538>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data20[num_cols] = scaler.transform(train_data20[num_cols])
<ipython-input-49-55a266707538>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data20[num_cols] = scaler.transform(test_data20[num_cols])

In [50]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_20.pkl', 'rb') as file:
    le = pickle.load(file)

train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])
test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

<ipython-input-50-7c0038e6c95b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])
<ipython-input-50-7c0038e6c95b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

## 10 FEATURES

In [51]:
train_data10 = train_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]
test_data10 = test_df[feature_dictionary['top 10'] + ['tp_ICD_cl0']]

In [52]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_10.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data10.columns if x.startswith('n_')]

train_data10[num_cols] = scaler.transform(train_data10[num_cols])
test_data10[num_cols] = scaler.transform(test_data10[num_cols])

<ipython-input-52-506e0a1cd87d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data10[num_cols] = scaler.transform(train_data10[num_cols])
<ipython-input-52-506e0a1cd87d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data10[num_cols] = scaler.transform(test_data10[num_cols])

In [53]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_10.pkl', 'rb') as file:
    le = pickle.load(file)

train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])
test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

<ipython-input-53-154e8dc9241a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])
<ipython-input-53-154e8dc9241a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

## 5 FEATURES

In [54]:
train_data5 = train_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]
test_data5 = test_df[feature_dictionary['top 5'] + ['tp_ICD_cl0']]

In [55]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/scaler_5.pkl', 'rb') as file:
    scaler = pickle.load(file)

num_cols = [x for x in test_data5.columns if x.startswith('n_')]

train_data5[num_cols] = scaler.transform(train_data5[num_cols])
test_data5[num_cols] = scaler.transform(test_data5[num_cols])

<ipython-input-55-38b2eab33523>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data5[num_cols] = scaler.transform(train_data5[num_cols])
<ipython-input-55-38b2eab33523>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data5[num_cols] = scaler.transform(test_data5[num_cols])

In [56]:
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/dataset/data_with_lk@500/label_encoder_5.pkl', 'rb') as file:
    le = pickle.load(file)

train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])
test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

<ipython-input-56-9ed65b4e62d0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])
<ipython-input-56-9ed65b4e62d0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

# FUNCTIONS

Jumlah Kelas:


*   Data @500 = 110 class
*   Data @1000 = 55 class
*   Data Top 10 Class = 10 class
*   Data all positive = 344 class
*   Data all pmr = 360 class
*   Data no_lk@500 = 211 class
*   Data no_lk@1000 = 161 class

In [57]:
# ubah threshold disini
threshold = [True, 1/26]

In [58]:
def get_predictions(y_prob, classes, threshold, top_n, y_true, le):
    y_pred = []

    keys = ['true_list', "pred_code1", "score1", "pred_code2", "score2", "pred_code3", "score3", "pred_code4", "score4", "pred_code5", "score5"]
    data_top_5 = {key: [] for key in keys}

    for idx, prob in enumerate(y_prob):
        above_threshold_indices = np.where(prob > threshold[1])[0]
        if len(above_threshold_indices) == 0:
            # If no classes are above the threshold, use the highest scores
            sorted_indices = np.argsort(-prob)[:top_n]
        else:
            # Sort filtered classes by probability in descending order
            above_threshold_probabilities = prob[above_threshold_indices]
            sorted_indices = above_threshold_indices[np.argsort(-above_threshold_probabilities)][:top_n]

        recommended_icd_code = [classes[i] for i in sorted_indices]
        recommended_score = [prob[i] for i in sorted_indices]
        if y_true[idx] in recommended_icd_code:
            y_pred.append(y_true[idx])
        else:
            y_pred.append(recommended_icd_code[0])

        # Ensure we have 5 elements in the lists
        while len(recommended_icd_code) < 5:
            recommended_icd_code.append(None)
            recommended_score.append(None)
        try:
            data_top_5['true_list'].append(le.inverse_transform([y_true[idx]])[0])
        except:
            data_top_5['true_list'].append(y_true[idx])

        try:
            data_top_5['pred_code1'].append(le.inverse_transform([recommended_icd_code[0]])[0])
        except:
            data_top_5['pred_code1'].append(recommended_icd_code[0])
        data_top_5['score1'].append(recommended_score[0])

        try:
            data_top_5['pred_code2'].append(le.inverse_transform([recommended_icd_code[1]])[0])
        except:
            data_top_5['pred_code2'].append(recommended_icd_code[1])
        data_top_5['score2'].append(recommended_score[1])

        try:
            data_top_5['pred_code3'].append(le.inverse_transform([recommended_icd_code[2]])[0])
        except:
            data_top_5['pred_code3'].append(recommended_icd_code[2])
        data_top_5['score3'].append(recommended_score[2])

        try:
            data_top_5['pred_code4'].append(le.inverse_transform([recommended_icd_code[3]])[0])
        except:
            data_top_5['pred_code4'].append(recommended_icd_code[3])
        data_top_5['score4'].append(recommended_score[3])

        try:
            data_top_5['pred_code5'].append(le.inverse_transform([recommended_icd_code[4]])[0])
        except:
            data_top_5['pred_code5'].append(recommended_icd_code[4])
        data_top_5['score5'].append(recommended_score[4])

    return y_pred, data_top_5

In [59]:
def knn_custom_kfold_evaluation(X, y, le, feature, n_splits=10, top_n=10, best_k=25):
    X = np.array(X)
    y = np.array(y)

    kf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    # kf = KFold(n_splits=n_splits)
    accuracy_scores, error_rates, precisions, recalls, f1_scores, index_list = [],[],[],[],[],[]

    cross_validation_results = pd.DataFrame(columns=["kfold", "accuracy", "f1_score", "error_rate", "recall", "precisions"])
    counter = 1

    for train_index, test_index in kf.split(X, y):
        index_list.append((train_index, test_index))
        X_train_fold, X_test_fold = X[train_index], X[test_index]
        y_train_fold, y_test_fold = y[train_index], y[test_index]

        if counter % 2 == 0:
            model = KNeighborsClassifier(n_neighbors=best_k, metric='jaccard')
        else:
            model = KNeighborsClassifier(n_neighbors=best_k, metric='jaccard', weights='distance')

        model.fit(X_train_fold, y_train_fold)

        classes = model.classes_
        y_prob = model.predict_proba(X_test_fold)

        y_true = y_test_fold
        y_pred, _ = get_predictions(y_prob, classes, threshold, top_n, y_test_fold, le)

        cm = pd.DataFrame(confusion_matrix(y_test_fold, y_pred))
        cm.index, cm.columns = le.inverse_transform(classes), le.inverse_transform(classes)

        # evaluation result per fold per class
        eval_per_fold = calculate_evaluation_metrics(Confusion_df=cm)
        eval_per_fold.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/data_per_fold_{feature}/eval_per_fold_{counter}.csv', index=False)

        accuracy = calculate_accuracy(cm)
        error_rate = 1 - accuracy
        precision = calculate_precision(cm)
        recall = calculate_recall(cm)
        f1_score = calculate_f1_score(precision, recall)

        cross_validation_results.loc[counter] = [int(counter), accuracy, f1_score, error_rate, recall, precision]

        accuracy_scores.append(accuracy)
        error_rates.append(error_rate)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1_score)

        counter += 1

    max_idx = np.argmax(cross_validation_results['accuracy'])
    cross_validation_results.loc[counter] = ["average", cross_validation_results["accuracy"].mean(), cross_validation_results["f1_score"].mean(), cross_validation_results["error_rate"].mean(), cross_validation_results["recall"].mean(), cross_validation_results["precisions"].mean()]
    cross_validation_results.loc[counter+1] = ["max", cross_validation_results["accuracy"][max_idx+1], cross_validation_results["f1_score"][max_idx+1], cross_validation_results["error_rate"][max_idx+1], cross_validation_results["recall"][max_idx+1], cross_validation_results["precisions"][max_idx+1]]
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    # cari fold mana yang akurasinya paling tinggi
    top_accuracy_idx = np.argmax(accuracy_scores)
    top_index_fold = index_list[top_accuracy_idx]

    if (top_accuracy_idx + 1) % 2 == 0:
        new_model = KNeighborsClassifier(n_neighbors=best_k, metric='jaccard')
    else:
        new_model = KNeighborsClassifier(n_neighbors=best_k, metric='jaccard', weights='distance')

    new_model.fit(X[top_index_fold[0]], y[top_index_fold[0]])
    new_y_prob = new_model.predict_proba(X)
    new_classes = new_model.classes_
    new_y_pred, data_top_5 = get_predictions(new_y_prob, new_classes, threshold, top_n, y, le)

    new_cm = pd.DataFrame(confusion_matrix(y, new_y_pred))
    new_cm.index, new_cm.columns = le.inverse_transform(new_classes), le.inverse_transform(new_classes)

    eval = calculate_evaluation_metrics(Confusion_df=new_cm)
    new_cm.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_train_knn{feature}.csv')
    eval.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_train_knn{feature}.csv', index=False)

    try:
        cross_validation_results = pd.read_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index_col=False)
    except:
        print("tidak ada data, ulangi proses cross val!")

    # append data fold ke 11
    accuracy11 = calculate_accuracy(new_cm)
    error_rate11 = 1 - accuracy11
    precision11 = calculate_precision(new_cm)
    recall11 = calculate_recall(new_cm)
    f1_score11 = calculate_f1_score(precision11, recall11)
    fold11 = [11, accuracy11, f1_score11, error_rate11, recall11, precision11]

    cross_validation_results = pd.concat([cross_validation_results.iloc[:10], pd.DataFrame([fold11], columns=cross_validation_results.columns), cross_validation_results.iloc[10:]], ignore_index=True)
    cross_validation_results.to_csv(f'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/cross_val_result_knn{feature}.csv', index=False)

    return new_model, data_top_5, new_cm, eval, cross_validation_results

In [60]:
def calculate_dcg(scores):
    return np.sum((2**scores - 1) / np.log2(np.arange(2, scores.size + 2)))

def calculate_ndcg(Confusion_df):
    ndcgs = []
    for i, true_label in enumerate(Confusion_df.index):
        predicted_scores = Confusion_df.loc[true_label].values
        ideal_scores = np.sort(predicted_scores)[::-1]
        dcg = calculate_dcg(predicted_scores)
        idcg = calculate_dcg(ideal_scores)
        ndcg = dcg / idcg if idcg > 0 else 0
        ndcgs.append(ndcg)
    return np.mean(ndcgs)

def calculate_accuracy(Confusion_df):
    diagonal_sum = np.trace(Confusion_df.values)
    total_sum = np.sum(Confusion_df.values)
    accuracy = diagonal_sum / total_sum
    return accuracy

def calculate_precision(Confusion_df):
    precisions = []
    for label in Confusion_df.columns:
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        precision = tp / column_sum if column_sum != 0 else 0
        precisions.append(precision)
    average_precision = np.mean(precisions)
    return average_precision

def calculate_recall(Confusion_df):
    recalls = []
    for label in Confusion_df.index:
        tp = Confusion_df.at[label, label]
        row_sum = Confusion_df.loc[label].sum()
        recall = tp / row_sum if row_sum != 0 else 0
        recalls.append(recall)
    average_recall = np.mean(recalls)
    return average_recall

def calculate_f1_score(precision, recall):
    if (precision + recall) == 0:
        return 0
    return 2 * (precision * recall) / (precision + recall)

def evaluate_predictions(data, classes):
    true_list = data['true_list']
    predicted_icd_codes, predicted_highest_score = [], []

    for i in range(len(data['true_list'])):
        top_5_pred = [
            data['pred_code1'][i],
            data['pred_code2'][i],
            data['pred_code3'][i],
            data['pred_code4'][i],
            data['pred_code5'][i]
        ]
        if data['true_list'][i] in top_5_pred:
            predicted_icd_codes.append(data['true_list'][i])
            predicted_highest_score.append(data[f'score{top_5_pred.index(data["true_list"][i]) + 1}'][i])
        else:
            predicted_icd_codes.append(data['pred_code1'][i])
            predicted_highest_score.append(data['score1'][i])

    Confusion = confusion_matrix(true_list, predicted_icd_codes)
    Confusion_df = pd.DataFrame(Confusion, columns=classes, index=classes)

    data_top_1 = pd.DataFrame({
        'true_icd_code': true_list,
        'predicted_icd_codes': predicted_icd_codes,
        'predicted_highest_score': predicted_highest_score
    })

    return true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1

In [61]:
def calculate_evaluation_metrics(data=None, classes=None, Confusion_df=None):
    if not isinstance(Confusion_df, pd.DataFrame):
        true_list, predicted_icd_codes, predicted_highest_score, Confusion, Confusion_df, data_top_1 = evaluate_predictions(data, classes)

    accuracy = calculate_accuracy(Confusion_df)
    precision = calculate_precision(Confusion_df)
    recall = calculate_recall(Confusion_df)

    eval_result = pd.DataFrame(columns=['class', 'accuracy', 'hit_rate', 'error_rate', 'specificity', 'precision', 'recall', 'f1', 'type_1_error', 'type_2_error', 'ndcg'])

    for idx, label in enumerate(Confusion_df.columns):
        tp = Confusion_df.at[label, label]
        column_sum = Confusion_df[label].sum()
        row_sum = Confusion_df.loc[label].sum()
        accuracy = tp / row_sum if row_sum != 0 else 0
        error_rate = 1 - accuracy
        specificity = (column_sum - tp) / (column_sum - tp + Confusion_df.values.sum() - row_sum)
        precision = tp / column_sum if column_sum != 0 else 0
        recall = tp / row_sum if row_sum != 0 else 0
        hit_rate = recall
        f1 = calculate_f1_score(precision, recall)
        type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
        type_2_error = (Confusion_df.loc[label].sum() - tp) / (Confusion_df.loc[label].sum())
        class_ndcg = calculate_ndcg(Confusion_df.loc[[label]])

        eval_result.loc[idx] = [label, accuracy, hit_rate, error_rate, specificity, precision, recall, f1, type_1_error, type_2_error, class_ndcg]

    avg_accuracy = eval_result['accuracy'].mean()
    avg_error_rate = eval_result['error_rate'].mean()
    avg_specificity = eval_result['specificity'].mean()
    avg_precision = eval_result['precision'].mean()
    avg_recall = eval_result['recall'].mean()
    avg_hit_rate = avg_recall
    avg_f1 = eval_result['f1'].mean()
    avg_type_1_error = eval_result['type_1_error'].mean()
    avg_type_2_error = eval_result['type_2_error'].mean()
    avg_ndcg = eval_result['ndcg'].mean()

    avg_row = ['average', avg_accuracy, avg_hit_rate, avg_error_rate, avg_specificity, avg_precision, avg_recall, avg_f1, avg_type_1_error, avg_type_2_error, avg_ndcg]
    eval_result.loc[len(eval_result)] = avg_row

    if not isinstance(Confusion_df, pd.DataFrame):
        return Confusion_df, eval_result, data_top_1
    else:
        return eval_result

In [62]:
class CalculateTime:
    def __init__(self, features, data_type):
        self.features = features
        self.data_type = data_type

    def start(self):
        self.start_time = time.time()

    def time_taken(self):
        return (time.time() - self.start_time) / 60

    def save_time_to_csv(self, time_taken, file_name='/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/training_times.csv'):
        df = pd.DataFrame({'features': [self.features],
                           'data_type': [self.data_type],
                           'time_taken (minutes)': [time_taken]})

        df.to_csv(file_name, mode='a', header=not pd.io.common.file_exists(file_name), index=False)

# **TRAINING**

## TRAIN knn TOP 5fi

In [63]:
# le = LabelEncoder()
# le.fit(train_data5['tp_ICD_cl0'])

In [64]:
# train_data5['tp_ICD_cl0'] = le.transform(train_data5['tp_ICD_cl0'])

In [65]:
# Separate features and tp_ICD_cl0 variable for train_data10
X_train5 = train_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_train5 = train_data5['tp_ICD_cl0']

In [66]:
timer = CalculateTime(features=5, data_type='train')
timer.start()

knn5, data_top_5, Confusion_df5, eval_result5, cv_result5 = knn_custom_kfold_evaluation(X_train5, y_train5, le, feature=5, best_k=24)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

Time taken: 0.25 minutes

<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

In [67]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667
2,41.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
3,129.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
4,169.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
5,161.0,161.0,0.375000,41.0,0.333333,169.0,0.083333,7.1,0.041667,104.1,0.041667
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667
10397,153.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
10398,169.0,161.0,0.375000,41.0,0.333333,169.0,0.083333,7.1,0.041667,104.1,0.041667
10399,249.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667
10400,150.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667

In [68]:
Confusion_df5

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,34,0,0,0,0,0,0,0,1,0,...,10,0,0,0,0,0,355,0,0,0
7.1,0,397,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,1,0
18.9,0,0,362,0,0,0,0,0,0,0,...,25,0,0,0,0,0,0,0,13,0
32.1,0,0,0,397,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0
41.0,0,0,0,0,199,0,0,0,0,0,...,0,0,0,0,0,0,201,0,0,0
98.9,0,0,0,0,0,367,0,0,0,0,...,33,0,0,0,0,0,0,0,0,0
104.1,0,0,0,0,0,0,34,0,16,0,...,0,0,0,0,0,0,349,0,1,0
111.0,0,0,0,0,0,0,0,0,3,0,...,29,0,0,0,0,0,368,0,0,0
128.0,0,0,0,0,0,0,0,0,339,0,...,0,0,0,0,0,0,60,0,1,0
129.0,0,0,0,0,0,0,0,0,0,0,...,8,0,0,0,0,0,392,0,0,0
146.0,0,0,0,0,0,0,0,0,22,0,...,57,0,0,0,0,0,0,0,0,0
147.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,361,0,0,0
150.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,312,0,1,0
151.0,0,0,0,0,0,0,0,0,2,0,...,96,0,0,0,0,0,301,0,0,0
153.0,0,0,0,0,0,0,0,0,1,0,...,2,0,0,0,0,0,0,0,0,0
154.0,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,396,0,0,0
161.0,0,0,0,0,0,0,0,0,0,0,...,235,0,0,0,0,0,163,0,2,0
169.0,0,0,0,0,0,0,0,0,0,0,...,0,126,0,0,0,0,265,0,9,0
185.9,0,0,0,0,0,0,0,0,0,0,...,13,0,387,0,0,0,0,0,0,0
197.0,0,0,0,0,0,0,0,0,0,0,...,8,0,0,390,0,0,0,0,2,0
212.9,0,0,0,0,0,0,0,0,0,0,...,25,0,0,0,35,0,340,0,0,0
217.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,400,0,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,398,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,0,383,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,399

In [69]:
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.085000,0.085000,0.915000,0.000000,1.000000,0.085000,0.156682,0.000000,0.915000,1.584962
1,7.1,0.992500,0.992500,0.007500,0.000000,1.000000,0.992500,0.996236,0.000000,0.007500,0.348155
2,18.9,0.905000,0.905000,0.095000,0.000000,1.000000,0.905000,0.950131,0.000000,0.095000,0.380103
3,32.1,0.992500,0.992500,0.007500,0.000000,1.000000,0.992500,0.996236,0.000000,0.007500,0.309833
4,41.0,0.497500,0.497500,0.502500,0.000000,1.000000,0.497500,0.664441,0.000000,0.502500,0.000000
5,98.9,0.917500,0.917500,0.082500,0.000000,1.000000,0.917500,0.956975,0.000000,0.082500,0.380094
6,104.1,0.085000,0.085000,0.915000,0.000000,1.000000,0.085000,0.156682,0.000000,0.915000,0.528321
7,111.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.380094
8,128.0,0.847500,0.847500,0.152500,0.004777,0.875969,0.847500,0.861499,0.124031,0.152500,0.345687
9,129.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.381107
10,146.0,0.802500,0.802500,0.197500,0.000000,1.000000,0.802500,0.890430,0.000000,0.197500,0.380094
11,147.0,0.095000,0.095000,0.905000,0.000000,1.000000,0.095000,0.173516,0.000000,0.905000,0.428317
12,150.0,0.217500,0.217500,0.782500,0.000000,1.000000,0.217500,0.357290,0.000000,0.782500,0.000000
13,151.0,0.002500,0.002500,0.997500,0.000000,1.000000,0.002500,0.004988,0.000000,0.997500,2.339078
14,153.0,0.992500,0.992500,0.007500,0.000000,1.000000,0.992500,0.996236,0.000000,0.007500,0.553183
15,154.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.399233
16,161.0,0.587500,0.587500,0.412500,0.030256,0.429616,0.587500,0.496304,0.570384,0.412500,0.000000
17,169.0,0.315000,0.315000,0.685000,0.000000,1.000000,0.315000,0.479087,0.000000,0.685000,0.426439
18,185.9,0.967500,0.967500,0.032500,0.000000,1.000000,0.967500,0.983482,0.000000,0.032500,0.380123
19,197.0,0.975000,0.975000,0.025000,0.000000,1.000000,0.975000,0.987342,0.000000,0.025000,0.381460
20,212.9,0.087500,0.087500,0.912500,0.000000,1.000000,0.087500,0.160920,0.000000,0.912500,0.355514
21,217.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
22,239.2,0.995000,0.995000,0.005000,0.279591,0.093012,0.995000,0.170122,0.906988,0.005000,0.561536
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.957500,0.957500,0.042500,0.003289,0.920673,0.957500,0.938725,0.079327,0.042500,0.345689
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.589038,0.589038,0.410962,0.012227,0.819972,0.589038,0.591387,0.073075,0.410962,0.430347

In [70]:
cv_result5

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.570192  0.631197    0.429808  0.570192    0.706820
1       2.0  0.569231  0.617296    0.430769  0.569231    0.674226
2       3.0  0.578846  0.634756    0.421154  0.578846    0.702621
3       4.0  0.568269  0.631076    0.431731  0.568269    0.709490
4       5.0  0.577885  0.652226    0.422115  0.577885    0.748520
5       6.0  0.580769  0.622473    0.419231  0.580769    0.670630
6       7.0  0.569231  0.615023    0.430769  0.569231    0.668826
7       8.0  0.589423  0.672227    0.410577  0.589423    0.782100
8       9.0  0.550962  0.605073    0.449038  0.550962    0.670971
9      10.0  0.575000  0.636561    0.425000  0.575000    0.712884
10       11  0.589038  0.685580    0.410962  0.589038    0.819972
11  average  0.572981  0.631791    0.427019  0.572981    0.704709
12      max  0.589423  0.672227    0.410577  0.589423    0.782100

### SAVE MODEL dTOP5fi

In [71]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier5.pkl', 'wb') as f:
    pickle.dump(knn5, f)

## TRAIN knn TOP 10fi

In [72]:
# train_data10['tp_ICD_cl0'] = le.transform(train_data10['tp_ICD_cl0'])

In [73]:
# Separate features and tp_ICD_cl0 variable for train_data10
X_train10 = train_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_train10 = train_data10['tp_ICD_cl0']

In [74]:
timer = CalculateTime(features=10, data_type='train')
timer.start()

knn10, data_top_5, Confusion_df10, eval_result10, cv_result10 = knn_custom_kfold_evaluation(X_train10, y_train10, le, feature=10, best_k=22)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

Time taken: 0.26 minutes

In [75]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN
2,41.0,239.2,0.272727,5.0,0.181818,7.1,0.136364,18.9,0.090909,169.0,0.090909
3,129.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
4,169.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
5,161.0,161.0,0.318182,41.0,0.272727,104.1,0.090909,169.0,0.090909,217.0,0.090909
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN
10397,153.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
10398,169.0,161.0,0.318182,41.0,0.272727,104.1,0.090909,169.0,0.090909,217.0,0.090909
10399,249.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN
10400,150.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909

In [76]:
Confusion_df10

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,82,0,0,309,0,0,0,0,1,0,...,7,0,0,0,0,0,0,0,1,0
7.1,0,394,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18.9,0,0,66,309,1,0,0,0,0,0,...,23,0,0,0,0,0,0,0,1,0
32.1,3,0,0,397,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,0,393,0,0,0,0,0,...,0,0,0,0,0,0,6,0,0,0
98.9,2,0,0,0,4,365,0,0,0,0,...,0,0,0,0,0,0,29,0,0,0
104.1,0,0,0,0,2,0,340,0,12,0,...,0,0,0,0,0,0,45,0,1,0
111.0,0,0,0,0,2,0,0,365,3,0,...,25,0,0,0,0,0,0,0,0,0
128.0,1,0,0,57,0,0,0,0,339,0,...,0,0,0,0,0,0,3,0,0,0
129.0,0,0,0,0,0,0,0,0,0,371,...,8,0,0,0,0,0,21,0,0,0
146.0,0,0,0,279,8,0,0,0,20,0,...,45,0,0,0,0,0,38,0,0,0
147.0,0,0,0,306,0,0,0,0,1,0,...,31,0,0,0,0,0,40,0,0,0
150.0,1,0,0,265,0,0,0,0,0,0,...,49,0,0,0,0,0,43,0,0,0
151.0,0,0,0,265,12,0,0,0,2,0,...,0,0,0,0,0,0,33,0,0,0
153.0,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,16,0,0,0
154.0,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,22,0,0,0
161.0,1,0,0,144,0,0,0,0,0,0,...,235,0,0,0,0,0,14,0,1,0
169.0,0,0,0,222,0,0,0,0,0,0,...,0,164,0,0,0,0,7,0,0,0
185.9,0,0,0,329,3,0,0,0,0,0,...,10,0,29,0,0,0,29,0,0,0
197.0,0,0,0,333,1,0,0,0,1,0,...,7,0,0,14,0,0,38,0,2,0
212.9,0,0,0,293,1,0,0,0,0,0,...,23,0,0,0,66,0,11,0,0,0
217.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,354,38,0,0,0
239.2,0,0,0,342,0,0,0,0,0,0,...,2,0,0,0,0,0,56,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,14,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,383,0
251.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [77]:
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.205000,0.205000,0.795000,0.000799,0.911111,0.205000,0.334694,0.088889,0.795000,0.471222
1,7.1,0.985000,0.985000,0.015000,0.000000,1.000000,0.985000,0.992443,0.000000,0.015000,0.384694
2,18.9,0.165000,0.165000,0.835000,0.000000,1.000000,0.165000,0.283262,0.000000,0.835000,0.479625
3,32.1,0.992500,0.992500,0.007500,0.257499,0.102717,0.992500,0.186166,0.897283,0.007500,1.922818
4,41.0,0.982500,0.982500,0.017500,0.003488,0.918224,0.982500,0.949275,0.081776,0.017500,0.346604
5,98.9,0.912500,0.912500,0.087500,0.000000,1.000000,0.912500,0.954248,0.000000,0.087500,0.345687
6,104.1,0.850000,0.850000,0.150000,0.000000,1.000000,0.850000,0.918919,0.000000,0.150000,0.345687
7,111.0,0.912500,0.912500,0.087500,0.000000,1.000000,0.912500,0.954248,0.000000,0.087500,0.380094
8,128.0,0.847500,0.847500,0.152500,0.003984,0.894459,0.847500,0.870347,0.105541,0.152500,0.682606
9,129.0,0.927500,0.927500,0.072500,0.000000,1.000000,0.927500,0.962387,0.000000,0.072500,0.345700
10,146.0,0.015000,0.015000,0.985000,0.000000,1.000000,0.015000,0.029557,0.000000,0.985000,0.380439
11,147.0,0.055000,0.055000,0.945000,0.000000,1.000000,0.055000,0.104265,0.000000,0.945000,0.345895
12,150.0,0.095000,0.095000,0.905000,0.000000,1.000000,0.095000,0.173516,0.000000,0.905000,0.380856
13,151.0,0.212500,0.212500,0.787500,0.000000,1.000000,0.212500,0.350515,0.000000,0.787500,0.436209
14,153.0,0.955000,0.955000,0.045000,0.006359,0.856502,0.955000,0.903073,0.143498,0.045000,0.345694
15,154.0,0.910000,0.910000,0.090000,0.000000,1.000000,0.910000,0.952880,0.000000,0.090000,0.345747
16,161.0,0.587500,0.587500,0.412500,0.022960,0.500000,0.587500,0.540230,0.500000,0.412500,0.436557
17,169.0,0.410000,0.410000,0.590000,0.000000,1.000000,0.410000,0.581560,0.000000,0.590000,0.504295
18,185.9,0.072500,0.072500,0.927500,0.000000,1.000000,0.072500,0.135198,0.000000,0.927500,0.397445
19,197.0,0.035000,0.035000,0.965000,0.000000,1.000000,0.035000,0.067633,0.000000,0.965000,0.345687
20,212.9,0.165000,0.165000,0.835000,0.000000,1.000000,0.165000,0.283262,0.000000,0.835000,0.479632
21,217.0,0.885000,0.885000,0.115000,0.000000,1.000000,0.885000,0.938992,0.000000,0.115000,0.345687
22,239.2,0.140000,0.140000,0.860000,0.041595,0.114286,0.140000,0.125843,0.885714,0.860000,0.345687
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.957500,0.957500,0.042500,0.000700,0.982051,0.957500,0.969620,0.017949,0.042500,0.682618
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.587404,0.587404,0.412596,0.012976,0.895360,0.587404,0.598495,0.104640,0.412596,0.441430

In [78]:
cv_result10

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.568269  0.700945    0.431731  0.568269    0.914442
1       2.0  0.587500  0.709186    0.412500  0.587500    0.894450
2       3.0  0.565385  0.681561    0.434615  0.565385    0.857829
3       4.0  0.554808  0.671603    0.445192  0.554808    0.850683
4       5.0  0.575962  0.680125    0.424038  0.575962    0.830282
5       6.0  0.587500  0.684972    0.412500  0.587500    0.821221
6       7.0  0.580769  0.699164    0.419231  0.580769    0.878192
7       8.0  0.576923  0.701217    0.423077  0.576923    0.893774
8       9.0  0.570192  0.673497    0.429808  0.570192    0.822515
9      10.0  0.575962  0.702825    0.424038  0.575962    0.901363
10       11  0.587404  0.709402    0.412596  0.587404    0.895360
11  average  0.574327  0.690509    0.425673  0.574327    0.866475
12      max  0.587500  0.709186    0.412500  0.587500    0.894450

### SAVE MODEL dTOP10fi

In [79]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier10.pkl', 'wb') as f:
    pickle.dump(knn10, f)

## TRAIN knn TOP 20fi

In [80]:
# train_data20['tp_ICD_cl0'] = le.transform(train_data20['tp_ICD_cl0'])

In [81]:
# Separate features and tp_ICD_cl0 variable for train_data20
X_train20 = train_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_train20 = train_data20['tp_ICD_cl0']

In [82]:
timer = CalculateTime(features=20, data_type='train')
timer.start()

knn20, data_top_5, Confusion_df20, eval_result20, cv_result20 = knn_custom_kfold_evaluation(X_train20, y_train20, le, feature=20, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.38 minutes

In [83]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.40,248.0,0.35,251.0,0.25,NaN,NaN,NaN,NaN
2,41.0,197.0,0.25,146.0,0.20,5.0,0.10,147.0,0.1,212.9,0.1
3,129.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
4,169.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
5,161.0,169.0,0.25,7.1,0.15,161.0,0.15,41.0,0.1,146.0,0.1
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.40,248.0,0.35,251.0,0.25,NaN,NaN,NaN,NaN
10397,153.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
10398,169.0,169.0,0.25,7.1,0.15,161.0,0.15,41.0,0.1,146.0,0.1
10399,249.0,249.0,0.40,248.0,0.35,251.0,0.25,NaN,NaN,NaN,NaN
10400,150.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1

In [84]:
Confusion_df20

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,388,0,0,0,1,0,0,0,0,0,...,4,0,0,0,0,0,0,0,1,0
7.1,0,211,0,0,2,0,28,0,2,0,...,1,0,150,5,0,0,0,0,1,0
18.9,27,0,89,0,0,0,5,0,0,0,...,0,3,268,0,0,0,0,0,1,0
32.1,0,0,0,375,1,0,5,0,6,0,...,0,0,2,0,0,0,0,0,0,0
41.0,8,0,0,0,303,0,2,0,0,0,...,0,0,84,1,0,0,0,0,0,0
98.9,0,0,0,3,0,335,23,0,4,0,...,22,0,0,0,0,0,0,0,0,0
104.1,0,1,0,1,1,0,190,0,14,0,...,0,0,187,0,0,0,0,0,1,0
111.0,0,4,0,0,1,0,0,331,3,0,...,15,2,42,2,0,0,0,0,0,0
128.0,0,0,0,5,0,0,0,0,341,0,...,0,0,52,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,0,392,...,8,0,0,0,0,0,0,0,0,0
146.0,16,1,0,0,0,0,0,0,20,0,...,23,0,0,0,0,0,0,0,0,0
147.0,0,1,0,0,1,0,0,0,1,0,...,3,4,9,0,0,0,0,0,0,0
150.0,23,0,0,0,0,0,32,0,26,0,...,10,5,216,2,0,0,0,0,0,0
151.0,15,4,0,0,0,0,0,0,2,0,...,7,0,154,0,0,0,0,0,0,0
153.0,25,0,0,0,0,0,49,0,0,0,...,2,0,19,0,0,0,0,0,0,0
154.0,19,1,0,1,0,0,26,0,0,0,...,3,0,320,1,0,0,0,0,0,0
161.0,3,0,1,8,0,0,1,0,0,0,...,347,0,40,0,0,0,0,0,0,0
169.0,0,0,0,0,0,0,31,0,0,0,...,0,197,169,3,0,0,0,0,0,0
185.9,14,2,0,12,0,0,0,0,0,0,...,7,0,360,0,0,0,0,0,0,0
197.0,16,0,0,2,1,0,0,0,1,0,...,5,0,200,163,0,0,0,0,2,0
212.9,21,1,0,0,1,0,3,0,0,0,...,2,1,212,0,146,0,0,0,0,0
217.0,23,1,0,1,1,0,1,0,1,0,...,3,0,255,5,0,96,0,0,0,0
239.2,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,360,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,15,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,399

In [85]:
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.970000,0.970000,0.030000,0.024200,0.610063,0.970000,0.749035,0.389937,0.030000,0.402557
1,7.1,0.527500,0.527500,0.472500,0.001597,0.929515,0.527500,0.673046,0.070485,0.472500,0.666667
2,18.9,0.222500,0.222500,0.777500,0.000100,0.988889,0.222500,0.363265,0.011111,0.777500,1.999999
3,32.1,0.937500,0.937500,0.062500,0.003289,0.919118,0.937500,0.928218,0.080882,0.062500,0.405196
4,41.0,0.757500,0.757500,0.242500,0.000999,0.968051,0.757500,0.849930,0.031949,0.242500,1.992257
5,98.9,0.837500,0.837500,0.162500,0.000000,1.000000,0.837500,0.911565,0.000000,0.162500,0.514533
6,104.1,0.475000,0.475000,0.525000,0.021622,0.462287,0.475000,0.468557,0.537713,0.525000,0.602176
7,111.0,0.827500,0.827500,0.172500,0.000000,1.000000,0.827500,0.905609,0.000000,0.172500,0.366726
8,128.0,0.852500,0.852500,0.147500,0.007937,0.809976,0.852500,0.830694,0.190024,0.147500,0.366726
9,129.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.380663
10,146.0,0.845000,0.845000,0.155000,0.000000,1.000000,0.845000,0.915989,0.000000,0.155000,0.409380
11,147.0,0.920000,0.920000,0.080000,0.000100,0.997290,0.920000,0.957087,0.002710,0.080000,0.399852
12,150.0,0.205000,0.205000,0.795000,0.000000,1.000000,0.205000,0.340249,0.000000,0.795000,0.669951
13,151.0,0.530000,0.530000,0.470000,0.000000,1.000000,0.530000,0.692810,0.000000,0.470000,1.994222
14,153.0,0.762500,0.762500,0.237500,0.011174,0.729665,0.762500,0.745721,0.270335,0.237500,0.528321
15,154.0,0.072500,0.072500,0.927500,0.000000,1.000000,0.072500,0.135198,0.000000,0.927500,0.414057
16,161.0,0.867500,0.867500,0.132500,0.011369,0.751082,0.867500,0.805104,0.248918,0.132500,0.366726
17,169.0,0.492500,0.492500,0.507500,0.001498,0.929245,0.492500,0.643791,0.070755,0.507500,0.666667
18,185.9,0.900000,0.900000,0.100000,0.192246,0.131387,0.900000,0.229299,0.868613,0.100000,1.460671
19,197.0,0.407500,0.407500,0.592500,0.001896,0.895604,0.407500,0.560137,0.104396,0.592500,1.980678
20,212.9,0.365000,0.365000,0.635000,0.000000,1.000000,0.365000,0.534799,0.000000,0.635000,1.995238
21,217.0,0.240000,0.240000,0.760000,0.000000,1.000000,0.240000,0.387097,0.000000,0.760000,1.998803
22,239.2,0.900000,0.900000,0.100000,0.000000,1.000000,0.900000,0.947368,0.000000,0.100000,1.584963
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000600,0.984655,0.962500,0.973451,0.015345,0.037500,0.528336
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.686731,0.686731,0.313269,0.010716,0.888724,0.686731,0.712949,0.111276,0.313269,0.872899

In [86]:
cv_result20

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.665385  0.755689    0.334615  0.665385    0.874355
1       2.0  0.642308  0.721906    0.357692  0.642308    0.824023
2       3.0  0.664423  0.747942    0.335577  0.664423    0.855477
3       4.0  0.646154  0.738438    0.353846  0.646154    0.861474
4       5.0  0.628846  0.712383    0.371154  0.628846    0.821514
5       6.0  0.631731  0.716603    0.368269  0.631731    0.827819
6       7.0  0.676923  0.752370    0.323077  0.676923    0.846744
7       8.0  0.630769  0.725640    0.369231  0.630769    0.854101
8       9.0  0.675000  0.752134    0.325000  0.675000    0.849172
9      10.0  0.687500  0.772067    0.312500  0.687500    0.880356
10       11  0.686731  0.774778    0.313269  0.686731    0.888724
11  average  0.654904  0.739517    0.345096  0.654904    0.849503
12      max  0.687500  0.772067    0.312500  0.687500    0.880356

### SAVE MODEL dTOP20fi

In [87]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier20.pkl', 'wb') as f:
    pickle.dump(knn20, f)

## TRAIN knn TOP 30fi

In [88]:
# train_data30['tp_ICD_cl0'] = le.transform(train_data30['tp_ICD_cl0'])

In [89]:
# Separate features and tp_ICD_cl0 variable for train_data30
X_train30 = train_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_train30 = train_data30['tp_ICD_cl0']

In [90]:
timer = CalculateTime(features=30, data_type='train')
timer.start()

knn30, data_top_5, Confusion_df30, eval_result30, cv_result30 = knn_custom_kfold_evaluation(X_train30, y_train30, le, feature=30, best_k=23)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.47 minutes

In [91]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.391304,249.0,0.391304,251.0,0.217391,NaN,NaN,NaN,NaN
2,41.0,7.1,0.130435,104.1,0.130435,146.0,0.130435,197.0,0.130435,111.0,0.086957
3,129.0,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
4,169.0,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
5,161.0,7.1,0.260870,161.0,0.260870,169.0,0.130435,41.0,0.086957,98.9,0.086957
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.391304,249.0,0.391304,251.0,0.217391,NaN,NaN,NaN,NaN
10397,153.0,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
10398,169.0,7.1,0.260870,161.0,0.260870,169.0,0.130435,41.0,0.086957,98.9,0.086957
10399,249.0,248.0,0.391304,249.0,0.391304,251.0,0.217391,NaN,NaN,NaN,NaN
10400,150.0,154.0,0.434783,239.2,0.130435,146.0,0.086957,151.0,0.086957,18.9,0.043478

In [92]:
Confusion_df30

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,141,7,0,233,2,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
7.1,0,215,10,133,7,0,0,0,2,0,...,1,0,1,0,0,0,0,1,0,0
18.9,0,0,384,0,0,0,0,0,0,0,...,0,0,0,0,0,3,7,1,0,0
32.1,0,2,0,389,3,0,0,0,6,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,1,0,47,343,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
98.9,0,0,11,0,0,357,0,1,0,0,...,0,0,0,0,0,2,6,0,0,0
104.1,0,1,4,162,12,0,144,0,0,0,...,1,0,0,0,0,1,4,1,0,0
111.0,0,4,0,233,0,0,0,149,0,0,...,2,6,0,0,0,0,6,0,0,0
128.0,0,0,1,52,0,0,0,0,345,0,...,0,0,0,0,0,0,2,0,0,0
129.0,0,0,31,0,5,0,0,0,0,351,...,0,2,0,0,0,11,0,0,0,0
146.0,0,0,2,126,24,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,0,1,12,116,17,0,0,0,1,0,...,2,2,0,0,0,0,4,0,0,0
150.0,0,0,4,198,15,3,0,0,25,0,...,1,8,0,0,0,9,8,0,0,0
151.0,0,9,14,130,5,1,0,0,2,0,...,0,6,0,0,0,7,4,0,0,0
153.0,0,4,22,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
154.0,1,1,15,0,24,0,0,0,0,0,...,0,0,0,0,0,7,11,0,0,0
161.0,0,0,3,35,0,0,0,0,0,0,...,356,0,0,0,0,5,0,0,0,0
169.0,0,3,5,138,0,0,0,1,0,0,...,0,205,0,0,0,10,5,0,0,0
185.9,1,4,20,0,27,0,0,0,1,0,...,0,0,337,0,0,0,3,0,0,0
197.0,0,0,17,1,31,0,1,0,1,0,...,1,2,0,341,0,2,0,2,0,0
212.9,0,2,25,176,35,0,3,1,33,0,...,1,0,0,0,37,7,0,0,0,0
217.0,0,5,0,0,23,0,1,0,4,0,...,0,2,0,0,0,356,6,0,0,0
239.2,1,0,37,0,0,0,0,0,0,0,...,0,0,0,0,0,0,360,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,383,0
251.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [93]:
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.352500,0.352500,0.647500,0.000300,0.979167,0.352500,0.518382,0.020833,0.647500,0.543556
1,7.1,0.537500,0.537500,0.462500,0.004381,0.830116,0.537500,0.652504,0.169884,0.462500,0.540477
2,18.9,0.960000,0.960000,0.040000,0.022769,0.622366,0.960000,0.755162,0.377634,0.040000,0.380899
3,32.1,0.972500,0.972500,0.027500,0.151176,0.179263,0.972500,0.302724,0.820737,0.027500,0.531342
4,41.0,0.857500,0.857500,0.142500,0.022578,0.597561,0.857500,0.704312,0.402439,0.142500,0.682606
5,98.9,0.892500,0.892500,0.107500,0.000400,0.988920,0.892500,0.938239,0.011080,0.107500,0.387881
6,104.1,0.360000,0.360000,0.640000,0.000600,0.960000,0.360000,0.523636,0.040000,0.640000,0.899278
7,111.0,0.372500,0.372500,0.627500,0.000300,0.980263,0.372500,0.539855,0.019737,0.627500,0.595064
8,128.0,0.862500,0.862500,0.137500,0.007444,0.821429,0.862500,0.841463,0.178571,0.137500,0.682606
9,129.0,0.877500,0.877500,0.122500,0.000000,1.000000,0.877500,0.934754,0.000000,0.122500,0.792481
10,146.0,0.620000,0.620000,0.380000,0.000000,1.000000,0.620000,0.765432,0.000000,0.380000,0.773706
11,147.0,0.595000,0.595000,0.405000,0.031477,0.422735,0.595000,0.494289,0.577265,0.405000,0.783744
12,150.0,0.322500,0.322500,0.677500,0.000000,1.000000,0.322500,0.487713,0.000000,0.677500,0.602310
13,151.0,0.552500,0.552500,0.447500,0.000200,0.991031,0.552500,0.709470,0.008969,0.447500,1.008810
14,153.0,0.805000,0.805000,0.195000,0.000000,1.000000,0.805000,0.891967,0.000000,0.195000,0.428317
15,154.0,0.787500,0.787500,0.212500,0.004678,0.870166,0.787500,0.826772,0.129834,0.212500,0.526639
16,161.0,0.890000,0.890000,0.110000,0.001199,0.967391,0.890000,0.927083,0.032609,0.110000,0.682606
17,169.0,0.512500,0.512500,0.487500,0.002892,0.876068,0.512500,0.646688,0.123932,0.487500,0.540476
18,185.9,0.842500,0.842500,0.157500,0.000100,0.997041,0.842500,0.913279,0.002959,0.157500,0.615528
19,197.0,0.852500,0.852500,0.147500,0.000000,1.000000,0.852500,0.920378,0.000000,0.147500,0.613166
20,212.9,0.092500,0.092500,0.907500,0.000000,1.000000,0.092500,0.169336,0.000000,0.907500,0.537862
21,217.0,0.890000,0.890000,0.110000,0.006655,0.841608,0.890000,0.865128,0.158392,0.110000,0.613149
22,239.2,0.900000,0.900000,0.100000,0.006557,0.845070,0.900000,0.871671,0.154930,0.100000,0.792481
23,248.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
24,249.0,0.957500,0.957500,0.042500,0.000000,1.000000,0.957500,0.978289,0.000000,0.042500,0.428364
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.717788,0.717788,0.282212,0.010166,0.875208,0.717788,0.737301,0.124792,0.282212,0.576283

In [94]:
cv_result30

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.614423  0.700570    0.385577  0.614423    0.814813
1       2.0  0.658654  0.740030    0.341346  0.658654    0.844348
2       3.0  0.674038  0.735449    0.325962  0.674038    0.809172
3       4.0  0.652885  0.725619    0.347115  0.652885    0.816592
4       5.0  0.680769  0.747987    0.319231  0.680769    0.829934
5       6.0  0.657692  0.734935    0.342308  0.657692    0.832736
6       7.0  0.647115  0.704593    0.352885  0.647115    0.773277
7       8.0  0.686538  0.757210    0.313462  0.686538    0.844101
8       9.0  0.666346  0.733198    0.333654  0.666346    0.814961
9      10.0  0.677885  0.750291    0.322115  0.677885    0.840015
10       11  0.717788  0.788720    0.282212  0.717788    0.875208
11  average  0.661635  0.732988    0.338365  0.661635    0.821995
12      max  0.686538  0.757210    0.313462  0.686538    0.844101

### SAVE MODEL dTOP30fi

In [95]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier30.pkl', 'wb') as f:
    pickle.dump(knn30, f)

## TRAIN knn TOP 40fi

In [96]:
# train_data40['tp_ICD_cl0'] = le.transform(train_data40['tp_ICD_cl0'])

In [97]:
# Separate features and tp_ICD_cl0 variable for train_data30
X_train40 = train_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_train40 = train_data40['tp_ICD_cl0']

In [98]:
timer = CalculateTime(features=40, data_type='train')
timer.start()

knn40, data_top_5, Confusion_df40, eval_result40, cv_result40 = knn_custom_kfold_evaluation(X_train40, y_train40, le, feature=40, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.55 minutes

In [99]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.380952,248.0,0.285714,249.0,0.285714,104.1,0.047619,NaN,NaN
2,41.0,151.0,0.238095,98.9,0.142857,197.0,0.142857,104.1,0.095238,147.0,0.095238
3,129.0,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
4,169.0,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
5,161.0,161.0,0.380952,41.0,0.190476,7.1,0.142857,169.0,0.142857,151.0,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.380952,248.0,0.285714,249.0,0.285714,104.1,0.047619,NaN,NaN
10397,153.0,153.0,0.333333,98.9,0.095238,104.1,0.095238,111.0,0.095238,150.0,0.095238
10398,169.0,161.0,0.380952,41.0,0.190476,7.1,0.142857,169.0,0.142857,151.0,0.095238
10399,249.0,251.0,0.380952,248.0,0.285714,249.0,0.285714,104.1,0.047619,NaN,NaN
10400,150.0,154.0,0.238095,98.9,0.142857,18.9,0.095238,41.0,0.047619,104.1,0.047619

In [100]:
Confusion_df40

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,350,0,6,0,2,0,0,0,0,0,...,17,0,1,0,0,0,0,0,0,1
7.1,0,347,5,0,1,0,0,0,2,0,...,6,0,0,0,0,0,0,0,0,1
18.9,254,0,88,1,10,0,0,0,0,0,...,28,0,0,1,0,0,0,0,0,1
32.1,3,0,0,386,1,0,0,0,6,0,...,2,0,0,0,0,0,0,0,0,0
41.0,37,0,0,0,346,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
98.9,2,0,0,0,5,346,0,0,0,0,...,6,0,1,0,0,0,0,0,0,0
104.1,1,0,2,1,2,0,372,0,0,0,...,1,0,0,0,0,0,0,0,0,0
111.0,209,0,0,0,7,0,0,147,3,0,...,4,0,5,0,0,0,0,0,0,0
128.0,0,0,0,5,0,0,0,0,394,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,1,0,5,0,0,0,0,385,...,2,0,0,0,0,0,0,0,0,0
146.0,0,0,0,0,6,0,0,0,0,0,...,15,0,0,0,0,0,0,0,0,0
147.0,0,1,8,1,1,0,0,0,1,0,...,6,0,0,0,0,0,0,0,0,0
150.0,193,0,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
151.0,130,2,2,0,0,0,0,0,2,0,...,4,0,0,0,0,0,0,0,0,0
153.0,199,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
154.0,243,0,0,1,1,0,1,0,1,0,...,0,0,2,0,0,0,0,0,0,0
161.0,30,0,12,0,0,0,0,0,0,0,...,346,0,0,0,0,0,0,0,0,0
169.0,127,1,5,0,1,0,0,1,0,0,...,19,189,2,0,1,0,0,0,0,0
185.9,0,1,4,0,4,0,0,0,16,0,...,20,0,314,0,1,0,0,0,0,0
197.0,182,0,2,1,1,1,0,0,1,0,...,28,0,0,56,0,0,0,0,0,2
212.9,169,1,4,1,13,0,3,1,0,0,...,2,0,0,0,188,0,0,0,0,0
217.0,197,0,4,11,4,1,1,0,4,1,...,14,0,0,0,3,130,0,0,0,0
239.2,333,0,2,0,0,2,0,0,1,0,...,0,0,0,0,0,0,22,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,384,0
251.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [101]:
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.875000,0.875000,0.125000,0.187652,0.131579,0.875000,0.228758,0.868421,0.125000,0.407102
1,7.1,0.867500,0.867500,0.132500,0.000600,0.983003,0.867500,0.921647,0.016997,0.132500,0.428318
2,18.9,0.220000,0.220000,0.780000,0.006458,0.575163,0.220000,0.318264,0.424837,0.780000,0.479626
3,32.1,0.965000,0.965000,0.035000,0.002195,0.946078,0.965000,0.955446,0.053922,0.035000,0.608300
4,41.0,0.865000,0.865000,0.135000,0.006557,0.839806,0.865000,0.852217,0.160194,0.135000,1.584962
5,98.9,0.865000,0.865000,0.135000,0.000400,0.988571,0.865000,0.922667,0.011429,0.135000,0.428330
6,104.1,0.930000,0.930000,0.070000,0.000600,0.984127,0.930000,0.956298,0.015873,0.070000,0.416649
7,111.0,0.367500,0.367500,0.632500,0.000300,0.980000,0.367500,0.534545,0.020000,0.632500,0.561013
8,128.0,0.985000,0.985000,0.015000,0.003686,0.914153,0.985000,0.948255,0.085847,0.015000,0.698500
9,129.0,0.962500,0.962500,0.037500,0.000100,0.997409,0.962500,0.979644,0.002591,0.037500,0.456804
10,146.0,0.940000,0.940000,0.060000,0.006557,0.850679,0.940000,0.893112,0.149321,0.060000,0.380716
11,147.0,0.917500,0.917500,0.082500,0.027521,0.564615,0.917500,0.699048,0.435385,0.082500,0.471956
12,150.0,0.482500,0.482500,0.517500,0.016813,0.530220,0.482500,0.505236,0.469780,0.517500,0.800480
13,151.0,0.607500,0.607500,0.392500,0.001797,0.931034,0.607500,0.735250,0.068966,0.392500,0.526063
14,153.0,0.320000,0.320000,0.680000,0.001697,0.882759,0.320000,0.469725,0.117241,0.680000,0.540476
15,154.0,0.365000,0.365000,0.635000,0.008527,0.629310,0.365000,0.462025,0.370690,0.635000,0.603285
16,161.0,0.865000,0.865000,0.135000,0.017102,0.665385,0.865000,0.752174,0.334615,0.135000,1.584961
17,169.0,0.472500,0.472500,0.527500,0.000000,1.000000,0.472500,0.641766,0.000000,0.527500,0.540520
18,185.9,0.785000,0.785000,0.215000,0.001199,0.963190,0.785000,0.865014,0.036810,0.215000,0.402335
19,197.0,0.140000,0.140000,0.860000,0.000100,0.982456,0.140000,0.245077,0.017544,0.860000,0.455340
20,212.9,0.470000,0.470000,0.530000,0.000500,0.974093,0.470000,0.634064,0.025907,0.530000,0.771730
21,217.0,0.325000,0.325000,0.675000,0.000000,1.000000,0.325000,0.490566,0.000000,0.675000,0.568986
22,239.2,0.055000,0.055000,0.945000,0.000000,1.000000,0.055000,0.104265,0.000000,0.945000,0.416292
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.428369
25,251.0,0.997500,0.997500,0.002500,0.000500,0.987624,0.997500,0.992537,0.012376,0.002500,0.000000
26,average,0.677115,0.677115,0.322885,0.011187,0.857741,0.677115,0.695661,0.142259,0.322885,0.560043

In [102]:
cv_result40

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.650000  0.725787    0.350000  0.650000    0.821579
1       2.0  0.656731  0.732163    0.343269  0.656731    0.827173
2       3.0  0.622115  0.685741    0.377885  0.622115    0.763862
3       4.0  0.646154  0.699887    0.353846  0.646154    0.763367
4       5.0  0.652885  0.728258    0.347115  0.652885    0.823305
5       6.0  0.671154  0.735413    0.328846  0.671154    0.813279
6       7.0  0.677885  0.749195    0.322115  0.677885    0.837271
7       8.0  0.670192  0.744648    0.329808  0.670192    0.837714
8       9.0  0.669231  0.732659    0.330769  0.669231    0.809369
9      10.0  0.679808  0.746917    0.320192  0.679808    0.828729
10       11  0.677115  0.756800    0.322885  0.677115    0.857741
11  average  0.659615  0.728067    0.340385  0.659615    0.812565
12      max  0.679808  0.746917    0.320192  0.679808    0.828729

### SAVE MODEL dTOP40fi

In [103]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier40.pkl', 'wb') as f:
    pickle.dump(knn40, f)

## TRAIN knn TOP 50fi

In [104]:
# train_data50['tp_ICD_cl0'] = le.transform(train_data50['tp_ICD_cl0'])

In [105]:
# Separate features and tp_ICD_cl0 variable for train_data50
X_train50 = train_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_train50 = train_data50['tp_ICD_cl0']

In [106]:
timer = CalculateTime(features=50, data_type='train')
timer.start()

knn50, data_top_5, Confusion_df50, eval_result50, cv_result50 = knn_custom_kfold_evaluation(X_train50, y_train50, le, feature=50, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.64 minutes

In [107]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,251.0,0.428571,248.0,0.333333,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,151.0,0.238095,104.1,0.190476,7.1,0.142857,197.0,0.095238,212.9,0.095238
3,129.0,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
4,169.0,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
5,161.0,161.0,0.476190,41.0,0.190476,7.1,0.142857,169.0,0.095238,150.0,0.047619
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,251.0,0.428571,248.0,0.333333,249.0,0.238095,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.380952,111.0,0.142857,129.0,0.095238,154.0,0.095238,18.9,0.047619
10398,169.0,161.0,0.476190,41.0,0.190476,7.1,0.142857,169.0,0.095238,150.0,0.047619
10399,249.0,251.0,0.428571,248.0,0.333333,249.0,0.238095,NaN,NaN,NaN,NaN
10400,150.0,154.0,0.285714,146.0,0.190476,98.9,0.095238,111.0,0.095238,151.0,0.095238

In [108]:
Confusion_df50

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,345,0,6,7,3,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
7.1,2,252,0,0,2,0,0,0,2,4,...,0,0,0,0,0,0,131,0,0,1
18.9,1,0,365,0,0,0,0,0,0,15,...,3,0,0,0,0,0,0,0,0,1
32.1,0,0,7,380,0,0,0,0,6,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,0,1,348,0,0,0,0,0,...,1,0,0,0,0,0,35,0,0,0
98.9,2,0,4,0,6,185,0,0,0,0,...,6,0,1,0,0,0,168,0,0,0
104.1,2,0,4,4,15,1,336,0,0,22,...,1,0,0,2,0,0,0,0,0,1
111.0,3,3,0,6,7,0,0,122,3,0,...,2,0,0,0,0,0,207,0,0,0
128.0,0,0,0,2,0,0,0,0,346,0,...,0,0,0,0,0,0,51,0,0,0
129.0,0,0,0,0,7,0,0,0,0,368,...,1,0,0,0,0,0,0,0,0,0
146.0,0,0,2,0,5,0,0,0,17,0,...,4,0,0,0,0,0,122,0,0,0
147.0,0,1,0,0,2,0,0,1,1,4,...,1,0,0,0,0,0,0,0,0,0
150.0,3,0,4,0,18,0,0,0,25,0,...,1,0,0,0,0,0,0,0,0,0
151.0,0,2,0,4,6,0,0,0,2,4,...,5,0,0,0,0,0,129,0,0,0
153.0,0,0,0,13,2,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
154.0,0,0,0,12,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
161.0,0,0,0,2,0,0,0,0,0,27,...,342,0,0,0,0,0,25,0,0,0
169.0,0,0,5,5,1,1,0,0,0,10,...,0,181,2,0,0,0,126,0,0,0
185.9,0,1,0,3,6,0,0,0,1,16,...,1,0,126,0,0,0,223,0,0,0
197.0,2,0,2,0,3,0,1,0,2,26,...,0,0,0,151,0,0,180,0,0,2
212.9,2,1,6,7,12,1,0,1,32,15,...,2,0,1,0,146,0,163,0,0,0
217.0,1,0,0,0,6,0,1,0,5,13,...,2,0,2,1,0,142,196,0,0,0
239.2,0,0,2,14,1,0,0,0,0,0,...,0,0,0,0,0,1,381,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,384,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,399

In [109]:
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.862500,0.862500,0.137500,0.001797,0.950413,0.862500,0.904325,0.049587,0.137500,0.397697
1,7.1,0.630000,0.630000,0.370000,0.000799,0.969231,0.630000,0.763636,0.030769,0.370000,0.859670
2,18.9,0.912500,0.912500,0.087500,0.004182,0.896806,0.912500,0.904585,0.103194,0.087500,0.458513
3,32.1,0.950000,0.950000,0.050000,0.007937,0.826087,0.950000,0.883721,0.173913,0.050000,0.674720
4,41.0,0.870000,0.870000,0.130000,0.010195,0.771619,0.870000,0.817861,0.228381,0.130000,0.345687
5,98.9,0.462500,0.462500,0.537500,0.000300,0.984043,0.462500,0.629252,0.015957,0.537500,0.511916
6,104.1,0.840000,0.840000,0.160000,0.000400,0.988235,0.840000,0.908108,0.011765,0.160000,0.460105
7,111.0,0.305000,0.305000,0.695000,0.000200,0.983871,0.305000,0.465649,0.016129,0.695000,0.511916
8,128.0,0.865000,0.865000,0.135000,0.009509,0.782805,0.865000,0.821853,0.217195,0.135000,0.345687
9,129.0,0.920000,0.920000,0.080000,0.015360,0.702290,0.920000,0.796537,0.297710,0.080000,0.396406
10,146.0,0.620000,0.620000,0.380000,0.003587,0.873239,0.620000,0.725146,0.126761,0.380000,0.602145
11,147.0,0.935000,0.935000,0.065000,0.004777,0.886256,0.935000,0.909976,0.113744,0.065000,0.400055
12,150.0,0.825000,0.825000,0.175000,0.000000,1.000000,0.825000,0.904110,0.000000,0.175000,0.479215
13,151.0,0.570000,0.570000,0.430000,0.018357,0.549398,0.570000,0.559509,0.450602,0.430000,0.506973
14,153.0,0.945000,0.945000,0.055000,0.018742,0.664323,0.945000,0.780186,0.335677,0.055000,0.682624
15,154.0,0.855000,0.855000,0.145000,0.001996,0.944751,0.855000,0.897638,0.055249,0.145000,0.405727
16,161.0,0.855000,0.855000,0.145000,0.003090,0.916890,0.855000,0.884864,0.083110,0.145000,0.454528
17,169.0,0.452500,0.452500,0.547500,0.000000,1.000000,0.452500,0.623064,0.000000,0.547500,0.511945
18,185.9,0.315000,0.315000,0.685000,0.000799,0.940299,0.315000,0.471910,0.059701,0.685000,0.585905
19,197.0,0.377500,0.377500,0.622500,0.000300,0.980519,0.377500,0.545126,0.019481,0.622500,0.578146
20,212.9,0.365000,0.365000,0.635000,0.000000,1.000000,0.365000,0.534799,0.000000,0.635000,0.602061
21,217.0,0.355000,0.355000,0.645000,0.000100,0.993007,0.355000,0.523020,0.006993,0.645000,0.500596
22,239.2,0.952500,0.952500,0.047500,0.149515,0.178121,0.952500,0.300118,0.821879,0.047500,0.682705
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.405721
25,251.0,0.997500,0.997500,0.002500,0.000600,0.985185,0.997500,0.991304,0.014815,0.002500,0.000000
26,average,0.730673,0.730673,0.269327,0.009713,0.875669,0.730673,0.750996,0.124331,0.269327,0.475410

In [110]:
cv_result50

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.662500  0.736920    0.337500  0.662500    0.830176
1       2.0  0.674038  0.740051    0.325962  0.674038    0.820397
2       3.0  0.645192  0.697973    0.354808  0.645192    0.760158
3       4.0  0.672115  0.737139    0.327885  0.672115    0.816091
4       5.0  0.632692  0.716462    0.367308  0.632692    0.825799
5       6.0  0.690385  0.755767    0.309615  0.690385    0.834829
6       7.0  0.629808  0.700448    0.370192  0.629808    0.788936
7       8.0  0.680769  0.757310    0.319231  0.680769    0.853242
8       9.0  0.634615  0.715250    0.365385  0.634615    0.819359
9      10.0  0.667308  0.721805    0.332692  0.667308    0.785995
10       11  0.730673  0.796627    0.269327  0.730673    0.875669
11  average  0.658942  0.727912    0.341058  0.658942    0.813498
12      max  0.690385  0.755767    0.309615  0.690385    0.834829

### SAVE MODEL dTOP50fi

In [111]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier50.pkl', 'wb') as f:
    pickle.dump(knn50, f)

## TRAIN knn TOP 60fi

In [112]:
# train_data60['tp_ICD_cl0'] = le.transform(train_data60['tp_ICD_cl0'])

In [113]:
# Separate features and tp_ICD_cl0 variable for train_data50
X_train60 = train_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_train60 = train_data60['tp_ICD_cl0']

In [114]:
timer = CalculateTime(features=60, data_type='train')
timer.start()

knn60, data_top_5, Confusion_df60, eval_result60, cv_result60 = knn_custom_kfold_evaluation(X_train60, y_train60, le, feature=60, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.72 minutes

In [115]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
2,41.0,197.0,0.238095,147.0,0.190476,146.0,0.142857,104.1,0.095238,212.9,0.095238
3,129.0,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
4,169.0,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
5,161.0,161.0,0.238095,169.0,0.238095,41.0,0.190476,7.1,0.142857,98.9,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.333333,154.0,0.142857,98.9,0.095238,111.0,0.095238,217.0,0.095238
10398,169.0,161.0,0.428571,7.1,0.142857,41.0,0.095238,169.0,0.095238,98.9,0.047619
10399,249.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.285714,154.0,0.238095,151.0,0.142857,146.0,0.095238,104.1,0.047619

In [116]:
Confusion_df60

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,382,0,0,0,10,0,0,0,0,2,...,0,0,0,5,0,0,0,0,1,0
7.1,0,239,129,0,16,1,0,0,2,0,...,5,0,0,0,0,0,0,0,1,0
18.9,1,0,343,1,23,5,0,0,0,0,...,9,0,0,0,0,0,0,0,1,0
32.1,2,0,0,383,2,0,0,0,6,0,...,0,0,0,2,0,0,0,0,0,0
41.0,0,0,31,0,363,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
98.9,0,0,164,1,6,207,0,0,0,0,...,7,0,1,0,0,10,0,0,0,0
104.1,0,0,149,1,22,0,120,0,0,2,...,1,0,1,0,0,15,0,0,1,0
111.0,0,3,0,0,2,2,0,381,0,0,...,0,0,0,2,0,0,0,0,0,0
128.0,0,0,50,0,0,0,0,0,347,0,...,0,0,0,0,0,1,0,0,0,0
129.0,0,0,0,0,5,0,0,0,0,386,...,0,0,2,0,0,0,0,0,0,0
146.0,0,0,0,0,12,0,0,0,0,0,...,6,0,2,0,0,1,0,0,0,0
147.0,0,0,116,1,9,5,0,0,0,0,...,2,0,0,0,0,11,0,0,0,0
150.0,1,0,0,1,0,2,0,0,0,0,...,9,0,1,2,0,15,0,0,0,0
151.0,0,1,123,0,4,0,0,1,2,0,...,0,0,0,0,0,13,0,0,0,0
153.0,1,0,0,0,14,3,0,1,0,0,...,1,0,0,4,0,18,0,0,0,0
154.0,0,0,0,0,2,0,0,1,0,0,...,0,0,0,1,0,13,0,0,0,0
161.0,1,0,15,6,0,0,0,0,0,0,...,367,0,0,0,0,2,0,0,0,0
169.0,0,4,126,0,11,0,0,0,0,1,...,7,207,0,0,0,0,0,0,0,0
185.9,0,0,220,0,0,0,0,1,16,2,...,10,0,115,1,0,14,0,0,0,0
197.0,0,0,178,0,5,0,0,0,1,2,...,7,0,1,184,0,15,0,0,2,0
212.9,0,1,166,0,17,0,0,1,0,0,...,1,0,1,0,101,18,0,0,0,0
217.0,2,0,191,0,12,1,0,0,4,1,...,7,0,0,1,0,158,0,0,0,0
239.2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,32,365,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,384,0
251.0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [117]:
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.955000,0.955000,0.045000,0.000799,0.979487,0.955000,0.967089,0.020513,0.045000,0.608942
1,7.1,0.597500,0.597500,0.402500,0.000899,0.963710,0.597500,0.737654,0.036290,0.402500,0.773609
2,18.9,0.857500,0.857500,0.142500,0.142294,0.171329,0.857500,0.285595,0.828671,0.142500,0.613124
3,32.1,0.957500,0.957500,0.042500,0.001099,0.972081,0.957500,0.964736,0.027919,0.042500,0.554356
4,41.0,0.907500,0.907500,0.092500,0.016909,0.678505,0.907500,0.776471,0.321495,0.092500,0.792481
5,98.9,0.517500,0.517500,0.482500,0.002096,0.907895,0.517500,0.659236,0.092105,0.482500,0.478264
6,104.1,0.300000,0.300000,0.700000,0.000000,1.000000,0.300000,0.461538,0.000000,0.700000,0.895957
7,111.0,0.952500,0.952500,0.047500,0.000500,0.987047,0.952500,0.969466,0.012953,0.047500,0.580865
8,128.0,0.867500,0.867500,0.132500,0.003090,0.917989,0.867500,0.892031,0.082011,0.132500,0.792481
9,129.0,0.965000,0.965000,0.035000,0.000999,0.974747,0.965000,0.969849,0.025253,0.035000,0.498574
10,146.0,0.927500,0.927500,0.072500,0.034842,0.506831,0.927500,0.655477,0.493169,0.072500,0.610985
11,147.0,0.627500,0.627500,0.372500,0.006754,0.786834,0.627500,0.698192,0.213166,0.372500,0.528237
12,150.0,0.877500,0.877500,0.122500,0.000200,0.994334,0.877500,0.932271,0.005666,0.122500,0.353743
13,151.0,0.625000,0.625000,0.375000,0.000200,0.992063,0.625000,0.766871,0.007937,0.375000,0.443561
14,153.0,0.740000,0.740000,0.260000,0.004975,0.855491,0.740000,0.793566,0.144509,0.260000,0.442114
15,154.0,0.885000,0.885000,0.115000,0.000200,0.994382,0.885000,0.936508,0.005618,0.115000,0.442114
16,161.0,0.917500,0.917500,0.082500,0.007247,0.834091,0.917500,0.873810,0.165909,0.082500,0.792515
17,169.0,0.517500,0.517500,0.482500,0.000000,1.000000,0.517500,0.682043,0.000000,0.482500,0.557886
18,185.9,0.287500,0.287500,0.712500,0.000899,0.927419,0.287500,0.438931,0.072581,0.712500,0.618631
19,197.0,0.460000,0.460000,0.540000,0.001896,0.906404,0.460000,0.610282,0.093596,0.540000,0.443024
20,212.9,0.252500,0.252500,0.747500,0.000000,1.000000,0.252500,0.403194,0.000000,0.747500,0.664192
21,217.0,0.395000,0.395000,0.605000,0.017489,0.470238,0.395000,0.429348,0.529762,0.605000,0.550052
22,239.2,0.912500,0.912500,0.087500,0.000000,1.000000,0.912500,0.954248,0.000000,0.087500,0.350379
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.960000,0.960000,0.040000,0.000600,0.984615,0.960000,0.972152,0.015385,0.040000,0.442146
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.740769,0.740769,0.259231,0.009384,0.877134,0.740769,0.762666,0.122866,0.259231,0.531855

In [118]:
cv_result60

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.626923  0.708005    0.373077  0.626923    0.813177
1       2.0  0.665385  0.733504    0.334615  0.665385    0.817161
2       3.0  0.644231  0.710261    0.355769  0.644231    0.791372
3       4.0  0.682692  0.740444    0.317308  0.682692    0.808870
4       5.0  0.671154  0.743508    0.328846  0.671154    0.833349
5       6.0  0.675000  0.752462    0.325000  0.675000    0.850008
6       7.0  0.640385  0.715305    0.359615  0.640385    0.810078
7       8.0  0.711538  0.772655    0.288462  0.711538    0.845258
8       9.0  0.679808  0.743509    0.320192  0.679808    0.820383
9      10.0  0.661538  0.735034    0.338462  0.661538    0.826902
10       11  0.740769  0.803205    0.259231  0.740769    0.877134
11  average  0.665865  0.735469    0.334135  0.665865    0.821656
12      max  0.711538  0.772655    0.288462  0.711538    0.845258

### SAVE MODEL dTOP60fi

In [119]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier60.pkl', 'wb') as f:
    pickle.dump(knn60, f)

## TRAIN knn TOP 70fi

In [120]:
# train_data70['tp_ICD_cl0'] = le.transform(train_data70['tp_ICD_cl0'])

In [121]:
# Separate features and tp_ICD_cl0 variable for train_data70
X_train70 = train_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_train70 = train_data70['tp_ICD_cl0']

In [122]:
timer = CalculateTime(features=70, data_type='train')
timer.start()

knn70, data_top_5, Confusion_df70, eval_result70, cv_result70 = knn_custom_kfold_evaluation(X_train70, y_train70, le, feature=70, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.82 minutes

In [123]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.476190,248.0,0.238095,251.0,0.238095,104.1,0.047619,NaN,NaN
2,41.0,147.0,0.285714,146.0,0.142857,151.0,0.142857,212.9,0.142857,197.0,0.095238
3,129.0,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
4,169.0,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
5,161.0,7.1,0.190476,161.0,0.190476,41.0,0.142857,150.0,0.142857,169.0,0.142857
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.476190,248.0,0.238095,251.0,0.238095,104.1,0.047619,NaN,NaN
10397,153.0,153.0,0.190476,217.0,0.190476,111.0,0.142857,154.0,0.142857,150.0,0.095238
10398,169.0,161.0,0.285714,7.1,0.190476,169.0,0.190476,98.9,0.095238,41.0,0.047619
10399,249.0,249.0,0.476190,248.0,0.238095,251.0,0.238095,104.1,0.047619,NaN,NaN
10400,150.0,98.9,0.238095,154.0,0.142857,18.9,0.095238,147.0,0.095238,150.0,0.095238

In [124]:
Confusion_df70

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,374,0,0,0,2,5,0,0,0,0,...,1,0,0,15,0,0,0,0,1,0
7.1,2,344,10,0,2,3,1,0,2,4,...,0,0,0,28,0,0,0,0,1,0
18.9,0,0,374,2,9,2,0,0,0,0,...,3,0,0,5,0,0,0,0,1,0
32.1,2,0,0,386,1,0,0,0,6,0,...,0,0,0,5,0,0,0,0,0,0
41.0,0,5,1,0,355,3,0,0,0,0,...,1,0,1,32,0,0,0,0,0,0
98.9,4,0,0,1,0,341,0,0,0,21,...,0,0,0,23,0,0,0,0,0,0
104.1,0,15,4,1,11,7,327,0,0,19,...,1,0,0,0,0,0,0,0,0,0
111.0,0,14,0,0,8,13,0,352,3,0,...,2,0,0,0,0,0,0,0,0,0
128.0,1,1,0,0,0,0,0,0,347,0,...,0,0,0,50,0,0,0,0,0,0
129.0,1,17,7,0,5,0,0,0,0,354,...,0,0,0,0,0,0,0,0,0,0
146.0,2,0,12,0,8,9,0,0,0,11,...,4,0,0,0,0,0,0,0,0,0
147.0,1,0,6,1,10,0,0,0,0,4,...,2,0,0,117,0,0,0,0,0,0
150.0,4,15,7,1,17,1,0,0,25,0,...,2,0,0,222,0,0,0,0,0,0
151.0,1,14,4,0,0,7,0,0,2,4,...,0,0,0,123,0,0,0,0,0,0
153.0,0,16,0,0,2,2,0,0,0,12,...,1,0,0,190,0,0,0,0,0,0
154.0,2,0,0,1,1,5,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
161.0,3,2,0,6,1,1,0,0,0,22,...,349,0,0,16,0,0,0,0,0,0
169.0,0,21,5,0,3,0,0,0,0,10,...,0,194,1,155,0,0,0,0,0,0
185.9,2,14,4,0,3,5,0,0,16,0,...,4,0,125,219,0,0,0,0,0,0
197.0,2,15,1,0,2,3,1,0,2,0,...,0,0,0,362,0,0,0,0,2,0
212.9,3,19,2,0,10,0,1,0,0,12,...,3,0,0,161,184,0,0,0,0,0
217.0,1,0,8,0,4,16,3,0,5,8,...,1,0,0,262,0,90,0,0,0,0
239.2,0,0,13,0,0,3,0,0,0,1,...,0,0,0,303,0,0,77,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,1,0,0,14,0,0,0,0,384,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,399

In [125]:
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.935000,0.935000,0.065000,0.003090,0.923457,0.935000,0.929193,0.076543,0.065000,0.361145
1,7.1,0.860000,0.860000,0.140000,0.016522,0.671875,0.860000,0.754386,0.328125,0.140000,0.360851
2,18.9,0.935000,0.935000,0.065000,0.008330,0.816594,0.935000,0.871795,0.183406,0.065000,0.609552
3,32.1,0.965000,0.965000,0.035000,0.001298,0.967419,0.965000,0.966208,0.032581,0.035000,0.518151
4,41.0,0.887500,0.887500,0.112500,0.009803,0.781938,0.887500,0.831382,0.218062,0.112500,0.360849
5,98.9,0.852500,0.852500,0.147500,0.008428,0.800469,0.852500,0.825666,0.199531,0.147500,0.396781
6,104.1,0.817500,0.817500,0.182500,0.000700,0.979042,0.817500,0.891008,0.020958,0.182500,0.497304
7,111.0,0.880000,0.880000,0.120000,0.000000,1.000000,0.880000,0.936170,0.000000,0.120000,0.918025
8,128.0,0.867500,0.867500,0.132500,0.006063,0.850490,0.867500,0.858911,0.149510,0.132500,0.360849
9,129.0,0.885000,0.885000,0.115000,0.012638,0.734440,0.885000,0.802721,0.265560,0.115000,0.955078
10,146.0,0.850000,0.850000,0.150000,0.000700,0.979827,0.850000,0.910308,0.020173,0.150000,0.736016
11,147.0,0.632500,0.632500,0.367500,0.002693,0.903571,0.632500,0.744118,0.096429,0.367500,0.790010
12,150.0,0.257500,0.257500,0.742500,0.002593,0.798450,0.257500,0.389414,0.201550,0.742500,0.603830
13,151.0,0.610000,0.610000,0.390000,0.000200,0.991870,0.610000,0.755418,0.008130,0.390000,1.258914
14,153.0,0.432500,0.432500,0.567500,0.006359,0.729958,0.432500,0.543171,0.270042,0.567500,1.231633
15,154.0,0.372500,0.372500,0.627500,0.000300,0.980263,0.372500,0.539855,0.019737,0.627500,0.902718
16,161.0,0.872500,0.872500,0.127500,0.002593,0.930667,0.872500,0.900645,0.069333,0.127500,0.458131
17,169.0,0.485000,0.485000,0.515000,0.000000,1.000000,0.485000,0.653199,0.000000,0.515000,1.261558
18,185.9,0.312500,0.312500,0.687500,0.000200,0.984252,0.312500,0.474383,0.015748,0.687500,0.755189
19,197.0,0.905000,0.905000,0.095000,0.179117,0.142296,0.905000,0.245924,0.857704,0.095000,0.999331
20,212.9,0.460000,0.460000,0.540000,0.000000,1.000000,0.460000,0.630137,0.000000,0.540000,1.257521
21,217.0,0.225000,0.225000,0.775000,0.000000,1.000000,0.225000,0.367347,0.000000,0.775000,0.714198
22,239.2,0.192500,0.192500,0.807500,0.000000,1.000000,0.192500,0.322851,0.000000,0.807500,1.000024
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.960000,0.960000,0.040000,0.000500,0.987147,0.960000,0.973384,0.012853,0.040000,0.360886
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.709615,0.709615,0.290385,0.010082,0.882847,0.709615,0.735244,0.117153,0.290385,0.679559

In [126]:
cv_result70

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.631731  0.705214    0.368269  0.631731    0.798042
1       2.0  0.688462  0.753793    0.311538  0.688462    0.832823
2       3.0  0.640385  0.701765    0.359615  0.640385    0.776159
3       4.0  0.686538  0.763602    0.313462  0.686538    0.860153
4       5.0  0.664423  0.728182    0.335577  0.664423    0.805477
5       6.0  0.688462  0.758291    0.311538  0.688462    0.843885
6       7.0  0.693269  0.749362    0.306731  0.693269    0.815332
7       8.0  0.693269  0.769776    0.306731  0.693269    0.865264
8       9.0  0.678846  0.737569    0.321154  0.678846    0.807413
9      10.0  0.699038  0.768290    0.300962  0.699038    0.852770
10       11  0.709615  0.786809    0.290385  0.709615    0.882847
11  average  0.676442  0.743584    0.323558  0.676442    0.825732
12      max  0.699038  0.768290    0.300962  0.699038    0.852770

### SAVE MODEL dTOP70fi

In [127]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier70.pkl', 'wb') as f:
    pickle.dump(knn70, f)

## TRAIN knn TOP 80fi

In [128]:
# train_data80['tp_ICD_cl0'] = le.transform(train_data80['tp_ICD_cl0'])

In [129]:
# Separate features and tp_ICD_cl0 variable for train_data80
X_train80 = train_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_train80 = train_data80['tp_ICD_cl0']

In [130]:
timer = CalculateTime(features=80, data_type='train')
timer.start()

knn80, data_top_5, Confusion_df80, eval_result80, cv_result80 = knn_custom_kfold_evaluation(X_train80, y_train80, le, feature=80, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 0.94 minutes

In [131]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
2,41.0,104.1,0.20,197.0,0.20,151.0,0.15,146.0,0.10,212.9,0.10
3,129.0,18.9,0.10,129.0,0.10,150.0,0.10,154.0,0.10,197.0,0.10
4,169.0,18.9,0.10,129.0,0.10,150.0,0.10,154.0,0.10,197.0,0.10
5,161.0,7.1,0.30,161.0,0.25,169.0,0.20,18.9,0.10,146.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
10397,153.0,129.0,0.20,153.0,0.20,154.0,0.20,111.0,0.15,104.1,0.10
10398,169.0,161.0,0.25,150.0,0.20,41.0,0.15,18.9,0.10,169.0,0.10
10399,249.0,248.0,0.40,251.0,0.40,249.0,0.20,NaN,NaN,NaN,NaN
10400,150.0,18.9,0.15,98.9,0.15,147.0,0.15,150.0,0.15,151.0,0.15

In [132]:
Confusion_df80

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,356,0,21,7,2,0,5,7,0,0,...,1,0,0,0,0,0,0,1,0,0
7.1,2,335,0,10,13,0,0,4,2,0,...,2,0,0,28,0,0,0,1,0,0
18.9,0,0,371,2,0,0,0,12,0,0,...,7,0,0,5,0,0,0,1,0,0
32.1,4,0,0,380,1,0,2,2,6,0,...,0,0,0,5,0,0,0,0,0,0
41.0,2,0,35,0,359,0,0,1,0,1,...,0,0,0,2,0,0,0,0,0,0
98.9,0,0,0,6,0,344,0,0,1,5,...,8,0,0,23,0,0,0,0,0,0
104.1,1,0,168,5,0,0,190,17,11,0,...,1,0,0,0,0,0,0,1,0,0
111.0,2,0,206,4,7,1,2,132,3,0,...,5,0,0,33,0,0,0,0,0,0
128.0,0,0,48,0,0,0,0,0,352,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,17,0,5,1,0,0,0,368,...,2,0,0,0,0,0,0,0,0,0
146.0,0,0,135,0,6,0,0,11,17,2,...,4,0,0,0,0,0,0,0,0,0
147.0,0,0,115,1,8,0,0,0,1,0,...,2,0,0,0,0,0,0,0,0,0
150.0,1,0,15,1,17,1,2,0,25,5,...,0,0,0,32,0,0,0,0,0,0
151.0,1,1,123,4,30,0,0,0,2,0,...,9,0,0,0,0,0,0,0,0,0
153.0,1,0,188,0,1,0,0,14,0,0,...,1,0,0,0,0,0,0,0,0,0
154.0,2,0,0,12,2,0,2,16,0,0,...,0,0,0,25,0,0,0,0,0,0
161.0,2,0,17,6,0,0,1,0,0,3,...,365,0,0,1,0,0,0,0,0,0
169.0,0,1,143,3,1,0,4,9,0,6,...,0,190,1,31,0,0,0,0,0,0
185.9,2,0,224,3,3,0,1,15,15,1,...,1,0,116,16,0,0,0,0,0,0
197.0,2,1,17,8,3,0,2,0,2,0,...,0,0,0,359,0,0,0,2,0,0
212.9,1,1,1,7,0,2,0,2,32,5,...,7,0,0,0,331,0,0,0,0,0
217.0,1,0,210,6,3,0,6,9,0,2,...,3,0,0,1,0,147,0,0,0,0
239.2,0,0,331,0,0,1,0,1,0,0,...,0,0,0,0,0,0,67,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,399,0
251.0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [133]:
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.8900,0.8900,0.1100,0.002394,0.936842,0.8900,0.912821,0.063158,0.1100,0.792483
1,7.1,0.8375,0.8375,0.1625,0.000400,0.988201,0.8375,0.906631,0.011799,0.1625,0.360860
2,18.9,0.9275,0.9275,0.0725,0.167707,0.155490,0.9275,0.266332,0.844510,0.0725,0.500011
3,32.1,0.9500,0.9500,0.0500,0.008428,0.817204,0.9500,0.878613,0.182796,0.0500,0.678432
4,41.0,0.8975,0.8975,0.1025,0.010097,0.778742,0.8975,0.833914,0.221258,0.1025,0.792481
5,98.9,0.8600,0.8600,0.1400,0.000600,0.982857,0.8600,0.917333,0.017143,0.1400,0.360927
6,104.1,0.4750,0.4750,0.5250,0.002792,0.871560,0.4750,0.614887,0.128440,0.5250,0.631969
7,111.0,0.3300,0.3300,0.6700,0.011858,0.523810,0.3300,0.404908,0.476190,0.6700,0.455341
8,128.0,0.8800,0.8800,0.1200,0.011565,0.750533,0.8800,0.810127,0.249467,0.1200,0.792481
9,129.0,0.9200,0.9200,0.0800,0.002991,0.924623,0.9200,0.922306,0.075377,0.0800,0.792323
10,146.0,0.5400,0.5400,0.4600,0.001298,0.943231,0.5400,0.686804,0.056769,0.4600,0.604043
11,147.0,0.6675,0.6675,0.3325,0.005767,0.821538,0.6675,0.736552,0.178462,0.3325,0.743152
12,150.0,0.7300,0.7300,0.2700,0.000000,1.000000,0.7300,0.843931,0.000000,0.2700,0.362348
13,151.0,0.5725,0.5725,0.4275,0.000100,0.995652,0.5725,0.726984,0.004348,0.4275,0.773706
14,153.0,0.4825,0.4825,0.5175,0.004480,0.810924,0.4825,0.605016,0.189076,0.5175,0.631079
15,154.0,0.8275,0.8275,0.1725,0.000200,0.993994,0.8275,0.903138,0.006006,0.1725,0.361320
16,161.0,0.9125,0.9125,0.0875,0.005272,0.873206,0.9125,0.892421,0.126794,0.0875,0.792513
17,169.0,0.4750,0.4750,0.5250,0.000000,1.000000,0.4750,0.644068,0.000000,0.5250,0.455341
18,185.9,0.2900,0.2900,0.7100,0.000100,0.991453,0.2900,0.448743,0.008547,0.7100,0.589826
19,197.0,0.8975,0.8975,0.1025,0.019800,0.639929,0.8975,0.747138,0.360071,0.1025,0.792631
20,212.9,0.8275,0.8275,0.1725,0.000000,1.000000,0.8275,0.905609,0.000000,0.1725,0.477121
21,217.0,0.3675,0.3675,0.6325,0.000000,1.000000,0.3675,0.537477,0.000000,0.6325,0.652011
22,239.2,0.1675,0.1675,0.8325,0.000000,1.000000,0.1675,0.286938,0.000000,0.8325,0.000000
23,248.0,1.0000,1.0000,0.0000,0.000600,0.985222,1.0000,0.992556,0.014778,0.0000,0.000000
24,249.0,0.9975,0.9975,0.0025,0.000000,1.000000,0.9975,0.998748,0.000000,0.0025,0.000000
25,251.0,0.9975,0.9975,0.0025,0.000000,1.000000,0.9975,0.998748,0.000000,0.0025,0.000000
26,average,0.7200,0.7200,0.2800,0.009863,0.876347,0.7200,0.747028,0.123653,0.2800,0.515092

In [134]:
cv_result80

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.620192  0.683521    0.379808  0.620192    0.761253
1       2.0  0.691346  0.749346    0.308654  0.691346    0.817969
2       3.0  0.680769  0.727959    0.319231  0.680769    0.782178
3       4.0  0.675000  0.749266    0.325000  0.675000    0.841893
4       5.0  0.678846  0.741377    0.321154  0.678846    0.816596
5       6.0  0.684615  0.745876    0.315385  0.684615    0.819179
6       7.0  0.651923  0.720766    0.348077  0.651923    0.805864
7       8.0  0.642308  0.722935    0.357692  0.642308    0.826710
8       9.0  0.673077  0.739023    0.326923  0.673077    0.819295
9      10.0  0.698077  0.761957    0.301923  0.698077    0.838706
10       11  0.720000  0.790517    0.280000  0.720000    0.876347
11  average  0.669615  0.734203    0.330385  0.669615    0.812964
12      max  0.698077  0.761957    0.301923  0.698077    0.838706

### SAVE MODEL dTOP80fi

In [135]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier80.pkl', 'wb') as f:
    pickle.dump(knn80, f)

## TRAIN knn TOP 90fi

In [136]:
# train_data90['tp_ICD_cl0'] = le.transform(train_data90['tp_ICD_cl0'])

In [137]:
# Separate features and tp_ICD_cl0 variable for train_data90
X_train90 = train_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_train90 = train_data90['tp_ICD_cl0']

In [138]:
timer = CalculateTime(features=90, data_type='train')
timer.start()

knn90, data_top_5, Confusion_df90, eval_result90, cv_result90 = knn_custom_kfold_evaluation(X_train90, y_train90, le, feature=90, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.08 minutes

In [139]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
2,41.0,212.9,0.190476,146.0,0.142857,151.0,0.142857,197.0,0.142857,104.1,0.095238
3,129.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
4,169.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
5,161.0,41.0,0.285714,161.0,0.285714,169.0,0.190476,150.0,0.095238,7.1,0.047619
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.190476,153.0,0.190476,129.0,0.142857,98.9,0.095238,18.9,0.047619
10398,169.0,161.0,0.333333,41.0,0.238095,7.1,0.190476,169.0,0.095238,98.9,0.047619
10399,249.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.285714,146.0,0.142857,154.0,0.142857,185.9,0.095238,18.9,0.047619

In [140]:
Confusion_df90

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,371,0,0,0,1,0,15,0,0,0,...,3,0,5,0,0,1,0,0,1,0
7.1,4,331,0,0,1,1,29,0,2,13,...,2,0,0,0,5,0,0,0,1,0
18.9,2,0,381,0,0,0,5,0,0,0,...,3,0,1,0,0,0,0,0,1,0
32.1,0,0,0,391,0,0,5,0,0,2,...,0,0,0,0,2,0,0,0,0,0
41.0,0,0,0,0,356,0,2,30,0,5,...,0,0,4,0,1,1,0,0,0,0
98.9,6,0,0,1,4,322,23,1,30,10,...,2,0,0,0,0,0,0,0,0,0
104.1,6,0,0,0,5,0,338,0,11,32,...,1,0,6,0,0,0,0,0,1,0
111.0,0,3,0,0,11,1,0,346,3,11,...,5,1,13,0,2,0,0,0,0,0
128.0,1,0,0,0,0,0,0,47,352,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,1,0,7,0,0,0,0,379,...,0,0,6,0,0,0,0,0,0,0
146.0,3,0,0,0,17,0,100,112,18,25,...,6,0,0,0,0,1,0,0,0,0
147.0,0,0,0,1,10,0,0,115,1,15,...,1,0,0,0,1,0,0,0,0,0
150.0,5,0,0,0,0,0,0,190,0,0,...,8,0,6,1,2,0,0,0,0,0
151.0,1,1,0,0,0,8,0,123,2,4,...,1,0,6,0,0,0,0,0,0,0
153.0,0,0,0,0,1,0,0,189,0,28,...,2,0,3,0,5,0,0,0,0,0
154.0,0,0,0,0,1,2,25,246,0,15,...,0,0,3,0,1,0,0,0,0,0
161.0,4,6,0,0,0,0,1,19,0,1,...,369,0,0,0,0,0,0,0,0,0
169.0,6,4,1,0,0,0,31,125,0,10,...,0,210,6,0,4,0,0,0,0,0
185.9,4,0,1,6,2,1,16,221,1,0,...,3,0,138,1,0,0,0,0,0,0
197.0,4,0,0,1,2,3,0,0,2,14,...,0,0,0,361,0,0,0,0,2,0
212.9,7,1,1,0,8,0,2,167,0,27,...,2,1,0,0,171,1,0,0,0,0
217.0,3,0,0,0,6,1,2,193,4,30,...,0,0,0,0,0,149,0,0,0,0
239.2,2,0,0,0,0,6,0,0,0,33,...,0,0,0,0,0,0,359,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,399

In [141]:
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.927500,0.927500,0.072500,0.005767,0.864802,0.927500,0.895054,0.135198,0.072500,0.528283
1,7.1,0.827500,0.827500,0.172500,0.001498,0.956647,0.827500,0.887399,0.043353,0.172500,0.528322
2,18.9,0.952500,0.952500,0.047500,0.000400,0.989610,0.952500,0.970701,0.010390,0.047500,0.495275
3,32.1,0.977500,0.977500,0.022500,0.000899,0.977500,0.977500,0.977500,0.022500,0.022500,0.535931
4,41.0,0.890000,0.890000,0.110000,0.007543,0.824074,0.890000,0.855769,0.175926,0.110000,0.500000
5,98.9,0.805000,0.805000,0.195000,0.002295,0.933333,0.805000,0.864430,0.066667,0.195000,0.478288
6,104.1,0.845000,0.845000,0.155000,0.026290,0.555921,0.845000,0.670635,0.444079,0.155000,0.458157
7,111.0,0.865000,0.865000,0.135000,0.151031,0.162824,0.865000,0.274059,0.837176,0.135000,0.464778
8,128.0,0.880000,0.880000,0.120000,0.007346,0.826291,0.880000,0.852300,0.173709,0.120000,0.500000
9,129.0,0.947500,0.947500,0.052500,0.026764,0.579511,0.947500,0.719165,0.420489,0.052500,0.577371
10,146.0,0.295000,0.295000,0.705000,0.001099,0.914729,0.295000,0.446125,0.085271,0.705000,0.673258
11,147.0,0.640000,0.640000,0.360000,0.007641,0.768769,0.640000,0.698499,0.231231,0.360000,0.586557
12,150.0,0.447500,0.447500,0.552500,0.000000,1.000000,0.447500,0.618307,0.000000,0.552500,0.646123
13,151.0,0.620000,0.620000,0.380000,0.000200,0.992000,0.620000,0.763077,0.008000,0.380000,0.698579
14,153.0,0.430000,0.430000,0.570000,0.000500,0.971751,0.430000,0.596187,0.028249,0.570000,0.578130
15,154.0,0.265000,0.265000,0.735000,0.000000,1.000000,0.265000,0.418972,0.000000,0.735000,0.666671
16,161.0,0.922500,0.922500,0.077500,0.003885,0.904412,0.922500,0.913366,0.095588,0.077500,0.500110
17,169.0,0.525000,0.525000,0.475000,0.000200,0.990566,0.525000,0.686275,0.009434,0.475000,0.666667
18,185.9,0.345000,0.345000,0.655000,0.005865,0.700508,0.345000,0.462312,0.299492,0.655000,0.667360
19,197.0,0.902500,0.902500,0.097500,0.000200,0.994490,0.902500,0.946265,0.005510,0.097500,0.460656
20,212.9,0.427500,0.427500,0.572500,0.002295,0.881443,0.427500,0.575758,0.118557,0.572500,0.578132
21,217.0,0.372500,0.372500,0.627500,0.000400,0.973856,0.372500,0.538879,0.026144,0.627500,0.578130
22,239.2,0.897500,0.897500,0.102500,0.000000,1.000000,0.897500,0.945982,0.000000,0.102500,0.458157
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000600,0.984655,0.962500,0.973451,0.015345,0.037500,0.528352
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.729519,0.729519,0.270481,0.009720,0.874911,0.729519,0.751893,0.125089,0.270481,0.513588

In [142]:
cv_result90

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.655769  0.715207    0.344231  0.655769    0.786492
1       2.0  0.700962  0.762231    0.299038  0.700962    0.835238
2       3.0  0.688462  0.735910    0.311538  0.688462    0.790383
3       4.0  0.681731  0.758929    0.318269  0.681731    0.855844
4       5.0  0.658654  0.719878    0.341346  0.658654    0.793651
5       6.0  0.692308  0.748547    0.307692  0.692308    0.814730
6       7.0  0.651923  0.723176    0.348077  0.651923    0.811916
7       8.0  0.668269  0.736201    0.331731  0.668269    0.819507
8       9.0  0.665385  0.732784    0.334615  0.665385    0.815377
9      10.0  0.695192  0.750461    0.304808  0.695192    0.815276
10       11  0.729519  0.795628    0.270481  0.729519    0.874911
11  average  0.675865  0.738332    0.324135  0.675865    0.813841
12      max  0.700962  0.762231    0.299038  0.700962    0.835238

### SAVE MODEL dTOP90fi

In [143]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier90.pkl', 'wb') as f:
    pickle.dump(knn90, f)

## TRAIN knn TOP 100fi

In [144]:
# train_data100['tp_ICD_cl0'] = le.transform(train_data100['tp_ICD_cl0'])

In [145]:
# Separate features and tp_ICD_cl0 variable for train_data100
X_train100 = train_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_train100 = train_data100['tp_ICD_cl0']

In [146]:
timer = CalculateTime(features=100, data_type='train')
timer.start()

knn100, data_top_5, Confusion_df100, eval_result100, cv_result100 = knn_custom_kfold_evaluation(X_train100, y_train100, le, feature=100, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.20 minutes

In [147]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
2,41.0,212.9,0.190476,146.0,0.142857,151.0,0.142857,197.0,0.142857,104.1,0.095238
3,129.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
4,169.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
5,161.0,41.0,0.285714,161.0,0.285714,169.0,0.190476,150.0,0.095238,7.1,0.047619
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.190476,153.0,0.190476,129.0,0.142857,98.9,0.095238,18.9,0.047619
10398,169.0,161.0,0.333333,41.0,0.238095,7.1,0.190476,169.0,0.095238,98.9,0.047619
10399,249.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.285714,146.0,0.142857,154.0,0.142857,185.9,0.095238,18.9,0.047619

In [148]:
Confusion_df100

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,371,0,0,0,1,0,15,0,0,0,...,3,0,5,0,0,1,0,0,1,0
7.1,4,331,0,0,1,1,29,0,2,13,...,2,0,0,0,5,0,0,0,1,0
18.9,2,0,381,0,0,0,5,0,0,0,...,3,0,1,0,0,0,0,0,1,0
32.1,0,0,0,391,0,0,5,0,0,2,...,0,0,0,0,2,0,0,0,0,0
41.0,0,0,0,0,356,0,2,30,0,5,...,0,0,4,0,1,1,0,0,0,0
98.9,6,0,0,1,4,322,23,1,30,10,...,2,0,0,0,0,0,0,0,0,0
104.1,6,0,0,0,5,0,338,0,11,32,...,1,0,6,0,0,0,0,0,1,0
111.0,0,3,0,0,11,1,0,346,3,11,...,5,1,13,0,2,0,0,0,0,0
128.0,1,0,0,0,0,0,0,47,352,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,1,0,7,0,0,0,0,379,...,0,0,6,0,0,0,0,0,0,0
146.0,3,0,0,0,17,0,100,112,18,25,...,6,0,0,0,0,1,0,0,0,0
147.0,0,0,0,1,10,0,0,115,1,15,...,1,0,0,0,1,0,0,0,0,0
150.0,5,0,0,0,0,0,0,190,0,0,...,8,0,6,1,2,0,0,0,0,0
151.0,1,1,0,0,0,8,0,123,2,4,...,1,0,6,0,0,0,0,0,0,0
153.0,0,0,0,0,1,0,0,189,0,28,...,2,0,3,0,5,0,0,0,0,0
154.0,0,0,0,0,1,2,25,246,0,15,...,0,0,3,0,1,0,0,0,0,0
161.0,4,6,0,0,0,0,1,19,0,1,...,369,0,0,0,0,0,0,0,0,0
169.0,6,4,1,0,0,0,31,125,0,10,...,0,210,6,0,4,0,0,0,0,0
185.9,4,0,1,6,2,1,16,221,1,0,...,3,0,138,1,0,0,0,0,0,0
197.0,4,0,0,1,2,3,0,0,2,14,...,0,0,0,361,0,0,0,0,2,0
212.9,7,1,1,0,8,0,2,167,0,27,...,2,1,0,0,171,1,0,0,0,0
217.0,3,0,0,0,6,1,2,193,4,30,...,0,0,0,0,0,149,0,0,0,0
239.2,2,0,0,0,0,6,0,0,0,33,...,0,0,0,0,0,0,359,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,399

In [149]:
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.927500,0.927500,0.072500,0.005767,0.864802,0.927500,0.895054,0.135198,0.072500,0.528283
1,7.1,0.827500,0.827500,0.172500,0.001498,0.956647,0.827500,0.887399,0.043353,0.172500,0.528322
2,18.9,0.952500,0.952500,0.047500,0.000400,0.989610,0.952500,0.970701,0.010390,0.047500,0.495275
3,32.1,0.977500,0.977500,0.022500,0.000899,0.977500,0.977500,0.977500,0.022500,0.022500,0.535931
4,41.0,0.890000,0.890000,0.110000,0.007543,0.824074,0.890000,0.855769,0.175926,0.110000,0.500000
5,98.9,0.805000,0.805000,0.195000,0.002295,0.933333,0.805000,0.864430,0.066667,0.195000,0.478288
6,104.1,0.845000,0.845000,0.155000,0.026290,0.555921,0.845000,0.670635,0.444079,0.155000,0.458157
7,111.0,0.865000,0.865000,0.135000,0.151031,0.162824,0.865000,0.274059,0.837176,0.135000,0.464778
8,128.0,0.880000,0.880000,0.120000,0.007346,0.826291,0.880000,0.852300,0.173709,0.120000,0.500000
9,129.0,0.947500,0.947500,0.052500,0.026764,0.579511,0.947500,0.719165,0.420489,0.052500,0.577371
10,146.0,0.295000,0.295000,0.705000,0.001099,0.914729,0.295000,0.446125,0.085271,0.705000,0.673258
11,147.0,0.640000,0.640000,0.360000,0.007641,0.768769,0.640000,0.698499,0.231231,0.360000,0.586557
12,150.0,0.447500,0.447500,0.552500,0.000000,1.000000,0.447500,0.618307,0.000000,0.552500,0.646123
13,151.0,0.620000,0.620000,0.380000,0.000200,0.992000,0.620000,0.763077,0.008000,0.380000,0.698579
14,153.0,0.430000,0.430000,0.570000,0.000500,0.971751,0.430000,0.596187,0.028249,0.570000,0.578130
15,154.0,0.265000,0.265000,0.735000,0.000000,1.000000,0.265000,0.418972,0.000000,0.735000,0.666671
16,161.0,0.922500,0.922500,0.077500,0.003885,0.904412,0.922500,0.913366,0.095588,0.077500,0.500110
17,169.0,0.525000,0.525000,0.475000,0.000200,0.990566,0.525000,0.686275,0.009434,0.475000,0.666667
18,185.9,0.345000,0.345000,0.655000,0.005865,0.700508,0.345000,0.462312,0.299492,0.655000,0.667360
19,197.0,0.902500,0.902500,0.097500,0.000200,0.994490,0.902500,0.946265,0.005510,0.097500,0.460656
20,212.9,0.427500,0.427500,0.572500,0.002295,0.881443,0.427500,0.575758,0.118557,0.572500,0.578132
21,217.0,0.372500,0.372500,0.627500,0.000400,0.973856,0.372500,0.538879,0.026144,0.627500,0.578130
22,239.2,0.897500,0.897500,0.102500,0.000000,1.000000,0.897500,0.945982,0.000000,0.102500,0.458157
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000600,0.984655,0.962500,0.973451,0.015345,0.037500,0.528352
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.729519,0.729519,0.270481,0.009720,0.874911,0.729519,0.751893,0.125089,0.270481,0.513588

In [150]:
cv_result100

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.655769  0.715207    0.344231  0.655769    0.786492
1       2.0  0.700962  0.762231    0.299038  0.700962    0.835238
2       3.0  0.688462  0.735910    0.311538  0.688462    0.790383
3       4.0  0.681731  0.758929    0.318269  0.681731    0.855844
4       5.0  0.658654  0.719878    0.341346  0.658654    0.793651
5       6.0  0.692308  0.748547    0.307692  0.692308    0.814730
6       7.0  0.651923  0.723176    0.348077  0.651923    0.811916
7       8.0  0.668269  0.736201    0.331731  0.668269    0.819507
8       9.0  0.665385  0.732784    0.334615  0.665385    0.815377
9      10.0  0.695192  0.750461    0.304808  0.695192    0.815276
10       11  0.729519  0.795628    0.270481  0.729519    0.874911
11  average  0.675865  0.738332    0.324135  0.675865    0.813841
12      max  0.700962  0.762231    0.299038  0.700962    0.835238

### SAVE MODEL dTOP100fi

In [151]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier100.pkl', 'wb') as f:
    pickle.dump(knn100, f)

## TRAIN knn TOP 110fi

In [152]:
# train_data110['tp_ICD_cl0'] = le.transform(train_data110['tp_ICD_cl0'])

In [153]:
# Separate features and tp_ICD_cl0 variable for train_data110
X_train110 = train_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_train110 = train_data110['tp_ICD_cl0']

In [154]:
timer = CalculateTime(features=110, data_type='train')
timer.start()

knn110, data_top_5, Confusion_df110, eval_result110, cv_result110 = knn_custom_kfold_evaluation(X_train110, y_train110, le, feature=110, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.31 minutes

In [155]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
2,41.0,147.0,0.190476,7.1,0.095238,104.1,0.095238,146.0,0.095238,151.0,0.095238
3,129.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
4,169.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
5,161.0,41.0,0.333333,161.0,0.238095,7.1,0.142857,169.0,0.142857,98.9,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.238095,129.0,0.142857,146.0,0.095238,150.0,0.095238,153.0,0.095238
10398,169.0,161.0,0.333333,41.0,0.238095,7.1,0.142857,169.0,0.095238,104.1,0.047619
10399,249.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.142857,147.0,0.142857,151.0,0.142857,104.1,0.095238,146.0,0.095238

In [156]:
Confusion_df110

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,354,0,0,0,2,7,7,6,0,0,...,1,0,0,0,0,0,0,1,0,0
7.1,0,327,0,0,14,11,5,0,2,0,...,0,0,0,0,9,0,0,1,0,0
18.9,1,0,371,0,8,9,0,1,0,0,...,3,0,1,0,0,0,0,1,0,0
32.1,0,0,0,374,0,11,2,0,6,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,14,0,0,344,1,0,1,0,0,...,1,0,0,0,6,0,2,0,0,0
98.9,1,0,0,0,1,340,0,12,0,1,...,4,0,0,0,10,0,3,0,0,0
104.1,1,0,0,0,14,5,213,6,11,0,...,1,0,0,0,0,0,0,1,0,0
111.0,4,3,0,0,12,5,0,169,0,0,...,2,0,0,0,11,0,0,0,0,0
128.0,6,0,0,0,0,2,0,0,343,1,...,0,0,0,0,1,0,0,0,0,0
129.0,1,0,0,0,5,0,0,4,0,114,...,1,0,0,0,0,0,0,0,0,0
146.0,1,0,0,0,11,0,10,9,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,1,0,1,0,2,4,0,1,1,0,...,0,0,0,0,11,0,0,0,0,0
150.0,1,0,0,0,1,0,0,0,0,0,...,6,0,0,0,15,0,0,0,0,0
151.0,1,1,0,0,0,0,4,0,2,0,...,0,0,1,0,13,0,0,0,0,0
153.0,0,0,0,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
154.0,0,0,0,0,1,0,15,0,0,5,...,0,0,0,0,13,0,0,0,0,0
161.0,3,7,0,1,1,1,0,8,0,0,...,362,0,0,0,1,0,0,0,0,0
169.0,4,5,1,0,1,3,11,12,0,1,...,1,179,2,0,20,0,0,0,0,0
185.9,2,0,0,0,6,4,13,2,1,1,...,3,0,335,0,14,0,0,0,0,0
197.0,3,0,1,0,2,2,13,3,1,0,...,1,0,0,195,14,0,0,2,0,0
212.9,2,1,3,0,19,0,10,3,0,1,...,2,0,0,1,190,0,0,0,0,0
217.0,0,0,0,0,5,7,9,5,5,0,...,2,0,0,0,0,170,0,0,0,0
239.2,1,0,0,0,0,17,0,0,0,0,...,0,0,0,0,0,0,380,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [157]:
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.885000,0.885000,0.115000,0.003289,0.914729,0.885000,0.899619,0.085271,0.115000,0.430860
1,7.1,0.817500,0.817500,0.182500,0.003090,0.913408,0.817500,0.862797,0.086592,0.182500,0.428336
2,18.9,0.927500,0.927500,0.072500,0.000600,0.984085,0.927500,0.954955,0.015915,0.072500,0.626220
3,32.1,0.935000,0.935000,0.065000,0.000100,0.997333,0.935000,0.965161,0.002667,0.065000,0.566452
4,41.0,0.860000,0.860000,0.140000,0.010489,0.764444,0.860000,0.809412,0.235556,0.140000,0.416331
5,98.9,0.850000,0.850000,0.150000,0.008821,0.792541,0.850000,0.820265,0.207459,0.150000,0.428404
6,104.1,0.532500,0.532500,0.467500,0.009901,0.680511,0.532500,0.597475,0.319489,0.467500,0.767010
7,111.0,0.422500,0.422500,0.577500,0.007444,0.692623,0.422500,0.524845,0.307377,0.577500,0.703457
8,128.0,0.857500,0.857500,0.142500,0.002892,0.922043,0.857500,0.888601,0.077957,0.142500,0.416290
9,129.0,0.285000,0.285000,0.715000,0.000999,0.919355,0.285000,0.435115,0.080645,0.715000,0.826323
10,146.0,0.637500,0.637500,0.362500,0.000100,0.996094,0.637500,0.777439,0.003906,0.362500,0.779580
11,147.0,0.660000,0.660000,0.340000,0.019223,0.573913,0.660000,0.613953,0.426087,0.340000,0.453159
12,150.0,0.847500,0.847500,0.152500,0.144787,0.166831,0.847500,0.278783,0.833169,0.152500,0.428317
13,151.0,0.632500,0.632500,0.367500,0.000000,1.000000,0.632500,0.774885,0.000000,0.367500,0.449552
14,153.0,0.982500,0.982500,0.017500,0.003488,0.918224,0.982500,0.949275,0.081776,0.017500,0.494180
15,154.0,0.905000,0.905000,0.095000,0.000300,0.991781,0.905000,0.946405,0.008219,0.095000,0.515239
16,161.0,0.905000,0.905000,0.095000,0.002792,0.928205,0.905000,0.916456,0.071795,0.095000,0.420690
17,169.0,0.447500,0.447500,0.552500,0.000000,1.000000,0.447500,0.618307,0.000000,0.552500,0.540476
18,185.9,0.837500,0.837500,0.162500,0.000400,0.988201,0.837500,0.906631,0.011799,0.162500,0.454810
19,197.0,0.487500,0.487500,0.512500,0.000100,0.994898,0.487500,0.654362,0.005102,0.512500,0.547229
20,212.9,0.475000,0.475000,0.525000,0.013612,0.579268,0.475000,0.521978,0.420732,0.525000,0.773716
21,217.0,0.425000,0.425000,0.575000,0.000000,1.000000,0.425000,0.596491,0.000000,0.575000,0.724285
22,239.2,0.950000,0.950000,0.050000,0.000500,0.987013,0.950000,0.968153,0.012987,0.050000,0.564587
23,248.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000000,1.000000,0.962500,0.980892,0.000000,0.037500,0.428350
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.750962,0.750962,0.249038,0.008982,0.872720,0.750962,0.778983,0.127280,0.249038,0.507071

In [158]:
cv_result110

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.655769  0.717783    0.344231  0.655769    0.792750
1       2.0  0.700000  0.758288    0.300000  0.700000    0.827166
2       3.0  0.647115  0.703396    0.352885  0.647115    0.770400
3       4.0  0.682692  0.754979    0.317308  0.682692    0.844387
4       5.0  0.666346  0.726289    0.333654  0.666346    0.798082
5       6.0  0.726923  0.779169    0.273077  0.726923    0.839506
6       7.0  0.663462  0.731463    0.336538  0.663462    0.814995
7       8.0  0.663462  0.740461    0.336538  0.663462    0.837679
8       9.0  0.660577  0.718707    0.339423  0.660577    0.788055
9      10.0  0.685577  0.740781    0.314423  0.685577    0.805655
10       11  0.750962  0.807276    0.249038  0.750962    0.872720
11  average  0.675192  0.737132    0.324808  0.675192    0.811867
12      max  0.726923  0.779169    0.273077  0.726923    0.839506

### SAVE MODEL dTOP110fi

In [159]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier110.pkl', 'wb') as f:
    pickle.dump(knn110, f)

## TRAIN knn TOP 120fi

In [160]:
# train_data120['tp_ICD_cl0'] = le.transform(train_data120['tp_ICD_cl0'])

In [161]:
# Separate features and tp_ICD_cl0 variable for train_data120
X_train120 = train_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_train120 = train_data120['tp_ICD_cl0']

In [162]:
timer = CalculateTime(features=120, data_type='train')
timer.start()

knn120, data_top_5, Confusion_df120, eval_result120, cv_result120 = knn_custom_kfold_evaluation(X_train120, y_train120, le, feature=120, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.40 minutes

In [163]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
2,41.0,147.0,0.190476,7.1,0.095238,104.1,0.095238,146.0,0.095238,151.0,0.095238
3,129.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
4,169.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
5,161.0,41.0,0.333333,161.0,0.238095,7.1,0.142857,169.0,0.142857,98.9,0.095238
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.238095,129.0,0.142857,146.0,0.095238,150.0,0.095238,153.0,0.095238
10398,169.0,161.0,0.333333,41.0,0.238095,7.1,0.142857,169.0,0.095238,104.1,0.047619
10399,249.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.142857,147.0,0.142857,151.0,0.142857,104.1,0.095238,146.0,0.095238

In [164]:
Confusion_df120

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,354,0,0,0,2,7,7,6,0,0,...,1,0,0,0,0,0,0,1,0,0
7.1,1,326,0,0,14,11,5,0,2,0,...,0,0,0,0,9,0,0,1,0,0
18.9,1,0,371,0,8,9,0,1,0,0,...,3,0,1,0,0,0,0,1,0,0
32.1,0,0,0,374,0,11,2,0,6,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,14,0,0,344,1,0,1,0,0,...,1,0,0,0,6,0,2,0,0,0
98.9,1,0,0,0,1,340,0,12,0,1,...,4,0,0,0,10,0,3,0,0,0
104.1,1,0,0,0,14,5,213,6,11,0,...,1,0,0,0,0,0,0,1,0,0
111.0,4,3,0,0,12,5,0,168,0,0,...,2,0,0,0,11,0,0,0,0,0
128.0,6,0,0,0,0,2,0,0,343,1,...,0,0,0,0,1,0,0,0,0,0
129.0,1,0,0,0,5,0,0,4,0,114,...,1,0,0,0,0,0,0,0,0,0
146.0,1,0,0,0,11,0,10,9,0,0,...,0,0,0,0,0,0,0,0,0,0
147.0,2,0,1,0,2,4,0,1,1,0,...,0,0,0,0,11,0,0,0,0,0
150.0,1,0,0,0,1,0,0,0,0,0,...,6,0,0,0,15,0,0,0,0,0
151.0,0,1,0,0,0,0,4,0,2,0,...,0,0,1,0,13,0,0,0,0,0
153.0,0,0,0,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
154.0,0,0,0,0,1,0,15,0,0,5,...,0,0,0,0,13,0,0,0,0,0
161.0,0,7,0,1,1,1,0,8,0,0,...,365,0,0,0,1,0,0,0,0,0
169.0,3,5,1,0,1,3,11,12,0,1,...,1,180,2,0,20,0,0,0,0,0
185.9,2,0,0,0,6,4,13,2,1,1,...,3,0,335,0,14,0,0,0,0,0
197.0,3,0,1,0,2,2,13,3,1,0,...,1,0,0,195,14,0,0,2,0,0
212.9,2,1,3,0,18,0,10,3,0,1,...,3,0,0,1,191,0,0,0,0,0
217.0,1,0,0,0,5,7,9,5,5,0,...,2,0,0,0,0,169,0,0,0,0
239.2,1,0,0,0,0,17,0,0,0,0,...,0,0,0,0,0,0,380,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [165]:
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.885000,0.885000,0.115000,0.003090,0.919481,0.885000,0.901911,0.080519,0.115000,0.430860
1,7.1,0.815000,0.815000,0.185000,0.003090,0.913165,0.815000,0.861295,0.086835,0.185000,0.428336
2,18.9,0.927500,0.927500,0.072500,0.000600,0.984085,0.927500,0.954955,0.015915,0.072500,0.626220
3,32.1,0.935000,0.935000,0.065000,0.000100,0.997333,0.935000,0.965161,0.002667,0.065000,0.566452
4,41.0,0.860000,0.860000,0.140000,0.010391,0.766147,0.860000,0.810365,0.233853,0.140000,0.416331
5,98.9,0.850000,0.850000,0.150000,0.008821,0.792541,0.850000,0.820265,0.207459,0.150000,0.428404
6,104.1,0.532500,0.532500,0.467500,0.009901,0.680511,0.532500,0.597475,0.319489,0.467500,0.767010
7,111.0,0.420000,0.420000,0.580000,0.007444,0.691358,0.420000,0.522551,0.308642,0.580000,0.703483
8,128.0,0.857500,0.857500,0.142500,0.002892,0.922043,0.857500,0.888601,0.077957,0.142500,0.416290
9,129.0,0.285000,0.285000,0.715000,0.000999,0.919355,0.285000,0.435115,0.080645,0.715000,0.826323
10,146.0,0.637500,0.637500,0.362500,0.000300,0.988372,0.637500,0.775076,0.011628,0.362500,0.779580
11,147.0,0.657500,0.657500,0.342500,0.019223,0.572985,0.657500,0.612340,0.427015,0.342500,0.454785
12,150.0,0.847500,0.847500,0.152500,0.144714,0.166913,0.847500,0.278898,0.833087,0.152500,0.428317
13,151.0,0.635000,0.635000,0.365000,0.000000,1.000000,0.635000,0.776758,0.000000,0.365000,0.449339
14,153.0,0.982500,0.982500,0.017500,0.003388,0.920375,0.982500,0.950423,0.079625,0.017500,0.494180
15,154.0,0.905000,0.905000,0.095000,0.000300,0.991781,0.905000,0.946405,0.008219,0.095000,0.515241
16,161.0,0.912500,0.912500,0.087500,0.002892,0.926396,0.912500,0.919395,0.073604,0.087500,0.420407
17,169.0,0.450000,0.450000,0.550000,0.000000,1.000000,0.450000,0.620690,0.000000,0.550000,0.540476
18,185.9,0.837500,0.837500,0.162500,0.000400,0.988201,0.837500,0.906631,0.011799,0.162500,0.454810
19,197.0,0.487500,0.487500,0.512500,0.000100,0.994898,0.487500,0.654362,0.005102,0.512500,0.547229
20,212.9,0.477500,0.477500,0.522500,0.013612,0.580547,0.477500,0.524005,0.419453,0.522500,0.773737
21,217.0,0.422500,0.422500,0.577500,0.000000,1.000000,0.422500,0.594025,0.000000,0.577500,0.726541
22,239.2,0.950000,0.950000,0.050000,0.000500,0.987013,0.950000,0.968153,0.012987,0.050000,0.564587
23,248.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000000,1.000000,0.962500,0.980892,0.000000,0.037500,0.428350
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.751154,0.751154,0.248846,0.008975,0.872643,0.751154,0.779117,0.127357,0.248846,0.507203

In [166]:
cv_result120

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.655769  0.717279    0.344231  0.655769    0.791521
1       2.0  0.699038  0.756949    0.300962  0.699038    0.825322
2       3.0  0.646154  0.702539    0.353846  0.646154    0.769705
3       4.0  0.682692  0.754963    0.317308  0.682692    0.844347
4       5.0  0.664423  0.724228    0.335577  0.664423    0.795863
5       6.0  0.725962  0.777774    0.274038  0.725962    0.837550
6       7.0  0.664423  0.732633    0.335577  0.664423    0.816451
7       8.0  0.663462  0.740456    0.336538  0.663462    0.837666
8       9.0  0.659615  0.718075    0.340385  0.659615    0.787905
9      10.0  0.687500  0.742799    0.312500  0.687500    0.807771
10       11  0.751154  0.807354    0.248846  0.751154    0.872643
11  average  0.674904  0.736769    0.325096  0.674904    0.811410
12      max  0.725962  0.777774    0.274038  0.725962    0.837550

### SAVE MODEL dTOP120fi

In [167]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier120.pkl', 'wb') as f:
    pickle.dump(knn120, f)

## TRAIN knn TOP 130fi

In [168]:
# train_data130['tp_ICD_cl0'] = le.transform(train_data130['tp_ICD_cl0'])

In [169]:
# Separate features and tp_ICD_cl0 variable for train_data130
X_train130 = train_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_train130 = train_data130['tp_ICD_cl0']

In [170]:
timer = CalculateTime(features=130, data_type='train')
timer.start()

knn130, data_top_5, Confusion_df130, eval_result130, cv_result130 = knn_custom_kfold_evaluation(X_train130, y_train130, le, feature=130, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.50 minutes

In [171]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
2,41.0,197.0,0.333333,104.1,0.142857,146.0,0.142857,151.0,0.142857,32.1,0.047619
3,129.0,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
4,169.0,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
5,161.0,161.0,0.333333,7.1,0.238095,41.0,0.238095,169.0,0.142857,111.0,0.047619
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10397,153.0,111.0,0.190476,153.0,0.190476,129.0,0.095238,212.9,0.095238,41.0,0.047619
10398,169.0,161.0,0.428571,7.1,0.142857,41.0,0.142857,169.0,0.095238,104.1,0.047619
10399,249.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.285714,154.0,0.142857,104.1,0.095238,146.0,0.095238,150.0,0.095238

In [172]:
Confusion_df130

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,355,0,0,7,1,0,0,1,0,0,...,2,0,5,5,0,0,0,1,0,0
7.1,0,327,9,10,13,1,0,0,2,0,...,0,0,3,5,0,0,0,1,0,0
18.9,1,0,372,0,8,4,0,2,0,0,...,4,0,1,2,0,0,0,1,0,0
32.1,0,0,7,382,0,0,0,0,6,0,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,6,1,344,1,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
98.9,2,1,10,0,1,341,0,5,0,0,...,4,0,0,5,0,0,0,0,0,0
104.1,1,0,0,4,13,0,195,4,13,0,...,4,0,0,0,0,0,0,1,0,0
111.0,2,3,16,0,7,1,0,149,0,0,...,1,0,0,2,0,0,0,0,0,0
128.0,1,0,1,2,0,0,0,0,349,0,...,0,0,0,0,0,0,0,0,0,0
129.0,1,0,0,0,5,0,0,0,0,388,...,0,0,5,0,0,1,0,0,0,0
146.0,1,0,0,0,0,0,0,0,0,1,...,0,0,7,0,0,0,0,0,0,0
147.0,1,0,17,0,1,0,0,0,1,0,...,2,0,0,0,0,0,0,0,0,0
150.0,3,0,3,7,0,0,0,1,0,0,...,9,0,6,0,0,0,0,0,0,0
151.0,1,0,14,0,0,0,0,0,2,0,...,2,0,6,0,0,0,0,0,0,0
153.0,1,0,16,0,1,0,0,1,0,0,...,0,0,2,4,0,0,0,0,0,0
154.0,1,0,8,11,1,1,0,0,0,0,...,0,0,3,1,0,0,0,0,0,0
161.0,0,0,1,1,0,0,0,0,0,0,...,377,0,5,0,0,0,0,0,0,0
169.0,10,1,5,3,0,0,0,0,0,0,...,0,208,3,3,0,1,0,0,0,0
185.9,2,0,17,3,3,1,0,1,16,0,...,2,1,321,0,0,0,0,0,0,0
197.0,3,0,17,0,2,0,0,3,2,0,...,0,1,0,108,0,0,0,2,0,0
212.9,1,0,19,7,10,1,0,6,0,0,...,3,0,5,1,167,0,0,0,0,0
217.0,1,0,0,6,3,1,0,5,5,0,...,0,0,0,0,0,177,0,0,0,0
239.2,1,0,35,13,0,3,0,0,0,0,...,0,0,0,0,0,0,49,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [173]:
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.887500,0.887500,0.112500,0.003388,0.912596,0.887500,0.899873,0.087404,0.112500,0.429194
1,7.1,0.817500,0.817500,0.182500,0.000500,0.984940,0.817500,0.893443,0.015060,0.182500,0.428328
2,18.9,0.930000,0.930000,0.070000,0.019704,0.649215,0.930000,0.764645,0.350785,0.070000,0.621858
3,32.1,0.955000,0.955000,0.045000,0.007444,0.835886,0.955000,0.891482,0.164114,0.045000,0.729249
4,41.0,0.860000,0.860000,0.140000,0.006853,0.832930,0.860000,0.846248,0.167070,0.140000,0.416306
5,98.9,0.852500,0.852500,0.147500,0.001398,0.960563,0.852500,0.903311,0.039437,0.147500,0.428377
6,104.1,0.487500,0.487500,0.512500,0.000000,1.000000,0.487500,0.655462,0.000000,0.512500,0.558134
7,111.0,0.372500,0.372500,0.627500,0.002892,0.837079,0.372500,0.515571,0.162921,0.627500,0.517353
8,128.0,0.872500,0.872500,0.127500,0.004678,0.881313,0.872500,0.876884,0.118687,0.127500,0.416290
9,129.0,0.970000,0.970000,0.030000,0.000100,0.997429,0.970000,0.983523,0.002571,0.030000,0.576240
10,146.0,0.692500,0.692500,0.307500,0.000799,0.971930,0.692500,0.808759,0.028070,0.307500,0.484213
11,147.0,0.647500,0.647500,0.352500,0.027143,0.481413,0.647500,0.552239,0.518587,0.352500,0.999979
12,150.0,0.827500,0.827500,0.172500,0.147921,0.160135,0.827500,0.268342,0.839865,0.172500,0.428317
13,151.0,0.622500,0.622500,0.377500,0.000400,0.984190,0.622500,0.762634,0.015810,0.377500,0.998388
14,153.0,0.937500,0.937500,0.062500,0.011662,0.760649,0.937500,0.839866,0.239351,0.062500,0.792446
15,154.0,0.927500,0.927500,0.072500,0.000100,0.997312,0.927500,0.961140,0.002688,0.072500,0.711895
16,161.0,0.942500,0.942500,0.057500,0.003289,0.919512,0.942500,0.930864,0.080488,0.057500,0.416367
17,169.0,0.520000,0.520000,0.480000,0.000200,0.990476,0.520000,0.681967,0.009524,0.480000,0.540476
18,185.9,0.802500,0.802500,0.197500,0.005074,0.862903,0.802500,0.831606,0.137097,0.197500,0.715166
19,197.0,0.270000,0.270000,0.730000,0.002892,0.788321,0.270000,0.402235,0.211679,0.730000,1.161037
20,212.9,0.417500,0.417500,0.582500,0.000000,1.000000,0.417500,0.589065,0.000000,0.582500,0.998624
21,217.0,0.442500,0.442500,0.557500,0.000300,0.983333,0.442500,0.610345,0.016667,0.557500,0.711041
22,239.2,0.122500,0.122500,0.877500,0.000000,1.000000,0.122500,0.218263,0.000000,0.877500,0.345719
23,248.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000000,1.000000,0.962500,0.980892,0.000000,0.037500,0.428328
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.736058,0.736058,0.263942,0.009513,0.876052,0.736058,0.756152,0.123948,0.263942,0.571282

In [174]:
cv_result130

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.651923  0.715439    0.348077  0.651923    0.792669
1       2.0  0.677885  0.738304    0.322115  0.677885    0.810548
2       3.0  0.670192  0.715986    0.329808  0.670192    0.768497
3       4.0  0.655769  0.725491    0.344231  0.655769    0.811802
4       5.0  0.655769  0.711837    0.344231  0.655769    0.778388
5       6.0  0.689423  0.748749    0.310577  0.689423    0.819246
6       7.0  0.645192  0.717124    0.354808  0.645192    0.807107
7       8.0  0.689423  0.756334    0.310577  0.689423    0.837629
8       9.0  0.657692  0.726227    0.342308  0.657692    0.810707
9      10.0  0.680769  0.745469    0.319231  0.680769    0.823759
10       11  0.736058  0.799976    0.263942  0.736058    0.876052
11  average  0.667404  0.730096    0.332596  0.667404    0.806035
12      max  0.689423  0.748749    0.310577  0.689423    0.819246

### SAVE MODEL dTOP130fi

In [175]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier130.pkl', 'wb') as f:
    pickle.dump(knn130, f)

## TRAIN knn TOP 140fi

In [176]:
# train_data140['tp_ICD_cl0'] = le.transform(train_data140['tp_ICD_cl0'])

In [177]:
# Separate features and tp_ICD_cl0 variable for train_data140
X_train140 = train_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_train140 = train_data140['tp_ICD_cl0']

In [178]:
timer = CalculateTime(features=140, data_type='train')
timer.start()

knn140, data_top_5, Confusion_df140, eval_result140, cv_result140 = knn_custom_kfold_evaluation(X_train140, y_train140, le, feature=140, best_k=21)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.59 minutes

In [179]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,248.0,0.476190,251.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
2,41.0,151.0,0.190476,197.0,0.190476,104.1,0.142857,5.0,0.095238,147.0,0.095238
3,129.0,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
4,169.0,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
5,161.0,161.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,248.0,0.476190,251.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
10397,153.0,129.0,0.238095,153.0,0.190476,154.0,0.142857,146.0,0.095238,18.9,0.047619
10398,169.0,7.1,0.380952,161.0,0.238095,41.0,0.095238,150.0,0.095238,169.0,0.095238
10399,249.0,248.0,0.476190,251.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.190476,146.0,0.142857,185.9,0.142857,104.1,0.095238,197.0,0.095238

In [180]:
Confusion_df140

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,133,0,21,0,1,0,0,0,0,0,...,1,0,0,15,0,0,0,1,0,0
7.1,0,229,0,0,2,1,0,0,2,0,...,1,1,0,28,0,0,0,1,0,0
18.9,0,0,385,0,1,4,0,0,0,0,...,1,0,0,5,0,0,0,1,0,0
32.1,0,0,27,363,0,0,0,0,0,0,...,0,0,0,5,1,0,0,0,0,0
41.0,1,0,5,0,355,1,1,0,0,1,...,0,0,0,2,1,0,0,0,0,0
98.9,0,4,11,1,1,378,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104.1,0,0,2,0,1,2,165,0,11,0,...,1,0,0,70,4,0,0,1,0,0
111.0,1,5,0,0,0,1,2,350,3,0,...,10,0,0,0,0,0,0,0,0,0
128.0,1,0,1,0,0,0,0,1,348,0,...,0,0,0,0,2,0,0,0,0,0
129.0,0,0,0,0,0,0,0,1,0,383,...,7,0,0,1,7,0,0,0,0,0
146.0,1,4,0,0,0,0,0,1,17,0,...,5,0,0,0,11,0,0,0,0,0
147.0,0,0,1,1,2,5,1,2,1,0,...,10,0,0,0,4,0,0,0,0,0
150.0,1,0,15,1,2,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
151.0,0,3,1,0,0,0,0,0,2,0,...,8,0,0,0,4,0,0,0,0,0
153.0,0,0,16,0,1,0,0,0,0,0,...,1,0,0,0,13,0,0,0,0,0
154.0,0,0,13,0,0,1,0,0,0,0,...,1,0,1,25,11,0,0,0,0,0
161.0,0,6,2,0,4,0,0,0,0,3,...,345,0,0,1,0,0,0,0,1,0
169.0,2,5,20,0,1,0,0,1,0,0,...,5,189,0,31,3,0,0,0,0,0
185.9,2,2,0,0,0,0,0,0,0,1,...,3,1,350,16,4,2,0,0,0,0
197.0,1,0,14,1,3,1,0,0,2,3,...,2,0,0,192,0,0,0,2,0,0
212.9,1,1,19,0,1,0,0,1,32,4,...,11,1,0,0,146,3,0,0,0,0
217.0,1,0,21,0,1,1,0,1,5,4,...,5,0,0,0,0,150,0,0,0,0
239.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,13,1,384,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,14,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,398

In [181]:
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.332500,0.332500,0.667500,0.001199,0.917241,0.332500,0.488073,0.082759,0.667500,0.993727
1,7.1,0.572500,0.572500,0.427500,0.002991,0.884170,0.572500,0.694992,0.115830,0.427500,0.455341
2,18.9,0.962500,0.962500,0.037500,0.018549,0.670732,0.962500,0.790554,0.329268,0.037500,0.479299
3,32.1,0.907500,0.907500,0.092500,0.000400,0.989101,0.907500,0.946545,0.010899,0.092500,0.792481
4,41.0,0.887500,0.887500,0.112500,0.002096,0.944149,0.887500,0.914948,0.055851,0.112500,0.387762
5,98.9,0.945000,0.945000,0.055000,0.001697,0.956962,0.945000,0.950943,0.043038,0.055000,0.794718
6,104.1,0.412500,0.412500,0.587500,0.000400,0.976331,0.412500,0.579965,0.023669,0.587500,0.700460
7,111.0,0.875000,0.875000,0.125000,0.000799,0.977654,0.875000,0.923483,0.022346,0.125000,0.442143
8,128.0,0.870000,0.870000,0.130000,0.007444,0.822695,0.870000,0.845687,0.177305,0.130000,0.387762
9,129.0,0.957500,0.957500,0.042500,0.001597,0.959900,0.957500,0.958698,0.040100,0.042500,0.413482
10,146.0,0.885000,0.885000,0.115000,0.011760,0.748414,0.885000,0.810997,0.251586,0.115000,0.476987
11,147.0,0.635000,0.635000,0.365000,0.004480,0.849498,0.635000,0.726753,0.150502,0.365000,0.496929
12,150.0,0.890000,0.890000,0.110000,0.000300,0.991643,0.890000,0.938076,0.008357,0.110000,0.791116
13,151.0,0.647500,0.647500,0.352500,0.001896,0.931655,0.647500,0.764012,0.068345,0.352500,0.512486
14,153.0,0.452500,0.452500,0.547500,0.003786,0.826484,0.452500,0.584814,0.173516,0.547500,0.953440
15,154.0,0.857500,0.857500,0.142500,0.140672,0.173232,0.857500,0.288235,0.826768,0.142500,0.360979
16,161.0,0.862500,0.862500,0.137500,0.007838,0.813679,0.862500,0.837379,0.186321,0.137500,0.442417
17,169.0,0.472500,0.472500,0.527500,0.000300,0.984375,0.472500,0.638514,0.015625,0.527500,0.455637
18,185.9,0.875000,0.875000,0.125000,0.000100,0.997151,0.875000,0.932091,0.002849,0.125000,0.416885
19,197.0,0.480000,0.480000,0.520000,0.020856,0.474074,0.480000,0.477019,0.525926,0.520000,0.894110
20,212.9,0.365000,0.365000,0.635000,0.007740,0.651786,0.365000,0.467949,0.348214,0.635000,0.602119
21,217.0,0.375000,0.375000,0.625000,0.000600,0.961538,0.375000,0.539568,0.038462,0.625000,0.999905
22,239.2,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.355500
23,248.0,1.000000,1.000000,0.000000,0.000600,0.985222,1.000000,0.992556,0.014778,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000200,0.994832,0.962500,0.978399,0.005168,0.037500,0.360872
25,251.0,0.995000,0.995000,0.005000,0.000000,1.000000,0.995000,0.997494,0.000000,0.005000,1.887170
26,average,0.747596,0.747596,0.252404,0.009165,0.864712,0.747596,0.771051,0.135288,0.252404,0.609759

In [182]:
cv_result140

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.643269  0.703215    0.356731  0.643269    0.775482
1       2.0  0.687500  0.744807    0.312500  0.687500    0.812536
2       3.0  0.693269  0.733677    0.306731  0.693269    0.779087
3       4.0  0.666346  0.733191    0.333654  0.666346    0.814944
4       5.0  0.670192  0.732094    0.329808  0.670192    0.806594
5       6.0  0.645192  0.714966    0.354808  0.645192    0.801662
6       7.0  0.657692  0.722321    0.342308  0.657692    0.801036
7       8.0  0.677885  0.745268    0.322115  0.677885    0.827527
8       9.0  0.652885  0.722817    0.347115  0.652885    0.809529
9      10.0  0.687500  0.747678    0.312500  0.687500    0.819401
10       11  0.747596  0.801901    0.252404  0.747596    0.864712
11  average  0.668173  0.730004    0.331827  0.668173    0.804780
12      max  0.693269  0.733677    0.306731  0.693269    0.779087

### SAVE MODEL dTOP140fi

In [183]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier140.pkl', 'wb') as f:
    pickle.dump(knn140, f)

## TRAIN knn TOP 150fi

In [184]:
# train_data150['tp_ICD_cl0'] = le.transform(train_data150['tp_ICD_cl0'])

In [185]:
# Separate features and tp_ICD_cl0 variable for train_data150
X_train150 = train_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_train150 = train_data150['tp_ICD_cl0']

In [186]:
timer = CalculateTime(features=150, data_type='train')
timer.start()

knn150, data_top_5, Confusion_df150, eval_result150, cv_result150 = knn_custom_kfold_evaluation(X_train150, y_train150, le, feature=150, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 1.69 minutes

In [187]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
2,41.0,197.0,0.25,151.0,0.20,104.1,0.15,212.9,0.15,5.0,0.05
3,129.0,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.10,185.9,0.10
4,169.0,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.10,185.9,0.10
5,161.0,161.0,0.35,169.0,0.25,7.1,0.10,146.0,0.10,150.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.40,154.0,0.25,98.9,0.10,104.1,0.10,129.0,0.05
10398,169.0,7.1,0.30,41.0,0.30,161.0,0.20,18.9,0.05,146.0,0.05
10399,249.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
10400,150.0,154.0,0.20,98.9,0.15,151.0,0.15,185.9,0.15,150.0,0.10

In [188]:
Confusion_df150

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,157,7,0,0,2,0,1,217,0,0,...,0,0,0,0,0,0,0,0,1,0
7.1,1,334,9,0,13,0,0,7,0,0,...,2,0,0,5,0,0,0,0,1,0
18.9,0,0,372,2,0,0,0,12,0,0,...,1,0,0,0,0,0,0,0,1,0
32.1,2,0,25,357,1,0,0,2,6,0,...,0,0,0,2,0,0,0,0,0,0
41.0,0,1,5,0,391,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
98.9,0,8,10,1,1,349,0,1,0,0,...,2,0,0,4,0,0,0,0,0,0
104.1,2,1,4,0,0,0,227,163,2,0,...,0,0,0,0,0,0,0,0,1,0
111.0,3,9,12,0,7,0,0,345,3,0,...,3,0,0,2,0,0,0,0,0,0
128.0,0,2,1,5,0,0,0,46,344,0,...,0,0,0,0,0,0,0,0,0,0
129.0,2,7,17,0,5,0,0,4,0,365,...,0,0,0,0,0,0,0,0,0,0
146.0,1,0,1,0,6,0,0,129,17,0,...,0,0,0,8,0,0,0,0,0,0
147.0,1,0,17,0,0,0,0,119,1,0,...,1,0,0,0,0,0,0,0,0,0
150.0,1,7,18,0,7,0,0,0,0,0,...,5,0,0,2,0,0,0,0,0,0
151.0,1,4,14,0,36,0,0,126,2,0,...,0,0,0,0,0,0,0,0,0,0
153.0,1,0,0,0,1,0,0,191,0,1,...,1,0,0,0,0,0,0,0,0,0
154.0,2,0,13,1,1,0,2,3,0,0,...,0,0,0,1,0,0,0,0,0,0
161.0,2,0,1,6,0,0,0,20,0,0,...,367,0,0,0,0,0,0,0,0,0
169.0,0,7,5,0,8,0,2,137,0,0,...,1,207,1,0,0,0,0,0,0,0
185.9,2,2,3,0,5,0,0,0,16,2,...,1,0,350,1,0,0,0,0,0,0
197.0,3,9,16,0,3,0,0,174,2,0,...,0,0,0,183,0,0,0,0,2,0
212.9,2,10,24,0,10,1,0,168,32,0,...,1,0,0,0,151,0,0,0,0,0
217.0,1,6,9,0,6,0,0,195,4,0,...,4,0,0,1,0,168,0,0,0,0
239.2,0,13,3,0,0,0,1,299,0,0,...,0,0,0,0,0,0,81,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,399

In [189]:
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.392500,0.392500,0.607500,0.002693,0.853261,0.392500,0.537671,0.146739,0.607500,0.543569
1,7.1,0.835000,0.835000,0.165000,0.009214,0.782201,0.835000,0.807739,0.217799,0.165000,0.428327
2,18.9,0.930000,0.930000,0.070000,0.020280,0.642487,0.930000,0.759959,0.357513,0.070000,0.500991
3,32.1,0.892500,0.892500,0.107500,0.001498,0.959677,0.892500,0.924870,0.040323,0.107500,0.792481
4,41.0,0.977500,0.977500,0.022500,0.011076,0.777336,0.977500,0.866002,0.222664,0.022500,0.817356
5,98.9,0.872500,0.872500,0.127500,0.000100,0.997143,0.872500,0.930667,0.002857,0.127500,0.428394
6,104.1,0.567500,0.567500,0.432500,0.000700,0.970085,0.567500,0.716088,0.029915,0.432500,1.287062
7,111.0,0.862500,0.862500,0.137500,0.167707,0.146186,0.862500,0.250000,0.853814,0.137500,0.430805
8,128.0,0.860000,0.860000,0.140000,0.008428,0.801865,0.860000,0.829916,0.198135,0.140000,0.500000
9,129.0,0.912500,0.912500,0.087500,0.000300,0.991848,0.912500,0.950521,0.008152,0.087500,0.792892
10,146.0,0.585000,0.585000,0.415000,0.000500,0.979079,0.585000,0.732394,0.020921,0.415000,0.602112
11,147.0,0.652500,0.652500,0.347500,0.026195,0.492453,0.652500,0.561290,0.507547,0.347500,1.000022
12,150.0,0.885000,0.885000,0.115000,0.000100,0.997183,0.885000,0.937748,0.002817,0.115000,0.792674
13,151.0,0.280000,0.280000,0.720000,0.000100,0.991150,0.280000,0.436647,0.008850,0.720000,0.898244
14,153.0,0.505000,0.505000,0.495000,0.003885,0.838174,0.505000,0.630265,0.161826,0.495000,0.907195
15,154.0,0.880000,0.880000,0.120000,0.001697,0.953930,0.880000,0.915475,0.046070,0.120000,0.428428
16,161.0,0.917500,0.917500,0.082500,0.002195,0.943445,0.917500,0.930292,0.056555,0.082500,0.500022
17,169.0,0.517500,0.517500,0.482500,0.000000,1.000000,0.517500,0.682043,0.000000,0.482500,0.540476
18,185.9,0.875000,0.875000,0.125000,0.000100,0.997151,0.875000,0.932091,0.002849,0.125000,0.505297
19,197.0,0.457500,0.457500,0.542500,0.002693,0.871429,0.457500,0.600000,0.128571,0.542500,1.003240
20,212.9,0.377500,0.377500,0.622500,0.000000,1.000000,0.377500,0.548094,0.000000,0.622500,0.603934
21,217.0,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,1.028750
22,239.2,0.202500,0.202500,0.797500,0.000000,1.000000,0.202500,0.336798,0.000000,0.797500,1.261713
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000600,0.984655,0.962500,0.973451,0.015345,0.037500,0.428350
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.716058,0.716058,0.283942,0.010002,0.883490,0.716058,0.745397,0.116510,0.283942,0.654705

In [190]:
cv_result150

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.636538  0.703604    0.363462  0.636538    0.786467
1       2.0  0.670192  0.732511    0.329808  0.670192    0.807607
2       3.0  0.650962  0.703907    0.349038  0.650962    0.766229
3       4.0  0.662500  0.738565    0.337500  0.662500    0.834364
4       5.0  0.678846  0.741781    0.321154  0.678846    0.817577
5       6.0  0.657692  0.729089    0.342308  0.657692    0.817875
6       7.0  0.657692  0.723040    0.342308  0.657692    0.802807
7       8.0  0.635577  0.716521    0.364423  0.635577    0.821092
8       9.0  0.654808  0.714187    0.345192  0.654808    0.785409
9      10.0  0.687500  0.760321    0.312500  0.687500    0.850395
10       11  0.716058  0.791011    0.283942  0.716058    0.883490
11  average  0.659231  0.726353    0.340769  0.659231    0.808982
12      max  0.687500  0.760321    0.312500  0.687500    0.850395

### SAVE MODEL dTOP150fi

In [191]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier150.pkl', 'wb') as f:
    pickle.dump(knn150, f)

## TRAIN knn ALLfi

In [192]:
# train_data353['tp_ICD_cl0'] = le.transform(train_data353['tp_ICD_cl0'])

In [193]:
# Separate features and tp_ICD_cl0 variable for train_data353
X_train353 = train_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_train353 = train_data353['tp_ICD_cl0']

In [194]:
timer = CalculateTime(features='all', data_type='train')
timer.start()

knn353, data_top_5, Confusion_df353, eval_result353, cv_result353 = knn_custom_kfold_evaluation(X_train353, y_train353, le, feature=353, best_k=20)

time_taken = timer.time_taken()
print(f"Time taken: {time_taken:.2f} minutes")

timer.save_time_to_csv(time_taken)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

Time taken: 3.36 minutes

In [195]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
2,41.0,104.1,0.15,151.0,0.15,197.0,0.15,212.9,0.15,5.0,0.10
3,129.0,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
4,169.0,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
5,161.0,41.0,0.25,161.0,0.20,169.0,0.15,18.9,0.10,150.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...
10396,248.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
10397,153.0,153.0,0.30,111.0,0.25,129.0,0.10,98.9,0.05,154.0,0.05
10398,169.0,7.1,0.25,41.0,0.25,161.0,0.15,169.0,0.15,98.9,0.05
10399,249.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
10400,150.0,98.9,0.30,18.9,0.10,147.0,0.10,150.0,0.10,154.0,0.10

In [196]:
Confusion_df353

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
5.0,137,0,21,0,1,0,0,0,0,7,...,1,1,0,0,0,0,0,0,1,0
7.1,2,210,0,0,1,0,0,0,2,4,...,13,0,0,0,0,0,10,0,1,0
18.9,0,3,390,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
32.1,0,0,0,387,0,0,0,0,6,2,...,0,0,0,0,0,0,0,0,0,0
41.0,0,0,5,0,357,1,1,0,0,0,...,1,0,0,0,0,0,2,0,0,0
98.9,2,0,10,0,1,370,4,0,1,0,...,0,0,0,0,0,0,4,0,0,0
104.1,1,1,4,0,1,0,158,0,0,0,...,11,0,0,0,0,0,4,0,1,0
111.0,0,5,11,0,0,1,2,297,3,21,...,8,2,0,0,0,0,4,0,0,0
128.0,1,0,1,0,0,0,0,0,349,0,...,0,0,0,0,0,0,2,0,0,0
129.0,2,0,17,0,0,1,0,0,0,362,...,5,0,0,0,0,0,7,0,0,0
146.0,1,0,0,0,3,9,0,0,17,0,...,6,0,0,0,0,0,11,0,0,0
147.0,1,0,19,1,1,0,0,0,1,4,...,10,1,0,0,0,0,0,0,0,0
150.0,1,5,18,0,0,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
151.0,1,1,14,0,0,0,0,0,2,4,...,30,0,0,0,0,0,4,0,0,0
153.0,1,0,16,0,0,0,0,2,0,12,...,1,1,0,0,0,0,0,0,0,0
154.0,2,0,19,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
161.0,2,6,1,0,0,1,0,0,0,22,...,352,0,0,0,0,0,0,0,0,0
169.0,0,1,1,0,3,0,3,0,0,0,...,1,225,0,0,0,0,0,0,0,0
185.9,0,0,4,0,0,5,0,0,16,13,...,4,0,336,0,0,0,3,0,0,0
197.0,2,0,16,0,1,3,1,0,1,0,...,0,0,0,100,0,0,8,0,2,0
212.9,3,2,23,0,1,0,4,2,0,9,...,13,1,0,1,170,0,8,0,0,0
217.0,1,0,9,0,1,0,6,1,4,6,...,5,0,1,0,0,168,7,0,0,0
239.2,0,0,2,0,0,4,1,0,0,0,...,2,0,0,0,0,0,391,0,0,0
248.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,400,0,0
249.0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,385,0
251.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,399

In [197]:
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
0,5.0,0.342500,0.342500,0.657500,0.002295,0.856250,0.342500,0.489286,0.143750,0.657500,0.887854
1,7.1,0.525000,0.525000,0.475000,0.002394,0.897436,0.525000,0.662461,0.102564,0.475000,0.540477
2,18.9,0.975000,0.975000,0.025000,0.020664,0.648918,0.975000,0.779221,0.351082,0.025000,0.870351
3,32.1,0.967500,0.967500,0.032500,0.000200,0.994859,0.967500,0.980989,0.005141,0.032500,0.500153
4,41.0,0.892500,0.892500,0.107500,0.001398,0.962264,0.892500,0.926070,0.037736,0.107500,0.387762
5,98.9,0.925000,0.925000,0.075000,0.002494,0.936709,0.925000,0.930818,0.063291,0.075000,0.756098
6,104.1,0.395000,0.395000,0.605000,0.002593,0.858696,0.395000,0.541096,0.141304,0.605000,0.565124
7,111.0,0.742500,0.742500,0.257500,0.000500,0.983444,0.742500,0.846154,0.016556,0.257500,0.428317
8,128.0,0.872500,0.872500,0.127500,0.005272,0.868159,0.872500,0.870324,0.131841,0.127500,0.387762
9,129.0,0.905000,0.905000,0.095000,0.010293,0.776824,0.905000,0.836028,0.223176,0.095000,0.792197
10,146.0,0.877500,0.877500,0.122500,0.002792,0.926121,0.877500,0.901155,0.073879,0.122500,0.477615
11,147.0,0.617500,0.617500,0.382500,0.036516,0.394569,0.617500,0.481481,0.605431,0.382500,0.999258
12,150.0,0.915000,0.915000,0.085000,0.000200,0.994565,0.915000,0.953125,0.005435,0.085000,0.792516
13,151.0,0.552500,0.552500,0.447500,0.000200,0.991031,0.552500,0.709470,0.008969,0.447500,0.479634
14,153.0,0.440000,0.440000,0.560000,0.001797,0.907216,0.440000,0.592593,0.092784,0.560000,0.983242
15,154.0,0.870000,0.870000,0.130000,0.140007,0.176113,0.870000,0.292929,0.823887,0.130000,0.429201
16,161.0,0.880000,0.880000,0.120000,0.011369,0.753747,0.880000,0.811995,0.246253,0.120000,0.458360
17,169.0,0.562500,0.562500,0.437500,0.000600,0.974026,0.562500,0.713154,0.025974,0.437500,0.540476
18,185.9,0.840000,0.840000,0.160000,0.000200,0.994083,0.840000,0.910569,0.005917,0.160000,0.512829
19,197.0,0.250000,0.250000,0.750000,0.000100,0.990099,0.250000,0.399202,0.009901,0.750000,1.158966
20,212.9,0.425000,0.425000,0.575000,0.000000,1.000000,0.425000,0.596491,0.000000,0.575000,0.999609
21,217.0,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,0.904194
22,239.2,0.977500,0.977500,0.022500,0.007346,0.840860,0.977500,0.904046,0.159140,0.022500,0.659442
23,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
24,249.0,0.962500,0.962500,0.037500,0.000600,0.984655,0.962500,0.973451,0.015345,0.037500,0.428350
25,251.0,0.997500,0.997500,0.002500,0.000000,1.000000,0.997500,0.998748,0.000000,0.002500,0.000000
26,average,0.735769,0.735769,0.264231,0.009609,0.873486,0.735769,0.757400,0.126514,0.264231,0.613069

In [198]:
cv_result353

      kfold  accuracy  f1_score  error_rate    recall  precisions
0       1.0  0.643269  0.712846    0.356731  0.643269    0.799299
1       2.0  0.687500  0.743769    0.312500  0.687500    0.810069
2       3.0  0.631731  0.678268    0.368269  0.631731    0.732207
3       4.0  0.663462  0.741202    0.336538  0.663462    0.839579
4       5.0  0.665385  0.725616    0.334615  0.665385    0.797838
5       6.0  0.650000  0.720886    0.350000  0.650000    0.809125
6       7.0  0.665385  0.728955    0.334615  0.665385    0.805954
7       8.0  0.686538  0.753033    0.313462  0.686538    0.833791
8       9.0  0.660577  0.733912    0.339423  0.660577    0.825563
9      10.0  0.711538  0.771263    0.288462  0.711538    0.841933
10       11  0.735769  0.798735    0.264231  0.735769    0.873486
11  average  0.666538  0.730975    0.333462  0.666538    0.809536
12      max  0.711538  0.771263    0.288462  0.711538    0.841933

### SAVE MODEL dAllfi

In [199]:
# Save the models to a file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier353.pkl', 'wb') as f:
    pickle.dump(knn353, f)

# **TESTING**

## LOADING TEST_DATASET

In [200]:
# sudah load dataset testing dari awal

## LOAD & APPLY MODEL_SHAP

In [201]:
# sudah apply shap ke data testing dari awal

## LOAD & APPLY MODEL dTOP5fi

In [202]:
# le = LabelEncoder()
# le.fit(test_data5['tp_ICD_cl0'])

In [203]:
# test_data5['tp_ICD_cl0'] = le.transform(test_data5['tp_ICD_cl0'])

In [204]:
# Separate features and tp_ICD_cl0 variable for test_data5
X_test5 = test_data5.drop(labels=['tp_ICD_cl0'], axis=1)
y_test5 = test_data5['tp_ICD_cl0']

In [205]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier5.pkl', 'rb') as f:
    knn_5 = pickle.load(f)

### EVALUATION & SAVE

In [206]:
prob5 = knn_5.predict_proba(X_test5)
classes5 = knn_5.classes_

y_pred5, data_top_5 = get_predictions(prob5, classes5, threshold, 10, np.array(y_test5), le)

Confusion_df5 = pd.DataFrame(confusion_matrix(np.array(y_test5), y_pred5))
Confusion_df5.index, Confusion_df5.columns = le.inverse_transform(classes5), le.inverse_transform(classes5)

eval_result5 = calculate_evaluation_metrics(Confusion_df=Confusion_df5)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

In [207]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.375000,41.0,0.333333,169.0,0.083333,7.1,0.041667,104.1,0.041667
2,185.9,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
3,248.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667
4,146.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
5,251.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
2597,18.9,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
2598,217.0,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
2599,104.1,239.2,0.416667,32.1,0.125000,217.0,0.125000,185.9,0.083333,7.1,0.041667
2600,251.0,249.0,0.500000,251.0,0.250000,248.0,0.125000,5.0,0.083333,98.9,0.041667

In [208]:
eval_result5.index = eval_result5.index + 1
eval_result5

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.100000,0.100000,0.900000,0.000000,1.000000,0.100000,0.181818,0.000000,0.900000,1.587083
2,7.1,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,-0.894783
3,18.9,0.840000,0.840000,0.160000,0.000000,1.000000,0.840000,0.913043,0.000000,0.160000,0.380179
4,32.1,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
5,41.0,0.480000,0.480000,0.520000,0.000000,1.000000,0.480000,0.648649,0.000000,0.520000,0.233091
6,98.9,0.910000,0.910000,0.090000,0.000000,1.000000,0.910000,0.952880,0.000000,0.090000,0.380168
7,104.1,0.050000,0.050000,0.950000,0.000000,1.000000,0.050000,0.095238,0.000000,0.950000,0.536053
8,111.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.387049
9,128.0,0.850000,0.850000,0.150000,0.006359,0.841584,0.850000,0.845771,0.158416,0.150000,0.345695
10,129.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
11,146.0,0.810000,0.810000,0.190000,0.000000,1.000000,0.810000,0.895028,0.000000,0.190000,0.380436
12,147.0,0.130000,0.130000,0.870000,0.000000,1.000000,0.130000,0.230088,0.000000,0.870000,0.428358
13,150.0,0.180000,0.180000,0.820000,0.000000,1.000000,0.180000,0.305085,0.000000,0.820000,0.416291
14,151.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.380094
15,153.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,2.014638
16,154.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.561536
17,161.0,0.630000,0.630000,0.370000,0.031383,0.437500,0.630000,0.516393,0.562500,0.370000,0.239812
18,169.0,0.280000,0.280000,0.720000,0.000000,1.000000,0.280000,0.437500,0.000000,0.720000,0.373114
19,185.9,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,0.397664
20,197.0,0.940000,0.940000,0.060000,0.000000,1.000000,0.940000,0.969072,0.000000,0.060000,0.384027
21,212.9,0.060000,0.060000,0.940000,0.000000,1.000000,0.060000,0.113208,0.000000,0.940000,0.413068
22,217.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
23,239.2,1.000000,1.000000,0.000000,0.282228,0.092336,1.000000,0.169062,0.907664,0.000000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.003984,0.903846,0.940000,0.921569,0.096154,0.060000,0.359388
26,251.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,0.497321
27,average,0.580769,0.580769,0.419231,0.012460,0.779818,0.580769,0.582450,0.078397,0.419231,0.376934

In [209]:
Confusion_df5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier5.csv')
eval_result5.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier5.csv', index=False)

## LOAD & APPLY MODEL dTOP10fi

In [210]:
# test_data10['tp_ICD_cl0'] = le.transform(test_data10['tp_ICD_cl0'])

In [211]:
# Separate features and tp_ICD_cl0 variable for test_data10
X_test10 = test_data10.drop(labels=['tp_ICD_cl0'], axis=1)
y_test10 = test_data10['tp_ICD_cl0']

In [212]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier10.pkl', 'rb') as f:
    knn_10 = pickle.load(f)

### EVALUATION & SAVE

In [213]:
prob10 = knn_10.predict_proba(X_test10)
classes10 = knn_10.classes_

y_pred10, data_top_5 = get_predictions(prob10, classes10, threshold, 10, np.array(y_test10), le)

Confusion_df10 = pd.DataFrame(confusion_matrix(np.array(y_test10), y_pred10))
Confusion_df10.index, Confusion_df10.columns = le.inverse_transform(classes10), le.inverse_transform(classes10)

eval_result10 = calculate_evaluation_metrics(Confusion_df=Confusion_df10)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
<ipython-input-61-308ee79aed86>:22: RuntimeWarning: invalid value encountered in scalar divide
  type_1_error = (Confusion_df[label].sum() - tp) / (Confusion_df[label].sum())

In [214]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.318182,41.0,0.272727,104.1,0.090909,169.0,0.090909,217.0,0.090909
2,185.9,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
3,248.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN
4,146.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
5,251.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
2597,18.9,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
2598,217.0,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
2599,104.1,32.1,0.181818,7.1,0.136364,41.0,0.090909,153.0,0.090909,154.0,0.090909
2600,251.0,249.0,0.545455,248.0,0.272727,251.0,0.181818,NaN,NaN,NaN,NaN

In [215]:
Confusion_df10.index = Confusion_df5.index + 1
Confusion_df10
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,22,0,0,78,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,97,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19.9,0,0,16,72,0,0,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
33.1,0,0,0,100,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,0,0,98,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
99.9,0,0,0,0,0,92,0,0,0,0,...,0,0,0,0,0,0,8,0,0,0
105.1,0,0,0,0,1,0,86,0,6,0,...,0,0,0,0,0,0,7,0,0,0
112.0,0,0,0,0,0,0,0,91,1,0,...,6,0,0,0,0,0,0,0,0,0
129.0,1,0,0,14,0,0,0,0,85,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,0,0,0,0,0,0,0,0,92,...,0,0,0,0,0,0,7,0,1,0
147.0,0,0,0,77,1,0,0,0,4,0,...,13,0,0,0,0,0,4,0,0,0
148.0,0,0,0,77,0,0,0,0,0,0,...,10,0,0,0,0,0,7,0,0,0
151.0,0,0,0,73,0,0,0,0,0,0,...,13,0,0,0,0,0,7,0,0,0
152.0,0,0,0,68,3,0,0,0,1,0,...,0,0,0,0,0,0,9,0,0,0
154.0,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,3,0,0,0
155.0,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,8,0,0,0
162.0,0,0,0,29,0,0,0,0,0,0,...,63,0,0,0,0,0,5,0,0,0
170.0,0,0,0,61,0,0,0,0,0,0,...,0,31,0,0,0,0,3,0,1,0
186.9,0,0,0,80,0,0,0,0,0,0,...,4,0,7,0,0,0,9,0,0,0
198.0,0,0,0,86,2,0,0,0,0,0,...,2,0,0,0,0,0,8,0,0,0
213.9,0,0,0,80,0,0,0,0,1,0,...,6,0,0,0,9,0,3,0,0,0
218.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,87,12,0,0,0
240.2,0,0,0,92,0,0,0,0,0,0,...,0,0,0,0,0,0,8,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,96

In [216]:
eval_result10.index = eval_result10.index + 1
eval_result10

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.220000,0.220000,0.780000,0.001597,0.846154,0.220000,0.349206,0.153846,0.780000,1.584963
2,7.1,0.970000,0.970000,0.030000,0.000000,1.000000,0.970000,0.984772,0.000000,0.030000,0.238239
3,18.9,0.160000,0.160000,0.840000,0.000000,1.000000,0.160000,0.275862,0.000000,0.840000,0.777728
4,32.1,1.000000,1.000000,0.000000,0.262972,0.100806,1.000000,0.183150,0.899194,0.000000,0.000000
5,41.0,0.980000,0.980000,0.020000,0.002792,0.933333,0.980000,0.956098,0.066667,0.020000,0.620573
6,98.9,0.920000,0.920000,0.080000,0.000000,1.000000,0.920000,0.958333,0.000000,0.080000,0.345621
7,104.1,0.860000,0.860000,0.140000,0.000000,1.000000,0.860000,0.924731,0.000000,0.140000,0.420657
8,111.0,0.910000,0.910000,0.090000,0.000000,1.000000,0.910000,0.952880,0.000000,0.090000,0.389480
9,128.0,0.850000,0.850000,0.150000,0.005964,0.850000,0.850000,0.850000,0.150000,0.150000,0.682707
10,129.0,0.920000,0.920000,0.080000,0.000000,1.000000,0.920000,0.958333,0.000000,0.080000,0.346899
11,146.0,0.010000,0.010000,0.990000,0.001597,0.200000,0.010000,0.019048,0.800000,0.990000,0.380637
12,147.0,0.060000,0.060000,0.940000,0.000000,1.000000,0.060000,0.113208,0.000000,0.940000,0.394004
13,150.0,0.050000,0.050000,0.950000,0.000000,1.000000,0.050000,0.095238,0.000000,0.950000,0.381407
14,151.0,0.190000,0.190000,0.810000,0.000000,1.000000,0.190000,0.319328,0.000000,0.810000,0.405712
15,153.0,0.950000,0.950000,0.050000,0.008330,0.818966,0.950000,0.879630,0.181034,0.050000,0.592972
16,154.0,0.850000,0.850000,0.150000,0.000000,1.000000,0.850000,0.918919,0.000000,0.150000,0.361341
17,161.0,0.630000,0.630000,0.370000,0.026480,0.480916,0.630000,0.545455,0.519084,0.370000,0.239812
18,169.0,0.310000,0.310000,0.690000,0.000000,1.000000,0.310000,0.473282,0.000000,0.690000,0.430677
19,185.9,0.070000,0.070000,0.930000,0.000000,1.000000,0.070000,0.130841,0.000000,0.930000,0.367950
20,197.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.353411
21,212.9,0.090000,0.090000,0.910000,0.000000,1.000000,0.090000,0.165138,0.000000,0.910000,0.368258
22,217.0,0.870000,0.870000,0.130000,0.000000,1.000000,0.870000,0.930481,0.000000,0.130000,0.345765
23,239.2,0.080000,0.080000,0.920000,0.038831,0.073394,0.080000,0.076555,0.926606,0.920000,0.345156
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.705146
26,251.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,1.479315
27,average,0.571154,0.571154,0.428846,0.013452,0.818179,0.571154,0.576707,0.149094,0.428846,0.483017

In [217]:
Confusion_df10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier10.csv')
eval_result10.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier10.csv', index=False)

## LOAD & APPLY MODEL dTOP20fi

In [218]:
# test_data20['tp_ICD_cl0'] = le.transform(test_data20['tp_ICD_cl0'])

In [219]:
# Separate features and tp_ICD_cl0 variable for test_data20
X_test20 = test_data20.drop(labels=['tp_ICD_cl0'], axis=1)
y_test20 = test_data20['tp_ICD_cl0']

In [220]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier20.pkl', 'rb') as f:
    knn_20 = pickle.load(f)

### EVALUATION & SAVE

In [221]:
prob20 = knn_20.predict_proba(X_test20)
classes20 = knn_20.classes_

y_pred20, data_top_5 = get_predictions(prob20, classes20, threshold, 10, np.array(y_test20), le)

Confusion_df20 = pd.DataFrame(confusion_matrix(np.array(y_test20), y_pred20))
Confusion_df20.index, Confusion_df20.columns = le.inverse_transform(classes20), le.inverse_transform(classes20)

eval_result20 = calculate_evaluation_metrics(Confusion_df=Confusion_df20)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [222]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.25,41.0,0.15,146.0,0.15,104.1,0.1,169.0,0.1
2,185.9,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
3,248.0,248.0,0.65,251.0,0.20,249.0,0.15,NaN,NaN,NaN,NaN
4,146.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
5,251.0,249.0,0.40,248.0,0.35,251.0,0.25,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
2597,18.9,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
2598,217.0,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
2599,104.1,185.9,0.15,239.2,0.15,32.1,0.10,111.0,0.1,146.0,0.1
2600,251.0,249.0,0.40,248.0,0.35,251.0,0.25,NaN,NaN,NaN,NaN

In [223]:
Confusion_df20.index = Confusion_df20.index + 1
Confusion_df20
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,98,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,55,0,0,1,0,12,0,1,0,...,1,0,29,0,0,0,0,0,1,0
19.9,6,0,22,0,0,0,1,0,0,0,...,2,1,66,0,0,0,0,0,0,0
33.1,0,0,0,92,0,0,1,0,1,0,...,0,0,2,0,0,0,0,0,0,0
42.0,2,0,0,0,71,0,0,0,0,0,...,0,0,26,0,0,0,0,0,0,0
99.9,0,0,0,1,0,83,5,0,0,0,...,6,0,0,0,0,0,0,0,0,0
105.1,0,1,0,3,0,0,34,0,6,0,...,0,0,54,0,0,0,0,0,0,0
112.0,0,2,0,0,0,0,0,83,1,0,...,4,0,8,2,0,0,0,0,0,0
129.0,0,0,0,0,0,0,1,0,86,0,...,0,0,13,0,0,0,0,0,0,0
130.0,0,1,0,0,0,0,0,0,0,98,...,0,0,0,0,0,0,0,0,1,0
147.0,3,0,0,0,0,0,0,0,4,0,...,8,0,0,0,0,0,0,0,0,0
148.0,0,0,0,0,0,0,0,0,0,0,...,1,4,0,0,0,0,0,0,0,0
151.0,5,0,0,0,0,0,8,0,4,0,...,0,4,60,0,0,0,0,0,0,0
152.0,5,0,0,0,0,0,0,0,1,0,...,4,0,39,0,0,0,0,0,0,0
154.0,9,0,0,0,0,0,11,0,1,0,...,0,0,4,0,0,0,0,0,0,0
155.0,5,0,0,0,0,0,4,0,0,0,...,2,0,77,1,0,0,0,0,0,0
162.0,3,0,0,5,0,0,0,0,0,0,...,83,0,8,0,0,0,0,0,0,0
170.0,0,0,0,1,1,0,11,0,0,0,...,0,44,41,1,0,0,0,0,1,0
186.9,4,0,0,3,0,0,0,0,0,0,...,4,0,85,0,0,0,0,0,0,0
198.0,5,0,0,1,2,0,0,0,0,0,...,2,0,52,36,0,0,0,0,0,0
213.9,1,0,0,1,0,0,1,0,1,0,...,0,0,56,0,38,0,0,0,0,0
218.0,8,0,0,1,0,0,0,0,0,0,...,0,0,67,1,0,21,0,0,0,0
240.2,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,93,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,5,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [224]:
eval_result20.index = eval_result20.index + 1
eval_result20

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.980000,0.980000,0.020000,0.024200,0.612500,0.980000,0.753846,0.387500,0.020000,-0.280021
2,7.1,0.550000,0.550000,0.450000,0.001597,0.932203,0.550000,0.691824,0.067797,0.450000,0.630930
3,18.9,0.220000,0.220000,0.780000,0.000000,1.000000,0.220000,0.360656,0.000000,0.780000,0.792496
4,32.1,0.920000,0.920000,0.080000,0.006359,0.851852,0.920000,0.884615,0.148148,0.080000,0.431093
5,41.0,0.710000,0.710000,0.290000,0.001597,0.946667,0.710000,0.811429,0.053333,0.290000,0.366726
6,98.9,0.830000,0.830000,0.170000,0.000000,1.000000,0.830000,0.907104,0.000000,0.170000,0.480641
7,104.1,0.340000,0.340000,0.660000,0.023438,0.361702,0.340000,0.350515,0.638298,0.660000,0.231378
8,111.0,0.830000,0.830000,0.170000,0.000000,1.000000,0.830000,0.907104,0.000000,0.170000,0.382853
9,128.0,0.860000,0.860000,0.140000,0.008330,0.803738,0.860000,0.830918,0.196262,0.140000,0.366768
10,129.0,0.980000,0.980000,0.020000,0.000000,1.000000,0.980000,0.989899,0.000000,0.020000,4.235943
11,146.0,0.850000,0.850000,0.150000,0.000799,0.977011,0.850000,0.909091,0.022989,0.150000,0.424812
12,147.0,0.920000,0.920000,0.080000,0.000400,0.989247,0.920000,0.953368,0.010753,0.080000,0.423628
13,150.0,0.170000,0.170000,0.830000,0.000000,1.000000,0.170000,0.290598,0.000000,0.830000,0.231378
14,151.0,0.500000,0.500000,0.500000,0.000400,0.980392,0.500000,0.662252,0.019608,0.500000,0.255992
15,153.0,0.750000,0.750000,0.250000,0.013418,0.688073,0.750000,0.717703,0.311927,0.250000,0.770742
16,154.0,0.110000,0.110000,0.890000,0.000000,1.000000,0.110000,0.198198,0.000000,0.890000,0.409071
17,161.0,0.830000,0.830000,0.170000,0.013418,0.709402,0.830000,0.764977,0.290598,0.170000,0.443891
18,169.0,0.440000,0.440000,0.560000,0.003587,0.830189,0.440000,0.575163,0.169811,0.560000,0.245008
19,185.9,0.850000,0.850000,0.150000,0.194068,0.123726,0.850000,0.216010,0.876274,0.150000,0.999940
20,197.0,0.360000,0.360000,0.640000,0.001996,0.878049,0.360000,0.510638,0.121951,0.640000,0.231379
21,212.9,0.380000,0.380000,0.620000,0.000000,1.000000,0.380000,0.550725,0.000000,0.620000,0.231379
22,217.0,0.210000,0.210000,0.790000,0.000000,1.000000,0.210000,0.347107,0.000000,0.790000,0.350539
23,239.2,0.930000,0.930000,0.070000,0.000000,1.000000,0.930000,0.963731,0.000000,0.070000,1.605966
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.546813
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,0.418903
27,average,0.669615,0.669615,0.330385,0.011354,0.870920,0.669615,0.695045,0.129080,0.330385,0.585702

In [225]:
Confusion_df20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier20.csv')
eval_result20.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier20.csv', index=False)

## LOAD & APPLY MODEL dTOP30fi

In [226]:
# test_data30['tp_ICD_cl0'] = le.transform(test_data30['tp_ICD_cl0'])

In [227]:
# Separate features and tp_ICD_cl0 variable for test_data30
X_test30 = test_data30.drop(labels=['tp_ICD_cl0'], axis=1)
y_test30 = test_data30['tp_ICD_cl0']

In [228]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier30.pkl', 'rb') as f:
    knn_30 = pickle.load(f)

### EVALUATION & SAVE

In [229]:
prob30 = knn_30.predict_proba(X_test30)
classes30 = knn_30.classes_

y_pred30, data_top_5 = get_predictions(prob30, classes30, threshold, 10, np.array(y_test30), le)

Confusion_df30 = pd.DataFrame(confusion_matrix(np.array(y_test30), y_pred30))
Confusion_df30.index, Confusion_df30.columns = le.inverse_transform(classes30), le.inverse_transform(classes30)

eval_result30 = calculate_evaluation_metrics(Confusion_df=Confusion_df30)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [230]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,169.0,0.217391,161.0,0.173913,98.9,0.130435,146.0,0.130435,104.1,0.086957
2,185.9,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
3,248.0,248.0,0.652174,251.0,0.217391,249.0,0.130435,NaN,NaN,NaN,NaN
4,146.0,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
5,251.0,248.0,0.391304,249.0,0.391304,251.0,0.217391,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
2597,18.9,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
2598,217.0,98.9,0.304348,7.1,0.260870,146.0,0.086957,147.0,0.086957,154.0,0.086957
2599,104.1,32.1,0.173913,217.0,0.173913,129.0,0.130435,154.0,0.130435,185.9,0.086957
2600,251.0,248.0,0.391304,249.0,0.391304,251.0,0.217391,NaN,NaN,NaN,NaN

In [231]:
Confusion_df30.index = Confusion_df30.index + 1
Confusion_df30
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,35,0,0,59,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,55,2,25,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
19.9,0,0,90,1,0,1,0,0,0,0,...,2,0,0,0,0,3,1,0,0,0
33.1,0,0,0,95,2,0,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,0,17,81,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
99.9,0,0,4,0,0,88,0,1,0,0,...,0,0,0,0,0,1,2,0,0,0
105.1,0,1,0,47,3,1,28,0,0,0,...,1,0,1,0,0,1,2,0,0,0
112.0,0,2,0,51,0,0,0,44,0,0,...,0,2,0,0,0,0,1,0,0,0
129.0,0,0,0,12,1,0,0,0,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,1,11,0,0,0,0,0,0,82,...,0,1,0,0,0,4,0,1,0,0
147.0,0,0,0,39,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148.0,0,1,3,31,3,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
151.0,0,0,2,58,4,0,0,0,3,0,...,0,1,0,0,0,2,2,0,0,0
152.0,0,3,5,33,2,3,0,0,1,0,...,0,1,0,0,0,2,1,0,0,0
154.0,1,3,8,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,0,1,5,0,6,0,0,0,0,0,...,0,0,0,0,0,1,4,0,0,0
162.0,0,0,3,6,0,0,0,0,0,0,...,87,0,0,0,0,3,1,0,0,0
170.0,0,2,1,38,0,0,0,0,0,0,...,0,43,1,0,0,0,2,1,0,0
186.9,0,0,5,0,10,0,0,0,0,0,...,0,0,79,0,0,0,4,0,0,0
198.0,0,0,5,0,10,0,0,0,0,0,...,1,0,0,81,0,1,0,0,0,0
213.9,0,0,2,50,4,1,1,1,6,0,...,0,0,0,0,7,3,0,0,0,0
218.0,0,1,0,0,2,0,0,0,1,0,...,0,0,0,0,0,95,1,0,0,0
240.2,1,0,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,92,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,96

In [232]:
eval_result30.index = eval_result30.index + 1
eval_result30

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.350000,0.350000,0.650000,0.001597,0.897436,0.350000,0.503597,0.102564,0.650000,0.430677
2,7.1,0.550000,0.550000,0.450000,0.005964,0.785714,0.550000,0.647059,0.214286,0.450000,0.630930
3,18.9,0.900000,0.900000,0.100000,0.025341,0.580645,0.900000,0.705882,0.419355,0.100000,0.489398
4,32.1,0.950000,0.950000,0.050000,0.157398,0.169039,0.950000,0.287009,0.830961,0.050000,0.719297
5,41.0,0.810000,0.810000,0.190000,0.020376,0.609023,0.810000,0.695279,0.390977,0.190000,0.682608
6,98.9,0.880000,0.880000,0.120000,0.002394,0.936170,0.880000,0.907216,0.063830,0.120000,0.719869
7,104.1,0.280000,0.280000,0.720000,0.001199,0.903226,0.280000,0.427481,0.096774,0.720000,0.430677
8,111.0,0.440000,0.440000,0.560000,0.001199,0.936170,0.440000,0.598639,0.063830,0.560000,0.431017
9,128.0,0.860000,0.860000,0.140000,0.005964,0.851485,0.860000,0.855721,0.148515,0.140000,0.682762
10,129.0,0.820000,0.820000,0.180000,0.000000,1.000000,0.820000,0.901099,0.000000,0.180000,0.790963
11,146.0,0.570000,0.570000,0.430000,0.000799,0.966102,0.570000,0.716981,0.033898,0.430000,0.278944
12,147.0,0.600000,0.600000,0.400000,0.035122,0.397351,0.600000,0.478088,0.602649,0.400000,0.270238
13,150.0,0.280000,0.280000,0.720000,0.000000,1.000000,0.280000,0.437500,0.000000,0.720000,0.430677
14,151.0,0.490000,0.490000,0.510000,0.001597,0.924528,0.490000,0.640523,0.075472,0.510000,0.255962
15,153.0,0.760000,0.760000,0.240000,0.000000,1.000000,0.760000,0.863636,0.000000,0.240000,0.482599
16,154.0,0.780000,0.780000,0.220000,0.002792,0.917647,0.780000,0.843243,0.082353,0.220000,0.711828
17,161.0,0.870000,0.870000,0.130000,0.001996,0.945652,0.870000,0.906250,0.054348,0.130000,0.704452
18,169.0,0.430000,0.430000,0.570000,0.002394,0.877551,0.430000,0.577181,0.122449,0.570000,0.244056
19,185.9,0.790000,0.790000,0.210000,0.000799,0.975309,0.790000,0.872928,0.024691,0.210000,0.621763
20,197.0,0.810000,0.810000,0.190000,0.000000,1.000000,0.810000,0.895028,0.000000,0.190000,0.622863
21,212.9,0.070000,0.070000,0.930000,0.000000,1.000000,0.070000,0.130841,0.000000,0.930000,0.430677
22,217.0,0.950000,0.950000,0.050000,0.008723,0.811966,0.950000,0.875576,0.188034,0.050000,0.945365
23,239.2,0.920000,0.920000,0.080000,0.008723,0.807018,0.920000,0.859813,0.192982,0.080000,0.807277
24,248.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000000,1.000000,0.940000,0.969072,0.000000,0.060000,0.444186
26,251.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,1.792757
27,average,0.694615,0.694615,0.305385,0.010984,0.856266,0.694615,0.713864,0.143734,0.305385,0.578917

In [233]:
Confusion_df30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier30.csv')
eval_result30.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier30.csv', index=False)

## LOAD & APPLY MODEL dTOP40fi

In [234]:
# test_data40['tp_ICD_cl0'] = le.transform(test_data40['tp_ICD_cl0'])

In [235]:
# Separate features and tp_ICD_cl0 variable for test_data40
X_test40 = test_data40.drop(labels=['tp_ICD_cl0'], axis=1)
y_test40 = test_data40['tp_ICD_cl0']

In [236]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier40.pkl', 'rb') as f:
    knn_40 = pickle.load(f)

### EVALUATION & SAVE

In [237]:
prob40 = knn_40.predict_proba(X_test40)
classes40 = knn_40.classes_

y_pred40, data_top_5 = get_predictions(prob40, classes40, threshold, 10, np.array(y_test40), le)

Confusion_df40 = pd.DataFrame(confusion_matrix(np.array(y_test40), y_pred40))
Confusion_df40.index, Confusion_df40.columns = le.inverse_transform(classes40), le.inverse_transform(classes40)

eval_result40 = calculate_evaluation_metrics(Confusion_df=Confusion_df40)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [238]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.380952,41.0,0.190476,151.0,0.095238,98.9,0.047619,104.1,0.047619
2,185.9,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
3,248.0,248.0,0.523810,249.0,0.238095,251.0,0.238095,NaN,NaN,NaN,NaN
4,146.0,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
5,251.0,251.0,0.380952,248.0,0.285714,249.0,0.285714,104.1,0.047619,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
2597,18.9,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
2598,217.0,98.9,0.380952,7.1,0.285714,147.0,0.095238,104.1,0.047619,146.0,0.047619
2599,104.1,5.0,0.142857,7.1,0.095238,128.0,0.095238,129.0,0.095238,146.0,0.095238
2600,251.0,251.0,0.380952,248.0,0.285714,249.0,0.285714,104.1,0.047619,NaN,NaN

In [239]:
Confusion_df40.index = Confusion_df40.index + 1
Confusion_df40
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,87,0,1,0,0,0,0,0,0,0,...,4,1,0,0,1,0,0,0,0,0
8.1,0,79,2,0,2,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
19.9,60,0,21,2,3,1,0,0,0,0,...,8,0,0,0,0,0,0,0,0,0
33.1,0,0,0,94,0,0,1,0,1,0,...,3,0,0,0,0,1,0,0,0,0
42.0,15,0,0,0,78,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,0,0,1,84,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
105.1,2,1,0,2,0,0,88,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112.0,50,0,0,0,2,0,0,37,0,0,...,0,0,1,0,0,0,0,0,0,0
129.0,0,0,1,0,0,0,0,0,97,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,1,0,0,0,0,0,0,0,95,...,0,0,0,0,0,0,0,0,0,1
147.0,0,0,0,0,2,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
148.0,0,0,2,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
151.0,57,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152.0,31,0,1,0,0,1,0,0,1,0,...,4,0,0,0,0,0,0,0,0,0
154.0,49,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,65,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162.0,4,0,1,0,0,0,0,0,0,0,...,87,0,1,0,0,0,0,0,0,0
170.0,33,0,0,2,1,0,0,0,0,0,...,7,39,0,0,0,0,0,0,0,1
186.9,0,0,1,0,2,0,0,0,6,0,...,8,0,72,0,0,0,0,0,0,0
198.0,48,0,0,1,0,0,0,0,0,0,...,7,0,0,15,0,0,0,0,0,0
213.9,49,0,1,0,1,0,1,0,1,1,...,1,0,0,1,39,0,0,0,0,0
218.0,54,0,1,2,0,2,0,0,1,0,...,1,0,0,0,0,33,0,0,0,0
240.2,87,0,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [240]:
eval_result40.index = eval_result40.index + 1
eval_result40

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.870,0.870,0.130,0.195106,0.125541,0.870,0.219420,0.874459,0.130,0.442004
2,7.1,0.790,0.790,0.210,0.000799,0.975309,0.790,0.872928,0.024691,0.210,0.429029
3,18.9,0.210,0.210,0.790,0.006754,0.552632,0.210,0.304348,0.447368,0.790,1.000000
4,32.1,0.940,0.940,0.060,0.003587,0.912621,0.940,0.926108,0.087379,0.060,0.444322
5,41.0,0.780,0.780,0.220,0.005569,0.847826,0.780,0.812500,0.152174,0.220,1.584817
6,98.9,0.840,0.840,0.160,0.001597,0.954545,0.840,0.893617,0.045455,0.160,0.460162
7,104.1,0.880,0.880,0.120,0.000799,0.977778,0.880,0.926316,0.022222,0.120,0.709548
8,111.0,0.370,0.370,0.630,0.000000,1.000000,0.370,0.540146,0.000000,0.630,0.999961
9,128.0,0.970,0.970,0.030,0.005569,0.873874,0.970,0.919431,0.126126,0.030,1.280627
10,129.0,0.950,0.950,0.050,0.000799,0.979381,0.950,0.964467,0.020619,0.050,0.520964
11,146.0,0.940,0.940,0.060,0.010293,0.783333,0.940,0.854545,0.216667,0.060,0.529352
12,147.0,0.920,0.920,0.080,0.030632,0.538012,0.920,0.678967,0.461988,0.080,0.611396
13,150.0,0.380,0.380,0.620,0.018453,0.447059,0.380,0.410811,0.552941,0.620,0.999999
14,151.0,0.560,0.560,0.440,0.003190,0.875000,0.560,0.682927,0.125000,0.440,0.255958
15,153.0,0.300,0.300,0.700,0.001996,0.857143,0.300,0.444444,0.142857,0.700,0.999999
16,154.0,0.320,0.320,0.680,0.011076,0.533333,0.320,0.400000,0.466667,0.680,0.387762
17,161.0,0.870,0.870,0.130,0.019608,0.635036,0.870,0.734177,0.364964,0.130,1.274017
18,169.0,0.390,0.390,0.610,0.000400,0.975000,0.390,0.557143,0.025000,0.610,0.248583
19,185.9,0.720,0.720,0.280,0.000799,0.972973,0.720,0.827586,0.027027,0.280,0.440911
20,197.0,0.150,0.150,0.850,0.000400,0.937500,0.150,0.258621,0.062500,0.850,1.000000
21,212.9,0.390,0.390,0.610,0.000400,0.975000,0.390,0.557143,0.025000,0.610,0.999603
22,217.0,0.330,0.330,0.670,0.000400,0.970588,0.330,0.492537,0.029412,0.670,1.000000
23,239.2,0.010,0.010,0.990,0.000000,1.000000,0.010,0.019802,0.000000,0.990,0.424349
24,248.0,1.000,1.000,0.000,0.000400,0.990099,1.000,0.995025,0.009901,0.000,0.000000
25,249.0,0.940,0.940,0.060,0.000000,1.000000,0.940,0.969072,0.000000,0.060,0.444186
26,251.0,0.950,0.950,0.050,0.001199,0.969388,0.950,0.959596,0.030612,0.050,1.595567
27,average,0.645,0.645,0.355,0.012301,0.833037,0.645,0.662372,0.166963,0.355,0.733966

In [241]:
Confusion_df40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier40.csv')
eval_result40.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier40.csv', index=False)

## LOAD & APPLY MODEL dTOP50fi

In [242]:
# test_data50['tp_ICD_cl0'] = le.transform(test_data50['tp_ICD_cl0'])

In [243]:
# Separate features and tp_ICD_cl0 variable for test_data50
X_test50 = test_data50.drop(labels=['tp_ICD_cl0'], axis=1)
y_test50 = test_data50['tp_ICD_cl0']

In [244]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier50.pkl', 'rb') as f:
    knn_50 = pickle.load(f)

### EVALUATION & SAVE

In [245]:
prob50 = knn_50.predict_proba(X_test50)
classes50 = knn_50.classes_

y_pred50, data_top_5 = get_predictions(prob50, classes50, threshold, 10, np.array(y_test50), le)

Confusion_df50 = pd.DataFrame(confusion_matrix(np.array(y_test50), y_pred50))
Confusion_df50.index, Confusion_df50.columns = le.inverse_transform(classes50), le.inverse_transform(classes50)

eval_result50 = calculate_evaluation_metrics(Confusion_df=Confusion_df50)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [246]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.190476,161.0,0.142857,18.9,0.095238,98.9,0.095238,146.0,0.095238
2,185.9,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
3,248.0,248.0,0.666667,251.0,0.190476,249.0,0.142857,NaN,NaN,NaN,NaN
4,146.0,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
5,251.0,251.0,0.428571,248.0,0.333333,249.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
2597,18.9,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
2598,217.0,98.9,0.333333,7.1,0.190476,104.1,0.095238,146.0,0.095238,147.0,0.047619
2599,104.1,239.2,0.190476,153.0,0.142857,5.0,0.095238,104.1,0.095238,154.0,0.095238
2600,251.0,251.0,0.428571,248.0,0.333333,249.0,0.238095,NaN,NaN,NaN,NaN

In [247]:
Confusion_df50.index = Confusion_df50.index + 1
Confusion_df50
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,84,0,2,3,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,1,68,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,24,0,0,1
19.9,1,0,91,0,1,1,0,0,0,1,...,2,0,0,0,0,0,0,0,0,0
33.1,0,0,4,92,0,0,2,0,1,0,...,1,0,0,0,0,0,0,0,0,0
42.0,0,0,0,1,76,0,0,0,0,0,...,2,0,0,0,0,0,15,0,0,0
99.9,0,0,1,0,1,38,0,0,0,0,...,2,0,0,0,0,0,51,0,0,0
105.1,1,1,0,2,3,2,78,0,0,7,...,1,0,0,0,0,0,0,0,0,0
112.0,1,0,0,1,2,0,0,27,1,0,...,0,0,0,0,0,0,50,0,0,0
129.0,0,0,0,0,0,0,0,0,86,0,...,0,0,0,0,0,0,11,0,0,0
130.0,0,1,0,0,0,0,0,0,0,90,...,0,0,0,0,0,0,0,0,0,1
147.0,0,0,0,0,2,0,0,0,4,0,...,1,0,0,0,0,0,39,0,0,0
148.0,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
151.0,2,0,2,0,4,0,0,0,3,0,...,1,0,0,0,0,0,0,0,0,0
152.0,0,0,0,1,2,1,0,0,1,1,...,5,0,0,0,0,0,31,0,0,0
154.0,0,0,0,3,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,0,0,0,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162.0,0,0,0,4,0,0,0,0,0,4,...,84,0,1,0,0,0,3,0,0,0
170.0,2,0,1,2,1,0,0,0,0,5,...,0,42,0,0,0,0,32,0,0,1
186.9,0,0,0,4,4,0,0,0,0,6,...,0,0,26,0,0,0,56,0,0,0
198.0,3,0,0,0,0,0,0,0,0,6,...,1,0,0,33,0,0,46,0,0,0
213.9,1,0,1,2,2,0,0,0,6,2,...,1,0,1,1,32,0,48,0,0,0
218.0,0,0,0,0,0,0,0,0,1,1,...,0,0,0,1,0,33,54,0,0,0
240.2,0,0,1,2,1,0,0,0,0,0,...,0,0,0,0,0,0,96,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [248]:
eval_result50.index = eval_result50.index + 1
eval_result50

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.840000,0.840000,0.160000,0.005569,0.857143,0.840000,0.848485,0.142857,0.160000,0.506157
2,7.1,0.680000,0.680000,0.320000,0.000799,0.971429,0.680000,0.800000,0.028571,0.320000,0.345687
3,18.9,0.910000,0.910000,0.090000,0.005569,0.866667,0.910000,0.887805,0.133333,0.090000,0.862005
4,32.1,0.920000,0.920000,0.080000,0.011467,0.760331,0.920000,0.832579,0.239669,0.080000,0.798607
5,41.0,0.760000,0.760000,0.240000,0.009901,0.752475,0.760000,0.756219,0.247525,0.240000,0.345784
6,98.9,0.380000,0.380000,0.620000,0.001597,0.904762,0.380000,0.535211,0.095238,0.620000,0.218131
7,104.1,0.780000,0.780000,0.220000,0.001199,0.962963,0.780000,0.861878,0.037037,0.220000,0.511920
8,111.0,0.270000,0.270000,0.730000,0.000400,0.964286,0.270000,0.421875,0.035714,0.730000,0.218104
9,128.0,0.860000,0.860000,0.140000,0.007937,0.811321,0.860000,0.834951,0.188679,0.140000,0.345977
10,129.0,0.900000,0.900000,0.100000,0.013028,0.731707,0.900000,0.807175,0.268293,0.100000,0.404900
11,146.0,0.540000,0.540000,0.460000,0.004381,0.830769,0.540000,0.654545,0.169231,0.460000,0.278944
12,147.0,0.950000,0.950000,0.050000,0.005964,0.863636,0.950000,0.904762,0.136364,0.050000,0.484550
13,150.0,0.840000,0.840000,0.160000,0.000000,1.000000,0.840000,0.913043,0.000000,0.160000,0.749130
14,151.0,0.510000,0.510000,0.490000,0.019608,0.504950,0.510000,0.507463,0.495050,0.490000,0.255958
15,153.0,0.920000,0.920000,0.080000,0.024581,0.593548,0.920000,0.721569,0.406452,0.080000,0.728476
16,154.0,0.830000,0.830000,0.170000,0.002394,0.932584,0.830000,0.878307,0.067416,0.170000,0.498603
17,161.0,0.840000,0.840000,0.160000,0.007149,0.823529,0.840000,0.831683,0.176471,0.160000,0.630267
18,169.0,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,0.235477
19,185.9,0.260000,0.260000,0.740000,0.000799,0.928571,0.260000,0.406250,0.071429,0.740000,0.218104
20,197.0,0.330000,0.330000,0.670000,0.000799,0.942857,0.330000,0.488889,0.057143,0.670000,0.218115
21,212.9,0.320000,0.320000,0.680000,0.000000,1.000000,0.320000,0.484848,0.000000,0.680000,0.218106
22,217.0,0.330000,0.330000,0.670000,0.000000,1.000000,0.330000,0.496241,0.000000,0.670000,0.218104
23,239.2,0.960000,0.960000,0.040000,0.155405,0.172662,0.960000,0.292683,0.827338,0.040000,1.075303
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000400,0.989474,0.940000,0.964103,0.010526,0.060000,0.420959
26,251.0,0.950000,0.950000,0.050000,0.001199,0.969388,0.950000,0.959596,0.030612,0.050000,1.594649
27,average,0.701538,0.701538,0.298462,0.010775,0.851348,0.701538,0.718527,0.148652,0.298462,0.476231

In [249]:
Confusion_df50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier50.csv')
eval_result50.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier50.csv', index=False)

## LOAD & APPLY MODEL dTOP60fi

In [250]:
# test_data60['tp_ICD_cl0'] = le.transform(test_data60['tp_ICD_cl0'])

In [251]:
# Separate features and tp_ICD_cl0 variable for test_data60
X_test60 = test_data60.drop(labels=['tp_ICD_cl0'], axis=1)
y_test60 = test_data60['tp_ICD_cl0']

In [252]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier60.pkl', 'rb') as f:
    knn_60 = pickle.load(f)

### EVALUATION & SAVE

In [253]:
prob60 = knn_60.predict_proba(X_test60)
classes60 = knn_60.classes_

y_pred60, data_top_5 = get_predictions(prob60, classes60, threshold, 10, np.array(y_test60), le)

Confusion_df60 = pd.DataFrame(confusion_matrix(np.array(y_test60), y_pred60))
Confusion_df60.index, Confusion_df60.columns = le.inverse_transform(classes60), le.inverse_transform(classes60)

eval_result60 = calculate_evaluation_metrics(Confusion_df=Confusion_df60)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [254]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.238095,169.0,0.142857,111.0,0.095238,151.0,0.095238,212.9,0.095238
2,185.9,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
3,248.0,248.0,0.619048,249.0,0.238095,251.0,0.142857,NaN,NaN,NaN,NaN
4,146.0,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
5,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
2597,18.9,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
2598,217.0,98.9,0.333333,7.1,0.190476,104.1,0.095238,146.0,0.095238,147.0,0.095238
2599,104.1,18.9,0.190476,111.0,0.190476,5.0,0.095238,129.0,0.095238,150.0,0.095238
2600,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN

In [255]:
Confusion_df60.index = Confusion_df60.index + 1
Confusion_df60
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,96,0,0,0,2,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8.1,0,67,24,0,1,2,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
19.9,0,0,85,2,4,2,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
33.1,0,0,0,95,2,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,12,0,85,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99.9,0,0,51,0,1,37,0,0,0,0,...,3,0,0,0,0,4,0,0,0,0
105.1,0,1,41,1,6,0,21,2,0,1,...,2,0,0,0,0,3,0,0,0,0
112.0,0,0,0,0,0,1,0,94,1,0,...,0,0,0,2,0,0,0,0,0,0
129.0,0,0,11,0,0,0,0,0,86,0,...,1,0,0,0,0,0,0,0,0,0
130.0,1,1,0,0,0,0,0,1,0,93,...,0,0,0,0,0,0,0,0,1,0
147.0,0,0,0,0,2,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
148.0,0,0,31,0,3,0,0,0,0,0,...,1,0,0,0,0,3,0,0,0,0
151.0,0,0,0,1,0,0,0,0,0,0,...,0,1,1,0,0,4,0,0,0,0
152.0,0,0,30,2,1,1,0,0,1,0,...,0,0,0,0,0,5,0,0,0,0
154.0,0,0,0,0,3,1,0,0,1,0,...,0,0,0,3,0,5,0,0,0,0
155.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,5,0,0,0,0
162.0,0,0,1,2,0,0,0,0,0,1,...,88,0,0,0,0,4,0,0,0,0
170.0,2,0,32,0,3,0,1,1,0,0,...,0,46,0,0,0,0,1,0,1,0
186.9,0,0,53,0,0,0,0,1,6,2,...,3,0,28,0,0,4,0,0,0,0
198.0,1,0,46,0,2,0,0,0,0,0,...,5,0,1,40,0,5,0,0,0,0
213.9,0,0,47,0,2,0,0,0,1,0,...,2,0,1,1,16,2,0,0,0,0
218.0,0,0,51,0,1,0,0,0,1,0,...,0,0,0,1,1,39,0,0,0,0
240.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,5,94,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,96

In [256]:
eval_result60.index = eval_result60.index + 1
eval_result60

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.960000,0.960000,0.040000,0.002394,0.941176,0.960000,0.950495,0.058824,0.040000,0.383678
2,7.1,0.670000,0.670000,0.330000,0.000799,0.971014,0.670000,0.792899,0.028986,0.330000,0.792481
3,18.9,0.850000,0.850000,0.150000,0.146758,0.165049,0.850000,0.276423,0.834951,0.150000,0.647742
4,32.1,0.950000,0.950000,0.050000,0.003190,0.922330,0.950000,0.935961,0.077670,0.050000,0.652257
5,41.0,0.850000,0.850000,0.150000,0.013028,0.720339,0.850000,0.779817,0.279661,0.150000,0.792444
6,98.9,0.370000,0.370000,0.630000,0.002792,0.840909,0.370000,0.513889,0.159091,0.630000,0.500002
7,104.1,0.210000,0.210000,0.790000,0.000400,0.954545,0.210000,0.344262,0.045455,0.790000,0.500000
8,111.0,0.940000,0.940000,0.060000,0.001996,0.949495,0.940000,0.944724,0.050505,0.060000,0.605381
9,128.0,0.860000,0.860000,0.140000,0.005569,0.860000,0.860000,0.860000,0.140000,0.140000,0.792649
10,129.0,0.930000,0.930000,0.070000,0.001996,0.948980,0.930000,0.939394,0.051020,0.070000,0.750981
11,146.0,0.960000,0.960000,0.040000,0.036237,0.505263,0.960000,0.662069,0.494737,0.040000,0.763198
12,147.0,0.610000,0.610000,0.390000,0.007937,0.753086,0.610000,0.674033,0.246914,0.390000,0.270238
13,150.0,0.870000,0.870000,0.130000,0.000799,0.977528,0.870000,0.920635,0.022472,0.130000,0.472996
14,151.0,0.590000,0.590000,0.410000,0.001597,0.936508,0.590000,0.723926,0.063492,0.410000,0.255958
15,153.0,0.720000,0.720000,0.280000,0.007543,0.791209,0.720000,0.753927,0.208791,0.280000,0.442350
16,154.0,0.880000,0.880000,0.120000,0.000400,0.988764,0.880000,0.931217,0.011236,0.120000,0.423991
17,161.0,0.880000,0.880000,0.120000,0.007937,0.814815,0.880000,0.846154,0.185185,0.120000,0.512389
18,169.0,0.460000,0.460000,0.540000,0.000400,0.978723,0.460000,0.625850,0.021277,0.540000,0.235430
19,185.9,0.280000,0.280000,0.720000,0.001199,0.903226,0.280000,0.427481,0.096774,0.720000,0.500000
20,197.0,0.400000,0.400000,0.600000,0.003190,0.833333,0.400000,0.540541,0.166667,0.600000,0.498642
21,212.9,0.160000,0.160000,0.840000,0.000400,0.941176,0.160000,0.273504,0.058824,0.840000,0.500000
22,217.0,0.390000,0.390000,0.610000,0.019223,0.443182,0.390000,0.414894,0.556818,0.610000,0.499977
23,239.2,0.940000,0.940000,0.060000,0.000400,0.989474,0.940000,0.964103,0.010526,0.060000,0.361245
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.458345
26,251.0,0.960000,0.960000,0.040000,0.000000,1.000000,0.960000,0.979592,0.000000,0.040000,1.479315
27,average,0.716538,0.716538,0.283462,0.010284,0.849969,0.716538,0.731927,0.150031,0.283462,0.541988

In [257]:
Confusion_df60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier60.csv')
eval_result60.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier60.csv', index=False)

## LOAD & APPLY MODEL dTOP70fi

In [258]:
# test_data70['tp_ICD_cl0'] = le.transform(test_data70['tp_ICD_cl0'])

In [259]:
# Separate features and tp_ICD_cl0 variable for test_data70
X_test70 = test_data70.drop(labels=['tp_ICD_cl0'], axis=1)
y_test70 = test_data70['tp_ICD_cl0']

In [260]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier70.pkl', 'rb') as f:
    knn_70 = pickle.load(f)

### EVALUATION & SAVE

In [261]:
prob70 = knn_70.predict_proba(X_test70)
classes70 = knn_70.classes_

y_pred70, data_top_5 = get_predictions(prob70, classes70, threshold, 10, np.array(y_test70), le)

Confusion_df70 = pd.DataFrame(confusion_matrix(np.array(y_test70), y_pred70))
Confusion_df70.index, Confusion_df70.columns = le.inverse_transform(classes70), le.inverse_transform(classes70)

eval_result70 = calculate_evaluation_metrics(Confusion_df=Confusion_df70)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [262]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,150.0,0.142857,161.0,0.142857,41.0,0.095238,98.9,0.095238,111.0,0.095238
2,185.9,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
3,248.0,248.0,0.666667,249.0,0.142857,251.0,0.142857,197.0,0.047619,NaN,NaN
4,146.0,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
5,251.0,249.0,0.476190,248.0,0.238095,251.0,0.238095,104.1,0.047619,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
2597,18.9,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
2598,217.0,98.9,0.333333,7.1,0.190476,104.1,0.095238,146.0,0.095238,147.0,0.095238
2599,104.1,197.0,0.238095,111.0,0.142857,18.9,0.095238,98.9,0.095238,129.0,0.095238
2600,251.0,249.0,0.476190,248.0,0.238095,251.0,0.238095,104.1,0.047619,NaN,NaN

In [263]:
Confusion_df70.index = Confusion_df70.index + 1
Confusion_df70
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,93,0,0,0,0,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,0
8.1,1,75,2,0,1,2,0,0,1,0,...,1,0,0,12,0,0,0,0,1,0
19.9,0,0,86,2,2,2,0,0,0,2,...,3,0,0,1,0,0,0,0,0,0
33.1,0,0,0,96,0,0,1,0,1,0,...,1,0,0,0,0,1,0,0,0,0
42.0,1,1,1,0,82,1,0,0,0,0,...,1,0,0,11,0,0,0,0,0,0
99.9,2,0,0,1,0,86,0,0,0,2,...,0,0,0,5,0,0,0,0,0,0
105.1,0,3,2,1,3,4,76,0,0,6,...,3,0,0,0,0,1,0,0,0,0
112.0,0,6,0,0,2,5,0,83,1,0,...,0,0,0,0,0,0,0,0,0,0
129.0,0,0,0,0,1,0,0,0,86,0,...,0,0,0,12,0,0,0,0,0,0
130.0,1,7,3,0,0,0,0,0,0,87,...,0,0,0,0,0,0,0,0,1,0
147.0,0,0,0,0,2,0,0,0,0,2,...,1,0,0,0,0,0,0,0,0,0
148.0,0,0,1,0,3,0,0,0,0,0,...,1,0,0,31,0,0,0,0,0,0
151.0,1,4,2,1,3,0,0,0,3,0,...,2,0,0,64,0,0,0,0,0,0
152.0,1,5,1,0,2,3,0,0,1,1,...,0,0,0,30,0,0,0,0,0,0
154.0,0,5,0,0,0,2,0,0,1,4,...,0,0,0,48,0,0,0,0,0,0
155.0,2,0,0,0,0,1,0,0,0,0,...,0,0,0,62,0,0,0,0,0,0
162.0,0,3,0,4,0,0,0,0,0,5,...,86,0,1,1,0,0,0,0,0,0
170.0,3,3,2,2,0,1,0,0,0,3,...,0,39,0,42,0,0,1,0,1,0
186.9,1,4,4,0,2,1,0,0,6,0,...,0,0,26,53,0,0,0,0,0,0
198.0,3,5,1,0,1,1,0,0,0,0,...,1,0,0,85,0,0,0,0,0,0
213.9,1,1,1,0,1,0,0,0,1,2,...,1,0,1,46,42,0,0,0,0,0
218.0,0,0,1,0,0,4,0,0,1,1,...,1,0,0,65,0,27,0,0,0,0
240.2,0,0,3,0,0,0,0,0,0,0,...,0,0,0,80,0,0,16,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,5,0,0,0,0,94,0
252.0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [264]:
eval_result70.index = eval_result70.index + 1
eval_result70

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.930000,0.930000,0.070000,0.007543,0.830357,0.930000,0.877358,0.169643,0.070000,0.337963
2,7.1,0.750000,0.750000,0.250000,0.018453,0.614754,0.750000,0.675676,0.385246,0.250000,0.362265
3,18.9,0.860000,0.860000,0.140000,0.009509,0.781818,0.860000,0.819048,0.218182,0.140000,0.673627
4,32.1,0.960000,0.960000,0.040000,0.004381,0.897196,0.960000,0.927536,0.102804,0.040000,0.700678
5,41.0,0.820000,0.820000,0.180000,0.009116,0.780952,0.820000,0.800000,0.219048,0.180000,0.362589
6,98.9,0.860000,0.860000,0.140000,0.010685,0.761062,0.860000,0.807512,0.238938,0.140000,0.528867
7,104.1,0.760000,0.760000,0.240000,0.000400,0.987013,0.760000,0.858757,0.012987,0.240000,0.611221
8,111.0,0.830000,0.830000,0.170000,0.000000,1.000000,0.830000,0.907104,0.000000,0.170000,0.923457
9,128.0,0.860000,0.860000,0.140000,0.006754,0.834951,0.860000,0.847291,0.165049,0.140000,0.360988
10,129.0,0.870000,0.870000,0.130000,0.011076,0.756522,0.870000,0.809302,0.243478,0.130000,1.011932
11,146.0,0.920000,0.920000,0.080000,0.003984,0.901961,0.920000,0.910891,0.098039,0.080000,0.580279
12,147.0,0.610000,0.610000,0.390000,0.003984,0.859155,0.610000,0.713450,0.140845,0.390000,0.270238
13,150.0,0.190000,0.190000,0.810000,0.003190,0.703704,0.190000,0.299213,0.296296,0.810000,0.416325
14,151.0,0.560000,0.560000,0.440000,0.000400,0.982456,0.560000,0.713376,0.017544,0.440000,0.255958
15,153.0,0.370000,0.370000,0.630000,0.006754,0.685185,0.370000,0.480519,0.314815,0.630000,0.227722
16,154.0,0.330000,0.330000,0.670000,0.000400,0.970588,0.330000,0.492537,0.029412,0.670000,0.227670
17,161.0,0.860000,0.860000,0.140000,0.006359,0.843137,0.860000,0.851485,0.156863,0.140000,0.672675
18,169.0,0.390000,0.390000,0.610000,0.000000,1.000000,0.390000,0.561151,0.000000,0.610000,0.238302
19,185.9,0.260000,0.260000,0.740000,0.000799,0.928571,0.260000,0.406250,0.071429,0.740000,0.227670
20,197.0,0.850000,0.850000,0.150000,0.186463,0.129179,0.850000,0.224274,0.870821,0.150000,1.154015
21,212.9,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,0.232517
22,217.0,0.270000,0.270000,0.730000,0.000799,0.931034,0.270000,0.418605,0.068966,0.730000,0.350379
23,239.2,0.160000,0.160000,0.840000,0.000400,0.941176,0.160000,0.273504,0.058824,0.840000,0.345748
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.374948
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,1.329936
27,average,0.676154,0.676154,0.323846,0.011271,0.849229,0.676154,0.699619,0.150771,0.323846,0.491460

In [265]:
Confusion_df70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier70.csv')
eval_result70.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier70.csv', index=False)

## LOAD & APPLY MODEL dTOP80fi

In [266]:
# test_data80['tp_ICD_cl0'] = le.transform(test_data80['tp_ICD_cl0'])

In [267]:
# Separate features and tp_ICD_cl0 variable for test_data80
X_test80 = test_data80.drop(labels=['tp_ICD_cl0'], axis=1)
y_test80 = test_data80['tp_ICD_cl0']

In [268]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier80.pkl', 'rb') as f:
    knn_80 = pickle.load(f)

### EVALUATION & SAVE

In [269]:
prob80 = knn_80.predict_proba(X_test80)
classes80 = knn_80.classes_

y_pred80, data_top_5 = get_predictions(prob80, classes80, threshold, 10, np.array(y_test80), le)

Confusion_df80 = pd.DataFrame(confusion_matrix(np.array(y_test80), y_pred80))
Confusion_df80.index, Confusion_df80.columns = le.inverse_transform(classes80), le.inverse_transform(classes80)

eval_result80 = calculate_evaluation_metrics(Confusion_df=Confusion_df80)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [270]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.4,41.0,0.10,146.0,0.1,212.9,0.1,104.1,0.05
2,185.9,18.9,0.1,129.0,0.10,150.0,0.1,154.0,0.1,197.0,0.10
3,248.0,248.0,0.5,197.0,0.15,146.0,0.1,212.9,0.1,98.9,0.05
4,146.0,18.9,0.1,129.0,0.10,150.0,0.1,154.0,0.1,197.0,0.10
5,251.0,248.0,0.4,251.0,0.40,249.0,0.2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,18.9,0.1,129.0,0.10,150.0,0.1,154.0,0.1,197.0,0.10
2597,18.9,18.9,0.1,129.0,0.10,150.0,0.1,154.0,0.1,197.0,0.10
2598,217.0,98.9,0.3,7.1,0.20,147.0,0.2,151.0,0.1,104.1,0.05
2599,104.1,18.9,0.1,129.0,0.10,150.0,0.1,154.0,0.1,197.0,0.10
2600,251.0,248.0,0.4,251.0,0.40,249.0,0.2,NaN,NaN,NaN,NaN

In [271]:
Confusion_df80.index = Confusion_df80.index + 1
Confusion_df80
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,87,0,5,3,0,0,0,1,0,1,...,2,0,1,0,0,0,0,0,0,0
8.1,1,77,0,2,1,0,0,0,1,0,...,1,0,0,12,0,0,0,1,0,0
19.9,1,1,82,1,1,0,0,1,0,1,...,5,1,1,1,0,0,0,0,0,0
33.1,0,0,0,95,0,0,1,2,1,0,...,0,0,0,0,0,1,0,0,0,0
42.0,1,0,12,0,83,0,0,0,0,2,...,0,0,0,1,0,0,0,0,0,0
99.9,0,0,0,2,0,84,0,0,1,0,...,3,0,0,5,0,0,0,0,0,0
105.1,0,0,46,3,0,0,33,7,6,0,...,0,0,0,0,0,0,0,0,0,0
112.0,1,0,55,1,2,1,2,25,1,1,...,0,0,0,10,0,0,0,0,0,0
129.0,0,0,11,0,0,1,0,0,86,1,...,0,0,0,1,0,0,0,0,0,0
130.0,0,1,6,0,0,0,0,0,0,92,...,0,0,0,0,0,0,0,1,0,0
147.0,0,0,40,0,2,0,0,3,4,0,...,1,0,0,0,0,0,0,0,0,0
148.0,0,0,31,0,3,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
151.0,1,0,4,1,3,0,0,0,3,1,...,1,0,0,8,0,0,0,0,0,0
152.0,1,0,30,1,9,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
154.0,0,0,48,0,0,0,0,3,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,2,0,0,4,1,0,1,4,0,0,...,0,0,0,4,0,0,0,0,0,0
162.0,0,0,3,2,0,0,0,1,0,0,...,90,0,1,0,0,0,0,0,0,0
170.0,3,0,35,3,0,0,1,3,0,3,...,0,38,1,11,0,0,1,1,0,0
186.9,1,0,54,4,2,0,0,5,6,0,...,0,0,23,3,0,0,0,0,0,0
198.0,3,0,6,0,3,0,0,0,0,0,...,1,0,0,86,0,0,0,0,0,0
213.9,1,0,1,1,0,1,0,1,6,0,...,0,0,1,0,84,0,0,0,0,0
218.0,0,0,59,1,0,0,1,2,0,0,...,1,0,0,0,0,32,0,0,0,0
240.2,0,0,85,0,0,0,0,1,0,0,...,0,0,0,0,0,0,14,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,99,0
252.0,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [272]:
eval_result80.index = eval_result80.index + 1
eval_result80

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.870000,0.870000,0.130000,0.006359,0.844660,0.870000,0.857143,0.155340,0.130000,0.780689
2,7.1,0.770000,0.770000,0.230000,0.000799,0.974684,0.770000,0.860335,0.025316,0.230000,0.361935
3,18.9,0.820000,0.820000,0.180000,0.175734,0.133333,0.820000,0.229371,0.866667,0.180000,0.511431
4,32.1,0.950000,0.950000,0.050000,0.011467,0.766129,0.950000,0.848214,0.233871,0.050000,0.620339
5,41.0,0.830000,0.830000,0.170000,0.010685,0.754545,0.830000,0.790476,0.245455,0.170000,0.792737
6,98.9,0.840000,0.840000,0.160000,0.001597,0.954545,0.840000,0.893617,0.045455,0.160000,0.452815
7,104.1,0.330000,0.330000,0.670000,0.002394,0.846154,0.330000,0.474820,0.153846,0.670000,0.500002
8,111.0,0.250000,0.250000,0.750000,0.013418,0.423729,0.250000,0.314465,0.576271,0.750000,0.500000
9,128.0,0.860000,0.860000,0.140000,0.012638,0.728814,0.860000,0.788991,0.271186,0.140000,0.792729
10,129.0,0.920000,0.920000,0.080000,0.003984,0.901961,0.920000,0.910891,0.098039,0.080000,0.807908
11,146.0,0.490000,0.490000,0.510000,0.005173,0.790323,0.490000,0.604938,0.209677,0.510000,0.279575
12,147.0,0.620000,0.620000,0.380000,0.006359,0.794872,0.620000,0.696629,0.205128,0.380000,0.270238
13,150.0,0.760000,0.760000,0.240000,0.000000,1.000000,0.760000,0.863636,0.000000,0.240000,0.414828
14,151.0,0.560000,0.560000,0.440000,0.001597,0.933333,0.560000,0.700000,0.066667,0.440000,0.255958
15,153.0,0.460000,0.460000,0.540000,0.006359,0.741935,0.460000,0.567901,0.258065,0.540000,0.485864
16,154.0,0.770000,0.770000,0.230000,0.000400,0.987179,0.770000,0.865169,0.012821,0.230000,0.648766
17,161.0,0.900000,0.900000,0.100000,0.007149,0.833333,0.900000,0.865385,0.166667,0.100000,0.839994
18,169.0,0.380000,0.380000,0.620000,0.000400,0.974359,0.380000,0.546763,0.025641,0.620000,0.276131
19,185.9,0.230000,0.230000,0.770000,0.001996,0.821429,0.230000,0.359375,0.178571,0.770000,0.500000
20,197.0,0.860000,0.860000,0.140000,0.021909,0.605634,0.860000,0.710744,0.394366,0.140000,0.901839
21,212.9,0.840000,0.840000,0.160000,0.000000,1.000000,0.840000,0.913043,0.000000,0.160000,0.535845
22,217.0,0.320000,0.320000,0.680000,0.000400,0.969697,0.320000,0.481203,0.030303,0.680000,0.500000
23,239.2,0.140000,0.140000,0.860000,0.000400,0.933333,0.140000,0.243478,0.066667,0.860000,0.345686
24,248.0,1.000000,1.000000,0.000000,0.001597,0.961538,1.000000,0.980392,0.038462,0.000000,0.000000
25,249.0,0.990000,0.990000,0.010000,0.000000,1.000000,0.990000,0.994975,0.000000,0.010000,0.000000
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,0.798674
27,average,0.681154,0.681154,0.318846,0.011262,0.833674,0.681154,0.705243,0.166326,0.318846,0.506692

In [273]:
Confusion_df80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier80.csv')
eval_result80.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier80.csv', index=False)

## LOAD & APPLY MODEL dTOP90fi

In [274]:
# test_data90['tp_ICD_cl0'] = le.transform(test_data90['tp_ICD_cl0'])

In [275]:
# Separate features and tp_ICD_cl0 variable for test_data90
X_test90 = test_data90.drop(labels=['tp_ICD_cl0'], axis=1)
y_test90 = test_data90['tp_ICD_cl0']

In [276]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier90.pkl', 'rb') as f:
    knn_90 = pickle.load(f)

### EVALUATION & SAVE

In [277]:
prob90 = knn_90.predict_proba(X_test90)
classes90 = knn_90.classes_

y_pred90, data_top_5 = get_predictions(prob90, classes90, threshold, 10, np.array(y_test90), le)

Confusion_df90 = pd.DataFrame(confusion_matrix(np.array(y_test90), y_pred90))
Confusion_df90.index, Confusion_df90.columns = le.inverse_transform(classes90), le.inverse_transform(classes90)

eval_result90 = calculate_evaluation_metrics(Confusion_df=Confusion_df90)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [278]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.380952,161.0,0.190476,169.0,0.142857,18.9,0.095238,98.9,0.047619
2,185.9,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
3,248.0,248.0,0.476190,147.0,0.142857,153.0,0.095238,5.0,0.047619,7.1,0.047619
4,146.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
5,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2597,18.9,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2598,217.0,7.1,0.190476,98.9,0.190476,151.0,0.190476,147.0,0.142857,146.0,0.095238
2599,104.1,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2600,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN

In [279]:
Confusion_df90.index = Confusion_df90.index + 1
Confusion_df90
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,90,0,0,0,0,0,5,1,0,0,...,2,0,0,0,0,0,0,0,0,0
8.1,2,76,0,0,0,2,12,2,1,1,...,1,0,0,0,0,0,0,0,1,0
19.9,0,0,87,2,0,0,1,2,0,1,...,3,0,1,0,0,0,0,0,0,0
33.1,0,0,0,96,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
42.0,1,0,0,0,81,0,0,13,0,1,...,0,0,1,0,0,0,0,0,0,0
99.9,1,0,0,0,2,83,5,1,3,4,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,0,1,1,0,76,2,6,9,...,0,0,3,0,0,0,1,0,0,0
112.0,0,0,0,0,4,1,0,80,0,7,...,0,0,5,0,2,0,0,0,0,0
129.0,0,0,0,0,0,1,1,12,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,1,1,0,0,0,0,0,0,0,93,...,0,0,1,0,0,0,0,0,1,0
147.0,0,0,0,0,5,0,29,38,4,4,...,1,0,0,0,0,0,0,0,0,0
148.0,0,0,0,0,4,0,0,31,0,3,...,1,0,0,0,0,0,0,0,0,0
151.0,2,0,0,0,0,0,0,56,0,0,...,5,0,1,1,0,0,0,0,0,0
152.0,0,0,0,0,0,0,0,30,1,1,...,4,0,2,0,0,0,0,0,0,0
154.0,0,0,0,0,0,0,0,48,1,8,...,0,0,2,0,3,0,0,0,0,0
155.0,0,0,0,0,0,0,4,64,0,4,...,0,0,1,0,1,0,0,0,0,0
162.0,0,0,0,0,0,0,0,2,0,3,...,92,0,1,0,0,1,0,0,0,0
170.0,3,0,0,0,1,0,11,31,0,3,...,0,45,1,0,1,0,1,0,1,0
186.9,1,0,0,0,2,0,2,54,0,0,...,0,0,34,0,0,0,0,0,0,0
198.0,4,0,0,1,2,1,0,0,0,5,...,1,0,0,85,0,0,0,0,0,0
213.9,2,0,0,0,3,0,0,48,1,3,...,1,0,1,1,36,0,1,0,0,0
218.0,0,0,0,0,0,0,0,53,1,10,...,0,0,0,0,0,32,0,0,0,0
240.2,1,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,94,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,5,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [280]:
eval_result90.index = eval_result90.index + 1
eval_result90

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.900000,0.900000,0.100000,0.008723,0.803571,0.900000,0.849057,0.196429,0.100000,0.514183
2,7.1,0.760000,0.760000,0.240000,0.000400,0.987013,0.760000,0.858757,0.012987,0.240000,0.529657
3,18.9,0.870000,0.870000,0.130000,0.000000,1.000000,0.870000,0.930481,0.000000,0.130000,0.618366
4,32.1,0.960000,0.960000,0.040000,0.001597,0.960000,0.960000,0.960000,0.040000,0.040000,0.521246
5,41.0,0.810000,0.810000,0.190000,0.009509,0.771429,0.810000,0.790244,0.228571,0.190000,0.500236
6,98.9,0.830000,0.830000,0.170000,0.001996,0.943182,0.830000,0.882979,0.056818,0.170000,0.613544
7,104.1,0.760000,0.760000,0.240000,0.029126,0.503311,0.760000,0.605578,0.496689,0.240000,0.474910
8,111.0,0.800000,0.800000,0.200000,0.163320,0.140845,0.800000,0.239521,0.859155,0.200000,0.492241
9,128.0,0.860000,0.860000,0.140000,0.007543,0.819048,0.860000,0.839024,0.180952,0.140000,0.500164
10,129.0,0.930000,0.930000,0.070000,0.028749,0.556886,0.930000,0.696629,0.443114,0.070000,0.722491
11,146.0,0.190000,0.190000,0.810000,0.003190,0.703704,0.190000,0.299213,0.296296,0.810000,0.315727
12,147.0,0.610000,0.610000,0.390000,0.010685,0.693182,0.610000,0.648936,0.306818,0.390000,0.270238
13,150.0,0.320000,0.320000,0.680000,0.000000,1.000000,0.320000,0.484848,0.000000,0.680000,0.315465
14,151.0,0.610000,0.610000,0.390000,0.000400,0.983871,0.610000,0.753086,0.016129,0.390000,0.255958
15,153.0,0.370000,0.370000,0.630000,0.000799,0.948718,0.370000,0.532374,0.051282,0.630000,0.315490
16,154.0,0.260000,0.260000,0.740000,0.001199,0.896552,0.260000,0.403101,0.103448,0.740000,0.387762
17,161.0,0.920000,0.920000,0.080000,0.007543,0.828829,0.920000,0.872038,0.171171,0.080000,0.563603
18,169.0,0.450000,0.450000,0.550000,0.000000,1.000000,0.450000,0.620690,0.000000,0.550000,0.235419
19,185.9,0.340000,0.340000,0.660000,0.007937,0.629630,0.340000,0.441558,0.370370,0.660000,0.315465
20,197.0,0.850000,0.850000,0.150000,0.000799,0.977011,0.850000,0.909091,0.022989,0.150000,0.910512
21,212.9,0.360000,0.360000,0.640000,0.002792,0.837209,0.360000,0.503497,0.162791,0.640000,0.315471
22,217.0,0.320000,0.320000,0.680000,0.000400,0.969697,0.320000,0.481203,0.030303,0.680000,0.315465
23,239.2,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.511202
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001597,0.959184,0.940000,0.949495,0.040816,0.060000,0.546813
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,1.673642
27,average,0.688846,0.688846,0.311154,0.011135,0.841613,0.688846,0.710772,0.158387,0.311154,0.489818

In [281]:
Confusion_df90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier90.csv')
eval_result90.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier90.csv', index=False)

## LOAD & APPLY MODEL dTOP100fi

In [282]:
# test_data100['tp_ICD_cl0'] = le.transform(test_data100['tp_ICD_cl0'])

In [283]:
# Separate features and tp_ICD_cl0 variable for test_data100
X_test100 = test_data100.drop(labels=['tp_ICD_cl0'], axis=1)
y_test100 = test_data100['tp_ICD_cl0']

In [284]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier100.pkl', 'rb') as f:
    knn_100 = pickle.load(f)

### EVALUATION & SAVE

In [285]:
prob100 = knn_100.predict_proba(X_test100)
classes100 = knn_100.classes_

y_pred100, data_top_5 = get_predictions(prob100, classes100, threshold, 10, np.array(y_test100), le)

Confusion_df100 = pd.DataFrame(confusion_matrix(np.array(y_test100), y_pred100))
Confusion_df100.index, Confusion_df100.columns = le.inverse_transform(classes100), le.inverse_transform(classes100)

eval_result100 = calculate_evaluation_metrics(Confusion_df=Confusion_df100)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [286]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.380952,161.0,0.190476,169.0,0.142857,18.9,0.095238,98.9,0.047619
2,185.9,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
3,248.0,248.0,0.476190,147.0,0.142857,153.0,0.095238,5.0,0.047619,7.1,0.047619
4,146.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
5,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2597,18.9,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2598,217.0,7.1,0.190476,98.9,0.190476,151.0,0.190476,147.0,0.142857,146.0,0.095238
2599,104.1,111.0,0.142857,197.0,0.142857,239.2,0.095238,5.0,0.047619,7.1,0.047619
2600,251.0,249.0,0.380952,251.0,0.333333,248.0,0.285714,NaN,NaN,NaN,NaN

In [287]:
Confusion_df100.index = Confusion_df100.index + 1
Confusion_df100
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,90,0,0,0,0,0,5,1,0,0,...,2,0,0,0,0,0,0,0,0,0
8.1,2,76,0,0,0,2,12,2,1,1,...,1,0,0,0,0,0,0,0,1,0
19.9,0,0,87,2,0,0,1,2,0,1,...,3,0,1,0,0,0,0,0,0,0
33.1,0,0,0,96,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
42.0,1,0,0,0,81,0,0,13,0,1,...,0,0,1,0,0,0,0,0,0,0
99.9,1,0,0,0,2,83,5,1,3,4,...,0,0,0,0,0,0,0,0,0,0
105.1,0,0,0,1,1,0,76,2,6,9,...,0,0,3,0,0,0,1,0,0,0
112.0,0,0,0,0,4,1,0,80,0,7,...,0,0,5,0,2,0,0,0,0,0
129.0,0,0,0,0,0,1,1,12,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,1,1,0,0,0,0,0,0,0,93,...,0,0,1,0,0,0,0,0,1,0
147.0,0,0,0,0,5,0,29,38,4,4,...,1,0,0,0,0,0,0,0,0,0
148.0,0,0,0,0,4,0,0,31,0,3,...,1,0,0,0,0,0,0,0,0,0
151.0,2,0,0,0,0,0,0,56,0,0,...,5,0,1,1,0,0,0,0,0,0
152.0,0,0,0,0,0,0,0,30,1,1,...,4,0,2,0,0,0,0,0,0,0
154.0,0,0,0,0,0,0,0,48,1,8,...,0,0,2,0,3,0,0,0,0,0
155.0,0,0,0,0,0,0,4,64,0,4,...,0,0,1,0,1,0,0,0,0,0
162.0,0,0,0,0,0,0,0,2,0,3,...,92,0,1,0,0,1,0,0,0,0
170.0,3,0,0,0,1,0,11,31,0,3,...,0,45,1,0,1,0,1,0,1,0
186.9,1,0,0,0,2,0,2,54,0,0,...,0,0,34,0,0,0,0,0,0,0
198.0,4,0,0,1,2,1,0,0,0,5,...,1,0,0,85,0,0,0,0,0,0
213.9,2,0,0,0,3,0,0,48,1,3,...,1,0,1,1,36,0,1,0,0,0
218.0,0,0,0,0,0,0,0,53,1,10,...,0,0,0,0,0,32,0,0,0,0
240.2,1,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,94,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,5,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [288]:
eval_result100.index = eval_result100.index + 1
eval_result100

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.900000,0.900000,0.100000,0.008723,0.803571,0.900000,0.849057,0.196429,0.100000,0.514183
2,7.1,0.760000,0.760000,0.240000,0.000400,0.987013,0.760000,0.858757,0.012987,0.240000,0.529657
3,18.9,0.870000,0.870000,0.130000,0.000000,1.000000,0.870000,0.930481,0.000000,0.130000,0.618366
4,32.1,0.960000,0.960000,0.040000,0.001597,0.960000,0.960000,0.960000,0.040000,0.040000,0.521246
5,41.0,0.810000,0.810000,0.190000,0.009509,0.771429,0.810000,0.790244,0.228571,0.190000,0.500236
6,98.9,0.830000,0.830000,0.170000,0.001996,0.943182,0.830000,0.882979,0.056818,0.170000,0.613544
7,104.1,0.760000,0.760000,0.240000,0.029126,0.503311,0.760000,0.605578,0.496689,0.240000,0.474910
8,111.0,0.800000,0.800000,0.200000,0.163320,0.140845,0.800000,0.239521,0.859155,0.200000,0.492241
9,128.0,0.860000,0.860000,0.140000,0.007543,0.819048,0.860000,0.839024,0.180952,0.140000,0.500164
10,129.0,0.930000,0.930000,0.070000,0.028749,0.556886,0.930000,0.696629,0.443114,0.070000,0.722491
11,146.0,0.190000,0.190000,0.810000,0.003190,0.703704,0.190000,0.299213,0.296296,0.810000,0.315727
12,147.0,0.610000,0.610000,0.390000,0.010685,0.693182,0.610000,0.648936,0.306818,0.390000,0.270238
13,150.0,0.320000,0.320000,0.680000,0.000000,1.000000,0.320000,0.484848,0.000000,0.680000,0.315465
14,151.0,0.610000,0.610000,0.390000,0.000400,0.983871,0.610000,0.753086,0.016129,0.390000,0.255958
15,153.0,0.370000,0.370000,0.630000,0.000799,0.948718,0.370000,0.532374,0.051282,0.630000,0.315490
16,154.0,0.260000,0.260000,0.740000,0.001199,0.896552,0.260000,0.403101,0.103448,0.740000,0.387762
17,161.0,0.920000,0.920000,0.080000,0.007543,0.828829,0.920000,0.872038,0.171171,0.080000,0.563603
18,169.0,0.450000,0.450000,0.550000,0.000000,1.000000,0.450000,0.620690,0.000000,0.550000,0.235419
19,185.9,0.340000,0.340000,0.660000,0.007937,0.629630,0.340000,0.441558,0.370370,0.660000,0.315465
20,197.0,0.850000,0.850000,0.150000,0.000799,0.977011,0.850000,0.909091,0.022989,0.150000,0.910512
21,212.9,0.360000,0.360000,0.640000,0.002792,0.837209,0.360000,0.503497,0.162791,0.640000,0.315471
22,217.0,0.320000,0.320000,0.680000,0.000400,0.969697,0.320000,0.481203,0.030303,0.680000,0.315465
23,239.2,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.511202
24,248.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001597,0.959184,0.940000,0.949495,0.040816,0.060000,0.546813
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,1.673642
27,average,0.688846,0.688846,0.311154,0.011135,0.841613,0.688846,0.710772,0.158387,0.311154,0.489818

In [289]:
Confusion_df100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier100.csv')
eval_result100.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier100.csv', index=False)

## LOAD & APPLY MODEL dTOP110fi

In [290]:
# test_data110['tp_ICD_cl0'] = le.transform(test_data110['tp_ICD_cl0'])

In [291]:
# Separate features and tp_ICD_cl0 variable for test_data110
X_test110 = test_data110.drop(labels=['tp_ICD_cl0'], axis=1)
y_test110 = test_data110['tp_ICD_cl0']

In [292]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier110.pkl', 'rb') as f:
    knn_110 = pickle.load(f)

### EVALUATION & SAVE

In [293]:
prob110 = knn_110.predict_proba(X_test110)
classes110 = knn_110.classes_

y_pred110, data_top_5 = get_predictions(prob110, classes110, threshold, 10, np.array(y_test110), le)

Confusion_df110 = pd.DataFrame(confusion_matrix(np.array(y_test110), y_pred110))
Confusion_df110.index, Confusion_df110.columns = le.inverse_transform(classes110), le.inverse_transform(classes110)

eval_result110 = calculate_evaluation_metrics(Confusion_df=Confusion_df110)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [294]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.190476,18.9,0.142857,150.0,0.142857,161.0,0.142857,98.9,0.095238
2,185.9,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
3,248.0,248.0,0.523810,147.0,0.095238,197.0,0.095238,98.9,0.047619,104.1,0.047619
4,146.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
5,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2597,18.9,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2598,217.0,98.9,0.238095,7.1,0.190476,147.0,0.190476,104.1,0.095238,151.0,0.095238
2599,104.1,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2600,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN

In [295]:
Confusion_df110.index = Confusion_df110.index + 1
Confusion_df110
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,1,3,2,3,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,75,0,0,2,4,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
19.9,0,0,84,2,5,2,0,1,0,0,...,2,0,0,0,0,0,0,0,0,0
33.1,0,0,0,91,0,4,3,0,1,1,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,0,0,80,0,0,2,0,0,...,2,0,0,0,1,0,3,0,0,0
99.9,0,0,0,0,0,84,0,1,0,1,...,2,0,0,0,4,0,0,0,0,0
105.1,0,0,0,0,4,2,45,3,6,0,...,0,0,0,0,0,0,0,0,0,0
112.0,1,0,0,0,4,2,0,39,1,0,...,0,0,0,0,6,0,0,0,0,0
129.0,0,0,0,0,1,0,0,1,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,1,0,0,0,0,0,1,0,32,...,0,0,0,0,0,0,0,1,0,0
147.0,0,0,0,0,3,0,2,1,0,0,...,0,0,0,0,0,0,0,0,0,0
148.0,0,0,0,0,1,1,0,0,0,0,...,1,0,0,0,3,0,0,0,0,0
151.0,2,0,0,0,0,0,0,0,0,0,...,4,0,0,0,4,0,0,0,0,0
152.0,1,0,1,0,0,0,1,0,1,0,...,2,0,0,0,5,0,0,0,0,0
154.0,0,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,0,0,0,0,0,0,4,0,0,3,...,0,0,0,0,5,0,0,0,0,0
162.0,0,0,0,0,0,0,0,2,0,0,...,91,0,1,0,2,0,1,0,0,0
170.0,2,0,0,0,0,3,3,3,0,0,...,0,39,1,0,3,0,1,1,0,0
186.9,1,0,0,0,5,5,5,0,0,1,...,0,0,76,0,4,0,0,0,0,0
198.0,3,0,0,0,3,1,4,0,0,0,...,1,0,2,40,5,0,0,0,0,0
213.9,1,0,1,0,4,0,2,0,1,0,...,0,0,1,0,39,0,0,0,0,0
218.0,0,0,0,0,0,1,1,3,1,0,...,0,0,0,0,0,42,0,0,0,0
240.2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,97,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [296]:
eval_result110.index = eval_result110.index + 1
eval_result110

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.004381,0.885417,0.850000,0.867347,0.114583,0.150000,0.509438
2,7.1,0.750000,0.750000,0.250000,0.000400,0.986842,0.750000,0.852273,0.013158,0.250000,0.429667
3,18.9,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.661362
4,32.1,0.910000,0.910000,0.090000,0.001597,0.957895,0.910000,0.933333,0.042105,0.090000,0.613064
5,41.0,0.800000,0.800000,0.200000,0.013028,0.707965,0.800000,0.751174,0.292035,0.200000,0.417012
6,98.9,0.840000,0.840000,0.160000,0.011858,0.736842,0.840000,0.785047,0.263158,0.160000,0.447257
7,104.1,0.450000,0.450000,0.550000,0.010685,0.625000,0.450000,0.523256,0.375000,0.550000,0.334937
8,111.0,0.390000,0.390000,0.610000,0.008723,0.639344,0.390000,0.484472,0.360656,0.610000,0.263233
9,128.0,0.860000,0.860000,0.140000,0.005569,0.860000,0.860000,0.860000,0.140000,0.140000,0.416707
10,129.0,0.320000,0.320000,0.680000,0.002394,0.842105,0.320000,0.463768,0.157895,0.680000,0.458157
11,146.0,0.560000,0.560000,0.440000,0.002394,0.903226,0.560000,0.691358,0.096774,0.440000,0.278943
12,147.0,0.630000,0.630000,0.370000,0.023819,0.508065,0.630000,0.562500,0.491935,0.370000,0.270238
13,150.0,0.800000,0.800000,0.200000,0.151104,0.152381,0.800000,0.256000,0.847619,0.200000,0.450707
14,151.0,0.580000,0.580000,0.420000,0.001597,0.935484,0.580000,0.716049,0.064516,0.420000,0.255958
15,153.0,0.930000,0.930000,0.070000,0.005964,0.861111,0.930000,0.894231,0.138889,0.070000,0.488298
16,154.0,0.840000,0.840000,0.160000,0.000000,1.000000,0.840000,0.913043,0.000000,0.160000,0.485663
17,161.0,0.910000,0.910000,0.090000,0.005569,0.866667,0.910000,0.887805,0.133333,0.090000,0.596790
18,169.0,0.390000,0.390000,0.610000,0.000000,1.000000,0.390000,0.561151,0.000000,0.610000,0.235854
19,185.9,0.760000,0.760000,0.240000,0.001996,0.938272,0.760000,0.839779,0.061728,0.240000,0.703413
20,197.0,0.400000,0.400000,0.600000,0.000000,1.000000,0.400000,0.571429,0.000000,0.600000,0.286199
21,212.9,0.390000,0.390000,0.610000,0.016909,0.475610,0.390000,0.428571,0.524390,0.610000,0.262878
22,217.0,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,0.262758
23,239.2,0.970000,0.970000,0.030000,0.001996,0.950980,0.970000,0.960396,0.049020,0.030000,1.158734
24,248.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000400,0.989474,0.940000,0.964103,0.010526,0.060000,0.444186
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,0.724098
27,average,0.710769,0.710769,0.289231,0.010476,0.837319,0.710769,0.739286,0.162681,0.289231,0.440598

In [297]:
Confusion_df110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier110.csv')
eval_result110.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier110.csv', index=False)

## LOAD & APPLY MODEL dTOP120fi

In [298]:
# test_data120['tp_ICD_cl0'] = le.transform(test_data120['tp_ICD_cl0'])

In [299]:
# Separate features and tp_ICD_cl0 variable for test_data120
X_test120 = test_data120.drop(labels=['tp_ICD_cl0'], axis=1)
y_test120 = test_data120['tp_ICD_cl0']

In [300]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier120.pkl', 'rb') as f:
    knn_120 = pickle.load(f)

### EVALUATION & SAVE

In [301]:
prob120 = knn_120.predict_proba(X_test120)
classes120 = knn_120.classes_

y_pred120, data_top_5 = get_predictions(prob120, classes120, threshold, 10, np.array(y_test120), le)

Confusion_df120 = pd.DataFrame(confusion_matrix(np.array(y_test120), y_pred120))
Confusion_df120.index, Confusion_df120.columns = le.inverse_transform(classes120), le.inverse_transform(classes120)

eval_result120 = calculate_evaluation_metrics(Confusion_df=Confusion_df120)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [302]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.190476,18.9,0.142857,150.0,0.142857,161.0,0.142857,98.9,0.095238
2,185.9,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
3,248.0,248.0,0.523810,147.0,0.095238,197.0,0.095238,98.9,0.047619,104.1,0.047619
4,146.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
5,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2597,18.9,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2598,217.0,98.9,0.238095,7.1,0.190476,147.0,0.190476,104.1,0.095238,151.0,0.095238
2599,104.1,150.0,0.142857,154.0,0.142857,32.1,0.095238,153.0,0.095238,185.9,0.095238
2600,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN

In [303]:
Confusion_df120.index = Confusion_df120.index + 1
Confusion_df120
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,85,0,0,0,1,3,2,3,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,75,0,0,2,4,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
19.9,0,1,84,2,5,1,0,1,0,0,...,2,0,0,0,0,0,0,0,0,0
33.1,0,0,0,91,0,4,3,1,1,0,...,0,0,0,0,0,0,0,0,0,0
42.0,0,0,0,0,80,0,0,2,0,0,...,2,0,0,0,1,0,3,0,0,0
99.9,0,0,0,0,0,84,0,1,0,1,...,2,0,0,0,4,0,0,0,0,0
105.1,0,0,0,0,4,2,45,3,6,0,...,0,0,0,0,0,0,0,0,0,0
112.0,0,0,0,0,4,2,0,40,1,0,...,0,0,0,0,6,0,0,0,0,0
129.0,0,0,0,0,1,0,0,1,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,1,0,0,0,0,0,1,0,32,...,0,0,0,0,0,0,0,1,0,0
147.0,0,0,0,0,3,0,2,1,0,0,...,0,0,0,0,0,0,0,0,0,0
148.0,0,0,0,0,1,1,0,0,0,0,...,1,0,0,0,3,0,0,0,0,0
151.0,2,0,0,0,0,0,0,0,0,0,...,4,0,0,0,4,0,0,0,0,0
152.0,0,0,1,0,0,0,1,0,1,0,...,2,0,0,0,5,0,0,0,0,0
154.0,0,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,0,0,0,0,0,0,4,0,0,3,...,0,0,0,0,5,0,0,0,0,0
162.0,0,0,0,0,0,0,0,2,0,0,...,91,0,1,0,2,0,1,0,0,0
170.0,3,0,0,0,0,3,3,3,0,0,...,0,38,1,0,3,0,1,1,0,0
186.9,1,0,0,0,4,5,5,0,0,1,...,1,0,76,0,4,0,0,0,0,0
198.0,3,0,0,0,3,1,4,0,0,0,...,1,0,0,40,5,0,0,0,0,0
213.9,1,0,1,0,4,0,2,0,1,0,...,0,0,1,0,39,0,0,0,0,0
218.0,0,0,0,0,0,1,1,3,1,0,...,0,0,0,0,0,42,0,0,0,0
240.2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,97,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [304]:
eval_result120.index = eval_result120.index + 1
eval_result120

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.850000,0.850000,0.150000,0.003984,0.894737,0.850000,0.871795,0.105263,0.150000,0.509438
2,7.1,0.750000,0.750000,0.250000,0.000799,0.974026,0.750000,0.847458,0.025974,0.250000,0.429667
3,18.9,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.671769
4,32.1,0.910000,0.910000,0.090000,0.001597,0.957895,0.910000,0.933333,0.042105,0.090000,0.615129
5,41.0,0.800000,0.800000,0.200000,0.012638,0.714286,0.800000,0.754717,0.285714,0.200000,0.417012
6,98.9,0.840000,0.840000,0.160000,0.011467,0.743363,0.840000,0.788732,0.256637,0.160000,0.447257
7,104.1,0.450000,0.450000,0.550000,0.010685,0.625000,0.450000,0.523256,0.375000,0.550000,0.334937
8,111.0,0.400000,0.400000,0.600000,0.009116,0.634921,0.400000,0.490798,0.365079,0.600000,0.263814
9,128.0,0.860000,0.860000,0.140000,0.005569,0.860000,0.860000,0.860000,0.140000,0.140000,0.416707
10,129.0,0.320000,0.320000,0.680000,0.001996,0.864865,0.320000,0.467153,0.135135,0.680000,0.458157
11,146.0,0.560000,0.560000,0.440000,0.002394,0.903226,0.560000,0.691358,0.096774,0.440000,0.278943
12,147.0,0.630000,0.630000,0.370000,0.023819,0.508065,0.630000,0.562500,0.491935,0.370000,0.270238
13,150.0,0.800000,0.800000,0.200000,0.151104,0.152381,0.800000,0.256000,0.847619,0.200000,0.450707
14,151.0,0.590000,0.590000,0.410000,0.001597,0.936508,0.590000,0.723926,0.063492,0.410000,0.255958
15,153.0,0.930000,0.930000,0.070000,0.005964,0.861111,0.930000,0.894231,0.138889,0.070000,0.488298
16,154.0,0.840000,0.840000,0.160000,0.000799,0.976744,0.840000,0.903226,0.023256,0.160000,0.485663
17,161.0,0.910000,0.910000,0.090000,0.005964,0.858491,0.910000,0.883495,0.141509,0.090000,0.596790
18,169.0,0.380000,0.380000,0.620000,0.000000,1.000000,0.380000,0.550725,0.000000,0.620000,0.236296
19,185.9,0.760000,0.760000,0.240000,0.001199,0.962025,0.760000,0.849162,0.037975,0.240000,0.676556
20,197.0,0.400000,0.400000,0.600000,0.000000,1.000000,0.400000,0.571429,0.000000,0.600000,0.286199
21,212.9,0.390000,0.390000,0.610000,0.016909,0.475610,0.390000,0.428571,0.524390,0.610000,0.262878
22,217.0,0.420000,0.420000,0.580000,0.000000,1.000000,0.420000,0.591549,0.000000,0.580000,0.262758
23,239.2,0.970000,0.970000,0.030000,0.001996,0.950980,0.970000,0.960396,0.049020,0.030000,1.158734
24,248.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000400,0.989474,0.940000,0.964103,0.010526,0.060000,0.444186
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,0.724098
27,average,0.711154,0.711154,0.288846,0.010461,0.838128,0.711154,0.739643,0.161872,0.288846,0.440084

In [305]:
Confusion_df120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier120.csv')
eval_result120.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier120.csv', index=False)

## LOAD & APPLY MODEL dTOP130fi

In [306]:
# test_data130['tp_ICD_cl0'] = le.transform(test_data130['tp_ICD_cl0'])

In [307]:
# Separate features and tp_ICD_cl0 variable for test_data130
X_test130 = test_data130.drop(labels=['tp_ICD_cl0'], axis=1)
y_test130 = test_data130['tp_ICD_cl0']

In [308]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier130.pkl', 'rb') as f:
    knn_130 = pickle.load(f)

### EVALUATION & SAVE

In [309]:
prob130 = knn_130.predict_proba(X_test130)
classes130 = knn_130.classes_

y_pred130, data_top_5 = get_predictions(prob130, classes130, threshold, 10, np.array(y_test130), le)

Confusion_df130 = pd.DataFrame(confusion_matrix(np.array(y_test130), y_pred130))
Confusion_df130.index, Confusion_df130.columns = le.inverse_transform(classes130), le.inverse_transform(classes130)

eval_result130 = calculate_evaluation_metrics(Confusion_df=Confusion_df130)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [310]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,150.0,0.190476,18.9,0.142857,41.0,0.142857,161.0,0.142857,104.1,0.047619
2,185.9,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
3,248.0,248.0,0.523810,147.0,0.095238,197.0,0.095238,98.9,0.047619,104.1,0.047619
4,146.0,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
5,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
2597,18.9,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
2598,217.0,98.9,0.285714,7.1,0.190476,151.0,0.142857,147.0,0.095238,104.1,0.047619
2599,104.1,150.0,0.142857,5.0,0.095238,32.1,0.095238,154.0,0.095238,185.9,0.095238
2600,251.0,248.0,0.333333,249.0,0.333333,251.0,0.333333,NaN,NaN,NaN,NaN

In [311]:
Confusion_df130.index = Confusion_df130.index + 1
Confusion_df130
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,84,0,0,3,2,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,75,1,2,1,2,0,0,1,0,...,1,0,2,0,0,0,0,1,0,0
19.9,0,0,84,2,4,2,0,0,0,0,...,3,0,1,0,0,1,0,0,0,0
33.1,0,0,4,92,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
42.0,0,0,1,1,81,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
99.9,2,0,4,0,1,79,0,0,0,0,...,2,0,0,1,0,0,0,0,0,0
105.1,1,0,0,2,3,0,38,2,6,0,...,1,0,0,0,0,0,0,0,0,0
112.0,1,0,7,0,2,1,0,32,1,0,...,0,0,0,2,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,1,86,0,...,0,0,0,1,0,0,0,0,0,0
130.0,0,1,0,0,0,0,0,0,0,97,...,0,0,1,0,0,0,0,1,0,0
147.0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
148.0,0,0,5,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
151.0,2,0,1,2,2,0,0,1,0,0,...,4,0,1,0,0,0,0,0,0,0
152.0,1,0,5,0,0,0,0,0,1,0,...,3,0,2,0,0,0,0,0,0,0
154.0,0,0,5,0,0,0,0,0,1,0,...,0,0,2,3,0,0,0,0,0,0
155.0,0,0,5,4,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
162.0,1,0,2,0,0,0,0,0,0,1,...,91,0,2,0,0,0,0,0,0,0
170.0,5,0,0,4,0,0,0,0,0,0,...,0,40,1,1,0,0,1,1,0,0
186.9,1,0,5,4,2,0,0,0,6,0,...,0,0,71,0,0,0,0,0,0,0
198.0,3,0,5,0,2,0,0,0,0,0,...,2,0,0,21,0,0,0,0,0,0
213.9,1,0,1,1,1,0,0,0,1,0,...,1,0,2,0,37,0,0,0,0,0
218.0,0,0,0,1,0,0,0,3,1,0,...,0,0,0,0,0,43,0,0,0,0
240.2,1,0,7,1,0,0,0,0,0,0,...,0,0,0,0,0,0,12,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,0,0,2,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,95

In [312]:
eval_result130.index = eval_result130.index + 1
eval_result130

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.840000,0.840000,0.160000,0.007543,0.815534,0.840000,0.827586,0.184466,0.160000,0.487626
2,7.1,0.750000,0.750000,0.250000,0.000400,0.986842,0.750000,0.852273,0.013158,0.250000,0.429295
3,18.9,0.840000,0.840000,0.160000,0.023438,0.583333,0.840000,0.688525,0.416667,0.160000,0.659859
4,32.1,0.920000,0.920000,0.080000,0.011467,0.760331,0.920000,0.832579,0.239669,0.080000,0.813648
5,41.0,0.810000,0.810000,0.190000,0.008330,0.794118,0.810000,0.801980,0.205882,0.190000,0.417224
6,98.9,0.790000,0.790000,0.210000,0.001996,0.940476,0.790000,0.858696,0.059524,0.210000,0.585538
7,104.1,0.380000,0.380000,0.620000,0.000000,1.000000,0.380000,0.550725,0.000000,0.620000,0.298845
8,111.0,0.320000,0.320000,0.680000,0.003984,0.761905,0.320000,0.450704,0.238095,0.680000,0.262651
9,128.0,0.860000,0.860000,0.140000,0.007937,0.811321,0.860000,0.834951,0.188679,0.140000,0.416584
10,129.0,0.970000,0.970000,0.030000,0.000400,0.989796,0.970000,0.979798,0.010204,0.030000,1.404153
11,146.0,0.610000,0.610000,0.390000,0.003587,0.871429,0.610000,0.717647,0.128571,0.390000,0.278943
12,147.0,0.620000,0.620000,0.380000,0.030256,0.442857,0.620000,0.516667,0.557143,0.380000,0.270238
13,150.0,0.760000,0.760000,0.240000,0.157398,0.139963,0.760000,0.236392,0.860037,0.240000,0.461191
14,151.0,0.570000,0.570000,0.430000,0.002394,0.904762,0.570000,0.699387,0.095238,0.430000,0.255958
15,153.0,0.890000,0.890000,0.110000,0.014196,0.712000,0.890000,0.791111,0.288000,0.110000,0.751499
16,154.0,0.860000,0.860000,0.140000,0.001199,0.966292,0.860000,0.910053,0.033708,0.140000,0.815852
17,161.0,0.910000,0.910000,0.090000,0.007543,0.827273,0.910000,0.866667,0.172727,0.090000,0.957217
18,169.0,0.400000,0.400000,0.600000,0.000000,1.000000,0.400000,0.571429,0.000000,0.600000,0.235632
19,185.9,0.710000,0.710000,0.290000,0.006359,0.816092,0.710000,0.759358,0.183908,0.290000,0.683418
20,197.0,0.210000,0.210000,0.790000,0.003587,0.700000,0.210000,0.323077,0.300000,0.790000,0.262650
21,212.9,0.370000,0.370000,0.630000,0.000000,1.000000,0.370000,0.540146,0.000000,0.630000,0.262664
22,217.0,0.430000,0.430000,0.570000,0.001199,0.934783,0.430000,0.589041,0.065217,0.570000,0.262865
23,239.2,0.120000,0.120000,0.880000,0.000400,0.923077,0.120000,0.212389,0.076923,0.880000,0.361895
24,248.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000400,0.989474,0.940000,0.964103,0.010526,0.060000,0.444186
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,0.989729
27,average,0.685769,0.685769,0.314231,0.011354,0.832405,0.685769,0.705187,0.167595,0.314231,0.502668

In [313]:
Confusion_df130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier130.csv')
eval_result130.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier130.csv', index=False)

## LOAD & APPLY MODEL dTOP140fi

In [314]:
# test_data140['tp_ICD_cl0'] = le.transform(test_data140['tp_ICD_cl0'])

In [315]:
# Separate features and tp_ICD_cl0 variable for test_data140
X_test140 = test_data140.drop(labels=['tp_ICD_cl0'], axis=1)
y_test140 = test_data140['tp_ICD_cl0']

In [316]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier140.pkl', 'rb') as f:
    knn_140 = pickle.load(f)

### EVALUATION & SAVE

In [317]:
prob140 = knn_140.predict_proba(X_test140)
classes140 = knn_140.classes_

y_pred140, data_top_5 = get_predictions(prob140, classes140, threshold, 10, np.array(y_test140), le)

Confusion_df140 = pd.DataFrame(confusion_matrix(np.array(y_test140), y_pred140))
Confusion_df140.index, Confusion_df140.columns = le.inverse_transform(classes140), le.inverse_transform(classes140)

eval_result140 = calculate_evaluation_metrics(Confusion_df=Confusion_df140)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [318]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,161.0,0.380952,98.9,0.142857,169.0,0.095238,197.0,0.095238,18.9,0.047619
2,185.9,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
3,248.0,248.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,146.0,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
5,251.0,248.0,0.476190,251.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
2597,18.9,154.0,0.142857,111.0,0.095238,129.0,0.095238,150.0,0.095238,185.9,0.095238
2598,217.0,98.9,0.428571,7.1,0.214286,147.0,0.142857,150.0,0.071429,185.9,0.071429
2599,104.1,104.1,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2600,251.0,248.0,0.476190,251.0,0.285714,249.0,0.238095,NaN,NaN,NaN,NaN

In [319]:
Confusion_df140.index = Confusion_df140.index + 1
Confusion_df140
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,33,0,4,1,1,0,0,0,0,1,...,1,0,0,5,2,0,0,0,0,0
8.1,0,51,0,0,2,2,0,0,1,0,...,0,0,0,12,0,0,0,1,0,0
19.9,2,0,85,1,4,1,1,0,0,0,...,1,0,0,2,0,0,0,0,0,0
33.1,0,0,10,84,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
42.0,2,1,2,0,73,0,0,0,0,2,...,5,0,0,0,1,0,0,0,0,0
99.9,0,2,6,1,0,81,2,0,0,0,...,0,0,0,2,0,0,0,0,0,0
105.1,0,0,0,0,1,0,30,2,6,0,...,1,0,2,15,3,0,0,0,0,0
112.0,1,0,0,0,0,1,0,85,0,0,...,6,0,1,0,0,0,0,0,0,0
129.0,0,0,0,0,0,0,0,0,86,1,...,0,0,0,2,0,0,0,0,0,0
130.0,1,1,2,0,0,0,0,2,0,89,...,0,1,0,0,3,0,0,1,0,0
147.0,0,1,0,0,0,0,0,1,4,0,...,2,0,0,0,0,0,0,0,0,0
148.0,0,1,0,0,0,0,0,0,0,0,...,4,0,2,0,1,0,0,0,0,0
151.0,1,0,4,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
152.0,1,0,1,0,0,2,2,0,1,0,...,1,0,0,0,1,0,0,0,0,0
154.0,1,0,5,0,0,0,0,0,1,0,...,0,0,0,0,3,0,0,0,0,0
155.0,0,0,5,0,0,0,1,0,0,0,...,0,0,0,4,4,0,0,0,0,0
162.0,1,1,3,3,4,0,0,3,0,0,...,76,0,0,0,0,0,0,0,0,0
170.0,3,1,3,1,3,0,0,0,0,0,...,6,30,0,11,3,1,1,1,0,0
186.9,1,0,0,0,1,1,0,0,0,0,...,2,0,79,2,4,0,1,0,0,0
198.0,1,0,6,1,2,4,0,0,0,0,...,3,0,1,35,0,0,0,0,0,0
213.9,2,0,2,0,0,0,1,0,6,0,...,1,0,1,0,35,0,0,0,0,0
218.0,0,0,8,0,0,1,0,0,1,2,...,0,0,0,1,0,27,0,0,0,0
240.2,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,1,0,96,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,5,0,0,0,0,94,0
252.0,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,2,94

In [320]:
eval_result140.index = eval_result140.index + 1
eval_result140

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.330000,0.330000,0.670000,0.006754,0.660000,0.330000,0.440000,0.340000,0.670000,0.244657
2,7.1,0.510000,0.510000,0.490000,0.003190,0.864407,0.510000,0.641509,0.135593,0.490000,0.630930
3,18.9,0.850000,0.850000,0.150000,0.024200,0.578231,0.850000,0.688259,0.421769,0.150000,0.817385
4,32.1,0.840000,0.840000,0.160000,0.003587,0.903226,0.840000,0.870466,0.096774,0.160000,0.791970
5,41.0,0.730000,0.730000,0.270000,0.007543,0.793478,0.730000,0.760417,0.206522,0.270000,0.392719
6,98.9,0.810000,0.810000,0.190000,0.005569,0.852632,0.810000,0.830769,0.147368,0.190000,0.815973
7,104.1,0.300000,0.300000,0.700000,0.002792,0.810811,0.300000,0.437956,0.189189,0.700000,0.246042
8,111.0,0.850000,0.850000,0.150000,0.003587,0.904255,0.850000,0.876289,0.095745,0.150000,0.453363
9,128.0,0.860000,0.860000,0.140000,0.008330,0.803738,0.860000,0.830918,0.196262,0.140000,0.388002
10,129.0,0.890000,0.890000,0.110000,0.002394,0.936842,0.890000,0.912821,0.063158,0.110000,0.764265
11,146.0,0.910000,0.910000,0.090000,0.016909,0.679104,0.910000,0.777778,0.320896,0.090000,0.554207
12,147.0,0.610000,0.610000,0.390000,0.005964,0.802632,0.610000,0.693182,0.197368,0.390000,0.270238
13,150.0,0.870000,0.870000,0.130000,0.001199,0.966667,0.870000,0.915789,0.033333,0.130000,0.881319
14,151.0,0.610000,0.610000,0.390000,0.005569,0.813333,0.610000,0.697143,0.186667,0.390000,0.255958
15,153.0,0.400000,0.400000,0.600000,0.005569,0.740741,0.400000,0.519481,0.259259,0.600000,0.245023
16,154.0,0.830000,0.830000,0.170000,0.142073,0.167002,0.830000,0.278057,0.832998,0.170000,0.681005
17,161.0,0.760000,0.760000,0.240000,0.013807,0.684685,0.760000,0.720379,0.315315,0.240000,0.708223
18,169.0,0.300000,0.300000,0.700000,0.000400,0.967742,0.300000,0.458015,0.032258,0.700000,0.275458
19,185.9,0.790000,0.790000,0.210000,0.002792,0.918605,0.790000,0.849462,0.081395,0.210000,0.466470
20,197.0,0.350000,0.350000,0.650000,0.023819,0.364583,0.350000,0.357143,0.635417,0.650000,0.245220
21,212.9,0.350000,0.350000,0.650000,0.010293,0.573770,0.350000,0.434783,0.426230,0.650000,0.244685
22,217.0,0.270000,0.270000,0.730000,0.000799,0.931034,0.270000,0.418605,0.068966,0.730000,0.244651
23,239.2,0.960000,0.960000,0.040000,0.000799,0.979592,0.960000,0.969697,0.020408,0.040000,1.129837
24,248.0,1.000000,1.000000,0.000000,0.001199,0.970874,1.000000,0.985222,0.029126,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.000799,0.979167,0.940000,0.959184,0.020833,0.060000,0.374948
26,251.0,0.940000,0.940000,0.060000,0.000000,1.000000,0.940000,0.969072,0.000000,0.060000,0.609677
27,average,0.686923,0.686923,0.313077,0.011536,0.794121,0.686923,0.703554,0.205879,0.313077,0.489701

In [321]:
Confusion_df140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier140.csv')
eval_result140.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier140.csv', index=False)

## LOAD & APPLY MODEL dTOP150fi

In [322]:
# test_data150['tp_ICD_cl0'] = le.transform(test_data150['tp_ICD_cl0'])

In [323]:
# Separate features and tp_ICD_cl0 variable for test_data150
X_test150 = test_data150.drop(labels=['tp_ICD_cl0'], axis=1)
y_test150 = test_data150['tp_ICD_cl0']

In [324]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier150.pkl', 'rb') as f:
    knn_150 = pickle.load(f)

### EVALUATION & SAVE

In [325]:
prob150 = knn_150.predict_proba(X_test150)
classes150 = knn_150.classes_

y_pred150, data_top_5 = get_predictions(prob150, classes150, threshold, 10, np.array(y_test150), le)

Confusion_df150 = pd.DataFrame(confusion_matrix(np.array(y_test150), y_pred150))
Confusion_df150.index, Confusion_df150.columns = le.inverse_transform(classes150), le.inverse_transform(classes150)

eval_result150 = calculate_evaluation_metrics(Confusion_df=Confusion_df150)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [326]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,41.0,0.20,161.0,0.20,146.0,0.10,212.9,0.1,7.1,0.05
2,185.9,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.1,185.9,0.10
3,248.0,248.0,0.50,197.0,0.15,104.1,0.10,151.0,0.1,98.9,0.05
4,146.0,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.1,185.9,0.10
5,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.1,185.9,0.10
2597,18.9,111.0,0.25,129.0,0.10,150.0,0.10,154.0,0.1,185.9,0.10
2598,217.0,98.9,0.30,7.1,0.20,147.0,0.15,151.0,0.1,104.1,0.05
2599,104.1,154.0,0.20,111.0,0.15,32.1,0.10,104.1,0.1,129.0,0.10
2600,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN

In [327]:
Confusion_df150.index = Confusion_df150.index + 1
Confusion_df150
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,38,3,1,0,0,0,1,51,0,0,...,0,0,0,0,0,0,0,0,0,0
8.1,0,79,1,0,1,0,0,2,0,0,...,1,0,0,0,0,0,0,0,1,0
19.9,0,1,86,1,2,0,0,2,0,1,...,2,0,0,0,0,1,0,0,0,0
33.1,0,0,10,84,0,0,1,2,1,0,...,1,0,0,0,0,1,0,0,0,0
42.0,1,1,1,0,94,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99.9,0,4,4,0,1,79,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
105.1,0,0,0,0,0,0,50,46,0,0,...,2,0,0,0,0,0,0,0,0,0
112.0,1,1,7,0,2,0,0,87,0,0,...,0,0,0,2,0,0,0,0,0,0
129.0,0,0,0,0,0,1,0,11,86,0,...,0,0,0,0,0,0,0,0,0,0
130.0,0,4,6,0,0,0,0,1,0,88,...,0,0,0,0,0,0,0,0,1,0
147.0,0,1,0,0,2,1,0,41,4,0,...,0,0,0,1,0,0,0,0,0,0
148.0,0,1,5,0,1,0,0,31,0,0,...,0,0,0,0,0,0,0,0,0,0
151.0,1,2,5,1,0,0,0,0,0,0,...,3,1,0,0,0,0,0,0,0,0
152.0,1,0,5,0,8,0,0,31,1,0,...,3,0,0,0,0,0,0,0,0,0
154.0,0,0,0,0,0,0,0,49,1,0,...,0,0,0,0,0,0,0,0,0,0
155.0,2,0,5,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
162.0,0,0,0,3,2,0,0,3,0,0,...,90,0,1,0,0,0,0,0,0,0
170.0,3,2,0,1,3,1,0,34,0,0,...,1,41,1,0,0,0,1,0,1,0
186.9,1,0,1,0,4,0,0,0,6,0,...,0,0,84,1,0,0,0,0,0,0
198.0,4,0,5,0,1,0,0,45,0,0,...,1,0,0,42,0,0,0,0,0,0
213.9,1,1,2,1,1,0,0,47,6,0,...,1,0,1,0,37,0,0,0,0,0
218.0,0,1,1,0,0,0,0,52,1,0,...,0,0,0,1,0,42,0,0,0,0
240.2,0,1,1,1,0,0,0,78,0,0,...,0,0,0,0,0,0,18,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [328]:
eval_result150.index = eval_result150.index + 1
eval_result150

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.380000,0.380000,0.620000,0.006754,0.690909,0.380000,0.490323,0.309091,0.620000,0.315563
2,7.1,0.790000,0.790000,0.210000,0.009116,0.774510,0.790000,0.782178,0.225490,0.210000,0.428798
3,18.9,0.860000,0.860000,0.140000,0.024200,0.581081,0.860000,0.693548,0.418919,0.140000,0.781294
4,32.1,0.840000,0.840000,0.160000,0.003190,0.913043,0.840000,0.875000,0.086957,0.160000,0.792513
5,41.0,0.940000,0.940000,0.060000,0.011076,0.770492,0.940000,0.846847,0.229508,0.060000,1.077065
6,98.9,0.790000,0.790000,0.210000,0.001199,0.963415,0.790000,0.868132,0.036585,0.210000,0.648264
7,104.1,0.500000,0.500000,0.500000,0.000799,0.961538,0.500000,0.657895,0.038462,0.500000,0.339656
8,111.0,0.870000,0.870000,0.130000,0.174373,0.141463,0.870000,0.243357,0.858537,0.130000,0.806393
9,128.0,0.860000,0.860000,0.140000,0.008330,0.803738,0.860000,0.830918,0.196262,0.140000,0.500323
10,129.0,0.880000,0.880000,0.120000,0.000400,0.988764,0.880000,0.931217,0.011236,0.120000,0.875430
11,146.0,0.500000,0.500000,0.500000,0.003190,0.862069,0.500000,0.632911,0.137931,0.500000,0.279215
12,147.0,0.620000,0.620000,0.380000,0.030632,0.439716,0.620000,0.514523,0.560284,0.380000,0.270238
13,150.0,0.850000,0.850000,0.150000,0.000000,1.000000,0.850000,0.918919,0.000000,0.150000,0.831814
14,151.0,0.220000,0.220000,0.780000,0.001199,0.880000,0.220000,0.352000,0.120000,0.780000,0.330993
15,153.0,0.480000,0.480000,0.520000,0.003587,0.842105,0.480000,0.611465,0.157895,0.520000,0.334836
16,154.0,0.860000,0.860000,0.140000,0.003190,0.914894,0.860000,0.886598,0.085106,0.140000,0.812883
17,161.0,0.900000,0.900000,0.100000,0.005964,0.857143,0.900000,0.878049,0.142857,0.100000,0.740104
18,169.0,0.410000,0.410000,0.590000,0.000400,0.976190,0.410000,0.577465,0.023810,0.590000,0.236707
19,185.9,0.840000,0.840000,0.160000,0.001199,0.965517,0.840000,0.898396,0.034483,0.160000,0.558307
20,197.0,0.420000,0.420000,0.580000,0.002792,0.857143,0.420000,0.563758,0.142857,0.580000,0.318782
21,212.9,0.370000,0.370000,0.630000,0.000000,1.000000,0.370000,0.540146,0.000000,0.630000,0.315489
22,217.0,0.420000,0.420000,0.580000,0.000799,0.954545,0.420000,0.583333,0.045455,0.580000,0.315486
23,239.2,0.180000,0.180000,0.820000,0.000400,0.947368,0.180000,0.302521,0.052632,0.820000,0.345695
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.444186
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,1.595567
27,average,0.679615,0.679615,0.320385,0.011323,0.847878,0.679615,0.707815,0.152122,0.320385,0.549831

In [329]:
Confusion_df150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier150.csv')
eval_result150.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier150.csv', index=False)

## LOAD & APPLY MODEL dALLfi

In [330]:
# test_data353['tp_ICD_cl0'] = le.transform(test_data353['tp_ICD_cl0'])

In [331]:
# Separate features and tp_ICD_cl0 variable for test_data353
X_test353 = test_data353.drop(labels=['tp_ICD_cl0'], axis=1)
y_test353 = test_data353['tp_ICD_cl0']

In [332]:
# Load the variable from the file
with open('/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/knnclassifier353.pkl', 'rb') as f:
    knn_353 = pickle.load(f)

### EVALUATION & SAVE

In [333]:
prob353 = knn_353.predict_proba(X_test353)
classes353 = knn_353.classes_

y_pred353, data_top_5 = get_predictions(prob353, classes353, threshold, 10, np.array(y_test353), le)

Confusion_df353 = pd.DataFrame(confusion_matrix(np.array(y_test353), y_pred353))
Confusion_df353.index, Confusion_df353.columns = le.inverse_transform(classes353), le.inverse_transform(classes353)

eval_result353 = calculate_evaluation_metrics(Confusion_df=Confusion_df353)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)

In [334]:
data_top_5 = pd.DataFrame(data_top_5)
data_top_5.index = data_top_5.index + 1
data_top_5

,true_list,pred_code1,score1,pred_code2,score2,pred_code3,score3,pred_code4,score4,pred_code5,score5
1,151.0,146.0,0.15,161.0,0.15,41.0,0.10,104.1,0.10,150.0,0.10
2,185.9,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
3,248.0,248.0,0.50,151.0,0.10,197.0,0.10,7.1,0.05,32.1,0.05
4,146.0,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
5,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2596,150.0,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
2597,18.9,154.0,0.15,32.1,0.10,111.0,0.10,129.0,0.10,150.0,0.10
2598,217.0,98.9,0.35,7.1,0.20,146.0,0.15,147.0,0.10,104.1,0.05
2599,104.1,154.0,0.15,32.1,0.10,104.1,0.10,129.0,0.10,146.0,0.10
2600,251.0,249.0,0.45,248.0,0.40,251.0,0.15,NaN,NaN,NaN,NaN

In [335]:
Confusion_df353.index = Confusion_df353.index + 1
Confusion_df353
# column = predicted
# row = actual

,5.0,7.1,18.9,32.1,41.0,98.9,104.1,111.0,128.0,129.0,...,161.0,169.0,185.9,197.0,212.9,217.0,239.2,248.0,249.0,251.0
6.0,38,0,4,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8.1,1,54,0,0,1,0,0,0,1,0,...,0,1,0,0,0,0,2,0,1,0
19.9,1,1,88,1,1,1,0,0,0,1,...,2,1,0,0,0,0,0,0,0,0
33.1,0,0,0,94,0,0,1,0,1,2,...,1,0,0,0,0,1,0,0,0,0
42.0,1,0,1,0,79,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,0
99.9,0,0,4,1,0,83,1,0,1,0,...,0,0,0,0,0,0,2,0,0,0
105.1,0,0,0,0,3,0,32,0,0,0,...,5,0,0,0,0,0,2,0,0,0
112.0,2,0,6,0,0,1,2,65,1,5,...,2,0,0,0,0,0,1,0,0,0
129.0,0,0,0,0,0,0,0,0,86,0,...,0,0,0,1,0,0,0,0,0,0
130.0,0,1,6,0,0,0,0,0,0,88,...,0,0,0,0,0,0,3,0,1,0
147.0,0,0,0,0,0,1,0,1,4,0,...,2,0,0,0,0,0,0,0,0,0
148.0,0,1,5,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
151.0,1,3,5,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
152.0,1,0,5,0,0,0,0,0,1,1,...,9,0,0,0,0,0,1,0,0,0
154.0,0,0,5,0,0,0,0,0,1,3,...,0,0,0,0,0,0,0,0,0,0
155.0,2,0,10,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162.0,0,0,0,0,0,0,0,0,0,5,...,90,0,1,0,1,0,0,0,0,0
170.0,2,0,0,2,0,0,1,0,0,0,...,0,48,1,0,0,0,1,0,1,0
186.9,0,0,1,0,0,1,0,0,6,5,...,2,0,76,1,0,0,4,0,0,0
198.0,3,0,5,0,1,1,0,0,0,0,...,2,0,2,22,0,0,0,0,0,0
213.9,1,0,2,0,0,1,1,1,1,2,...,1,0,1,0,39,0,1,0,0,0
218.0,0,0,1,0,0,0,1,0,1,1,...,0,0,0,1,0,40,1,0,0,0
240.2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,99,0,0,0
249.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,100,0,0
250.0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,94,0
252.0,2,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,95

In [336]:
eval_result353.index = eval_result353.index + 1
eval_result353

,class,accuracy,hit_rate,error_rate,specificity,precision,recall,f1,type_1_error,type_2_error,ndcg
1,5.0,0.380000,0.380000,0.620000,0.006754,0.690909,0.380000,0.490323,0.309091,0.620000,0.244857
2,7.1,0.540000,0.540000,0.460000,0.002394,0.900000,0.540000,0.675000,0.100000,0.460000,0.630930
3,18.9,0.880000,0.880000,0.120000,0.024581,0.582781,0.880000,0.701195,0.417219,0.120000,0.995150
4,32.1,0.940000,0.940000,0.060000,0.001597,0.959184,0.940000,0.949495,0.040816,0.060000,0.596822
5,41.0,0.790000,0.790000,0.210000,0.002792,0.918605,0.790000,0.849462,0.081395,0.210000,0.389394
6,98.9,0.830000,0.830000,0.170000,0.002394,0.932584,0.830000,0.878307,0.067416,0.170000,0.547651
7,104.1,0.320000,0.320000,0.680000,0.003587,0.780488,0.320000,0.453901,0.219512,0.680000,0.250136
8,111.0,0.650000,0.650000,0.350000,0.000799,0.970149,0.650000,0.778443,0.029851,0.350000,0.429533
9,128.0,0.860000,0.860000,0.140000,0.007543,0.819048,0.860000,0.839024,0.180952,0.140000,0.388013
10,129.0,0.880000,0.880000,0.120000,0.010293,0.771930,0.880000,0.822430,0.228070,0.120000,0.779590
11,146.0,0.920000,0.920000,0.080000,0.007149,0.836364,0.920000,0.876190,0.163636,0.080000,0.521971
12,147.0,0.590000,0.590000,0.410000,0.039201,0.366460,0.590000,0.452107,0.633540,0.410000,0.270238
13,150.0,0.880000,0.880000,0.120000,0.000799,0.977778,0.880000,0.926316,0.022222,0.120000,0.913631
14,151.0,0.520000,0.520000,0.480000,0.002394,0.896552,0.520000,0.658228,0.103448,0.480000,0.255958
15,153.0,0.400000,0.400000,0.600000,0.004777,0.769231,0.400000,0.526316,0.230769,0.600000,0.245023
16,154.0,0.800000,0.800000,0.200000,0.141778,0.162272,0.800000,0.269815,0.837728,0.200000,0.790477
17,161.0,0.900000,0.900000,0.100000,0.011858,0.750000,0.900000,0.818182,0.250000,0.100000,0.479051
18,169.0,0.480000,0.480000,0.520000,0.000799,0.960000,0.480000,0.640000,0.040000,0.520000,0.235409
19,185.9,0.760000,0.760000,0.240000,0.001996,0.938272,0.760000,0.839779,0.061728,0.240000,0.530770
20,197.0,0.220000,0.220000,0.780000,0.001199,0.880000,0.220000,0.352000,0.120000,0.780000,0.244651
21,212.9,0.390000,0.390000,0.610000,0.000400,0.975000,0.390000,0.557143,0.025000,0.610000,0.244787
22,217.0,0.400000,0.400000,0.600000,0.000400,0.975610,0.400000,0.567376,0.024390,0.600000,0.244683
23,239.2,0.990000,0.990000,0.010000,0.008330,0.825000,0.990000,0.900000,0.175000,0.010000,0.000000
24,248.0,1.000000,1.000000,0.000000,0.000400,0.990099,1.000000,0.995025,0.009901,0.000000,0.000000
25,249.0,0.940000,0.940000,0.060000,0.001199,0.969072,0.940000,0.954315,0.030928,0.060000,0.444186
26,251.0,0.950000,0.950000,0.050000,0.000000,1.000000,0.950000,0.974359,0.000000,0.050000,1.595567
27,average,0.700385,0.700385,0.299615,0.010977,0.830669,0.700385,0.720951,0.169331,0.299615,0.471864

In [337]:
Confusion_df353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/confusion_test_knnclassifier353.csv')
eval_result353.to_csv(r'/content/drive/MyDrive/IF6099-TESIS/References/Bootcamp/Final Experiment/knn_single_jaccard/fv_3/data_with_lk@500/result_test_knnclassifier353.csv', index=False)